<?xml version="1.0"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<parent>
		<groupId>com.code.aon</groupId>
		<artifactId>aon.web.parent</artifactId>
		<version>6.24.2</version>
	</parent>
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.code.aon</groupId>
	<artifactId>aon-manager</artifactId>
	<packaging>war</packaging>
	<version>6.24.2</version>
	<description>AON WEB MANAGER</description>
	<name>AON WEB MANAGER</name>
	<build>
		<finalName>aon-manager</finalName>
		<plugins>
			<!-- Para construir el RPM -->
                       <plugin>
                                <groupId>org.codehaus.mojo</groupId>
                                <artifactId>rpm-maven-plugin</artifactId>
                       </plugin>
		</plugins>
	</build>
	<dependencies>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.rich.components</artifactId>
			<version>${pom.version}</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.resources</artifactId>
			<version>${pom.version}</version>
			<scope>compile</scope>
			<exclusions>
				<exclusion>
					<groupId>com.code.aon</groupId>
					<artifactId>aon.ui.dbutils</artifactId>
				</exclusion>
			</exclusions>				
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.config</artifactId>
			<version>${pom.version}</version>
			<scope>runtime</scope>
		</dependency>		
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.manager</artifactId>
			<version>${pom.version}</version>
			<scope>runtime</scope>
		</dependency>		
	</dependencies>
</project>
 
