bgcolor_color_fondo_pagina = #000000
font_fuente_texto_pagina = 2
size_tamano_texto_pagina = 12
color_color_texto_pagina = 
border_tamano_borde_pagina = 1
color_color_borde_pagina = #666666
img_imagen_fondo_pagina =

bgcolor_color_fondo_cabecera = 
font_fuente_texto_cabecera = 
size_tamano_texto_cabecera = 
color_color_texto_cabecera = 
border_tamano_borde_cabecera = 
color_color_borde_cabecera = 
img_imagen_fondo_cabecera =
img_mostrar_logo_cabecera = 

border_tamano_borde_imagen = 
color_color_borde_imagen =

bgcolor_color_fondo_titulo = 
font_fuente_texto_titulo =
size_tamano_texto_titulo = 14
color_color_texto_titulo = #1B1D1E
border_tamano_borde_titulo =
color_color_borde_titulo = 

bgcolor_color_fondo_menu = 
font_fuente_texto_menu =
size_tamano_texto_menu =
color_color_texto_menu = 	
color_color_texto_menu_hover = #ffffff
size_tamano_texto_menu_hover =
color_color_fondo_menu_hover = #C23B01
color_color_borde_menu_hover =
color_color_borde_menu = 
border_tamano_borde_menu = 
color_color_borde_menu =

bgcolor_color_fondo_contenido = 
font_fuente_texto_contenido =
size_tamano_texto_contenido=
color_color_texto_contenido =
color_color_borde_contenido = 
border_tamano_borde_contenido = 
color_color_borde_contenido =
img_imagen_fondo_contenido =

bgcolor_color_fondo_pie = 
font_fuente_texto_pie =
size_tamano_texto_pie = 12
color_color_texto_pie = #ffffff	
border_tamano_borde_pie =
color_color_borde_pie =

color_color_texto_link = #C23B01
size_tamano_texto_link =
font_fuente_texto_link =
color_color_texto_hover = #333333
size_tamano_texto_hover =
font_fuente_texto_hover =

bgcolor_color_fondo_sidebar = 
color_color_borde_sidebar =

color_color_texto_slogan = 
size_tamano_texto_slogan =
font_fuente_texto_slogan =