MODULAR_OPTION=true
GENERIC_PAGE=true
MENU_LINK=true
MENU_FAQ=true
MENU_ARTICLE=true
MENU_BANNER=true
MENU_DOWNLOAD=true
MENU_ALBUM=true
MENU_DIRECT_ACCESS=true
MENU_ACTIVITY=true
MENU_PRODUCT=true
MENU_HIRU=false
MENU_BULLETIN=false
MENU_SPORT=false
MENU_STRUCTURE=true
