<?xml version="1.0" encoding="UTF-8"?>
<project>
	<parent>
		<groupId>com.code.aon</groupId>
		<artifactId>aon.parent</artifactId>
		<version>1.0.1</version>
	</parent>
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.code.aon</groupId>
	<artifactId>aon.security.bridge</artifactId>
	<version>3.2.1</version>
	<name>AON SECURITY BRIDGE</name>
	<description>AON SECURITY BRIDGE</description> 
	<dependencies>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.security</artifactId>
			<version>1.8.0</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ldap</artifactId>
			<version>1.0.0</version>
		</dependency>
		<dependency>
			<groupId>commons-logging</groupId>
			<artifactId>commons-logging</artifactId>
			<version>1.1</version>
			<scope>provided</scope>
		</dependency> 

		<dependency>
			<groupId>jboss</groupId>
			<artifactId>jboss-system</artifactId>
			<version>4.2.1.GA</version>
			<scope>provided</scope>
		</dependency>

		<dependency>
			<groupId>jboss</groupId>
			<artifactId>jboss-jmx</artifactId>
			<version>4.2.1.GA</version>
			<scope>provided</scope>
		</dependency>

		<dependency>
			<groupId>org.apache.tomcat</groupId>
			<artifactId>coyote</artifactId>
			<version>6.0.13</version>
			<scope>provided</scope>
		</dependency>

		<dependency>
			<groupId>javax.faces</groupId>
			<artifactId>jsf-api</artifactId>
			<version>1.2_09</version>
			<scope>provided</scope>
		</dependency>
	</dependencies>
</project>