color_color_borde_cuadro = #cccccc
color_color_borde_menu = #236a89
border_color_borde_imagen = #ffffff
bgcolor_color_fondo_pagina = #333333
bgcolor_color_fondo_de_cabecera = #236a89
bgcolor_color_fondo_logo = #ffffff
bgcolor_color_fondo_menu = #4797bf
bgcolor_color_fondo_titular = #4797bf
bgcolor_color_fondo_pie = #236a89
color_texto_menu = #ffffff
color_texto_links = #ffffff
color_texto_contenido = #ffffff
color_texto_titular = #ffffff
color_texto_pie = #ffffff
size_tamano_fuente = 11
size_tamano_fuente_titular = 14
font_fuente = 0