//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.03.31 at 11:57:12 AM CEST 
//


package com.esferalia.aon.ui.payroll.utils.contractMojo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Datos de los contratos de investigación.
 * 
 * <p>Java class for DATOS_CONTRATOINVESTIGACIONTYPE complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DATOS_CONTRATOINVESTIGACIONTYPE">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="IND_EMPLEADOR" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value="\d{1}"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="IND_TRABAJADOR" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value="\d{1}"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="IND_RD63_2006" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DATOS_CONTRATOINVESTIGACIONTYPE", propOrder = {
    "indempleador",
    "indtrabajador",
    "indrd632006"
})
public class DATOSCONTRATOINVESTIGACIONTYPE {

    @XmlElement(name = "IND_EMPLEADOR")
    protected String indempleador;
    @XmlElement(name = "IND_TRABAJADOR")
    protected String indtrabajador;
    @XmlElement(name = "IND_RD63_2006")
    protected String indrd632006;

    /**
     * Gets the value of the indempleador property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINDEMPLEADOR() {
        return indempleador;
    }

    /**
     * Sets the value of the indempleador property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINDEMPLEADOR(String value) {
        this.indempleador = value;
    }

    /**
     * Gets the value of the indtrabajador property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINDTRABAJADOR() {
        return indtrabajador;
    }

    /**
     * Sets the value of the indtrabajador property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINDTRABAJADOR(String value) {
        this.indtrabajador = value;
    }

    /**
     * Gets the value of the indrd632006 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINDRD632006() {
        return indrd632006;
    }

    /**
     * Sets the value of the indrd632006 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINDRD632006(String value) {
        this.indrd632006 = value;
    }

}
