<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>com.code.aon</groupId>
		<artifactId>aon.parent</artifactId>
		<version>9.23-SNAPSHOT</version>
	</parent>
	<groupId>solutions.aon</groupId>
	<artifactId>aon.aws</artifactId>
	<name>AON AWS</name>
	<description>AON AWS</description>

	<dependencies>
		<dependency>
    		<groupId>software.amazon.awssdk</groupId>
		    <artifactId>s3</artifactId>
		    <version>2.42.23</version>
    		<scope>compile</scope>
   	 	</dependency>
	
		<dependency>
    		<groupId>software.amazon.awssdk</groupId>
    		<artifactId>sesv2</artifactId>
		    <version>2.42.23</version>
    		<scope>compile</scope>
    	</dependency>
    
    	<dependency>
    		<groupId>software.amazon.awssdk</groupId>
    		<artifactId>dynamodb</artifactId>
		    <version>2.42.23</version>
			<scope>compile</scope>
		</dependency>
    
    	<dependency>
    		<groupId>software.amazon.awssdk</groupId>
    		<artifactId>secretsmanager</artifactId>
    		<version>2.42.23</version>
    		<scope>compile</scope>
		</dependency>

	    <dependency>
			<groupId>com.sun.mail</groupId>
			<artifactId>jakarta.mail</artifactId>
			<version>1.5.0</version>
		</dependency>
		
		<!-- Test dependecies -->
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>${junitVersion}</version>
			<scope>test</scope>
		</dependency>
	</dependencies>

</project>
