<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<!-- **************************** AvailabilityQueryRequest ************************************** -->
	<xs:element name="HITISOperation" type="HITISOperationType" substitutionGroup="HITISOperationAbstract"/>
	<xs:complexType name="HITISOperationType">
		<xs:complexContent>
			<xs:extension base="HITISOperationAbstractType">
				<xs:sequence>
					<xs:element ref="Errors" minOccurs="0"/>
					<xs:element ref="AvailabilityQuery"/>
					<xs:element name="RequestQueryDetail" type="xs:string" minOccurs="0"/>
					<xs:element ref="AvailabilitySummaryResponses" minOccurs="0"/>
					<xs:element ref="AvailabilityDetailResponses" minOccurs="0" maxOccurs="unbounded"/>
					<xs:element ref="AvailabilityOriginatorCode"/>
					<xs:element ref="Distributor" minOccurs="0"/>
					<xs:element ref="ReservationRequestType"/>
					<xs:element ref="ReservationTransaction"/>
					<xs:element ref="Reservation" minOccurs="0"/>
					<xs:element ref="ReservationID" minOccurs="0"/>
				</xs:sequence>
				<xs:attribute name="HITISCode" type="xs:string"/>
				<xs:attribute name="OperationName" type="xs:string" use="required"/>
				<xs:attribute name="OperationType" use="required">
					<xs:simpleType>
						<xs:restriction base="xs:NMTOKEN">
							<xs:enumeration value="Availability"/>
							<xs:enumeration value="Rate"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:attribute>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name="AvailabilityQuery">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="HotelReference" minOccurs="0"/>
				<xs:element name="ReservationID" type="xs:string" minOccurs="0"/>
				<xs:element ref="LanguageID" minOccurs="0"/>
				<xs:element ref="RequestedCurrencyCode" minOccurs="0"/>
				<xs:element name="RateMinCurrency" type="RateCurrencyType" minOccurs="0"/>
				<xs:element name="RateMaxCurrency" type="RateCurrencyType" minOccurs="0"/>
				<xs:element ref="StayDateRange" minOccurs="0"/>
				<xs:element ref="Profiles" minOccurs="0"/>
				<xs:element ref="RoomStays" minOccurs="0"/>
				<xs:element ref="Services" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="PagingKey" minOccurs="0"/>
				<xs:element name="AgencyCode" type="AgencyCodeType" minOccurs="0"/>
				<xs:element name="ExternalWebCode" type="xs:string" minOccurs="0"/>
				<!--				<xs:element name="RatePlanCandidates" type="RatePlanCandidatesType" minOccurs="0"/>-->
				<!--				<xs:element name="SpecialRequests" type="SpecialRequestsType" minOccurs="0" maxOccurs="unbounded"/>-->
				<!--				<xs:element ref="AgencyCode" minOccurs="0"/>-->
				<xs:element name="BusinessOrigin" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="CountryCode" type="xs:string"/>
							<xs:element name="ProvinceCode" type="xs:string" minOccurs="0"/>
						</xs:sequence>
						<xs:attribute name="Check" type="xs:string"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="AvailRequestType">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN">
						<xs:enumeration value="Room"/>
						<xs:enumeration value="NonRoom"/>
						<xs:enumeration value="Both"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="ExactMatchOnly" type="xs:boolean" use="optional">
				<xs:annotation>
					<xs:documentation xml:lang="en">A boolean flag that indicates the response message should send back only those rates that are an exact match to the requested criteria.</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="SearchCacheLevel" type="xs:string" use="optional"/>
			<xs:attribute name="IncludePackages" type="xs:string" use="optional">
				<xs:annotation>
					<xs:documentation xml:lang="en">A=All Rates, Y=Include Just Package Rates, N=Don't include Package Rates</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="DetailPackages" type="xs:string">
				<xs:annotation>
					<xs:documentation>Empty, S=Short Detail, A= AllDetail</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="FilterPackagesByType" type="xs:string"/>
			<xs:attribute name="FilterPackagesBySubType1" type="xs:string"/>
			<xs:attribute name="FilterPackagesBySubType3" type="xs:string"/>
			<xs:attribute name="FilterPackagesBySubType2" type="xs:string"/>
			<xs:attribute name="FilterPackagesBySubType4" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="AvailabilitySummaryResponses">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="AvailabilitySummaryResponse"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="AvailabilitySummaryResponse">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="HotelReference"/>
				<xs:element ref="AvailabilitySummaryRecords"/>
				<xs:element ref="Taxes" minOccurs="0"/>
				<xs:element ref="ProfileReferences" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="PagingKey" minOccurs="0"/>
				<xs:element ref="RequestedCurrencyCode"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="AvailabilityDetailResponses">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="AvailabilityDetailResponse" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="AvailabilityDetailResponse">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="AvailabilityDetailResponseRPH" type="xs:positiveInteger"/>
				<xs:element name="DetailDescription" type="xs:string"/>
			</xs:sequence>
			<xs:attribute name="AvailabilityDetailType" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN">
						<xs:enumeration value="RateDescription"/>
						<xs:enumeration value="RoomInformation"/>
						<xs:enumeration value="GuaranteeInformation"/>
						<xs:enumeration value="DepositInformation"/>
						<xs:enumeration value="CancellationInformation"/>
						<xs:enumeration value="CheckInCheckOutInformation"/>
						<xs:enumeration value="ExtraChargeInformation"/>
						<xs:enumeration value="PackageInformation"/>
						<xs:enumeration value="PropertyDescription"/>
						<xs:enumeration value="PropertyLocation"/>
						<xs:enumeration value="MiscellaneousInformation"/>
						<xs:enumeration value="PromotionalInformation"/>
						<xs:enumeration value="RoomRateInformation"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="RateCurrencyType">
		<xs:sequence>
			<xs:element ref="Currency"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="HotelReference">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ChainCode" minOccurs="0"/>
				<xs:element ref="HotelCode"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Profiles">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Profile"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="RoomStays">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="RoomStay" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="RoomStayRPH"/>
							<xs:element ref="RoomInventoryCode" minOccurs="0"/>
							<xs:element ref="InventoryCode" minOccurs="0"/>
							<xs:element ref="GuestCounts"/>
							<xs:element ref="RatePlans" minOccurs="0"/>
							<xs:element name="Amount" minOccurs="0"/>
							<xs:element name="RoomCodes" minOccurs="0">
								<xs:complexType>
									<xs:attribute name="Category" type="xs:string" use="required"/>
									<xs:attribute name="MealPlan" type="xs:string" use="required"/>
									<xs:attribute name="BaseRoomCode" type="xs:string" use="required"/>
								</xs:complexType>
							</xs:element>
							<xs:element ref="Services" minOccurs="0" maxOccurs="unbounded"/>
							<xs:element ref="RateQuotes"/>
							<xs:element ref="RoomInformations" minOccurs="0" maxOccurs="unbounded"/>
							<xs:element ref="LimitDates" minOccurs="0" maxOccurs="unbounded"/>
							<xs:element ref="BookingRules" minOccurs="0"/>
							<xs:element ref="PaymentInstructions" minOccurs="0" maxOccurs="unbounded"/>
							<!--						<xs:element ref="RoomID" minOccurs="0"/>-->
							<!--						<xs:element name="TimeSpan" type="TimeSpanType" minOccurs="0"/>-->
							<!--						<xs:element name="AnticipatedSettlementRPHs" type="AnticipatedSettlementRPHsType" minOccurs="0" maxOccurs="unbounded"/>-->
							<!--						<xs:element ref="InventoryBlockCode" minOccurs="0"/>-->
							<!--						<xs:element ref="MarketSegmentCode" minOccurs="0"/>-->
							<!--						<xs:element ref="PromotionCode" minOccurs="0"/>-->
							<!--						<xs:element ref="TACommissionPlanCode" minOccurs="0"/>-->
							<!--						<xs:element name="ResGuestRPHs" type="ResGuestRPHsType" minOccurs="0" maxOccurs="unbounded"/>-->
							<!--						<xs:element name="SelectedMembershipRPHs" type="SelectedMembershipRPHsType" minOccurs="0" maxOccurs="unbounded"/>-->
							<!--						<xs:element name="ResCommentRPHs" type="ResCommentRPHsType" minOccurs="0" maxOccurs="unbounded"/>-->
							<!--						<xs:element name="SpecialRequestRPHs" type="SpecialRequestRPHsType" minOccurs="0" maxOccurs="unbounded"/>-->
							<!--						<xs:element name="ServiceRPHs" type="ServiceRPHsType" minOccurs="0" maxOccurs="unbounded"/>-->
							<!--						<xs:element name="GuaranteeInfo" type="GuaranteeInfoType" minOccurs="0"/>-->
							<!--						<xs:element name="CancelPenalties" type="CancelPenaltiesType" minOccurs="0"/>-->
							<!--						<xs:element name="PaymentInstructions" type="PaymentInstructionsType" minOccurs="0"/>-->
						</xs:sequence>
						<xs:attribute name="ReservationActionType">
							<xs:simpleType>
								<xs:restriction base="xs:NMTOKEN">
									<xs:enumeration value="DoesNotApply"/>
									<xs:enumeration value="New"/>
									<xs:enumeration value="Change"/>
									<xs:enumeration value="Delete"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute name="ReservationStatusType">
							<xs:simpleType>
								<xs:restriction base="xs:NMTOKEN">
									<xs:enumeration value="Reserved"/>
									<xs:enumeration value="Requested"/>
									<xs:enumeration value="RequestDenied"/>
									<xs:enumeration value="NoShow"/>
									<xs:enumeration value="Canceled"/>
									<xs:enumeration value="InHouse"/>
									<xs:enumeration value="CheckedOut"/>
									<xs:enumeration value="Waitlisted"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="RatePlans">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="RatePlan" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="RatePlanRPH"/>
							<xs:element ref="RatePlanCode"/>
							<!--							<xs:element name="TimeSpan" type="TimeSpanType" minOccurs="0"/>-->
							<!--							<xs:element name="Rates" type="RatesType" minOccurs="0" maxOccurs="unbounded"/>-->
						</xs:sequence>
						<xs:attribute name="ReservationActionType">
							<xs:simpleType>
								<xs:restriction base="xs:NMTOKEN">
									<xs:enumeration value="DoesNotApply"/>
									<xs:enumeration value="New"/>
									<xs:enumeration value="Change"/>
									<xs:enumeration value="Delete"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Services">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Service" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="ServiceRPH"/>
							<xs:element ref="ServiceInventoryCode"/>
							<!--							<xs:element name="AnticipatedSettlementRPHs" type="AnticipatedSettlementRPHsType" minOccurs="0" maxOccurs="unbounded"/>-->
							<!--							<xs:element name="ResCommentRPHs" type="ResCommentRPHsType" minOccurs="0" maxOccurs="unbounded"/>-->
							<!--							<xs:element name="SelectedMembershipRPHs" type="SelectedMembershipRPHsType" minOccurs="0" maxOccurs="unbounded"/>-->
							<!--							<xs:element ref="RatePlanCode" minOccurs="0"/>-->
							<!--							<xs:element ref="InventoryBlockCode" minOccurs="0"/>-->
							<!--							<xs:element name="TimeSpan" type="TimeSpanType" minOccurs="0"/>-->
							<!--							<xs:element name="Price" type="PriceType" minOccurs="0"/>-->
							<!--							<xs:element name="PriceGuaranteed" type="PriceGuaranteedType" minOccurs="0"/>-->
							<!--							<xs:element name="Inclusive" type="InclusiveType" minOccurs="0"/>-->
							<!--							<xs:element name="Quantity" type="QuantityType" minOccurs="0"/>-->
							<!--							<xs:element name="GuaranteeInfos" type="GuaranteeInfosType" minOccurs="0"/>-->
							<!--							<xs:element name="CancelPenalties" type="CancelPenaltiesType" minOccurs="0" maxOccurs="unbounded"/>-->
							<!--							<xs:element name="PaymentInstructions" type="PaymentInstructionsType" minOccurs="0" maxOccurs="unbounded"/>-->
							<!--							<xs:element name="GuestCounts" type="GuestCountsType" minOccurs="0" maxOccurs="unbounded"/>-->
						</xs:sequence>
						<xs:attribute name="ReservationStatusType">
							<xs:simpleType>
								<xs:restriction base="xs:NMTOKEN">
									<xs:enumeration value="Reserved"/>
									<xs:enumeration value="Requested"/>
									<xs:enumeration value="RequestDenied"/>
									<xs:enumeration value="NoShow"/>
									<xs:enumeration value="Canceled"/>
									<xs:enumeration value="InHouse"/>
									<xs:enumeration value="CheckedOut"/>
									<xs:enumeration value="Waitlisted"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute name="ServicePricingType">
							<xs:simpleType>
								<xs:restriction base="xs:NMTOKEN">
									<xs:enumeration value="PerStay"/>
									<xs:enumeration value="PerPerson"/>
									<xs:enumeration value="PerNight"/>
									<xs:enumeration value="PerPersonPerNight"/>
									<xs:enumeration value="PerUse"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute name="ReservationActionType">
							<xs:simpleType>
								<xs:restriction base="xs:NMTOKEN">
									<xs:enumeration value="DoesNotApply"/>
									<xs:enumeration value="New"/>
									<xs:enumeration value="Change"/>
									<xs:enumeration value="Delete"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="RateQuotes">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="RateQuote">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="DateRange" minOccurs="0"/>
							<xs:element ref="QuotedRateAmount"/>
							<xs:element name="QuotedLoyaltyRateAmount" minOccurs="0">
								<xs:complexType mixed="true">
									<xs:all minOccurs="0">
										<xs:element ref="Currency"/>
									</xs:all>
									<xs:attribute name="CurrencyCode" type="xs:string" use="optional"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="QuotedOfferRateAmount" minOccurs="0">
								<xs:complexType mixed="true">
									<xs:all minOccurs="0">
										<xs:element ref="Currency"/>
									</xs:all>
									<xs:attribute name="CurrencyCode" type="xs:string" use="optional"/>
								</xs:complexType>
							</xs:element>
							<xs:element ref="RateBasisTimeUnitType"/>
							<xs:element name="RateBasisUnits" type="xs:positiveInteger" minOccurs="0"/>
							<xs:element name="IsChange" type="StringLength1YorN" minOccurs="0"/>
							<xs:element name="RateFlags" type="xs:string" minOccurs="0"/>
							<xs:element name="TotalTaxes" minOccurs="0">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute name="CurrencyCode" type="AlphaLength3to3" use="required"/>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
							<xs:element name="TotalLoyaltyTaxes" minOccurs="0">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute name="CurrencyCode" type="AlphaLength3to3" use="required"/>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
							<xs:element name="TotalOfferTaxes" minOccurs="0">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute name="CurrencyCode" type="AlphaLength3to3" use="required"/>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
							<xs:element name="TotalAmountWithoutTax" minOccurs="0">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute name="CurrencyCode" type="AlphaLength3to3" use="required"/>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
							<xs:element name="TotalLoyaltyAmountWithoutTax" minOccurs="0">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute name="CurrencyCode" type="AlphaLength3to3" use="required"/>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
							<xs:element name="TotalOfferAmountWithoutTax" minOccurs="0">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute name="CurrencyCode" type="AlphaLength3to3" use="required"/>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
							<xs:element name="TotalAmountWithTax" minOccurs="0">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute name="CurrencyCode" type="AlphaLength3to3" use="required"/>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
							<xs:element name="TotalLoyaltyAmountWithTax" minOccurs="0">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute name="CurrencyCode" type="AlphaLength3to3" use="required"/>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
							<xs:element name="TotalLoyaltyPoints" minOccurs="0"/>
							<xs:element name="TotalOfferAmountWithTax" minOccurs="0">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute name="CurrencyCode" type="AlphaLength3to3" use="required"/>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="DateRange">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="DateTimeSpan"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="RoomInformations">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="RoomInformation" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="RoomInformationRPH" type="xs:positiveInteger"/>
							<xs:element name="DetailDescription" type="xs:string"/>
						</xs:sequence>
						<xs:attribute name="RoomInformationType" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:NMTOKEN">
									<xs:enumeration value="RoomInformation"/>
									<xs:enumeration value="RoomRateInformation"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="LimitDates">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Cancelation" type="xs:string" minOccurs="0"/>
				<xs:element name="HotelArrival" type="xs:string" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Taxes">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Tax" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Tax">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="TaxDescription" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="Percent" type="xs:string"/>
			<xs:attribute name="Type" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN">
						<xs:enumeration value="Inclusive"/>
						<xs:enumeration value="Exclusive"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="Code" type="xs:string" use="required"/>
			<xs:attribute name="ChargeUnit" type="xs:string" use="required"/>
			<xs:attribute name="Amount" type="xs:string"/>
			<xs:attribute name="CurrencyCode" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="TaxDescription">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Text"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Text">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="Language" type="xs:string" use="required"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="ProfileReferences">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Profiles">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="Profile"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="AvailabilitySummaryRecords">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="AvailabilitySummaryRecord" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="AvailabilitySummaryRecord">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="AvailabilitySummaryRecordRPH" type="xs:positiveInteger"/>
				<xs:element name="IsRoom" type="xs:boolean" minOccurs="0"/>
				<xs:element name="IsConverted" type="xs:boolean" minOccurs="0"/>
				<xs:element name="IsAlternate" type="xs:boolean" minOccurs="0"/>
				<xs:element ref="RatePlanCode"/>
				<xs:element name="RatePlanCategory" type="xs:string" minOccurs="0"/>
				<xs:element name="RatePlanType" type="xs:string" minOccurs="0"/>
				<xs:element name="TaxesText" type="xs:string" minOccurs="0"/>
				<xs:element name="MarketingText" type="xs:string" minOccurs="0"/>
				<xs:element ref="RateDescriptions" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="TACommission" minOccurs="0"/>
				<xs:element ref="RoomStays"/>
				<xs:element name="ExtraPackage" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="ExtraPackageCode"/>
							<xs:element name="ExtraPackageName" minOccurs="0"/>
							<xs:element name="ExtraPackageType" minOccurs="0"/>
							<xs:element name="ExtraPackageSubType1" minOccurs="0"/>
							<xs:element name="ExtraPackageSubType2" minOccurs="0"/>
							<xs:element name="ExtraPackageSubType3" minOccurs="0"/>
							<xs:element name="ExtraPackageSubType4" minOccurs="0"/>
							<xs:element name="ExtraPackageServices" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="ExtraPackageService" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="ServiceNumber"/>
													<xs:element name="ServiceCode"/>
													<xs:element name="ServiceDescription" minOccurs="0"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="CancelPenalty" type="CancelPenaltyType" minOccurs="0"/>
				<xs:element name="Offers" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Offer" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="OfferRPH"/>
										<xs:element name="ServiceCode"/>
										<xs:element name="OfferCode"/>
										<xs:element name="OfferDescription"/>
										<xs:element name="Amount" minOccurs="0">
											<xs:complexType/>
										</xs:element>
										<xs:element name="Percent" minOccurs="0"/>
										<xs:element name="CurrencyCode" minOccurs="0"/>
										<xs:element name="NumberOfNights" minOccurs="0"/>
										<xs:element name="NumberOfPaidNights" minOccurs="0"/>
										<xs:element name="NumberOfFreeNights" minOccurs="0"/>
										<xs:element name="ExtraType" minOccurs="0"/>
										<xs:element name="PAXType" minOccurs="0"/>
										<xs:element name="Order" minOccurs="0"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element ref="BookingRules" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="RequiredGuaranteeType">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN">
						<xs:enumeration value="None"/>
						<xs:enumeration value="GuaranteeRequired"/>
						<xs:enumeration value="DepositRequired"/>
						<xs:enumeration value="ImmediatePaymentRequired"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="RateDescriptions">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="RateDescription" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="RateDescriptionRPH" type="xs:string"/>
							<xs:element name="DetailDescription" type="xs:string"/>
						</xs:sequence>
						<xs:attribute name="AvailabilityDetailType" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:NMTOKEN">
									<xs:enumeration value="RateText"/>
									<xs:enumeration value="DetailRateDescription"/>
									<xs:enumeration value="TaxesText"/>
									<xs:enumeration value="TaxesDescription"/>
									<xs:enumeration value="SpecialRequired"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="TACommission">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="type" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:NMTOKEN">
								<xs:enumeration value="Percentage"/>
								<xs:enumeration value="Absolute"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>



	<!-- **************************** SolMelia_Messaging ************************************** -->
	<xs:complexType name="HITISOperationAbstractType">
		<xs:annotation>
			<xs:documentation xml:lang="en">This is empty as it will be redefined for each message</xs:documentation>
		</xs:annotation>
	</xs:complexType>
	<xs:element name="HITISOperationAbstract" type="HITISOperationAbstractType" abstract="true"/>
	<xs:element name="HITISMessage">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Header">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="FromURI" type="xs:string" minOccurs="0"/>
							<xs:element name="ToURI" type="xs:string" minOccurs="0"/>
							<xs:element name="ReplyToURI" type="xs:string" minOccurs="0"/>
							<xs:element name="MessageID" type="xs:string"/>
							<xs:element name="OriginalMessageID" type="xs:string" minOccurs="0"/>
							<xs:element name="TimeStamp" type="TimeStampType" minOccurs="0"/>
							<xs:element name="Token" type="xs:string" minOccurs="0"/>
						</xs:sequence>
						<xs:attribute name="ImmediateResponseRequired" type="xs:string"/>
						<xs:attribute name="OriginalBodyRequested" type="xs:string"/>
						<xs:attribute name="a-dtype" type="xs:NMTOKENS" default="texto"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="Body">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="HITISOperationAbstract"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="Version" type="xs:string"/>
		</xs:complexType>
	</xs:element>



	<!-- **************************** SolMelia_CommonTypes ************************************** -->
	<xs:element name="LanguageID" type="xs:language"/>
	<!--xs:element name="duration" type="xs:string"-->
	<xs:element name="Errors">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Error" maxOccurs="unbounded">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attribute name="HITISCode" type="xs:string" use="required"/>
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="duration">
		<xs:simpleType>
			<xs:annotation>
				<xs:documentation xml:lang="en">
					Duration of stay in the format YYYY-MM-ddTHH:mm:ss
					The maximum number of days for a stay is 999 days
				</xs:documentation>
			</xs:annotation>
			<xs:restriction base="xs:string">
				<xs:pattern value="\+0000-00-([0-9]{1,3})T00:00:00"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:complexType name="TimeStampType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="e-dtype" type="xs:NMTOKEN" fixed="timeInstant"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:element name="startInstant" type="xs:dateTime"/>
	<xs:element name="TimeSpan">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="DateTimeSpan"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="DateTimeSpan">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="startInstant"/>
				<xs:element ref="duration"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="StayDateRange">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="DateTimeSpan"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<!-- ## HotelReference attributes ## -->
	<xs:element name="HotelCode" type="NumericStringLength4to9"/>
	<xs:element name="HotelReferenceRPH" type="xs:positiveInteger"/>
	<xs:element name="ChainCode" type="xs:string"/>
	<xs:element name="HotelAvailability" type="xs:string"/>
	<xs:element name="HotelInformations">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="HotelInformation" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="HotelInformationRPH" type="xs:positiveInteger"/>
							<xs:element name="DetailDescription" type="xs:string"/>
						</xs:sequence>
						<xs:attribute name="HotelInformationType" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:NMTOKEN">
									<xs:enumeration value="GuarantyPolicy"/>
									<xs:enumeration value="DepositPolicy"/>
									<xs:enumeration value="CommisionsPolicy"/>
									<xs:enumeration value="CancelationInformation"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<!-- ## RoomStay attributes ## -->
	<xs:element name="RoomStayRPH" type="xs:positiveInteger"/>
	<xs:element name="InventoryCode" type="xs:string"/>
	<xs:element name="ServiceCharges" type="xs:string"/>
	<xs:element name="RoomInventoryCode" type="xs:string"/>
	<!-- ## Service attributes ## -->
	<xs:element name="ServiceRPH" type="xs:positiveInteger"/>
	<xs:element name="ExtraServiceRPH" type="xs:positiveInteger"/>
	<xs:element name="ServiceInventoryCode" type="xs:string"/>
	<xs:element name="Quantity" type="xs:positiveInteger"/>
	<xs:element name="Price">
		<xs:complexType mixed="true">
			<xs:all minOccurs="0">
				<xs:element ref="Currency" minOccurs="0"/>
			</xs:all>
			<xs:attribute name="CurrencyCode" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<!-- ## RateQuote attributes ## -->
	<xs:element name="QuotedRateAmount">
		<xs:complexType mixed="true">
			<xs:all minOccurs="0">
				<xs:element ref="Currency"/>
			</xs:all>
			<xs:attribute name="CurrencyCode" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="RateBasisTimeUnitType" type="xs:string"/>
	<xs:element name="RequestedCurrencyCode" type="AlphaLength3to3">
		<xs:annotation>
			<xs:documentation xml:lang="en">Currency type based on ISO 4217</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="PagingKey" type="xs:string"/>
	<xs:element name="Membership">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element name="ProgramCode" type="xs:string"/>
				<xs:element name="AccountID" type="xs:string"/>
				<xs:element name="LevelCode" type="xs:string"/>
				<xs:element name="MembershipCategoryCode" type="xs:string" minOccurs="0"/>
				<xs:element name="ExpireDate" type="TimeStampType" minOccurs="0"/>
				<xs:element name="SignupDate" type="TimeStampType" minOccurs="0"/>
				<xs:element name="StartDate" type="TimeStampType" minOccurs="0"/>
				<xs:element ref="Membership" minOccurs="0"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<xs:element name="Profile">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="ProfileID" type="xs:string" minOccurs="0"/>
				<xs:element ref="Membership" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="GenderType">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN">
						<xs:enumeration value="Unknown"/>
						<xs:enumeration value="Male"/>
						<xs:enumeration value="Female"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="ProfileType">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN">
						<xs:enumeration value="Guest"/>
						<xs:enumeration value="CorporateAccount"/>
						<xs:enumeration value="TravelAgency"/>
						<xs:enumeration value="Wholesaler"/>
						<xs:enumeration value="Group"/>
						<xs:enumeration value="TourOperator"/>
						<xs:enumeration value="CRO"/>
						<xs:enumeration value="Contact"/>
						<xs:enumeration value="Airline"/>
						<xs:enumeration value="RepCompany"/>
						<xs:enumeration value="InternetBroker"/>
						<xs:enumeration value="Hotel"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="Currency">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="CurrencyCode" type="xs:string"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="GuestCounts">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="GuestCount" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="AgeQualifyingCode" type="xs:string" minOccurs="0"/>
							<xs:element name="Age" type="xs:positiveInteger" minOccurs="0"/>
							<xs:element name="Count" type="Numeric1to9"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="RatePlanRPH" type="xs:positiveInteger"/>
	<xs:element name="RatePlanCode" type="xs:string"/>
	<!-- @@@@@@@@@@@@@@@@@@ AVAILABILITY @@@@@@@@@@@@@@@@@-->
	<xs:element name="AvailabilityOriginatorCode" type="xs:string"/>
	<!--xs:element name="AgencyCode" type="NumericStringLength8"/ DEFINED IN SolMelia_SimpleTypes.xsd -->
	<!--######################## BOOKING RULES o Normas de Venta (deposito, garantización y cancelación) ############################################-->
	<xs:complexType name="BankCityType">
		<xs:attribute name="CityCode" type="xs:string" use="required"/>
		<xs:attribute name="CityName" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:complexType name="BankCountryType">
		<xs:attribute name="CountryCode" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:element name="AccountHolderName" type="StringLength1to150"/>
	<xs:element name="AccountNumber" type="StringLength1to60"/>
	<xs:complexType name="BankDetailsType">
		<xs:sequence>
			<xs:element ref="BankName" minOccurs="0"/>
			<xs:element ref="AccountNumber" minOccurs="0"/>
			<xs:element ref="AccountHolderName" minOccurs="0"/>
			<xs:element name="BankCity" type="BankCityType" minOccurs="0"/>
			<xs:element name="BankCountry" type="BankCountryType" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="BankName" type="StringLength1to60"/>
	<xs:element name="BookingRules">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="GuaranteeRequirements" type="GuaranteeRequirementsType"/>
				<xs:element name="CancelPenalties" type="CancelPenaltiesType" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="CancelPenaltyType">
		<xs:sequence>
			<xs:element name="Deadline" type="DeadlineType" minOccurs="0"/>
			<xs:element name="DuePayment" type="DuePaymentType"/>
			<xs:element ref="Description" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="ModificationIncluded" type="xs:boolean" use="optional"/>
	</xs:complexType>
	<xs:complexType name="CancelPenaltiesType">
		<xs:sequence>
			<xs:element name="Comment" type="xs:string" minOccurs="0"/>
			<xs:element name="CancelPenalty" type="CancelPenaltyType" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="DeadlineType">
		<xs:attribute name="AbsoluteDeadline" type="DateOrTimeOrDateTimeType" use="optional"/>
		<xs:attribute name="OffsetUnit" use="optional">
			<xs:simpleType>
				<xs:restriction base="xs:NMTOKEN">
					<xs:enumeration value="Hour"/>
					<xs:enumeration value="Day"/>
					<xs:enumeration value="Week"/>
					<xs:enumeration value="Month"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="OffsetUnitMultiplier" type="xs:positiveInteger" use="optional"/>
		<xs:attribute name="OffsetDropTime" use="optional">
			<xs:simpleType>
				<xs:restriction base="xs:NMTOKEN">
					<xs:enumeration value="BeforeArrival"/>
					<xs:enumeration value="AfterBooking"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="DepositPaymentType">
		<xs:sequence>
			<xs:element name="DuePayment" type="DuePaymentType"/>
			<xs:element name="Deadline" type="DeadlineType"/>
			<xs:element name="BankDetails" type="BankDetailsType" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="Method" type="DepositGuaranteeMethod" use="optional"/>
	</xs:complexType>
	<xs:element name="Description" type="xs:string"/>
	<xs:complexType name="DuePaymentType">
		<xs:attribute name="Quantity" type="xs:string" use="required"/>
		<xs:attribute name="Unit" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:NMTOKEN">
					<xs:enumeration value="Percent"/>
					<xs:enumeration value="Amount"/>
					<xs:enumeration value="NightStay"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="CurrencyCode" type="AlphaLength3to3" use="optional"/>
	</xs:complexType>
	<xs:complexType name="GuaranteeType">
		<xs:attribute name="Method" type="DepositGuaranteeMethod" use="required"/>
	</xs:complexType>
	<xs:simpleType name="DepositGuaranteeMethod">
		<xs:restriction base="xs:NMTOKEN">
			<xs:enumeration value="CreditCard"/>
			<xs:enumeration value="Voucher"/>
			<xs:enumeration value="CreditCardOrVoucher"/>
			<xs:enumeration value="CreditCardAuthFax"/>
			<xs:enumeration value="PrepayOrDeposit"/>
			<xs:enumeration value="CreditCardOrDeposit"/>
			<xs:enumeration value="Cheque"/>
			<xs:enumeration value="BankDeposit"/>
			<xs:enumeration value="CreditCardAndCheque"/>
			<xs:enumeration value="PrePay"/>
			<xs:enumeration value="CreditCardAndVoucher"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="GuaranteeRequirementsType">
		<xs:choice>
			<xs:element name="LatestArrivalTime" type="xs:time"/>
			<xs:element name="Guarantee" type="GuaranteeType"/>
			<xs:element name="DepositPayment" type="DepositPaymentType"/>
		</xs:choice>
	</xs:complexType>
	<xs:element name="ExtraServices">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ExtraService" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ExtraService">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ExtraServiceRPH"/>
				<xs:element ref="ServiceInventoryCode"/>
				<xs:element ref="Price"/>
			</xs:sequence>
			<xs:attribute name="ExtraServiceType" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN">
						<xs:enumeration value="Bed"/>
						<xs:enumeration value="Person"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="Distributor">
		<xs:complexType>
			<xs:attribute name="Code" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>



	<!-- **************************** SolMelia_SimpleTypes ************************************** -->
	<xs:simpleType name="AlphaLength3to3">
		<xs:annotation>
			<xs:documentation xml:lang="en">Used for Alphabetic Strings, length exactly 3</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:pattern value="[a-zA-Z]{3}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="StringLength1to3">
		<xs:annotation>
			<xs:documentation xml:lang="en">Used for Strings, length 1 to 3</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
			<xs:maxLength value="3"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="NumericStringLength10">
		<xs:annotation>
			<xs:documentation xml:lang="en">Used for Numeric Strings, length 10</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:pattern value="[0-9]{1,10}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="NumericStringLength4">
		<xs:annotation>
			<xs:documentation xml:lang="en">Used for Numeric Strings, length 4</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:pattern value="[0-9]{4}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="NumericStringLength8">
		<xs:annotation>
			<xs:documentation xml:lang="en">Used for Numeric Strings, length 8</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:pattern value="[0-9]{8}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="Numeric1to9">
		<xs:annotation>
			<xs:documentation xml:lang="en">Used for Numeric values, from 1 to 9 inclusive</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:integer">
			<xs:minInclusive value="1"/>
			<xs:maxInclusive value="9"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="StringLength1YorN">
		<xs:annotation>
			<xs:documentation xml:lang="en">Character Y or N</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
			<xs:maxLength value="1"/>
			<xs:enumeration value="Y"/>
			<xs:enumeration value="N"/>
		</xs:restriction>
	</xs:simpleType>
	<!--xs:simpleType name="AgencyCodeType">
		<xs:annotation>
			<xs:documentation xml:lang="en">Travel agency codes: alphanumeric Strings 1 to 8 numbers plus 3 optional control chars</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:pattern value="[0-9]{1,8}([a-zA-Z]{3})?"/>
		</xs:restriction>
	</xs:simpleType-->
	<xs:complexType name="AgencyCodeType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="Type" use="optional">
					<xs:simpleType>
						<xs:restriction base="xs:NMTOKEN">
							<xs:enumeration value="IATA"/>
							<xs:enumeration value="SolRes"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:attribute>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:simpleType name="StringLength1to20">
		<xs:annotation>
			<xs:documentation xml:lang="en">Used for Strings, length 1 to 20</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
			<xs:maxLength value="20"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="StringLength1to60">
		<xs:annotation>
			<xs:documentation xml:lang="en">Used for Strings, length 1 to 60</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
			<xs:maxLength value="60"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="StringLength1to150">
		<xs:annotation>
			<xs:documentation xml:lang="en">Used for Strings, length 1 to 150</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
			<xs:maxLength value="150"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="DateOrTimeOrDateTimeType">
		<xs:annotation>
			<xs:documentation xml:lang="en">A construct to validate either a date or a time or a dateTime value.</xs:documentation>
		</xs:annotation>
		<xs:union memberTypes="xs:date xs:dateTime xs:time"/>
	</xs:simpleType>
	<xs:simpleType name="NumericStringLength4to9">
		<xs:annotation>
			<xs:documentation xml:lang="en">Used for Numeric Strings, length 4 to 9</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:pattern value="[0-9]{4,9}"/>
		</xs:restriction>
	</xs:simpleType>



	<!-- **************************** Booking_Request ************************************** -->
	<xs:element name="ReservationRequestType">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="ReservationRequestType" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:NMTOKEN">
								<xs:enumeration value="Initiate"/>
								<xs:enumeration value="Ignore"/>
								<xs:enumeration value="Modify"/>
								<xs:enumeration value="Commit"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="ReservationTransaction">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="RoutingHops" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="WrittenComfirmationInstructions" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="Reservation" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="ReservationTransactionType">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN">
						<xs:enumeration value="New"/>
						<xs:enumeration value="Change"/>
						<xs:enumeration value="Cancel"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="ReservationMessageType">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN">
						<xs:enumeration value="Normal"/>
						<xs:enumeration value="FullOverlay"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="ActionCode">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN">
						<xs:enumeration value="SS"/>
						<xs:enumeration value="IS"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="RoutingHops">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="RoutingHop"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="RoutingHop">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="SystemCode"/>
				<xs:element ref="ObjectID"/>
				<xs:element ref="TimeStamp"/>
				<xs:element ref="Data"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="SystemCode" type="xs:string"/>
	<xs:element name="ObjectID" type="xs:string"/>
	<xs:element name="TimeStamp" type="TimeStampType"/>
	<xs:element name="Data" type="xs:string"/>
	<xs:element name="WrittenComfirmationInstructions">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="WrittenConfirmationInstruction"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="WrittenConfirmationInstruction">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ElectronicAddresses" minOccurs="0"/>
				<xs:element ref="PostalAddresses" minOccurs="0"/>
				<xs:element ref="PhoneNumbers" minOccurs="0"/>
				<xs:element ref="LanguageID" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="ProfileType" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN">
						<xs:enumeration value="Guest"/>
						<xs:enumeration value="CorporateAccount"/>
						<xs:enumeration value="TravelAgency"/>
						<xs:enumeration value="Wholesaler"/>
						<xs:enumeration value="Group"/>
						<xs:enumeration value="TourOperator"/>
						<xs:enumeration value="CRO"/>
						<xs:enumeration value="Contact"/>
						<xs:enumeration value="Airline"/>
						<xs:enumeration value="RepCompany"/>
						<xs:enumeration value="InternetBroker"/>
						<xs:enumeration value="Hotel"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="ElectronicAddresses">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ElectronicAddress"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ElectronicAddress">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="EAddress"/>
			</xs:sequence>
			<xs:attribute name="ElectronicAddressType">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN">
						<xs:enumeration value="Email"/>
						<xs:enumeration value="Pager"/>
						<xs:enumeration value="WebPage"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="EAddress" type="xs:string"/>
	<xs:element name="PostalAddresses">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="PostalAddress"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="PostalAddress">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Address1"/>
				<xs:element ref="Address2"/>
				<xs:element ref="Address3"/>
				<xs:element ref="Address4"/>
				<xs:element ref="City"/>
				<xs:element ref="StateCode"/>
				<xs:element ref="PostalCode"/>
				<xs:element ref="CountryCode"/>
			</xs:sequence>
			<xs:attribute name="AddressType" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN">
						<xs:enumeration value="Home"/>
						<xs:enumeration value="Business"/>
						<xs:enumeration value="Mailing"/>
						<xs:enumeration value="ShippingReceiving"/>
						<xs:enumeration value="Billing"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="Address1" type="xs:string"/>
	<xs:element name="Address2" type="xs:string"/>
	<xs:element name="Address3" type="xs:string"/>
	<xs:element name="Address4" type="xs:string"/>
	<xs:element name="City" type="xs:string"/>
	<xs:element name="StateCode" type="xs:string"/>
	<xs:element name="PostalCode" type="xs:string"/>
	<xs:element name="CountryCode" type="xs:string"/>
	<xs:element name="PhoneNumbers">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="PhoneNumber"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="PhoneNumber">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="PhoneNumberType">
						<xs:simpleType>
							<xs:restriction base="xs:NMTOKEN">
								<xs:enumeration value="HomePhone"/>
								<xs:enumeration value="BusinessPhone"/>
								<xs:enumeration value="MobilePhone"/>
								<xs:enumeration value="HomeFax"/>
								<xs:enumeration value="BusinessFax"/>
								<xs:enumeration value="Pager"/>
								<xs:enumeration value="Telex"/>
								<xs:enumeration value="TTY"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>


	<!-- **************************** Booking ************************************** -->
	<xs:element name="Reservation">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="HotelReference" minOccurs="0"/>
				<xs:element ref="ConfirmationID" minOccurs="0"/>
				<xs:element ref="ReservationID" minOccurs="0"/>
				<xs:element name="ReservationStatus" minOccurs="0">
					<xs:complexType>
						<xs:attribute name="State" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:NMTOKEN">
									<xs:enumeration value="Active"/>
									<xs:enumeration value="ActivePending"/>
									<xs:enumeration value="Cancelled"/>
									<xs:enumeration value="CancelledPending"/>
									<xs:enumeration value="ModifiedPending"/>
									<xs:enumeration value="Waitlisted"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
				<xs:element ref="Amount" minOccurs="0"/>
				<xs:element ref="CancellationID" minOccurs="0"/>
				<xs:element ref="ReservationOriginatorCode"/>
				<xs:element ref="StayDateRange" minOccurs="0"/>
				<xs:element ref="GuestCounts" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="ResComments" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="ResCreditCards" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="ResProfiles" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="RoomStays" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="SelectedMemberships" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="Services" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="ExtraPackage" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="ExtraPackageCode"/>
							<xs:element name="ExtraPackageName" minOccurs="0"/>
							<xs:element name="ExtraPackageType" minOccurs="0"/>
							<xs:element name="ExtraPackageSubType1" minOccurs="0"/>
							<xs:element name="ExtraPackageSubType2" minOccurs="0"/>
							<xs:element name="ExtraPackageSubType3" minOccurs="0"/>
							<xs:element name="ExtraPackageSubType4" minOccurs="0"/>
							<xs:element name="ExtraPackageServices" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="ExtraPackageService" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="ServiceNumber"/>
													<xs:element name="ServiceCode"/>
													<xs:element name="ServiceDescription" minOccurs="0"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element ref="BookingRules" minOccurs="0"/>
				<xs:element name="AgencyCode" type="AgencyCodeType" minOccurs="0"/>
				<xs:element ref="ExternalWebCode" minOccurs="0"/>
				<xs:element name="POSTransactionID" type="StringLength1to20" minOccurs="0"/>
				<xs:element name="ExternalReservationID" type="StringLength1to20" minOccurs="0"/>
				<!--			<xs:element name="ResCommentRPHs" type="ResCommentRPHsType" minOccurs="0" maxOccurs="unbounded"/>-->
				<!--			<xs:element name="ResProfileRPHs" type="ResProfileRPHsType" minOccurs="0" maxOccurs="unbounded"/>-->
				<!--			<xs:element name="SpecialRequestRPHs" type="SpecialRequestRPHsType" minOccurs="0" maxOccurs="unbounded"/>-->
				<!--			<xs:element name="ServiceRPHs" type="ServiceRPHsType" minOccurs="0" maxOccurs="unbounded"/>-->
				<!--			<xs:element name="AnticipatedSettlements" type="AnticipatedSettlementsType" minOccurs="0" maxOccurs="unbounded"/>-->
				<!--			<xs:element name="SpecialRequests" type="SpecialRequestsType" minOccurs="0" maxOccurs="unbounded"/>-->
				<!--			<xs:element name="Services" type="ServicesType" minOccurs="0" maxOccurs="unbounded"/>-->
				<!--			<xs:element name="OriginalRoutingHops" type="OriginalRoutingHopsType" minOccurs="0" maxOccurs="unbounded"/>-->
				<!--			<xs:element name="SelectedMemberships" type="SelectedMembershipsType" minOccurs="0" maxOccurs="unbounded"/>-->
				<!--			<xs:element name="RoomStays" type="RoomStaysType" minOccurs="0" maxOccurs="unbounded"/>-->
				<!--			<xs:element name="RoomStayReservation" type="RoomStayReservationType" minOccurs="0"/>-->
				<!--			<xs:element name="OriginalBookingDate" type="OriginalBookingDateType" minOccurs="0"/>-->
				<!--			<xs:element ref="CancelOriginatorCode" minOccurs="0"/>-->
				<!--			<xs:element name="CancellationDate" type="CancellationDateType" minOccurs="0"/>-->
				<!--			<xs:element name="GuestCounts" type="GuestCountsType" minOccurs="0" maxOccurs="unbounded"/>-->
				<!--			<xs:element name="ResComments" type="ResCommentsType" minOccurs="0" maxOccurs="unbounded"/>-->
				<!--			<xs:element name="ResCreditCards" type="ResCreditCardsType" minOccurs="0" maxOccurs="unbounded"/>-->
				<!--			<xs:element name="ResGuests" type="ResGuestsType" minOccurs="0" maxOccurs="unbounded"/>-->
				<xs:element ref="Distributor" minOccurs="0"/>
				<xs:element name="BusinessOrigin" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="CountryCode" type="xs:string"/>
							<xs:element name="ProvinceCode" type="xs:string"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="IncludePackages" type="xs:string" use="optional">
				<xs:annotation>
					<xs:documentation xml:lang="en">A=All Rates, Y=Include Just Package Rates, N=Don't include Package Rates</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="DetailPackages" type="xs:string">
				<xs:annotation>
					<xs:documentation>Empty, S=Short Detail, A= AllDetail</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="FilterPackagesByType" type="xs:string"/>
			<xs:attribute name="FilterPackagesBySubType1" type="xs:string"/>
			<xs:attribute name="FilterPackagesBySubType3" type="xs:string"/>
			<xs:attribute name="FilterPackagesBySubType2" type="xs:string"/>
			<xs:attribute name="FilterPackagesBySubType4" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="ConfirmationID" type="NumericStringLength10"/>
	<xs:element name="ReservationID" type="NumericStringLength10"/>
	<xs:element name="CancellationID" type="NumericStringLength10"/>
	<xs:element name="ExternalWebCode" type="xs:string"/>
	<xs:element name="ReservationOriginatorCode" type="StringLength1to3"/>
	<xs:element name="ResProfileRPH" type="xs:positiveInteger"/>
	<xs:element name="ResComments">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="ResComment" minOccurs="0" maxOccurs="3">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="ResCommentRPH"/>
							<xs:element name="Comment" type="xs:string"/>
							<!--							<xs:element name="CommentOriginatorCode"  type="xs:string" minOccurs="0"/>-->
							<!--							<xs:element ref="GuestViewable" minOccurs="0"/>-->
						</xs:sequence>
						<xs:attribute name="ReservationActionType">
							<xs:simpleType>
								<xs:restriction base="xs:NMTOKEN">
									<xs:enumeration value="New"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ResCommentRPH" type="xs:positiveInteger"/>
	<xs:element name="ResCreditCards">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ResCreditCard" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ResCreditCard">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ResCreditCardRPH" minOccurs="0"/>
				<xs:element name="CreditCard">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="CreditCardCode" type="xs:string" minOccurs="0"/>
							<xs:element name="CreditCardHolderName" type="xs:string" minOccurs="0"/>
							<xs:element name="CreditCardNumber" type="xs:string" minOccurs="0"/>
							<xs:element name="CreditCardBeginDate" type="xs:dateTime" minOccurs="0"/>
							<xs:element name="CreditCardExpire" type="xs:dateTime" minOccurs="0"/>
							<xs:element name="IssuingBankCode" type="xs:string" minOccurs="0"/>
							<xs:element name="SeriesCode" type="xs:string" minOccurs="0"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ResCreditCardRPH" type="xs:positiveInteger"/>
	<xs:element name="Amount">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="CurrencyCode" type="xs:string" use="required"/>
					<xs:attribute name="e-dtype" type="xs:NMTOKEN" fixed="decimal"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="PaymentInstructions">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="PaymentInstruction">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="ResCreditCardRPH" minOccurs="0"/>
							<!--							<xs:element ref="PaymentDue" minOccurs="0"/>-->
						</xs:sequence>
						<xs:attribute name="PaymentMethodType" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:NMTOKEN">
									<xs:enumeration value="CreditCard"/>
									<xs:enumeration value="DebitCard"/>
									<xs:enumeration value="Voucher"/>
									<xs:enumeration value="Check"/>
									<xs:enumeration value="Other"/>
									<xs:enumeration value="LoyaltyPoints"/>
									<xs:enumeration value="PrepaidDeposit"/>
									<xs:enumeration value="NoGuarantee"/>
									<xs:enumeration value="POS"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="SelectedMemberships">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="SelectedMembership" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="ClientCode" minOccurs="0"/>
							<xs:element ref="SelectedMembershipRPH"/>
							<xs:element ref="ProgramCode"/>
							<xs:element ref="AccountID"/>
							<!--							<xs:element ref="BonusCode" minOccurs="0"/>-->
							<!--							<xs:element ref="PointsEarned" minOccurs="0"/>-->
							<xs:element ref="Autorization" minOccurs="0"/>
							<xs:element ref="BeneficiaryType" minOccurs="0"/>
						</xs:sequence>
						<xs:attribute name="ReservationActionType">
							<xs:simpleType>
								<xs:restriction base="xs:NMTOKEN">
									<xs:enumeration value="DoesNotApply"/>
									<xs:enumeration value="New"/>
									<xs:enumeration value="Change"/>
									<xs:enumeration value="Delete"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ProgramCode" type="xs:string"/>
	<xs:element name="AccountID" type="xs:string"/>
	<xs:element name="BeneficiaryType" type="xs:string"/>
	<xs:element name="Autorization" type="xs:string"/>
	<xs:element name="ClientCode" type="xs:positiveInteger"/>
	<xs:element name="SelectedMembershipRPHs">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="SelectedMembershipRPH" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="SelectedMembershipRPH" type="xs:positiveInteger"/>
	<xs:element name="ResProfiles">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="ResProfile" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="ResProfileRPH"/>
							<xs:element name="CustProfileCreateRQ" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element ref="UniqueId"/>
										<xs:element ref="CustProfile"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="CustProfileCreateRS" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element ref="UniqueId"/>
										<xs:element ref="CustProfile"/>
									</xs:sequence>
									<xs:attribute name="Success" default="Yes">
										<xs:simpleType>
											<xs:restriction base="xs:NMTOKEN">
												<xs:enumeration value="Yes"/>
												<xs:enumeration value="No"/>
												<xs:enumeration value="Part"/>
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="ReservationActionType">
							<xs:simpleType>
								<xs:restriction base="xs:NMTOKEN">
									<xs:enumeration value="DoesNotApply"/>
									<xs:enumeration value="New"/>
									<xs:enumeration value="Change"/>
									<xs:enumeration value="Delete"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>



	<!-- **************************** Profile ************************************** -->
	<xs:element name="CustProfile">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Customer"/>
				<xs:element ref="Preferences" minOccurs="0"/>
				<xs:element ref="Affiliations" minOccurs="0"/>
				<!--				<xs:element ref="Accesses" minOccurs="0"/>-->
				<!--				<xs:element ref="TPA_Extensions" minOccurs="0"/>-->
			</xs:sequence>
			<xs:attribute name="ShareAllMarketInd" default="No">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN">
						<xs:enumeration value="Yes"/>
						<xs:enumeration value="No"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="ShareAllSynchInd" default="No">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN">
						<xs:enumeration value="Yes"/>
						<xs:enumeration value="No"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="Customer">
		<xs:complexType>
			<xs:sequence>
				<xs:choice>
					<xs:sequence>
						<xs:element ref="PersonName" maxOccurs="unbounded"/>
						<xs:element ref="CustTelephone" minOccurs="0" maxOccurs="unbounded"/>
						<xs:element ref="CustEmail" minOccurs="0" maxOccurs="unbounded"/>
					</xs:sequence>
					<xs:sequence>
						<xs:element ref="CustTelephone" maxOccurs="unbounded"/>
						<xs:element ref="CustEmail" minOccurs="0" maxOccurs="unbounded"/>
					</xs:sequence>
					<xs:choice>
						<xs:element ref="CustEmail" maxOccurs="unbounded"/>
					</xs:choice>
				</xs:choice>
				<xs:element ref="CustAddress" minOccurs="0" maxOccurs="unbounded"/>
				<!--				<xs:element ref="CustURL" minOccurs="0" maxOccurs="unbounded"/>-->
				<!--				<xs:element ref="CitizenCountryName" minOccurs="0" maxOccurs="unbounded"/>-->
				<!--				<xs:element name="PhysChallName" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>-->
				<!--				<xs:element name="PetInfo" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>-->
				<!--				<xs:element ref="PaymentForm" minOccurs="0" maxOccurs="unbounded"/>-->
				<!--				<xs:element ref="RelatedTraveler" minOccurs="0" maxOccurs="unbounded"/>-->
				<!--				<xs:element ref="Contact" minOccurs="0" maxOccurs="unbounded"/>-->
				<!--				<xs:element ref="Document" minOccurs="0" maxOccurs="unbounded"/>-->
				<!--				<xs:element ref="CustLoyalty" minOccurs="0" maxOccurs="unbounded"/>-->
				<!--				<xs:element ref="TPA_Extensions" minOccurs="0"/>-->
			</xs:sequence>
			<xs:attribute name="Gender">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN">
						<xs:enumeration value="Male"/>
						<xs:enumeration value="Female"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="Deceased">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN">
						<xs:enumeration value="Yes"/>
						<xs:enumeration value="No"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="LockoutType" type="xs:string"/>
			<xs:attribute name="ShareSynchInd" default="Inherit">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN">
						<xs:enumeration value="Yes"/>
						<xs:enumeration value="No"/>
						<xs:enumeration value="Inherit"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="ShareMarketInd" default="Inherit">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN">
						<xs:enumeration value="Yes"/>
						<xs:enumeration value="No"/>
						<xs:enumeration value="Inherit"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="BirthDate" type="xs:string"/>
			<xs:attribute name="Currency" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="PersonName">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="NamePrefix" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="GivenName" type="xs:string" minOccurs="0"/>
				<xs:element name="MiddleName" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="Surname" type="xs:string"/>
				<xs:element name="NameSuffix" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="NameTitle" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="DefaultInd">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN">
						<xs:enumeration value="Yes"/>
						<xs:enumeration value="No"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="ShareSynchInd" default="Inherit">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN">
						<xs:enumeration value="Yes"/>
						<xs:enumeration value="No"/>
						<xs:enumeration value="Inherit"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="ShareMarketInd" default="Inherit">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN">
						<xs:enumeration value="Yes"/>
						<xs:enumeration value="No"/>
						<xs:enumeration value="Inherit"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="NameType" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="CustTelephone">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Telephone"/>
			</xs:sequence>
			<xs:attribute name="DefaultInd">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN">
						<xs:enumeration value="Yes"/>
						<xs:enumeration value="No"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="ShareSynchInd" default="Inherit">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN">
						<xs:enumeration value="Yes"/>
						<xs:enumeration value="No"/>
						<xs:enumeration value="Inherit"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="ShareMarketInd" default="Inherit">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN">
						<xs:enumeration value="Yes"/>
						<xs:enumeration value="No"/>
						<xs:enumeration value="Inherit"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="PhoneUseType" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Telephone">
		<xs:complexType>
			<xs:attribute name="PhoneTechType" type="xs:string" use="optional"/>
			<xs:attribute name="CountryAccessCode" type="xs:string" use="optional"/>
			<xs:attribute name="AreaCityCode" type="xs:string" use="optional"/>
			<xs:attribute name="PhoneNumber" type="xs:string" use="required"/>
			<xs:attribute name="Extension" type="xs:string" use="optional"/>
			<xs:attribute name="PIN" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="CustEmail">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="DefaultInd">
						<xs:simpleType>
							<xs:restriction base="xs:NMTOKEN">
								<xs:enumeration value="Yes"/>
								<xs:enumeration value="No"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
					<xs:attribute name="ShareSynchInd" default="Inherit">
						<xs:simpleType>
							<xs:restriction base="xs:NMTOKEN">
								<xs:enumeration value="Yes"/>
								<xs:enumeration value="No"/>
								<xs:enumeration value="Inherit"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
					<xs:attribute name="ShareMarketInd" default="Inherit">
						<xs:simpleType>
							<xs:restriction base="xs:NMTOKEN">
								<xs:enumeration value="Yes"/>
								<xs:enumeration value="No"/>
								<xs:enumeration value="Inherit"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
					<xs:attribute name="EmailType" type="xs:string"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="CustAddress">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Address"/>
			</xs:sequence>
			<xs:attribute name="DefaultInd">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN">
						<xs:enumeration value="Yes"/>
						<xs:enumeration value="No"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="ShareSynchInd" default="Inherit">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN">
						<xs:enumeration value="Yes"/>
						<xs:enumeration value="No"/>
						<xs:enumeration value="Inherit"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="ShareMarketInd" default="Inherit">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN">
						<xs:enumeration value="Yes"/>
						<xs:enumeration value="No"/>
						<xs:enumeration value="Inherit"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="AddressType">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN">
						<xs:enumeration value="Home"/>
						<xs:enumeration value="Business"/>
						<xs:enumeration value="Delivery"/>
						<xs:enumeration value="Mailing"/>
						<xs:enumeration value="Billing"/>
						<xs:enumeration value="CreditCard"/>
						<xs:enumeration value="Other"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="Address">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="StreetNmbr" minOccurs="0">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attribute name="POBox" type="xs:string"/>
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="BldgRoom" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="AddressLine" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attribute name="ParsedInd">
									<xs:simpleType>
										<xs:restriction base="xs:NMTOKEN">
											<xs:enumeration value="Yes"/>
											<xs:enumeration value="No"/>
										</xs:restriction>
									</xs:simpleType>
								</xs:attribute>
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="CityName" minOccurs="0">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attribute name="PostalCode" type="xs:string"/>
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="StateProv" minOccurs="0">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attribute name="StateCode" type="xs:string"/>
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="CountryName" minOccurs="0">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attribute name="CountryCode" type="xs:string"/>
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Affiliations">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Employer" minOccurs="0" maxOccurs="unbounded"/>
				<!--				<xs:element ref="Organization" minOccurs="0" maxOccurs="unbounded"/>-->
				<!--				<xs:element ref="TravelArranger" minOccurs="0" maxOccurs="unbounded"/>-->
				<!--				<xs:element ref="TravelClub" minOccurs="0" maxOccurs="unbounded"/>-->
				<!--				<xs:element ref="Insurance" minOccurs="0" maxOccurs="unbounded"/>-->
				<!--				<xs:element ref="TPA_Extensions" minOccurs="0"/>-->
			</xs:sequence>
			<xs:attribute name="ShareSynchInd" default="Inherit">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN">
						<xs:enumeration value="Yes"/>
						<xs:enumeration value="No"/>
						<xs:enumeration value="Inherit"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="ShareMarketInd" default="Inherit">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN">
						<xs:enumeration value="Yes"/>
						<xs:enumeration value="No"/>
						<xs:enumeration value="Inherit"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="Employer">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="EmployerName" minOccurs="0"/>
				<!--				<xs:element ref="RelatedEmployerName" minOccurs="0" maxOccurs="unbounded"/>-->
				<!--				<xs:element ref="EmployeeName" minOccurs="0"/>-->
				<!--				<xs:element ref="InternalRefNmbr" minOccurs="0" maxOccurs="unbounded"/>-->
				<!--				<xs:element ref="EmplTravelSrvcVendor" minOccurs="0" maxOccurs="unbounded"/>-->
				<!--				<xs:element ref="EmployerLoyalty" minOccurs="0" maxOccurs="unbounded"/>-->
			</xs:sequence>
			<xs:attribute name="DefaultInd">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN">
						<xs:enumeration value="Yes"/>
						<xs:enumeration value="No"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="OfficeType" type="xs:string"/>
			<xs:attribute name="ExpireDate" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="EmployerName">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="CompanyName"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="CompanyName">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="CompanyCode" type="xs:string"/>
					<xs:attribute name="CodeContext" type="xs:string"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="UniqueId">
		<xs:complexType>
			<xs:attribute name="URL" type="xs:string"/>
			<xs:attribute name="Type" type="xs:string" use="required"/>
			<xs:attribute name="Id" type="xs:ID"/>
			<xs:attribute name="Instance" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Preferences">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="PrefCollection" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="ShareSynchInd" default="Inherit">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN">
						<xs:enumeration value="Yes"/>
						<xs:enumeration value="No"/>
						<xs:enumeration value="Inherit"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="ShareMarketInd" default="Inherit">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN">
						<xs:enumeration value="Yes"/>
						<xs:enumeration value="No"/>
						<xs:enumeration value="Inherit"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="PrefCollection">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="CommonPref" minOccurs="0" maxOccurs="unbounded"/>
				<!--				<xs:element ref="CarRentalPref" minOccurs="0" maxOccurs="unbounded"/>-->
				<!--				<xs:element ref="AirlinesPref" minOccurs="0" maxOccurs="unbounded"/>-->
				<!--				<xs:element ref="HotelPref" minOccurs="0" maxOccurs="unbounded"/>-->
				<!--				<xs:element ref="OtherSrvcPref" minOccurs="0" maxOccurs="unbounded"/>-->
				<!--				<xs:element ref="TPA_Extensions" minOccurs="0"/>-->
			</xs:sequence>
			<xs:attribute name="ShareSynchInd" default="Inherit">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN">
						<xs:enumeration value="Yes"/>
						<xs:enumeration value="No"/>
						<xs:enumeration value="Inherit"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="ShareMarketInd" default="Inherit">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN">
						<xs:enumeration value="Yes"/>
						<xs:enumeration value="No"/>
						<xs:enumeration value="Inherit"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="TravelType" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="CommonPref">
		<xs:complexType>
			<xs:sequence>
				<!--				<xs:element ref="NamePref" minOccurs="0" maxOccurs="unbounded"/>-->
				<!--				<xs:element ref="PhonePref" minOccurs="0" maxOccurs="unbounded"/>-->
				<!--				<xs:element ref="AddressPref" minOccurs="0" maxOccurs="unbounded"/>-->
				<!--				<xs:element ref="PaymentFormPref" minOccurs="0" maxOccurs="unbounded"/>-->
				<!--				<xs:element ref="InterestPref" minOccurs="0" maxOccurs="unbounded"/>-->
				<!--				<xs:element ref="InsurancePref" minOccurs="0" maxOccurs="unbounded"/>-->
				<!--				<xs:element ref="SeatingPref" minOccurs="0" maxOccurs="unbounded"/>-->
				<!--				<xs:element ref="TicketDistribPref" minOccurs="0" maxOccurs="unbounded"/>-->
				<!--				<xs:element ref="MediaEntertainPref" minOccurs="0" maxOccurs="unbounded"/>-->
				<!--				<xs:element ref="PetInfoPref" minOccurs="0" maxOccurs="unbounded"/>-->
				<!--				<xs:element ref="MealPref" minOccurs="0" maxOccurs="unbounded"/>-->
				<!--				<xs:element ref="LoyaltyPref" minOccurs="0" maxOccurs="unbounded"/>-->
				<!--				<xs:element ref="SpecRequestPref" minOccurs="0" maxOccurs="unbounded"/>-->
				<!--				<xs:element ref="RelatedTravelerPref" minOccurs="0" maxOccurs="unbounded"/>-->
				<!--				<xs:element ref="TPA_Extensions" minOccurs="0"/>-->
			</xs:sequence>
			<xs:attribute name="ShareSynchInd" default="Inherit">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN">
						<xs:enumeration value="Yes"/>
						<xs:enumeration value="No"/>
						<xs:enumeration value="Inherit"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="ShareMarketInd" default="Inherit">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN">
						<xs:enumeration value="Yes"/>
						<xs:enumeration value="No"/>
						<xs:enumeration value="Inherit"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="SmokingInd">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN">
						<xs:enumeration value="Yes"/>
						<xs:enumeration value="No"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="PrimaryLanguage" type="xs:string"/>
			<xs:attribute name="AltLanguage" type="xs:string"/>
		</xs:complexType>
	</xs:element>

</xs:schema>