<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>com.code.aon</groupId>
		<artifactId>aon.parent</artifactId>
		<version>8.100.2</version>
	</parent>
	<groupId>com.esferalia.aon</groupId>
	<artifactId>aon.aeat</artifactId>
	<name>AON AEAT</name>
	<dependencies>
	</dependencies>
	<build>
		<plugins>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>jaxb2-maven-plugin</artifactId>
				<!--version>1.6</version-->
				<executions>
					<execution>
						<id>xjc-2016</id>
						<goals>
							<goal>xjc</goal>
						</goals>
						<configuration>
							<sources>
                    						<source>src/main/xsd/AEATRetenciones2016.xsd</source>
					                </sources>
							<!-- The name of your generated source package -->
							<packageName>com.esferalia.aon.aeat.jaxb</packageName> 
						</configuration>
                                        </execution>
					<execution>
						<id>xjc-2017</id>
						<goals>
							<goal>xjc</goal>
						</goals>
						<configuration>
							<sources>
                    						<source>src/main/xsd/AEATRetenciones2017.xsd</source>
					                </sources>
							<packageName>com.esferalia.aon.aeat.v2017.jaxb</packageName> 
					                <!--
					                    Don't clear the output directory before generating the sources.
					                    Clearing the output directory removes the 2016 schema from above.
					                -->
					                <clearOutputDir>false</clearOutputDir>
						</configuration>
                                        </execution>
				</executions>
			</plugin>
		</plugins>
	</build>

</project>
