package com.esferalia.aon.gwt.template.server.imports;

public interface IConstants {
	String[] REGISTRY_TITLES = { 
		IConstants.TIPO, IConstants.CUENTA, IConstants.CUENTA_CONTABLE, IConstants.CIF, IConstants.NOMBRE,IConstants.DOMICILIO,
		IConstants.DIRECCION, IConstants.DIRECCIÓN, IConstants.CP, IConstants.CODIGO_POSTAL, IConstants.CÓDIGO_POSTAL, IConstants.POBLACIÓN,
		IConstants.POBLACION, IConstants.CIUDAD, IConstants.PROVINCIA, IConstants.IBAN, IConstants.PAÍS, IConstants.PAIS,
		IConstants.TELEFONO, IConstants.TELÉFONO, IConstants.EMAIL, IConstants.MAIL, IConstants.CORREO_ELECTRONICO, IConstants.CORREO_ELECTRÓNICO,
		IConstants.FORMA_DE_PAGO, IConstants.MOVIL, IConstants.MÓVIL, IConstants.BIC, IConstants.BIC_SWIFT, IConstants.BBAN, IConstants.CCC
	};
	
	String[] DIARY_TITLES = {
		IConstants.ASIENTO, IConstants.N_DIARIO, IConstants.APUNTE, IConstants.FECHA, IConstants.SEGURIDAD, IConstants.ACTIVIDAD,
		IConstants.FACTURA, IConstants.DOCUMENTO, IConstants.SUBCUENTA, IConstants.CUENTA, IConstants.TITULO_DE_SUBCUENTA, 
		IConstants.TÍTULO_DE_SUBCUENTA, IConstants.DESC_CUENTA, IConstants.CONTRAPARTIDA, IConstants.CONTRAP, IConstants.DESC_CONTRAP,
		IConstants.CONCEPTO, IConstants.TIPO, IConstants.REFERENCIA, IConstants.DEBE, IConstants.HABER, IConstants.COMENTARIOS
	};
	
	String[] FEE_TITLES = {
			IConstants.CLIENTE, IConstants.PRODUCTO, IConstants.CANTIDAD, IConstants.PRECIO, IConstants.DESCUENTO, IConstants.FECHA_INICIO,
			IConstants.FECHA_FIN, IConstants.FECHA_FACTURACION, IConstants.FECHA_FACTURACIÓN, IConstants.PERIODO, IConstants.COMERCIAL, 
			IConstants.CENTRO_DE_TRABAJO, IConstants.CENTRO_TRABAJO, IConstants.GRUPO, IConstants.GRUPO_FACTURACION, IConstants.GRUPO_FACTURACIÓN, 
			IConstants.GRUPO_DE_FACTURACION, IConstants.GRUPO_DE_FACTURACIÓN, IConstants.CONFIDENCIAL, IConstants.DESCRIPCION,
			IConstants.DESCRIPCIÓN, IConstants.EXPEDIENTE, IConstants.DETALLE, IConstants.DETALLE1, IConstants.DETALLE_1, IConstants.DETALLE2, IConstants.DETALLE_2,
			IConstants.DETALLE3, IConstants.DETALLE_3, IConstants.CODIGO_DE_BARRAS, IConstants.CÓDIGO_DE_BARRAS, IConstants.CODIGO_BARRAS, IConstants.CÓDIGO_BARRAS,
			IConstants.BARCODE, IConstants.NUMERO_DE_SERIE,IConstants.NÚMERO_DE_SERIE, IConstants.NUMERO_SERIE,IConstants.NÚMERO_SERIE, IConstants.SERIAL_NUMBER,
			IConstants.LINEA, IConstants.LÍNEA
		};
	
	String ACTIVIDAD = "ACTIVIDAD";
	String ASIENTO = "ASIENTO";
	String APUNTE = "APUNTE";
	String BIC = "BIC";
	String BIC_SWIFT = "BIC/SWIFT";
	String CIF = "CIF";
	String CIUDAD = "CIUDAD";
	String CODIGO_POSTAL = "CODIGO POSTAL";
	String CÓDIGO_POSTAL = "CÓDIGO POSTAL";
	String COMENTARIOS = "COMENTARIOS";
	String CONCEPTO = "CONCEPTO";
	String CONTRAPARTIDA = "CONTRAPARTIDA";
	String CONTRAP = "CONTRAP.";
	String CORREO_ELECTRONICO = "CORREO ELECTRONICO";
	String CORREO_ELECTRÓNICO = "CORREO ELECTRÓNICO";
	String CP = "C.P.";
	String CUENTA = "CUENTA";
	String CUENTA_CONTABLE = "CUENTA CONTABLE";
	String DEBE = "DEBE";
	String DESC_CONTRAP = "DESC. CONTRAP.";
	String DESC_CUENTA = "DESC. CUENTA";
	String DIRECCION = "DIRECCION";
	String DIRECCIÓN = "DIRECCIÓN";
	String DOCUMENTO = "DOCUMENTO";
	String DOMICILIO = "DOMICILIO";
	String EMAIL = "EMAIL";
	String FACTURA = "FACTURA";
	String FECHA = "FECHA";
	String FORMA_DE_PAGO = "FORMA DE PAGO";
	String FORMA_PAGO = "FORMA PAGO";
	String TIPO_DE_PAGO = "TIPO DE PAGO";
	String TIPO_PAGO = "TIPO PAGO";
	String HABER = "HABER";
	String IBAN = "IBAN";	
	String BBAN = "BBAN";
	String CCC = "CCC";
	String N_ASIENTO = "Nº ASIENTO";
	String N_APUNTE = "Nº APUNTE";
	String N_DIARIO = "Nº DIARIO";
	String NOMBRE = "NOMBRE";
	String MAIL = "MAIL";	
	String MÓVIL = "MÓVIL";
	String MOVIL = "MOVIL";
	String PAÍS = "PAÍS";
	String PAIS = "PAIS";
	String POBLACIÓN = "POBLACIÓN";
	String POBLACION = "POBLACION";
	String PROVINCIA = "PROVINCIA";
	String REFERENCIA = "REFERENCIA";
	String SEGURIDAD = "SEGURIDAD";
	String SUBCUENTA = "SUBCUENTA";
	String TELÉFONO = "TELÉFONO";
	String TELEFONO = "TELEFONO";
	String TIPO = "TIPO";
	String TITULO_DE_SUBCUENTA = "TITULO DE SUBCUENTA";
	String TÍTULO_DE_SUBCUENTA = "TÍTULO DE SUBCUENTA";
	
	String TRUE = "TRUE";
	String SI = "SI";

	String CLIENTE = "CLIENTE";
	String PRODUCTO = "PRODUCTO";
	String CANTIDAD = "CANTIDAD";
	String PRECIO = "PRECIO";
	String DESCUENTO = "DESCUENTO";
	String FECHA_INICIO = "FECHA INICIO";
	String FECHA_FIN = "FECHA FIN";
	String FECHA_FACTURACION = "FECHA FACTURACION";
	String FECHA_FACTURACIÓN = "FECHA FACTURACIÓN";
	String PERIODO = "PERIODO";
	String COMERCIAL = "COMERCIAL";
	String CENTRO_DE_TRABAJO = "CENTRO DE TRABAJO";
	String CENTRO_TRABAJO = "CENTRO TRABAJO";
	String GRUPO = "GRUPO";
	String GRUPO_FACTURACION = "GRUPO FACTURACION";
	String GRUPO_FACTURACIÓN = "GRUPO FACTURACIÓN";
	String GRUPO_DE_FACTURACION = "GRUPO DE FACTURACION";
	String GRUPO_DE_FACTURACIÓN = "GRUPO DE FACTURACIÓN";
	String CONFIDENCIAL = "CONFIDENCIAL";
	String DESCRIPCION = "DESCRIPCION";
	String DESCRIPCIÓN = "DESCRIPCIÓN";
	String EXPEDIENTE = "EXPEDIENTE";
	String DETALLE = "DETALLE";
	String DETALLE1 = "DETALLE1";
	String DETALLE_1 = "DETALLE 1";
	String DETALLE2 = "DETALLE2";
	String DETALLE_2 = "DETALLE 2";
	String DETALLE3 = "DETALLE3";
	String DETALLE_3 = "DETALLE 3";
	String CODIGO_DE_BARRAS = "CODIGO DE BARRAS";
	String CÓDIGO_DE_BARRAS = "CÓDIGO DE BARRAS";
	String CODIGO_BARRAS = "CODIGO BARRAS";
	String CÓDIGO_BARRAS = "CÓDIGO BARRAS";
	String BARCODE = "BARCODE";
	String NUMERO_DE_SERIE = "NUMERO DE SERIE";
	String NÚMERO_DE_SERIE = "NÚMERO DE SERIE";
	String NUMERO_SERIE = "NUMERO SERIE";
	String NÚMERO_SERIE = "NÚMERO SERIE";
	String SERIAL_NUMBER = "SERIAL NUMBER";
	String LINEA = "LINEA";
	String LÍNEA = "LÍNEA";


	


}
