package com.esferalia.aon.gwt.template.server.imports;

public interface IConstants {
	String[] REGISTRY_TITLES = { 
		IConstants.TIPO, IConstants.CUENTA, IConstants.CUENTA_CONTABLE, IConstants.CIF, IConstants.NOMBRE, IConstants.ALIAS, 
		IConstants.NOMBRE_COMERCIAL,IConstants.DOMICILIO,IConstants.DIRECCION, IConstants.DIRECCION2, IConstants.CP, IConstants.CODIGO_POSTAL, IConstants.CODIGO_POSTAL2, IConstants.POBLACION2,
		IConstants.POBLACION, IConstants.CIUDAD, IConstants.PROVINCIA, IConstants.IBAN, IConstants.PAIS2, IConstants.PAIS,
		IConstants.TELEFONO, IConstants.TELEFONO2, IConstants.EMAIL, IConstants.MAIL, IConstants.CORREO_ELECTRONICO, IConstants.CORREO_ELECTRONICO2,
		IConstants.FORMA_DE_PAGO, IConstants.MOVIL, IConstants.MOVIL2, IConstants.BIC, IConstants.BIC_SWIFT, IConstants.BBAN, IConstants.CCC, 
		IConstants.TRANSACCION, IConstants.TRANSACCION2
	};
	
	String[] DIARY_TITLES = {
		IConstants.ASIENTO, IConstants.N_DIARIO, IConstants.APUNTE, IConstants.FECHA, IConstants.SEGURIDAD, IConstants.ACTIVIDAD,
		IConstants.FACTURA, IConstants.DOCUMENTO, IConstants.SUBCUENTA, IConstants.CUENTA, IConstants.TITULO_DE_SUBCUENTA, 
		IConstants.TITULO_DE_SUBCUENTA2, IConstants.DESC_CUENTA, IConstants.CONTRAPARTIDA, IConstants.CONTRAP, IConstants.DESC_CONTRAP,
		IConstants.CONCEPTO, IConstants.TIPO, IConstants.REFERENCIA, IConstants.DEBE, IConstants.HABER, IConstants.COMENTARIOS
	};
	
	String[] FEE_TITLES = {
			IConstants.CLIENTE, IConstants.PRODUCTO, IConstants.CANTIDAD, IConstants.PRECIO, IConstants.DESCUENTO, IConstants.FECHA_INICIO,
			IConstants.FECHA_FIN, IConstants.FECHA_FACTURACION, IConstants.FECHA_FACTURACION2, IConstants.PERIODO, IConstants.COMERCIAL, 
			IConstants.CENTRO_DE_TRABAJO, IConstants.CENTRO_TRABAJO, IConstants.GRUPO, IConstants.GRUPO_FACTURACION, IConstants.GRUPO_FACTURACION2, 
			IConstants.GRUPO_DE_FACTURACION, IConstants.GRUPO_DE_FACTURACION2, IConstants.CONFIDENCIAL, IConstants.DESCRIPCION,
			IConstants.DESCRIPCION2, IConstants.EXPEDIENTE, IConstants.DETALLE, IConstants.DETALLE1, IConstants.DETALLE_1, IConstants.DETALLE2, IConstants.DETALLE_2,
			IConstants.DETALLE3, IConstants.DETALLE_3, IConstants.CODIGO_DE_BARRAS, IConstants.CODIGO_DE_BARRAS2, IConstants.CODIGO_BARRAS, IConstants.CODIGO_BARRAS2,
			IConstants.BARCODE, IConstants.NUMERO_DE_SERIE,IConstants.NUMERO_DE_SERIE2, IConstants.NUMERO_SERIE,IConstants.NUMERO_SERIE2, IConstants.SERIAL_NUMBER,
			IConstants.LINEA, IConstants.LINEA2
		};
	
	String ACTIVIDAD = "ACTIVIDAD";
	String ALIAS = "ALIAS";
	String ASIENTO = "ASIENTO";
	String APUNTE = "APUNTE";
	String BIC = "BIC";
	String BIC_SWIFT = "BIC/SWIFT";
	String CIF = "CIF";
	String CIUDAD = "CIUDAD";
	String CODIGO_POSTAL = "CODIGO POSTAL";
	String CODIGO_POSTAL2 = "CÓDIGO POSTAL";
	String CODIGO_PRODUCTO = "CODIGO PRODUCTO";
	String CODIGO_PRODUCTO2 = "CÓDIGO PRODUCTO";
	String NOMBRE_PRODUCTO = "NOMBRE PRODUCTO";
	String COMENTARIOS = "COMENTARIOS";
	String CONCEPTO = "CONCEPTO";
	String CONTRAPARTIDA = "CONTRAPARTIDA";
	String CONTRAP = "CONTRAP.";
	String CORREO_ELECTRONICO = "CORREO ELECTRONICO";
	String CORREO_ELECTRONICO2 = "CORREO ELECTRÓNICO";
	String CP = "C.P.";
	String CUENTA = "CUENTA";
	String CUENTA_CONTABLE = "CUENTA CONTABLE";
	String DEBE = "DEBE";
	String DESC_CONTRAP = "DESC. CONTRAP.";
	String DESCRIPCION_CONTRAPARTIDA = "DESCRIPCION CONTRAPARTIDA";
	String DESC_CUENTA = "DESC. CUENTA";
	String DIRECCION = "DIRECCION";
	String DIRECCION2 = "DIRECCIÓN";
	String DOCUMENTO = "DOCUMENTO";
	String DOMICILIO = "DOMICILIO";
	String EMAIL = "EMAIL";
	String FACTURA = "FACTURA";
	String FECHA = "FECHA";
	String FECHA_IVA = "FECHA IVA";
	String FICHERO = "FICHERO";
	String FORMA_DE_PAGO = "FORMA DE PAGO";
	String FORMA_PAGO = "FORMA PAGO";
	String TIPO_DE_PAGO = "TIPO DE PAGO";
	String TIPO_PAGO = "TIPO PAGO";
	String TIPO_DOCUMENTO = "TIPO DOCUMENTO";
	String TIPO_DE_DOCUMENTO = "TIPO DE DOCUMENTO";
	String TIPO_OPERACION = "TIPO OPERACION";
	String TIPO_OPERACION2 = "TIPO OPERACIÓN";
	String TIPO_DE_OPERACION = "TIPO DE OPERACION";
	String TIPO_DE_OPERACION2 = "TIPO DE OPERACIÓN";
	String TIPO_DE_VIA = "TIPO DE VIA";
	String TIPO_DE_VIA2 = "TIPO DE VÍA";
	String TIPO_FACTURA = "TIPO FACTURA";
	String HABER = "HABER";
	String IBAN = "IBAN";	
	String BBAN = "BBAN";
	String CCC = "CCC";
	String N_ASIENTO = "Nº ASIENTO";
	String N_APUNTE = "Nº APUNTE";
	String N_DIARIO = "Nº DIARIO";
	String NOMBRE = "NOMBRE";
	String RAZON_SOCIAL = "RAZON SOCIAL";
	String RAZON_SOCIAL2 = "RAZÓN SOCIAL";
	String MAIL = "MAIL";	
	String MOVIL = "MOVIL";
	String MOVIL2 = "MÓVIL";
	String PAIS = "PAIS";
	String PAIS2 = "PAÍS";
	String PAIS_DOCUMENTO = "PAIS DOCUMENTO";
	String PAIS2_DOCUMENTO = "PAÍS DOCUMENTO";
	String PAIS_DE_DOCUMENTO = "PAIS DE DOCUMENTO";
	String PAIS2_DE_DOCUMENTO = "PAÍS DE DOCUMENTO";
	String POBLACION = "POBLACION";
	String POBLACION2 = "POBLACIÓN";
	String PROVINCIA = "PROVINCIA";
	String REFERENCIA = "REFERENCIA";
	String RESTO_DIRECCION = "RESTO DIRECCION";
	String RESTO_DIRECCION2 = "RESTO DIRECCIÓN";
	String SEGURIDAD = "SEGURIDAD";
	String SUBCUENTA = "SUBCUENTA";
	String SUPLIDO = "SUPLIDO";
	String TELEFONO = "TELEFONO";
	String TELEFONO2 = "TELÉFONO";
	String TIPO = "TIPO";
	String TITULO_DE_SUBCUENTA = "TITULO DE SUBCUENTA";
	String TITULO_DE_SUBCUENTA2 = "TÍTULO DE SUBCUENTA";
	
	String TRUE = "TRUE";
	String VERDADERO = "VERDADERO";
	String SI = "SI";

	String CLIENTE = "CLIENTE";
	String PRODUCTO = "PRODUCTO";
	String CANTIDAD = "CANTIDAD";
	String PRECIO = "PRECIO";
	String DESCUENTO = "DESCUENTO";
	String IMPORTE = "IMPORTE";
	String FECHA_INICIO = "FECHA INICIO";
	String FECHA_FIN = "FECHA FIN";
	String FECHA_FACTURACION = "FECHA FACTURACION";
	String FECHA_FACTURACION2 = "FECHA FACTURACIÓN";
	String PERIODO = "PERIODO";
	String COMERCIAL = "COMERCIAL";
	String NOMBRE_COMERCIAL = "NOMBRE COMERCIAL";
	String CENTRO_DE_TRABAJO = "CENTRO DE TRABAJO";
	String CENTRO_TRABAJO = "CENTRO TRABAJO";
	String GRUPO = "GRUPO";
	String GRUPO_FACTURACION = "GRUPO FACTURACION";
	String GRUPO_FACTURACION2 = "GRUPO FACTURACIÓN";
	String GRUPO_DE_FACTURACION = "GRUPO DE FACTURACION";
	String GRUPO_DE_FACTURACION2 = "GRUPO DE FACTURACIÓN";
	String CONFIDENCIAL = "CONFIDENCIAL";
	String DESCRIPCION = "DESCRIPCION";
	String DESCRIPCION2 = "DESCRIPCIÓN";
	String EXPEDIENTE = "EXPEDIENTE";
	String DETALLE = "DETALLE";
	String DETALLE1 = "DETALLE1";
	String DETALLE_1 = "DETALLE 1";
	String DETALLE2 = "DETALLE2";
	String DETALLE_2 = "DETALLE 2";
	String DETALLE3 = "DETALLE3";
	String DETALLE_3 = "DETALLE 3";
	String CODIGO_DE_BARRAS = "CODIGO DE BARRAS";
	String CODIGO_DE_BARRAS2 = "CÓDIGO DE BARRAS";
	String CODIGO_BARRAS = "CODIGO BARRAS";
	String CODIGO_BARRAS2 = "CÓDIGO BARRAS";
	String BARCODE = "BARCODE";
	String NUMERO_DE_SERIE = "NUMERO DE SERIE";
	String AGENTE_DE_SOPORTE = "AGENTE DE SOPORTE";
	String NUMERO_DE_SERIE2 = "NÚMERO DE SERIE";
	String NUMERO_SERIE = "NUMERO SERIE";
	String NUMERO_SERIE2 = "NÚMERO SERIE";
	String SERIAL_NUMBER = "SERIAL NUMBER";
	String LINEA = "LINEA";
	String LINEA2 = "LÍNEA";
	String SEGMENTO = "SEGMENTO";
	
	String SERIE = "SERIE";
	String SERIES = "SERIES";
	
	String NUMBER = "NUMBER";
	String NUMERO = "NUMERO";
	String NUMERO2 = "NÚMERO";
	String NUMERO_FACTURA = "NUMERO FACTURA";
	String NUMERO_DE_FACTURA = "NUMERO DE FACTURA";
	String CODIGO_REFERENCIA = "CODIGO REFERENCIA";
	String CODIGO_DE_REFERENCIA = "CODIGO DE REFERENCIA";
	
	String NIF = "NIF";
	String CUENTA_CONTRAPARTE = "CUENTA CONTRAPARTE";
	String TERCERO = "TERCERO";
	String OBSERVACIONES = "OBSERVACIONES";
	String CUENTA_BASE = "CUENTA BASE";
	String CUENTA_EXPLOTACION = "CUENTA EXPLOTACION";
	String CUENTA_DE_EXPLOTACION = "CUENTA DE EXPLOTACION";
	String DESCRIPCION_CUENTA = "DESCRIPCION CUENTA";
	String CONCEPTO_DETALLE = "CONCEPTO DETALLE";
	
	String BASE = "BASE";
	String BASE_IMPONIBLE = "BASE IMPONIBLE";
	
	String IGIC = "IGIC";
	String IMPUESTO = "IMPUESTO";
	String IMPORTE_NETO = "I. NETO";
	String IMPORTE_BRUTO = "I. BRUTO";
	String IVA = "IVA";
	String CUOTA_IMPUESTO = "CUOTA IMPUESTO";
	String CUOTA_IVA = "CUOTA IVA";
	String CUOTA_IGIC = "CUOTA IGIC";
	String RE = "RE";
	String CUOTA_RE = "CUOTA RE";
	String RETENCION = "RETENCION";
	String IRPF = "IRPF";
	String CUOTA_RETENCION = "CUOTA RETENCION";
	String CUOTA_IRPF = "CUOTA IRPF";
	String TOTAL = "TOTAL";
	String TOTAL_FACTURA = "TOTAL FACTURA";
	String IMPORTE_TOTAL = "IMPORTE TOTAL";

	String CLAVE_RETENCION = "CLAVE RETENCION";
	String SUBCLAVE_RETENCION = "SUBCLAVE RETENCION";
	
	String VENCIMIENTO = "VENCIMIETO";
	String FECHA_VTO = "FECHA VTO";
	String IMPORTE_VTO = "IMPORTE VTO";
	String FORMA_PAGO_VTO = "FORMA PAGO VTO";
	String FORMA_DE_PAGO_VTO = "FORMA DE PAGO VTO";
	
	String CUENTA_TESORERIA = "CUENTA TESORERIA";
	String PAGO_POR_CAJA = "PAGO POR CAJA";
	
	String SERVICIO = "SERVICIO";
	String SERVICE = "SERVICE";
	
	String TRANSACCION = "TRANSACCION";
	String TRANSACCION2 = "TRANSACCIÓN";

}
