package com.esferalia.aon.ui.sepe.controller;

import java.util.LinkedList;
import java.util.List;
import javax.faces.model.SelectItem;
import com.esferalia.aon.payroll.enumeration.certificados.*;

/** 
 * Autogenerated class
 * 
 * Certific@2 code tables Collections.
 * Generation main class: com.esferalia.aon.payroll.sepe.CertificadosCodeTablesWriter
*/ 

public class CertificadosCollectionsController {

	/** 
	 *  ------------------------------------------------------------------------
	 *  TABLA      	DESCRIPCION						FECHA ÚLTIMA ACTUALIZACIÓN.
	 * No description found
	 *  ------------------------------------------------------------------------
	 */ 
	private List<SelectItem> CertificadosCodeTablesCodeList;

	public List<SelectItem> getCertificadosCodeTablesCodeList() {
		if (CertificadosCodeTablesCodeList == null) {
			CertificadosCodeTablesCodeList = new LinkedList<SelectItem>();
			CertificadosCodeTables[] el = CertificadosCodeTables.values();
			for (CertificadosCodeTables obj : el) {
				if(obj.isActive()){
					String name = (obj.getDescription().length()>80?(obj.getDescription().substring(0, 80)+"..."):obj.getDescription());
					SelectItem item = new SelectItem(obj, name);
					CertificadosCodeTablesCodeList.add(item);
				}
			}
		}
		return CertificadosCodeTablesCodeList;
	}

	/** 
	 *  ------------------------------------------------------------------------
	 *  TABLA      	DESCRIPCION						FECHA ÚLTIMA ACTUALIZACIÓN.
	 * No description found
	 *  ------------------------------------------------------------------------
	 */ 
	private List<SelectItem> DCODEDTCCodeList;

	public List<SelectItem> getDCODEDTCCodeList() {
		if (DCODEDTCCodeList == null) {
			DCODEDTCCodeList = new LinkedList<SelectItem>();
			DCODEDTC[] el = DCODEDTC.values();
			for (DCODEDTC obj : el) {
				if(obj.isActive()){
					String name = (obj.getDescription().length()>80?(obj.getDescription().substring(0, 80)+"..."):obj.getDescription());
					SelectItem item = new SelectItem(obj, name);
					DCODEDTCCodeList.add(item);
				}
			}
		}
		return DCODEDTCCodeList;
	}

	/** 
	 *  ------------------------------------------------------------------------
	 *  TABLA      	DESCRIPCION						FECHA ÚLTIMA ACTUALIZACIÓN.
	 * No description found
	 *  ------------------------------------------------------------------------
	 */ 
	private List<SelectItem> DCSPCPTCCodeList;

	public List<SelectItem> getDCSPCPTCCodeList() {
		if (DCSPCPTCCodeList == null) {
			DCSPCPTCCodeList = new LinkedList<SelectItem>();
			DCSPCPTC[] el = DCSPCPTC.values();
			for (DCSPCPTC obj : el) {
				if(obj.isActive()){
					String name = (obj.getDescription().length()>80?(obj.getDescription().substring(0, 80)+"..."):obj.getDescription());
					SelectItem item = new SelectItem(obj, name);
					DCSPCPTCCodeList.add(item);
				}
			}
		}
		return DCSPCPTCCodeList;
	}

	/** 
	 *  ------------------------------------------------------------------------
	 *  TABLA      	DESCRIPCION						FECHA ÚLTIMA ACTUALIZACIÓN.
	 * No description found
	 *  ------------------------------------------------------------------------
	 */ 
	private List<SelectItem> DGRCOTTCCodeList;

	public List<SelectItem> getDGRCOTTCCodeList() {
		if (DGRCOTTCCodeList == null) {
			DGRCOTTCCodeList = new LinkedList<SelectItem>();
			DGRCOTTC[] el = DGRCOTTC.values();
			for (DGRCOTTC obj : el) {
				if(obj.isActive()){
					String name = (obj.getDescription().length()>80?(obj.getDescription().substring(0, 80)+"..."):obj.getDescription());
					SelectItem item = new SelectItem(obj, name);
					DGRCOTTCCodeList.add(item);
				}
			}
		}
		return DGRCOTTCCodeList;
	}

	/** 
	 *  ------------------------------------------------------------------------
	 *  TABLA      	DESCRIPCION						FECHA ÚLTIMA ACTUALIZACIÓN.
	 * No description found
	 *  ------------------------------------------------------------------------
	 */ 
	private List<SelectItem> DSTEMCTCCodeList;

	public List<SelectItem> getDSTEMCTCCodeList() {
		if (DSTEMCTCCodeList == null) {
			DSTEMCTCCodeList = new LinkedList<SelectItem>();
			DSTEMCTC[] el = DSTEMCTC.values();
			for (DSTEMCTC obj : el) {
				if(obj.isActive()){
					String name = (obj.getDescription().length()>80?(obj.getDescription().substring(0, 80)+"..."):obj.getDescription());
					SelectItem item = new SelectItem(obj, name);
					DSTEMCTCCodeList.add(item);
				}
			}
		}
		return DSTEMCTCCodeList;
	}

	/** 
	 *  ------------------------------------------------------------------------
	 *  TABLA      	DESCRIPCION						FECHA ÚLTIMA ACTUALIZACIÓN.
	 * No description found
	 *  ------------------------------------------------------------------------
	 */ 
	private List<SelectItem> SACECOTCCodeList;

	public List<SelectItem> getSACECOTCCodeList() {
		if (SACECOTCCodeList == null) {
			SACECOTCCodeList = new LinkedList<SelectItem>();
			SACECOTC[] el = SACECOTC.values();
			for (SACECOTC obj : el) {
				if(obj.isActive()){
					String name = (obj.getDescription().length()>80?(obj.getDescription().substring(0, 80)+"..."):obj.getDescription());
					SelectItem item = new SelectItem(obj, name);
					SACECOTCCodeList.add(item);
				}
			}
		}
		return SACECOTCCodeList;
	}

	/** 
	 *  ------------------------------------------------------------------------
	 *  TABLA      	DESCRIPCION						FECHA ÚLTIMA ACTUALIZACIÓN.
	 * No description found
	 *  ------------------------------------------------------------------------
	 */ 
	private List<SelectItem> TAICLAOCCodeList;

	public List<SelectItem> getTAICLAOCCodeList() {
		if (TAICLAOCCodeList == null) {
			TAICLAOCCodeList = new LinkedList<SelectItem>();
			TAICLAOC[] el = TAICLAOC.values();
			for (TAICLAOC obj : el) {
				if(obj.isActive()){
					String name = (obj.getDescription().length()>80?(obj.getDescription().substring(0, 80)+"..."):obj.getDescription());
					SelectItem item = new SelectItem(obj, name);
					TAICLAOCCodeList.add(item);
				}
			}
		}
		return TAICLAOCCodeList;
	}

	/** 
	 *  ------------------------------------------------------------------------
	 *  TABLA      	DESCRIPCION						FECHA ÚLTIMA ACTUALIZACIÓN.
	 * No description found
	 *  ------------------------------------------------------------------------
	 */ 
	private List<SelectItem> TCGPROVICodeList;

	public List<SelectItem> getTCGPROVICodeList() {
		if (TCGPROVICodeList == null) {
			TCGPROVICodeList = new LinkedList<SelectItem>();
			TCGPROVI[] el = TCGPROVI.values();
			for (TCGPROVI obj : el) {
				if(obj.isActive()){
					String name = (obj.getDescription().length()>80?(obj.getDescription().substring(0, 80)+"..."):obj.getDescription());
					SelectItem item = new SelectItem(obj, name);
					TCGPROVICodeList.add(item);
				}
			}
		}
		return TCGPROVICodeList;
	}

	/** 
	 *  ------------------------------------------------------------------------
	 *  TABLA      	DESCRIPCION						FECHA ÚLTIMA ACTUALIZACIÓN.
	 * No description found
	 *  ------------------------------------------------------------------------
	 */ 
	private List<SelectItem> TCHRGCOTCodeList;

	public List<SelectItem> getTCHRGCOTCodeList() {
		if (TCHRGCOTCodeList == null) {
			TCHRGCOTCodeList = new LinkedList<SelectItem>();
			TCHRGCOT[] el = TCHRGCOT.values();
			for (TCHRGCOT obj : el) {
				if(obj.isActive()){
					String name = (obj.getDescription().length()>80?(obj.getDescription().substring(0, 80)+"..."):obj.getDescription());
					SelectItem item = new SelectItem(obj, name);
					TCHRGCOTCodeList.add(item);
				}
			}
		}
		return TCHRGCOTCodeList;
	}

	/** 
	 *  ------------------------------------------------------------------------
	 *  TABLA      	DESCRIPCION						FECHA ÚLTIMA ACTUALIZACIÓN.
	 * No description found
	 *  ------------------------------------------------------------------------
	 */ 
	private List<SelectItem> TerroresCodeList;

	public List<SelectItem> getTerroresCodeList() {
		if (TerroresCodeList == null) {
			TerroresCodeList = new LinkedList<SelectItem>();
			Terrores[] el = Terrores.values();
			for (Terrores obj : el) {
				if(obj.isActive()){
					String name = (obj.getDescription().length()>80?(obj.getDescription().substring(0, 80)+"..."):obj.getDescription());
					SelectItem item = new SelectItem(obj, name);
					TerroresCodeList.add(item);
				}
			}
		}
		return TerroresCodeList;
	}

	/** 
	 *  ------------------------------------------------------------------------
	 *  TABLA      	DESCRIPCION						FECHA ÚLTIMA ACTUALIZACIÓN.
	 * No description found
	 *  ------------------------------------------------------------------------
	 */ 
	private List<SelectItem> TKCSITEMCodeList;

	public List<SelectItem> getTKCSITEMCodeList() {
		if (TKCSITEMCodeList == null) {
			TKCSITEMCodeList = new LinkedList<SelectItem>();
			TKCSITEM[] el = TKCSITEM.values();
			for (TKCSITEM obj : el) {
				if(obj.isActive()){
					String name = (obj.getDescription().length()>80?(obj.getDescription().substring(0, 80)+"..."):obj.getDescription());
					SelectItem item = new SelectItem(obj, name);
					TKCSITEMCodeList.add(item);
				}
			}
		}
		return TKCSITEMCodeList;
	}

	/** 
	 *  ------------------------------------------------------------------------
	 *  TABLA      	DESCRIPCION						FECHA ÚLTIMA ACTUALIZACIÓN.
	 * No description found
	 *  ------------------------------------------------------------------------
	 */ 
	private List<SelectItem> TKDIASACCodeList;

	public List<SelectItem> getTKDIASACCodeList() {
		if (TKDIASACCodeList == null) {
			TKDIASACCodeList = new LinkedList<SelectItem>();
			TKDIASAC[] el = TKDIASAC.values();
			for (TKDIASAC obj : el) {
				if(obj.isActive()){
					String name = (obj.getDescription().length()>80?(obj.getDescription().substring(0, 80)+"..."):obj.getDescription());
					SelectItem item = new SelectItem(obj, name);
					TKDIASACCodeList.add(item);
				}
			}
		}
		return TKDIASACCodeList;
	}

	/** 
	 *  ------------------------------------------------------------------------
	 *  TABLA      	DESCRIPCION						FECHA ÚLTIMA ACTUALIZACIÓN.
	 * No description found
	 *  ------------------------------------------------------------------------
	 */ 
	private List<SelectItem> TKEINDUCCodeList;

	public List<SelectItem> getTKEINDUCCodeList() {
		if (TKEINDUCCodeList == null) {
			TKEINDUCCodeList = new LinkedList<SelectItem>();
			TKEINDUC[] el = TKEINDUC.values();
			for (TKEINDUC obj : el) {
				if(obj.isActive()){
					String name = (obj.getDescription().length()>80?(obj.getDescription().substring(0, 80)+"..."):obj.getDescription());
					SelectItem item = new SelectItem(obj, name);
					TKEINDUCCodeList.add(item);
				}
			}
		}
		return TKEINDUCCodeList;
	}

	/** 
	 *  ------------------------------------------------------------------------
	 *  TABLA      	DESCRIPCION						FECHA ÚLTIMA ACTUALIZACIÓN.
	 * No description found
	 *  ------------------------------------------------------------------------
	 */ 
	private List<SelectItem> TKFCOEFICodeList;

	public List<SelectItem> getTKFCOEFICodeList() {
		if (TKFCOEFICodeList == null) {
			TKFCOEFICodeList = new LinkedList<SelectItem>();
			TKFCOEFI[] el = TKFCOEFI.values();
			for (TKFCOEFI obj : el) {
				if(obj.isActive()){
					String name = (obj.getDescription().length()>80?(obj.getDescription().substring(0, 80)+"..."):obj.getDescription());
					SelectItem item = new SelectItem(obj, name);
					TKFCOEFICodeList.add(item);
				}
			}
		}
		return TKFCOEFICodeList;
	}

	/** 
	 *  ------------------------------------------------------------------------
	 *  TABLA      	DESCRIPCION						FECHA ÚLTIMA ACTUALIZACIÓN.
	 * No description found
	 *  ------------------------------------------------------------------------
	 */ 
	private List<SelectItem> TKZCARPSCodeList;

	public List<SelectItem> getTKZCARPSCodeList() {
		if (TKZCARPSCodeList == null) {
			TKZCARPSCodeList = new LinkedList<SelectItem>();
			TKZCARPS[] el = TKZCARPS.values();
			for (TKZCARPS obj : el) {
				if(obj.isActive()){
					String name = (obj.getDescription().length()>80?(obj.getDescription().substring(0, 80)+"..."):obj.getDescription());
					SelectItem item = new SelectItem(obj, name);
					TKZCARPSCodeList.add(item);
				}
			}
		}
		return TKZCARPSCodeList;
	}

	/** 
	 *  ------------------------------------------------------------------------
	 *  TABLA      	DESCRIPCION						FECHA ÚLTIMA ACTUALIZACIÓN.
	 * No description found
	 *  ------------------------------------------------------------------------
	 */ 
	private List<SelectItem> TLDCAUSSCodeList;

	public List<SelectItem> getTLDCAUSSCodeList() {
		if (TLDCAUSSCodeList == null) {
			TLDCAUSSCodeList = new LinkedList<SelectItem>();
			TLDCAUSS[] el = TLDCAUSS.values();
			for (TLDCAUSS obj : el) {
				if(obj.isActive()){
					String name = (obj.getDescription().length()>80?(obj.getDescription().substring(0, 80)+"..."):obj.getDescription());
					SelectItem item = new SelectItem(obj, name);
					TLDCAUSSCodeList.add(item);
				}
			}
		}
		return TLDCAUSSCodeList;
	}

	/** 
	 *  ------------------------------------------------------------------------
	 *  TABLA      	DESCRIPCION						FECHA ÚLTIMA ACTUALIZACIÓN.
	 * No description found
	 *  ------------------------------------------------------------------------
	 */ 
	private List<SelectItem> TMJMINSSCodeList;

	public List<SelectItem> getTMJMINSSCodeList() {
		if (TMJMINSSCodeList == null) {
			TMJMINSSCodeList = new LinkedList<SelectItem>();
			TMJMINSS[] el = TMJMINSS.values();
			for (TMJMINSS obj : el) {
				if(obj.isActive()){
					String name = (obj.getDescription().length()>80?(obj.getDescription().substring(0, 80)+"..."):obj.getDescription());
					SelectItem item = new SelectItem(obj, name);
					TMJMINSSCodeList.add(item);
				}
			}
		}
		return TMJMINSSCodeList;
	}

	/** 
	 *  ------------------------------------------------------------------------
	 *  TABLA      	DESCRIPCION						FECHA ÚLTIMA ACTUALIZACIÓN.
	 * No description found
	 *  ------------------------------------------------------------------------
	 */ 
	private List<SelectItem> TMPORCRDCodeList;

	public List<SelectItem> getTMPORCRDCodeList() {
		if (TMPORCRDCodeList == null) {
			TMPORCRDCodeList = new LinkedList<SelectItem>();
			TMPORCRD[] el = TMPORCRD.values();
			for (TMPORCRD obj : el) {
				if(obj.isActive()){
					String name = (obj.getDescription().length()>80?(obj.getDescription().substring(0, 80)+"..."):obj.getDescription());
					SelectItem item = new SelectItem(obj, name);
					TMPORCRDCodeList.add(item);
				}
			}
		}
		return TMPORCRDCodeList;
	}

	/** 
	 *  ------------------------------------------------------------------------
	 *  TABLA      	DESCRIPCION						FECHA ÚLTIMA ACTUALIZACIÓN.
	 * No description found
	 *  ------------------------------------------------------------------------
	 */ 
	private List<SelectItem> TMQTDISTCodeList;

	public List<SelectItem> getTMQTDISTCodeList() {
		if (TMQTDISTCodeList == null) {
			TMQTDISTCodeList = new LinkedList<SelectItem>();
			TMQTDIST[] el = TMQTDIST.values();
			for (TMQTDIST obj : el) {
				if(obj.isActive()){
					String name = (obj.getDescription().length()>80?(obj.getDescription().substring(0, 80)+"..."):obj.getDescription());
					SelectItem item = new SelectItem(obj, name);
					TMQTDISTCodeList.add(item);
				}
			}
		}
		return TMQTDISTCodeList;
	}

	/** 
	 *  ------------------------------------------------------------------------
	 *  TABLA      	DESCRIPCION						FECHA ÚLTIMA ACTUALIZACIÓN.
	 * No description found
	 *  ------------------------------------------------------------------------
	 */ 
	private List<SelectItem> TNWTPCOMCodeList;

	public List<SelectItem> getTNWTPCOMCodeList() {
		if (TNWTPCOMCodeList == null) {
			TNWTPCOMCodeList = new LinkedList<SelectItem>();
			TNWTPCOM[] el = TNWTPCOM.values();
			for (TNWTPCOM obj : el) {
				if(obj.isActive()){
					String name = (obj.getDescription().length()>80?(obj.getDescription().substring(0, 80)+"..."):obj.getDescription());
					SelectItem item = new SelectItem(obj, name);
					TNWTPCOMCodeList.add(item);
				}
			}
		}
		return TNWTPCOMCodeList;
	}

}