package com.esferalia.aon.ui.sepe.controller;

import java.util.LinkedList;
import java.util.List;
import javax.faces.model.SelectItem;
import com.esferalia.aon.payroll.contrata.enumeration.*;

/** 
 * Autogenerated class
 * 
 * Contrat@ code tables Collections.
 * Generation main class: com.esferalia.aon.payroll.sepe.ContrataCodeTablesWriter
*/ 

public class ContrataCollectionsController {

	/** 
	 *  ------------------------------------------------------------------------
	 *  TABLA      	DESCRIPCION						FECHA ÚLTIMA ACTUALIZACIÓN.
	 * No description found
	 *  ------------------------------------------------------------------------
	 */ 
	private List<SelectItem> ContrataCodeTablesCodeList;

	public List<SelectItem> getContrataCodeTablesCodeList() {
		if (ContrataCodeTablesCodeList == null) {
			ContrataCodeTablesCodeList = new LinkedList<SelectItem>();
			ContrataCodeTables[] el = ContrataCodeTables.values();
			for (ContrataCodeTables obj : el) {
				if(obj.isActive()){
					String name = (obj.getDescription().length()>80?(obj.getDescription().substring(0, 80)+"..."):obj.getDescription());
					SelectItem item = new SelectItem(obj, name);
					ContrataCodeTablesCodeList.add(item);
				}
			}
		}
		return ContrataCodeTablesCodeList;
	}

	/** 
	 *  ------------------------------------------------------------------------
	 *  TABLA      	DESCRIPCION						FECHA ÚLTIMA ACTUALIZACIÓN.
	 *  STDIDETC	TIPO DE DOCUMENTO IDENTIFICATIVO	 	
	 *  ------------------------------------------------------------------------
	 */ 
	private List<SelectItem> STDIDETCCodeList;

	public List<SelectItem> getSTDIDETCCodeList() {
		if (STDIDETCCodeList == null) {
			STDIDETCCodeList = new LinkedList<SelectItem>();
			STDIDETC[] el = STDIDETC.values();
			for (STDIDETC obj : el) {
				if(obj.isActive()){
					String name = (obj.getDescription().length()>80?(obj.getDescription().substring(0, 80)+"..."):obj.getDescription());
					SelectItem item = new SelectItem(obj, name);
					STDIDETCCodeList.add(item);
				}
			}
		}
		return STDIDETCCodeList;
	}

	/** 
	 *  ------------------------------------------------------------------------
	 *  TABLA      	DESCRIPCION						FECHA ÚLTIMA ACTUALIZACIÓN.
	 *  TABCCNAE	ACTIVIDAD ECONÓMICA						15-03-2009	
	 *  ------------------------------------------------------------------------
	 */ 
	private List<SelectItem> TABCCNAECodeList;

	public List<SelectItem> getTABCCNAECodeList() {
		if (TABCCNAECodeList == null) {
			TABCCNAECodeList = new LinkedList<SelectItem>();
			TABCCNAE[] el = TABCCNAE.values();
			for (TABCCNAE obj : el) {
				if(obj.isActive()){
					String name = (obj.getDescription().length()>80?(obj.getDescription().substring(0, 80)+"..."):obj.getDescription());
					SelectItem item = new SelectItem(obj, name);
					TABCCNAECodeList.add(item);
				}
			}
		}
		return TABCCNAECodeList;
	}

	/** 
	 *  ------------------------------------------------------------------------
	 *  TABLA      	DESCRIPCION						FECHA ÚLTIMA ACTUALIZACIÓN.
	 *  TAICLAOC2011   OCUPACIÓN ( A partir de 2011 )					29-02-2012 
	 *  ------------------------------------------------------------------------
	 */ 
	private List<SelectItem> TAICLAOC2011CodeList;

	public List<SelectItem> getTAICLAOC2011CodeList() {
		if (TAICLAOC2011CodeList == null) {
			TAICLAOC2011CodeList = new LinkedList<SelectItem>();
			TAICLAOC2011[] el = TAICLAOC2011.values();
			for (TAICLAOC2011 obj : el) {
				if(obj.isActive()){
					String name = (obj.getDescription().length()>80?(obj.getDescription().substring(0, 80)+"..."):obj.getDescription());
					SelectItem item = new SelectItem(obj, name);
					TAICLAOC2011CodeList.add(item);
				}
			}
		}
		return TAICLAOC2011CodeList;
	}

	/** 
	 *  ------------------------------------------------------------------------
	 *  TABLA      	DESCRIPCION						FECHA ÚLTIMA ACTUALIZACIÓN.
	 *  TAUCOMAU	COMUNIDAD AUTÓNOMA				
	 *  ------------------------------------------------------------------------
	 */ 
	private List<SelectItem> TAUCOMAUCodeList;

	public List<SelectItem> getTAUCOMAUCodeList() {
		if (TAUCOMAUCodeList == null) {
			TAUCOMAUCodeList = new LinkedList<SelectItem>();
			TAUCOMAU[] el = TAUCOMAU.values();
			for (TAUCOMAU obj : el) {
				if(obj.isActive()){
					String name = (obj.getDescription().length()>80?(obj.getDescription().substring(0, 80)+"..."):obj.getDescription());
					SelectItem item = new SelectItem(obj, name);
					TAUCOMAUCodeList.add(item);
				}
			}
		}
		return TAUCOMAUCodeList;
	}

	/** 
	 *  ------------------------------------------------------------------------
	 *  TABLA      	DESCRIPCION						FECHA ÚLTIMA ACTUALIZACIÓN.
	 *  TBONVFOR	NIVEL FORMATIVO							29-02-2012					
	 *  ------------------------------------------------------------------------
	 */ 
	private List<SelectItem> TBONVFORCodeList;

	public List<SelectItem> getTBONVFORCodeList() {
		if (TBONVFORCodeList == null) {
			TBONVFORCodeList = new LinkedList<SelectItem>();
			TBONVFOR[] el = TBONVFOR.values();
			for (TBONVFOR obj : el) {
				if(obj.isActive()){
					String name = (obj.getDescription().length()>80?(obj.getDescription().substring(0, 80)+"..."):obj.getDescription());
					SelectItem item = new SelectItem(obj, name);
					TBONVFORCodeList.add(item);
				}
			}
		}
		return TBONVFORCodeList;
	}

	/** 
	 *  ------------------------------------------------------------------------
	 *  TABLA      	DESCRIPCION						FECHA ÚLTIMA ACTUALIZACIÓN.
	 *  TBXCPAIS	PAÍS								
	 *  ------------------------------------------------------------------------
	 */ 
	private List<SelectItem> TBXCPAISCodeList;

	public List<SelectItem> getTBXCPAISCodeList() {
		if (TBXCPAISCodeList == null) {
			TBXCPAISCodeList = new LinkedList<SelectItem>();
			TBXCPAIS[] el = TBXCPAIS.values();
			for (TBXCPAIS obj : el) {
				if(obj.isActive()){
					String name = (obj.getDescription().length()>80?(obj.getDescription().substring(0, 80)+"..."):obj.getDescription());
					SelectItem item = new SelectItem(obj, name);
					TBXCPAISCodeList.add(item);
				}
			}
		}
		return TBXCPAISCodeList;
	}

	/** 
	 *  ------------------------------------------------------------------------
	 *  TABLA      	DESCRIPCION						FECHA ÚLTIMA ACTUALIZACIÓN.
	 *  TCGPROVI	PROVINCIA
	 *  ------------------------------------------------------------------------
	 */ 
	private List<SelectItem> TCGPROVICodeList;

	public List<SelectItem> getTCGPROVICodeList() {
		if (TCGPROVICodeList == null) {
			TCGPROVICodeList = new LinkedList<SelectItem>();
			TCGPROVI[] el = TCGPROVI.values();
			for (TCGPROVI obj : el) {
				if(obj.isActive()){
					String name = (obj.getDescription().length()>80?(obj.getDescription().substring(0, 80)+"..."):obj.getDescription());
					SelectItem item = new SelectItem(obj, name);
					TCGPROVICodeList.add(item);
				}
			}
		}
		return TCGPROVICodeList;
	}

	/** 
	 *  ------------------------------------------------------------------------
	 *  TABLA      	DESCRIPCION						FECHA ÚLTIMA ACTUALIZACIÓN.
	 *  TCHRGCOT	RÉGIMEN DE COTIZACIÓN						10-01-2012						
	 *  ------------------------------------------------------------------------
	 */ 
	private List<SelectItem> TCHRGCOTCodeList;

	public List<SelectItem> getTCHRGCOTCodeList() {
		if (TCHRGCOTCodeList == null) {
			TCHRGCOTCodeList = new LinkedList<SelectItem>();
			TCHRGCOT[] el = TCHRGCOT.values();
			for (TCHRGCOT obj : el) {
				if(obj.isActive()){
					String name = (obj.getDescription().length()>80?(obj.getDescription().substring(0, 80)+"..."):obj.getDescription());
					SelectItem item = new SelectItem(obj, name);
					TCHRGCOTCodeList.add(item);
				}
			}
		}
		return TCHRGCOTCodeList;
	}

	/** 
	 *  ------------------------------------------------------------------------
	 *  TABLA      	DESCRIPCION						FECHA ÚLTIMA ACTUALIZACIÓN.
	 *  TCMCSEXO	SEXO								
	 *  ------------------------------------------------------------------------
	 */ 
	private List<SelectItem> TCMCSEXOCodeList;

	public List<SelectItem> getTCMCSEXOCodeList() {
		if (TCMCSEXOCodeList == null) {
			TCMCSEXOCodeList = new LinkedList<SelectItem>();
			TCMCSEXO[] el = TCMCSEXO.values();
			for (TCMCSEXO obj : el) {
				if(obj.isActive()){
					String name = (obj.getDescription().length()>80?(obj.getDescription().substring(0, 80)+"..."):obj.getDescription());
					SelectItem item = new SelectItem(obj, name);
					TCMCSEXOCodeList.add(item);
				}
			}
		}
		return TCMCSEXOCodeList;
	}

	/** 
	 *  ------------------------------------------------------------------------
	 *  TABLA      	DESCRIPCION						FECHA ÚLTIMA ACTUALIZACIÓN.
	 * *TDTVINFO	VINCULACIÓN FORMATIVA						17-04-2013
	 *  ------------------------------------------------------------------------
	 */ 
	private List<SelectItem> TDTVINFOCodeList;

	public List<SelectItem> getTDTVINFOCodeList() {
		if (TDTVINFOCodeList == null) {
			TDTVINFOCodeList = new LinkedList<SelectItem>();
			TDTVINFO[] el = TDTVINFO.values();
			for (TDTVINFO obj : el) {
				if(obj.isActive()){
					String name = (obj.getDescription().length()>80?(obj.getDescription().substring(0, 80)+"..."):obj.getDescription());
					SelectItem item = new SelectItem(obj, name);
					TDTVINFOCodeList.add(item);
				}
			}
		}
		return TDTVINFOCodeList;
	}

	/** 
	 *  ------------------------------------------------------------------------
	 *  TABLA      	DESCRIPCION						FECHA ÚLTIMA ACTUALIZACIÓN.
	 * *TEHTPCTO	CÓDIGOS DE CONTRATO						07-02-2013					
	 *  ------------------------------------------------------------------------
	 */ 
	private List<SelectItem> TEHTPCTOCodeList;

	public List<SelectItem> getTEHTPCTOCodeList() {
		if (TEHTPCTOCodeList == null) {
			TEHTPCTOCodeList = new LinkedList<SelectItem>();
			TEHTPCTO[] el = TEHTPCTO.values();
			for (TEHTPCTO obj : el) {
				if(obj.isActive()){
					String name = (obj.getDescription().length()>80?(obj.getDescription().substring(0, 80)+"..."):obj.getDescription());
					SelectItem item = new SelectItem(obj, name);
					TEHTPCTOCodeList.add(item);
				}
			}
		}
		return TEHTPCTOCodeList;
	}

	/** 
	 *  ------------------------------------------------------------------------
	 *  TABLA      	DESCRIPCION						FECHA ÚLTIMA ACTUALIZACIÓN.
	 * *TEIINTER	CAUSA OBJETO DE LA INTERINIDAD					
	 *  ------------------------------------------------------------------------
	 */ 
	private List<SelectItem> TEIINTERCodeList;

	public List<SelectItem> getTEIINTERCodeList() {
		if (TEIINTERCodeList == null) {
			TEIINTERCodeList = new LinkedList<SelectItem>();
			TEIINTER[] el = TEIINTER.values();
			for (TEIINTER obj : el) {
				if(obj.isActive()){
					String name = (obj.getDescription().length()>80?(obj.getDescription().substring(0, 80)+"..."):obj.getDescription());
					SelectItem item = new SelectItem(obj, name);
					TEIINTERCodeList.add(item);
				}
			}
		}
		return TEIINTERCodeList;
	}

	/** 
	 *  ------------------------------------------------------------------------
	 *  TABLA      	DESCRIPCION						FECHA ÚLTIMA ACTUALIZACIÓN.
	 *  TEJINDIS	INDICADOR DISCAPACIDAD										
	 *  ------------------------------------------------------------------------
	 */ 
	private List<SelectItem> TEJINDISCodeList;

	public List<SelectItem> getTEJINDISCodeList() {
		if (TEJINDISCodeList == null) {
			TEJINDISCodeList = new LinkedList<SelectItem>();
			TEJINDIS[] el = TEJINDIS.values();
			for (TEJINDIS obj : el) {
				if(obj.isActive()){
					String name = (obj.getDescription().length()>80?(obj.getDescription().substring(0, 80)+"..."):obj.getDescription());
					SelectItem item = new SelectItem(obj, name);
					TEJINDISCodeList.add(item);
				}
			}
		}
		return TEJINDISCodeList;
	}

	/** 
	 *  ------------------------------------------------------------------------
	 *  TABLA      	DESCRIPCION						FECHA ÚLTIMA ACTUALIZACIÓN.
	 * *TEKLEYBO	LEY BONIFICACIÓN						17-04-2013	
	 *  ------------------------------------------------------------------------
	 */ 
	private List<SelectItem> TEKLEYBOCodeList;

	public List<SelectItem> getTEKLEYBOCodeList() {
		if (TEKLEYBOCodeList == null) {
			TEKLEYBOCodeList = new LinkedList<SelectItem>();
			TEKLEYBO[] el = TEKLEYBO.values();
			for (TEKLEYBO obj : el) {
				if(obj.isActive()){
					String name = (obj.getDescription().length()>80?(obj.getDescription().substring(0, 80)+"..."):obj.getDescription());
					SelectItem item = new SelectItem(obj, name);
					TEKLEYBOCodeList.add(item);
				}
			}
		}
		return TEKLEYBOCodeList;
	}

	/** 
	 *  ------------------------------------------------------------------------
	 *  TABLA      	DESCRIPCION						FECHA ÚLTIMA ACTUALIZACIÓN.
	 * *TELCOLBO	COLECTIVO BONIFICACIÓN						17-04-2013
	 *  ------------------------------------------------------------------------
	 */ 
	private List<SelectItem> TELCOLBOCodeList;

	public List<SelectItem> getTELCOLBOCodeList() {
		if (TELCOLBOCodeList == null) {
			TELCOLBOCodeList = new LinkedList<SelectItem>();
			TELCOLBO[] el = TELCOLBO.values();
			for (TELCOLBO obj : el) {
				if(obj.isActive()){
					String name = (obj.getDescription().length()>80?(obj.getDescription().substring(0, 80)+"..."):obj.getDescription());
					SelectItem item = new SelectItem(obj, name);
					TELCOLBOCodeList.add(item);
				}
			}
		}
		return TELCOLBOCodeList;
	}

	/** 
	 *  ------------------------------------------------------------------------
	 *  TABLA      	DESCRIPCION						FECHA ÚLTIMA ACTUALIZACIÓN.
	 * *TENLEYDE	LEY FOMENTO DE LA CONTR. INDEFINIDA				29-02-2012
	 *  ------------------------------------------------------------------------
	 */ 
	private List<SelectItem> TENLEYDECodeList;

	public List<SelectItem> getTENLEYDECodeList() {
		if (TENLEYDECodeList == null) {
			TENLEYDECodeList = new LinkedList<SelectItem>();
			TENLEYDE[] el = TENLEYDE.values();
			for (TENLEYDE obj : el) {
				if(obj.isActive()){
					String name = (obj.getDescription().length()>80?(obj.getDescription().substring(0, 80)+"..."):obj.getDescription());
					SelectItem item = new SelectItem(obj, name);
					TENLEYDECodeList.add(item);
				}
			}
		}
		return TENLEYDECodeList;
	}

	/** 
	 *  ------------------------------------------------------------------------
	 *  TABLA      	DESCRIPCION						FECHA ÚLTIMA ACTUALIZACIÓN.
	 * *TEOCOLDE	COLECTIVO FOMENTO DE LA CONTR. INDEFINIDA			29-02-2012
	 *  ------------------------------------------------------------------------
	 */ 
	private List<SelectItem> TEOCOLDECodeList;

	public List<SelectItem> getTEOCOLDECodeList() {
		if (TEOCOLDECodeList == null) {
			TEOCOLDECodeList = new LinkedList<SelectItem>();
			TEOCOLDE[] el = TEOCOLDE.values();
			for (TEOCOLDE obj : el) {
				if(obj.isActive()){
					String name = (obj.getDescription().length()>80?(obj.getDescription().substring(0, 80)+"..."):obj.getDescription());
					SelectItem item = new SelectItem(obj, name);
					TEOCOLDECodeList.add(item);
				}
			}
		}
		return TEOCOLDECodeList;
	}

	/** 
	 *  ------------------------------------------------------------------------
	 *  TABLA      	DESCRIPCION						FECHA ÚLTIMA ACTUALIZACIÓN.
	 *  TEQPTIEM	PERÍODO DE TIEMPO				
	 *  ------------------------------------------------------------------------
	 */ 
	private List<SelectItem> TEQPTIEMCodeList;

	public List<SelectItem> getTEQPTIEMCodeList() {
		if (TEQPTIEMCodeList == null) {
			TEQPTIEMCodeList = new LinkedList<SelectItem>();
			TEQPTIEM[] el = TEQPTIEM.values();
			for (TEQPTIEM obj : el) {
				if(obj.isActive()){
					String name = (obj.getDescription().length()>80?(obj.getDescription().substring(0, 80)+"..."):obj.getDescription());
					SelectItem item = new SelectItem(obj, name);
					TEQPTIEMCodeList.add(item);
				}
			}
		}
		return TEQPTIEMCodeList;
	}

	/** 
	 *  ------------------------------------------------------------------------
	 *  TABLA      	DESCRIPCION						FECHA ÚLTIMA ACTUALIZACIÓN.
	 *  TERFIRCB	FIRMA COPIA BÁSICA				
	 *  ------------------------------------------------------------------------
	 */ 
	private List<SelectItem> TERFIRCBCodeList;

	public List<SelectItem> getTERFIRCBCodeList() {
		if (TERFIRCBCodeList == null) {
			TERFIRCBCodeList = new LinkedList<SelectItem>();
			TERFIRCB[] el = TERFIRCB.values();
			for (TERFIRCB obj : el) {
				if(obj.isActive()){
					String name = (obj.getDescription().length()>80?(obj.getDescription().substring(0, 80)+"..."):obj.getDescription());
					SelectItem item = new SelectItem(obj, name);
					TERFIRCBCodeList.add(item);
				}
			}
		}
		return TERFIRCBCodeList;
	}

	/** 
	 *  ------------------------------------------------------------------------
	 *  TABLA      	DESCRIPCION						FECHA ÚLTIMA ACTUALIZACIÓN.
	 * TERRORES 
	 *  ------------------------------------------------------------------------
	 */ 
	private List<SelectItem> TERRORESCodeList;

	public List<SelectItem> getTERRORESCodeList() {
		if (TERRORESCodeList == null) {
			TERRORESCodeList = new LinkedList<SelectItem>();
			TERRORES[] el = TERRORES.values();
			for (TERRORES obj : el) {
				if(obj.isActive()){
					String name = (obj.getDescription().length()>80?(obj.getDescription().substring(0, 80)+"..."):obj.getDescription());
					SelectItem item = new SelectItem(obj, name);
					TERRORESCodeList.add(item);
				}
			}
		}
		return TERRORESCodeList;
	}

	/** 
	 *  ------------------------------------------------------------------------
	 *  TABLA      	DESCRIPCION						FECHA ÚLTIMA ACTUALIZACIÓN.
	 * *TESCETCO	RELACIÓN CONTRACTUAL ET / CO / TE		
	 *  ------------------------------------------------------------------------
	 */ 
	private List<SelectItem> TESCETCOCodeList;

	public List<SelectItem> getTESCETCOCodeList() {
		if (TESCETCOCodeList == null) {
			TESCETCOCodeList = new LinkedList<SelectItem>();
			TESCETCO[] el = TESCETCO.values();
			for (TESCETCO obj : el) {
				if(obj.isActive()){
					String name = (obj.getDescription().length()>80?(obj.getDescription().substring(0, 80)+"..."):obj.getDescription());
					SelectItem item = new SelectItem(obj, name);
					TESCETCOCodeList.add(item);
				}
			}
		}
		return TESCETCOCodeList;
	}

	/** 
	 *  ------------------------------------------------------------------------
	 *  TABLA      	DESCRIPCION						FECHA ÚLTIMA ACTUALIZACIÓN.
	 *  TETPGMEM	PROGRAMA DE EMPLEO				
	 *  ------------------------------------------------------------------------
	 */ 
	private List<SelectItem> TETPGMEMCodeList;

	public List<SelectItem> getTETPGMEMCodeList() {
		if (TETPGMEMCodeList == null) {
			TETPGMEMCodeList = new LinkedList<SelectItem>();
			TETPGMEM[] el = TETPGMEM.values();
			for (TETPGMEM obj : el) {
				if(obj.isActive()){
					String name = (obj.getDescription().length()>80?(obj.getDescription().substring(0, 80)+"..."):obj.getDescription());
					SelectItem item = new SelectItem(obj, name);
					TETPGMEMCodeList.add(item);
				}
			}
		}
		return TETPGMEMCodeList;
	}

	/** 
	 *  ------------------------------------------------------------------------
	 *  TABLA      	DESCRIPCION						FECHA ÚLTIMA ACTUALIZACIÓN.
	 *  TEUECCLL	CORPORACIONES LOCALES				
	 *  ------------------------------------------------------------------------
	 */ 
	private List<SelectItem> TEUECCLLCodeList;

	public List<SelectItem> getTEUECCLLCodeList() {
		if (TEUECCLLCodeList == null) {
			TEUECCLLCodeList = new LinkedList<SelectItem>();
			TEUECCLL[] el = TEUECCLL.values();
			for (TEUECCLL obj : el) {
				if(obj.isActive()){
					String name = (obj.getDescription().length()>80?(obj.getDescription().substring(0, 80)+"..."):obj.getDescription());
					SelectItem item = new SelectItem(obj, name);
					TEUECCLLCodeList.add(item);
				}
			}
		}
		return TEUECCLLCodeList;
	}

	/** 
	 *  ------------------------------------------------------------------------
	 *  TABLA      	DESCRIPCION						FECHA ÚLTIMA ACTUALIZACIÓN.
	 *  TEVACTCL	ACTUACIONES DE CORPORACIONES LOCALES		
	 *  ------------------------------------------------------------------------
	 */ 
	private List<SelectItem> TEVACTCLCodeList;

	public List<SelectItem> getTEVACTCLCodeList() {
		if (TEVACTCLCodeList == null) {
			TEVACTCLCodeList = new LinkedList<SelectItem>();
			TEVACTCL[] el = TEVACTCL.values();
			for (TEVACTCL obj : el) {
				if(obj.isActive()){
					String name = (obj.getDescription().length()>80?(obj.getDescription().substring(0, 80)+"..."):obj.getDescription());
					SelectItem item = new SelectItem(obj, name);
					TEVACTCLCodeList.add(item);
				}
			}
		}
		return TEVACTCLCodeList;
	}

	/** 
	 *  ------------------------------------------------------------------------
	 *  TABLA      	DESCRIPCION						FECHA ÚLTIMA ACTUALIZACIÓN.
	 *  TEWEINVE	TIPO DE EMPLEADOR INVESTIGACIÓN					10-01-2012			
	 *  ------------------------------------------------------------------------
	 */ 
	private List<SelectItem> TEWEINVECodeList;

	public List<SelectItem> getTEWEINVECodeList() {
		if (TEWEINVECodeList == null) {
			TEWEINVECodeList = new LinkedList<SelectItem>();
			TEWEINVE[] el = TEWEINVE.values();
			for (TEWEINVE obj : el) {
				if(obj.isActive()){
					String name = (obj.getDescription().length()>80?(obj.getDescription().substring(0, 80)+"..."):obj.getDescription());
					SelectItem item = new SelectItem(obj, name);
					TEWEINVECodeList.add(item);
				}
			}
		}
		return TEWEINVECodeList;
	}

	/** 
	 *  ------------------------------------------------------------------------
	 *  TABLA      	DESCRIPCION						FECHA ÚLTIMA ACTUALIZACIÓN.
	 * *TEXTINVE	TIPO DE TRABAJADOR INVESTIGACIÓN				
	 *  ------------------------------------------------------------------------
	 */ 
	private List<SelectItem> TEXTINVECodeList;

	public List<SelectItem> getTEXTINVECodeList() {
		if (TEXTINVECodeList == null) {
			TEXTINVECodeList = new LinkedList<SelectItem>();
			TEXTINVE[] el = TEXTINVE.values();
			for (TEXTINVE obj : el) {
				if(obj.isActive()){
					String name = (obj.getDescription().length()>80?(obj.getDescription().substring(0, 80)+"..."):obj.getDescription());
					SelectItem item = new SelectItem(obj, name);
					TEXTINVECodeList.add(item);
				}
			}
		}
		return TEXTINVECodeList;
	}

	/** 
	 *  ------------------------------------------------------------------------
	 *  TABLA      	DESCRIPCION						FECHA ÚLTIMA ACTUALIZACIÓN.
	 *  TEYTRELE	TIPO DE TRABAJADOR DE RELEVO			
	 *  ------------------------------------------------------------------------
	 */ 
	private List<SelectItem> TEYTRELECodeList;

	public List<SelectItem> getTEYTRELECodeList() {
		if (TEYTRELECodeList == null) {
			TEYTRELECodeList = new LinkedList<SelectItem>();
			TEYTRELE[] el = TEYTRELE.values();
			for (TEYTRELE obj : el) {
				if(obj.isActive()){
					String name = (obj.getDescription().length()>80?(obj.getDescription().substring(0, 80)+"..."):obj.getDescription());
					SelectItem item = new SelectItem(obj, name);
					TEYTRELECodeList.add(item);
				}
			}
		}
		return TEYTRELECodeList;
	}

	/** 
	 *  ------------------------------------------------------------------------
	 *  TABLA      	DESCRIPCION						FECHA ÚLTIMA ACTUALIZACIÓN.
	 * *TFGGRCOT	GRUPOS DE COTIZACION						15-01-2013
	 *  ------------------------------------------------------------------------
	 */ 
	private List<SelectItem> TFGGRCOTCodeList;

	public List<SelectItem> getTFGGRCOTCodeList() {
		if (TFGGRCOTCodeList == null) {
			TFGGRCOTCodeList = new LinkedList<SelectItem>();
			TFGGRCOT[] el = TFGGRCOT.values();
			for (TFGGRCOT obj : el) {
				if(obj.isActive()){
					String name = (obj.getDescription().length()>80?(obj.getDescription().substring(0, 80)+"..."):obj.getDescription());
					SelectItem item = new SelectItem(obj, name);
					TFGGRCOTCodeList.add(item);
				}
			}
		}
		return TFGGRCOTCodeList;
	}

	/** 
	 *  ------------------------------------------------------------------------
	 *  TABLA      	DESCRIPCION						FECHA ÚLTIMA ACTUALIZACIÓN.
	 * *THPCOLFO	COLECTIVOS CONTRATOS DE FORMACIÓN				26-07-2012
	 *  ------------------------------------------------------------------------
	 */ 
	private List<SelectItem> THPCOLFOCodeList;

	public List<SelectItem> getTHPCOLFOCodeList() {
		if (THPCOLFOCodeList == null) {
			THPCOLFOCodeList = new LinkedList<SelectItem>();
			THPCOLFO[] el = THPCOLFO.values();
			for (THPCOLFO obj : el) {
				if(obj.isActive()){
					String name = (obj.getDescription().length()>80?(obj.getDescription().substring(0, 80)+"..."):obj.getDescription());
					SelectItem item = new SelectItem(obj, name);
					THPCOLFOCodeList.add(item);
				}
			}
		}
		return THPCOLFOCodeList;
	}

	/** 
	 *  ------------------------------------------------------------------------
	 *  TABLA      	DESCRIPCION						FECHA ÚLTIMA ACTUALIZACIÓN.
	 * *THYDISLE	DISPOSICIONES LEGALES				
	 *  ------------------------------------------------------------------------
	 */ 
	private List<SelectItem> THYDISLECodeList;

	public List<SelectItem> getTHYDISLECodeList() {
		if (THYDISLECodeList == null) {
			THYDISLECodeList = new LinkedList<SelectItem>();
			THYDISLE[] el = THYDISLE.values();
			for (THYDISLE obj : el) {
				if(obj.isActive()){
					String name = (obj.getDescription().length()>80?(obj.getDescription().substring(0, 80)+"..."):obj.getDescription());
					SelectItem item = new SelectItem(obj, name);
					THYDISLECodeList.add(item);
				}
			}
		}
		return THYDISLECodeList;
	}

	/** 
	 *  ------------------------------------------------------------------------
	 *  TABLA      	DESCRIPCION						FECHA ÚLTIMA ACTUALIZACIÓN.
	 * *TQNLEYRE	LEYES DE REDUCCIÓN						17-04-2013
	 *  ------------------------------------------------------------------------
	 */ 
	private List<SelectItem> TQNLEYRECodeList;

	public List<SelectItem> getTQNLEYRECodeList() {
		if (TQNLEYRECodeList == null) {
			TQNLEYRECodeList = new LinkedList<SelectItem>();
			TQNLEYRE[] el = TQNLEYRE.values();
			for (TQNLEYRE obj : el) {
				if(obj.isActive()){
					String name = (obj.getDescription().length()>80?(obj.getDescription().substring(0, 80)+"..."):obj.getDescription());
					SelectItem item = new SelectItem(obj, name);
					TQNLEYRECodeList.add(item);
				}
			}
		}
		return TQNLEYRECodeList;
	}

	/** 
	 *  ------------------------------------------------------------------------
	 *  TABLA      	DESCRIPCION						FECHA ÚLTIMA ACTUALIZACIÓN.
	 * *TQOCOLRE	COLECTIVOS DE REDUCCIÓN						17-04-2013 					 
	 *  ------------------------------------------------------------------------
	 */ 
	private List<SelectItem> TQOCOLRECodeList;

	public List<SelectItem> getTQOCOLRECodeList() {
		if (TQOCOLRECodeList == null) {
			TQOCOLRECodeList = new LinkedList<SelectItem>();
			TQOCOLRE[] el = TQOCOLRE.values();
			for (TQOCOLRE obj : el) {
				if(obj.isActive()){
					String name = (obj.getDescription().length()>80?(obj.getDescription().substring(0, 80)+"..."):obj.getDescription());
					SelectItem item = new SelectItem(obj, name);
					TQOCOLRECodeList.add(item);
				}
			}
		}
		return TQOCOLRECodeList;
	}

	/** 
	 *  ------------------------------------------------------------------------
	 *  TABLA      	DESCRIPCION						FECHA ÚLTIMA ACTUALIZACIÓN.
	 * *TRCMODFO 	MODALIDAD DE FORMACION						22-03-2012
	 *  ------------------------------------------------------------------------
	 */ 
	private List<SelectItem> TRCMODFOCodeList;

	public List<SelectItem> getTRCMODFOCodeList() {
		if (TRCMODFOCodeList == null) {
			TRCMODFOCodeList = new LinkedList<SelectItem>();
			TRCMODFO[] el = TRCMODFO.values();
			for (TRCMODFO obj : el) {
				if(obj.isActive()){
					String name = (obj.getDescription().length()>80?(obj.getDescription().substring(0, 80)+"..."):obj.getDescription());
					SelectItem item = new SelectItem(obj, name);
					TRCMODFOCodeList.add(item);
				}
			}
		}
		return TRCMODFOCodeList;
	}

	/** 
	 *  ------------------------------------------------------------------------
	 *  TABLA      	DESCRIPCION						FECHA ÚLTIMA ACTUALIZACIÓN.
	 * *TRDACTFO	ACTIVIDAD FORMATIVA						15-01-2013
	 *  ------------------------------------------------------------------------
	 */ 
	private List<SelectItem> TRDACTFOCodeList;

	public List<SelectItem> getTRDACTFOCodeList() {
		if (TRDACTFOCodeList == null) {
			TRDACTFOCodeList = new LinkedList<SelectItem>();
			TRDACTFO[] el = TRDACTFO.values();
			for (TRDACTFO obj : el) {
				if(obj.isActive()){
					String name = (obj.getDescription().length()>80?(obj.getDescription().substring(0, 80)+"..."):obj.getDescription());
					SelectItem item = new SelectItem(obj, name);
					TRDACTFOCodeList.add(item);
				}
			}
		}
		return TRDACTFOCodeList;
	}

	/** 
	 *  ------------------------------------------------------------------------
	 *  TABLA      	DESCRIPCION						FECHA ÚLTIMA ACTUALIZACIÓN.
	 * *TRWCOLDF	COLECTIVO DE DEDUCCION FISCAL					29-02-2012
	 *  ------------------------------------------------------------------------
	 */ 
	private List<SelectItem> TRWCOLDFCodeList;

	public List<SelectItem> getTRWCOLDFCodeList() {
		if (TRWCOLDFCodeList == null) {
			TRWCOLDFCodeList = new LinkedList<SelectItem>();
			TRWCOLDF[] el = TRWCOLDF.values();
			for (TRWCOLDF obj : el) {
				if(obj.isActive()){
					String name = (obj.getDescription().length()>80?(obj.getDescription().substring(0, 80)+"..."):obj.getDescription());
					SelectItem item = new SelectItem(obj, name);
					TRWCOLDFCodeList.add(item);
				}
			}
		}
		return TRWCOLDFCodeList;
	}

	/** 
	 *  ------------------------------------------------------------------------
	 *  TABLA      	DESCRIPCION						FECHA ÚLTIMA ACTUALIZACIÓN.
	 * *TRXLEYDF	LEY DE DEDUCCION FISCAL						26-07-2012
	 *  ------------------------------------------------------------------------
	 */ 
	private List<SelectItem> TRXLEYDFCodeList;

	public List<SelectItem> getTRXLEYDFCodeList() {
		if (TRXLEYDFCodeList == null) {
			TRXLEYDFCodeList = new LinkedList<SelectItem>();
			TRXLEYDF[] el = TRXLEYDF.values();
			for (TRXLEYDF obj : el) {
				if(obj.isActive()){
					String name = (obj.getDescription().length()>80?(obj.getDescription().substring(0, 80)+"..."):obj.getDescription());
					SelectItem item = new SelectItem(obj, name);
					TRXLEYDFCodeList.add(item);
				}
			}
		}
		return TRXLEYDFCodeList;
	}

	/** 
	 *  ------------------------------------------------------------------------
	 *  TABLA      	DESCRIPCION						FECHA ÚLTIMA ACTUALIZACIÓN.
	 * *TSATPCEN	TIPOS DE CENTRO							22-03-2012
	 *  ------------------------------------------------------------------------
	 */ 
	private List<SelectItem> TSATPCENCodeList;

	public List<SelectItem> getTSATPCENCodeList() {
		if (TSATPCENCodeList == null) {
			TSATPCENCodeList = new LinkedList<SelectItem>();
			TSATPCEN[] el = TSATPCEN.values();
			for (TSATPCEN obj : el) {
				if(obj.isActive()){
					String name = (obj.getDescription().length()>80?(obj.getDescription().substring(0, 80)+"..."):obj.getDescription());
					SelectItem item = new SelectItem(obj, name);
					TSATPCENCodeList.add(item);
				}
			}
		}
		return TSATPCENCodeList;
	}

}