<?xml version="1.0"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<parent>
		<groupId>com.code.aon</groupId>
		<artifactId>aon.parent</artifactId>
		<version>8.83.2</version>
	</parent>
	<modelVersion>4.0.0</modelVersion>
	<artifactId>aon.finance.bridge</artifactId>
	<description>AON FINANCE BRIDGE</description>
	<name>AON FINANCE BRIDGE</name>
	<dependencies>
	    <dependency>
	      <groupId>com.code.aon</groupId>
	      <artifactId>aon.account.bridge</artifactId>
	      <version>${project.version}</version>
	    </dependency>
	    <dependency>
	      <groupId>com.code.aon</groupId>
	      <artifactId>aon.accounting</artifactId>
	      <version>${project.version}</version>
	    </dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.commercial</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.config</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.customer</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.finance</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.product</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.sales.bridge</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.warehouse</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>com.esferalia.aon</groupId>
			<artifactId>aon.entity</artifactId>
			<version>${project.version}</version>
			<scope>compile</scope>
		</dependency>
	    <dependency>
	      <groupId>javax.faces</groupId>
	      <artifactId>jsf-api</artifactId>
	      <version>1.2_14</version>
	      <scope>provided</scope>
	    </dependency>
	</dependencies>
</project>
 
