BEGIN;

LOCK TABLES `make` WRITE;
INSERT INTO `make` (`domain`,`name`) VALUES
	(@Domain,'ALFA ROMEO');
SET @MAKE_ID = (SELECT LAST_INSERT_ID());
INSERT INTO `make` (`id`,`domain`,`name`) VALUES
	(@MAKE_ID+1,@Domain,'ASTON MARTIN'),
	(@MAKE_ID+2,@Domain,'AUDI'),
	(@MAKE_ID+3,@Domain,'BENTLEY'),
	(@MAKE_ID+4,@Domain,'BMW'),
	(@MAKE_ID+5,@Domain,'BUGATTI'),
	(@MAKE_ID+6,@Domain,'CADILLAC'),
	(@MAKE_ID+7,@Domain,'CHEVROLET'),
	(@MAKE_ID+8,@Domain,'CHRYSLER'),
	(@MAKE_ID+9,@Domain,'CITROËN'),
	(@MAKE_ID+10,@Domain,'DACIA'),
	(@MAKE_ID+11,@Domain,'DAEWOO'),
	(@MAKE_ID+12,@Domain,'DAIHATSU'),
	(@MAKE_ID+13,@Domain,'DODGE'),
	(@MAKE_ID+14,@Domain,'FERRARI'),
	(@MAKE_ID+15,@Domain,'FIAT'),
	(@MAKE_ID+16,@Domain,'FORD'),
	(@MAKE_ID+17,@Domain,'GM'),
	(@MAKE_ID+18,@Domain,'HONDA'),
	(@MAKE_ID+19,@Domain,'HUMMER'),
	(@MAKE_ID+20,@Domain,'HYUNDAI'),
	(@MAKE_ID+21,@Domain,'INFINITI'),
	(@MAKE_ID+22,@Domain,'ISUZU'),
	(@MAKE_ID+23,@Domain,'JAGUAR'),
	(@MAKE_ID+24,@Domain,'JEEP'),
	(@MAKE_ID+25,@Domain,'KIA'),
	(@MAKE_ID+26,@Domain,'LAMBORGHINI'),
	(@MAKE_ID+27,@Domain,'LANCIA'),
	(@MAKE_ID+28,@Domain,'LAND ROVER'),
	(@MAKE_ID+29,@Domain,'LEXUS'),
	(@MAKE_ID+30,@Domain,'LOTUS'),
	(@MAKE_ID+31,@Domain,'MASERATI'),
	(@MAKE_ID+32,@Domain,'MAYBACH'),
	(@MAKE_ID+33,@Domain,'MAZDA'),
	(@MAKE_ID+34,@Domain,'MERCEDES'),
	(@MAKE_ID+35,@Domain,'MG'),
	(@MAKE_ID+36,@Domain,'ROVER'),
	(@MAKE_ID+37,@Domain,'MINI'),
	(@MAKE_ID+38,@Domain,'MITSUBISHI'),
	(@MAKE_ID+39,@Domain,'MORGAN'),
	(@MAKE_ID+40,@Domain,'NISSAN'),
	(@MAKE_ID+41,@Domain,'OPEL'),
	(@MAKE_ID+42,@Domain,'PEUGEOT'),
	(@MAKE_ID+43,@Domain,'PONTIAC'),
	(@MAKE_ID+44,@Domain,'PORSCHE'),
	(@MAKE_ID+45,@Domain,'RENAULT'),
	(@MAKE_ID+46,@Domain,'ROLLS-ROYCE'),
	(@MAKE_ID+47,@Domain,'SAAB'),
	(@MAKE_ID+48,@Domain,'SANTANA'),
	(@MAKE_ID+49,@Domain,'SEAT'),
	(@MAKE_ID+50,@Domain,'SKODA'),
	(@MAKE_ID+51,@Domain,'SMART'),
	(@MAKE_ID+52,@Domain,'SSANGYONG'),
	(@MAKE_ID+53,@Domain,'SUBARU'),
	(@MAKE_ID+54,@Domain,'SUZUKI'),
	(@MAKE_ID+55,@Domain,'TATA'),
	(@MAKE_ID+56,@Domain,'TOYOTA'),
	(@MAKE_ID+57,@Domain,'VOLKSWAGEN'),
	(@MAKE_ID+58,@Domain,'VOLVO');
UNLOCK TABLES;
ALTER TABLE `make` AUTO_INCREMENT = 1;

LOCK TABLES `model` WRITE;
INSERT INTO `model` (`domain`,`make`,`name`) VALUES
  (@Domain,@MAKE_ID+2,'TT'),
  (@Domain,@MAKE_ID+2,'A3'),
  (@Domain,@MAKE_ID+2,'A4'),
  (@Domain,@MAKE_ID+2,'A6'),
  (@Domain,@MAKE_ID+2,'A8'),
  (@Domain,@MAKE_ID+4,'Serie1'),
  (@Domain,@MAKE_ID+4,'Serie3'),
  (@Domain,@MAKE_ID+4,'Serie5'),
  (@Domain,@MAKE_ID+4,'Serie7'),
  (@Domain,@MAKE_ID+4,'Z4'),
  (@Domain,@MAKE_ID+4,'X3'),
  (@Domain,@MAKE_ID+4,'X5'),
  (@Domain,@MAKE_ID+9,'C1'),
  (@Domain,@MAKE_ID+9,'C2'),
  (@Domain,@MAKE_ID+9,'C3'),
  (@Domain,@MAKE_ID+9,'C4'),
  (@Domain,@MAKE_ID+9,'C5'),
  (@Domain,@MAKE_ID+9,'C6'),
  (@Domain,@MAKE_ID+9,'C8'),
  (@Domain,@MAKE_ID+9,'Xsara'),
  (@Domain,@MAKE_ID+9,'Berlingo'),
  (@Domain,@MAKE_ID+15,'Seicento'),
  (@Domain,@MAKE_ID+15,'Punto'),
  (@Domain,@MAKE_ID+15,'Panda'),
  (@Domain,@MAKE_ID+15,'Ulysse'),
  (@Domain,@MAKE_ID+15,'Multipla'),
  (@Domain,@MAKE_ID+15,'Croma'),
  (@Domain,@MAKE_ID+15,'Stilo'),
  (@Domain,@MAKE_ID+16,'Ka'),
  (@Domain,@MAKE_ID+16,'Fiesta'),
  (@Domain,@MAKE_ID+16,'Focus'),
  (@Domain,@MAKE_ID+16,'Mondeo'),
  (@Domain,@MAKE_ID+16,'Fusion'),
  (@Domain,@MAKE_ID+16,'C-Max'),
  (@Domain,@MAKE_ID+16,'S-Max'),
  (@Domain,@MAKE_ID+16,'Galaxy'),
  (@Domain,@MAKE_ID+16,'Combi'),
  (@Domain,@MAKE_ID+16,'Ranger'),
  (@Domain,@MAKE_ID+18,'Civic'),
  (@Domain,@MAKE_ID+18,'Accord'),
  (@Domain,@MAKE_ID+18,'Legend'),
  (@Domain,@MAKE_ID+18,'Jazz'),
  (@Domain,@MAKE_ID+18,'FR-V'),
  (@Domain,@MAKE_ID+18,'S2000'),
  (@Domain,@MAKE_ID+18,'CR-V'),
  (@Domain,@MAKE_ID+20,'Getz'),
  (@Domain,@MAKE_ID+20,'Accent'),
  (@Domain,@MAKE_ID+20,'Elantra'),
  (@Domain,@MAKE_ID+20,'Sonata'),
  (@Domain,@MAKE_ID+20,'XG'),
  (@Domain,@MAKE_ID+20,'Atos'),
  (@Domain,@MAKE_ID+20,'Matrix'),
  (@Domain,@MAKE_ID+20,'Trajet'),
  (@Domain,@MAKE_ID+20,'H1'),
  (@Domain,@MAKE_ID+27,'Ypsilon'),
  (@Domain,@MAKE_ID+27,'Libra'),
  (@Domain,@MAKE_ID+27,'Tesis'),
  (@Domain,@MAKE_ID+27,'Musa'),
  (@Domain,@MAKE_ID+27,'Phedra'),
  (@Domain,@MAKE_ID+41,'Corsa'),
  (@Domain,@MAKE_ID+41,'Nuevo Corsa'),
  (@Domain,@MAKE_ID+41,'Astra'),
  (@Domain,@MAKE_ID+41,'Vectra'),
  (@Domain,@MAKE_ID+41,'Signum'),
  (@Domain,@MAKE_ID+41,'Agila'),
  (@Domain,@MAKE_ID+41,'Meriva'),
  (@Domain,@MAKE_ID+41,'Zafira'),
  (@Domain,@MAKE_ID+42,'107'),
  (@Domain,@MAKE_ID+42,'206'),
  (@Domain,@MAKE_ID+42,'207'),
  (@Domain,@MAKE_ID+42,'307'),
  (@Domain,@MAKE_ID+42,'407'),
  (@Domain,@MAKE_ID+42,'607'),
  (@Domain,@MAKE_ID+42,'1007'),
  (@Domain,@MAKE_ID+42,'807'),
  (@Domain,@MAKE_ID+45,'Clio'),
  (@Domain,@MAKE_ID+45,'Megane'),
  (@Domain,@MAKE_ID+45,'Laguna'),
  (@Domain,@MAKE_ID+45,'Vel Satis'),
  (@Domain,@MAKE_ID+45,'Twingo'),
  (@Domain,@MAKE_ID+45,'Modus'),
  (@Domain,@MAKE_ID+45,'Scenic'),
  (@Domain,@MAKE_ID+45,'Space'),
  (@Domain,@MAKE_ID+45,'Coupe'),
  (@Domain,@MAKE_ID+49,'Ibiza'),
  (@Domain,@MAKE_ID+49,'Leon'),
  (@Domain,@MAKE_ID+49,'Toledo'),
  (@Domain,@MAKE_ID+49,'Cordoba'),
  (@Domain,@MAKE_ID+49,'Altea'),
  (@Domain,@MAKE_ID+49,'Alhanbra'),
  (@Domain,@MAKE_ID+57,'New Beetle'),
  (@Domain,@MAKE_ID+57,'Fox'),
  (@Domain,@MAKE_ID+57,'Polo'),
  (@Domain,@MAKE_ID+57,'Golf'),
  (@Domain,@MAKE_ID+57,'Jetta'),
  (@Domain,@MAKE_ID+57,'Passat'),
  (@Domain,@MAKE_ID+57,'Phaeton'),
  (@Domain,@MAKE_ID+56,'Aygo'),
  (@Domain,@MAKE_ID+56,'Yaris'),
  (@Domain,@MAKE_ID+56,'Corolla'),
  (@Domain,@MAKE_ID+56,'Avensis'),
  (@Domain,@MAKE_ID+56,'Prius'),
  (@Domain,@MAKE_ID+56,'Land Cruiser'),
  (@Domain,@MAKE_ID+56,'RAV4'),
  (@Domain,@MAKE_ID+56,'Hilus'),
  (@Domain,@MAKE_ID+58,'S40'),
  (@Domain,@MAKE_ID+58,'S60'),
  (@Domain,@MAKE_ID+58,'S80'),
  (@Domain,@MAKE_ID+58,'V50'),
  (@Domain,@MAKE_ID+58,'V70'),
  (@Domain,@MAKE_ID+58,'C70'),
  (@Domain,@MAKE_ID+58,'XC90');
UNLOCK TABLES;
ALTER TABLE `model` AUTO_INCREMENT = 1;

INSERT INTO `app_param` (`domain`, `name`, `value`) VALUES 
  (@Domain,'AON_TAS_PRIVATE_CODE_REQUIRED','false'),
  (@Domain,'AON_DELIVERY_TEMPLATE_PARAM','deliveryGta');

COMMIT;