<?xml version="1.0"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

	<parent>
		<groupId>com.code.aon</groupId>
		<artifactId>aon.parent</artifactId>
		<version>9.13.2</version>
	</parent>
	<groupId>net.aonsolutions</groupId>
	<artifactId>aon.google.apis.v2</artifactId>
	<modelVersion>4.0.0</modelVersion>
	<description>AON GOOGLE APIS V2</description>
	<name>AON GOOGLE APIS V2</name>

	<dependencies>
		<!-- AON DEPENDENCIES -->
		
		<dependency>
			<groupId>com.esferalia.aon</groupId>
			<artifactId>aon.occam</artifactId>
			<version>${project.version}</version>
			<scope>compile</scope>
		</dependency>

		<!-- GOOGLE DEPENDENCIES -->
		
		<dependency>
			<groupId>com.google.api-client</groupId>
			<artifactId>google-api-client</artifactId>
			<version>1.22.0</version>
		</dependency>
		<dependency>
			<groupId>com.google.api-client</groupId>
			<artifactId>google-api-client-servlet</artifactId>
			<version>1.22.0</version>
		</dependency>
		<dependency>
			<groupId>com.google.http-client</groupId>
			<artifactId>google-http-client-jackson2</artifactId>
			<version>1.22.0</version>
		</dependency>
    	
    	<!-- Google Drive API-->
		<dependency>
    		<groupId>com.google.apis</groupId>
    		<artifactId>google-api-services-drive</artifactId>
    		<version>v3-rev72-1.22.0</version>
		</dependency>
		
		<!-- Google Oauth2 API -->
		<dependency>
    		<groupId>com.google.apis</groupId>
    		<artifactId>google-api-services-oauth2</artifactId>
    		<version>v2-rev126-1.22.0</version>
		</dependency>
		
		<dependency>
			<groupId>com.google.code.gson</groupId>
			<artifactId>gson</artifactId>
			<version>2.8.0</version>
		</dependency>
		
		<!-- EXTERNAL DEPENDENCIES -->
		
		<dependency>
		    <groupId>junit</groupId>
    		<artifactId>junit</artifactId>
    		<version>4.12</version>
    		<scope>test</scope>
		</dependency>

	</dependencies>
</project>
 
