<?xml version="1.0"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<parent>
		<groupId>com.code.aon</groupId>
		<artifactId>aon.parent</artifactId>
		<version>6.77</version>
	</parent>
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.esferalia.aon</groupId>
	<artifactId>aon.gwt</artifactId>
	<packaging>jar</packaging>
	<version>6.77</version>
	<description>AON GWT Widget Library</description>
	<name>AON GWT</name>
	<scm>
		<developerConnection>scm:svn:http://dev.esferalia.com/repos/aon-application/trunk/aon-gwt-common</developerConnection>
		<connection>scm:svn:http://dev.esferalia.com/repos/aon-application/trunk/aon-gwt-common</connection>
		<url>http://dev.esferalia.com/websvn/wsvn/on-application/trunk/aon-gwt-common</url>
	</scm>
	<properties>
		<maven.build.timestamp.format>dd/MM/yyyy</maven.build.timestamp.format>
	</properties>

	<build>
		<plugins>

			<!-- plugin> <groupId>org.codehaus.mojo</groupId> <artifactId>buildnumber-maven-plugin</artifactId> 
				<version>1.0-beta-4</version> <executions> <execution> <phase>validate</phase> 
				<goals> <goal>create</goal> </goals> </execution> </executions> <configuration> 
				<doCheck>false</doCheck> <doUpdate>false</doUpdate> </configuration> </plugin -->

			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>gwt-maven-plugin</artifactId>
				<version>2.4.0</version>
				<executions>
					<execution>
						<goals>
							<goal>compile</goal>
							<!--goal>generateAsync</goal -->
							<goal>test</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		</plugins>
                <resources>
                        <resource>
                                <directory>src/main</directory>
                                <includes>
                                        <include>**/client/**</include>
                                        <include>**/public/**</include>
                                        <include>**/*.gwt.xml</include>
                                        <include>**/*.gif</include>
                                        <include>**/*.png</include>
                                        <include>**/*.css</include>
                                </includes>
                        </resource>
                </resources>
	</build>

	<repositories>
		<repository>
			<id>external_free</id>
			<name>Inhouse Snapshot Repository</name>
			<url>http://dev.esferalia.com/maven2_repositories/external_free</url>
			<releases>
				<enabled>true</enabled>
				<updatePolicy>never</updatePolicy>
			</releases>
			<snapshots>
				<enabled>false</enabled>
				<updatePolicy>never</updatePolicy>
			</snapshots>
		</repository>

	</repositories>

	<dependencies>

		<dependency>
			<groupId>com.google.gwt</groupId>
			<artifactId>gwt-user</artifactId>
			<version>2.4.0</version>
			<scope>provided</scope>
		</dependency>

	</dependencies>


    <profiles>
      	<profile>
            <id>perform-stats</id>
        </profile>
    </profiles>
</project>
