bgcolor_color_fondo_pagina = #ffffff
font_fuente_texto_pagina = 3
size_tamano_texto_pagina = 11
color_color_texto_pagina = #000000
border_tamano_borde_pagina = 0
color_color_borde_pagina = #f70e76
img_imagen_fondo_pagina = fondo.jpg

bgcolor_color_fondo_cabecera = #ffffff
font_fuente_texto_cabecera = 
size_tamano_texto_cabecera = 
color_color_texto_cabecera = #000000
border_tamano_borde_cabecera = 10
color_color_borde_cabecera = 
img_imagen_fondo_cabecera = cabecera.jpg
img_mostrar_logo_cabecera = 

color_color_fondo_inicio = #d90d66
color_color_fondo_contacto = #dddddd

border_tamano_borde_imagen = 
color_color_borde_imagen =

bgcolor_color_fondo_titulo = 
font_fuente_texto_titulo =
size_tamano_texto_titulo = 18
color_color_texto_titulo = #f70e76
border_tamano_borde_titulo =
color_color_borde_titulo = 

bgcolor_color_fondo_menu = #ffffff
font_fuente_texto_menu =
size_tamano_texto_menu =
color_color_texto_menu = #000000
color_color_texto_menu_hover = #f70e76
size_tamano_texto_menu_hover =
color_color_fondo_menu_hover =
color_color_borde_menu_hover =
color_color_borde_menu = 
border_tamano_borde_menu = 
color_color_borde_menu =

bgcolor_color_fondo_contenido =
font_fuente_texto_contenido =
size_tamano_texto_contenido = 12
color_color_texto_contenido =
color_color_borde_contenido = 
border_tamano_borde_contenido = 
color_color_borde_contenido =
img_imagen_fondo_contenido =

bgcolor_color_fondo_pie = #415d8b
font_fuente_texto_pie =
size_tamano_texto_pie =
color_color_texto_pie = #ffffff
border_tamano_borde_pie = #000000
color_color_borde_pie =

color_color_texto_link = #415d8b
size_tamano_texto_link =
font_fuente_texto_link =
color_color_texto_hover =
size_tamano_texto_hover =
font_fuente_texto_hover =

bgcolor_color_fondo_sidebar = 
color_color_borde_sidebar =
color_color_texto_slogan = 
size_tamano_texto_slogan =
font_fuente_texto_slogan =