bgcolor_color_fondo_pagina = #ffffff
font_fuente_texto_pagina = 0
size_tamano_texto_pagina = 11
color_color_texto_pagina = #000000
border_tamano_borde_pagina = 
color_color_borde_pagina =
img_imagen_fondo_pagina =

bgcolor_color_fondo_cabecera = #04B4AE
font_fuente_texto_cabecera = 0
size_tamano_texto_cabecera = 11
color_color_texto_cabecera = #ffffff
border_tamano_borde_cabecera = 
color_color_borde_cabecera = #04B4AE
img_imagen_fondo_cabecera =

img_mostrar_logo_cabecera = si 
border_tamano_borde_imagen = #ffffff
color_color_borde_imagen =

bgcolor_color_fondo_logo = #ffffff

bgcolor_color_fondo_titulo = #ffffff
font_fuente_texto_titulo =
size_tamano_texto_titulo = 14
color_color_texto_titulo = #0B615E
border_tamano_borde_titulo = 
color_color_borde_titulo = 

bgcolor_color_fondo_menu = #ffffff
font_fuente_texto_menu =
size_tamano_texto_menu =
color_color_texto_menu = #0B3B39
color_color_borde_menu = #04B4AE
color_color_texto_menu_hover = 
size_tamano_texto_menu_hover =
color_color_fondo_menu_hover =
color_color_borde_menu_hover =
border_tamano_borde_menu = 
color_color_borde_menu = #236a89

bgcolor_color_fondo_contenido =
font_fuente_texto_contenido =
size_tamano_texto_contenido = 
color_color_texto_contenido =
border_tamano_borde_contenido = 
color_color_borde_contenido = 
img_imagen_fondo_contenido =

bgcolor_color_fondo_pie = #04B4AE
font_fuente_texto_pie =
size_tamano_texto_pie = 
color_color_texto_pie = #ffffff
border_tamano_borde_pie = 
color_color_borde_pie =

bgcolor_color_fondo_link =
color_color_texto_link = #04B4AE
size_tamano_texto_link =
font_fuente_texto_link =
color_color_texto_hover =
size_tamano_texto_hover =
font_fuente_texto_hover =

bgcolor_color_fondo_sidebar = 
color_color_borde_sidebar =

color_color_texto_slogan = 
size_tamano_texto_slogan =
font_fuente_texto_slogan =


