<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

	<parent>
		<groupId>com.code.aon</groupId>
		<artifactId>aon.web.parent</artifactId>
		<version>1.0.1</version>
	</parent>
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.code.aon</groupId>
	<artifactId>aon.ui.cms</artifactId>
	<packaging>war</packaging>
	<version>2.0.0</version>
	<description>AON UI CMS</description>
	<name>AON UI CMS</name>
	<dependencies>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.cms</artifactId>
			<version>2.0.0</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.components</artifactId>
			<version>1.0.2-SNAPSHOT</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>commons-net</groupId>
			<artifactId>commons-net</artifactId>
			<version>1.4.1</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>com.sun</groupId>
			<artifactId>jimi</artifactId>
			<version>1.0</version>
			<scope>compile</scope>
		</dependency>
	</dependencies>
</project>