//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.30 at 11:03:18 AM CET 
//


package net.aonsolutions.core.araba.sii;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 *  Datos de contexto de un suministro 
 * 
 * <p>Java class for CabeceraSii complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CabeceraSii">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="IDVersionSii" type="{https://sii.araba.eus/documentos/SuministroInformacion.xsd}VersionSiiType"/>
 *         &lt;element name="Titular" type="{https://sii.araba.eus/documentos/SuministroInformacion.xsd}PersonaFisicaJuridicaESType"/>
 *         &lt;element name="TipoComunicacion" type="{https://sii.araba.eus/documentos/SuministroInformacion.xsd}ClaveTipoComunicacionType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CabeceraSii", propOrder = {
    "idVersionSii",
    "titular",
    "tipoComunicacion"
})
public class CabeceraSii {

    @XmlElement(name = "IDVersionSii", required = true)
    protected String idVersionSii;
    @XmlElement(name = "Titular", required = true)
    protected PersonaFisicaJuridicaESType titular;
    @XmlElement(name = "TipoComunicacion", required = true)
    @XmlSchemaType(name = "string")
    protected ClaveTipoComunicacionType tipoComunicacion;

    /**
     * Gets the value of the idVersionSii property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIDVersionSii() {
        return idVersionSii;
    }

    /**
     * Sets the value of the idVersionSii property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIDVersionSii(String value) {
        this.idVersionSii = value;
    }

    /**
     * Gets the value of the titular property.
     * 
     * @return
     *     possible object is
     *     {@link PersonaFisicaJuridicaESType }
     *     
     */
    public PersonaFisicaJuridicaESType getTitular() {
        return titular;
    }

    /**
     * Sets the value of the titular property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonaFisicaJuridicaESType }
     *     
     */
    public void setTitular(PersonaFisicaJuridicaESType value) {
        this.titular = value;
    }

    /**
     * Gets the value of the tipoComunicacion property.
     * 
     * @return
     *     possible object is
     *     {@link ClaveTipoComunicacionType }
     *     
     */
    public ClaveTipoComunicacionType getTipoComunicacion() {
        return tipoComunicacion;
    }

    /**
     * Sets the value of the tipoComunicacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClaveTipoComunicacionType }
     *     
     */
    public void setTipoComunicacion(ClaveTipoComunicacionType value) {
        this.tipoComunicacion = value;
    }

}
