//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.30 at 11:02:08 AM CET 
//


package net.aonsolutions.core.araba.sii;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RegistroRespuestaConsultaOperacionesSegurosType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RegistroRespuestaConsultaOperacionesSegurosType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DatosOperacionesSeguros" type="{https://sii.araba.eus/documentos/RespuestaConsultaLR.xsd}RespuestaOperacionesSegurosType"/>
 *         &lt;element name="DatosPresentacion" type="{https://sii.araba.eus/documentos/SuministroInformacion.xsd}DatosPresentacion2Type"/>
 *         &lt;element name="EstadoOperacionesSeguros" type="{https://sii.araba.eus/documentos/RespuestaConsultaLR.xsd}EstadoFactura2Type"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RegistroRespuestaConsultaOperacionesSegurosType", namespace = "https://sii.araba.eus/documentos/RespuestaConsultaLR.xsd", propOrder = {
    "datosOperacionesSeguros",
    "datosPresentacion",
    "estadoOperacionesSeguros"
})
public class RegistroRespuestaConsultaOperacionesSegurosType {

    @XmlElement(name = "DatosOperacionesSeguros", required = true)
    protected RespuestaOperacionesSegurosType datosOperacionesSeguros;
    @XmlElement(name = "DatosPresentacion", required = true)
    protected DatosPresentacion2Type datosPresentacion;
    @XmlElement(name = "EstadoOperacionesSeguros", required = true)
    protected EstadoFactura2Type estadoOperacionesSeguros;

    /**
     * Gets the value of the datosOperacionesSeguros property.
     * 
     * @return
     *     possible object is
     *     {@link RespuestaOperacionesSegurosType }
     *     
     */
    public RespuestaOperacionesSegurosType getDatosOperacionesSeguros() {
        return datosOperacionesSeguros;
    }

    /**
     * Sets the value of the datosOperacionesSeguros property.
     * 
     * @param value
     *     allowed object is
     *     {@link RespuestaOperacionesSegurosType }
     *     
     */
    public void setDatosOperacionesSeguros(RespuestaOperacionesSegurosType value) {
        this.datosOperacionesSeguros = value;
    }

    /**
     * Gets the value of the datosPresentacion property.
     * 
     * @return
     *     possible object is
     *     {@link DatosPresentacion2Type }
     *     
     */
    public DatosPresentacion2Type getDatosPresentacion() {
        return datosPresentacion;
    }

    /**
     * Sets the value of the datosPresentacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatosPresentacion2Type }
     *     
     */
    public void setDatosPresentacion(DatosPresentacion2Type value) {
        this.datosPresentacion = value;
    }

    /**
     * Gets the value of the estadoOperacionesSeguros property.
     * 
     * @return
     *     possible object is
     *     {@link EstadoFactura2Type }
     *     
     */
    public EstadoFactura2Type getEstadoOperacionesSeguros() {
        return estadoOperacionesSeguros;
    }

    /**
     * Sets the value of the estadoOperacionesSeguros property.
     * 
     * @param value
     *     allowed object is
     *     {@link EstadoFactura2Type }
     *     
     */
    public void setEstadoOperacionesSeguros(EstadoFactura2Type value) {
        this.estadoOperacionesSeguros = value;
    }

}
