<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>com.code.aon</groupId>
		<artifactId>aon.parent</artifactId>
		<version>9.23-SNAPSHOT</version>
	</parent>
	<groupId>com.esferalia.aon</groupId>
	<artifactId>aon.watson</artifactId>
	<name>AON WATSON</name>
	<description>
		"El criado obedece; los mayordomos anticipamos deseos"
	</description>
	
	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<configuration>
					<encoding>UTF-8</encoding>
					<compilerArgs>
						<!--
						<arg>-Werror</arg>
						-->
						<arg>-Xlint:all</arg>
					</compilerArgs>
				</configuration>
			</plugin>
		</plugins>
	</build>
	
	<dependencies>
		<!--
			******************************************************************
			¡¡ANALIZAR EXHAUSTIVAMENTE SI ES NECESARIO CREAR UNA DEPENDENCIA!!  
			******************************************************************
			
					ESTE PROYECTO NO DEBE TENER DEPENDENCIAS
			
			******************************************************************
			******************************************************************
		 -->
		 
		<!-- **** TEST DEPENDENCIES **** -->
		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter</artifactId>
			<version>5.13.3</version>
			<scope>test</scope>
		</dependency>
	</dependencies>
</project>
