
export const BANKS = [
    {code: '0019', bic: 'DEUTESBBXXX', bank: 'DEUTSCHE BANK, S.A.E.'},
    {code: '0058', bic: 'BNPAESMMXXX', bank: 'BNP PARIBAS ESPAÑA, S.A.'},
    {code: '0065', bic: 'BARCESMMXXX', bank: 'BARCLAYS BANK, S.A.'},
    {code: '0108', bic: 'SOGEESMMXXX', bank: 'SOCIETE GENERALE, SUCURSAL EN ESPAÑA'},
    {code: '0144', bic: 'PARBESMXXXX', bank: 'BNP PARIBAS SECURITIES SERVICES, SUCURSAL EN ESPAÑA'},
    {code: '0149', bic: 'BNPAESMSXXX', bank: 'BNP PARIBAS, SUCURSAL EN ESPAÑA'},
    {code: '0152', bic: 'BPLCESMMXXX', bank: 'BARCLAYS BANK PLC, SUCURSAL EN ESPAÑA'},
    {code: '0159', bic: 'COBAESMXXXX', bank: 'COMMERZBANK AKTIENGESELLSCHAFT, SUCURSAL EN ESPAÑA'},
    {code: '0162', bic: 'MIDLESMMXXX', bank: 'HSBC BANK PLC, SUCURSAL EN ESPAÑA'},
    {code: '0167', bic: 'GEBAESMMXXX', bank: 'BNP PARIBAS FORTIS, S.A., N.V., SUCURSAL EN ESPAÑA'},
    {code: '0196', bic: 'WELAESMMXXX', bank: 'PORTIGON AG, SUCURSAL EN ESPAÑA'},
    {code: '0226', bic: 'UBSWESMMXXX', bank: 'UBS BANK, S.A.'},
    {code: '1467', bic: 'EHYPESMXXXX', bank: 'HYPOTHEKENBANK FRANKFURT AG., SUCURSAL EN ESPAÑA'},
    {code: '1474', bic: 'CITIESMXXXX', bank: 'CITIBANK INTERNATIONAL LTD, SUCURSAL EN ESPAÑA'},
    {code: '3656', bic: 'CSSOES2SFIN', bank: 'FINANDUERO, SOCIEDAD DE VALORES, S.A.'},
    {code: '0156', bic: 'ABNAESMMXXX', bank: 'THE ROYAL BANK OF SCOTLAND PLC, SUCURSAL EN ESPAÑA'},
    {code: '3524', bic: 'AHCFESMMXXX', bank: 'AHORRO CORPORACION FINANCIERA, S.A., SOCIEDAD DE VALORES'},
    {code: '0188', bic: 'ALCLESMMXXX', bank: 'BANCO ALCALA, S.A.'},
    {code: '0136', bic: 'AREBESMMXXX', bank: 'ARESBANK, S.A.'},
    {code: '0078', bic: 'BAPUES22XXX', bank: 'BANCA PUEYO, S.A.'},
    {code: '2095', bic: 'BASKES2BXXX', bank: 'KUTXABANK, S.A.'},
    {code: '0190', bic: 'BBPIESMMXXX', bank: 'BANCO BPI, S.A., SUCURSAL EN ESPAÑA'},
    {code: '0168', bic: 'BBRUESMXXXX', bank: 'ING BELGIUM, S.A., SUCURSAL EN ESPAÑA'},
    {code: '0182', bic: 'BBVAESMMXXX', bank: 'BANCO BILBAO VIZCAYA ARGENTARIA, S.A.'},
    {code: '0240', bic: 'BCCAESMMXXX', bank: 'BANCO DE CRÉDITO SOCIAL COOPERATIVO S.A.'},
    {code: '3081', bic: 'BCOEESMM081', bank: 'CAJA RURAL DE CASTILLA-LA MANCHA, S.C.C.'},
    {code: '0198', bic: 'BCOEESMMXXX', bank: 'BANCO COOPERATIVO ESPAÑOL, S.A.'},                
    {code: '0131', bic: 'BESMESMMXXX', bank: 'NOVO BANCO, S.A., SUCURSAL EN ESPAÑA'},                     
    {code: '0186', bic: 'BFIVESBBXXX', bank: 'BANCO MEDIOLANUM, S.A.'},
    {code: '0128', bic: 'BKBKESMMXXX', bank: 'BANKINTER, S.A.'},
    {code: '0138', bic: 'BKOAES22XXX', bank: 'BANKOA, S.A.'},
    {code: '0061', bic: 'BMARES2MXXX', bank: 'BANCA MARCH, S.A.'},
    {code: '0219', bic: 'BMCEESMMXXX', bank: 'BANQUE MAROCAINE COMMERCE EXTERIEUR INTERNATIONAL, S.A.'},
    {code: '0160', bic: 'BOTKESMXXXX', bank: 'THE BANK OF TOKYO-MITSUBISHI UFJ, LTD, SUCURSAL EN ESPAÑA'},
    {code: '0155', bic: 'BRASESMMXXX', bank: 'BANCO DO BRASIL AG, SUCURSAL EN ESPAÑA'},
    {code: '0081', bic: 'BSABESBBXXX', bank: 'BANCO DE SABADELL, S.A.'},
    {code: '0049', bic: 'BSCHESMMXXX', bank: 'BANCO SANTANDER, S.A.'},
    {code: '0154', bic: 'BSUIESMMXXX', bank: 'CREDIT AGRICOLE CORPORATE AND INVESTMENT BANK, SUCURSAL EN ESPAÑA'},
    {code: '0094', bic: 'BVALESMMXXX', bank: 'RBC INVESTOR SERVICES ESPAÑA, S.A.'},
    {code: '2080', bic: 'CAGLESMMVIG', bank: 'ABANCA CORPORACIÓN BANCARIA, S.A.'},                     
    {code: '2038', bic: 'CAHMESMMXXX', bank: 'BANKIA, S.A.'},
    {code: '2100', bic: 'CAIXESBBXXX', bank: 'CAIXABANK, S.A.'},
    {code: '3604', bic: 'CAPIESMMXXX', bank: 'CM CAPITAL MARKETS BOLSA, SOCIEDAD DE VALORES, S.A.'},
    {code: '3183', bic: 'CASDESBBXXX', bank: 'CAJA DE ARQUITECTOS, S.C.C.'},
    {code: '2085', bic: 'CAZRES2ZXXX', bank: 'IBERCAJA BANCO, S.A.'},
    {code: '0234', bic: 'CCOCESMMXXX', bank: 'BANCO CAMINOS, S.A.'},
    {code: '3058', bic: 'CCRIES2AXXX', bank: 'CAJAS RURALES UNIDAS, S.C.C.'},
    {code: '3025', bic: 'CDENESBBXXX', bank: 'CAIXA DE CREDIT DELS ENGINYERS - CAJA DE CREDITO DE LOS INGENIEROS, S.C.C.'},
    {code: '2045', bic: 'CECAESMM045', bank: 'CAJA DE AHORROS Y M.P. DE ONTINYENT'},
    {code: '2048', bic: 'CECAESMM048', bank: 'LIBERBANK, S.A.'},
    {code: '2056', bic: 'CECAESMM056', bank: `COLONYA - CAIXA D'ESTALVIS DE POLLENSA`},
    {code: '2105', bic: 'CECAESMM105', bank: 'BANCO DE CASTILLA-LA MANCHA, S.A. /CAJA DE AHORROS DE CASTILLA-LA MANCHA'},
    {code: '2000', bic: 'CECAESMMXXX', bank: 'CECABANK, S.A.'},
    {code: '2013', bic: 'CESCESBBXXX', bank: 'CATALUNYA BANC, S.A.'},
    {code: '0130', bic: 'CGDIESMMXXX', bank: 'BANCO CAIXA GERAL, S.A.'},
    {code: '0122', bic: 'CITIES2XXXX', bank: 'CITIBANK ESPAÑA, S.A.'},
    {code: '3035', bic: 'CLPEES2MXXX', bank: 'CAJA LABORAL POPULAR, C.C.'},
    {code: '1460', bic: 'CRESESMMXXX', bank: 'CREDIT SUISSE AG, SUCURSAL EN ESPAÑA'},
    {code: '2108', bic: 'CSPAES2L108', bank: 'BANCO DE CAJA ESPAÑA DE INVERSIONES, SALAMANCA Y SORIA, S.A.'},
    {code: '0237', bic: 'CSURES2CXXX', bank: 'CAJASUR BANCO, S.A.'},
    {code: '0231', bic: 'DSBLESMMXXX', bank: 'DEXIA SABADELL, S.A.'},
    {code: '9000', bic: 'ESPBESMMXXX', bank: 'BANCO DE ESPAÑA'},
    {code: '1497', bic: 'ESSIESMMXXX', bank: 'BANCO ESPIRITO SANTO DE INVESTIMENTO, S.A., SUCURSAL EN ESPAÑA'},
    {code: '0239', bic: 'EVOBESMMXXX', bank: 'EVO BANCO S.A.U.'},
    {code: '0220', bic: 'FIOFESM1XXX', bank: 'BANCO FINANTIA SOFINLOC, S.A.'},
    {code: '0487', bic: 'GBMNESMMXXX', bank: 'BANCO MARE NOSTRUM, S.A.'},
    {code: '3682', bic: 'GVCBESBBETB', bank: 'GVC GAESCO VALORES, SOCIEDAD DE VALORES, S.A.'},
    {code: '9096', bic: 'IBRCESMMXXX', bank: 'SOCIEDAD DE GESTION DE LOS SISTEMAS DE REGISTRO, COMPENSACION Y LIQUIDACION DE VALORES, S.A.U.'},		
    {code: '1000', bic: 'ICROESMMXXX', bank: 'INSTITUTO DE CREDITO OFICIAL'},
    {code: '1465', bic: 'INGDESMMXXX', bank: 'ING BANK, N.V., SUCURSAL EN ESPAÑA'},
    {code: '3575', bic: 'INSGESMMXXX', bank: 'INVERSEGUROS, SOCIEDAD DE VALORES, S.A.'},
    {code: '0232', bic: 'INVLESMMXXX', bank: 'BANCO INVERSIS, S.A.'},
    {code: '9020', bic: 'IPAYESMMXXX', bank: 'SOCIEDAD ESPAÑOLA DE SISTEMAS DE PAGO, S.A.'},
    {code: '3669', bic: 'IVALESMMXXX', bank: 'INTERMONEY VALORES, SOCIEDAD DE VALORES, S.A.'},
    {code: '3641', bic: 'LISEESMMXXX', bank: 'LINK SECURITIES, SOCIEDAD DE VALORES, S.A.'},
    {code: '0059', bic: 'MADRESMMXXX', bank: 'BANCO DE MADRID, S.A.'},
    {code: '9094', bic: 'MEFFESBBXXX', bank: 'BME CLEARING, S.A.'},
    {code: '3563', bic: 'MISVESMMXXX', bank: 'MAPFRE INVERSION, SOCIEDAD DE VALORES, S.A.'},
    {code: '3661', bic: 'MLCEESMMXXX', bank: 'MERRILL LYNCH CAPITAL MARKETS ESPAÑA, S.A., SOCIEDAD DE VALORES'},
    {code: '0169', bic: 'NACNESMMXXX', bank: 'BANCO DE LA NACION ARGENTINA, SUCURSAL EN ESPAÑA '},
    {code: '1479', bic: 'NATXESMMXXX', bank: 'NATIXIS, S.A., SUCURSAL EN ESPAÑA'},
    {code: '0216', bic: 'POHIESMMXXX', bank: 'TARGOBANK, S.A.'},
    {code: '0233', bic: 'POPIESMMXXX', bank: 'POPULAR BANCA PRIVADA, S.A.'},
    {code: '0229', bic: 'POPLESMMXXX', bank: 'BANCOPOPULAR-E, S.A.'},
    {code: '0075', bic: 'POPUESMMXXX', bank: 'BANCO POPULAR ESPAÑOL, S.A.'},
    {code: '1459', bic: 'PRABESMMXXX', bank: 'COOPERATIEVE CENTRALE RAIFFEISEN-BOERENLEENBANK B.A. (RABOBANK NEDERLAND), SUCURSAL EN ESPAÑA'},
    {code: '0241', bic: 'PRDVESM1XXX', bank: 'AyG BANCA PRIVADA S.A.U.'},
    {code: '0211', bic: 'PROAESMMXXX', bank: 'EBN BANCO DE NEGOCIOS, S.A.'},
    {code: '0238', bic: 'PSTRESMMXXX', bank: 'BANCO PASTOR, S.A.'},
    {code: '0083', bic: 'RENBESMMXXX', bank: 'RENTA 4 BANCO, S.A.'},
    {code: '3501', bic: 'RENTESMMXXX', bank: 'RENTA 4 SOCIEDAD DE VALORES, S.A.'},
    {code: '1524', bic: 'UBIBESMMXXX', bank: 'UBI BANCA INTERNATIONAL, S.A., SUCURSAL EN ESPAÑA'},
    {code: '2103', bic: 'UCJAES2MXXX', bank: 'UNICAJA BANCO, S.A.'},
    {code: '9091', bic: 'XBCNESBBXXX', bank: 'SOCIEDAD RECTORA BOLSA VALORES DE BARCELONA, S.A., S.R.B.V.'},
    {code: '9092', bic: 'XRBVES2BXXX', bank: 'SOCIEDAD RECTORA BOLSA DE VALORES DE BILBAO, S.A., S.R.B.V.'},
    {code: '9093', bic: 'XRVVESVVXXX', bank: 'SOCIEDAD RECTORA BOLSA VALORES DE VALENCIA, S.A., S.R.B.V.'},
    {code: '0133', bic: '', bank: ''},
    {code: '1491', bic: 'TRIOESMMXXX', bank: 'TRIODOS BANK'},
    {code: '0073', bic: 'OPENESMM', bank: 'OPENBANK'},
    {code: '0030', bic: 'BAEMESM1XXX', bank: 'BANESTO'},
    {code: '0004', bic: 'POPUESMMXXX',  bank: 'BANCO DE ANDALUCIA, S.A.'},
    {code: '2024', bic: 'CSURES2CXXX', bank: 'BBK BANK CAJASUR S.A.U.'},
    {code: '2106', bic: 'CECAESMM106', bank: 'CAJASOL'}, 
    {code: '3005', bic: 'BCOEESMM005', bank: 'CAJA RURAL CENTRAL'},
    {code: '3016', bic: 'BCOEESMM016', bank: 'CAJA RURAL DE SALAMANCA'},
    {code: '3020', bic: 'BCOEESMM020', bank: 'CAJA RURAL DE UTRERA'},
    {code: '3029', bic: 'BCOEESMM029', bank: 'CAJA DE CREDITO DE PETREL, CAIXAPETRER'},
    {code: '3059', bic: 'BCOEESMM059', bank: 'CAJA RURAL DE ASTURIAS'},
    {code: '3060', bic: 'BCOEESMM060', bank: 'CAJA RURAL DE BURGOS'},
    {code: '3063', bic: 'BCOEESMM063', bank: 'CAJA RURAL DE CORDOBA'},
    {code: '3067', bic: 'BCOEESMM067', bank: 'CAJA RURAL DE JAEN'},
    {code: '3070', bic: 'BCOEESMM070', bank: 'CAIXA RURAL GALEGA'},
    {code: '3076', bic: 'BCOEESMM076', bank: 'CAJA RURAL DE TENERIFE'},
    {code: '3080', bic: 'BCOEESMM080', bank: 'CAJA RURAL DE TERUEL'},
    {code: '3085', bic: 'BCOEESMM085', bank: 'CAJA RURAL DE ZAMORA'},
    {code: '3159', bic: 'BCOEESMM159', bank: 'CAIXA POPULAR, CAIXA RURAL'},
    {code: '3187', bic: 'BCOEESMM187', bank: 'CAJA RURAL DEL SUR'},
    {code: '3190', bic: 'BCOEESMM190', bank: 'CAJA RURAL ALBACETE C. REAL CUENCA'},
    {code: '3191', bic: 'BCOEESMM191', bank: 'CAJA RURAL DE ARAGON'},
    {code: '3023', bic: 'BCOEESMM023', bank: 'CAJA RURAL DE GRANADA'},
];

export const getBank = (code) => {
    let banks = BANKS.filter(f => f.code === code);
    return banks.length > 0 ? banks[0] : {code, bic: '', bank:''}; 
}

