<?xml version="1.0"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<parent>
		<groupId>com.code.aon</groupId>
		<artifactId>aon.web.parent</artifactId>
		<version>6.21-SNAPSHOT</version>
	</parent>
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.code.aon</groupId>
	<artifactId>aon-external-libs</artifactId>
	<version>6.21-SNAPSHOT</version>
	<description>AON EXTERNAL LIBS</description>
	<name>AON EXTERNAL LIBS</name>

	<scm>
		<url>http://dev.esferalia.com/websvn/wsvn/aon-external-libs</url>
		<connection>scm:svn:http://dev.esferalia.com/repos/aon-application/trunk/aon-external-libs</connection>
		<developerConnection>scm:svn:http://dev.esferalia.com/repos/aon-application/trunk/aon-external-libs</developerConnection>
	</scm>

	<dependencies>
		<dependency>
			<groupId>axis</groupId>
			<artifactId>axis</artifactId>
			<version>1.3</version>
		</dependency>
		<dependency>
			<groupId>axis</groupId>
			<artifactId>axis-saaj</artifactId>
			<version>1.3</version>
		</dependency>
		<dependency>
			<groupId>axis</groupId>
			<artifactId>axis-jaxrpc</artifactId>
			<version>1.3</version>
		</dependency>
		<dependency>
			<groupId>org.bouncycastle</groupId>
			<artifactId>bcmail-jdk14</artifactId>
			<version>1.38</version>
		</dependency>
		<dependency>
			<groupId>org.bouncycastle</groupId>
			<artifactId>bcprov-jdk14</artifactId>
			<version>1.38</version>
		</dependency>
		<dependency>
			<groupId>org.bouncycastle</groupId>
			<artifactId>bctsp-jdk14</artifactId>
			<version>1.38</version>
		</dependency>
		<dependency>
			<groupId>commons-beanutils</groupId>
			<artifactId>commons-beanutils</artifactId>
			<version>1.8.3</version>
		</dependency>
		<dependency>
			<groupId>commons-dbutils</groupId>
			<artifactId>commons-dbutils</artifactId>
			<version>1.3</version>
		</dependency>
		<dependency>
			<groupId>commons-digester</groupId>
			<artifactId>commons-digester</artifactId>
			<version>2.0</version>
		</dependency>
		<dependency>
			<groupId>commons-discovery</groupId>
			<artifactId>commons-discovery</artifactId>
			<version>0.2</version>
		</dependency>
		<dependency>
			<groupId>commons-io</groupId>
			<artifactId>commons-io</artifactId>
			<version>1.4</version>
		</dependency>
		<dependency>
			<groupId>commons-lang</groupId>
			<artifactId>commons-lang</artifactId>
			<version>2.5</version>
		</dependency>
		<dependency>
			<groupId>commons-net</groupId>
			<artifactId>commons-net</artifactId>
			<version>2.1</version>
		</dependency>
		<dependency>
			<groupId>commons-validator</groupId>
			<artifactId>commons-validator</artifactId>
			<version>1.3.1</version>
		</dependency>
		<dependency>
			<groupId>commons-net</groupId>
			<artifactId>commons-net</artifactId>
			<version>2.1</version>
		</dependency>
		<dependency>
			<groupId>org.richfaces.ui</groupId>
			<artifactId>richfaces-ui</artifactId>
			<version>3.3.3.Final</version>
		</dependency>
		<dependency>
			<groupId>org.richfaces.framework</groupId>
			<artifactId>richfaces-api</artifactId>
			<version>3.3.3.Final</version>
		</dependency>
		<dependency>
			<groupId>org.richfaces.framework</groupId>
			<artifactId>richfaces-impl</artifactId>
			<version>3.3.3.Final</version>
		</dependency>
		<dependency>
			<groupId>org.apache.velocity</groupId>
			<artifactId>velocity</artifactId>
			<version>1.6.4</version>
		</dependency>
		<dependency>
			<groupId>velocity-tools</groupId>
			<artifactId>velocity-tools</artifactId>
			<version>1.2</version>
		</dependency>
		<dependency>
			<groupId>com.lowagie</groupId>
			<artifactId>itext</artifactId>
			<version>2.1.7</version>
		</dependency>
		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi</artifactId>
			<version>3.6</version>
		</dependency>
		<dependency>
			<groupId>jfree</groupId>
			<artifactId>jcommon</artifactId>
			<version>1.0.15</version>
		</dependency>
		<dependency>
			<groupId>jfree</groupId>
			<artifactId>jfreechart</artifactId>
			<version>1.0.12</version>
		</dependency>
		<dependency>
			<groupId>com.sun</groupId>
			<artifactId>jimi</artifactId>
			<version>1.0</version>
		</dependency>
		<dependency>
			<groupId>jmimemagic</groupId>
			<artifactId>jmimemagic</artifactId>
			<version>0.1.2</version>
		</dependency>
		<dependency>
			<groupId>com.sun.facelets</groupId>
			<artifactId>jsf-facelets</artifactId>
			<version>1.1.15</version>
		</dependency>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-api</artifactId>
			<version>1.5.11</version>
		</dependency>
		<dependency>
			<groupId>jtidy</groupId>
			<artifactId>jtidy</artifactId>
			<version>r938.mod</version>
		</dependency>
		<dependency>
			<groupId>eu.medsea.mimeutil</groupId>
			<artifactId>mime-util</artifactId>
			<version>2.1.3</version>
		</dependency>
		<dependency>
			<groupId>es.mityc</groupId>
			<artifactId>facturae-api</artifactId>
			<version>1.0.0</version>
		</dependency>
		<dependency>
			<groupId>org.apache.sanselan</groupId>
			<artifactId>sanselan</artifactId>
			<version>0.97-incubator</version>
		</dependency>
		<dependency>
			<groupId>sinadura</groupId>
			<artifactId>sinaduraCore</artifactId>
			<version>1.3.0.MOD2</version>
		</dependency>
		<dependency>
			<groupId>com.esendex</groupId>
			<artifactId>Esendex</artifactId>
			<version>0.0.1</version>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.jsf.bridge</artifactId>
			<version>${pom.version}</version>
		</dependency>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-api</artifactId>
			<version>1.5.11</version>
		</dependency>
		<dependency>
			<groupId>net.sf.jasperreports</groupId>
			<artifactId>jasperreports</artifactId>
			<version>4.0.0</version>
		</dependency>
		<dependency>
			<groupId>oro</groupId>
			<artifactId>oro</artifactId>
			<version>2.0.8</version>
		</dependency>
		<dependency>
			<groupId>javax.mail</groupId>
			<artifactId>mail</artifactId>
			<version>1.4.4</version>
		</dependency>
		<dependency>
			<groupId>org.jboss.slf4j</groupId>
			<artifactId>slf4j-jboss-logging</artifactId>
			<version>1.0.2.GA</version>
		</dependency>
		<dependency>
			<groupId>ar.com.fdvs</groupId>
			<artifactId>DynamicJasper</artifactId>
			<version>3.1.2</version>
		</dependency>
	</dependencies>
	<profiles>
		<profile>
			<id>rpm-release</id>
			<activation>
				<property>
					<name>rpm.release</name>
					<value>true</value>
				</property>
			</activation>
			<build>
				<plugins>
					<!-- Para construir el RPM -->
					<plugin>

						<groupId>org.codehaus.mojo</groupId>
						<artifactId>rpm-maven-plugin</artifactId>
						<version>2.0.1</version>
						<extensions>true</extensions>

						<executions>
							<execution>
								<id>rpm-build</id>
								<goals>
									<goal>attached-rpm</goal>
								</goals>
							</execution>

						</executions>

						<configuration>
							<group>Applications/Aon</group>
							<release>${buildNumber}</release>
							<copyright>2010, esferalia Networks S.A</copyright>
							<requires>
								<require>aon-master</require>
							</requires>
							<mappings>
								<mapping>
									<filemode>755</filemode>
									<username>root</username>
									<groupname>root</groupname>
									<directory>/var/lib/jbossas/server/default/lib</directory>
									<sources>
										<source>
											<includes>
												<include>*.jar</include>
											</includes>
											<location>target</location>
										</source>
										<softlinkSource>
											<location>/usr/share/java/aon-master.jar</location>
											<destination>aon-master.jar</destination>
										</softlinkSource>
										<softlinkSource>
											<location>/usr/share/java/aon-dbutils.jar</location>
											<destination>aon-dbutils.jar</destination>
										</softlinkSource>
									</sources>

									<dependency>
										<includes>
											<include>axis:axis:1.3</include>
											<include>axis:axis-saaj:1.3</include>
											<include>axis:axis-jaxrpc:1.3</include>
											<include>org.bouncycastle:bcmail-jdk14:1.38</include>
											<include>org.bouncycastle:bcprov-jdk14:1.38</include>
											<include>org.bouncycastle:bctsp-jdk14:1.38</include>
											<include>commons-beanutils:commons-beanutils:1.8.3</include>
											<include>commons-dbutils:commons-dbutils:1.3</include>
											<include>commons-digester:commons-digester:2.0</include>
											<include>commons-discovery:commons-discovery:0.2</include>
											<include>commons-io:commons-io:1.4</include>
											<include>commons-lang:commons-lang:2.5</include>
											<include>commons-net:commons-net:2.1</include>
											<include>commons-validator:commons-validator:1.3.1</include>
											<include>org.richfaces.ui:richfaces-ui:3.3.3.Final</include>
											<include>org.richfaces.framework:richfaces-api:3.3.3.Final</include>
											<include>org.richfaces.framework:richfaces-impl:3.3.3.Final</include>
											<include>org.apache.velocity:velocity:1.6.4</include>
											<include>velocity-tools:velocity-tools:1.2</include>
											<include>com.lowagie:itext:2.1.7</include>
											<include>org.apache.poi:poi:3.6</include>
											<include>jfree:jcommon:1.0.15</include>
											<include>jfree:jfreechart:1.0.12</include>
											<include>com.sun:jimi:1.0</include>
											<include>jmimemagic:jmimemagic:0.1.2</include>
											<include>com.sun.facelets:jsf-facelets:1.1.15</include>
											<include>org.slf4j:slf4j-api:1.5.11</include>
											<include>jtidy:jtidy:r938.mod</include>
											<include>eu.medsea.mimeutil:mime-util:2.1.3</include>
											<include>es.mityc:facturae-api:1.0.0</include>
											<include>org.apache.sanselan:sanselan:0.97-incubator</include>
											<include>sinadura:sinaduraCore:1.3.0.MOD2</include>
											<include>com.esendex:Esendex:0.0.1</include>
											<include>com.code.aon:aon.jsf.bridge:${pom.version}</include>
											<include>org.slf4j:slf4j-api:1.5.11</include>
											<include>net.sf.jasperreports:jasperreports:4.0.0</include>
											<include>ar.com.fdvs:DynamicJasper:3.1.2</include>
											<include>oro:oro:2.0.8</include>
											<include>javax.mail:mail:1.4.2</include>
											<include>org.jboss.slf4j:slf4j-jboss-logging:1.0.2.GA</include>
										</includes>
									</dependency>
								</mapping>

							</mappings>

							<postinstallScriptlet>
								<scriptFile>src/main/scripts/postinstall</scriptFile>
								<fileEncoding>utf-8</fileEncoding>
							</postinstallScriptlet>


						</configuration>
					</plugin>


				</plugins>
			</build>
		</profile>
	</profiles>
</project>
 
