//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.01.31 at 09:35:14 AM UTC 
//


package net.aonsolutions.fiscal.mod100.e2023;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tipo_GPDerechos complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tipo_GPDerechos"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="EntidadDerecho" maxOccurs="60"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="G2CDE" type="{}tipo_String20L" minOccurs="0"/&gt;
 *                   &lt;element name="G2CVT" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="ENTIDADDS" type="{}tipo_String20L"/&gt;
 *                             &lt;element name="DERECHO" maxOccurs="4" minOccurs="0"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;sequence&gt;
 *                                       &lt;element name="ITDS" minOccurs="0"&gt;
 *                                         &lt;complexType&gt;
 *                                           &lt;complexContent&gt;
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                               &lt;sequence&gt;
 *                                                 &lt;element name="IMP1ITDS" type="{}tipo_ImpPositivo" minOccurs="0"/&gt;
 *                                                 &lt;element name="IMP2ITDS" type="{}tipo_ImpPositivo" minOccurs="0"/&gt;
 *                                               &lt;/sequence&gt;
 *                                               &lt;attribute name="valor" type="{}tipo_ImpPositivo" /&gt;
 *                                             &lt;/restriction&gt;
 *                                           &lt;/complexContent&gt;
 *                                         &lt;/complexType&gt;
 *                                       &lt;/element&gt;
 *                                       &lt;element name="IADS" type="{}tipo_ImpPositivo" minOccurs="0"/&gt;
 *                                       &lt;element name="RETDS" type="{}tipo_ImpPositivo" minOccurs="0"/&gt;
 *                                       &lt;element name="RV2DS" minOccurs="0"&gt;
 *                                         &lt;complexType&gt;
 *                                           &lt;complexContent&gt;
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                               &lt;sequence&gt;
 *                                                 &lt;element name="IMP1RV2DS" type="{}tipo_ImpPositivo" minOccurs="0"/&gt;
 *                                                 &lt;element name="IMP2RV2DS" type="{}tipo_ImpPositivo" minOccurs="0"/&gt;
 *                                                 &lt;element name="IMP3RV2DS" type="{}tipo_ImpPositivo" minOccurs="0"/&gt;
 *                                               &lt;/sequence&gt;
 *                                               &lt;attribute name="valor" type="{}tipo_ImpPositivo" /&gt;
 *                                             &lt;/restriction&gt;
 *                                           &lt;/complexContent&gt;
 *                                         &lt;/complexType&gt;
 *                                       &lt;/element&gt;
 *                                       &lt;element name="VTXDS" type="{}tipo_logico" minOccurs="0"/&gt;
 *                                       &lt;element name="DT92DS" type="{}tipo_logico" minOccurs="0"/&gt;
 *                                       &lt;element name="VTDT92DS" type="{}tipo_logico" minOccurs="0"/&gt;
 *                                       &lt;element name="TIPODS" type="{}tipo_String1L" minOccurs="0"/&gt;
 *                                       &lt;element name="FTDS" type="{}tipo_Fecha" minOccurs="0"/&gt;
 *                                       &lt;element name="FADS" type="{}tipo_Fecha" minOccurs="0"/&gt;
 *                                     &lt;/sequence&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                           &lt;/sequence&gt;
 *                           &lt;attribute name="valor" type="{}tipo_ImpPositivo" /&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="G2CVTRV" type="{}tipo_ImpPositivo" minOccurs="0"/&gt;
 *                   &lt;element name="G2CVTDT" type="{}tipo_ImpPositivo" minOccurs="0"/&gt;
 *                   &lt;element name="G2CVA" type="{}tipo_ImpPositivo" minOccurs="0"/&gt;
 *                   &lt;element name="G2CG" type="{}tipo_ImpPositivo" minOccurs="0"/&gt;
 *                   &lt;element name="G2CEXRV" type="{}tipo_ImpPositivo" minOccurs="0"/&gt;
 *                   &lt;element name="G2CGSR" type="{}tipo_ImpPositivo" minOccurs="0"/&gt;
 *                   &lt;element name="G2CDT" type="{}tipo_ImpPositivo" minOccurs="0"/&gt;
 *                   &lt;element name="G2CGR" type="{}tipo_ImpPositivo" minOccurs="0"/&gt;
 *                   &lt;element name="G2CP" type="{}tipo_ImpPositivo" minOccurs="0"/&gt;
 *                   &lt;element name="G2CPA" type="{}tipo_ImpPositivo" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tipo_GPDerechos", propOrder = {
    "entidadDerecho"
})
public class TipoGPDerechos {

    @XmlElement(name = "EntidadDerecho", required = true)
    protected List<TipoGPDerechos.EntidadDerecho> entidadDerecho;

    /**
     * Gets the value of the entidadDerecho property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the entidadDerecho property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEntidadDerecho().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TipoGPDerechos.EntidadDerecho }
     * 
     * 
     */
    public List<TipoGPDerechos.EntidadDerecho> getEntidadDerecho() {
        if (entidadDerecho == null) {
            entidadDerecho = new ArrayList<TipoGPDerechos.EntidadDerecho>();
        }
        return this.entidadDerecho;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="G2CDE" type="{}tipo_String20L" minOccurs="0"/&gt;
     *         &lt;element name="G2CVT" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="ENTIDADDS" type="{}tipo_String20L"/&gt;
     *                   &lt;element name="DERECHO" maxOccurs="4" minOccurs="0"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;sequence&gt;
     *                             &lt;element name="ITDS" minOccurs="0"&gt;
     *                               &lt;complexType&gt;
     *                                 &lt;complexContent&gt;
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                                     &lt;sequence&gt;
     *                                       &lt;element name="IMP1ITDS" type="{}tipo_ImpPositivo" minOccurs="0"/&gt;
     *                                       &lt;element name="IMP2ITDS" type="{}tipo_ImpPositivo" minOccurs="0"/&gt;
     *                                     &lt;/sequence&gt;
     *                                     &lt;attribute name="valor" type="{}tipo_ImpPositivo" /&gt;
     *                                   &lt;/restriction&gt;
     *                                 &lt;/complexContent&gt;
     *                               &lt;/complexType&gt;
     *                             &lt;/element&gt;
     *                             &lt;element name="IADS" type="{}tipo_ImpPositivo" minOccurs="0"/&gt;
     *                             &lt;element name="RETDS" type="{}tipo_ImpPositivo" minOccurs="0"/&gt;
     *                             &lt;element name="RV2DS" minOccurs="0"&gt;
     *                               &lt;complexType&gt;
     *                                 &lt;complexContent&gt;
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                                     &lt;sequence&gt;
     *                                       &lt;element name="IMP1RV2DS" type="{}tipo_ImpPositivo" minOccurs="0"/&gt;
     *                                       &lt;element name="IMP2RV2DS" type="{}tipo_ImpPositivo" minOccurs="0"/&gt;
     *                                       &lt;element name="IMP3RV2DS" type="{}tipo_ImpPositivo" minOccurs="0"/&gt;
     *                                     &lt;/sequence&gt;
     *                                     &lt;attribute name="valor" type="{}tipo_ImpPositivo" /&gt;
     *                                   &lt;/restriction&gt;
     *                                 &lt;/complexContent&gt;
     *                               &lt;/complexType&gt;
     *                             &lt;/element&gt;
     *                             &lt;element name="VTXDS" type="{}tipo_logico" minOccurs="0"/&gt;
     *                             &lt;element name="DT92DS" type="{}tipo_logico" minOccurs="0"/&gt;
     *                             &lt;element name="VTDT92DS" type="{}tipo_logico" minOccurs="0"/&gt;
     *                             &lt;element name="TIPODS" type="{}tipo_String1L" minOccurs="0"/&gt;
     *                             &lt;element name="FTDS" type="{}tipo_Fecha" minOccurs="0"/&gt;
     *                             &lt;element name="FADS" type="{}tipo_Fecha" minOccurs="0"/&gt;
     *                           &lt;/sequence&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                 &lt;/sequence&gt;
     *                 &lt;attribute name="valor" type="{}tipo_ImpPositivo" /&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="G2CVTRV" type="{}tipo_ImpPositivo" minOccurs="0"/&gt;
     *         &lt;element name="G2CVTDT" type="{}tipo_ImpPositivo" minOccurs="0"/&gt;
     *         &lt;element name="G2CVA" type="{}tipo_ImpPositivo" minOccurs="0"/&gt;
     *         &lt;element name="G2CG" type="{}tipo_ImpPositivo" minOccurs="0"/&gt;
     *         &lt;element name="G2CEXRV" type="{}tipo_ImpPositivo" minOccurs="0"/&gt;
     *         &lt;element name="G2CGSR" type="{}tipo_ImpPositivo" minOccurs="0"/&gt;
     *         &lt;element name="G2CDT" type="{}tipo_ImpPositivo" minOccurs="0"/&gt;
     *         &lt;element name="G2CGR" type="{}tipo_ImpPositivo" minOccurs="0"/&gt;
     *         &lt;element name="G2CP" type="{}tipo_ImpPositivo" minOccurs="0"/&gt;
     *         &lt;element name="G2CPA" type="{}tipo_ImpPositivo" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "g2CDE",
        "g2CVT",
        "g2CVTRV",
        "g2CVTDT",
        "g2CVA",
        "g2CG",
        "g2CEXRV",
        "g2CGSR",
        "g2CDT",
        "g2CGR",
        "g2CP",
        "g2CPA"
    })
    public static class EntidadDerecho {

        @XmlElement(name = "G2CDE")
        protected String g2CDE;
        @XmlElement(name = "G2CVT")
        protected TipoGPDerechos.EntidadDerecho.G2CVT g2CVT;
        @XmlElement(name = "G2CVTRV")
        protected BigDecimal g2CVTRV;
        @XmlElement(name = "G2CVTDT")
        protected BigDecimal g2CVTDT;
        @XmlElement(name = "G2CVA")
        protected BigDecimal g2CVA;
        @XmlElement(name = "G2CG")
        protected BigDecimal g2CG;
        @XmlElement(name = "G2CEXRV")
        protected BigDecimal g2CEXRV;
        @XmlElement(name = "G2CGSR")
        protected BigDecimal g2CGSR;
        @XmlElement(name = "G2CDT")
        protected BigDecimal g2CDT;
        @XmlElement(name = "G2CGR")
        protected BigDecimal g2CGR;
        @XmlElement(name = "G2CP")
        protected BigDecimal g2CP;
        @XmlElement(name = "G2CPA")
        protected BigDecimal g2CPA;

        /**
         * Gets the value of the g2CDE property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getG2CDE() {
            return g2CDE;
        }

        /**
         * Sets the value of the g2CDE property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setG2CDE(String value) {
            this.g2CDE = value;
        }

        /**
         * Gets the value of the g2CVT property.
         * 
         * @return
         *     possible object is
         *     {@link TipoGPDerechos.EntidadDerecho.G2CVT }
         *     
         */
        public TipoGPDerechos.EntidadDerecho.G2CVT getG2CVT() {
            return g2CVT;
        }

        /**
         * Sets the value of the g2CVT property.
         * 
         * @param value
         *     allowed object is
         *     {@link TipoGPDerechos.EntidadDerecho.G2CVT }
         *     
         */
        public void setG2CVT(TipoGPDerechos.EntidadDerecho.G2CVT value) {
            this.g2CVT = value;
        }

        /**
         * Gets the value of the g2CVTRV property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getG2CVTRV() {
            return g2CVTRV;
        }

        /**
         * Sets the value of the g2CVTRV property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setG2CVTRV(BigDecimal value) {
            this.g2CVTRV = value;
        }

        /**
         * Gets the value of the g2CVTDT property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getG2CVTDT() {
            return g2CVTDT;
        }

        /**
         * Sets the value of the g2CVTDT property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setG2CVTDT(BigDecimal value) {
            this.g2CVTDT = value;
        }

        /**
         * Gets the value of the g2CVA property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getG2CVA() {
            return g2CVA;
        }

        /**
         * Sets the value of the g2CVA property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setG2CVA(BigDecimal value) {
            this.g2CVA = value;
        }

        /**
         * Gets the value of the g2CG property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getG2CG() {
            return g2CG;
        }

        /**
         * Sets the value of the g2CG property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setG2CG(BigDecimal value) {
            this.g2CG = value;
        }

        /**
         * Gets the value of the g2CEXRV property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getG2CEXRV() {
            return g2CEXRV;
        }

        /**
         * Sets the value of the g2CEXRV property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setG2CEXRV(BigDecimal value) {
            this.g2CEXRV = value;
        }

        /**
         * Gets the value of the g2CGSR property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getG2CGSR() {
            return g2CGSR;
        }

        /**
         * Sets the value of the g2CGSR property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setG2CGSR(BigDecimal value) {
            this.g2CGSR = value;
        }

        /**
         * Gets the value of the g2CDT property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getG2CDT() {
            return g2CDT;
        }

        /**
         * Sets the value of the g2CDT property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setG2CDT(BigDecimal value) {
            this.g2CDT = value;
        }

        /**
         * Gets the value of the g2CGR property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getG2CGR() {
            return g2CGR;
        }

        /**
         * Sets the value of the g2CGR property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setG2CGR(BigDecimal value) {
            this.g2CGR = value;
        }

        /**
         * Gets the value of the g2CP property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getG2CP() {
            return g2CP;
        }

        /**
         * Sets the value of the g2CP property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setG2CP(BigDecimal value) {
            this.g2CP = value;
        }

        /**
         * Gets the value of the g2CPA property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getG2CPA() {
            return g2CPA;
        }

        /**
         * Sets the value of the g2CPA property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setG2CPA(BigDecimal value) {
            this.g2CPA = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="ENTIDADDS" type="{}tipo_String20L"/&gt;
         *         &lt;element name="DERECHO" maxOccurs="4" minOccurs="0"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;sequence&gt;
         *                   &lt;element name="ITDS" minOccurs="0"&gt;
         *                     &lt;complexType&gt;
         *                       &lt;complexContent&gt;
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                           &lt;sequence&gt;
         *                             &lt;element name="IMP1ITDS" type="{}tipo_ImpPositivo" minOccurs="0"/&gt;
         *                             &lt;element name="IMP2ITDS" type="{}tipo_ImpPositivo" minOccurs="0"/&gt;
         *                           &lt;/sequence&gt;
         *                           &lt;attribute name="valor" type="{}tipo_ImpPositivo" /&gt;
         *                         &lt;/restriction&gt;
         *                       &lt;/complexContent&gt;
         *                     &lt;/complexType&gt;
         *                   &lt;/element&gt;
         *                   &lt;element name="IADS" type="{}tipo_ImpPositivo" minOccurs="0"/&gt;
         *                   &lt;element name="RETDS" type="{}tipo_ImpPositivo" minOccurs="0"/&gt;
         *                   &lt;element name="RV2DS" minOccurs="0"&gt;
         *                     &lt;complexType&gt;
         *                       &lt;complexContent&gt;
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                           &lt;sequence&gt;
         *                             &lt;element name="IMP1RV2DS" type="{}tipo_ImpPositivo" minOccurs="0"/&gt;
         *                             &lt;element name="IMP2RV2DS" type="{}tipo_ImpPositivo" minOccurs="0"/&gt;
         *                             &lt;element name="IMP3RV2DS" type="{}tipo_ImpPositivo" minOccurs="0"/&gt;
         *                           &lt;/sequence&gt;
         *                           &lt;attribute name="valor" type="{}tipo_ImpPositivo" /&gt;
         *                         &lt;/restriction&gt;
         *                       &lt;/complexContent&gt;
         *                     &lt;/complexType&gt;
         *                   &lt;/element&gt;
         *                   &lt;element name="VTXDS" type="{}tipo_logico" minOccurs="0"/&gt;
         *                   &lt;element name="DT92DS" type="{}tipo_logico" minOccurs="0"/&gt;
         *                   &lt;element name="VTDT92DS" type="{}tipo_logico" minOccurs="0"/&gt;
         *                   &lt;element name="TIPODS" type="{}tipo_String1L" minOccurs="0"/&gt;
         *                   &lt;element name="FTDS" type="{}tipo_Fecha" minOccurs="0"/&gt;
         *                   &lt;element name="FADS" type="{}tipo_Fecha" minOccurs="0"/&gt;
         *                 &lt;/sequence&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *       &lt;/sequence&gt;
         *       &lt;attribute name="valor" type="{}tipo_ImpPositivo" /&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "entidadds",
            "derecho"
        })
        public static class G2CVT {

            @XmlElement(name = "ENTIDADDS", required = true)
            protected String entidadds;
            @XmlElement(name = "DERECHO")
            protected List<TipoGPDerechos.EntidadDerecho.G2CVT.DERECHO> derecho;
            @XmlAttribute(name = "valor")
            protected BigDecimal valor;

            /**
             * Gets the value of the entidadds property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getENTIDADDS() {
                return entidadds;
            }

            /**
             * Sets the value of the entidadds property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setENTIDADDS(String value) {
                this.entidadds = value;
            }

            /**
             * Gets the value of the derecho property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the derecho property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getDERECHO().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link TipoGPDerechos.EntidadDerecho.G2CVT.DERECHO }
             * 
             * 
             */
            public List<TipoGPDerechos.EntidadDerecho.G2CVT.DERECHO> getDERECHO() {
                if (derecho == null) {
                    derecho = new ArrayList<TipoGPDerechos.EntidadDerecho.G2CVT.DERECHO>();
                }
                return this.derecho;
            }

            /**
             * Gets the value of the valor property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getValor() {
                return valor;
            }

            /**
             * Sets the value of the valor property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setValor(BigDecimal value) {
                this.valor = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;sequence&gt;
             *         &lt;element name="ITDS" minOccurs="0"&gt;
             *           &lt;complexType&gt;
             *             &lt;complexContent&gt;
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *                 &lt;sequence&gt;
             *                   &lt;element name="IMP1ITDS" type="{}tipo_ImpPositivo" minOccurs="0"/&gt;
             *                   &lt;element name="IMP2ITDS" type="{}tipo_ImpPositivo" minOccurs="0"/&gt;
             *                 &lt;/sequence&gt;
             *                 &lt;attribute name="valor" type="{}tipo_ImpPositivo" /&gt;
             *               &lt;/restriction&gt;
             *             &lt;/complexContent&gt;
             *           &lt;/complexType&gt;
             *         &lt;/element&gt;
             *         &lt;element name="IADS" type="{}tipo_ImpPositivo" minOccurs="0"/&gt;
             *         &lt;element name="RETDS" type="{}tipo_ImpPositivo" minOccurs="0"/&gt;
             *         &lt;element name="RV2DS" minOccurs="0"&gt;
             *           &lt;complexType&gt;
             *             &lt;complexContent&gt;
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *                 &lt;sequence&gt;
             *                   &lt;element name="IMP1RV2DS" type="{}tipo_ImpPositivo" minOccurs="0"/&gt;
             *                   &lt;element name="IMP2RV2DS" type="{}tipo_ImpPositivo" minOccurs="0"/&gt;
             *                   &lt;element name="IMP3RV2DS" type="{}tipo_ImpPositivo" minOccurs="0"/&gt;
             *                 &lt;/sequence&gt;
             *                 &lt;attribute name="valor" type="{}tipo_ImpPositivo" /&gt;
             *               &lt;/restriction&gt;
             *             &lt;/complexContent&gt;
             *           &lt;/complexType&gt;
             *         &lt;/element&gt;
             *         &lt;element name="VTXDS" type="{}tipo_logico" minOccurs="0"/&gt;
             *         &lt;element name="DT92DS" type="{}tipo_logico" minOccurs="0"/&gt;
             *         &lt;element name="VTDT92DS" type="{}tipo_logico" minOccurs="0"/&gt;
             *         &lt;element name="TIPODS" type="{}tipo_String1L" minOccurs="0"/&gt;
             *         &lt;element name="FTDS" type="{}tipo_Fecha" minOccurs="0"/&gt;
             *         &lt;element name="FADS" type="{}tipo_Fecha" minOccurs="0"/&gt;
             *       &lt;/sequence&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "itds",
                "iads",
                "retds",
                "rv2DS",
                "vtxds",
                "dt92DS",
                "vtdt92DS",
                "tipods",
                "ftds",
                "fads"
            })
            public static class DERECHO {

                @XmlElement(name = "ITDS")
                protected TipoGPDerechos.EntidadDerecho.G2CVT.DERECHO.ITDS itds;
                @XmlElement(name = "IADS")
                protected BigDecimal iads;
                @XmlElement(name = "RETDS")
                protected BigDecimal retds;
                @XmlElement(name = "RV2DS")
                protected TipoGPDerechos.EntidadDerecho.G2CVT.DERECHO.RV2DS rv2DS;
                @XmlElement(name = "VTXDS")
                protected String vtxds;
                @XmlElement(name = "DT92DS")
                protected String dt92DS;
                @XmlElement(name = "VTDT92DS")
                protected String vtdt92DS;
                @XmlElement(name = "TIPODS")
                protected String tipods;
                @XmlElement(name = "FTDS")
                protected String ftds;
                @XmlElement(name = "FADS")
                protected String fads;

                /**
                 * Gets the value of the itds property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link TipoGPDerechos.EntidadDerecho.G2CVT.DERECHO.ITDS }
                 *     
                 */
                public TipoGPDerechos.EntidadDerecho.G2CVT.DERECHO.ITDS getITDS() {
                    return itds;
                }

                /**
                 * Sets the value of the itds property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link TipoGPDerechos.EntidadDerecho.G2CVT.DERECHO.ITDS }
                 *     
                 */
                public void setITDS(TipoGPDerechos.EntidadDerecho.G2CVT.DERECHO.ITDS value) {
                    this.itds = value;
                }

                /**
                 * Gets the value of the iads property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link BigDecimal }
                 *     
                 */
                public BigDecimal getIADS() {
                    return iads;
                }

                /**
                 * Sets the value of the iads property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link BigDecimal }
                 *     
                 */
                public void setIADS(BigDecimal value) {
                    this.iads = value;
                }

                /**
                 * Gets the value of the retds property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link BigDecimal }
                 *     
                 */
                public BigDecimal getRETDS() {
                    return retds;
                }

                /**
                 * Sets the value of the retds property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link BigDecimal }
                 *     
                 */
                public void setRETDS(BigDecimal value) {
                    this.retds = value;
                }

                /**
                 * Gets the value of the rv2DS property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link TipoGPDerechos.EntidadDerecho.G2CVT.DERECHO.RV2DS }
                 *     
                 */
                public TipoGPDerechos.EntidadDerecho.G2CVT.DERECHO.RV2DS getRV2DS() {
                    return rv2DS;
                }

                /**
                 * Sets the value of the rv2DS property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link TipoGPDerechos.EntidadDerecho.G2CVT.DERECHO.RV2DS }
                 *     
                 */
                public void setRV2DS(TipoGPDerechos.EntidadDerecho.G2CVT.DERECHO.RV2DS value) {
                    this.rv2DS = value;
                }

                /**
                 * Gets the value of the vtxds property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getVTXDS() {
                    return vtxds;
                }

                /**
                 * Sets the value of the vtxds property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setVTXDS(String value) {
                    this.vtxds = value;
                }

                /**
                 * Gets the value of the dt92DS property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getDT92DS() {
                    return dt92DS;
                }

                /**
                 * Sets the value of the dt92DS property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setDT92DS(String value) {
                    this.dt92DS = value;
                }

                /**
                 * Gets the value of the vtdt92DS property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getVTDT92DS() {
                    return vtdt92DS;
                }

                /**
                 * Sets the value of the vtdt92DS property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setVTDT92DS(String value) {
                    this.vtdt92DS = value;
                }

                /**
                 * Gets the value of the tipods property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getTIPODS() {
                    return tipods;
                }

                /**
                 * Sets the value of the tipods property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setTIPODS(String value) {
                    this.tipods = value;
                }

                /**
                 * Gets the value of the ftds property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getFTDS() {
                    return ftds;
                }

                /**
                 * Sets the value of the ftds property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setFTDS(String value) {
                    this.ftds = value;
                }

                /**
                 * Gets the value of the fads property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getFADS() {
                    return fads;
                }

                /**
                 * Sets the value of the fads property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setFADS(String value) {
                    this.fads = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType&gt;
                 *   &lt;complexContent&gt;
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
                 *       &lt;sequence&gt;
                 *         &lt;element name="IMP1ITDS" type="{}tipo_ImpPositivo" minOccurs="0"/&gt;
                 *         &lt;element name="IMP2ITDS" type="{}tipo_ImpPositivo" minOccurs="0"/&gt;
                 *       &lt;/sequence&gt;
                 *       &lt;attribute name="valor" type="{}tipo_ImpPositivo" /&gt;
                 *     &lt;/restriction&gt;
                 *   &lt;/complexContent&gt;
                 * &lt;/complexType&gt;
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "imp1ITDS",
                    "imp2ITDS"
                })
                public static class ITDS {

                    @XmlElement(name = "IMP1ITDS")
                    protected BigDecimal imp1ITDS;
                    @XmlElement(name = "IMP2ITDS")
                    protected BigDecimal imp2ITDS;
                    @XmlAttribute(name = "valor")
                    protected BigDecimal valor;

                    /**
                     * Gets the value of the imp1ITDS property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link BigDecimal }
                     *     
                     */
                    public BigDecimal getIMP1ITDS() {
                        return imp1ITDS;
                    }

                    /**
                     * Sets the value of the imp1ITDS property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link BigDecimal }
                     *     
                     */
                    public void setIMP1ITDS(BigDecimal value) {
                        this.imp1ITDS = value;
                    }

                    /**
                     * Gets the value of the imp2ITDS property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link BigDecimal }
                     *     
                     */
                    public BigDecimal getIMP2ITDS() {
                        return imp2ITDS;
                    }

                    /**
                     * Sets the value of the imp2ITDS property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link BigDecimal }
                     *     
                     */
                    public void setIMP2ITDS(BigDecimal value) {
                        this.imp2ITDS = value;
                    }

                    /**
                     * Gets the value of the valor property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link BigDecimal }
                     *     
                     */
                    public BigDecimal getValor() {
                        return valor;
                    }

                    /**
                     * Sets the value of the valor property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link BigDecimal }
                     *     
                     */
                    public void setValor(BigDecimal value) {
                        this.valor = value;
                    }

                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType&gt;
                 *   &lt;complexContent&gt;
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
                 *       &lt;sequence&gt;
                 *         &lt;element name="IMP1RV2DS" type="{}tipo_ImpPositivo" minOccurs="0"/&gt;
                 *         &lt;element name="IMP2RV2DS" type="{}tipo_ImpPositivo" minOccurs="0"/&gt;
                 *         &lt;element name="IMP3RV2DS" type="{}tipo_ImpPositivo" minOccurs="0"/&gt;
                 *       &lt;/sequence&gt;
                 *       &lt;attribute name="valor" type="{}tipo_ImpPositivo" /&gt;
                 *     &lt;/restriction&gt;
                 *   &lt;/complexContent&gt;
                 * &lt;/complexType&gt;
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "imp1RV2DS",
                    "imp2RV2DS",
                    "imp3RV2DS"
                })
                public static class RV2DS {

                    @XmlElement(name = "IMP1RV2DS")
                    protected BigDecimal imp1RV2DS;
                    @XmlElement(name = "IMP2RV2DS")
                    protected BigDecimal imp2RV2DS;
                    @XmlElement(name = "IMP3RV2DS")
                    protected BigDecimal imp3RV2DS;
                    @XmlAttribute(name = "valor")
                    protected BigDecimal valor;

                    /**
                     * Gets the value of the imp1RV2DS property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link BigDecimal }
                     *     
                     */
                    public BigDecimal getIMP1RV2DS() {
                        return imp1RV2DS;
                    }

                    /**
                     * Sets the value of the imp1RV2DS property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link BigDecimal }
                     *     
                     */
                    public void setIMP1RV2DS(BigDecimal value) {
                        this.imp1RV2DS = value;
                    }

                    /**
                     * Gets the value of the imp2RV2DS property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link BigDecimal }
                     *     
                     */
                    public BigDecimal getIMP2RV2DS() {
                        return imp2RV2DS;
                    }

                    /**
                     * Sets the value of the imp2RV2DS property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link BigDecimal }
                     *     
                     */
                    public void setIMP2RV2DS(BigDecimal value) {
                        this.imp2RV2DS = value;
                    }

                    /**
                     * Gets the value of the imp3RV2DS property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link BigDecimal }
                     *     
                     */
                    public BigDecimal getIMP3RV2DS() {
                        return imp3RV2DS;
                    }

                    /**
                     * Sets the value of the imp3RV2DS property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link BigDecimal }
                     *     
                     */
                    public void setIMP3RV2DS(BigDecimal value) {
                        this.imp3RV2DS = value;
                    }

                    /**
                     * Gets the value of the valor property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link BigDecimal }
                     *     
                     */
                    public BigDecimal getValor() {
                        return valor;
                    }

                    /**
                     * Sets the value of the valor property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link BigDecimal }
                     *     
                     */
                    public void setValor(BigDecimal value) {
                        this.valor = value;
                    }

                }

            }

        }

    }

}
