//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.01.31 at 09:35:14 AM UTC 
//


package net.aonsolutions.fiscal.mod100.e2023;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tipo_AdecuacionVHDiscapacitados complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tipo_AdecuacionVHDiscapacitados"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="IMPVHDIS" type="{}tipo_ImpPositivo" minOccurs="0"/&gt;
 *         &lt;element name="FECHA1VHDIS" type="{}tipo_Fecha" minOccurs="0"/&gt;
 *         &lt;element name="FECHA2VHDIS" type="{}tipo_Fecha" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tipo_AdecuacionVHDiscapacitados", propOrder = {
    "impvhdis",
    "fecha1VHDIS",
    "fecha2VHDIS"
})
public class TipoAdecuacionVHDiscapacitados {

    @XmlElement(name = "IMPVHDIS")
    protected BigDecimal impvhdis;
    @XmlElement(name = "FECHA1VHDIS")
    protected String fecha1VHDIS;
    @XmlElement(name = "FECHA2VHDIS")
    protected String fecha2VHDIS;

    /**
     * Gets the value of the impvhdis property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getIMPVHDIS() {
        return impvhdis;
    }

    /**
     * Sets the value of the impvhdis property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setIMPVHDIS(BigDecimal value) {
        this.impvhdis = value;
    }

    /**
     * Gets the value of the fecha1VHDIS property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFECHA1VHDIS() {
        return fecha1VHDIS;
    }

    /**
     * Sets the value of the fecha1VHDIS property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFECHA1VHDIS(String value) {
        this.fecha1VHDIS = value;
    }

    /**
     * Gets the value of the fecha2VHDIS property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFECHA2VHDIS() {
        return fecha2VHDIS;
    }

    /**
     * Sets the value of the fecha2VHDIS property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFECHA2VHDIS(String value) {
        this.fecha2VHDIS = value;
    }

}
