//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.01.31 at 09:35:14 AM UTC 
//


package net.aonsolutions.fiscal.mod100.e2023;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tipo_GPAccionesRes complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tipo_GPAccionesRes"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="G2B_RT0" type="{}tipo_ImpPositivo" minOccurs="0"/&gt;
 *         &lt;element name="G2B_RT1" type="{}tipo_ImpPositivo" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tipo_GPAccionesRes", propOrder = {
    "g2BRT0",
    "g2BRT1"
})
public class TipoGPAccionesRes {

    @XmlElement(name = "G2B_RT0")
    protected BigDecimal g2BRT0;
    @XmlElement(name = "G2B_RT1")
    protected BigDecimal g2BRT1;

    /**
     * Gets the value of the g2BRT0 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getG2BRT0() {
        return g2BRT0;
    }

    /**
     * Sets the value of the g2BRT0 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setG2BRT0(BigDecimal value) {
        this.g2BRT0 = value;
    }

    /**
     * Gets the value of the g2BRT1 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getG2BRT1() {
        return g2BRT1;
    }

    /**
     * Sets the value of the g2BRT1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setG2BRT1(BigDecimal value) {
        this.g2BRT1 = value;
    }

}
