<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://www.inteco.es/xbrl/pgc07/validator" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:impl="http://www.inteco.es/xbrl/pgc07/validator" xmlns:intf="http://www.inteco.es/xbrl/pgc07/validator" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<!--WSDL created by Apache Axis version: 1.4
Built on Apr 22, 2006 (06:55:48 PDT)-->
 <wsdl:types>
  <schema elementFormDefault="qualified" targetNamespace="http://www.inteco.es/xbrl/pgc07/validator" xmlns="http://www.w3.org/2001/XMLSchema">
   <element name="validate">
    <complexType>
     <sequence>
      <element name="inputDocument" type="xsd:base64Binary"/>
     </sequence>
    </complexType>
   </element>
   <element name="validateResponse">
    <complexType>
     <sequence>
      <element name="validateReturn" type="impl:ValidateResult"/>
     </sequence>
    </complexType>
   </element>
   <complexType name="ValidateResult">
    <sequence>
     <element name="errors" nillable="true" type="xsd:string"/>
     <element name="generalError" nillable="true" type="xsd:string"/>
     <element name="valid" type="xsd:boolean"/>
    </sequence>
   </complexType>
  </schema>
 </wsdl:types>

   <wsdl:message name="validateResponse">

      <wsdl:part element="impl:validateResponse" name="parameters"/>

   </wsdl:message>

   <wsdl:message name="validateRequest">

      <wsdl:part element="impl:validate" name="parameters"/>

   </wsdl:message>

   <wsdl:portType name="XSDWSValidator">

      <wsdl:operation name="validate">

         <wsdl:input message="impl:validateRequest" name="validateRequest"/>

         <wsdl:output message="impl:validateResponse" name="validateResponse"/>

      </wsdl:operation>

   </wsdl:portType>

   <wsdl:binding name="XSDWSValidatorSoapBinding" type="impl:XSDWSValidator">

      <wsdlsoap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>

      <wsdl:operation name="validate">

         <wsdlsoap:operation soapAction=""/>

         <wsdl:input name="validateRequest">

            <wsdlsoap:body use="literal"/>

         </wsdl:input>

         <wsdl:output name="validateResponse">

            <wsdlsoap:body use="literal"/>

         </wsdl:output>

      </wsdl:operation>

   </wsdl:binding>

   <wsdl:service name="XSDWSValidatorService">

      <wsdl:port binding="impl:XSDWSValidatorSoapBinding" name="XSDWSValidator">

         <wsdlsoap:address location="http://localhost:8080/PGCWSProject/services/XSDWSValidator"/>

      </wsdl:port>

   </wsdl:service>

</wsdl:definitions>
