PGCWSTransformatorServiceLocator.address=http://localhost:8080/PGCWSProject/services/PGCWSTransformator
XBRLWSValidatorServiceLocator.address=http://localhost:8080/PGCWSProject/services/XBRLWSValidator
XSDWSValidatorServiceLocator.address=http://localhost:8080/PGCWSProject/services/XSDWSValidator
PGCWSViewerServiceLocator.address=http://localhost:8080/PGCWSProject/services/PGCWSViewer
