<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>com.code.aon</groupId>
		<artifactId>aon.parent</artifactId>
		<version>8.94.2</version>
	</parent>
	<artifactId>aon.pool</artifactId>
	<name>AON SQL CONNECTION POOL</name>
	<description>AON SQL CONNECTION POOL</description>
	<dependencies>
		<dependency>
			<groupId>com.mchange</groupId>
			<artifactId>c3p0</artifactId>
			<version>0.9.2</version>
			<scope>compile</scope>
		</dependency>
	</dependencies>
</project>
