<?xml version="1.0"?>
<!-- Propuesta de Esquema de datos para el modelo 420 -->

<xs:schema id="Modelo417DataSetCOL" xmlns=""
	xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:jaxb="http://java.sun.com/xml/ns/jaxb"
	jaxb:version="2.0">


	<xs:element name="COL_DEC">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="PRE" type="xs:string" maxOccurs="unbounded" minOccurs="1" >
					<xs:annotation>
						<xs:documentation>
							Espacio que contendrá la estructura/XML de una declaración individual
							del modelo, dentro de su elemento "DEC".
							Se generarán tantos elementos "PRE" como declaraciónes individuales
							se incluyan en la declaración colectiva.
						</xs:documentation>
					</xs:annotation>
				
				</xs:element>
			</xs:sequence>

			<xs:attribute name="MOD" type="xs:string">
				<xs:annotation>
					<xs:documentation>
						Atributo cumplimentado por el programa.
						Identificador del modelo.
					</xs:documentation>
				</xs:annotation>
			</xs:attribute>

			<xs:attribute name="ANY">
				<xs:annotation>
					<xs:documentation>
						Atributo cumplimentado por el programa.
						Ejercicio al que se refiere la autoliquidación.
						Formato String(4).
					</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:length value="4"></xs:length>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>

			<xs:attribute name="VER" type="xs:string">
				<xs:annotation>
					<xs:documentation>
						Atributo cumplimentado por el programa.
						Versión del programa de ayuda con la que se generó el XML.
					</xs:documentation>
				</xs:annotation>
			</xs:attribute>

			<xs:attribute name="NUM" type="xs:string">
				<xs:annotation>
					<xs:documentation>
						Atributo cumplimentado por el programa.
						Número de declaraciones que contiene la colectiva.
					</xs:documentation>
				</xs:annotation>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
</xs:schema>