<?xml version="1.0"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<parent>
		<groupId>com.code.aon</groupId>
		<artifactId>aon.parent</artifactId>
		<version>9.19-SNAPSHOT</version>
	</parent>
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.esferalia.aon</groupId>
	<artifactId>aon.dex.api</artifactId>
	<version>9.19-SNAPSHOT</version>
	<name>AON DEX API</name>
	<build>
		<plugins>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>build-helper-maven-plugin</artifactId>
				<version>1.7</version>
				<executions>
					<execution>
						<id>add-source</id>
						<phase>process-sources</phase>
						<goals>
							<goal>add-source</goal>
						</goals>
						<configuration>
							<sources>
								<source>
									${project.build.directory}/generated-sources
								</source>
							</sources>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>jaxws-maven-plugin</artifactId>
				<version>1.2</version>
				<executions>
					<execution>
						<id>facturas-exec</id>
						<goals>
							<goal>wsimport</goal>
						</goals>
						<configuration>
 							<wsdlDirectory>src/main/wsdl</wsdlDirectory>
							<wsdlFiles>
         						<wsdlFile>Facturas.wsdl</wsdlFile>
							</wsdlFiles>
							<sourceDestDir>${project.build.directory}/generated-sources</sourceDestDir>
							<packageName>com.esferalia.aon.dex.nav.facturas</packageName>
							<staleFile>${project.build.directory}/generated-sources/staleFlag/jaxws/.facturasStaleFlag</staleFile>
						</configuration>
					</execution>
					<execution>
						<id>remesas-exec</id>
						<goals>
							<goal>wsimport</goal>
						</goals>
						<configuration>
 							<wsdlDirectory>src/main/wsdl</wsdlDirectory>
							<wsdlFiles>
         						<wsdlFile>Remesas.wsdl</wsdlFile>
							</wsdlFiles>
							<sourceDestDir>${project.build.directory}/generated-sources</sourceDestDir>
							<packageName>com.esferalia.aon.dex.nav.remesas</packageName>
							<staleFile>${project.build.directory}/generated-sources/staleFlag/jaxws/.remesasStaleFlag</staleFile>
						</configuration>
					</execution>
					<execution>
						<id>produccion-exec</id>
						<goals>
							<goal>wsimport</goal>
						</goals>
						<configuration>
 							<wsdlDirectory>src/main/wsdl</wsdlDirectory>
							<wsdlFiles>
         						<wsdlFile>Produccion.wsdl</wsdlFile>
							</wsdlFiles>
							<sourceDestDir>${project.build.directory}/generated-sources</sourceDestDir>
							<packageName>com.esferalia.aon.dex.nav.produccion</packageName>
							<staleFile>${project.build.directory}/generated-sources/staleFlag/jaxws/.produccionStaleFlag</staleFile>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build> 
	<dependencies>
		<dependency>
			<groupId>org.apache.xmlbeans</groupId>
			<artifactId>xmlbeans</artifactId>
			<version>2.4.0</version>
			<scope>compile</scope>
		</dependency>
	</dependencies>
</project>
 
