<?xml version="1.0"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<parent>
		<groupId>com.code.aon</groupId>
		<artifactId>aon.parent</artifactId>
		<version>8.4-SNAPSHOT</version>
	</parent>
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.esferalia.aon</groupId>
	<artifactId>aon.gwt.document</artifactId>
	<packaging>jar</packaging>
	<version>8.4-SNAPSHOT</version>
	<description>AON GWT DOCUMENT</description>
	<name>AON GWT DOCUMENT</name>
	<build>
		<plugins>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>gwt-maven-plugin</artifactId>
				<version>2.6.0</version>
				<configuration>
					<webappDirectory>${project.build.outputDirectory}</webappDirectory>
				</configuration>
				<executions>
					<execution>
						<phase>prepare-package</phase>
						<goals>
							<goal>compile</goal>
							<!--goal>generateAsync</goal -->
							<!--goal>test</goal -->
						</goals>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>


	<dependencies>
		
	    <dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.google.apis</artifactId>
			<version>${project.version}</version>
			<scope>compile</scope>
		</dependency>
	    
		<dependency>
			<groupId>com.google.gwt</groupId>
			<artifactId>gwt-servlet</artifactId>
			<version>2.6.1</version>
			<scope>compile</scope>
		</dependency>

		<dependency>
			<groupId>com.google.gwt</groupId>
			<artifactId>gwt-user</artifactId>
			<version>2.6.1</version>
			<scope>provided</scope>
		</dependency>

		<dependency>
			<groupId>com.esferalia.aon</groupId>
			<artifactId>aon.gwt.common</artifactId>
			<version>${project.version}</version>
		</dependency>
	</dependencies>
	<profiles>
		<profile>
			<id>perform-stats</id>
		</profile>
	</profiles>
</project>
