<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://viewer.pgc.xbrl.inteco.es" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:impl="http://viewer.pgc.xbrl.inteco.es" xmlns:intf="http://viewer.pgc.xbrl.inteco.es" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<!--WSDL created by Apache Axis version: 1.4
Built on Apr 22, 2006 (06:55:48 PDT)-->
 <wsdl:types>
  <schema elementFormDefault="qualified" targetNamespace="http://viewer.pgc.xbrl.inteco.es" xmlns="http://www.w3.org/2001/XMLSchema">
   <element name="view">
    <complexType>
     <sequence>
      <element name="inputDocument" type="xsd:base64Binary"/>
      <element name="module" type="xsd:string"/>
     </sequence>
    </complexType>
   </element>
   <element name="viewResponse">
    <complexType>
     <sequence>
      <element name="viewReturn" type="impl:ViewerResult"/>
     </sequence>
    </complexType>
   </element>
   <complexType name="ViewerResult">
    <sequence>
     <element name="arrayResult" nillable="true" type="xsd:base64Binary"/>
     <element name="generalError" nillable="true" type="xsd:string"/>
    </sequence>
   </complexType>
   <element name="viewXML">
    <complexType>
     <sequence>
      <element name="inputDocument" type="xsd:base64Binary"/>
      <element name="module" type="xsd:string"/>
     </sequence>
    </complexType>
   </element>
   <element name="viewXMLResponse">
    <complexType>
     <sequence>
      <element name="viewXMLReturn" type="impl:ViewerResult"/>
     </sequence>
    </complexType>
   </element>
  </schema>
 </wsdl:types>

   <wsdl:message name="viewXMLResponse">

      <wsdl:part element="impl:viewXMLResponse" name="parameters"/>

   </wsdl:message>

   <wsdl:message name="viewResponse">

      <wsdl:part element="impl:viewResponse" name="parameters"/>

   </wsdl:message>

   <wsdl:message name="viewRequest">

      <wsdl:part element="impl:view" name="parameters"/>

   </wsdl:message>

   <wsdl:message name="viewXMLRequest">

      <wsdl:part element="impl:viewXML" name="parameters"/>

   </wsdl:message>

   <wsdl:portType name="PGCWSViewer">

      <wsdl:operation name="view">

         <wsdl:input message="impl:viewRequest" name="viewRequest"/>

         <wsdl:output message="impl:viewResponse" name="viewResponse"/>

      </wsdl:operation>

      <wsdl:operation name="viewXML">

         <wsdl:input message="impl:viewXMLRequest" name="viewXMLRequest"/>

         <wsdl:output message="impl:viewXMLResponse" name="viewXMLResponse"/>

      </wsdl:operation>

   </wsdl:portType>

   <wsdl:binding name="PGCWSViewerSoapBinding" type="impl:PGCWSViewer">

      <wsdlsoap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>

      <wsdl:operation name="view">

         <wsdlsoap:operation soapAction=""/>

         <wsdl:input name="viewRequest">

            <wsdlsoap:body use="literal"/>

         </wsdl:input>

         <wsdl:output name="viewResponse">

            <wsdlsoap:body use="literal"/>

         </wsdl:output>

      </wsdl:operation>

      <wsdl:operation name="viewXML">

         <wsdlsoap:operation soapAction=""/>

         <wsdl:input name="viewXMLRequest">

            <wsdlsoap:body use="literal"/>

         </wsdl:input>

         <wsdl:output name="viewXMLResponse">

            <wsdlsoap:body use="literal"/>

         </wsdl:output>

      </wsdl:operation>

   </wsdl:binding>

   <wsdl:service name="PGCWSViewerService">

      <wsdl:port binding="impl:PGCWSViewerSoapBinding" name="PGCWSViewer">

         <wsdlsoap:address location="http://localhost:8080/PGCWSProject/services/PGCWSViewer"/>

      </wsdl:port>

   </wsdl:service>

</wsdl:definitions>
