apiVersion: batch/v1
kind: Job
metadata:
  labels:
    run: aon-db-up2date # Label for the Job
  name: aon-db-up2date # Name of Job
spec: # Job's specification
  backoffLimit: 1
  activeDeadlineSeconds: 300
  template:
    spec: 
      containers:
      - env:
        - name: DB_HOST # Define the environment variable
          valueFrom:
            configMapKeyRef:
              key: DB_HOST
              name: aon-aio-config
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              key: DB_USER
              name: aon-aio-config
        - name: DB_PASSWD
          valueFrom:
            configMapKeyRef:
              key: DB_PASSWD
              name: aon-aio-config
        image: eu.gcr.io/aon-application/aon-db-up2date:9.23.7 # Application to run in Deployment's Pods
        name: aon-db-up2date
      restartPolicy: Never

