version: 0.2

#env:
  #variables:
     # key: "value"
     # key: "value"
  #parameter-store:
     # key: "value"
     # key: "value"

phases:
  install:
    commands:
      - apt-get update
      - echo Install MariaDB on `date`
      - echo 'mariadb-server mysql-server/root_password password pass' | debconf-set-selections
      - echo 'mariadb-server mysql-server/root_password_again password pass' | debconf-set-selections
      - DEBIAN_FRONTEND=noninteractive apt-get install -y mariadb-client mariadb-server
      - sed -i -r -e 's/bind-address.*$/bind-address = 0.0.0.0/' $(grep -l -R bind-address /etc/mysql/*)
      - service mysql start
      - echo MariaDB started on `date`
      - echo "GRANT ALL ON *.* TO 'dbuser'@'%' IDENTIFIED BY 'serubd2000'" | mysql -u root --password=pass
  pre_build:
    commands:
      - export LC_ALL="en_US.UTF-8"
      - locale-gen en_US en_US.UTF-8
      - dpkg-reconfigure locales
      # - echo Logging in to Amazon ECR...
      # - aws --version
      # - $(aws ecr get-login --region ${AWS_DEFAULT_REGION:=eu-west-1} --no-include-email)
      # - IMAGE_TAG=$(date +%Y.%m.%d-%H.%M.%S)
  build:
    commands:
      - echo Build started on `date`
      - mvn --fail-at-end  -T 1C -DbuildNumber=666 -Drpm.release=false -Dgwt.working=true -DSNAPSHOT -am -pl aon-rest-api install
      - echo Build completed on `date`
  post_build:
    commands:

artifacts:
  files:
    - aon-rest-api/target/aon-rest-api-9.23-SNAPSHOT.jar
    # - location
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - paths
