<?xml version="1.0" encoding="utf-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

  <modelVersion>4.0.0</modelVersion>
  <groupId>com.code.aon</groupId>
  <artifactId>aon.solutions</artifactId>
  <version>5.0.0</version>
  <packaging>pom</packaging>
  <description>POM de aon Solutions (para sacar versions...)</description>
  <name>aon Solutions</name>

  <properties>
    <aon-version>5.0.0-SNAPSHOT</aon-version>
  </properties>

  <organization>
    <name>esferalia Networks S.A.</name>
    <url>http://www.esferalia.com</url>
  </organization>

  <scm>
    <connection>
    scm:svn:http://dev.esferalia.com/repos/aon-application/trunk</connection>
    <url>http://dev.esferalia.com/websvn/wsvn</url>
  </scm>

  <modules>
	<module>aon-parent</module>
	<module>aon-ql</module>
	<module>aon-common</module>
	<!--module>aon-account-bridge</module>
	<module>aon-accounting</module>
	<module>aon-account</module>
	<module>aon-asset</module>
	<module>aon-audit</module>
	<module>aon-campaign</module>
	<module>aon-cms</module>
	<module>aon-commercial</module>
	<module>aon-common-ldap</module>
	<module>aon-company</module>
	<module>aon-config</module>
	<module>aon-core</module>
	<module>aon-csb</module>
	<module>aon-customer</module>
	<module>aon-db-manager</module>
	<module>aon-desktop</module>
	<module>aon-ebackoffice</module>
	<module>aon-facturae</module>
	<module>aon-file-bank</module>
	<module>aon-file-format</module>
	<module>aon-file-tax</module>
	<module>aon-finance-bridge</module>
	<module>aon-finance</module>
	<module>aon-geozone</module>
	<module>aon-groupware</module>
	<module>aon-infoweb</module>
	<module>aon-ldap</module>
	<module>aon-marketing</module>
	<module>aon-messaging</module>
	<module>aon-payroll-core</module>
	<module>aon-payroll-nominasta</module>
	<module>aon-product</module>
	<module>aon-project</module>
	<module>aon-purchase-bridge</module>
	<module>aon-purchase</module>
	<module>aon-registry</module>
	<module>aon-report</module>
	<module>aon-rich-components</module>
	<module>aon-sales-bridge</module>
	<module>aon-sales</module>
	<module>aon-security-bridge</module>
	<module>aon-seller</module>
	<module>aon-stat</module>
	<module>aon-supplier</module>
	<module>aon-ui-account-bridge</module>
	<module>aon-ui-accounting</module>
	<module>aon-ui-account</module>
	<module>aon-ui-asset</module>
	<module>aon-ui-audit</module>
	<module>aon-ui-campaign</module>
	<module>aon-ui-commercial</module>
	<module>aon-ui-common</module>
	<module>aon-ui-company</module>
	<module>aon-ui-config</module>
	<module>aon-ui-customer</module>
	<module>aon-ui-db-manager</module>
	<module>aon-ui-ebackoffice</module>
	<module>aon-ui-ecommerce</module>
	<module>aon-ui-finance</module>
	<module>aon-ui-form</module>
	<module>aon-ui-geozone</module>
	<module>aon-ui-groupware</module>
	<module>aon-ui-infoweb</module>
	<module>aon-ui-mailing</module>
	<module>aon-ui-marketing</module>
	<module>aon-ui-messaging</module>
	<module>aon-ui-product</module>
	<module>aon-ui-project</module>
	<module>aon-ui-purchase</module>
	<module>aon-ui-registry</module>
	<module>aon-ui-report</module>
	<module>aon-ui-resources</module>
	<module>aon-ui-sales</module>
	<module>aon-ui-sign</module>
	<module>aon-ui-stat</module>
	<module>aon-ui-supplier</module>
	<module>aon-ui-warehouse</module>
	<module>aon-ui-webmail</module>
	<module>aon-warehouse-bridge</module>
	<module>aon-warehouse</module>
	<module>aon-web-parent</module>
	<module>aon-web-account</module>
	<module>aon-web-asset</module>
	<module>aon-web-cms</module>
	<module>aon-web-commercial</module>
	<module>aon-web-communicator</module>
	<module>aon-web-consultant</module>
	<module>aon-web-ebackoffice</module>
	<module>aon-web-ecommerce</module>
	<module>aon-web-enterprise</module>
	<module>aon-web-finance</module>
	<module>aon-web-infoweb</module>
	<module>aon-webmail</module>
	<module>aon-web-smb</module>
	<module>aon-web-task</module>
	<module>aon-web-webmail</module-->
  </modules>

  <build>
    <plugins>
	<plugin>
        	<groupId>org.apache.maven.plugins</groupId>
	        <artifactId>maven-release-plugin</artifactId>
        	<version>2.0</version>
	        <configuration>
			<releaseVersion>5.0.0</releaseVersion>
			<developmentVersion>5.0.1-SNAPSHOT</developmentVersion>
			<autoVersionSubmodules>true</autoVersionSubmodules>

			<tag>5.0.0</tag>
        	  	<tagBase>https://dev.esferalia.com/repos/aon-application/releases</tagBase>
	        </configuration>
	</plugin>
    </plugins>
  </build>

</project>
