<?xml version="1.0"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

	<modelVersion>4.0.0</modelVersion>
	<groupId>com.code.aon</groupId>
	<artifactId>aon.parent</artifactId>
	<version>6.75.1</version>
	<packaging>pom</packaging>
	<description>POM padre de los proyectos AON</description>
	<name>AON PARENT</name>

	<properties>
		<project.build.sourceEncoding>ISO-8859-1</project.build.sourceEncoding>
		<jasperReportsArtifact>jasperreports-javaflow</jasperReportsArtifact>
		<jasperReportsVersion>4.5.1</jasperReportsVersion>
		<jasperreportsMavenPluginVersion>1.0-beta-3</jasperreportsMavenPluginVersion>
		<jasperreportsMavenPluginCompiler>net.sf.jasperreports.engine.design.JRJavacCompiler</jasperreportsMavenPluginCompiler>
	</properties>

	<modules>
		<!-- PARENT MODULES -->
		<module>aon-web-parent</module>

		<!-- LIB MODULES -->
		<module>aon-external-libs</module>
	
		<!-- MAVEN PLUGINS -->
		<module>aon-alias-maven-plugin</module>
		<module>aon-maven-plugin</module>
		<module>aon.mock.entity.maven.plugin</module>
		<module>aon.test.entity.maven.plugin</module>

		<!-- DB MODULES -->
		<module>aon-master</module>
		<module>aon.entity.common</module>
		<module>aon.entity</module>
		<module>aon.entity.alias</module>
		<module>aon-db-manager</module>
		<module>aon-dbutils</module>
		<module>aon-ui-dbutils</module>
		<module>aon-ui-db-manager</module>
		<module>aon-sql-payroll</module>
		
		<!-- FRAMEWORK -->
		<module>aon-audit</module>
		<module>aon-ui-audit</module>
		<module>aon-jaas</module>
		<module>aon-common</module>
		<module>aon-common-ldap</module>
		<module>aon-report</module>
		<module>aon-ldap</module>
		<module>aon-ql</module>
		<module>aon-rich-components</module>
		<module>aon-security-bridge</module>
		<module>aon-ui-common</module>
		<module>aon-ui-form</module>
		<module>aon-ui-report</module>
		<module>aon-ui-resources</module>
		<module>aon-webmail</module>
		<module>aon-ui-webmail</module>
		<module>aon-jsf-bridge</module>
		<module>aon-manager</module>
		<module>aon-ui-manager</module>
		<module>aon-admin</module>
		<module>aon-ui-admin</module>

		<!-- ENTITY -->
		<module>aon-company</module>
		<module>aon-config</module>
		<module>aon-customer</module>
		<module>aon-geozone</module>
		<module>aon-groupware</module>
		<module>aon-messaging</module>
		<module>aon-project</module>
		<module>aon-registry</module>
		<module>aon-calendar</module>
		<module>aon-payroll</module>
		<module>aon-salary</module>
		<module>aon-account-bridge</module>
		<module>aon-accounting</module>
		<module>aon-commercial</module>
		<module>aon-finance</module>
		<module>aon-finance-bridge</module>
		<module>aon-fiscal</module>
		<module>aon-product</module>
		<module>aon-purchase</module>
		<module>aon-sales</module>
		<module>aon-sales-bridge</module>
		<module>aon-seller</module>
		<module>aon-supplier</module>
		<module>aon-warehouse</module>
		<module>aon-warehouse-bridge</module>
		<module>aon-asset</module>
		<module>aon-infoweb</module>
		<module>aon-infoweb-templates</module>
		<module>aon-marketing</module>
		<module>aon-purchase-bridge</module>
		<module>aon-tas</module>
		<module>aon.test.entity</module>
		<module>aon-pms</module>
		<module>aon-academy</module>    

		<!-- UI MODULES -->
    <module>aon-ui-academy</module>
		<module>aon-ui-audabridge</module>
		<module>aon-ui-company</module>
		<module>aon-ui-config</module>
		<module>aon-ui-customer</module>
		<module>aon-ui-geozone</module>
		<module>aon-ui-groupware</module>
		<module>aon-ui-messaging</module>
		<module>aon-ui-registry</module>
		<module>aon-ui-calendar</module>
		<module>aon-ui-payroll</module>
		<module>aon-ui-account</module>
		<module>aon-ui-account-bridge</module>
		<module>aon-ui-accounting</module>
		<module>aon-ui-commercial</module>
		<module>aon-ui-finance</module>
		<module>aon-ui-fiscal</module>
		<module>aon-ui-product</module>
		<module>aon-ui-sales</module>
		<module>aon-ui-seller</module>
		<module>aon-ui-sign</module>
		<module>aon-ui-stat</module>
		<module>aon-ui-supplier</module>
		<module>aon-ui-asset</module>
		<module>aon-ui-infoweb</module>
		<module>aon-ui-mailing</module>
		<module>aon-ui-marketing</module>
		<module>aon-ui-project</module>
		<module>aon-ui-publisher</module>
		<module>aon-ui-purchase</module>
		<module>aon-ui-warehouse</module>
		<module>aon-ui-tas</module>
		<module>aon-ui-document</module>
		<module>aon-ui-pms</module>

		<!-- GWT MODULES -->
		<module>aon-gwt-payroll</module>

		<!-- GENERATED -->
		<module>aon-audabridge-api</module>
	  	<module>aon-pms-api</module>

		<!-- UTILITY -->
		<module>aon-file-format</module>
		<module>aon-file-bank</module>
		<module>aon-file-tax</module>
		<module>aon-file-payroll</module>
		<module>aon-facturae</module>
		<module>aon-stat</module>

		<!-- WEB MODULES -->
		<module>aon-desktop</module>
		<module>aon-web-payroll</module>
		<module>aon-web-smb</module>
		<module>aon-web-account</module>
		<module>aon-web-asset</module>
		<module>aon-web-commercial</module>
		<module>aon-web-communicator</module>
		<module>aon-web-consultant</module>
		<module>aon-web-project</module>
		<module>aon-web-enterprise</module>
		<module>aon-web-finance</module>
		<module>aon-web-fiscal</module>
		<module>aon-web-gta</module>
		<module>aon-web-infoweb</module>
		<module>aon-web-manager</module>
		<module>aon-web-publisher</module>
		<module>aon-web-webmail</module>
		<module>aon-web-document</module>
		<module>aon-web-pms</module>
		<module>aon-web-aio</module>

		<!-- GWT MODULES -->
		<module>aon-gwt-employee</module>

		<!-- WS MODULES -->
		<module>aon-ws-gps</module>

		<!-- OTHER -->
		<module>aon-payroll-ctsql2mysql</module>
		<module>aon-common-resources</module>
		<module>tgc-ui-payroll</module>

<!--
		*************************************************************************************************************
		MODULOS DESACTIVADOS TEMPORALMENTE, POR ESTAR INCLUIDOS DENTRO DE OTROS O PARA ACELERAR LA COMPILACION (CSM).
		*************************************************************************************************************
		<module>aon-cms</module>
		<module>aon-ui-cms</module>
		<module>aon-web-cms</module>
		
		******************
		MODULOS DEPRECADOS 
		******************

		<module>aon-ebackoffice</module>
		<module>aon-ui-ebackoffice</module>
		<module>aon-ui-ecommerce</module>
		<module>aon-web-ebackoffice</module>
		<module>aon-web-ecommerce</module>
-->
<!-- 
		<module>aon.python</module>
 -->
	</modules>

	<scm>
		<connection>scm:svn:http://dev.esferalia.com/repos/aon-application/releases/6.75.x</connection>
		<url>scm:svn:http://dev.esferalia.com/repos/aon-application/releases/6.75.x</url>
	</scm>

	<organization>
		<name>esferalia Networks S.A.</name>
		<url>http://www.esferalia.com</url>
	</organization>

	<developers>
		<developer>
			<id>ecastellano</id>
		</developer>
		<developer>
			<id>girazu</id>
		</developer>
		<developer>
			<id>atellitu</id>
		</developer>
		<developer>
			<id>rtrepiana</id>
		</developer>
		<developer>
			<id>eagirrezabal</id>
		</developer>
		<developer>
			<id>vsantamaria</id>
		</developer>
	</developers>
	<issueManagement>
		<system>Bugzilla</system>
		<url>http://bugzilla.esferalia.com/</url>
	</issueManagement>

	<repositories>
		<repository>
			<id>inhouse</id>
			<name>Inhouse Repository</name>
			<url>http://dev.esferalia.com/maven2_repositories/inhouse</url>
			<releases>
				<enabled>true</enabled>
				<updatePolicy>never</updatePolicy>
			</releases>
			<snapshots>
				<enabled>false</enabled>
				<updatePolicy>never</updatePolicy>
			</snapshots>
		</repository>

		<repository>
			<id>inhouse_snaphot</id>
			<name>Inhouse Snapshot Repository</name>
			<url>http://dev.esferalia.com/maven2_repositories/inhouse_snapshot</url>
			<releases>
				<enabled>false</enabled>
				<updatePolicy>never</updatePolicy>
			</releases>
			<snapshots>
				<enabled>true</enabled>
				<updatePolicy>always</updatePolicy>
			</snapshots>
		</repository>

		<repository>
			<id>external_free</id>
			<name>External Free Repository</name>
			<url>http://dev.esferalia.com/maven2_repositories/external_free</url>
			<releases>
				<enabled>true</enabled>
				<updatePolicy>never</updatePolicy>
			</releases>
			<snapshots>
				<enabled>false</enabled>
				<updatePolicy>never</updatePolicy>
			</snapshots>
		</repository>

		<repository>
			<id>jboss-thirdparty-releases</id>
			<name>JBoss Thirdparty Releases</name>
			<url>https://repository.jboss.org/nexus/content/repositories/thirdparty-releases</url>
			<releases>
				<enabled>true</enabled>
				<updatePolicy>never</updatePolicy>
			</releases>
			<snapshots>
				<enabled>false</enabled>
				<updatePolicy>never</updatePolicy>
			</snapshots>
		</repository>

		<repository>
			<id>jboss-public-repository-group</id>
			<name>JBoss Public Maven Repository Group</name>
			<url>https://repository.jboss.org/nexus/content/groups/public-jboss/</url>
			<layout>default</layout>
			<releases>
				<enabled>true</enabled>
				<updatePolicy>never</updatePolicy>
			</releases>
			<snapshots>
				<enabled>false</enabled>
				<updatePolicy>never</updatePolicy>
			</snapshots>
		</repository>

		<repository>
                    <id>maven2-repository.dev.java.net</id>
                    <name>Java.net Repository for Maven 2</name>
                    <url>http://download.java.net/maven/2</url>
                    <releases>
                        <enabled>true</enabled>
			<updatePolicy>never</updatePolicy>
                    </releases>
                    <snapshots>
                        <enabled>false</enabled>
			<updatePolicy>never</updatePolicy>
                    </snapshots>
                </repository>

		<repository>
			<id>jasperForge</id>
			<name>Jasper Forge Repository</name>
			<layout>default</layout>
			<url>http://jasperreports.sourceforge.net/maven2</url>
			<releases>
				<enabled>true</enabled>
				<updatePolicy>never</updatePolicy>
			</releases>
			<snapshots>
				<enabled>false</enabled>
				<updatePolicy>true</updatePolicy>
			</snapshots>
		</repository>

		<repository>
			<id>dynamicJasper-public-repository</id>
			<name>DynamicJasper public Repository</name>
			<url>http://archiva.fdvs.com.ar/repository/public1/</url>
			<releases>
				<enabled>true</enabled>
				<updatePolicy>never</updatePolicy>
			</releases>
			<snapshots>
				<enabled>false</enabled>
				<updatePolicy>never</updatePolicy>
			</snapshots>
		</repository>
	</repositories>

	<pluginRepositories>
	
		<pluginRepository>
			<id>aon</id>
			<url>http://dev.esferalia.com/maven2_repositories/inhouse</url>
                        <snapshots>
                                <enabled>false</enabled>
                        </snapshots>
                        <releases>
                                <enabled>true</enabled>
                        </releases>
		</pluginRepository>
		
		<pluginRepository>
			<id>aon.snapshots</id>
			<url>http://dev.esferalia.com/maven2_repositories/inhouse_snapshot</url>
                        <snapshots>
                                <enabled>true</enabled>
                        </snapshots>
                        <releases>
                                <enabled>false</enabled>
                        </releases>
		</pluginRepository>

		<pluginRepository>
			<id>aon.external.free</id>
			<url>http://dev.esferalia.com/maven2_repositories/external_free</url>
                        <snapshots>
                                <enabled>false</enabled>
                        </snapshots>
                        <releases>
                                <enabled>true</enabled>
                        </releases>
		</pluginRepository>

		<pluginRepository>
			<id>maven2-repository.dev.java.net</id>
			<url>http://download.java.net/maven/2/</url>
                        <snapshots>
                                <enabled>false</enabled>
                        </snapshots>
                        <releases>
                                <enabled>true</enabled>
                        </releases>
		</pluginRepository>
		
                <pluginRepository>
                        <id>Codehaus Public</id>
                        <url>https://nexus.codehaus.org/content/groups/public/</url>
                        <snapshots>
                                <enabled>true</enabled>
                        </snapshots>
                        <releases>
                                <enabled>true</enabled>
                        </releases>
                </pluginRepository>
        </pluginRepositories>

	<build>
		<plugins>

			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>2.3.2</version>
				<configuration>
					<source>1.6</source>
					<target>1.6</target>
					<encoding>ISO-8859-1</encoding>
				</configuration>
			</plugin>

			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
          		<artifactId>maven-surefire-plugin</artifactId>
          		<version>2.10</version>
				<configuration>
					<workingDirectory>target</workingDirectory>
				</configuration>
			</plugin>

			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-jar-plugin</artifactId>
				<version>2.3.2</version>
				<configuration>
					<archive>
						<manifest>
							<addDefaultSpecificationEntries>
								true</addDefaultSpecificationEntries>
							<addDefaultImplementationEntries>
								true</addDefaultImplementationEntries>
						</manifest>
					</archive>
				</configuration>
			</plugin>

			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-source-plugin</artifactId>
				<version>2.1.2</version>
				<executions>
					<!-- here we override the super-pom attach-sources executionid which
					calls sources:jar goal. That goals forks the lifecycle, causing
					the generate-sources phase to be called twice for the install goal.
					This causes any other plugin bound to the generate-sources phase to
					be called twice which usually has nasty side effects, let alone
					creating duplicate processing and longer build times. -->
					<execution>
					  <id>attach-sources</id>
					  <phase>DISABLE_FORKED_LIFECYCLE_MSOURCES-13</phase>
					</execution>
				</executions>
			</plugin>

			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-javadoc-plugin</artifactId>
				<version>2.8</version>
				<configuration>
					<skip>true</skip>
				</configuration> 
			</plugin>

			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-release-plugin</artifactId>
				<version>2.0</version>
				<configuration>
					<preparationGoals>clean</preparationGoals>
					<autoVersionSubmodules>true</autoVersionSubmodules>
					<tagBase>http://dev.esferalia.com/repos/aon-application/releases</tagBase>
				</configuration>
			</plugin>

			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-deploy-plugin</artifactId>
				<version>2.5</version>
				<dependencies>
					<dependency>
						<groupId>org.apache.maven.wagon</groupId>
						<artifactId>wagon-ssh</artifactId>
						<version>1.0-beta-7</version>
					</dependency>
				</dependencies>
			</plugin>
			<!-- Para añadir la carpeta de los fuentes generados como source folder. -->
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>build-helper-maven-plugin</artifactId>
				<version>1.5</version>
				<executions>
					<execution>
						<id>add-source</id>
						<phase>process-sources</phase>
						<goals>
							<goal>add-source</goal>
						</goals>
						<configuration>
							<sources>
								<source>
									${project.build.directory}/generated-sources
								</source>
							</sources>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>

		<pluginManagement>
			<plugins>
				<!--This plugin's configuration is used to store Eclipse m2e settings 
					only. It has no influence on the Maven build itself. -->
				<plugin>
					<groupId>org.eclipse.m2e</groupId>
					<artifactId>lifecycle-mapping</artifactId>
					<version>1.0.0</version>
					<configuration>
						<lifecycleMappingMetadata>
							<pluginExecutions>
								<pluginExecution>
									<pluginExecutionFilter>
										<groupId>
											com.esferalia.aon
										</groupId>
										<artifactId>
											aon-alias-maven-plugin
										</artifactId>
										<versionRange>
											[7.0-SNAPSHOT,)
										</versionRange>
										<goals>
											<goal>generate-alias</goal>
										</goals>
									</pluginExecutionFilter>
									<action>
										<ignore />
									</action>
								</pluginExecution>
							</pluginExecutions>
						</lifecycleMappingMetadata>
					</configuration>
				</plugin>
			</plugins>
		</pluginManagement>
	</build>

	<distributionManagement>
		<repository>
			<id>inhouse</id>
			<name>Inhouse Internal Release Repository</name>
			<url>scp://dev.esferalia.com/var/www/maven2_repositories/inhouse</url>
		</repository>
		<snapshotRepository>
			<id>inhouse_snapshot</id>
			<name>Inhouse Internal Snapshot Repository</name>
			<url>scp://dev.esferalia.com/var/www/maven2_repositories/inhouse_snapshot</url>
			<uniqueVersion>false</uniqueVersion>
		</snapshotRepository>
	</distributionManagement>
	<profiles>
		<!-- MSOURCES-13 related workaround overriding super-pom -->
		<profile>
			<id>release-profile</id>
			<activation>
				<property>
					<name>performRelease</name>
					<value>true</value>
				</property>
			</activation>
			<build>
				<plugins>
					<plugin>
						<inherited>true</inherited>
						<artifactId>maven-source-plugin</artifactId>
						<executions>
							<execution>
								<id>attach-sources-no-fork</id>
								<inherited>true</inherited>
								<goals>
									<goal>jar-no-fork</goal>
								</goals>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>
		</profile>
	</profiles>
</project>
