#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
# commons-logging.properties
# jdk handlers

#org.apache.commons.logging.Log=org.apache.commons.logging.impl.Jdk14Logger

org.apache.commons.logging.Log=org.apache.commons.logging.impl.Jdk14Logger
#org.apache.commons.logging.LogFactory=org.apache.commons.logging.impl.Jdk14Logger
#org.apache.commons.logging.Log=org.apache.commons.logging.impl.Log4JLogger

#handlers=java.util.logging.FileHandler, java.util.logging.ConsoleHandler
handlers=java.util.logging.ConsoleHandler

# default log level
.level=DEBUG

# Specific logger level
#example.Example.level=DEBUG
#example.SimpleSample.level=FINE
com.gargoylesoftware.htmlunit.WebCLient.level=DEBUG


java.util.logging.ConsoleHandler.level=ALL
