<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>com.code.aon</groupId>
		<artifactId>aon.parent</artifactId>
		<version>8.91.1</version>
	</parent>
	<artifactId>aon.aeat.mipf</artifactId>
	<packaging>rpm</packaging>
	<name>AON AEAT MIPF</name>
	<description>Modulo de Validacion e impresion de modelos fiscales</description>

	<properties>
		<maven.build.timestamp.format>dd/MM/yyyy</maven.build.timestamp.format>
	</properties>
	
	<scm>
		<developerConnection>scm:svn:http://dev.esferalia.net/repos/aon-application/trunk/aon.aeat.mipf</developerConnection>
		<connection>scm:svn:http://dev.esferalia.net/repos/aon-application/trunk/aon.aeat.mipf</connection>
	  <tag>8.91.1.x</tag>
  </scm>
	<build>
		<finalName>aon-aio</finalName>
		
		<plugins>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>build-helper-maven-plugin</artifactId>
				<version>1.7</version>
				<executions>
					<execution>
						<id>parse-version</id>
						<goals>
							<goal>parse-version</goal>
						</goals>
						<configuration>
		
						</configuration>
					</execution>
				</executions>
			</plugin>

			<!-- Para construir el RPM -->
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>rpm-maven-plugin</artifactId>
				<version>2.1-alpha-2</version>
				<extensions>true</extensions>
				<configuration>
					<group>Applications/Aon</group>
					<release>${buildNumber}</release>
					<copyright>2009, esferalia Networks S.A</copyright>
					<requires>
						<require>java</require>
						<require>xorg-x11-server-Xvfb</require>
					</requires>

					<mappings>
						<mapping>
							<directory>/usr/share/java/aon.mipf</directory>
							<filemode>755</filemode>
							<username>tomcat</username>
							<groupname>tomcat</groupname>
							<sources>
								<source>
									<location>src/main/resources/tool</location>
								</source>
							</sources>
						</mapping>
						<mapping>
							<directory>/var/log/aon.mipf</directory>
							<filemode>755</filemode>
							<username>tomcat</username>
							<groupname>tomcat</groupname>
							<sources>
								<softlinkSource>
									<location>/usr/share/java/aon.mipf/log/mipf.log</location>
									<destination>mipf.log</destination>
								</softlinkSource>
							</sources>
						</mapping>
					</mappings>
				</configuration>
			</plugin>
		</plugins>
	</build>
</project>
