<?xml version="1.0"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <parent>
    <groupId>com.code.aon</groupId>
    <artifactId>aon.parent</artifactId>
    <version>8.109</version>
  </parent>
  <modelVersion>4.0.0</modelVersion>
  <artifactId>aon.ui.finance</artifactId>
  <description>AON UI FINANCE</description>
  <name>AON UI FINANCE</name>
  <dependencies>
    <dependency>
      <groupId>com.code.aon</groupId>
      <artifactId>aon.pool</artifactId>
      <version>${project.version}</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>com.code.aon</groupId>
      <artifactId>aon.account.bridge</artifactId>
      <version>${project.version}</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.code.aon</groupId>
      <artifactId>aon.accounting</artifactId>
      <version>${project.version}</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.code.aon</groupId>
      <artifactId>aon.company</artifactId>
      <version>${project.version}</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.code.aon</groupId>
      <artifactId>aon.config</artifactId>
      <version>${project.version}</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.code.aon</groupId>
      <artifactId>aon.customer</artifactId>
      <version>${project.version}</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.code.aon</groupId>
      <artifactId>aon.facturae</artifactId>
      <version>${project.version}</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.code.aon</groupId>
      <artifactId>aon.file.bank</artifactId>
      <version>${project.version}</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.code.aon</groupId>
      <artifactId>aon.file.tax</artifactId>
      <version>${project.version}</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.code.aon</groupId>
      <artifactId>aon.finance</artifactId>
      <version>${project.version}</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.code.aon</groupId>
      <artifactId>aon.finance.bridge</artifactId>
      <version>${project.version}</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.code.aon</groupId>
      <artifactId>aon.geozone</artifactId>
      <version>${project.version}</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.code.aon</groupId>
      <artifactId>aon.product</artifactId>
      <version>${project.version}</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.code.aon</groupId>
      <artifactId>aon.registry</artifactId>
      <version>${project.version}</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.code.aon</groupId>
      <artifactId>aon.supplier</artifactId>
      <version>${project.version}</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.code.aon</groupId>
      <artifactId>aon.warehouse.bridge</artifactId>
      <version>${project.version}</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.code.aon</groupId>
      <artifactId>aon.ui.company</artifactId>
      <version>${project.version}</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.code.aon</groupId>
      <artifactId>aon.ui.config</artifactId>
      <version>${project.version}</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.code.aon</groupId>
      <artifactId>aon.ui.customer</artifactId>
      <version>${project.version}</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.code.aon</groupId>
      <artifactId>aon.ui.form</artifactId>
      <version>${project.version}</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.code.aon</groupId>
      <artifactId>aon.ui.product</artifactId>
      <version>${project.version}</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.code.aon</groupId>
      <artifactId>aon.ui.project</artifactId>
      <version>${project.version}</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.code.aon</groupId>
      <artifactId>aon.ui.registry</artifactId>
      <version>${project.version}</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.code.aon</groupId>
      <artifactId>aon.ui.report</artifactId>
      <version>${project.version}</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.code.aon</groupId>
      <artifactId>aon.ui.sign</artifactId>
      <version>${project.version}</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.code.aon</groupId>
      <artifactId>aon.ui.supplier</artifactId>
      <version>${project.version}</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.code.aon</groupId>
      <artifactId>aon.ui.webmail</artifactId>
      <version>${project.version}</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.esferalia.aon</groupId>
      <artifactId>aon.file.seres</artifactId>
      <version>${project.version}</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.esferalia.aon</groupId>
      <artifactId>aon.pms</artifactId>
      <version>${project.version}</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>commons-codec</groupId>
      <artifactId>commons-codec</artifactId>
      <version>1.3</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>javax.servlet</groupId>
      <artifactId>javax.servlet-api</artifactId>
      <version>3.1.0</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>javax.faces</groupId>
      <artifactId>jsf-api</artifactId>
      <version>1.2_14</version>
      <scope>provided</scope>
    </dependency>
  </dependencies>
</project>
