bgcolor_color_de_fondo = #ffffff
bgcolor_color_de_fondo_contenido = #eeeeee
color_color_de_texto = #222222
color_color_de_texto_menu = #666666
color_color_texto_titulos = #333333
color_color_texto_links = #333333
color_color_texto_links_hover = #666666
font_fuente = 3
size_tamaño_de_fuente = 11
border_bordes = 1
color_color_borde = #666666