//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.06.03 at 02:08:06 p. m. CEST 
//


package https.www2_agenciatributaria_gob_es.static_files.common.internet.dep.aplicaciones.es.aeat.tike.cont.ws.eventossif;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import org.w3._2000._09.xmldsig.SignatureType;


/**
 * <p>Java class for EventoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EventoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SistemaInformatico" type="{https://www2.agenciatributaria.gob.es/static_files/common/internet/dep/aplicaciones/es/aeat/tike/cont/ws/EventosSIF.xsd}SistemaInformaticoType"/>
 *         &lt;element name="ObligadoEmision" type="{https://www2.agenciatributaria.gob.es/static_files/common/internet/dep/aplicaciones/es/aeat/tike/cont/ws/EventosSIF.xsd}PersonaFisicaJuridicaESType"/>
 *         &lt;element name="EmitidaPorTerceroODestinatario" type="{https://www2.agenciatributaria.gob.es/static_files/common/internet/dep/aplicaciones/es/aeat/tike/cont/ws/EventosSIF.xsd}TercerosODestinatarioType" minOccurs="0"/>
 *         &lt;element name="TerceroODestinatario" type="{https://www2.agenciatributaria.gob.es/static_files/common/internet/dep/aplicaciones/es/aeat/tike/cont/ws/EventosSIF.xsd}PersonaFisicaJuridicaType" minOccurs="0"/>
 *         &lt;element name="FechaHoraHusoGenEvento" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="TipoEvento" type="{https://www2.agenciatributaria.gob.es/static_files/common/internet/dep/aplicaciones/es/aeat/tike/cont/ws/EventosSIF.xsd}TipoEventoType"/>
 *         &lt;element name="DatosPropiosEvento" type="{https://www2.agenciatributaria.gob.es/static_files/common/internet/dep/aplicaciones/es/aeat/tike/cont/ws/EventosSIF.xsd}DatosPropiosEventoType" minOccurs="0"/>
 *         &lt;element name="OtrosDatosEvento" type="{https://www2.agenciatributaria.gob.es/static_files/common/internet/dep/aplicaciones/es/aeat/tike/cont/ws/EventosSIF.xsd}TextMax100Type" minOccurs="0"/>
 *         &lt;element name="Encadenamiento" type="{https://www2.agenciatributaria.gob.es/static_files/common/internet/dep/aplicaciones/es/aeat/tike/cont/ws/EventosSIF.xsd}EncadenamientoType"/>
 *         &lt;element name="TipoHuella" type="{https://www2.agenciatributaria.gob.es/static_files/common/internet/dep/aplicaciones/es/aeat/tike/cont/ws/EventosSIF.xsd}TipoHuellaType"/>
 *         &lt;element name="HuellaEvento" type="{https://www2.agenciatributaria.gob.es/static_files/common/internet/dep/aplicaciones/es/aeat/tike/cont/ws/EventosSIF.xsd}TextMax64Type"/>
 *         &lt;element ref="{http://www.w3.org/2000/09/xmldsig#}Signature"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EventoType", propOrder = {
    "sistemaInformatico",
    "obligadoEmision",
    "emitidaPorTerceroODestinatario",
    "terceroODestinatario",
    "fechaHoraHusoGenEvento",
    "tipoEvento",
    "datosPropiosEvento",
    "otrosDatosEvento",
    "encadenamiento",
    "tipoHuella",
    "huellaEvento",
    "signature"
})
public class EventoType {

    @XmlElement(name = "SistemaInformatico", required = true)
    protected SistemaInformaticoType sistemaInformatico;
    @XmlElement(name = "ObligadoEmision", required = true)
    protected PersonaFisicaJuridicaESType obligadoEmision;
    @XmlElement(name = "EmitidaPorTerceroODestinatario")
    protected TercerosODestinatarioType emitidaPorTerceroODestinatario;
    @XmlElement(name = "TerceroODestinatario")
    protected PersonaFisicaJuridicaType terceroODestinatario;
    @XmlElement(name = "FechaHoraHusoGenEvento", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar fechaHoraHusoGenEvento;
    @XmlElement(name = "TipoEvento", required = true)
    protected String tipoEvento;
    @XmlElement(name = "DatosPropiosEvento")
    protected DatosPropiosEventoType datosPropiosEvento;
    @XmlElement(name = "OtrosDatosEvento")
    protected String otrosDatosEvento;
    @XmlElement(name = "Encadenamiento", required = true)
    protected EncadenamientoType encadenamiento;
    @XmlElement(name = "TipoHuella", required = true)
    protected String tipoHuella;
    @XmlElement(name = "HuellaEvento", required = true)
    protected String huellaEvento;
    @XmlElement(name = "Signature", namespace = "http://www.w3.org/2000/09/xmldsig#", required = true)
    protected SignatureType signature;

    /**
     * Gets the value of the sistemaInformatico property.
     * 
     * @return
     *     possible object is
     *     {@link SistemaInformaticoType }
     *     
     */
    public SistemaInformaticoType getSistemaInformatico() {
        return sistemaInformatico;
    }

    /**
     * Sets the value of the sistemaInformatico property.
     * 
     * @param value
     *     allowed object is
     *     {@link SistemaInformaticoType }
     *     
     */
    public void setSistemaInformatico(SistemaInformaticoType value) {
        this.sistemaInformatico = value;
    }

    /**
     * Gets the value of the obligadoEmision property.
     * 
     * @return
     *     possible object is
     *     {@link PersonaFisicaJuridicaESType }
     *     
     */
    public PersonaFisicaJuridicaESType getObligadoEmision() {
        return obligadoEmision;
    }

    /**
     * Sets the value of the obligadoEmision property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonaFisicaJuridicaESType }
     *     
     */
    public void setObligadoEmision(PersonaFisicaJuridicaESType value) {
        this.obligadoEmision = value;
    }

    /**
     * Gets the value of the emitidaPorTerceroODestinatario property.
     * 
     * @return
     *     possible object is
     *     {@link TercerosODestinatarioType }
     *     
     */
    public TercerosODestinatarioType getEmitidaPorTerceroODestinatario() {
        return emitidaPorTerceroODestinatario;
    }

    /**
     * Sets the value of the emitidaPorTerceroODestinatario property.
     * 
     * @param value
     *     allowed object is
     *     {@link TercerosODestinatarioType }
     *     
     */
    public void setEmitidaPorTerceroODestinatario(TercerosODestinatarioType value) {
        this.emitidaPorTerceroODestinatario = value;
    }

    /**
     * Gets the value of the terceroODestinatario property.
     * 
     * @return
     *     possible object is
     *     {@link PersonaFisicaJuridicaType }
     *     
     */
    public PersonaFisicaJuridicaType getTerceroODestinatario() {
        return terceroODestinatario;
    }

    /**
     * Sets the value of the terceroODestinatario property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonaFisicaJuridicaType }
     *     
     */
    public void setTerceroODestinatario(PersonaFisicaJuridicaType value) {
        this.terceroODestinatario = value;
    }

    /**
     * Gets the value of the fechaHoraHusoGenEvento property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFechaHoraHusoGenEvento() {
        return fechaHoraHusoGenEvento;
    }

    /**
     * Sets the value of the fechaHoraHusoGenEvento property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFechaHoraHusoGenEvento(XMLGregorianCalendar value) {
        this.fechaHoraHusoGenEvento = value;
    }

    /**
     * Gets the value of the tipoEvento property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoEvento() {
        return tipoEvento;
    }

    /**
     * Sets the value of the tipoEvento property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoEvento(String value) {
        this.tipoEvento = value;
    }

    /**
     * Gets the value of the datosPropiosEvento property.
     * 
     * @return
     *     possible object is
     *     {@link DatosPropiosEventoType }
     *     
     */
    public DatosPropiosEventoType getDatosPropiosEvento() {
        return datosPropiosEvento;
    }

    /**
     * Sets the value of the datosPropiosEvento property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatosPropiosEventoType }
     *     
     */
    public void setDatosPropiosEvento(DatosPropiosEventoType value) {
        this.datosPropiosEvento = value;
    }

    /**
     * Gets the value of the otrosDatosEvento property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOtrosDatosEvento() {
        return otrosDatosEvento;
    }

    /**
     * Sets the value of the otrosDatosEvento property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOtrosDatosEvento(String value) {
        this.otrosDatosEvento = value;
    }

    /**
     * Gets the value of the encadenamiento property.
     * 
     * @return
     *     possible object is
     *     {@link EncadenamientoType }
     *     
     */
    public EncadenamientoType getEncadenamiento() {
        return encadenamiento;
    }

    /**
     * Sets the value of the encadenamiento property.
     * 
     * @param value
     *     allowed object is
     *     {@link EncadenamientoType }
     *     
     */
    public void setEncadenamiento(EncadenamientoType value) {
        this.encadenamiento = value;
    }

    /**
     * Gets the value of the tipoHuella property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoHuella() {
        return tipoHuella;
    }

    /**
     * Sets the value of the tipoHuella property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoHuella(String value) {
        this.tipoHuella = value;
    }

    /**
     * Gets the value of the huellaEvento property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHuellaEvento() {
        return huellaEvento;
    }

    /**
     * Sets the value of the huellaEvento property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHuellaEvento(String value) {
        this.huellaEvento = value;
    }

    /**
     * Gets the value of the signature property.
     * 
     * @return
     *     possible object is
     *     {@link SignatureType }
     *     
     */
    public SignatureType getSignature() {
        return signature;
    }

    /**
     * Sets the value of the signature property.
     * 
     * @param value
     *     allowed object is
     *     {@link SignatureType }
     *     
     */
    public void setSignature(SignatureType value) {
        this.signature = value;
    }

}
