bgcolor_color_de_fondo = #999933
bgcolor_color_de_fondo_contenido = #ffffff	
color_color_de_texto = #666666
font_fuente = 3
size_tamano_de_fuente = 11
size_tamano_de_fuente_menu = 14
color_color_de_texto_cabecera = #FFFFFF
color_color_de_texto_cabecera_hover = #FFFF99
color_color_punto_cabecera = #99CC00
color_color_de_texto_menu = #999933
color_color_de_texto_menu_hover = #CCCC33
color_color_de_texto_titulos = #669900
color_color_de_texto_pie = #CCCC66
color_color_de_texto_pie_hover = #FFFF99