bgcolor_color_de_fondo = #5aab32
bgcolor_color_de_fondo_contenido = #ffffff	
color_color_de_texto_pie = #ffffff
color_color_de_texto_pie_hover = #cccccc
color_color_de_texto_menu = #ffffff
color_color_de_texto_menu_hover = #EDEDED
color_color_borde = #ffffff
color_color_de_texto_contenido = #000000
font_fuente = 3
size_tamano_de_fuente_pie = 12
size_tamano_de_fuente_menu = 11
size_tamano_de_fuente_contenido = 11