bgcolor_color_de_fondo = #000000
bgcolor_color_de_fondo_contenido = #ffffff
bgcolor_color_de_fondo_cabecera = #C13B00
bgcolor_color_de_fondo_menu = #FF6600
bgcolor_color_fondo_pie = #424E4F
color_color_de_texto_link = #C23B01
color_color_de_texto_link_hover = #333333
color_color_de_texto_menu = #ffffff	
color_color_de_texto_titulos = #1B1D1E
color_color_de_texto_pie = #ffffff	
bgcolor_color_de_fondo_menu_hover = #C23B01
font_fuente = 2
size_tamano_de_fuente = 12
size_tamano_de_fuente_menu = 14
size_tamano_de_fuente_pie = 12
border_bordes = 1
color_color_de_borde = #666666
color_color_de_texto_cabecera = #FFFFFF