<?xml version="1.0" encoding="ISO-8859-1"?>
<xs:schema targetNamespace="http://www.seg-social.es/creta/esquemas/V100/ReciboLiquidacionCotizaciones" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.seg-social.es/creta/esquemas/V100/ReciboLiquidacionCotizaciones" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="ReciboLiquidacionCotizaciones">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Autorizado"/>
				<xs:element ref="Liquidacion"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Autorizado">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:pattern value="\d\d\d\d\d\d\d\d"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Liquidacion">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Ccc"/>
				<xs:element ref="CccConcertado" minOccurs="0"/>
				<xs:element ref="PeriodoDesde"/>
				<xs:element ref="PeriodoHasta"/>
				<xs:element ref="Tipo"/>
				<xs:element ref="FechaControl" minOccurs="0"/>
				<xs:element ref="FechaHoraRecaudacion"/>
				<xs:element ref="TipoRLC"/>
				<xs:element ref="DatosCabeceraRLC"/>
				<xs:element ref="DatosCuerpoRLC"/>
				<xs:element ref="DatosPiePaginaRLC"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="CtaCot">
		<xs:sequence>
			<xs:element ref="Regimen"/>
			<xs:element ref="Provincia"/>
			<xs:element ref="Numero"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="Ccc" type="CtaCot"/>
	<xs:element name="CccConcertado" type="CtaCot"/>
	<xs:element name="Regimen">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:pattern value="\d\d\d\d"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Provincia">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:pattern value="\d\d"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Numero">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:pattern value="\d{9}"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:complexType name="Periodo">
		<xs:sequence>
			<xs:element ref="Mes"/>
			<xs:element ref="Anho"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="Mes">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="12"/>
				<xs:enumeration value="11"/>
				<xs:enumeration value="10"/>
				<xs:enumeration value="09"/>
				<xs:enumeration value="08"/>
				<xs:enumeration value="07"/>
				<xs:enumeration value="06"/>
				<xs:enumeration value="05"/>
				<xs:enumeration value="04"/>
				<xs:enumeration value="03"/>
				<xs:enumeration value="02"/>
				<xs:enumeration value="01"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Anho">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:length value="4"/>
				<xs:pattern value="\d{4}"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="PeriodoDesde" type="Periodo"/>
	<xs:element name="PeriodoHasta" type="Periodo"/>
	<xs:element name="Tipo">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="3"/>
				<xs:maxLength value="3"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="FechaControl" type="Periodo"/>
	<xs:element name="FechaHoraRecaudacion">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="FechaRecaudacion"/>
				<xs:element ref="HoraRecaudacion"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="FechaRecaudacion" type="Fecha"/>
	<xs:element name="HoraRecaudacion">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:length value="6"/>
				<xs:pattern value="\d{6}"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="TipoRLC">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
				<xs:maxLength value="2"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="DatosCabeceraRLC">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="AlcanceCalculo"/>
				<xs:element ref="CuotaALiquidar"/>
				<xs:element ref="DatosEnvio"/>
				<xs:element ref="DatosLiquidacion"/>
				<xs:element ref="CodificacionesInformaticas"/>
				<xs:element ref="CabeceraPagoElectronico" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="AlcanceCalculo">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:maxLength value="50"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="CuotaALiquidar" type="xs:string"/>
	<xs:element name="DatosEnvio">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Autorizado"/>
				<xs:element ref="Envio"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Envio">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:length value="10"/>
				<xs:pattern value="\d{10}"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="DatosLiquidacion">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Ccc"/>
				<xs:element ref="PeriodoDesde"/>
				<xs:element ref="PeriodoHasta"/>
				<xs:element ref="DescripcionTipoLiquidacion"/>
				<xs:element ref="RazonSocial"/>
				<xs:element ref="Empresario"/>
				<xs:element ref="EntidadAtEp"/>
				<xs:element ref="NumeroTrabajadores"/>
				<xs:element ref="ModalidadPago"/>
				<xs:element ref="NumeroLiquidacion"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="DescripcionTipoLiquidacion">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:maxLength value="50"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="RazonSocial">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:maxLength value="55"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Empresario" type="Ipf"/>
	<xs:complexType name="Ipf">
		<xs:sequence>
			<xs:element ref="TipoIpf"/>
			<xs:element ref="NumeroIpf"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="TipoIpf">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:pattern value="\w"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="NumeroIpf">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:pattern value="\w{10}"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="EntidadAtEp">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:maxLength value="50"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="NumeroTrabajadores">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
				<xs:maxLength value="6"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="ModalidadPago">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:maxLength value="50"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="NumeroLiquidacion">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:length value="17"/>
				<xs:pattern value="\d{17}"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="CodificacionesInformaticas">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ReferenciaCI"/>
				<xs:element ref="FechaCI"/>
				<xs:element ref="HoraCI"/>
				<xs:element ref="HuellaCI"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ReferenciaCI">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:length value="14"/>
				<xs:pattern value="\w{14}"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="FechaCI" type="Fecha"/>
	<xs:element name="HoraCI">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:length value="6"/>
				<xs:pattern value="\d{6}"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="HuellaCI">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:length value="8"/>
				<xs:pattern value="\w{8}"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:complexType name="Fecha">
		<xs:sequence>
			<xs:element ref="Dia"/>
			<xs:element ref="Mes"/>
			<xs:element ref="Anho"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="Dia">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="2"/>
				<xs:maxLength value="2"/>
				<xs:pattern value="\d\d"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="CabeceraPagoElectronico">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="PeriodoPagoPE"/>
				<xs:element ref="EmisoraPE"/>
				<xs:element ref="NumeroReferenciaPE"/>
				<xs:element ref="IdentificacionPE"/>
				<xs:element ref="ImportePE"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="PeriodoPagoPE">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="PeriodoDesde"/>
				<xs:element ref="PeriodoHasta"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="EmisoraPE">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:pattern value="\d{11}"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="NumeroReferenciaPE">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:pattern value="\d{13}"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="IdentificacionPE">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:pattern value="\d{6}"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="ImportePE">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
				<xs:maxLength value="11"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="DatosCuerpoRLC">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="LineaRLC" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="LineaRLC">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="DescripcionLRLC"/>
				<xs:element ref="BaseLRLC" minOccurs="0"/>
				<xs:element ref="ImporteLRLC"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="DescripcionLRLC">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:maxLength value="50"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="BaseLRLC">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
				<xs:maxLength value="11"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="ImporteLRLC">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
				<xs:maxLength value="11"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="DatosPiePaginaRLC">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="TextoPieRLC"/>
				<xs:element ref="CodigoBarras" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="TextoPieRLC" type="xs:string"/>
	<xs:element name="CodigoBarras">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="IdentificacionAplicacionCB"/>
				<xs:element ref="TipoFormatoCB"/>
				<xs:element ref="EmisoraCB"/>
				<xs:element ref="SufijoCB"/>
				<xs:element ref="ReferenciaCB"/>
				<xs:element ref="IdentificadorCB"/>
				<xs:element ref="ImporteCB"/>
				<xs:element ref="DigitoParidadCB"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="IdentificacionAplicacionCB">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:pattern value="\d\d"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="TipoFormatoCB">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:pattern value="\d\d\d"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="EmisoraCB">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:pattern value="\d{8}"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="SufijoCB">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:pattern value="\d\d\d"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="ReferenciaCB">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:pattern value="\d{13}"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="IdentificadorCB">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:pattern value="\d{6}"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="ImporteCB">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:pattern value="\d{10}"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="DigitoParidadCB">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:pattern value="\d"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
</xs:schema>
