GENERIC=true
BANNER=true
BANNER_GROUP=true
MENU=true
ARTICLE=true
LINK=true
DIRECT_ACCESS=true
ARTICLE_NEWS_CATEGORY=true
ARTICLE_SERVICES_CATEGORY=true
ARTICLE_EVENTS_CATEGORY=true
ARTICLE_OTHER_CATEGORY=true
DOWNLOAD_CATEGORY=true
ALBUM_CATEGORY=true
DIARY_CALENDAR=true
