bgcolor_color_de_fondo = #125d7d
bgcolor_color_de_fondo_contenido = #f8f8f8
bgcolor_color_de_fondo_menu_hover = #5eb3d7
color_color_de_texto = #000000
color_color_de_texto_link = #125d7d
color_color_de_texto_link_hover = #444444
color_color_de_texto_pie = #ffffff
color_color_de_texto_menu = #ffffff
color_color_de_texto_menu_hover = #5eb3d7
color_color_borde_abajo = #e6e4e4
color_color_borde_arriba = #ffffff
font_fuente = 3
size_tamano_de_fuente = 12
size_tamano_de_fuente_pie = 10
border_bordes = 1