<?xml version="1.0"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<parent>
		<groupId>com.code.aon</groupId>
		<artifactId>aon.web.parent</artifactId>
		<version>7.14.4</version>
		<relativePath>../aon-web-parent</relativePath>
	</parent>
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.esferalia.aon</groupId>
	<artifactId>aon-ws-gps</artifactId>
	<packaging>war</packaging>
	<version>7.14.4</version>
	<description>AON WS GPS</description>
	<name>AON WS GPS</name>
	<properties>
		<dbVersion>7.0.0</dbVersion>
	</properties>
	<build>
		<finalName>aon-ws-gps</finalName>
		<plugins>
			<!-- Para construir el RPM -->
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>rpm-maven-plugin</artifactId>
				<version>2.0.1</version>
			</plugin>
		</plugins>
	</build>
	<dependencies>
 		<dependency>
			<groupId>com.esferalia.aon</groupId>
			<artifactId>aon.pms</artifactId>
			<version>${project.version}</version>
			<scope>runtime</scope>
		</dependency>
	</dependencies>
    <profiles>
      	<profile>
            <id>perform-stats</id>
        </profile>
    </profiles>
</project>
 
