<?xml version="1.0"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.code.aon</groupId>
    <artifactId>aon.parent</artifactId>
    <version>8.54</version>
  </parent>
  <groupId>com.esferalia.aon</groupId>
  <artifactId>aon-ws-gps</artifactId>
  <packaging>war</packaging>
  <name>AON WS GPS</name>
  <description>AON WS GPS</description>
  <properties>
    <maven.build.timestamp.format>dd/MM/yyyy</maven.build.timestamp.format>
  </properties>
  <build>
    <finalName>aon-ws-gps</finalName>
    <plugins>
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>build-helper-maven-plugin</artifactId>
        <version>1.7</version>
        <executions>
          <execution>
            <id>parse-version</id>
            <goals>
              <goal>parse-version</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-war-plugin</artifactId>
        <version>2.2</version>
        <configuration>
          <archive>
            <manifest>
              <addDefaultSpecificationEntries>true</addDefaultSpecificationEntries>
              <addDefaultImplementationEntries>true</addDefaultImplementationEntries>
            </manifest>
            <manifestEntries>
              <dbVersion>${dbVersion}</dbVersion>
              <buildNumber>${env.BUILD_NUMBER}</buildNumber>
              <buildDate>${maven.build.timestamp}</buildDate>
              <buildRevision>${buildNumber}</buildRevision>
            </manifestEntries>
          </archive>
        </configuration>
        <executions>
          <execution>
            <id>execution1</id>
            <phase>package</phase>
            <configuration />
            <goals>
              <goal>manifest</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <!-- Para construir el RPM -->
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>rpm-maven-plugin</artifactId>
        <version>2.0.1</version>
      </plugin>
    </plugins>
  </build>
  <dependencies>
	<dependency>
		<groupId>com.code.aon</groupId>
		<artifactId>aon.pool</artifactId>
		<version>${project.version}</version>
		<scope>provided</scope>
	</dependency>
    <dependency>
      <groupId>com.esferalia.aon</groupId>
      <artifactId>aon.pms</artifactId>
      <version>${project.version}</version>
      <scope>compile</scope>
      <exclusions>
        <exclusion>
          <artifactId>aon.payroll</artifactId>
          <groupId>com.esferalia.aon</groupId>
        </exclusion>
      </exclusions>
    </dependency>
    <!--  DEPENDENCIAS DE EJECUCION PARA TOMCAT -->
    <dependency>
      <groupId>com.sun.xml.ws</groupId>
      <artifactId>jaxws-rt</artifactId>
      <version>2.2.6</version>
      <scope>runtime</scope>
      <exclusions>
        <exclusion>
          <artifactId>activation</artifactId>
          <groupId>javax.activation</groupId>
        </exclusion>
        <exclusion>
          <artifactId>istack-commons-runtime</artifactId>
          <groupId>com.sun.istack</groupId>
        </exclusion>
        <exclusion>
          <artifactId>javax.annotation</artifactId>
          <groupId>org.glassfish</groupId>
        </exclusion>
        <exclusion>
          <artifactId>jsr181-api</artifactId>
          <groupId>javax.jws</groupId>
        </exclusion>
        <exclusion>
          <artifactId>mimepull</artifactId>
          <groupId>org.jvnet.mimepull</groupId>
        </exclusion>
        <exclusion>
          <artifactId>stax-api</artifactId>
          <groupId>javax.xml.stream</groupId>
        </exclusion>
        <exclusion>
          <artifactId>txw2</artifactId>
          <groupId>com.sun.xml.txw2</groupId>
        </exclusion>
        <exclusion>
          <artifactId>woodstox-core-asl</artifactId>
          <groupId>org.codehaus.woodstox</groupId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.hibernate</groupId>
      <artifactId>hibernate</artifactId>
      <version>3.2.7.ga</version>
      <exclusions>
        <exclusion>
          <groupId>asm</groupId>
          <artifactId>asm-attrs</artifactId>
        </exclusion>
        <exclusion>
          <groupId>net.sf.ehcache</groupId>
          <artifactId>ehcache</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.hibernate</groupId>
      <artifactId>hibernate-tools</artifactId>
      <version>3.2.3.GA</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>commons-logging</groupId>
      <artifactId>commons-logging</artifactId>
      <version>1.1</version>
      <scope>provided</scope>
      <exclusions>
        <exclusion>
          <groupId>javax.servlet</groupId>
          <artifactId>servlet-api</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>commons-collections</groupId>
      <artifactId>commons-collections</artifactId>
      <version>3.1</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-api</artifactId>
      <version>1.5.11</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-jcl</artifactId>
      <version>1.5.11</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>javax.servlet</groupId>
      <artifactId>javax.servlet-api</artifactId>
      <version>3.1.0</version>
      <scope>provided</scope>
    </dependency>
  </dependencies>
  <profiles>
    <profile>
      <id>rpm-release</id>
      <activation>
        <property>
          <name>rpm.release</name>
          <value>true</value>
        </property>
      </activation>
      <build>
        <pluginManagement>
          <plugins>
            <plugin>
              <groupId>org.codehaus.mojo</groupId>
              <artifactId>rpm-maven-plugin</artifactId>
              <version>2.1-alpha-2</version>
              <extensions>true</extensions>
              <executions>
                <execution>
                  <id>tomcat8-rpm-build</id>
                  <goals>
                    <goal>attached-rpm</goal>
                  </goals>
                  <configuration>
                    <name>aon-ws-gps8</name>
                    <group>Applications/Aon</group>
                    <classifier>TOMCAT8</classifier>
                    <release>tomcat_${buildNumber}</release>
                    <copyright>2013, esferalia Networks S.A</copyright>
                    <requires>
                      <require>tomcat8</require>
                      <require>java-1.8.0-openjdk</require>
                      <require>mysql-connector-java</require>
                      <require>slf4j</require>
                    </requires>
                    <mappings>
                      <mapping>
                        <directory>/var/lib/tomcat8/webapps/aon-ws-gps</directory>
                        <filemode>755</filemode>
                        <username>tomcat</username>
                        <groupname>tomcat</groupname>
                        <directoryIncluded>false</directoryIncluded>
                        <sources>
                          <source>
                            <location>target/aon-ws-gps</location>
                          </source>
                        </sources>
                      </mapping>
                    </mappings>
                  </configuration>
                </execution>
              </executions>
            </plugin>
          </plugins>
        </pluginManagement>
      </build>
    </profile>
  </profiles>
</project>
