<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<parent>
		<groupId>com.code.aon</groupId>
		<artifactId>aon.parent</artifactId>
		<version>5.2.5</version>
	</parent>
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.code.aon</groupId>
	<artifactId>aon-master</artifactId>
	<version>5.2.5</version>
	<description>AON MASTER</description>
	<name>AON-MASTER</name>

        <scm>
                <developerConnection>scm:svn:http://dev.esferalia.com/repos/aon-application/releases/5.2.x/trunk/aon-master</developerConnection>
                <connection>scm:svn:http://dev.esferalia.com/repos/aon-application/releases/5.2.x/trunk/aon-master</connection>
                <url>scm:svn:http://dev.esferalia.com/repos/aon-application/releases/5.2.x/wsvn/aon-master</url>
        </scm>

	<dependencies>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon-dbutils</artifactId>
			<version>${pom.version}</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>commons-lang</groupId>
			<artifactId>commons-lang</artifactId>
			<version>2.5</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-api</artifactId>
			<version>1.5.11</version>
			<scope>compile</scope>
		</dependency>
<!-- 
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.common</artifactId>
			<version>${aon-version}</version>
			<scope>compile</scope>
		</dependency>
-->		
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-jcl</artifactId>
			<version>1.5.8</version>
			<scope>runtime</scope>
		</dependency>
		<!-- TEST DEPENDENCIES -->
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.1</version>
			<scope>test</scope>
		</dependency>
		<dependency>
		    <groupId>mysql</groupId>
		    <artifactId>mysql-connector-java</artifactId>
		    <version>5.0.8</version>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<build>
		<plugins>
                        <plugin>
                                <groupId>org.codehaus.mojo</groupId>
                                <artifactId>buildnumber-maven-plugin</artifactId>
                                <version>1.0-beta-4</version>
                                <executions>
                                        <execution>
                                                <phase>validate</phase>
                                                <goals>
                                                        <goal>create</goal>
                                                </goals>
                                        </execution>
                                </executions>
                                <configuration>
                                        <doCheck>true</doCheck>
                                        <doUpdate>true</doUpdate>
                                </configuration>
                        </plugin>
		</plugins>
	</build>

        <profiles>
                <profile>
                        <id>rpm-release</id>
                        <activation>
                                <property>
                                        <name>rpm.release</name>
                                        <value>true</value>
                                </property>
                        </activation>
                        <build>
                                <plugins>
                                        <!-- Para construir el RPM -->
                                        <plugin>

                                                <groupId>org.codehaus.mojo</groupId>
                                                <artifactId>rpm-maven-plugin</artifactId>
                                                <version>2.0.1</version>
                                                <extensions>true</extensions>

                                                <executions>
                                                        <execution>
                                                                <id>rpm-build</id>
                                                                <goals>
                                                                        <goal>attached-rpm</goal>
                                                                </goals>
                                                        </execution>

                                                </executions>

                                                <configuration>
                                                        <group>Applications/Aon</group>
                                                        <release>${buildNumber}</release>
                                                        <copyright>2010, esferalia Networks S.A</copyright>
                                                        <requires>
                                                                <require>aon-dbutils</require>
                                                                <require>aon-directory-client &gt;= 5.0.0-4</require>
                                                        </requires>
                                                        <mappings>
                                                                <mapping>
									<artifact>
										<classifiers>
											<classifier />
										</classifiers>
									</artifact>	
									<dependency>
										<includes>
											<include>org.slf4j:slf4j-jcl</include>
											<include>org.slf4j:slf4j-api</include>
											<include>commons-lang:commons-lang</include>
										</includes>
									</dependency>
                                                                        <filemode>755</filemode>
                                                                        <username>root</username>
                                                                        <groupname>root</groupname>
									<directory>/usr/share/java</directory>
                                                                </mapping>
                                                                <mapping>
                                                                        <sources>
                                                                                <source>
                                                                                        <location>src/main/scripts/automysqlbackup.sh</location>
                                                                                </source>
                                                                        </sources>
                                                                        <filemode>755</filemode>
                                                                        <username>root</username>
                                                                        <groupname>root</groupname>
                                                                        <directory>/usr/share/aon-master/bin</directory>
                                                                </mapping>
                                                        </mappings>
                                                        
							<postinstallScriptlet>
                                                                <scriptFile>src/main/scripts/postinstall</scriptFile>
                                                                <fileEncoding>utf-8</fileEncoding>
                                                        </postinstallScriptlet>
                                                        
							<postremoveScriptlet>
                                                                <scriptFile>src/main/scripts/postremove</scriptFile>
                                                                <fileEncoding>utf-8</fileEncoding>
                                                        </postremoveScriptlet>

                                                </configuration>
                                        </plugin>

                                        <plugin>
                                                <groupId>org.codehaus.mojo</groupId>
                                                <artifactId>wagon-maven-plugin</artifactId>
                                                <version>1.0-beta-3</version>
                                                <executions>
                                                        <execution>
                                                                <id>upload-rpm</id>
                                                                <phase>deploy</phase>
                                                                <goals>
                                                                        <goal>upload</goal>
                                                                </goals>
                                                                <configuration>
                                                                        <fromDir>${project.basedir}/target/rpm/${project.artifactId}/RPMS/</fromDir>
                                                                        <includes>**/*.rpm</includes>
                                                                        <url>scp://dev.esferalia.com</url>
                                                                        <toDir>/var/www/aon-inetserver</toDir>
                                                                </configuration>
                                                        </execution>
                                                </executions>
                                        </plugin>


                                </plugins>
                        </build>
                </profile>
        </profiles>

</project>
