bgcolor_color_de_fondo = #ffffff
color_color_de_texto = #000000
color_color_texto_contenido = #505050
font_fuente = 1
size_tamaño_de_fuente = 14
size_tamaño_fuente_cabecera = 26
size_tamaño_fuente_pie = 10
size_tamaño_fuente_menu = 16
img_imagen_de_fondo = art.jpg	
border_bordes_menu = 1
color_color_borde = #cccccc