bgcolor_color_de_fondo_contenido = #cccccc
bgcolor_color_de_fondo = #ffffff
color_texto= #000000
font_fuente = 3
size_tamaño_de_fuente = 11
img_imagen_de_fondo = fondocomun.jpg
color_cabecera_color_de_texto #000000
bgcolor_color_de_fondo_cabecera = #ffffff
img_imagen_fondo_cabecera = fondocomun.jpg
bgcolor_cabecera_color_fondo_inicio = #ffffff
color_texto_menu_hover = #e55302
color_color_titulo = #000000