
USE `aon_master`;

SET FOREIGN_KEY_CHECKS=0;

#
# Data for the `geozone` table  (LIMIT 0,500)
#

INSERT INTO `geozone` (`id`, `name`) VALUES 
  (1,'ALAVA'),
  (2,'ALBACETE'),
  (3,'ALICANTE'),
  (4,'ALMERIA'),
  (5,'AVILA'),
  (6,'BADAJOZ'),
  (7,'ILLES BALEARS'),
  (8,'BARCELONA'),
  (9,'BURGOS'),
  (10,'CACERES'),
  (11,'CADIZ'),
  (12,'CASTELLON'),
  (13,'CIUDAD REAL'),
  (14,'CORDOBA'),
  (15,'A CORUÑA'),
  (16,'CUENCA'),
  (17,'GIRONA'),
  (18,'GRANADA'),
  (19,'GUADALAJARA'),
  (20,'GUIPUZCOA'),
  (21,'HUELVA'),
  (22,'HUESCA'),
  (23,'JAEN'),
  (24,'LEON'),
  (25,'LLEIDA'),
  (26,'LA RIOJA'),
  (27,'LUGO'),
  (28,'MADRID'),
  (29,'MALAGA'),
  (30,'MURCIA'),
  (31,'NAVARRA'),
  (32,'OURENSE'),
  (33,'ASTURIAS'),
  (34,'PALENCIA'),
  (35,'LAS PALMAS'),
  (36,'PONTEVEDRA'),
  (37,'SALAMANCA'),
  (38,'TENERIFE'),
  (39,'CANTABRIA'),
  (40,'SEGOVIA'),
  (41,'SEVILLA'),
  (42,'SORIA'),
  (43,'TARRAGONA'),
  (44,'TERUEL'),
  (45,'TOLEDO'),
  (46,'VALENCIA'),
  (47,'VALLADOLID'),
  (48,'VIZCAYA'),
  (49,'ZAMORA'),
  (50,'ZARAGOZA'),
  (51,'CEUTA'),
  (52,'MELILLA'),
  (53,'ESPAÑA');

COMMIT;

#
# Data for the `geotree` table  (LIMIT 0,500)
#

INSERT INTO `geotree` (`id`, `parent`, `child`) VALUES 
  (1, NULL, 53),
  (2, 53, 1),
  (3, 53, 2),
  (4, 53, 3),
  (5, 53, 4),
  (6, 53, 5),
  (7, 53, 6),
  (8, 53, 7),
  (9, 53, 8),
  (10, 53, 9),
  (11, 53, 10),
  (12, 53, 11),
  (13, 53, 12),
  (14, 53, 13),
  (15, 53, 14),
  (16, 53, 15),
  (17, 53, 16),
  (18, 53, 17),
  (19, 53, 18),
  (20, 53, 19),
  (21, 53, 20),
  (22, 53, 21),
  (23, 53, 22),
  (24, 53, 23),
  (25, 53, 24),
  (26, 53, 25),
  (27, 53, 26),
  (28, 53, 27),
  (29, 53, 28),
  (30, 53, 29),
  (31, 53, 30),
  (32, 53, 31),
  (33, 53, 32),
  (34, 53, 33),
  (35, 53, 34),
  (36, 53, 35),
  (37, 53, 36),
  (38, 53, 37),
  (39, 53, 38),
  (40, 53, 39),
  (41, 53, 40),
  (42, 53, 41),
  (43, 53, 42),
  (44, 53, 43),
  (45, 53, 44),
  (46, 53, 45),
  (47, 53, 46),
  (48, 53, 47),
  (49, 53, 48),
  (50, 53, 49),
  (51, 53, 50),
  (52, 53, 51),
  (53, 53, 52);

COMMIT;

#
# Data for the `pcategory` table  (LIMIT 0,500)
#

INSERT INTO `pcategory` (`id`, `name`, `detail_pattern`, `pcategory_group`) VALUES 
  (1,'GENERICA',NULL,NULL);

COMMIT;

#
# Data for the `tax` table  (LIMIT 0,500)
#

INSERT INTO `tax` (`id`, `name`, `tax_type`, `percentage`, `surcharge`, `start_date`) VALUES 
  (1,'GENERAL',1,16,4,'2000-01-01'),
  (2,'REDUCIDO',1,7,1,'2000-01-01'),
  (3,'SUPERREDUCIDO',1,4,0.5,'2000-01-01'),
  (4,'SIN IVA',1,0,0,'2000-01-01'),
  (5,'IRPF',2,15,0,'2000-01-01');

COMMIT;

#
# Data for the `pay_method` table  (LIMIT 0,500)
#

INSERT IGNORE INTO `pay_method` (`id`, `name`, `type`) VALUES 
  (1,'EFECTIVO',1),
  (2,'GIRO',2),
  (3,'CHEQUE',5),
  (4,'TRANSFERENCIA',6);

COMMIT;

#
# Data for the `bank` table  (LIMIT 0,500)
#

INSERT INTO `bank` (`id`, `name`, `code`) VALUES 
  (1,'ALLFUNDS BANK, S.A.','0011'),
  (2,'ALTAE BANCO, S.A.','0099'),
  (3,'BANCA MARCH, S.A.','0061'),
  (4,'BANCA PUEYO, S.A.','0078'),
  (5,'BANCO ALCALA, S.A.','0188'),
  (6,'BANCO ALICANTINO DE COMERCIO, S.A.','0083'),
  (7,'BANCO ARABE ESPAÑOL, S.A.','0136'),
  (8,'BANCO BANIF, S.A.','0086'),
  (9,'BANCO BILBAO VIZCAYA ARGENTARIA, S.A.','0182'),
  (10,'BANCO CAIXA GERAL, S.A.','0130'),
  (11,'BANCO CETELEM, S.A.','0225'),
  (12,'BANCO CONDAL, S.A.','0021'),
  (13,'BANCO COOPERATIVO ESPAÑOL, S.A.','0198'),
  (14,'BANCO DE ALBACETE, S.A.','0091'),
  (15,'BANCO DE ANDALUCIA, S.A.','0004'),
  (16,'BANCO DE CASTILLA, S.A.','0082'),
  (17,'BANCO DE CREDITO BALEAR, S.A.','0024'),
  (18,'BANCO DE CREDITO LOCAL DE ESPAÑA, S.A.','1004'),
  (19,'BANCO DE DEPOSITOS, S.A.','0003'),
  (20,'BANCO DE EUROPA, S.A.','0133'),
  (21,'BANCO DE FINANZAS E INVERSIONES, S.A.','0186'),
  (22,'BANCO DE GALICIA, S.A.','0097'),
  (23,'BANCO DE LA PEQUEÑA Y MEDIANA EMPRESA, S.A.','0142'),
  (24,'BANCO DE MADRID, S.A.','0059'),
  (25,'BANCO DE PROMOCION DE NEGOCIOS, S.A. (PROMOBANC)','0132'),
  (26,'BANCO DE SABADELL, S.A.','0081'),
  (27,'BANCO DE VALENCIA, S.A.','0093'),
  (28,'BANCO DE VASCONIA, S.A.','0095'),
  (29,'BANCO DEPOSITARIO BBVA, S.A.','0057'),
  (30,'BANCO ESPAÑOL DE CREDITO, S.A.','0030'),
  (31,'BANCO ETCHEVERRIA, S.A.','0031'),
  (32,'BANCO EUROPEO DE FINANZAS, S.A.','0184'),
  (33,'BANCO EXELBANK, S.A.','0228'),
  (34,'BANCO FINANTIA SOFINLOC, S.A.','0220'),
  (35,'BANCO GALLEGO, S.A.','0046'),
  (36,'BANCO GUIPUZCOANO, S.A.','0042'),
  (37,'BANCO HALIFAX HISPANIA, S.A.','0217'),
  (38,'BANCO INDUSTRIAL DE BILBAO, S.A.','0113'),
  (39,'BANCO INVERSIS NET, S.A.','0232'),
  (40,'BANCO LIBERTA, S.A.','0115'),
  (41,'BANCO OCCIDENTAL, S.A.','0121'),
  (42,'BANCO PASTOR, S.A.','0072'),
  (43,'BANCO POPULAR ESPAÑOL, S.A.','0075'),
  (44,'BANCO POPULAR HIPOTECARIO, S.A.','0216'),
  (45,'BANCO SANTANDER CENTRAL HISPANO, S.A.','0049'),
  (46,'BANCO SERVICIOS FINANCIEROS CAJA MADRID-MAPFRE,SA','0063'),
  (47,'BANCO URQUIJO SABADELL BANCA PRIVADA, S.A.','0185'),
  (48,'BANCOFAR, S.A.','0125'),
  (49,'BANCOPOPULAR-E, S.A.','0229'),
  (50,'BANESTO BANCO DE EMISIONES, S.A.','0038'),
  (51,'BANKINTER, S.A.','0128'),
  (52,'BANKOA, S.A.','0138'),
  (53,'BANQUE MAROCAINE COMMERCE EXTERIEUR INTERNAT.,S.A.','0219'),
  (54,'BARCLAYS BANK, S.A.','0065'),
  (55,'BBVA BANCO DE FINANCIACION, S.A.','0129'),
  (56,'BNP PARIBAS ESPAÑA, S.A.','0058'),
  (57,'CITIBANK ESPAÑA, S.A.','0122'),
  (58,'DEUTSCHE BANK CREDIT, S.A.','0205'),
  (59,'DEUTSCHE BANK, S.A.E.','0019'),
  (60,'DEXIA SABADELL BANCO LOCAL, S.A.','0231'),
  (61,'EBN BANCO DE NEGOCIOS, S.A.','0211'),
  (62,'FINANZIA, BANCO DE CREDITO, S.A.','0009'),
  (63,'GENERAL ELECTRIC CAPITAL BANK, S.A.','0223'),
  (64,'OPEN BANK SANTANDER CONSUMER, S.A.','0073'),
  (65,'POPULAR BANCA PRIVADA, S.A.','0233'),
  (66,'PRIVAT BANK, S.A.','0200'),
  (67,'RBC DEXIA INVESTOR SERVICES ESPAÑA, S.A.','0094'),
  (68,'SANTANDER CONSUMER FINANCE, S.A.','0224'),
  (69,'SANTANDER INVESTMENT, S.A.','0036'),
  (70,'UBS ESPAÑA, S.A.','0226'),
  (71,'UNOE BANK, S.A.','0227'),
  (72,'BILBAO BIZKAIA KUTXA,AURREZKI KUTXA ETA BAHITETXEA','2095'),
  (73,'C.A.M.P. CIRCULO CATOLICO DE OBREROS DE BURGOS','2017'),
  (74,'CAIXA AFORROS VIGO,OURENSE E PONTEVEDRA(CAIXANOVA)','2080'),
  (75,'CAIXA D''ESTALVIS COMARCAL DE MANLLEU','2040'),
  (76,'CAIXA D''ESTALVIS DE CATALUNYA','2013'),
  (77,'CAIXA D''ESTALVIS DE GIRONA','2030'),
  (78,'CAIXA D''ESTALVIS DE MANRESA','2041'),
  (79,'CAIXA D''ESTALVIS DE SABADELL','2059'),
  (80,'CAIXA D''ESTALVIS DE TARRAGONA','2073'),
  (81,'CAIXA D''ESTALVIS DE TERRASSA','2074'),
  (82,'CAIXA D''ESTALVIS DEL PENEDES','2081'),
  (83,'CAIXA D''ESTALVIS LAIETANA','2042'),
  (84,'CAJA AH. VALENCIA, CASTELLON Y ALICANTE, BANCAJA','2077'),
  (85,'CAJA DE AH. PROV. SAN FERNANDO DE SEVILLA Y JEREZ','2071'),
  (86,'CAJA DE AHORRO PROVINCIAL DE GUADALAJARA','2032'),
  (87,'CAJA DE AHORROS DE ASTURIAS','2048'),
  (88,'CAJA DE AHORROS DE CASTILLA-LA MANCHA','2105'),
  (89,'CAJA DE AHORROS DE GALICIA','2091'),
  (90,'CAJA DE AHORROS DE LA INMACULADA DE ARAGON','2086'),
  (91,'CAJA DE AHORROS DE LA RIOJA','2037'),
  (92,'CAJA DE AHORROS DE MURCIA','2043'),
  (93,'CAJA DE AHORROS DE SALAMANCA Y SORIA','2104'),
  (94,'CAJA DE AHORROS DE SANTANDER Y CANTABRIA','2066'),
  (95,'CAJA DE AHORROS DE VITORIA Y ALAVA','2097'),
  (96,'CAJA DE AHORROS DEL MEDITERRANEO','2090'),
  (97,'CAJA DE AHORROS MUNICIPAL DE BURGOS','2018'),
  (98,'CAJA DE AHORROS Y M.P. DE AVILA','2094'),
  (99,'CAJA DE AHORROS Y M.P. DE CORDOBA','2024'),
  (100,'CAJA DE AHORROS Y M.P. DE EXTREMADURA','2099'),
  (101,'CAJA DE AHORROS Y M.P. DE GIPUZKOA Y SAN SEBASTIAN','2101'),
  (102,'CAJA DE AHORROS Y M.P. DE LAS BALEARES','2051'),
  (103,'CAJA DE AHORROS Y M.P. DE MADRID','2038'),
  (104,'CAJA DE AHORROS Y M.P. DE NAVARRA','2054'),
  (105,'CAJA DE AHORROS Y M.P. DE ONTINYENT','2045'),
  (106,'CAJA DE AHORROS Y M.P. DE SEGOVIA','2069'),
  (107,'CAJA DE AHORROS Y M.P. DE ZARAGOZA, ARAGON Y RIOJA','2085'),
  (108,'CAJA DE AHORROS Y PENSIONES DE BARCELONA','2100'),
  (109,'CAJA ESPAÑA DE INVERSIONES, CAJA DE AHORROS Y M.P.','2096'),
  (110,'CAJA GENERAL DE AHORROS DE CANARIAS','2065'),
  (111,'CAJA GENERAL DE AHORROS DE GRANADA','2031'),
  (112,'CAJA INSULAR DE AHORROS DE CANARIAS','2052'),
  (113,'CAJA PROVINCIAL DE AHORROS DE JAEN','2092'),
  (114,'COLONYA - CAIXA D''ESTALVIS DE POLLENSA','2056'),
  (115,'CONFEDERACION ESPAÑOLA DE CAJAS DE AHORROS','2000'),
  (116,'M.P. Y CAJA DE AHORROS DE HUELVA Y SEVILLA','2098'),
  (117,'M.P. Y CAJA GENERAL AHORROS DE BADAJOZ','2010'),
  (118,'M.P.C.A. RONDA, CADIZ, ALMERIA, MALAGA Y ANTEQUERA','2103'),
  (119,'CAIXA DE C. DELS ENGINYERS-C.C. INGENIEROS, S.C.C','3025'),
  (120,'CAIXA DELS ADVOCATS-CAJA DE LOS ABOGADOS, S.C.C.','3171'),
  (121,'CAIXA POPULAR-CAIXA RURAL, S.C.C.V.','3159'),
  (122,'CAIXA R. ALBALAT DELS SORELLS, C.C.V.','3186'),
  (123,'CAIXA R. ALTEA, C.C.V.','3045'),
  (124,'CAIXA R. BENICARLO, S.C.C.V.','3162'),
  (125,'CAIXA R. D''ALGEMESI, S.C.V.C.','3117'),
  (126,'CAIXA R. DE BALEARS, S.C.C.','3147'),
  (127,'CAIXA R. DE CALLOSA D''EN SARRIA, C.C.V.','3105'),
  (128,'CAIXA R. DE L''ALCUDIA, S.C.V.C.','3096'),
  (129,'CAIXA R. DE TURIS, C.C.V.','3123'),
  (130,'CAIXA R. GALEGA, S.C.C.L.G.','3070'),
  (131,'CAIXA R. LA VALL ''S. ISIDRO'', S.C.C.V.','3111'),
  (132,'CAIXA R. S. VICENT FERRER DE LA VALL D''UIXO,C.C.V.','3102'),
  (133,'CAIXA R. VINAROS, S.C.C.V.','3174'),
  (134,'CAIXA R.S.JOSEP DE VILAVELLA, S.C.C.V.','3160'),
  (135,'CAIXA RURAL LES COVES DE VINROMA, S.C.C.V.','3166'),
  (136,'CAIXA RURAL TORRENT C.C.V.','3118'),
  (137,'CAJA CAMINOS, S.C.C.','3172'),
  (138,'CAJA CAMPO, CAJA RURAL, S.C.C.','3094'),
  (139,'CAJA DE ARQUITECTOS S.C.C.','3183'),
  (140,'CAJA DE CREDITO DE ALCOY, C.C.V. (EN LIQUIDACION)','3184'),
  (141,'CAJA DE CREDITO DE PETREL, CAJA RURAL, C.C.V.','3029'),
  (142,'CAJA ESCOLAR DE FOMENTO, S.C.C.','3146'),
  (143,'CAJA LABORAL POPULAR C.C.','3035'),
  (144,'CAJA R. ''NUESTRA MADRE DEL SOL'', S.C.A.C.','3115'),
  (145,'CAJA R. ARAGONESA Y DE LOS PIRINEOS, S.C.C.','3189'),
  (146,'CAJA R. CASTELLON S. ISIDRO, S.C.C.V.','3114'),
  (147,'CAJA R. CATOLICO AGRARIA, S.C.C.V.','3110'),
  (148,'CAJA R. CENTRAL, S.C.C.','3005'),
  (149,'CAJA R. COMARCAL DE MOTA DEL CUERVO, S.C.L.C.A.','3116'),
  (150,'CAJA R. DE ALBACETE, S.C.C.','3056'),
  (151,'CAJA R. DE ALBAL, C.C.V.','3150'),
  (152,'CAJA R. DE ALGINET, S.C.C.V.','3179'),
  (153,'CAJA R. DE ALMENDRALEJO, S.C.C.','3001'),
  (154,'CAJA R. DE ARAGON, S.C.C.','3021'),
  (155,'CAJA R. DE ASTURIAS, S.C.C.','3059'),
  (156,'CAJA R. DE BETXI, S.C.C.V.','3138'),
  (157,'CAJA R. DE BURGOS,S.C.C.','3060'),
  (158,'CAJA R. DE CANARIAS, S.C.C.','3177'),
  (159,'CAJA R. DE CASAS IBAÑEZ, S.C. - C.C.A.,','3127'),
  (160,'CAJA R. DE CASINOS S.C.C.V.','3137'),
  (161,'CAJA R. DE CAÑETE TORRES NTRA.SRA.DEL CAMPO,S.C.A.','3104'),
  (162,'CAJA R. DE CHESTE, S.C.C.','3121'),
  (163,'CAJA R. DE CIUDAD REAL, S.C.C.','3062'),
  (164,'CAJA R. DE CORDOBA, S.C.C.','3063'),
  (165,'CAJA R. DE CUENCA, S.C.C.','3064'),
  (166,'CAJA R. DE EXTREMADURA, S.C.C.','3009'),
  (167,'CAJA R. DE FUENTEPELAYO, S.C.C.','3022'),
  (168,'CAJA R. DE GIJON, C.C','3007'),
  (169,'CAJA R. DE GRANADA, S.C.C.','3023'),
  (170,'CAJA R. DE GUISSONA, S.C.C.','3140'),
  (171,'CAJA R. DE JAEN, S.C.C.','3067'),
  (172,'CAJA R. DE LA CARLOTA, S.C.A.C.L. (EN LIQUIDACION)','3154'),
  (173,'CAJA R. DE LA RODA, S.C.C. DE CASTILLA LA MANCHA','3128'),
  (174,'CAJA R. DE NAVARRA, S.C.C.','3008'),
  (175,'CAJA R. DE SALAMANCA, S.C.C.','3016'),
  (176,'CAJA R. DE SEGOVIA, C.C.','3078'),
  (177,'CAJA R. DE SORIA, S.C.C.','3017'),
  (178,'CAJA R. DE TENERIFE, S.C.C.','3076'),
  (179,'CAJA R. DE TERUEL, S.C.C.','3080'),
  (180,'CAJA R. DE TOLEDO, S.C.C.','3081'),
  (181,'CAJA R. DE UTRERA, S.C.A.L.C.','3020'),
  (182,'CAJA R. DE VILLAMALEA, S.C.C.A. CASTILLA-LA MANCHA','3144'),
  (183,'CAJA R. DE VILLAR C.C.V.','3152'),
  (184,'CAJA R. DE ZAMORA, C.C.','3085'),
  (185,'CAJA R. DEL DUERO, S.C.C.L.','3083'),
  (186,'CAJA R. DEL MEDITERRANEO, RURALCAJA, S.C.C.','3082'),
  (187,'CAJA R. DEL SUR, S. COOP. DE CREDITO','3187'),
  (188,'CAJA R. LA JUNQUERA DE CHILCHES, S.C.C.V.','3157'),
  (189,'CAJA R. NTRA. SRA. DE GUADALUPE, S.C.C.A.','3089'),
  (190,'CAJA R. NTRA. SRA. DEL ROSARIO, S.C.A.C.','3098'),
  (191,'CAJA R. NTRA. SRA. LA ESPERANZA DE ONDA, S.C.C.V.','3134'),
  (192,'CAJA R. S. FORTUNATO, S.C.C.C.L.','3161'),
  (193,'CAJA R. S. ISIDRO DE VILAFAMES, S.C.C.V.','3165'),
  (194,'CAJA R. S. JAIME ALQUERIAS NIÑO PERDIDO S.C.C.V.','3119'),
  (195,'CAJA R. S. JOSE DE ALCORA S.C.C.V.','3113'),
  (196,'CAJA R. S. JOSE DE ALMASSORA, S.C.C.V.','3130'),
  (197,'CAJA R. S. JOSE DE BURRIANA, S.C.C.V.','3112'),
  (198,'CAJA R. S. JOSE DE NULES S.C.C.V.','3135'),
  (199,'CAJA R. S. ROQUE DE ALMENARA S.C.C.V.','3095'),
  (200,'CAJA R.R.S.AGUSTIN DE FUENTE ALAMO M., S.C.C.','3018'),
  (201,'CAJAMAR CAJA RURAL, S.C.C.','3058'),
  (202,'CREDIT VALENCIA, C.R.C.C.V.','3188'),
  (203,'IPAR KUTXA RURAL, S.C.C.','3084');

COMMIT;

#
# Data for the `app_param` table  (LIMIT 0,500)
#

INSERT INTO `app_param` (`name`, `value`) VALUES 
  ('ACC_DEFAULT_CASH_ACC','570'),
  ('ACC_DEFAULT_CHARGED_RET_ACC','47501'),
  ('ACC_DEFAULT_CHARGED_VAT_ACC','47700'),
  ('ACC_DEFAULT_COMPANY_SOC_INS_ACC','642'),
  ('ACC_DEFAULT_DEBT_INTEREST_ACC','662'),
  ('ACC_DEFAULT_FINAN_EXPENSES_ACC','669'),
  ('ACC_DEFAULT_PAID_RET_ACC','47300'),
  ('ACC_DEFAULT_PAID_VAT_ACC','47200'),
  ('ACC_DEFAULT_PENDING_SALARY_ACC','465'),
  ('ACC_DEFAULT_PURCHASE_ACC','600'),
  ('ACC_DEFAULT_SALARY_ACC','640'),
  ('ACC_DEFAULT_SALES_ACC','700'),
  ('ACC_DEFAULT_SOCIAL_INSURANCE_ACC','476'),
  ('APP_PRINT_HEADER_PARAM','false'),
  ('APP_PRINT_RECORD_DATA_PARAM','false');

COMMIT;

#
# Data for the `scope` table  (LIMIT 0,500)
#

INSERT INTO `scope` (`id`, `description`) VALUES 
  (1,'GENERAL');

COMMIT;

#
# Data for the `account` table  (LIMIT 0,500)
#

INSERT INTO `account` (`id`, `description`, `alias`, `entryEnabled`) VALUES 
  ('1','FINANCIACIÓN BÁSICA',NULL,0),
  ('10','CAPITAL.',NULL,0),
  ('100','Capital social.',NULL,1),
  ('101','Fondo social.',NULL,1),
  ('102','Capital.',NULL,1),
  ('103','Socios por desembolsos no exigidos..',NULL,0),
  ('10300','Socios por desembolsos no exigidos, capital social.',NULL,1),
  ('10304','Socios por desembolsos no exigidos, capital pendiente de inscripción.',NULL,1),
  ('104','Socios por aportaciones no dinerarias pendientes..',NULL,0),
  ('10400','Socios por aportaciones no dinerarias pendientes, capital social.',NULL,1),
  ('10404','Socios por aportaciones no dinerarias pendientes, capital pendiente de inscripción.',NULL,1),
  ('108','Acciones o participaciones propias en situaciones especiales.',NULL,1),
  ('109','Acciones o participaciones propias para reducción de capital.',NULL,1),
  ('11','RESERVAS.',NULL,0),
  ('110','Prima de emisión o asunción.',NULL,1),
  ('111','Patrimonio neto por emisión de instrumentos financieros compuestos.',NULL,0),
  ('11100','Patrimonio neto por emisión de instrumentos financieros compuestos.',NULL,1),
  ('11101','Resto de instrumentos de patrimonio neto.',NULL,1),
  ('112','Reserva legal.',NULL,1),
  ('113','Reservas voluntarias.',NULL,1),
  ('114','Reservas especiales.',NULL,0),
  ('11400','Reservas para acciones o participaciones de la sociedad dominante.',NULL,1),
  ('11401','Reservas estatutarias.',NULL,1),
  ('11402','Reserva por capital amortizado.',NULL,1),
  ('11403','Reserva por fondo de comercio.',NULL,1),
  ('11404','Reservas por acciones propias aceptadas en garantía.',NULL,1),
  ('115','Reservas por pérdidas y ganancias actuariales y otros ajustes.',NULL,1),
  ('118','Aportaciones de socios o propietarios.',NULL,1),
  ('119','Diferencias por ajuste del capital a euros.',NULL,1),
  ('12','RESULTADOS PENDIENTES DE APLICACIÓN.',NULL,0),
  ('120','Remanente.',NULL,1),
  ('121','Resultados negativos de ejercicios anteriores.',NULL,1),
  ('129','Resultados del ejercicio.',NULL,1),
  ('13','SUBVENCIONES, DONACIONES Y AJUSTES POR CAMBIOS DE VALOR.',NULL,0),
  ('130','Subvenciones oficiales de capital.',NULL,1),
  ('131','Donaciones y legados de capital.',NULL,1),
  ('132','Otras subvenciones, donaciones y legados.',NULL,1),
  ('133','Ajustes por valoración en instrumentos financieros.',NULL,1),
  ('134','Operaciones de cobertura.',NULL,0),
  ('13400','Cobertura de flujos de efectivo.',NULL,1),
  ('13401','Cobertura de una inversión neta en un negocio en el extranjero.',NULL,1),
  ('135','Diferencias de conversión.',NULL,1),
  ('136','Ajustes por valoración en activos no corrientes y grupos enajenables de elementos mantenidos para la venta.',NULL,1),
  ('137','Ingresos fiscales a distribuir en varios ejercicios.',NULL,0),
  ('13700','Ingresos fiscales por diferencias permanentes a distribuir en varios ejercicios.',NULL,1),
  ('13701','Ingresos fiscales por deducciones y bonificaciones a distribuir en varios ejercicios.',NULL,1),
  ('14','PROVISIONES.',NULL,0),
  ('140','Provisión para retribuciones y otras prestaciones al personal.',NULL,1),
  ('141','Provisión para impuestos.',NULL,1),
  ('142','Provisión para otras responsabilidades.',NULL,1),
  ('143','Provisión por desmantelamiento, retiro o rehabilitación del inmovilizado.',NULL,1),
  ('145','Provisión para actuaciones medioambientales.',NULL,1),
  ('146','Provisión para reestructuraciones.',NULL,1),
  ('147','Provisiones por transacciones con pagos basados en instrumentos de patrimonio.',NULL,1),
  ('15','DEUDAS A LARGO PLAZO CON CARACTERÍSTICAS ESPECIALES.',NULL,0),
  ('150','Acciones o participaciones a largo plazo contabilizadas como pasivo.',NULL,1),
  ('153','Desembolsos no exigidos por acciones o participaciones contabilizadas como pasivo.',NULL,1),
  ('154','Aportaciones no dinerarias pendientes por acciones o participaciones contabilizadas como pasivo.',NULL,1),
  ('16','DEUDAS A LARGO PLAZO CON PARTES VINCULADAS.',NULL,0),
  ('160','Deudas a largo plazo con entidades de crédito vinculadas.',NULL,1),
  ('161','Proveedores de inmovilizado a largo plazo, partes vinculadas.',NULL,1),
  ('162','Otras deudas a largo plazo con partes vinculadas.',NULL,1),
  ('163','Otras deudas a largo plazo con partes vinculadas.',NULL,0),
  ('16303','Otras deudas a largo plazo empresas del grupo.',NULL,1),
  ('16304','Otras deudas a largo plazo empresas asociadas.',NULL,1),
  ('16305','Otras deudas a largo plazo con otras partes vinculadas.',NULL,1),
  ('17','DEUDAS A LARGO PLAZO POR PRÉSTAMOS RECIBIDOS Y OTROS CONCEPTOS.',NULL,0),
  ('170','Deudas a largo plazo con entidades de crédito.',NULL,1),
  ('171','Deudas a largo plazo.',NULL,1),
  ('172','Deudas a largo plazo transformables en subvenciones, donaciones y legados.',NULL,1),
  ('173','Proveedores de inmovilizado a largo plazo.',NULL,1),
  ('174','Acreedores de arrendamiento financiero a largo plazo.',NULL,1),
  ('175','Efectos a pagar a largo plazo.',NULL,1),
  ('176','Pasivos por derivados financieros a largo plazo.',NULL,0),
  ('17605','Pasivos por derivados financieros a largo plazo, cartera de negociación.',NULL,1),
  ('17608','Pasivos por derivados financieros a largo plazo, instrumentos de cobertura.',NULL,1),
  ('177','Obligaciones y bonos.',NULL,1),
  ('178','Obligaciones y bonos convertibles.',NULL,1),
  ('179','Deudas representadas en otros valores negociables.',NULL,1),
  ('18','PASIVOS POR FIANZAS Y GARANTÍAS Y OTROS CONCEPTOS A LARGO PLAZO.',NULL,0),
  ('180','Fianzas recibidas a largo plazo.',NULL,1),
  ('181','Anticipos recibidos por ventas o prestaciones de servicios a largo plazo.',NULL,1),
  ('185','Depósitos recibidos a largo plazo.',NULL,1),
  ('189','Garantías financieras a largo plazo.',NULL,1),
  ('19','SITUACIONES TRANSITORIAS DE FINANCIACIÓN.',NULL,0),
  ('190','Acciones o participaciones emitidas.',NULL,1),
  ('192','Suscriptores de acciones.',NULL,1),
  ('194','Capital emitido pendiente de inscripción.',NULL,1),
  ('195','Acciones o participaciones emitidas consideradas como pasivos financieros.',NULL,1),
  ('197','Suscriptores de acciones consideradas como pasivos financieros.',NULL,1),
  ('199','Acciones o participaciones emitidas consideradas como pasivos financieros pendientes de inscripción.',NULL,1),
  ('2','ACTIVO NO CORRIENTE',NULL,0),
  ('20','INMOVILIZACIONES INTANGIBLES.',NULL,0),
  ('200','Gastos de investigación.',NULL,1),
  ('201','Desarrollo.',NULL,1),
  ('202','Concesiones administrativas.',NULL,1),
  ('203','Propiedad industrial.',NULL,1),
  ('204','Fondo de comercio.',NULL,1),
  ('205','Derechos de traspaso.',NULL,1),
  ('206','Aplicaciones informáticas.',NULL,1),
  ('209','Anticipos para inmovilizaciones intangibles.',NULL,1),
  ('21','INMOVILIZACIONES MATERIALES.',NULL,0),
  ('210','Terrenos y bienes naturales.',NULL,1),
  ('211','Construcciones .',NULL,1),
  ('212','Instalaciones técnicas.',NULL,1),
  ('213','Maquinaria.',NULL,1),
  ('214','Utillaje.',NULL,1),
  ('215','Otras instalaciones.',NULL,1),
  ('216','Mobiliario.',NULL,1),
  ('217','Equipos para procesos de información.',NULL,1),
  ('218','Elementos de transporte.',NULL,1),
  ('219','Otro inmovilizado material.',NULL,1),
  ('22','INVERSIONES INMOBILIARIAS.',NULL,0),
  ('220','Inversiones en terrenos y bienes naturales.',NULL,1),
  ('221','Inversiones en construcciones.',NULL,1),
  ('23','INMOVILIZACIONES MATERIALES EN CURSO.',NULL,0),
  ('230','Adaptación de terrenos y bienes naturales.',NULL,1),
  ('231','Construcciones en curso.',NULL,1),
  ('232','Instalaciones técnicas en montaje.',NULL,1),
  ('233','Maquinaria en montaje.',NULL,1),
  ('237','Equipos para procesos de información en montaje.',NULL,1),
  ('239','Anticipos para inmovilizaciones materiales.',NULL,1),
  ('24','INVERSIONES FINANCIERAS A LARGO PLAZO EN PARTES VINCULADAS.',NULL,0),
  ('240','Participaciones a largo plazo en partes vinculadas.',NULL,1),
  ('241','Valores representativos de deuda a largo plazo de partes vinculadas.',NULL,1),
  ('242','Créditos a largo plazo a partes vinculadas.',NULL,1),
  ('249','Desembolsos pendientes sobre participaciones a largo plazo en partes vinculadas.',NULL,1),
  ('25','OTRAS INVERSIONES FINANCIERAS A LARGO PLAZO.',NULL,0),
  ('250','Inversiones financieras a largo plazo en instrumentos de patrimonio.',NULL,1),
  ('251','Valores representativos de deuda a largo plazo.',NULL,1),
  ('252','Créditos a largo plazo.',NULL,1),
  ('253','Créditos a largo plazo por enajenación de inmovilizado.',NULL,1),
  ('254','Créditos a largo plazo al personal.',NULL,1),
  ('255','Activos por derivados financieros a largo plazo.',NULL,1),
  ('257','Activos por retribuciones a largo plazo de prestación definida.',NULL,1),
  ('258','Imposiciones a largo plazo.',NULL,1),
  ('259','Desembolsos pendientes sobre participaciones en el patrimonio neto a largo plazo.',NULL,1),
  ('26','FIANZAS Y DEPÓSITOS CONSTITUIDOS A LARGO PLAZO.',NULL,0),
  ('260','Fianzas constituidas a largo plazo.',NULL,1),
  ('265','Depósitos constituidos a largo plazo.',NULL,1),
  ('28','AMORTIZACIÓN ACUMULADA DEL INMOVILIZADO.',NULL,0),
  ('280','Amortización acumulada del inmovilizado intangible.',NULL,1),
  ('281','Amortización acumulada del inmovilizado material.',NULL,1),
  ('282','Amortización acumulada de las inversiones inmobiliarias.',NULL,1),
  ('29','DETERIORO DE VALOR DE ACTIVOS NO CORRIENTES.',NULL,0),
  ('290','Deterioro de valor del inmovilizado intangible.',NULL,1),
  ('291','Deterioro de valor del inmovilizado material.',NULL,1),
  ('292','Deterioro de valor de las inversiones inmobiliarias.',NULL,1),
  ('293','Deterioro de valor de participaciones a largo plazo en partes vinculadas.',NULL,1),
  ('294','Deterioro de valor de valores representativos de deuda a largo plazo de partes vinculadas.',NULL,1),
  ('295','Deterioro de valor de créditos a largo plazo a partes vinculadas.',NULL,1),
  ('297','Deterioro de valor de valores representativos de deuda a largo plazo.',NULL,1),
  ('298','Deterioro de valor de créditos a largo plazo.',NULL,1),
  ('3','EXISTENCIAS',NULL,0),
  ('30','COMERCIALES.',NULL,0),
  ('300','Mercaderías A.',NULL,1),
  ('301','Mercaderías B.',NULL,1),
  ('31','MATERIAS PRIMAS.',NULL,0),
  ('310','Materias primas A.',NULL,1),
  ('311','Materias primas B.',NULL,1),
  ('32','OTROS APROVISIONAMIENTOS.',NULL,0),
  ('320','Elementos conjuntos incorporables.',NULL,1),
  ('321','Combustibles.',NULL,1),
  ('322','Repuestos.',NULL,1),
  ('325','Materiales diversos.',NULL,1),
  ('326','Embalajes.',NULL,1),
  ('327','Envases.',NULL,1),
  ('328','Material de oficina.',NULL,1),
  ('33','PRODUCTOS EN CURSO.',NULL,0),
  ('330','Productos en curso A.',NULL,1),
  ('331','Productos en curso B.',NULL,1),
  ('34','PRODUCTOS SEMITERMINADOS.',NULL,0),
  ('340','Productos semiterminados A.',NULL,1),
  ('341','Productos semiterminados B.',NULL,1),
  ('35','PRODUCTOS TERMINADOS.',NULL,0),
  ('350','Productos terminados A.',NULL,1),
  ('351','Productos terminados B.',NULL,1),
  ('36','SUBPRODUCTOS, RESIDUOS Y MATERIALES RECUPERADOS.',NULL,0),
  ('360','Subproductos A.',NULL,1),
  ('361','Subproductos B.',NULL,1),
  ('365','Residuos A.',NULL,1),
  ('366','Residuos B.',NULL,1),
  ('368','Materiales recuperados A.',NULL,1),
  ('369','Materiales recuperados B.',NULL,1),
  ('39','DETERIORO DE VALOR DE LAS EXISTENCIAS.',NULL,0),
  ('390','Deterioro de valor de las mercaderías.',NULL,1),
  ('391','Deterioro de valor de las materias primas.',NULL,1),
  ('392','Deterioro de valor de otros aprovisionamientos.',NULL,1),
  ('393','Deterioro de valor de los productos en curso.',NULL,1),
  ('394','Deterioro de valor de los productos semiterminados.',NULL,1),
  ('395','Deterioro de valor de los productos terminados.',NULL,1),
  ('396','Deterioro de valor de los subproductos, residuos y materiales recuperados.',NULL,1),
  ('4','ACREEDORES Y DEUDORES POR OPERACIONES COMERCIALES',NULL,0),
  ('40','PROVEEDORES.',NULL,0),
  ('400','Proveedores.',NULL,0),
  ('40000','Proveedores.',NULL,0),
  ('401','Proveedores, efectos comerciales a pagar.',NULL,1),
  ('403','Proveedores, empresas del grupo.',NULL,1),
  ('404','Proveedores, empresas asociadas.',NULL,1),
  ('405','Proveedores, otras partes vinculadas.',NULL,1),
  ('406','Envases y embalajes a devolver a proveedores.',NULL,1),
  ('407','Anticipos a proveedores.',NULL,1),
  ('41','ACREEDORES VARIOS.',NULL,0),
  ('410','Acreedores por prestaciones de servicios.',NULL,0),
  ('41000','Acreedores por prestaciones de servicios.',NULL,0),
  ('411','Acreedores, efectos comerciales a pagar.',NULL,1),
  ('419','Acreedores por operaciones en común.',NULL,1),
  ('43','CLIENTES.',NULL,0),
  ('430','Clientes.',NULL,0),
  ('43000','Clientes.',NULL,0),
  ('431','Clientes, efectos comerciales a cobrar.',NULL,1),
  ('432','Clientes operaciones de factoring.',NULL,1),
  ('433','Clientes, empresas del grupo.',NULL,1),
  ('434','Clientes, empresas asociadas.',NULL,1),
  ('435','Clientes, otras partes vinculadas.',NULL,1),
  ('436','Clientes de dudoso cobro.',NULL,1),
  ('437','Envases y embalajes a devolver por clientes.',NULL,1),
  ('438','Anticipos de clientes.',NULL,1),
  ('44','DEUDORES VARIOS.',NULL,0),
  ('440','Deudores.',NULL,1),
  ('441','Deudores, efectos comerciales a cobrar.',NULL,1),
  ('446','Deudores de dudoso cobro.',NULL,1),
  ('449','Deudores por operaciones en común.',NULL,1),
  ('46','PERSONAL.',NULL,0),
  ('460','Anticipos de remuneraciones.',NULL,1),
  ('465','Remuneraciones pendientes de pago.',NULL,1),
  ('466','Remuneraciones mediante sistemas de aportación definida pendientes de pago.',NULL,1),
  ('47','ADMINISTRACIONES PÚBLICAS.',NULL,0),
  ('470','Hacienda Pública deudora por diversos conceptos.',NULL,0),
  ('47000','Hacienda Pública, deudora por IVA.',NULL,1),
  ('47008','Hacienda Pública, deudora por subvenciones concedidas.',NULL,1),
  ('47009','Hacienda Pública, deudora por devolución de impuestos.',NULL,1),
  ('471','Organismos de la Seguridad Social, deudores.',NULL,1),
  ('472','Hacienda Pública, IVA soportado.',NULL,0),
  ('47200','Hacienda Pública, IVA soportado.',NULL,1),
  ('473','Hacienda Pública, retenciones y pagos a cuenta.',NULL,0),
  ('47300','Hacienda Pública, retenciones y pagos a cuenta.',NULL,1),
  ('474','Activos por impuesto diferido.',NULL,0),
  ('47400','Activos por diferencias temporarias deducibles.',NULL,1),
  ('47402','Derechos por deducciones y bonificaciones pendientes de aplicar.',NULL,1),
  ('47405','Crédito por pérdidas a compensar del ejercicio.',NULL,1),
  ('475','Hacienda Pública acreedora por conceptos fiscales.',NULL,0),
  ('47500','Hacienda Pública, acreedora por IVA.',NULL,1),
  ('47501','Hacienda Pública, acreedora por retenciones practicadas.',NULL,1),
  ('47502','Hacienda Pública, acreedora por impuesto sobre sociedades.',NULL,1),
  ('47508','Hacienda Pública, acreedora por subvenciones a reintegrar.',NULL,1),
  ('476','Organismos de la Seguridad Social, acreedores.',NULL,1),
  ('477','Hacienda Pública, IVA repercutido.',NULL,0),
  ('47700','Hacienda Pública, IVA repercutido.',NULL,1),
  ('479','Pasivos por diferencias temporarias imponibles.',NULL,1),
  ('48','AJUSTES POR PERIODIFICACIÓN.',NULL,0),
  ('480','Gastos anticipados.',NULL,1),
  ('485','Ingresos anticipados.',NULL,1),
  ('49','DETERIORO DE VALOR DE CRÉDITOS COMERCIALES Y PROVISIONES A CORTO PLAZO.',NULL,0),
  ('490','Deterioro de valor de créditos por operaciones comerciales.',NULL,1),
  ('493','Deterioro de valor de créditos por operaciones comerciales con partes vinculadas.',NULL,1),
  ('499','Provisiones por operaciones comerciales.',NULL,0),
  ('49904','Provisión para contratos onerosos.',NULL,1),
  ('49909','Provisión para otras operaciones comerciales.',NULL,1),
  ('5','CUENTAS FINANCIERAS',NULL,0),
  ('50','EMPRÉSTITOS, DEUDAS CON CARACTERÍSTICAS ESPECIALES Y OTRAS EMISIONES ANÁLOGAS A CORTO PLAZO.',NULL,0),
  ('500','Obligaciones y bonos a corto plazo.',NULL,1),
  ('501','Obligaciones y bonos convertibles a corto plazo.',NULL,1),
  ('502','Acciones o participaciones a corto plazo contabilizadas como pasivo.',NULL,1),
  ('505','Deudas representadas en otros valores negociables a corto plazo.',NULL,1),
  ('506','Intereses de empréstitos y otras emisiones análogas.',NULL,1),
  ('507','Dividendos de emisiones contabilizadas como pasivo.',NULL,1),
  ('509','Valores negociables amortizados.',NULL,1),
  ('51','DEUDAS A CORTO PLAZO CON PARTES VINCULADAS.',NULL,0),
  ('510','Deudas a corto plazo con entidades de crédito vinculadas.',NULL,1),
  ('511','Proveedores de inmovilizado a corto plazo, partes vinculadas.',NULL,1),
  ('512','Acreedores por arrendamiento financiero a corto plazo, partes vinculadas.',NULL,1),
  ('513','Otras deudas a corto plazo con partes vinculadas.',NULL,1),
  ('514','Intereses a corto plazo de deudas con partes vinculadas.',NULL,1),
  ('52','DEUDAS A CORTO PLAZO POR PRÉSTAMOS RECIBIDOS Y OTROS CONCEPTOS.',NULL,0),
  ('520','Deudas a corto plazo con entidades de crédito.',NULL,0),
  ('52000','Préstamos a corto plazo de entidades de crédito.',NULL,0),
  ('52001','Deudas a corto plazo por crédito dispuesto.',NULL,1),
  ('52008','Deudas por efectos descontados.',NULL,1),
  ('52009','Deudas por operaciones de factoring.',NULL,1),
  ('521','Deudas a corto plazo.',NULL,1),
  ('522','Deudas a corto plazo transformables en subvenciones, donaciones y legados.',NULL,1),
  ('523','Proveedores de inmovilizado a corto plazo.',NULL,0),
  ('52300','Proveedores de inmovilizado a corto plazo.',NULL,0),
  ('525','Efectos a pagar a corto plazo.',NULL,1),
  ('526','Dividendo activo a pagar.',NULL,1),
  ('527','Intereses a corto plazo de deudas con entidades de crédito.',NULL,1),
  ('528','Intereses a corto plazo de deudas.',NULL,1),
  ('529','Provisiones a corto plazo.',NULL,1),
  ('53','INVERSIONES FINANCIERAS A CORTO PLAZO EN PARTES VINCULADAS.',NULL,0),
  ('530','Participaciones a corto plazo en partes vinculadas.',NULL,0),
  ('53003','Participaciones a corto plazo en empresas del grupo.',NULL,1),
  ('53004','Participaciones a corto plazo en empresas del asociadas.',NULL,1),
  ('53005','Participaciones a corto plazo, en otras partes vinculadas.',NULL,1),
  ('531','Valores representativos de deuda a corto plazo de partes vinculadas.',NULL,1),
  ('532','Créditos a corto plazo a partes vinculadas.',NULL,1),
  ('533','Intereses a corto plazo de inversiones financieras en partes vinculadas.',NULL,1),
  ('534','Intereses a corto plazo de créditos a partes vinculadas.',NULL,1),
  ('535','Dividendo a cobrar de inversiones financieras en partes vinculadas.',NULL,1),
  ('539','Desembolsos pendientes sobre participaciones a corto plazo de partes vinculadas.',NULL,1),
  ('54','OTRAS INVERSIONES FINANCIERAS A CORTO PLAZO.',NULL,0),
  ('540','Inversiones financieras temporales en instrumentos de patrimonio.',NULL,1),
  ('541','Valores representativos de deuda a corto plazo.',NULL,1),
  ('542','Créditos a corto plazo.',NULL,1),
  ('543','Créditos a corto plazo por enajenación de inmovilizado.',NULL,1),
  ('544','Créditos a corto plazo al personal.',NULL,1),
  ('545','Dividendo a cobrar.',NULL,1),
  ('546','Intereses a corto plazo de valores representativos de deuda.',NULL,1),
  ('547','Intereses a corto plazo de créditos.',NULL,1),
  ('548','Imposiciones a corto plazo.',NULL,1),
  ('549','Desembolsos pendientes sobre instrumentos de patrimonio a corto plazo.',NULL,1),
  ('55','OTRAS CUENTAS NO BANCARIAS.',NULL,0),
  ('550','Titular de la explotación.',NULL,1),
  ('551','Cuenta corriente con socios administradores.',NULL,1),
  ('552','Cuenta corriente con otras personas y entidades vinculadas.',NULL,1),
  ('553','Cuentas corrientes en fusiones y escisiones.',NULL,0),
  ('55300','Socios de sociedad disuelta.',NULL,1),
  ('55301','Socios, cuenta de fusión.',NULL,1),
  ('55302','Socios de sociedad escindida.',NULL,1),
  ('55303','Socios, cuenta de escisión.',NULL,1),
  ('554','Cuenta corriente con uniones temporales de empresas y comunidades de bienes.',NULL,1),
  ('555','Partidas pendientes de aplicación.',NULL,1),
  ('556','Desembolsos exigidos sobre participaciones en el patrimonio neto.',NULL,1),
  ('557','Dividendo activo a cuenta.',NULL,1),
  ('558','Socios por desembolsos exigidos.',NULL,0),
  ('55800','Socios por desembolsos exigidos sobre acciones o participaciones ordinarias.',NULL,1),
  ('55805','Socios por desembolsos exigidos sobre acciones o participaciones consideradas como pasivos financieros.',NULL,1),
  ('559','Derivados financieros a corto plazo.',NULL,0),
  ('55900','Activos por derivados financieros a corto plazo, cartera de negociación.',NULL,1),
  ('55903','Activos de derivados financieros a corto plazo, instrumentos de cobertura.',NULL,1),
  ('55905','Pasivos por derivados financieros a corto plazo, cartera de negociación.',NULL,1),
  ('55908','Pasivos por derivados financieros a corto plazo, instrumentos de cobertura.',NULL,1),
  ('56','FIANZAS Y DEPÓSITOS RECIBIDOS Y CONSTITUIDOS A CORTO PLAZO Y AJUSTES POR PERIODIFICACIÓN.',NULL,0),
  ('560','Fianzas recibidas a corto plazo.',NULL,1),
  ('561','Depósitos recibidos a corto plazo.',NULL,1),
  ('565','Fianzas constituidas a corto plazo.',NULL,1),
  ('566','Depósitos constituidos a corto plazo.',NULL,1),
  ('567','Intereses pagados por anticipado.',NULL,1),
  ('568','Intereses cobrados por anticipado.',NULL,1),
  ('569','Garantías financieras a corto plazo.',NULL,1),
  ('57','TESORERÍA.',NULL,0),
  ('570','Caja, euros.',NULL,1),
  ('571','Caja, moneda extranjera.',NULL,1),
  ('572','Bancos e instituciones de crédito c/c vista, euros.',NULL,0),
  ('57200','Bancos e instituciones de crédito c/c vista, euros.',NULL,0),
  ('573','Bancos e instituciones de crédito c/c vista, moneda extranjera.',NULL,1),
  ('574','Bancos e instituciones de crédito, cuentas de ahorro, euros.',NULL,1),
  ('575','Bancos e instituciones de crédito, cuentas de ahorro, moneda extranjera.',NULL,1),
  ('576','Inversiones a corto plazo de gran liquidez.',NULL,1),
  ('58','ACTIVOS NO CORRIENTES MANTENIDOS PARA LA VENTA Y ACTIVOS Y PASIVOS ASOCIADOS.',NULL,0),
  ('580','Inmovilizado.',NULL,1),
  ('581','Inversiones con personas y entidades vinculadas.',NULL,1),
  ('582','Inversiones financieras.',NULL,1),
  ('583','Existencias, deudores comerciales y otras cuentas a cobrar.',NULL,1),
  ('584','Otros activos.',NULL,1),
  ('585','Provisiones.',NULL,1),
  ('586','Deudas con características especiales.',NULL,1),
  ('587','Deudas con personas y entidades vinculadas.',NULL,1),
  ('588','Acreedores comerciales y otras cuentas a pagar.',NULL,1),
  ('589','Otros pasivos.',NULL,1),
  ('59','DETERIORO DEL VALOR DE INVERSIONES FINANCIERAS A CORTO PLAZO Y DE ACTIVOS NO CORRIENTES MANTENIDOS PARA LA VENTA.',NULL,0),
  ('593','Deterioro de valor de participaciones a corto plazo en partes vinculadas.',NULL,1),
  ('594','Deterioro del valor de valores representativos de deuda a corto plazo de partes vinculadas.',NULL,1),
  ('595','Deterioro del valor de créditos a corto plazo a partes vinculadas.',NULL,1),
  ('597','Deterioro de valor de valores representativos de deuda a corto plazo.',NULL,1),
  ('598','Deterioro de valor de créditos a corto plazo.',NULL,1),
  ('599','Deterioro de valor de activos no corrientes mantenidos para la venta.',NULL,1),
  ('6','COMPRAS Y GASTOS',NULL,0),
  ('60','COMPRAS.',NULL,0),
  ('600','Compras de mercaderías.',NULL,1),
  ('601','Compras de materias primas.',NULL,1),
  ('602','Compras de otros aprovisionamientos.',NULL,1),
  ('606','Descuentos sobre compras por pronto pago.',NULL,1),
  ('607','Trabajos realizados por otras empresas.',NULL,1),
  ('608','Devoluciones de compras y operaciones similares.',NULL,1),
  ('609','Rappels por compras.',NULL,1),
  ('61','VARIACIÓN DE EXISTENCIAS.',NULL,0),
  ('610','Variación de existencias de mercaderías.',NULL,1),
  ('611','Variación de existencias de materias primas.',NULL,1),
  ('612','Variación de existencias de otros aprovisionamientos.',NULL,1),
  ('62','SERVICIOS EXTERIORES.',NULL,0),
  ('620','Gastos en investigación y desarrollo del ejercicio.',NULL,1),
  ('621','Arrendamientos y cánones.',NULL,1),
  ('622','Reparaciones y conservación.',NULL,1),
  ('623','Servicios de profesionales independientes.',NULL,1),
  ('624','Transportes.',NULL,1),
  ('625','Primas de seguros.',NULL,1),
  ('626','Servicios bancarios y similares.',NULL,1),
  ('627','Publicidad, propaganda y relaciones públicas.',NULL,1),
  ('628','Suministros.',NULL,1),
  ('629','Otros servicios.',NULL,1),
  ('63','TRIBUTOS.',NULL,0),
  ('630','Impuesto sobre beneficios.',NULL,0),
  ('63000','Impuesto corriente.',NULL,1),
  ('63001','Impuesto diferido.',NULL,1),
  ('631','Otros tributos.',NULL,1),
  ('633','Ajustes negativos en la imposición sobre beneficios.',NULL,1),
  ('634','Ajustes negativos en la imposición indirecta.',NULL,1),
  ('636','Devolución de impuestos.',NULL,1),
  ('638','Ajustes positivos en la imposición sobre beneficios.',NULL,1),
  ('639','Ajustes positivos en la imposición indirecta.',NULL,1),
  ('64','GASTOS DE PERSONAL.',NULL,0),
  ('640','Sueldos y salarios.',NULL,1),
  ('641','Indemnizaciones.',NULL,1),
  ('642','Seguridad Social a cargo de la empresa.',NULL,1),
  ('643','Retribuciones a largo plazo mediante sistemas de aportación definida.',NULL,1),
  ('644','Retribuciones a largo plazo mediante sistemas de prestación definida.',NULL,0),
  ('64400','Contribuciones anuales.',NULL,1),
  ('64402','Otros costes.',NULL,1),
  ('645','Retribuciones al personal mediante instrumentos de patrimonio.',NULL,1),
  ('649','Otros gastos sociales.',NULL,1),
  ('65','OTROS GASTOS DE GESTIÓN.',NULL,0),
  ('650','Pérdidas de créditos comerciales incobrables.',NULL,1),
  ('651','Resultados de operaciones en común.',NULL,0),
  ('65100','Beneficio transferido (gestor).',NULL,1),
  ('65101','Pérdida soportada (partícipe o asociado no gestor).',NULL,1),
  ('659','Otras pérdidas en gestión corriente.',NULL,1),
  ('66','GASTOS FINANCIEROS.',NULL,0),
  ('660','Gastos financieros por actualización de provisiones.',NULL,1),
  ('661','Intereses de obligaciones y bonos.',NULL,1),
  ('662','Intereses de deudas.',NULL,1),
  ('663','Pérdidas por valoración de instrumentos financieros por su valor razonable.',NULL,0),
  ('66300','Pérdidas de cartera de negociación.',NULL,1),
  ('66301','Pérdidas de designados por la empresa.',NULL,1),
  ('66302','Pérdidas de disponibles para la venta.',NULL,1),
  ('66303','Pérdidas de instrumentos de cobertura.',NULL,1),
  ('664','Dividendos de acciones o participaciones contabilizadas como pasivo.',NULL,1),
  ('665','Intereses por descuento de efectos y operaciones de factoring.',NULL,1),
  ('666','Pérdidas en participaciones y valores representativos de deuda.',NULL,1),
  ('667','Pérdidas de créditos no comerciales.',NULL,1),
  ('668','Diferencias negativas de cambio.',NULL,1),
  ('669','Otros gastos financieros.',NULL,1),
  ('67','PÉRDIDAS PROCEDENTES DE ACTIVOS NO CORRIENTES Y GASTOS EXCEPCIONALES.',NULL,0),
  ('670','Pérdidas procedentes del inmovilizado intangible.',NULL,1),
  ('671','Pérdidas procedentes del inmovilizado material.',NULL,1),
  ('672','Pérdidas procedentes de las inversiones inmobiliarias.',NULL,1),
  ('673','Pérdidas procedentes de participaciones a largo plazo en partes vinculadas.',NULL,1),
  ('675','Pérdidas por operaciones con obligaciones propias.',NULL,1),
  ('678','Gastos excepcionales.',NULL,1),
  ('68','DOTACIONES PARA AMORTIZACIONES.',NULL,0),
  ('680','Amortización del inmovilizado intangible.',NULL,1),
  ('681','Amortización del inmovilizado material.',NULL,1),
  ('682','Amortización de las inversiones inmobiliarias.',NULL,1),
  ('69','PÉRDIDAS POR DETERIORO Y OTRAS DOTACIONES.',NULL,0),
  ('690','Pérdidas por deterioro del inmovilizado intangible.',NULL,1),
  ('691','Pérdidas por deterioro del inmovilizado material.',NULL,1),
  ('692','Pérdidas por deterioro de las inversiones inmobiliarias.',NULL,1),
  ('693','Pérdidas por deterioro de existencias.',NULL,1),
  ('694','Pérdidas por deterioro de créditos comerciales.',NULL,1),
  ('695','Dotación a la provisión por operaciones comerciales.',NULL,0),
  ('69504','Dotación a la provisión por contratos onerosos.',NULL,1),
  ('69509','Dotación a la provisión para otras operaciones comerciales.',NULL,1),
  ('696','Pérdidas por deterioro de participaciones y valores representativos de deuda a largo plazo.',NULL,1),
  ('697','Pérdidas por deterioro de créditos a largo plazo.',NULL,1),
  ('698','Pérdidas por deterioro de participaciones y valores representativos de deuda a corto plazo.',NULL,1),
  ('699','Pérdidas por deterioro de créditos a corto plazo.',NULL,1),
  ('7','VENTAS E INGRESOS',NULL,0),
  ('70','VENTAS DE MERCADERÍAS, DE PRODUCCIÓN PROPIA, DE SERVICIOS, ETC.',NULL,0),
  ('700','Ventas de mercaderías.',NULL,1),
  ('701','Ventas de productos terminados.',NULL,1),
  ('702','Ventas de productos semiterminados.',NULL,1),
  ('703','Ventas de subproductos y residuos.',NULL,1),
  ('704','Ventas de envases y embalajes.',NULL,1),
  ('705','Prestación de servicios.',NULL,1),
  ('706','Descuentos sobre ventas por pronto pago.',NULL,1),
  ('708','Devoluciones de ventas y operaciones similares.',NULL,1),
  ('709','Rappels sobre ventas.',NULL,1),
  ('71','VARIACIÓN DE EXISTENCIAS.',NULL,0),
  ('710','Variación de existencias de productos en curso.',NULL,1),
  ('711','Variación de existencias de productos semiterminados.',NULL,1),
  ('712','Variación de existencias de productos terminados.',NULL,1),
  ('713','Variación de existencias de subproductos, residuos y materiales recuperados.',NULL,1),
  ('73','TRABAJOS REALIZADOS PARA LA EMPRESA.',NULL,0),
  ('730','Trabajos realizados para el inmovilizado intangible.',NULL,1),
  ('731','Trabajos realizados para el inmovilizado material.',NULL,1),
  ('732','Trabajos realizados en inversiones inmobiliarias.',NULL,1),
  ('733','Trabajos realizados para el inmovilizado en curso.',NULL,1),
  ('74','SUBVENCIONES, DONACIONES Y LEGADOS.',NULL,0),
  ('740','Subvenciones, donaciones y legados a la explotación.',NULL,1),
  ('746','Subvenciones, donaciones y legados de capital transferidos al resultado del ejercicio.',NULL,1),
  ('747','Otras subvenciones, donaciones y legados transferidos al resultado del ejercicio.',NULL,1),
  ('75','OTROS INGRESOS DE GESTIÓN.',NULL,0),
  ('751','Resultados de operaciones en común.',NULL,0),
  ('75100','Pérdida transferida (gestor).',NULL,1),
  ('75101','Beneficio atribuido (partícipe o asociado no gestor).',NULL,1),
  ('752','Ingresos por arrendamientos.',NULL,1),
  ('753','Ingresos de propiedad industrial cedida en explotación.',NULL,1),
  ('754','Ingresos por comisiones.',NULL,1),
  ('755','Ingresos por servicios al personal.',NULL,1),
  ('759','Ingresos por servicios diversos.',NULL,1),
  ('76','INGRESOS FINANCIEROS.',NULL,0),
  ('760','Ingresos de participaciones en instrumentos de patrimonio.',NULL,1),
  ('761','Ingresos de valores representativos de deuda.',NULL,1),
  ('762','Ingresos de créditos.',NULL,1),
  ('763','Beneficios por valoración de instrumentos financieros por su valor razonable.',NULL,0),
  ('76300','Beneficios de cartera de negociación.',NULL,1),
  ('76301','Beneficios de designados por la empresa.',NULL,1),
  ('76302','Beneficios de disponibles para la venta.',NULL,1),
  ('76303','Beneficios de instrumentos de cobertura.',NULL,1),
  ('766','Beneficios en participaciones y valores representativos de deuda.',NULL,1),
  ('767','Ingresos de activos afectos y de derechos de reembolso relativos a retribuciones a largo plazo.',NULL,1),
  ('768','Diferencias positivas de cambio.',NULL,1),
  ('769','Otros ingresos financieros.',NULL,1),
  ('77','BENEFICIOS PROCEDENTES DE ACTIVOS NO CORRIENTES E INGRESOS EXCEPCIONALES.',NULL,0),
  ('770','Beneficios procedentes del inmovilizado intangible.',NULL,1),
  ('771','Beneficios procedentes del inmovilizado material.',NULL,1),
  ('772','Beneficios procedentes de las inversiones inmobiliarias.',NULL,1),
  ('773','Beneficios procedentes de participaciones..',NULL,1),
  ('774','Diferencia negativa en combinaciones de negocios.',NULL,1),
  ('775','Beneficios por operaciones con obligaciones propias.',NULL,1),
  ('778','Ingresos excepcionales.',NULL,1),
  ('79','EXCESOS Y APLICACIONES DE PROVISIONES Y DE PÉRDIDAS POR DETERIORO.',NULL,0),
  ('790','Reversión del deterioro del inmovilizado intangible.',NULL,1),
  ('791','Reversión del deterioro del inmovilizado material.',NULL,1),
  ('792','Reversión del deterioro de las inversiones inmobiliarias.',NULL,1),
  ('793','Reversión del deterioro de existencias.',NULL,1),
  ('794','Reversión del deterioro de créditos por operaciones comerciales.',NULL,1),
  ('795','Exceso de provisiones.',NULL,1),
  ('796','Reversión del deterioro de participaciones y valores representativos de deuda a largo plazo.',NULL,1),
  ('797','Reversión del deterioro de créditos a largo plazo.',NULL,1),
  ('798','Reversión del deterioro de participaciones y valores representativos de deuda a corto plazo.',NULL,1),
  ('799','Reversión del deterioro de créditos a corto plazo.',NULL,1),
  ('8','GASTOS IMPUTADOS AL PATRIMONIO NETO',NULL,0),
  ('80','GASTOS FINANCIEROS POR VALORACIÓN DE ACTIVOS FINANCIEROS.',NULL,0),
  ('800','Pérdidas en activos financieros disponibles para la venta.',NULL,1),
  ('802','Transferencia de beneficios en activos financieros disponibles para la venta.',NULL,1),
  ('81','GASTOS EN OPERACIONES DE COBERTURA.',NULL,0),
  ('810','Pérdidas por coberturas de flujos de efectivo.',NULL,1),
  ('811','Pérdidas por coberturas de inversiones netas en un negocio en el extranjero.',NULL,1),
  ('812','Transferencia de beneficios por coberturas de flujos de efectivo.',NULL,1),
  ('813','Transferencia de beneficios por coberturas de inversiones netas en un negocio en el extranjero.',NULL,1),
  ('82','GASTOS POR DIFERENCIAS EN CONVERSIÓN.',NULL,0),
  ('820','Diferencias de conversión negativas.',NULL,1),
  ('821','Transferencia de diferencias de conversión positivas.',NULL,1),
  ('83','IMPUESTOS SOBRE BENEFICIOS.',NULL,0),
  ('830','Impuestos sobre beneficios.',NULL,0),
  ('83000','Impuesto corriente.',NULL,1),
  ('83001','Impuesto diferido.',NULL,1),
  ('833','Ajustes negativos en la imposición sobre beneficios.',NULL,1),
  ('834','Ingresos fiscales por diferencias permanentes.',NULL,1),
  ('835','Ingresos fiscales por deducciones y bonificaciones.',NULL,1),
  ('836','Transferencia de diferencias permanentes.',NULL,1),
  ('837','Transferencia de deducciones y bonificaciones.',NULL,1),
  ('838','Ajustes positivos en la imposición sobre beneficios.',NULL,1),
  ('84','TRANSFERENCIAS DE SUBVENCIONES, DONACIONES Y LEGADOS.',NULL,0),
  ('840','Transferencia de subvenciones oficiales de capital.',NULL,1),
  ('841','Transferencia de donaciones y legados de capital.',NULL,1),
  ('842','Transferencia de otras subvenciones, donaciones y legados.',NULL,1),
  ('85','GASTOS POR PÉRDIDAS ACTUARIALES Y AJUSTES EN LOS ACTIVOS POR RETRIBUCIONES A LARGO PLAZO DE PRESTACIÓN DEFINIDA.',NULL,0),
  ('850','Pérdidas actuariales.',NULL,1),
  ('851','Ajustes negativos en activos por retribuciones a largo plazo de prestación definida.',NULL,1),
  ('86','GASTOS POR ACTIVOS NO CORRIENTES EN VENTA.',NULL,0),
  ('860','Pérdidas en activos no corrientes y grupos enajenables de elementos mantenidos para la venta.',NULL,1),
  ('862','Transferencia de beneficios en activos no corrientes y grupos enajenables de elementos mantenidos para la venta.',NULL,1),
  ('89','GASTOS DE PARTICIPACIONES EN EMPRESAS DEL GRUPO O ASOCIADAS CON AJUSTES VALORATIVOS POSITIVOS PREVIOS.',NULL,0),
  ('891','Deterioro de participaciones en el patrimonio y valores representativos de deuda de empresas del grupo.',NULL,1),
  ('892','Deterioro de participaciones en el patrimonio y valores representativos de deuda de empresas asociadas.',NULL,1),
  ('9','INGRESOS IMPUTADOS AL PATRIMONIO NETO',NULL,0),
  ('90','INGRESOS FINANCIEROS POR VALORACIÓN DE ACTIVOS FINANCIEROS.',NULL,0),
  ('900','Beneficios en activos financieros disponibles para la venta.',NULL,1),
  ('902','Transferencia de pérdidas de activos financieros disponibles para la venta.',NULL,1),
  ('91','INGRESOS EN OPERACIONES DE COBERTURA.',NULL,0),
  ('910','Beneficios por coberturas de flujos de efectivo.',NULL,1),
  ('911','Beneficios por coberturas de una inversión neta en un negocio en el extranjero.',NULL,1),
  ('912','Transferencia de pérdidas por coberturas de flujos de efectivo.',NULL,1),
  ('913','Transferencia de pérdidas por coberturas de una inversión neta en un negocio en el extranjero.',NULL,1),
  ('92','INGRESOS POR DIFERENCIAS DE CONVERSIÓN.',NULL,0),
  ('920','Diferencias de conversión positivas.',NULL,1),
  ('921','Transferencia de diferencias de conversión negativas.',NULL,1),
  ('94','INGRESOS POR SUBVENCIONES, DONACIONES Y LEGADOS.',NULL,0),
  ('940','Ingresos de subvenciones oficiales de capital.',NULL,1),
  ('941','Ingresos de donaciones y legados de capital.',NULL,1),
  ('942','Ingresos de otras subvenciones, donaciones y legados.',NULL,1),
  ('95','INGRESOS POR GANANCIAS ACTUARIALES Y AJUSTES EN LOS ACTIVOS POR RETRIBUCIONES A LARGO PLAZO DE PRESTACIÓN DEFINIDA.',NULL,0),
  ('950','Ganancias actuariales.',NULL,1),
  ('951','Ajustes positivos en activos por retribuciones a largo plazo de prestación definida.',NULL,1),
  ('96','INGRESOS POR ACTIVOS NO CORRIENTES EN VENTA.',NULL,0),
  ('960','Beneficios en activos no corrientes y grupos enajenables de elementos mantenidos para la venta.',NULL,1),
  ('962','Transferencia de pérdidas en activos no corrientes y grupos enajenables de elementos mantenidos para la venta.',NULL,1),
  ('99','INGRESOS DE PARTICIPACIONES EN EL PATRIMONIO DE EMPRESAS DEL GRUPO O ASOCIADAS CON AJUSTES VALORATIVOS NEGATIVOS PREVIOS.',NULL,0),
  ('991','Recuperación de ajustes valorativos negativos previos, empresas del grupo.',NULL,1),
  ('992','Recuperación de ajustes valorativos negativos previos, empresas asociadas.',NULL,1),
  ('993','Transferencia por deterioro de ajustes valorativos negativos previos, empresas del grupo.',NULL,1),
  ('994','Transferencia por deterioro de ajustes valorativos negativos previos, empresas asociadas.',NULL,1); 

COMMIT;

#
# Data for the `level` column on `account` table
#

UPDATE `account` SET `level` = LENGTH(`id`);
UPDATE `account` SET `level` = 4 WHERE `level` = 5;
UPDATE `account` SET `level` = 5 WHERE `level` > 5;

COMMIT;

SET FOREIGN_KEY_CHECKS=1;
