bgcolor_color_de_fondo = #fafffc
color_color_de_texto = #646464
color_color_de_texto_link = #000000
color_color_de_texto_slogan = #000000
color_color_de_texto_titulo = #000000
color_color_borde_titulo = #000000
font_fuente = 2
size_tamano_de_fuente = 10
size_tamano_de_fuente_pie = 9
border_size_bordes = 1
color_color_borde = #c8c8c8