package es.code.nominasta.entity;
// Generated by Expand 2.0.1 

import com.transtools.expand.annotation.DataDefinition;
import com.transtools.expand.annotation.Lines;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Calculo generated by Expand 2.0.1
 */
@Entity
@Lines(joinProperty="emprper")
@Table(name="calculo")
public class Calculo  implements java.io.Serializable {

     private CalculoId id;
     private String indirpf;
     private String aplicado;
     private BigDecimal retrAnt;
     private BigDecimal retrAcuFij;
     private BigDecimal retrAcuVar;
     private BigDecimal retrPreFij;
     private BigDecimal retrPreVar;
     private BigDecimal retrEstimada;
     private BigDecimal retrConsid;
     private BigDecimal impAcuSs;
     private BigDecimal impPreSs;
     private BigDecimal impIrreg;
     private BigDecimal impRentas;
     private BigDecimal impPersonal;
     private BigDecimal impFamiliar;
     private BigDecimal impDescen;
     private BigDecimal impPension;
     private BigDecimal impCss;
     private BigDecimal impAscen;
     private BigDecimal baseCalculo;
     private BigDecimal impAnualid;
     private BigDecimal cuotaCalculo;
     private BigDecimal cuotaAnualid;
     private BigDecimal irpfAcu;
     private BigDecimal irpfCal;
     private BigDecimal irpf;
     private BigDecimal irpfAnterior;
     private String regula;
     private Integer diascont;
     private String hijos;
     private Date fecnew;
     private Date hornew;
     private Date fecmod;
     private Date hormod;
     private BigDecimal minforal;
     private BigDecimal impDiscapacidadt;
     private BigDecimal impCuidadohijo;
     private BigDecimal impDiscapacidad;
     private BigDecimal impPensionista;
     private BigDecimal impProlongacion;
     private BigDecimal impMovilidad;
     private BigDecimal impAsistencia;
     private BigDecimal retanualn;
     private BigDecimal retanualb;
     private BigDecimal difret;
     private BigDecimal irpfanual;
     private Emprper emprper;

    public Calculo() {
    }
	
    public Calculo(CalculoId id, String aplicado, BigDecimal retrAnt, BigDecimal retrAcuFij, BigDecimal retrAcuVar, BigDecimal retrPreFij, BigDecimal retrPreVar, BigDecimal retrEstimada, BigDecimal retrConsid, BigDecimal impAcuSs, BigDecimal impPreSs, BigDecimal impIrreg, BigDecimal impRentas, BigDecimal impPersonal, BigDecimal impFamiliar, BigDecimal impDescen, BigDecimal impPension, BigDecimal impCss, BigDecimal impAscen, BigDecimal baseCalculo, BigDecimal impAnualid, BigDecimal cuotaCalculo, BigDecimal cuotaAnualid, BigDecimal irpfAcu, BigDecimal irpfCal, BigDecimal minforal, BigDecimal impDiscapacidadt, BigDecimal impCuidadohijo, BigDecimal impDiscapacidad, BigDecimal impPensionista, BigDecimal impProlongacion, BigDecimal impMovilidad, BigDecimal impAsistencia, BigDecimal retanualn, BigDecimal retanualb, BigDecimal difret, BigDecimal irpfanual) {
        this.id = id;
        this.aplicado = aplicado;
        this.retrAnt = retrAnt;
        this.retrAcuFij = retrAcuFij;
        this.retrAcuVar = retrAcuVar;
        this.retrPreFij = retrPreFij;
        this.retrPreVar = retrPreVar;
        this.retrEstimada = retrEstimada;
        this.retrConsid = retrConsid;
        this.impAcuSs = impAcuSs;
        this.impPreSs = impPreSs;
        this.impIrreg = impIrreg;
        this.impRentas = impRentas;
        this.impPersonal = impPersonal;
        this.impFamiliar = impFamiliar;
        this.impDescen = impDescen;
        this.impPension = impPension;
        this.impCss = impCss;
        this.impAscen = impAscen;
        this.baseCalculo = baseCalculo;
        this.impAnualid = impAnualid;
        this.cuotaCalculo = cuotaCalculo;
        this.cuotaAnualid = cuotaAnualid;
        this.irpfAcu = irpfAcu;
        this.irpfCal = irpfCal;
        this.minforal = minforal;
        this.impDiscapacidadt = impDiscapacidadt;
        this.impCuidadohijo = impCuidadohijo;
        this.impDiscapacidad = impDiscapacidad;
        this.impPensionista = impPensionista;
        this.impProlongacion = impProlongacion;
        this.impMovilidad = impMovilidad;
        this.impAsistencia = impAsistencia;
        this.retanualn = retanualn;
        this.retanualb = retanualb;
        this.difret = difret;
        this.irpfanual = irpfanual;
    }

    public Calculo(CalculoId id, String indirpf, String aplicado, BigDecimal retrAnt, BigDecimal retrAcuFij, BigDecimal retrAcuVar, BigDecimal retrPreFij, BigDecimal retrPreVar, BigDecimal retrEstimada, BigDecimal retrConsid, BigDecimal impAcuSs, BigDecimal impPreSs, BigDecimal impIrreg, BigDecimal impRentas, BigDecimal impPersonal, BigDecimal impFamiliar, BigDecimal impDescen, BigDecimal impPension, BigDecimal impCss, BigDecimal impAscen, BigDecimal baseCalculo, BigDecimal impAnualid, BigDecimal cuotaCalculo, BigDecimal cuotaAnualid, BigDecimal irpfAcu, BigDecimal irpfCal, BigDecimal irpf, BigDecimal irpfAnterior, String regula, Integer diascont, String hijos, Date fecnew, Date hornew, Date fecmod, Date hormod, BigDecimal minforal, BigDecimal impDiscapacidadt, BigDecimal impCuidadohijo, BigDecimal impDiscapacidad, BigDecimal impPensionista, BigDecimal impProlongacion, BigDecimal impMovilidad, BigDecimal impAsistencia, BigDecimal retanualn, BigDecimal retanualb, BigDecimal difret, BigDecimal irpfanual, Emprper emprper) {
       this.id = id;
       this.indirpf = indirpf;
       this.aplicado = aplicado;
       this.retrAnt = retrAnt;
       this.retrAcuFij = retrAcuFij;
       this.retrAcuVar = retrAcuVar;
       this.retrPreFij = retrPreFij;
       this.retrPreVar = retrPreVar;
       this.retrEstimada = retrEstimada;
       this.retrConsid = retrConsid;
       this.impAcuSs = impAcuSs;
       this.impPreSs = impPreSs;
       this.impIrreg = impIrreg;
       this.impRentas = impRentas;
       this.impPersonal = impPersonal;
       this.impFamiliar = impFamiliar;
       this.impDescen = impDescen;
       this.impPension = impPension;
       this.impCss = impCss;
       this.impAscen = impAscen;
       this.baseCalculo = baseCalculo;
       this.impAnualid = impAnualid;
       this.cuotaCalculo = cuotaCalculo;
       this.cuotaAnualid = cuotaAnualid;
       this.irpfAcu = irpfAcu;
       this.irpfCal = irpfCal;
       this.irpf = irpf;
       this.irpfAnterior = irpfAnterior;
       this.regula = regula;
       this.diascont = diascont;
       this.hijos = hijos;
       this.fecnew = fecnew;
       this.hornew = hornew;
       this.fecmod = fecmod;
       this.hormod = hormod;
       this.minforal = minforal;
       this.impDiscapacidadt = impDiscapacidadt;
       this.impCuidadohijo = impCuidadohijo;
       this.impDiscapacidad = impDiscapacidad;
       this.impPensionista = impPensionista;
       this.impProlongacion = impProlongacion;
       this.impMovilidad = impMovilidad;
       this.impAsistencia = impAsistencia;
       this.retanualn = retanualn;
       this.retanualb = retanualb;
       this.difret = difret;
       this.irpfanual = irpfanual;
       this.emprper = emprper;
    }

    @EmbeddedId    
    @AttributeOverrides( {
        @AttributeOverride(name="cdg", column=@Column(name="cdg", nullable=false, length=4) ), 
        @AttributeOverride(name="anio", column=@Column(name="anio", nullable=false, length=2) ), 
        @AttributeOverride(name="mes", column=@Column(name="mes", nullable=false, length=2) ), 
        @AttributeOverride(name="dia", column=@Column(name="dia", nullable=false, length=2) ) } )
    public CalculoId getId() {
        return this.id;
    }
    
    public void setId(CalculoId id) {
        this.id = id;
    }
    
	@DataDefinition(label="Indicador Especial I.R.P.F.")
    @Column(name="indirpf", length=1)
    public String getIndirpf() {
        return this.indirpf;
    }
    
    public void setIndirpf(String indirpf) {
        this.indirpf = indirpf;
    }
    
	@DataDefinition(label="Indicador de modificacion segun indicador de irpf")
    @Column(name="aplicado", nullable=false, length=1)
    public String getAplicado() {
        return this.aplicado;
    }
    
    public void setAplicado(String aplicado) {
        this.aplicado = aplicado;
    }
    
	@DataDefinition(label="Retribucion Periodo Anterior")
    @Column(name="retr_ant", nullable=false, precision=11)
    public BigDecimal getRetrAnt() {
        return this.retrAnt;
    }
    
    public void setRetrAnt(BigDecimal retrAnt) {
        this.retrAnt = retrAnt;
    }
    
	@DataDefinition(label="Retribucion Acumulada Complementos Fijos")
    @Column(name="retr_acu_fij", nullable=false, precision=11)
    public BigDecimal getRetrAcuFij() {
        return this.retrAcuFij;
    }
    
    public void setRetrAcuFij(BigDecimal retrAcuFij) {
        this.retrAcuFij = retrAcuFij;
    }
    
	@DataDefinition(label="Retribucion Acumulada Complementos Variables")
    @Column(name="retr_acu_var", nullable=false, precision=11)
    public BigDecimal getRetrAcuVar() {
        return this.retrAcuVar;
    }
    
    public void setRetrAcuVar(BigDecimal retrAcuVar) {
        this.retrAcuVar = retrAcuVar;
    }
    
	@DataDefinition(label="Retribucion Prevista Complementos Fijos")
    @Column(name="retr_pre_fij", nullable=false, precision=11)
    public BigDecimal getRetrPreFij() {
        return this.retrPreFij;
    }
    
    public void setRetrPreFij(BigDecimal retrPreFij) {
        this.retrPreFij = retrPreFij;
    }
    
	@DataDefinition(label="Retribucion Prevista Complementos Variables")
    @Column(name="retr_pre_var", nullable=false, precision=11)
    public BigDecimal getRetrPreVar() {
        return this.retrPreVar;
    }
    
    public void setRetrPreVar(BigDecimal retrPreVar) {
        this.retrPreVar = retrPreVar;
    }
    
	@DataDefinition(label="Retribucion Estimada Ejercicio Actual")
    @Column(name="retr_estimada", nullable=false, precision=11)
    public BigDecimal getRetrEstimada() {
        return this.retrEstimada;
    }
    
    public void setRetrEstimada(BigDecimal retrEstimada) {
        this.retrEstimada = retrEstimada;
    }
    
	@DataDefinition(label="Retribucion a considerar")
    @Column(name="retr_consid", nullable=false, precision=11)
    public BigDecimal getRetrConsid() {
        return this.retrConsid;
    }
    
    public void setRetrConsid(BigDecimal retrConsid) {
        this.retrConsid = retrConsid;
    }
    
	@DataDefinition(label="Aportacion S.S. Acumulada")
    @Column(name="imp_acu_ss", nullable=false, precision=11)
    public BigDecimal getImpAcuSs() {
        return this.impAcuSs;
    }
    
    public void setImpAcuSs(BigDecimal impAcuSs) {
        this.impAcuSs = impAcuSs;
    }
    
	@DataDefinition(label="Aportacion S.S. Prevista")
    @Column(name="imp_pre_ss", nullable=false, precision=11)
    public BigDecimal getImpPreSs() {
        return this.impPreSs;
    }
    
    public void setImpPreSs(BigDecimal impPreSs) {
        this.impPreSs = impPreSs;
    }
    
	@DataDefinition(label="Minoracion Rentas Irregulares")
    @Column(name="imp_irreg", nullable=false, precision=11)
    public BigDecimal getImpIrreg() {
        return this.impIrreg;
    }
    
    public void setImpIrreg(BigDecimal impIrreg) {
        this.impIrreg = impIrreg;
    }
    
	@DataDefinition(label="Minoracion Rentas Trabajo")
    @Column(name="imp_rentas", nullable=false, precision=11)
    public BigDecimal getImpRentas() {
        return this.impRentas;
    }
    
    public void setImpRentas(BigDecimal impRentas) {
        this.impRentas = impRentas;
    }
    
	@DataDefinition(label="Minoracion Personal")
    @Column(name="imp_personal", nullable=false, precision=11)
    public BigDecimal getImpPersonal() {
        return this.impPersonal;
    }
    
    public void setImpPersonal(BigDecimal impPersonal) {
        this.impPersonal = impPersonal;
    }
    
	@DataDefinition(label="Minoracion Familiar")
    @Column(name="imp_familiar", nullable=false, precision=11)
    public BigDecimal getImpFamiliar() {
        return this.impFamiliar;
    }
    
    public void setImpFamiliar(BigDecimal impFamiliar) {
        this.impFamiliar = impFamiliar;
    }
    
	@DataDefinition(label="Mas de 2 descendientes")
    @Column(name="imp_descen", nullable=false, precision=11)
    public BigDecimal getImpDescen() {
        return this.impDescen;
    }
    
    public void setImpDescen(BigDecimal impDescen) {
        this.impDescen = impDescen;
    }
    
	@DataDefinition(label="Pension Compensatoria")
    @Column(name="imp_pension", nullable=false, precision=11)
    public BigDecimal getImpPension() {
        return this.impPension;
    }
    
    public void setImpPension(BigDecimal impPension) {
        this.impPension = impPension;
    }
    
	@DataDefinition(label="Minoracion SS")
    @Column(name="imp_css", nullable=false, precision=11)
    public BigDecimal getImpCss() {
        return this.impCss;
    }
    
    public void setImpCss(BigDecimal impCss) {
        this.impCss = impCss;
    }
    
	@DataDefinition(label="Minoracion por Ascendientes")
    @Column(name="imp_ascen", nullable=false, precision=11)
    public BigDecimal getImpAscen() {
        return this.impAscen;
    }
    
    public void setImpAscen(BigDecimal impAscen) {
        this.impAscen = impAscen;
    }
    
	@DataDefinition(label="Base Calculo Retencion")
    @Column(name="base_calculo", nullable=false, precision=11)
    public BigDecimal getBaseCalculo() {
        return this.baseCalculo;
    }
    
    public void setBaseCalculo(BigDecimal baseCalculo) {
        this.baseCalculo = baseCalculo;
    }
    
	@DataDefinition(label="Anualidades por Alimentos")
    @Column(name="imp_anualid", nullable=false, precision=11)
    public BigDecimal getImpAnualid() {
        return this.impAnualid;
    }
    
    public void setImpAnualid(BigDecimal impAnualid) {
        this.impAnualid = impAnualid;
    }
    
	@DataDefinition(label="Cuota Calculo Retencion")
    @Column(name="cuota_calculo", nullable=false, precision=11)
    public BigDecimal getCuotaCalculo() {
        return this.cuotaCalculo;
    }
    
    public void setCuotaCalculo(BigDecimal cuotaCalculo) {
        this.cuotaCalculo = cuotaCalculo;
    }
    
	@DataDefinition(label="Cuota Anualidades")
    @Column(name="cuota_anualid", nullable=false, precision=11)
    public BigDecimal getCuotaAnualid() {
        return this.cuotaAnualid;
    }
    
    public void setCuotaAnualid(BigDecimal cuotaAnualid) {
        this.cuotaAnualid = cuotaAnualid;
    }
    
	@DataDefinition(label="Retencion I.R.P.F. acumulada")
    @Column(name="irpf_acu", nullable=false, precision=11)
    public BigDecimal getIrpfAcu() {
        return this.irpfAcu;
    }
    
    public void setIrpfAcu(BigDecimal irpfAcu) {
        this.irpfAcu = irpfAcu;
    }
    
	@DataDefinition(label="Tipo I.R.P.F. calculado")
    @Column(name="irpf_cal", nullable=false, precision=11)
    public BigDecimal getIrpfCal() {
        return this.irpfCal;
    }
    
    public void setIrpfCal(BigDecimal irpfCal) {
        this.irpfCal = irpfCal;
    }
    
	@DataDefinition(label="I.R.P.F. asignado")
    @Column(name="irpf", precision=5)
    public BigDecimal getIrpf() {
        return this.irpf;
    }
    
    public void setIrpf(BigDecimal irpf) {
        this.irpf = irpf;
    }
    
	@DataDefinition(label="I.R.P.F. Anterior")
    @Column(name="irpf_anterior", precision=5)
    public BigDecimal getIrpfAnterior() {
        return this.irpfAnterior;
    }
    
    public void setIrpfAnterior(BigDecimal irpfAnterior) {
        this.irpfAnterior = irpfAnterior;
    }
    
	@DataDefinition(label="I.R.P.F. Anterior Procede de Regularizacion")
    @Column(name="regula", length=1)
    public String getRegula() {
        return this.regula;
    }
    
    public void setRegula(String regula) {
        this.regula = regula;
    }
    
	@DataDefinition(label="Dias de contrato")
    @Column(name="diascont", length=2)
    public Integer getDiascont() {
        return this.diascont;
    }
    
    public void setDiascont(Integer diascont) {
        this.diascont = diascont;
    }
    
	@DataDefinition(label="Indicador de hijos",descriptionColumn=true)
    @Column(name="hijos", length=12)
    public String getHijos() {
        return this.hijos;
    }
    
    public void setHijos(String hijos) {
        this.hijos = hijos;
    }
    @Temporal(TemporalType.DATE)
	@DataDefinition(label="Fecha Creacion Fila")
    @Column(name="fecnew", length=10)
    public Date getFecnew() {
        return this.fecnew;
    }
    
    public void setFecnew(Date fecnew) {
        this.fecnew = fecnew;
    }
    @Temporal(TemporalType.TIME)
	@DataDefinition(label="Hora Creacion Fila")
    @Column(name="hornew", length=8)
    public Date getHornew() {
        return this.hornew;
    }
    
    public void setHornew(Date hornew) {
        this.hornew = hornew;
    }
    @Temporal(TemporalType.DATE)
	@DataDefinition(label="Fecha Modificacion Fila")
    @Column(name="fecmod", length=10)
    public Date getFecmod() {
        return this.fecmod;
    }
    
    public void setFecmod(Date fecmod) {
        this.fecmod = fecmod;
    }
    @Temporal(TemporalType.TIME)
	@DataDefinition(label="Hora Modificacion Fila")
    @Column(name="hormod", length=8)
    public Date getHormod() {
        return this.hormod;
    }
    
    public void setHormod(Date hormod) {
        this.hormod = hormod;
    }
    
	@DataDefinition(label="Minoracion Foral por Minusvalia")
    @Column(name="minforal", nullable=false, precision=5)
    public BigDecimal getMinforal() {
        return this.minforal;
    }
    
    public void setMinforal(BigDecimal minforal) {
        this.minforal = minforal;
    }
    
	@DataDefinition(label="Discapacidad trabajador activos")
    @Column(name="imp_discapacidadt", nullable=false, precision=11)
    public BigDecimal getImpDiscapacidadt() {
        return this.impDiscapacidadt;
    }
    
    public void setImpDiscapacidadt(BigDecimal impDiscapacidadt) {
        this.impDiscapacidadt = impDiscapacidadt;
    }
    
	@DataDefinition(label="Cuidado de hijos")
    @Column(name="imp_cuidadohijo", nullable=false, precision=11)
    public BigDecimal getImpCuidadohijo() {
        return this.impCuidadohijo;
    }
    
    public void setImpCuidadohijo(BigDecimal impCuidadohijo) {
        this.impCuidadohijo = impCuidadohijo;
    }
    
	@DataDefinition(label="Discapacidad")
    @Column(name="imp_discapacidad", nullable=false, precision=11)
    public BigDecimal getImpDiscapacidad() {
        return this.impDiscapacidad;
    }
    
    public void setImpDiscapacidad(BigDecimal impDiscapacidad) {
        this.impDiscapacidad = impDiscapacidad;
    }
    
	@DataDefinition(label="Pensionistas")
    @Column(name="imp_pensionista", nullable=false, precision=11)
    public BigDecimal getImpPensionista() {
        return this.impPensionista;
    }
    
    public void setImpPensionista(BigDecimal impPensionista) {
        this.impPensionista = impPensionista;
    }
    
	@DataDefinition(label="Prolongacion actividad laboral")
    @Column(name="imp_prolongacion", nullable=false, precision=11)
    public BigDecimal getImpProlongacion() {
        return this.impProlongacion;
    }
    
    public void setImpProlongacion(BigDecimal impProlongacion) {
        this.impProlongacion = impProlongacion;
    }
    
	@DataDefinition(label="Movilidad geográfica")
    @Column(name="imp_movilidad", nullable=false, precision=11)
    public BigDecimal getImpMovilidad() {
        return this.impMovilidad;
    }
    
    public void setImpMovilidad(BigDecimal impMovilidad) {
        this.impMovilidad = impMovilidad;
    }
    
	@DataDefinition(label="Por asistencia")
    @Column(name="imp_asistencia", nullable=false, precision=11)
    public BigDecimal getImpAsistencia() {
        return this.impAsistencia;
    }
    
    public void setImpAsistencia(BigDecimal impAsistencia) {
        this.impAsistencia = impAsistencia;
    }
    
	@DataDefinition(label="Retención Anual Nueva")
    @Column(name="retanualn", nullable=false, precision=13)
    public BigDecimal getRetanualn() {
        return this.retanualn;
    }
    
    public void setRetanualn(BigDecimal retanualn) {
        this.retanualn = retanualn;
    }
    
	@DataDefinition(label="Retención Anual Base")
    @Column(name="retanualb", nullable=false, precision=13)
    public BigDecimal getRetanualb() {
        return this.retanualb;
    }
    
    public void setRetanualb(BigDecimal retanualb) {
        this.retanualb = retanualb;
    }
    
	@DataDefinition(label="Diferencia Retención")
    @Column(name="difret", nullable=false, precision=13)
    public BigDecimal getDifret() {
        return this.difret;
    }
    
    public void setDifret(BigDecimal difret) {
        this.difret = difret;
    }
    
	@DataDefinition(label="IRPF Anual")
    @Column(name="irpfanual", nullable=false, precision=5)
    public BigDecimal getIrpfanual() {
        return this.irpfanual;
    }
    
    public void setIrpfanual(BigDecimal irpfanual) {
        this.irpfanual = irpfanual;
    }
    
	@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cdg", insertable=false, updatable=false)
    public Emprper getEmprper() {
        return this.emprper;
    }
    
    public void setEmprper(Emprper emprper) {
        this.emprper = emprper;
    }


}


