package es.code.nominasta.entity;
// Generated by Expand 2.0.1 

import com.transtools.expand.annotation.DataDefinition;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * Cuota48Id generated by Expand 2.0.1
 */
@Embeddable
public class Cuota48Id  implements java.io.Serializable {

     private int numTramo;
     private Date fecini;

    public Cuota48Id() {
    }

    public Cuota48Id(int numTramo, Date fecini) {
       this.numTramo = numTramo;
       this.fecini = fecini;
    }


	@DataDefinition(label="Numero de tramo")
    @Column(name="num_tramo", nullable=false, length=2)
    public int getNumTramo() {
        return this.numTramo;
    }
    
    public void setNumTramo(int numTramo) {
        this.numTramo = numTramo;
    }

	@DataDefinition(label="Fecha Inicio Vigencia")
    @Column(name="fecini", nullable=false, length=10)
    public Date getFecini() {
        return this.fecini;
    }
    
    public void setFecini(Date fecini) {
        this.fecini = fecini;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof Cuota48Id) ) return false;
		 Cuota48Id castOther = ( Cuota48Id ) other; 
         
		 return (this.getNumTramo()==castOther.getNumTramo())
 && ( (this.getFecini()==castOther.getFecini()) || ( this.getFecini()!=null && castOther.getFecini()!=null && this.getFecini().equals(castOther.getFecini()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getNumTramo();
         result = 37 * result + ( getFecini() == null ? 0 : this.getFecini().hashCode() );
         return result;
   }   
}


