package es.code.nominasta.entity;
// Generated by Expand 2.0.1 

import com.transtools.expand.annotation.DataDefinition;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Datosafi generated by Expand 2.0.1
 */
@Entity
@Table(name="datosafi")
public class Datosafi  implements java.io.Serializable {

     private int cdg;
     private Integer codtrab;
     private String passact;
     private String provrrss;
     private String numrrss;
     private String tipemp;
     private String paisemp;
     private String provccc;
     private String numccc;
     private String numidemp;
     private String indrs;
     private Integer codact;
     private String razon;
     private String provnaf;
     private String numnaf;
     private String tipidipf;
     private String paisipf;
     private String nacion;
     private String apel1;
     private String apel2;
     private String nombre;
     private String tipovia;
     private String nomvia;
     private String numero;
     private String bloque;
     private String escalera;
     private String piso;
     private String puerta;
     private String codpos;
     private String munic;
     private String localidad;
     private String provincia;
     private String accion;
     private String situacion;
     private Date fecreal;
     private String grucot;
     private String epigat;
     private String contrab;
     private String coeftp;
     private String indimp;
     private String diastrab;
     private BigDecimal coefper;
     private Date fecnac;
     private String sexo;
     private String catprof;
     private String alfaclave;
     private String entidad;
     private String coltrab;
     private String calemp;
     private String regss;
     private String rlabcaresp;
     private String provsstrasust;
     private String numsstrasust;
     private String causasust;
     private String autorizacion;
     private Date fecaut;
     private Date fecinicont;
     private String indsubrog;
     private String emporigen;
     private String excoti;
     private String provempusu;
     private String numempusu;
     private String contrint;
     private String pariente;
     private String embarcacion;
     private String ocupacion;

    public Datosafi() {
    }
	
    public Datosafi(int cdg) {
        this.cdg = cdg;
    }

    public Datosafi(int cdg, Integer codtrab, String passact, String provrrss, String numrrss, String tipemp, String paisemp, String provccc, String numccc, String numidemp, String indrs, Integer codact, String razon, String provnaf, String numnaf, String tipidipf, String paisipf, String nacion, String apel1, String apel2, String nombre, String tipovia, String nomvia, String numero, String bloque, String escalera, String piso, String puerta, String codpos, String munic, String localidad, String provincia, String accion, String situacion, Date fecreal, String grucot, String epigat, String contrab, String coeftp, String indimp, String diastrab, BigDecimal coefper, Date fecnac, String sexo, String catprof, String alfaclave, String entidad, String coltrab, String calemp, String regss, String rlabcaresp, String provsstrasust, String numsstrasust, String causasust, String autorizacion, Date fecaut, Date fecinicont, String indsubrog, String emporigen, String excoti, String provempusu, String numempusu, String contrint, String pariente, String embarcacion, String ocupacion) {
       this.cdg = cdg;
       this.codtrab = codtrab;
       this.passact = passact;
       this.provrrss = provrrss;
       this.numrrss = numrrss;
       this.tipemp = tipemp;
       this.paisemp = paisemp;
       this.provccc = provccc;
       this.numccc = numccc;
       this.numidemp = numidemp;
       this.indrs = indrs;
       this.codact = codact;
       this.razon = razon;
       this.provnaf = provnaf;
       this.numnaf = numnaf;
       this.tipidipf = tipidipf;
       this.paisipf = paisipf;
       this.nacion = nacion;
       this.apel1 = apel1;
       this.apel2 = apel2;
       this.nombre = nombre;
       this.tipovia = tipovia;
       this.nomvia = nomvia;
       this.numero = numero;
       this.bloque = bloque;
       this.escalera = escalera;
       this.piso = piso;
       this.puerta = puerta;
       this.codpos = codpos;
       this.munic = munic;
       this.localidad = localidad;
       this.provincia = provincia;
       this.accion = accion;
       this.situacion = situacion;
       this.fecreal = fecreal;
       this.grucot = grucot;
       this.epigat = epigat;
       this.contrab = contrab;
       this.coeftp = coeftp;
       this.indimp = indimp;
       this.diastrab = diastrab;
       this.coefper = coefper;
       this.fecnac = fecnac;
       this.sexo = sexo;
       this.catprof = catprof;
       this.alfaclave = alfaclave;
       this.entidad = entidad;
       this.coltrab = coltrab;
       this.calemp = calemp;
       this.regss = regss;
       this.rlabcaresp = rlabcaresp;
       this.provsstrasust = provsstrasust;
       this.numsstrasust = numsstrasust;
       this.causasust = causasust;
       this.autorizacion = autorizacion;
       this.fecaut = fecaut;
       this.fecinicont = fecinicont;
       this.indsubrog = indsubrog;
       this.emporigen = emporigen;
       this.excoti = excoti;
       this.provempusu = provempusu;
       this.numempusu = numempusu;
       this.contrint = contrint;
       this.pariente = pariente;
       this.embarcacion = embarcacion;
       this.ocupacion = ocupacion;
    }

    @Id     
	@DataDefinition(label="Codigo Secuencial")
    @Column(name="cdg", unique=true, nullable=false, length=4)
    public int getCdg() {
        return this.cdg;
    }
    
    public void setCdg(int cdg) {
        this.cdg = cdg;
    }
    
	@DataDefinition(label="Codigo Trabajador")
    @Column(name="codtrab", length=4)
    public Integer getCodtrab() {
        return this.codtrab;
    }
    
    public void setCodtrab(Integer codtrab) {
        this.codtrab = codtrab;
    }
    
	@DataDefinition(label="Password Actual",descriptionColumn=true)
    @Column(name="passact", length=8)
    public String getPassact() {
        return this.passact;
    }
    
    public void setPassact(String passact) {
        this.passact = passact;
    }
    
	@DataDefinition(label="Provincia C.C.C.")
    @Column(name="provrrss", length=2)
    public String getProvrrss() {
        return this.provrrss;
    }
    
    public void setProvrrss(String provrrss) {
        this.provrrss = provrrss;
    }
    
	@DataDefinition(label="Numero C.C.C.")
    @Column(name="numrrss", length=9)
    public String getNumrrss() {
        return this.numrrss;
    }
    
    public void setNumrrss(String numrrss) {
        this.numrrss = numrrss;
    }
    
	@DataDefinition(label="Tipo identificacion empresa")
    @Column(name="tipemp", length=1)
    public String getTipemp() {
        return this.tipemp;
    }
    
    public void setTipemp(String tipemp) {
        this.tipemp = tipemp;
    }
    
	@DataDefinition(label="Pais empresa")
    @Column(name="paisemp", length=3)
    public String getPaisemp() {
        return this.paisemp;
    }
    
    public void setPaisemp(String paisemp) {
        this.paisemp = paisemp;
    }
    
	@DataDefinition(label="Provincia CCC")
    @Column(name="provccc", length=2)
    public String getProvccc() {
        return this.provccc;
    }
    
    public void setProvccc(String provccc) {
        this.provccc = provccc;
    }
    
	@DataDefinition(label="Numero CCC")
    @Column(name="numccc", length=9)
    public String getNumccc() {
        return this.numccc;
    }
    
    public void setNumccc(String numccc) {
        this.numccc = numccc;
    }
    
	@DataDefinition(label="Numero identificacion empresa")
    @Column(name="numidemp", length=14)
    public String getNumidemp() {
        return this.numidemp;
    }
    
    public void setNumidemp(String numidemp) {
        this.numidemp = numidemp;
    }
    
	@DataDefinition(label="Indicador razon social")
    @Column(name="indrs", length=1)
    public String getIndrs() {
        return this.indrs;
    }
    
    public void setIndrs(String indrs) {
        this.indrs = indrs;
    }
    
	@DataDefinition(label="Codigo Actividad")
    @Column(name="codact", length=4)
    public Integer getCodact() {
        return this.codact;
    }
    
    public void setCodact(Integer codact) {
        this.codact = codact;
    }
    
	@DataDefinition(label="Razon social")
    @Column(name="razon", length=55)
    public String getRazon() {
        return this.razon;
    }
    
    public void setRazon(String razon) {
        this.razon = razon;
    }
    
	@DataDefinition(label="Provincia N.A.F.")
    @Column(name="provnaf", length=2)
    public String getProvnaf() {
        return this.provnaf;
    }
    
    public void setProvnaf(String provnaf) {
        this.provnaf = provnaf;
    }
    
	@DataDefinition(label="Numero N.A.F.")
    @Column(name="numnaf", length=10)
    public String getNumnaf() {
        return this.numnaf;
    }
    
    public void setNumnaf(String numnaf) {
        this.numnaf = numnaf;
    }
    
	@DataDefinition(label="Tipo identificacion IPF")
    @Column(name="tipidipf", length=1)
    public String getTipidipf() {
        return this.tipidipf;
    }
    
    public void setTipidipf(String tipidipf) {
        this.tipidipf = tipidipf;
    }
    
	@DataDefinition(label="Pais IPF")
    @Column(name="paisipf", length=3)
    public String getPaisipf() {
        return this.paisipf;
    }
    
    public void setPaisipf(String paisipf) {
        this.paisipf = paisipf;
    }
    
	@DataDefinition(label="Nacionalidad")
    @Column(name="nacion", length=3)
    public String getNacion() {
        return this.nacion;
    }
    
    public void setNacion(String nacion) {
        this.nacion = nacion;
    }
    
	@DataDefinition(label="Primer apellido")
    @Column(name="apel1", length=35)
    public String getApel1() {
        return this.apel1;
    }
    
    public void setApel1(String apel1) {
        this.apel1 = apel1;
    }
    
	@DataDefinition(label="Segundo apellido")
    @Column(name="apel2", length=25)
    public String getApel2() {
        return this.apel2;
    }
    
    public void setApel2(String apel2) {
        this.apel2 = apel2;
    }
    
	@DataDefinition(label="Nombre")
    @Column(name="nombre", length=25)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    
	@DataDefinition(label="Tipo Via")
    @Column(name="tipovia", length=2)
    public String getTipovia() {
        return this.tipovia;
    }
    
    public void setTipovia(String tipovia) {
        this.tipovia = tipovia;
    }
    
	@DataDefinition(label="Nombre Via")
    @Column(name="nomvia", length=40)
    public String getNomvia() {
        return this.nomvia;
    }
    
    public void setNomvia(String nomvia) {
        this.nomvia = nomvia;
    }
    
	@DataDefinition(label="Numero")
    @Column(name="numero", length=5)
    public String getNumero() {
        return this.numero;
    }
    
    public void setNumero(String numero) {
        this.numero = numero;
    }
    
	@DataDefinition(label="Bloque")
    @Column(name="bloque", length=2)
    public String getBloque() {
        return this.bloque;
    }
    
    public void setBloque(String bloque) {
        this.bloque = bloque;
    }
    
	@DataDefinition(label="Escalera")
    @Column(name="escalera", length=2)
    public String getEscalera() {
        return this.escalera;
    }
    
    public void setEscalera(String escalera) {
        this.escalera = escalera;
    }
    
	@DataDefinition(label="Piso")
    @Column(name="piso", length=2)
    public String getPiso() {
        return this.piso;
    }
    
    public void setPiso(String piso) {
        this.piso = piso;
    }
    
	@DataDefinition(label="Puerta")
    @Column(name="puerta", length=3)
    public String getPuerta() {
        return this.puerta;
    }
    
    public void setPuerta(String puerta) {
        this.puerta = puerta;
    }
    
	@DataDefinition(label="Codigo Postal")
    @Column(name="codpos", length=5)
    public String getCodpos() {
        return this.codpos;
    }
    
    public void setCodpos(String codpos) {
        this.codpos = codpos;
    }
    
	@DataDefinition(label="Municipio-Entidad")
    @Column(name="munic", length=9)
    public String getMunic() {
        return this.munic;
    }
    
    public void setMunic(String munic) {
        this.munic = munic;
    }
    
	@DataDefinition(label="Localidad")
    @Column(name="localidad", length=24)
    public String getLocalidad() {
        return this.localidad;
    }
    
    public void setLocalidad(String localidad) {
        this.localidad = localidad;
    }
    
	@DataDefinition(label="Provincia")
    @Column(name="provincia", length=15)
    public String getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(String provincia) {
        this.provincia = provincia;
    }
    
	@DataDefinition(label="Accion")
    @Column(name="accion", length=3)
    public String getAccion() {
        return this.accion;
    }
    
    public void setAccion(String accion) {
        this.accion = accion;
    }
    
	@DataDefinition(label="Situacion")
    @Column(name="situacion", length=2)
    public String getSituacion() {
        return this.situacion;
    }
    
    public void setSituacion(String situacion) {
        this.situacion = situacion;
    }
    @Temporal(TemporalType.DATE)
	@DataDefinition(label="Fecha Real")
    @Column(name="fecreal", length=10)
    public Date getFecreal() {
        return this.fecreal;
    }
    
    public void setFecreal(Date fecreal) {
        this.fecreal = fecreal;
    }
    
	@DataDefinition(label="Grupo cotizacion")
    @Column(name="grucot", length=2)
    public String getGrucot() {
        return this.grucot;
    }
    
    public void setGrucot(String grucot) {
        this.grucot = grucot;
    }
    
	@DataDefinition(label="Epigrafe de A.T.")
    @Column(name="epigat", length=3)
    public String getEpigat() {
        return this.epigat;
    }
    
    public void setEpigat(String epigat) {
        this.epigat = epigat;
    }
    
	@DataDefinition(label="Contrato de trabajo")
    @Column(name="contrab", length=3)
    public String getContrab() {
        return this.contrab;
    }
    
    public void setContrab(String contrab) {
        this.contrab = contrab;
    }
    
	@DataDefinition(label="Coeficiente tiempo parcial")
    @Column(name="coeftp", length=3)
    public String getCoeftp() {
        return this.coeftp;
    }
    
    public void setCoeftp(String coeftp) {
        this.coeftp = coeftp;
    }
    
	@DataDefinition(label="Indicador impresion")
    @Column(name="indimp", length=1)
    public String getIndimp() {
        return this.indimp;
    }
    
    public void setIndimp(String indimp) {
        this.indimp = indimp;
    }
    
	@DataDefinition(label="Dias trabajados")
    @Column(name="diastrab", length=3)
    public String getDiastrab() {
        return this.diastrab;
    }
    
    public void setDiastrab(String diastrab) {
        this.diastrab = diastrab;
    }
    
	@DataDefinition(label="Coeficiente de permanencia")
    @Column(name="coefper", precision=3)
    public BigDecimal getCoefper() {
        return this.coefper;
    }
    
    public void setCoefper(BigDecimal coefper) {
        this.coefper = coefper;
    }
    @Temporal(TemporalType.DATE)
	@DataDefinition(label="Fecha Nacimiento")
    @Column(name="fecnac", length=10)
    public Date getFecnac() {
        return this.fecnac;
    }
    
    public void setFecnac(Date fecnac) {
        this.fecnac = fecnac;
    }
    
	@DataDefinition(label="Sexo")
    @Column(name="sexo", length=1)
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    
	@DataDefinition(label="Categoria profesional")
    @Column(name="catprof", length=6)
    public String getCatprof() {
        return this.catprof;
    }
    
    public void setCatprof(String catprof) {
        this.catprof = catprof;
    }
    
	@DataDefinition(label="Numero identificacion trabajador")
    @Column(name="alfaclave", length=14)
    public String getAlfaclave() {
        return this.alfaclave;
    }
    
    public void setAlfaclave(String alfaclave) {
        this.alfaclave = alfaclave;
    }
    
	@DataDefinition(label="Entidad menor")
    @Column(name="entidad", length=28)
    public String getEntidad() {
        return this.entidad;
    }
    
    public void setEntidad(String entidad) {
        this.entidad = entidad;
    }
    
	@DataDefinition(label="Colectivo del trabajador")
    @Column(name="coltrab", length=3)
    public String getColtrab() {
        return this.coltrab;
    }
    
    public void setColtrab(String coltrab) {
        this.coltrab = coltrab;
    }
    
	@DataDefinition(label="Tipo empresario")
    @Column(name="calemp", length=2)
    public String getCalemp() {
        return this.calemp;
    }
    
    public void setCalemp(String calemp) {
        this.calemp = calemp;
    }
    
	@DataDefinition(label="Regimen S.S.")
    @Column(name="regss", length=4)
    public String getRegss() {
        return this.regss;
    }
    
    public void setRegss(String regss) {
        this.regss = regss;
    }
    
	@DataDefinition(label="Relacion Laboral de Caracter Especial")
    @Column(name="rlabcaresp", length=4)
    public String getRlabcaresp() {
        return this.rlabcaresp;
    }
    
    public void setRlabcaresp(String rlabcaresp) {
        this.rlabcaresp = rlabcaresp;
    }
    
	@DataDefinition(label="Provincia de S.S. del Trabajador Sustituido")
    @Column(name="provsstrasust", length=2)
    public String getProvsstrasust() {
        return this.provsstrasust;
    }
    
    public void setProvsstrasust(String provsstrasust) {
        this.provsstrasust = provsstrasust;
    }
    
	@DataDefinition(label="Numero de S.S. del Trabajador Sustituido")
    @Column(name="numsstrasust", length=10)
    public String getNumsstrasust() {
        return this.numsstrasust;
    }
    
    public void setNumsstrasust(String numsstrasust) {
        this.numsstrasust = numsstrasust;
    }
    
	@DataDefinition(label="Causa de Sustitucion")
    @Column(name="causasust", length=1)
    public String getCausasust() {
        return this.causasust;
    }
    
    public void setCausasust(String causasust) {
        this.causasust = causasust;
    }
    
	@DataDefinition(label="Autorización para trabajar")
    @Column(name="autorizacion", length=3)
    public String getAutorizacion() {
        return this.autorizacion;
    }
    
    public void setAutorizacion(String autorizacion) {
        this.autorizacion = autorizacion;
    }
    @Temporal(TemporalType.DATE)
	@DataDefinition(label="Fecha autorización")
    @Column(name="fecaut", length=10)
    public Date getFecaut() {
        return this.fecaut;
    }
    
    public void setFecaut(Date fecaut) {
        this.fecaut = fecaut;
    }
    @Temporal(TemporalType.DATE)
	@DataDefinition(label="Fecha de Inicio de Contrato")
    @Column(name="fecinicont", length=10)
    public Date getFecinicont() {
        return this.fecinicont;
    }
    
    public void setFecinicont(Date fecinicont) {
        this.fecinicont = fecinicont;
    }
    
	@DataDefinition(label="Indicador de subrogacion parcial")
    @Column(name="indsubrog", length=1)
    public String getIndsubrog() {
        return this.indsubrog;
    }
    
    public void setIndsubrog(String indsubrog) {
        this.indsubrog = indsubrog;
    }
    
	@DataDefinition(label="Empresa Origen del Contrato")
    @Column(name="emporigen", length=21)
    public String getEmporigen() {
        return this.emporigen;
    }
    
    public void setEmporigen(String emporigen) {
        this.emporigen = emporigen;
    }
    
	@DataDefinition(label="Trabajadores con exclusion de cotizacion")
    @Column(name="excoti", length=43)
    public String getExcoti() {
        return this.excoti;
    }
    
    public void setExcoti(String excoti) {
        this.excoti = excoti;
    }
    
	@DataDefinition(label="Provincia del CCC del empresario usuario")
    @Column(name="provempusu", length=2)
    public String getProvempusu() {
        return this.provempusu;
    }
    
    public void setProvempusu(String provempusu) {
        this.provempusu = provempusu;
    }
    
	@DataDefinition(label="Numero de CCC del empresario usuario")
    @Column(name="numempusu", length=9)
    public String getNumempusu() {
        return this.numempusu;
    }
    
    public void setNumempusu(String numempusu) {
        this.numempusu = numempusu;
    }
    
	@DataDefinition(label="Contrato Interno")
    @Column(name="contrint", length=2)
    public String getContrint() {
        return this.contrint;
    }
    
    public void setContrint(String contrint) {
        this.contrint = contrint;
    }
    
	@DataDefinition(label="Pariente 1º o 2º Grado")
    @Column(name="pariente", length=1)
    public String getPariente() {
        return this.pariente;
    }
    
    public void setPariente(String pariente) {
        this.pariente = pariente;
    }
    
	@DataDefinition(label="Denominación de la Explotación")
    @Column(name="embarcacion", length=40)
    public String getEmbarcacion() {
        return this.embarcacion;
    }
    
    public void setEmbarcacion(String embarcacion) {
        this.embarcacion = embarcacion;
    }
    
	@DataDefinition(label="Ocupación")
    @Column(name="ocupacion", length=1)
    public String getOcupacion() {
        return this.ocupacion;
    }
    
    public void setOcupacion(String ocupacion) {
        this.ocupacion = ocupacion;
    }


}


