package es.code.nominasta.entity;
// Generated by Expand 2.0.1 

import com.transtools.expand.annotation.Lines;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Linautom generated by Expand 2.0.1
 */
@Entity
@Lines(joinProperty="automat")
@Table(name="linautom")
public class Linautom  implements java.io.Serializable {

     private LinautomId id;
     private Automat automat;

    public Linautom() {
    }
	
    public Linautom(LinautomId id) {
        this.id = id;
    }

    public Linautom(LinautomId id, Automat automat) {
       this.id = id;
       this.automat = automat;
    }

    @EmbeddedId    
    @AttributeOverrides( {
        @AttributeOverride(name="cdg", column=@Column(name="cdg", nullable=false, length=4) ), 
        @AttributeOverride(name="codigo", column=@Column(name="codigo", nullable=false, length=4) ) } )
    public LinautomId getId() {
        return this.id;
    }
    
    public void setId(LinautomId id) {
        this.id = id;
    }
    
	@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cdg", insertable=false, updatable=false)
    public Automat getAutomat() {
        return this.automat;
    }
    
    public void setAutomat(Automat automat) {
        this.automat = automat;
    }


}


