package es.code.nominasta.entity;
// Generated by Expand 2.0.1 

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Nszcopa generated by Expand 2.0.1
 */
@Entity
@Table(name="nszcopa")
public class Nszcopa  implements java.io.Serializable {

     private NszcopaId id;

    public Nszcopa() {
    }

    public Nszcopa(NszcopaId id) {
       this.id = id;
    }

    @EmbeddedId    
    @AttributeOverrides( {
        @AttributeOverride(name="spg0", column=@Column(name="spg0", nullable=false, length=4) ), 
        @AttributeOverride(name="spg1", column=@Column(name="spg1", nullable=false, length=4) ), 
        @AttributeOverride(name="spg2", column=@Column(name="spg2", nullable=false, length=1) ), 
        @AttributeOverride(name="spg3", column=@Column(name="spg3", nullable=false, length=4) ), 
        @AttributeOverride(name="spg4", column=@Column(name="spg4", nullable=false, length=1) ), 
        @AttributeOverride(name="spg5", column=@Column(name="spg5", nullable=false, length=4) ), 
        @AttributeOverride(name="spg6", column=@Column(name="spg6", nullable=false, length=1) ), 
        @AttributeOverride(name="spg7", column=@Column(name="spg7", nullable=false, length=16) ) } )
    public NszcopaId getId() {
        return this.id;
    }
    
    public void setId(NszcopaId id) {
        this.id = id;
    }


}


