package es.code.nominasta.entity;
// Generated by Expand 2.0.1 

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NszemprId generated by Expand 2.0.1
 */
@Embeddable
public class NszemprId  implements java.io.Serializable {

     private String sem0;
     private String sem1;
     private Integer nem0;
     private Integer nem1;
     private Integer nem2;
     private Integer nem3;
     private Integer nem4;
     private Integer nem5;
     private Integer nem6;
     private Integer nem7;
     private Integer nem8;
     private Integer nem9;
     private Integer nem10;
     private Integer nem11;
     private Integer nem12;
     private Integer nem13;
     private Integer nem14;
     private Integer nem15;
     private Integer nem16;
     private Integer nem17;
     private Integer nem18;
     private Integer nem19;
     private Integer nem20;
     private Integer nem21;
     private Integer nem22;
     private Integer nem23;
     private Integer nem24;
     private Integer nem25;
     private Integer nem26;
     private Integer nem27;
     private Integer nem28;
     private Integer nem29;
     private Integer nem30;
     private Integer nem31;
     private Integer nem32;
     private Integer nem33;
     private Integer nem34;
     private Integer nem35;
     private Integer nem36;
     private Integer nem37;
     private Integer nem38;
     private Integer nem39;
     private Integer nem40;
     private Integer nem41;
     private Integer nem42;
     private Integer nem43;
     private Integer nem44;
     private Integer nem45;
     private Integer nem46;
     private Integer nem47;
     private Integer nem48;
     private Integer nem49;
     private Integer nem50;
     private Integer nem51;
     private Integer nem52;
     private Integer nem53;
     private Integer nem54;
     private Integer nem55;
     private Integer nem56;
     private Integer nem57;
     private Integer nem58;
     private Integer nem59;
     private Integer nem60;
     private Integer nem61;
     private Integer nem62;
     private Integer nem63;
     private Integer nem64;
     private Integer nem65;

    public NszemprId() {
    }

    public NszemprId(String sem0, String sem1, Integer nem0, Integer nem1, Integer nem2, Integer nem3, Integer nem4, Integer nem5, Integer nem6, Integer nem7, Integer nem8, Integer nem9, Integer nem10, Integer nem11, Integer nem12, Integer nem13, Integer nem14, Integer nem15, Integer nem16, Integer nem17, Integer nem18, Integer nem19, Integer nem20, Integer nem21, Integer nem22, Integer nem23, Integer nem24, Integer nem25, Integer nem26, Integer nem27, Integer nem28, Integer nem29, Integer nem30, Integer nem31, Integer nem32, Integer nem33, Integer nem34, Integer nem35, Integer nem36, Integer nem37, Integer nem38, Integer nem39, Integer nem40, Integer nem41, Integer nem42, Integer nem43, Integer nem44, Integer nem45, Integer nem46, Integer nem47, Integer nem48, Integer nem49, Integer nem50, Integer nem51, Integer nem52, Integer nem53, Integer nem54, Integer nem55, Integer nem56, Integer nem57, Integer nem58, Integer nem59, Integer nem60, Integer nem61, Integer nem62, Integer nem63, Integer nem64, Integer nem65) {
       this.sem0 = sem0;
       this.sem1 = sem1;
       this.nem0 = nem0;
       this.nem1 = nem1;
       this.nem2 = nem2;
       this.nem3 = nem3;
       this.nem4 = nem4;
       this.nem5 = nem5;
       this.nem6 = nem6;
       this.nem7 = nem7;
       this.nem8 = nem8;
       this.nem9 = nem9;
       this.nem10 = nem10;
       this.nem11 = nem11;
       this.nem12 = nem12;
       this.nem13 = nem13;
       this.nem14 = nem14;
       this.nem15 = nem15;
       this.nem16 = nem16;
       this.nem17 = nem17;
       this.nem18 = nem18;
       this.nem19 = nem19;
       this.nem20 = nem20;
       this.nem21 = nem21;
       this.nem22 = nem22;
       this.nem23 = nem23;
       this.nem24 = nem24;
       this.nem25 = nem25;
       this.nem26 = nem26;
       this.nem27 = nem27;
       this.nem28 = nem28;
       this.nem29 = nem29;
       this.nem30 = nem30;
       this.nem31 = nem31;
       this.nem32 = nem32;
       this.nem33 = nem33;
       this.nem34 = nem34;
       this.nem35 = nem35;
       this.nem36 = nem36;
       this.nem37 = nem37;
       this.nem38 = nem38;
       this.nem39 = nem39;
       this.nem40 = nem40;
       this.nem41 = nem41;
       this.nem42 = nem42;
       this.nem43 = nem43;
       this.nem44 = nem44;
       this.nem45 = nem45;
       this.nem46 = nem46;
       this.nem47 = nem47;
       this.nem48 = nem48;
       this.nem49 = nem49;
       this.nem50 = nem50;
       this.nem51 = nem51;
       this.nem52 = nem52;
       this.nem53 = nem53;
       this.nem54 = nem54;
       this.nem55 = nem55;
       this.nem56 = nem56;
       this.nem57 = nem57;
       this.nem58 = nem58;
       this.nem59 = nem59;
       this.nem60 = nem60;
       this.nem61 = nem61;
       this.nem62 = nem62;
       this.nem63 = nem63;
       this.nem64 = nem64;
       this.nem65 = nem65;
    }


    @Column(name="sem0", nullable=false, length=5)
    public String getSem0() {
        return this.sem0;
    }
    
    public void setSem0(String sem0) {
        this.sem0 = sem0;
    }

    @Column(name="sem1", nullable=false, length=270)
    public String getSem1() {
        return this.sem1;
    }
    
    public void setSem1(String sem1) {
        this.sem1 = sem1;
    }

    @Column(name="nem0", nullable=false, length=4)
    public Integer getNem0() {
        return this.nem0;
    }
    
    public void setNem0(Integer nem0) {
        this.nem0 = nem0;
    }

    @Column(name="nem1", nullable=false, length=4)
    public Integer getNem1() {
        return this.nem1;
    }
    
    public void setNem1(Integer nem1) {
        this.nem1 = nem1;
    }

    @Column(name="nem2", nullable=false, length=4)
    public Integer getNem2() {
        return this.nem2;
    }
    
    public void setNem2(Integer nem2) {
        this.nem2 = nem2;
    }

    @Column(name="nem3", nullable=false, length=4)
    public Integer getNem3() {
        return this.nem3;
    }
    
    public void setNem3(Integer nem3) {
        this.nem3 = nem3;
    }

    @Column(name="nem4", nullable=false, length=4)
    public Integer getNem4() {
        return this.nem4;
    }
    
    public void setNem4(Integer nem4) {
        this.nem4 = nem4;
    }

    @Column(name="nem5", nullable=false, length=4)
    public Integer getNem5() {
        return this.nem5;
    }
    
    public void setNem5(Integer nem5) {
        this.nem5 = nem5;
    }

    @Column(name="nem6", nullable=false, length=4)
    public Integer getNem6() {
        return this.nem6;
    }
    
    public void setNem6(Integer nem6) {
        this.nem6 = nem6;
    }

    @Column(name="nem7", nullable=false, length=4)
    public Integer getNem7() {
        return this.nem7;
    }
    
    public void setNem7(Integer nem7) {
        this.nem7 = nem7;
    }

    @Column(name="nem8", nullable=false, length=4)
    public Integer getNem8() {
        return this.nem8;
    }
    
    public void setNem8(Integer nem8) {
        this.nem8 = nem8;
    }

    @Column(name="nem9", nullable=false, length=4)
    public Integer getNem9() {
        return this.nem9;
    }
    
    public void setNem9(Integer nem9) {
        this.nem9 = nem9;
    }

    @Column(name="nem10", nullable=false, length=4)
    public Integer getNem10() {
        return this.nem10;
    }
    
    public void setNem10(Integer nem10) {
        this.nem10 = nem10;
    }

    @Column(name="nem11", nullable=false, length=4)
    public Integer getNem11() {
        return this.nem11;
    }
    
    public void setNem11(Integer nem11) {
        this.nem11 = nem11;
    }

    @Column(name="nem12", nullable=false, length=4)
    public Integer getNem12() {
        return this.nem12;
    }
    
    public void setNem12(Integer nem12) {
        this.nem12 = nem12;
    }

    @Column(name="nem13", nullable=false, length=4)
    public Integer getNem13() {
        return this.nem13;
    }
    
    public void setNem13(Integer nem13) {
        this.nem13 = nem13;
    }

    @Column(name="nem14", nullable=false, length=4)
    public Integer getNem14() {
        return this.nem14;
    }
    
    public void setNem14(Integer nem14) {
        this.nem14 = nem14;
    }

    @Column(name="nem15", nullable=false, length=4)
    public Integer getNem15() {
        return this.nem15;
    }
    
    public void setNem15(Integer nem15) {
        this.nem15 = nem15;
    }

    @Column(name="nem16", nullable=false, length=4)
    public Integer getNem16() {
        return this.nem16;
    }
    
    public void setNem16(Integer nem16) {
        this.nem16 = nem16;
    }

    @Column(name="nem17", nullable=false, length=4)
    public Integer getNem17() {
        return this.nem17;
    }
    
    public void setNem17(Integer nem17) {
        this.nem17 = nem17;
    }

    @Column(name="nem18", nullable=false, length=4)
    public Integer getNem18() {
        return this.nem18;
    }
    
    public void setNem18(Integer nem18) {
        this.nem18 = nem18;
    }

    @Column(name="nem19", nullable=false, length=4)
    public Integer getNem19() {
        return this.nem19;
    }
    
    public void setNem19(Integer nem19) {
        this.nem19 = nem19;
    }

    @Column(name="nem20", nullable=false, length=4)
    public Integer getNem20() {
        return this.nem20;
    }
    
    public void setNem20(Integer nem20) {
        this.nem20 = nem20;
    }

    @Column(name="nem21", nullable=false, length=4)
    public Integer getNem21() {
        return this.nem21;
    }
    
    public void setNem21(Integer nem21) {
        this.nem21 = nem21;
    }

    @Column(name="nem22", nullable=false, length=4)
    public Integer getNem22() {
        return this.nem22;
    }
    
    public void setNem22(Integer nem22) {
        this.nem22 = nem22;
    }

    @Column(name="nem23", nullable=false, length=4)
    public Integer getNem23() {
        return this.nem23;
    }
    
    public void setNem23(Integer nem23) {
        this.nem23 = nem23;
    }

    @Column(name="nem24", nullable=false, length=4)
    public Integer getNem24() {
        return this.nem24;
    }
    
    public void setNem24(Integer nem24) {
        this.nem24 = nem24;
    }

    @Column(name="nem25", nullable=false, length=4)
    public Integer getNem25() {
        return this.nem25;
    }
    
    public void setNem25(Integer nem25) {
        this.nem25 = nem25;
    }

    @Column(name="nem26", nullable=false, length=4)
    public Integer getNem26() {
        return this.nem26;
    }
    
    public void setNem26(Integer nem26) {
        this.nem26 = nem26;
    }

    @Column(name="nem27", nullable=false, length=4)
    public Integer getNem27() {
        return this.nem27;
    }
    
    public void setNem27(Integer nem27) {
        this.nem27 = nem27;
    }

    @Column(name="nem28", nullable=false, length=4)
    public Integer getNem28() {
        return this.nem28;
    }
    
    public void setNem28(Integer nem28) {
        this.nem28 = nem28;
    }

    @Column(name="nem29", nullable=false, length=4)
    public Integer getNem29() {
        return this.nem29;
    }
    
    public void setNem29(Integer nem29) {
        this.nem29 = nem29;
    }

    @Column(name="nem30", nullable=false, length=4)
    public Integer getNem30() {
        return this.nem30;
    }
    
    public void setNem30(Integer nem30) {
        this.nem30 = nem30;
    }

    @Column(name="nem31", nullable=false, length=4)
    public Integer getNem31() {
        return this.nem31;
    }
    
    public void setNem31(Integer nem31) {
        this.nem31 = nem31;
    }

    @Column(name="nem32", nullable=false, length=4)
    public Integer getNem32() {
        return this.nem32;
    }
    
    public void setNem32(Integer nem32) {
        this.nem32 = nem32;
    }

    @Column(name="nem33", nullable=false, length=4)
    public Integer getNem33() {
        return this.nem33;
    }
    
    public void setNem33(Integer nem33) {
        this.nem33 = nem33;
    }

    @Column(name="nem34", nullable=false, length=4)
    public Integer getNem34() {
        return this.nem34;
    }
    
    public void setNem34(Integer nem34) {
        this.nem34 = nem34;
    }

    @Column(name="nem35", nullable=false, length=4)
    public Integer getNem35() {
        return this.nem35;
    }
    
    public void setNem35(Integer nem35) {
        this.nem35 = nem35;
    }

    @Column(name="nem36", nullable=false, length=4)
    public Integer getNem36() {
        return this.nem36;
    }
    
    public void setNem36(Integer nem36) {
        this.nem36 = nem36;
    }

    @Column(name="nem37", nullable=false, length=4)
    public Integer getNem37() {
        return this.nem37;
    }
    
    public void setNem37(Integer nem37) {
        this.nem37 = nem37;
    }

    @Column(name="nem38", nullable=false, length=4)
    public Integer getNem38() {
        return this.nem38;
    }
    
    public void setNem38(Integer nem38) {
        this.nem38 = nem38;
    }

    @Column(name="nem39", nullable=false, length=4)
    public Integer getNem39() {
        return this.nem39;
    }
    
    public void setNem39(Integer nem39) {
        this.nem39 = nem39;
    }

    @Column(name="nem40", nullable=false, length=4)
    public Integer getNem40() {
        return this.nem40;
    }
    
    public void setNem40(Integer nem40) {
        this.nem40 = nem40;
    }

    @Column(name="nem41", nullable=false, length=4)
    public Integer getNem41() {
        return this.nem41;
    }
    
    public void setNem41(Integer nem41) {
        this.nem41 = nem41;
    }

    @Column(name="nem42", nullable=false, length=4)
    public Integer getNem42() {
        return this.nem42;
    }
    
    public void setNem42(Integer nem42) {
        this.nem42 = nem42;
    }

    @Column(name="nem43", nullable=false, length=4)
    public Integer getNem43() {
        return this.nem43;
    }
    
    public void setNem43(Integer nem43) {
        this.nem43 = nem43;
    }

    @Column(name="nem44", nullable=false, length=4)
    public Integer getNem44() {
        return this.nem44;
    }
    
    public void setNem44(Integer nem44) {
        this.nem44 = nem44;
    }

    @Column(name="nem45", nullable=false, length=4)
    public Integer getNem45() {
        return this.nem45;
    }
    
    public void setNem45(Integer nem45) {
        this.nem45 = nem45;
    }

    @Column(name="nem46", nullable=false, length=4)
    public Integer getNem46() {
        return this.nem46;
    }
    
    public void setNem46(Integer nem46) {
        this.nem46 = nem46;
    }

    @Column(name="nem47", nullable=false, length=4)
    public Integer getNem47() {
        return this.nem47;
    }
    
    public void setNem47(Integer nem47) {
        this.nem47 = nem47;
    }

    @Column(name="nem48", nullable=false, length=4)
    public Integer getNem48() {
        return this.nem48;
    }
    
    public void setNem48(Integer nem48) {
        this.nem48 = nem48;
    }

    @Column(name="nem49", nullable=false, length=4)
    public Integer getNem49() {
        return this.nem49;
    }
    
    public void setNem49(Integer nem49) {
        this.nem49 = nem49;
    }

    @Column(name="nem50", nullable=false, length=4)
    public Integer getNem50() {
        return this.nem50;
    }
    
    public void setNem50(Integer nem50) {
        this.nem50 = nem50;
    }

    @Column(name="nem51", nullable=false, length=4)
    public Integer getNem51() {
        return this.nem51;
    }
    
    public void setNem51(Integer nem51) {
        this.nem51 = nem51;
    }

    @Column(name="nem52", nullable=false, length=4)
    public Integer getNem52() {
        return this.nem52;
    }
    
    public void setNem52(Integer nem52) {
        this.nem52 = nem52;
    }

    @Column(name="nem53", nullable=false, length=4)
    public Integer getNem53() {
        return this.nem53;
    }
    
    public void setNem53(Integer nem53) {
        this.nem53 = nem53;
    }

    @Column(name="nem54", nullable=false, length=4)
    public Integer getNem54() {
        return this.nem54;
    }
    
    public void setNem54(Integer nem54) {
        this.nem54 = nem54;
    }

    @Column(name="nem55", nullable=false, length=4)
    public Integer getNem55() {
        return this.nem55;
    }
    
    public void setNem55(Integer nem55) {
        this.nem55 = nem55;
    }

    @Column(name="nem56", nullable=false, length=4)
    public Integer getNem56() {
        return this.nem56;
    }
    
    public void setNem56(Integer nem56) {
        this.nem56 = nem56;
    }

    @Column(name="nem57", nullable=false, length=4)
    public Integer getNem57() {
        return this.nem57;
    }
    
    public void setNem57(Integer nem57) {
        this.nem57 = nem57;
    }

    @Column(name="nem58", nullable=false, length=4)
    public Integer getNem58() {
        return this.nem58;
    }
    
    public void setNem58(Integer nem58) {
        this.nem58 = nem58;
    }

    @Column(name="nem59", nullable=false, length=4)
    public Integer getNem59() {
        return this.nem59;
    }
    
    public void setNem59(Integer nem59) {
        this.nem59 = nem59;
    }

    @Column(name="nem60", nullable=false, length=4)
    public Integer getNem60() {
        return this.nem60;
    }
    
    public void setNem60(Integer nem60) {
        this.nem60 = nem60;
    }

    @Column(name="nem61", nullable=false, length=4)
    public Integer getNem61() {
        return this.nem61;
    }
    
    public void setNem61(Integer nem61) {
        this.nem61 = nem61;
    }

    @Column(name="nem62", nullable=false, length=4)
    public Integer getNem62() {
        return this.nem62;
    }
    
    public void setNem62(Integer nem62) {
        this.nem62 = nem62;
    }

    @Column(name="nem63", nullable=false, length=4)
    public Integer getNem63() {
        return this.nem63;
    }
    
    public void setNem63(Integer nem63) {
        this.nem63 = nem63;
    }

    @Column(name="nem64", nullable=false, length=4)
    public Integer getNem64() {
        return this.nem64;
    }
    
    public void setNem64(Integer nem64) {
        this.nem64 = nem64;
    }

    @Column(name="nem65", nullable=false, length=4)
    public Integer getNem65() {
        return this.nem65;
    }
    
    public void setNem65(Integer nem65) {
        this.nem65 = nem65;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof NszemprId) ) return false;
		 NszemprId castOther = ( NszemprId ) other; 
         
		 return ( (this.getSem0()==castOther.getSem0()) || ( this.getSem0()!=null && castOther.getSem0()!=null && this.getSem0().equals(castOther.getSem0()) ) )
 && ( (this.getSem1()==castOther.getSem1()) || ( this.getSem1()!=null && castOther.getSem1()!=null && this.getSem1().equals(castOther.getSem1()) ) )
 && ( (this.getNem0()==castOther.getNem0()) || ( this.getNem0()!=null && castOther.getNem0()!=null && this.getNem0().equals(castOther.getNem0()) ) )
 && ( (this.getNem1()==castOther.getNem1()) || ( this.getNem1()!=null && castOther.getNem1()!=null && this.getNem1().equals(castOther.getNem1()) ) )
 && ( (this.getNem2()==castOther.getNem2()) || ( this.getNem2()!=null && castOther.getNem2()!=null && this.getNem2().equals(castOther.getNem2()) ) )
 && ( (this.getNem3()==castOther.getNem3()) || ( this.getNem3()!=null && castOther.getNem3()!=null && this.getNem3().equals(castOther.getNem3()) ) )
 && ( (this.getNem4()==castOther.getNem4()) || ( this.getNem4()!=null && castOther.getNem4()!=null && this.getNem4().equals(castOther.getNem4()) ) )
 && ( (this.getNem5()==castOther.getNem5()) || ( this.getNem5()!=null && castOther.getNem5()!=null && this.getNem5().equals(castOther.getNem5()) ) )
 && ( (this.getNem6()==castOther.getNem6()) || ( this.getNem6()!=null && castOther.getNem6()!=null && this.getNem6().equals(castOther.getNem6()) ) )
 && ( (this.getNem7()==castOther.getNem7()) || ( this.getNem7()!=null && castOther.getNem7()!=null && this.getNem7().equals(castOther.getNem7()) ) )
 && ( (this.getNem8()==castOther.getNem8()) || ( this.getNem8()!=null && castOther.getNem8()!=null && this.getNem8().equals(castOther.getNem8()) ) )
 && ( (this.getNem9()==castOther.getNem9()) || ( this.getNem9()!=null && castOther.getNem9()!=null && this.getNem9().equals(castOther.getNem9()) ) )
 && ( (this.getNem10()==castOther.getNem10()) || ( this.getNem10()!=null && castOther.getNem10()!=null && this.getNem10().equals(castOther.getNem10()) ) )
 && ( (this.getNem11()==castOther.getNem11()) || ( this.getNem11()!=null && castOther.getNem11()!=null && this.getNem11().equals(castOther.getNem11()) ) )
 && ( (this.getNem12()==castOther.getNem12()) || ( this.getNem12()!=null && castOther.getNem12()!=null && this.getNem12().equals(castOther.getNem12()) ) )
 && ( (this.getNem13()==castOther.getNem13()) || ( this.getNem13()!=null && castOther.getNem13()!=null && this.getNem13().equals(castOther.getNem13()) ) )
 && ( (this.getNem14()==castOther.getNem14()) || ( this.getNem14()!=null && castOther.getNem14()!=null && this.getNem14().equals(castOther.getNem14()) ) )
 && ( (this.getNem15()==castOther.getNem15()) || ( this.getNem15()!=null && castOther.getNem15()!=null && this.getNem15().equals(castOther.getNem15()) ) )
 && ( (this.getNem16()==castOther.getNem16()) || ( this.getNem16()!=null && castOther.getNem16()!=null && this.getNem16().equals(castOther.getNem16()) ) )
 && ( (this.getNem17()==castOther.getNem17()) || ( this.getNem17()!=null && castOther.getNem17()!=null && this.getNem17().equals(castOther.getNem17()) ) )
 && ( (this.getNem18()==castOther.getNem18()) || ( this.getNem18()!=null && castOther.getNem18()!=null && this.getNem18().equals(castOther.getNem18()) ) )
 && ( (this.getNem19()==castOther.getNem19()) || ( this.getNem19()!=null && castOther.getNem19()!=null && this.getNem19().equals(castOther.getNem19()) ) )
 && ( (this.getNem20()==castOther.getNem20()) || ( this.getNem20()!=null && castOther.getNem20()!=null && this.getNem20().equals(castOther.getNem20()) ) )
 && ( (this.getNem21()==castOther.getNem21()) || ( this.getNem21()!=null && castOther.getNem21()!=null && this.getNem21().equals(castOther.getNem21()) ) )
 && ( (this.getNem22()==castOther.getNem22()) || ( this.getNem22()!=null && castOther.getNem22()!=null && this.getNem22().equals(castOther.getNem22()) ) )
 && ( (this.getNem23()==castOther.getNem23()) || ( this.getNem23()!=null && castOther.getNem23()!=null && this.getNem23().equals(castOther.getNem23()) ) )
 && ( (this.getNem24()==castOther.getNem24()) || ( this.getNem24()!=null && castOther.getNem24()!=null && this.getNem24().equals(castOther.getNem24()) ) )
 && ( (this.getNem25()==castOther.getNem25()) || ( this.getNem25()!=null && castOther.getNem25()!=null && this.getNem25().equals(castOther.getNem25()) ) )
 && ( (this.getNem26()==castOther.getNem26()) || ( this.getNem26()!=null && castOther.getNem26()!=null && this.getNem26().equals(castOther.getNem26()) ) )
 && ( (this.getNem27()==castOther.getNem27()) || ( this.getNem27()!=null && castOther.getNem27()!=null && this.getNem27().equals(castOther.getNem27()) ) )
 && ( (this.getNem28()==castOther.getNem28()) || ( this.getNem28()!=null && castOther.getNem28()!=null && this.getNem28().equals(castOther.getNem28()) ) )
 && ( (this.getNem29()==castOther.getNem29()) || ( this.getNem29()!=null && castOther.getNem29()!=null && this.getNem29().equals(castOther.getNem29()) ) )
 && ( (this.getNem30()==castOther.getNem30()) || ( this.getNem30()!=null && castOther.getNem30()!=null && this.getNem30().equals(castOther.getNem30()) ) )
 && ( (this.getNem31()==castOther.getNem31()) || ( this.getNem31()!=null && castOther.getNem31()!=null && this.getNem31().equals(castOther.getNem31()) ) )
 && ( (this.getNem32()==castOther.getNem32()) || ( this.getNem32()!=null && castOther.getNem32()!=null && this.getNem32().equals(castOther.getNem32()) ) )
 && ( (this.getNem33()==castOther.getNem33()) || ( this.getNem33()!=null && castOther.getNem33()!=null && this.getNem33().equals(castOther.getNem33()) ) )
 && ( (this.getNem34()==castOther.getNem34()) || ( this.getNem34()!=null && castOther.getNem34()!=null && this.getNem34().equals(castOther.getNem34()) ) )
 && ( (this.getNem35()==castOther.getNem35()) || ( this.getNem35()!=null && castOther.getNem35()!=null && this.getNem35().equals(castOther.getNem35()) ) )
 && ( (this.getNem36()==castOther.getNem36()) || ( this.getNem36()!=null && castOther.getNem36()!=null && this.getNem36().equals(castOther.getNem36()) ) )
 && ( (this.getNem37()==castOther.getNem37()) || ( this.getNem37()!=null && castOther.getNem37()!=null && this.getNem37().equals(castOther.getNem37()) ) )
 && ( (this.getNem38()==castOther.getNem38()) || ( this.getNem38()!=null && castOther.getNem38()!=null && this.getNem38().equals(castOther.getNem38()) ) )
 && ( (this.getNem39()==castOther.getNem39()) || ( this.getNem39()!=null && castOther.getNem39()!=null && this.getNem39().equals(castOther.getNem39()) ) )
 && ( (this.getNem40()==castOther.getNem40()) || ( this.getNem40()!=null && castOther.getNem40()!=null && this.getNem40().equals(castOther.getNem40()) ) )
 && ( (this.getNem41()==castOther.getNem41()) || ( this.getNem41()!=null && castOther.getNem41()!=null && this.getNem41().equals(castOther.getNem41()) ) )
 && ( (this.getNem42()==castOther.getNem42()) || ( this.getNem42()!=null && castOther.getNem42()!=null && this.getNem42().equals(castOther.getNem42()) ) )
 && ( (this.getNem43()==castOther.getNem43()) || ( this.getNem43()!=null && castOther.getNem43()!=null && this.getNem43().equals(castOther.getNem43()) ) )
 && ( (this.getNem44()==castOther.getNem44()) || ( this.getNem44()!=null && castOther.getNem44()!=null && this.getNem44().equals(castOther.getNem44()) ) )
 && ( (this.getNem45()==castOther.getNem45()) || ( this.getNem45()!=null && castOther.getNem45()!=null && this.getNem45().equals(castOther.getNem45()) ) )
 && ( (this.getNem46()==castOther.getNem46()) || ( this.getNem46()!=null && castOther.getNem46()!=null && this.getNem46().equals(castOther.getNem46()) ) )
 && ( (this.getNem47()==castOther.getNem47()) || ( this.getNem47()!=null && castOther.getNem47()!=null && this.getNem47().equals(castOther.getNem47()) ) )
 && ( (this.getNem48()==castOther.getNem48()) || ( this.getNem48()!=null && castOther.getNem48()!=null && this.getNem48().equals(castOther.getNem48()) ) )
 && ( (this.getNem49()==castOther.getNem49()) || ( this.getNem49()!=null && castOther.getNem49()!=null && this.getNem49().equals(castOther.getNem49()) ) )
 && ( (this.getNem50()==castOther.getNem50()) || ( this.getNem50()!=null && castOther.getNem50()!=null && this.getNem50().equals(castOther.getNem50()) ) )
 && ( (this.getNem51()==castOther.getNem51()) || ( this.getNem51()!=null && castOther.getNem51()!=null && this.getNem51().equals(castOther.getNem51()) ) )
 && ( (this.getNem52()==castOther.getNem52()) || ( this.getNem52()!=null && castOther.getNem52()!=null && this.getNem52().equals(castOther.getNem52()) ) )
 && ( (this.getNem53()==castOther.getNem53()) || ( this.getNem53()!=null && castOther.getNem53()!=null && this.getNem53().equals(castOther.getNem53()) ) )
 && ( (this.getNem54()==castOther.getNem54()) || ( this.getNem54()!=null && castOther.getNem54()!=null && this.getNem54().equals(castOther.getNem54()) ) )
 && ( (this.getNem55()==castOther.getNem55()) || ( this.getNem55()!=null && castOther.getNem55()!=null && this.getNem55().equals(castOther.getNem55()) ) )
 && ( (this.getNem56()==castOther.getNem56()) || ( this.getNem56()!=null && castOther.getNem56()!=null && this.getNem56().equals(castOther.getNem56()) ) )
 && ( (this.getNem57()==castOther.getNem57()) || ( this.getNem57()!=null && castOther.getNem57()!=null && this.getNem57().equals(castOther.getNem57()) ) )
 && ( (this.getNem58()==castOther.getNem58()) || ( this.getNem58()!=null && castOther.getNem58()!=null && this.getNem58().equals(castOther.getNem58()) ) )
 && ( (this.getNem59()==castOther.getNem59()) || ( this.getNem59()!=null && castOther.getNem59()!=null && this.getNem59().equals(castOther.getNem59()) ) )
 && ( (this.getNem60()==castOther.getNem60()) || ( this.getNem60()!=null && castOther.getNem60()!=null && this.getNem60().equals(castOther.getNem60()) ) )
 && ( (this.getNem61()==castOther.getNem61()) || ( this.getNem61()!=null && castOther.getNem61()!=null && this.getNem61().equals(castOther.getNem61()) ) )
 && ( (this.getNem62()==castOther.getNem62()) || ( this.getNem62()!=null && castOther.getNem62()!=null && this.getNem62().equals(castOther.getNem62()) ) )
 && ( (this.getNem63()==castOther.getNem63()) || ( this.getNem63()!=null && castOther.getNem63()!=null && this.getNem63().equals(castOther.getNem63()) ) )
 && ( (this.getNem64()==castOther.getNem64()) || ( this.getNem64()!=null && castOther.getNem64()!=null && this.getNem64().equals(castOther.getNem64()) ) )
 && ( (this.getNem65()==castOther.getNem65()) || ( this.getNem65()!=null && castOther.getNem65()!=null && this.getNem65().equals(castOther.getNem65()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getSem0() == null ? 0 : this.getSem0().hashCode() );
         result = 37 * result + ( getSem1() == null ? 0 : this.getSem1().hashCode() );
         result = 37 * result + ( getNem0() == null ? 0 : this.getNem0().hashCode() );
         result = 37 * result + ( getNem1() == null ? 0 : this.getNem1().hashCode() );
         result = 37 * result + ( getNem2() == null ? 0 : this.getNem2().hashCode() );
         result = 37 * result + ( getNem3() == null ? 0 : this.getNem3().hashCode() );
         result = 37 * result + ( getNem4() == null ? 0 : this.getNem4().hashCode() );
         result = 37 * result + ( getNem5() == null ? 0 : this.getNem5().hashCode() );
         result = 37 * result + ( getNem6() == null ? 0 : this.getNem6().hashCode() );
         result = 37 * result + ( getNem7() == null ? 0 : this.getNem7().hashCode() );
         result = 37 * result + ( getNem8() == null ? 0 : this.getNem8().hashCode() );
         result = 37 * result + ( getNem9() == null ? 0 : this.getNem9().hashCode() );
         result = 37 * result + ( getNem10() == null ? 0 : this.getNem10().hashCode() );
         result = 37 * result + ( getNem11() == null ? 0 : this.getNem11().hashCode() );
         result = 37 * result + ( getNem12() == null ? 0 : this.getNem12().hashCode() );
         result = 37 * result + ( getNem13() == null ? 0 : this.getNem13().hashCode() );
         result = 37 * result + ( getNem14() == null ? 0 : this.getNem14().hashCode() );
         result = 37 * result + ( getNem15() == null ? 0 : this.getNem15().hashCode() );
         result = 37 * result + ( getNem16() == null ? 0 : this.getNem16().hashCode() );
         result = 37 * result + ( getNem17() == null ? 0 : this.getNem17().hashCode() );
         result = 37 * result + ( getNem18() == null ? 0 : this.getNem18().hashCode() );
         result = 37 * result + ( getNem19() == null ? 0 : this.getNem19().hashCode() );
         result = 37 * result + ( getNem20() == null ? 0 : this.getNem20().hashCode() );
         result = 37 * result + ( getNem21() == null ? 0 : this.getNem21().hashCode() );
         result = 37 * result + ( getNem22() == null ? 0 : this.getNem22().hashCode() );
         result = 37 * result + ( getNem23() == null ? 0 : this.getNem23().hashCode() );
         result = 37 * result + ( getNem24() == null ? 0 : this.getNem24().hashCode() );
         result = 37 * result + ( getNem25() == null ? 0 : this.getNem25().hashCode() );
         result = 37 * result + ( getNem26() == null ? 0 : this.getNem26().hashCode() );
         result = 37 * result + ( getNem27() == null ? 0 : this.getNem27().hashCode() );
         result = 37 * result + ( getNem28() == null ? 0 : this.getNem28().hashCode() );
         result = 37 * result + ( getNem29() == null ? 0 : this.getNem29().hashCode() );
         result = 37 * result + ( getNem30() == null ? 0 : this.getNem30().hashCode() );
         result = 37 * result + ( getNem31() == null ? 0 : this.getNem31().hashCode() );
         result = 37 * result + ( getNem32() == null ? 0 : this.getNem32().hashCode() );
         result = 37 * result + ( getNem33() == null ? 0 : this.getNem33().hashCode() );
         result = 37 * result + ( getNem34() == null ? 0 : this.getNem34().hashCode() );
         result = 37 * result + ( getNem35() == null ? 0 : this.getNem35().hashCode() );
         result = 37 * result + ( getNem36() == null ? 0 : this.getNem36().hashCode() );
         result = 37 * result + ( getNem37() == null ? 0 : this.getNem37().hashCode() );
         result = 37 * result + ( getNem38() == null ? 0 : this.getNem38().hashCode() );
         result = 37 * result + ( getNem39() == null ? 0 : this.getNem39().hashCode() );
         result = 37 * result + ( getNem40() == null ? 0 : this.getNem40().hashCode() );
         result = 37 * result + ( getNem41() == null ? 0 : this.getNem41().hashCode() );
         result = 37 * result + ( getNem42() == null ? 0 : this.getNem42().hashCode() );
         result = 37 * result + ( getNem43() == null ? 0 : this.getNem43().hashCode() );
         result = 37 * result + ( getNem44() == null ? 0 : this.getNem44().hashCode() );
         result = 37 * result + ( getNem45() == null ? 0 : this.getNem45().hashCode() );
         result = 37 * result + ( getNem46() == null ? 0 : this.getNem46().hashCode() );
         result = 37 * result + ( getNem47() == null ? 0 : this.getNem47().hashCode() );
         result = 37 * result + ( getNem48() == null ? 0 : this.getNem48().hashCode() );
         result = 37 * result + ( getNem49() == null ? 0 : this.getNem49().hashCode() );
         result = 37 * result + ( getNem50() == null ? 0 : this.getNem50().hashCode() );
         result = 37 * result + ( getNem51() == null ? 0 : this.getNem51().hashCode() );
         result = 37 * result + ( getNem52() == null ? 0 : this.getNem52().hashCode() );
         result = 37 * result + ( getNem53() == null ? 0 : this.getNem53().hashCode() );
         result = 37 * result + ( getNem54() == null ? 0 : this.getNem54().hashCode() );
         result = 37 * result + ( getNem55() == null ? 0 : this.getNem55().hashCode() );
         result = 37 * result + ( getNem56() == null ? 0 : this.getNem56().hashCode() );
         result = 37 * result + ( getNem57() == null ? 0 : this.getNem57().hashCode() );
         result = 37 * result + ( getNem58() == null ? 0 : this.getNem58().hashCode() );
         result = 37 * result + ( getNem59() == null ? 0 : this.getNem59().hashCode() );
         result = 37 * result + ( getNem60() == null ? 0 : this.getNem60().hashCode() );
         result = 37 * result + ( getNem61() == null ? 0 : this.getNem61().hashCode() );
         result = 37 * result + ( getNem62() == null ? 0 : this.getNem62().hashCode() );
         result = 37 * result + ( getNem63() == null ? 0 : this.getNem63().hashCode() );
         result = 37 * result + ( getNem64() == null ? 0 : this.getNem64().hashCode() );
         result = 37 * result + ( getNem65() == null ? 0 : this.getNem65().hashCode() );
         return result;
   }   
}


