package es.code.nominasta.entity;
// Generated by Expand 2.0.1 

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Nszodet generated by Expand 2.0.1
 */
@Entity
@Table(name="nszodet")
public class Nszodet  implements java.io.Serializable {

     private NszodetId id;

    public Nszodet() {
    }

    public Nszodet(NszodetId id) {
       this.id = id;
    }

    @EmbeddedId    
    @AttributeOverrides( {
        @AttributeOverride(name="sod0", column=@Column(name="sod0", nullable=false, length=16) ), 
        @AttributeOverride(name="sod1", column=@Column(name="sod1", nullable=false, length=35) ), 
        @AttributeOverride(name="nod0", column=@Column(name="nod0", nullable=false, length=4) ) } )
    public NszodetId getId() {
        return this.id;
    }
    
    public void setId(NszodetId id) {
        this.id = id;
    }


}


