package es.code.nominasta.entity;
// Generated by Expand 2.0.1 

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NszpeopId generated by Expand 2.0.1
 */
@Embeddable
public class NszpeopId  implements java.io.Serializable {

     private String spp0;
     private String spp1;
     private Integer npp0;
     private Integer npp1;
     private Integer npp2;
     private Integer npp3;

    public NszpeopId() {
    }

    public NszpeopId(String spp0, String spp1, Integer npp0, Integer npp1, Integer npp2, Integer npp3) {
       this.spp0 = spp0;
       this.spp1 = spp1;
       this.npp0 = npp0;
       this.npp1 = npp1;
       this.npp2 = npp2;
       this.npp3 = npp3;
    }


    @Column(name="spp0", nullable=false, length=19)
    public String getSpp0() {
        return this.spp0;
    }
    
    public void setSpp0(String spp0) {
        this.spp0 = spp0;
    }

    @Column(name="spp1", nullable=false, length=32)
    public String getSpp1() {
        return this.spp1;
    }
    
    public void setSpp1(String spp1) {
        this.spp1 = spp1;
    }

    @Column(name="npp0", nullable=false, length=4)
    public Integer getNpp0() {
        return this.npp0;
    }
    
    public void setNpp0(Integer npp0) {
        this.npp0 = npp0;
    }

    @Column(name="npp1", nullable=false, length=4)
    public Integer getNpp1() {
        return this.npp1;
    }
    
    public void setNpp1(Integer npp1) {
        this.npp1 = npp1;
    }

    @Column(name="npp2", nullable=false, length=4)
    public Integer getNpp2() {
        return this.npp2;
    }
    
    public void setNpp2(Integer npp2) {
        this.npp2 = npp2;
    }

    @Column(name="npp3", nullable=false, length=4)
    public Integer getNpp3() {
        return this.npp3;
    }
    
    public void setNpp3(Integer npp3) {
        this.npp3 = npp3;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof NszpeopId) ) return false;
		 NszpeopId castOther = ( NszpeopId ) other; 
         
		 return ( (this.getSpp0()==castOther.getSpp0()) || ( this.getSpp0()!=null && castOther.getSpp0()!=null && this.getSpp0().equals(castOther.getSpp0()) ) )
 && ( (this.getSpp1()==castOther.getSpp1()) || ( this.getSpp1()!=null && castOther.getSpp1()!=null && this.getSpp1().equals(castOther.getSpp1()) ) )
 && ( (this.getNpp0()==castOther.getNpp0()) || ( this.getNpp0()!=null && castOther.getNpp0()!=null && this.getNpp0().equals(castOther.getNpp0()) ) )
 && ( (this.getNpp1()==castOther.getNpp1()) || ( this.getNpp1()!=null && castOther.getNpp1()!=null && this.getNpp1().equals(castOther.getNpp1()) ) )
 && ( (this.getNpp2()==castOther.getNpp2()) || ( this.getNpp2()!=null && castOther.getNpp2()!=null && this.getNpp2().equals(castOther.getNpp2()) ) )
 && ( (this.getNpp3()==castOther.getNpp3()) || ( this.getNpp3()!=null && castOther.getNpp3()!=null && this.getNpp3().equals(castOther.getNpp3()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getSpp0() == null ? 0 : this.getSpp0().hashCode() );
         result = 37 * result + ( getSpp1() == null ? 0 : this.getSpp1().hashCode() );
         result = 37 * result + ( getNpp0() == null ? 0 : this.getNpp0().hashCode() );
         result = 37 * result + ( getNpp1() == null ? 0 : this.getNpp1().hashCode() );
         result = 37 * result + ( getNpp2() == null ? 0 : this.getNpp2().hashCode() );
         result = 37 * result + ( getNpp3() == null ? 0 : this.getNpp3().hashCode() );
         return result;
   }   
}


