package es.code.nominasta.entity;
// Generated by Expand 2.0.1 

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NszpocoId generated by Expand 2.0.1
 */
@Embeddable
public class NszpocoId  implements java.io.Serializable {

     private String spz0;
     private String spz1;
     private BigDecimal npz0;
     private BigDecimal npz1;
     private BigDecimal npz2;
     private BigDecimal npz3;

    public NszpocoId() {
    }

    public NszpocoId(String spz0, String spz1, BigDecimal npz0, BigDecimal npz1, BigDecimal npz2, BigDecimal npz3) {
       this.spz0 = spz0;
       this.spz1 = spz1;
       this.npz0 = npz0;
       this.npz1 = npz1;
       this.npz2 = npz2;
       this.npz3 = npz3;
    }


    @Column(name="spz0", nullable=false, length=8)
    public String getSpz0() {
        return this.spz0;
    }
    
    public void setSpz0(String spz0) {
        this.spz0 = spz0;
    }

    @Column(name="spz1", nullable=false, length=40)
    public String getSpz1() {
        return this.spz1;
    }
    
    public void setSpz1(String spz1) {
        this.spz1 = spz1;
    }

    @Column(name="npz0", nullable=false, precision=5)
    public BigDecimal getNpz0() {
        return this.npz0;
    }
    
    public void setNpz0(BigDecimal npz0) {
        this.npz0 = npz0;
    }

    @Column(name="npz1", nullable=false, precision=5)
    public BigDecimal getNpz1() {
        return this.npz1;
    }
    
    public void setNpz1(BigDecimal npz1) {
        this.npz1 = npz1;
    }

    @Column(name="npz2", nullable=false, precision=5)
    public BigDecimal getNpz2() {
        return this.npz2;
    }
    
    public void setNpz2(BigDecimal npz2) {
        this.npz2 = npz2;
    }

    @Column(name="npz3", nullable=false, precision=5)
    public BigDecimal getNpz3() {
        return this.npz3;
    }
    
    public void setNpz3(BigDecimal npz3) {
        this.npz3 = npz3;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof NszpocoId) ) return false;
		 NszpocoId castOther = ( NszpocoId ) other; 
         
		 return ( (this.getSpz0()==castOther.getSpz0()) || ( this.getSpz0()!=null && castOther.getSpz0()!=null && this.getSpz0().equals(castOther.getSpz0()) ) )
 && ( (this.getSpz1()==castOther.getSpz1()) || ( this.getSpz1()!=null && castOther.getSpz1()!=null && this.getSpz1().equals(castOther.getSpz1()) ) )
 && ( (this.getNpz0()==castOther.getNpz0()) || ( this.getNpz0()!=null && castOther.getNpz0()!=null && this.getNpz0().equals(castOther.getNpz0()) ) )
 && ( (this.getNpz1()==castOther.getNpz1()) || ( this.getNpz1()!=null && castOther.getNpz1()!=null && this.getNpz1().equals(castOther.getNpz1()) ) )
 && ( (this.getNpz2()==castOther.getNpz2()) || ( this.getNpz2()!=null && castOther.getNpz2()!=null && this.getNpz2().equals(castOther.getNpz2()) ) )
 && ( (this.getNpz3()==castOther.getNpz3()) || ( this.getNpz3()!=null && castOther.getNpz3()!=null && this.getNpz3().equals(castOther.getNpz3()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getSpz0() == null ? 0 : this.getSpz0().hashCode() );
         result = 37 * result + ( getSpz1() == null ? 0 : this.getSpz1().hashCode() );
         result = 37 * result + ( getNpz0() == null ? 0 : this.getNpz0().hashCode() );
         result = 37 * result + ( getNpz1() == null ? 0 : this.getNpz1().hashCode() );
         result = 37 * result + ( getNpz2() == null ? 0 : this.getNpz2().hashCode() );
         result = 37 * result + ( getNpz3() == null ? 0 : this.getNpz3().hashCode() );
         return result;
   }   
}


