package es.code.nominasta.entity;
// Generated by Expand 2.0.1 

import com.transtools.expand.annotation.DataDefinition;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tipreg generated by Expand 2.0.1
 */
@Entity
@Table(name="tipreg")
public class Tipreg  implements java.io.Serializable {

     private String cdg;
     private String descripcion;
     private List<Regidocu> regidocuList = new ArrayList<Regidocu>(0);

    public Tipreg() {
    }
	
    public Tipreg(String cdg) {
        this.cdg = cdg;
    }

    public Tipreg(String cdg, String descripcion, List<Regidocu> regidocuList) {
       this.cdg = cdg;
       this.descripcion = descripcion;
       this.regidocuList = regidocuList;
    }

    @Id     
	@DataDefinition(label="Codigo de Tipo de Registro")
    @Column(name="cdg", unique=true, nullable=false, length=2)
    public String getCdg() {
        return this.cdg;
    }
    
    public void setCdg(String cdg) {
        this.cdg = cdg;
    }
    
	@DataDefinition(label="Descripcion de Tipo de Registro",descriptionColumn=true)
    @Column(name="descripcion", length=65)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

	@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tipreg")
    public List<Regidocu> getRegidocuList() {
        return this.regidocuList;
    }
    
    public void setRegidocuList(List<Regidocu> regidocuList) {
        this.regidocuList = regidocuList;
    }


}


