<?xml version="1.0" encoding="utf-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

  <modelVersion>4.0.0</modelVersion>
  <groupId>com.code.aon</groupId>
  <artifactId>aon.solutions</artifactId>
  <version>5.0.0</version>
  <packaging>pom</packaging>
  <description>POM de aon Solutions (para sacar versions...)</description>
  <name>aon Solutions</name>

  <properties>
    <aon-version>5.0.0-SNAPSHOT</aon-version>
  </properties>

  <organization>
    <name>esferalia Networks S.A.</name>
    <url>http://www.esferalia.com</url>
  </organization>

  <scm>
    <connection>
    scm:svn:http://dev.esferalia.com/repos/aon-application/trunk</connection>
    <url>http://dev.esferalia.com/websvn/wsvn</url>
  </scm>

  <modules>
    <module>aon-ql</module>
  </modules>

  <build>
    <plugins>
	<plugin>
        	<groupId>org.apache.maven.plugins</groupId>
	        <artifactId>maven-release-plugin</artifactId>
        	<version>2.0</version>
	        <configuration>
			<releaseVersion>${project.version}</releaseVersion>
			<developmentVersion>${project.version}</developmentVersion>
			<autoVersionSubmodules>true</autoVersionSubmodules>

			<tag>${project.version}</tag>
        	  	<tagBase>https://dev.esferalia.com/repos/aon-application/releases</tagBase>
	        </configuration>
	</plugin>
    </plugins>
  </build>

</project>
