<?xml version="1.0"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

	<modelVersion>4.0.0</modelVersion>
	<groupId>com.code.gbp</groupId>
	<artifactId>gbp.parent</artifactId>
	<version>1.0.1</version>
	<packaging>pom</packaging>
	<description>POM padre de los proyectos GBP</description>
	<name>GBP PARENT</name>

	<organization>
		<name>Consulting &amp; Development</name>
		<url>http://www.code.es</url>
	</organization>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>2.0</version>
				<configuration>
					<source>1.5</source>
					<target>1.5</target>
				</configuration>
			</plugin>
			<plugin>
				<artifactId>maven-surefire-plugin</artifactId>
				<configuration>
					<workingDirectory>target</workingDirectory>
				</configuration>
			</plugin>
			<plugin>
				<artifactId>maven-jar-plugin</artifactId>
				<configuration>
					<archive>
						<manifest>
							<addDefaultSpecificationEntries>
								true
							</addDefaultSpecificationEntries>
							<addDefaultImplementationEntries>
								true
							</addDefaultImplementationEntries>
						</manifest>
					</archive>
				</configuration>
			</plugin>
			<plugin>
				<artifactId>maven-source-plugin</artifactId>
				<executions>
					<execution>
						<goals>
							<goal>jar</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>ch.elca.el4j.maven.plugins</groupId>
				<artifactId>maven-depgraph-plugin</artifactId>
				<executions>
					<execution>
						<id>FULLGRAPH</id>
						<phase>install</phase>
						<goals>
							<goal>fullgraph</goal>
						</goals>
						<configuration>
							<outDir>/target/graph</outDir>
							<outFile>
								${pom.artifactId}-${pom.version}-full.png
							</outFile>
						</configuration>
					</execution>
					<execution>
						<id>GBP-FULLGRAPH</id>
						<phase>install</phase>
						<goals>
							<goal>fullgraph</goal>
						</goals>
						<configuration>
							<outDir>/target/graph</outDir>
							<outFile>
								${pom.artifactId}-${pom.version}-gbp.png
							</outFile>
							<groupFilter>com.code.gbp</groupFilter>
						</configuration>
					</execution>
				</executions>
				<version>1.2</version>
			</plugin>
		</plugins>
		<!-- 
			<extensions>
			<extension>
			<groupId>org.apache.maven.wagon</groupId>
			<artifactId>wagon-webdav</artifactId>
			<version>1.0-beta-2</version>
			</extension>
			</extensions>
		-->
	</build>


	<distributionManagement>
		<repository>
			<id>inhouse</id>
			<name>Inhouse Internal Release Repository</name>
			<url>
				scp://192.168.2.4/DOCUMENTOS/MAVEN/maven2_repositories/inhouse
			</url>
			<!-- 
				<url>
				dav:http://192.168.2.4:8080/archiva/repository/inhouse
				</url>
			-->
		</repository>
		<snapshotRepository>
			<id>inhouse_snapshot</id>
			<name>Inhouse Internal Snapshot Repository</name>
			<url>
				scp://192.168.2.4/DOCUMENTOS/MAVEN/maven2_repositories/inhouse_snapshot
			</url>
			<!-- 
				<url>
				dav:http://192.168.2.4:8080/archiva/repository/inhouse_snapshot
				</url>
			-->
		</snapshotRepository>
	</distributionManagement>

	<reporting>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>
					maven-project-info-reports-plugin
				</artifactId>
				<reportSets>
					<reportSet>
						<reports>
							<report>index</report>
							<report>dependencies</report>
							<report>mailing-list</report>
							<report>project-team</report>
							<report>cim</report>
							<report>issue-tracking</report>
							<report>scm</report>
						</reports>
					</reportSet>
				</reportSets>
			</plugin>
			<!-- 
				<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-javadoc-plugin</artifactId>
				</plugin>
			-->
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-jxr-plugin</artifactId>
			</plugin>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>jdepend-maven-plugin</artifactId>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-javadoc-plugin</artifactId>
				<configuration>
					<aggregate>true</aggregate>
					<debug>true</debug>
					<links>
						<link>
							http://java.sun.com/javaee/5/docs/api
						</link>
					</links>
				</configuration>
			</plugin>
		</plugins>
	</reporting>
</project>
