<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>com.code.aon</groupId>
		<artifactId>aon.parent</artifactId>
		<version>8.97.6</version>
	</parent>
	<groupId>net.aonsolutions</groupId>
	<artifactId>aon.tgss</artifactId>
	<name>AON TGSS</name>
	<dependencies>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.8</version>
			<type>jar</type>
			<scope>test</scope>
		</dependency>
	</dependencies>
	<build>
		<plugins>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>jaxb2-maven-plugin</artifactId>
				<version>1.6</version>
				<!-- groupId>org.jvnet.jaxb2.maven2</groupId>
				<artifactId>maven-jaxb2-plugin</artifactId-->
				<executions>
					<execution>
						<id>xjc-request-dba</id>
						<goals>
							<goal>xjc</goal>
						</goals>
						<configuration>
							<schemaFiles>DBA.xsd</schemaFiles>
							<packageName>net.aonsolutions.tgss.creta.jaxb.dba</packageName>
							<clearOutputDir>false</clearOutputDir>
						</configuration>
					</execution>
					<!--  execution>
						<id>xjc-request-employee</id>
						<goals>
							<goal>xjc</goal>
						</goals>
						<configuration>
							<schemaFiles>SolicitudTrabajadoresTramos.xsd</schemaFiles>
							<packageName>net.aonsolutions.tgss.creta.jaxb.solicitud.trabajadorestramos</packageName>
							<clearOutputDir>false</clearOutputDir>
						</configuration>
					</execution>
					<execution>
						<id>xjc-response-employee</id>
						<goals>
							<goal>xjc</goal>
						</goals>
						<configuration>
							<schemaFiles>TrabajadoresTramos.xsd</schemaFiles>
							<packageName>net.aonsolutions.tgss.creta.jaxb.trabajadorestramos</packageName>
							<clearOutputDir>false</clearOutputDir>
						</configuration>
					</execution-->
					<execution>
						<id>xjc-request-draft</id>
						<goals>
							<goal>xjc</goal>
						</goals>
						<configuration>
							<schemaFiles>SolicitudBorrador.xsd</schemaFiles>
							<packageName>net.aonsolutions.tgss.creta.jaxb.solicitud.borrador</packageName>
							<clearOutputDir>false</clearOutputDir>
						</configuration>
					</execution>
					<!--  execution>
						<id>xjc-request-calc</id>
						<goals>
							<goal>xjc</goal>
						</goals>
						<configuration>
							<schemaFiles>SolicitudCalculos.xsd</schemaFiles>
							<packageName>net.aonsolutions.tgss.creta.jaxb.solicitud.calculos</packageName>
							<clearOutputDir>false</clearOutputDir>
						</configuration>
					</execution-->
					<execution>
						<id>xjc-response-calc</id>
						<goals>
							<goal>xjc</goal>
						</goals>
						<configuration>
							<schemaFiles>Calculos.xsd</schemaFiles>
							<packageName>net.aonsolutions.tgss.creta.jaxb.calculos</packageName>
							<clearOutputDir>false</clearOutputDir>
						</configuration>
					</execution>
					<!--  execution>
						<id>xjc-request-confirm</id>
						<goals>
							<goal>xjc</goal>
						</goals>
						<configuration>
							<schemaFiles>SolicitudConfirmacion.xsd</schemaFiles>
							<packageName>net.aonsolutions.tgss.creta.jaxb.solicitud.confirmacion</packageName>
							<clearOutputDir>false</clearOutputDir>
						</configuration>
					</execution-->
					<!--  execution>
						<id>xjc-response</id>
						<goals>
							<goal>xjc</goal>
						</goals>
						<configuration>
    						<schemaFiles>Respuesta.xsd</schemaFiles>
   							<packageName>net.aonsolutions.tgss.creta.jaxb.respuesta</packageName>
							<clearOutputDir>false</clearOutputDir>
						</configuration>
					</execution-->
					<execution>
						<id>xjc-response-bases</id>
						<goals>
							<goal>xjc</goal>
						</goals>
						<configuration>
							<schemaFiles>Bases.xsd</schemaFiles>
							<packageName>net.aonsolutions.tgss.creta.jaxb.bases</packageName>
							<clearOutputDir>false</clearOutputDir>
						</configuration>
					</execution>
					<!-- execution>
						<id>xjc-response-dcl</id>
						<goals>
							<goal>xjc</goal>
						</goals>
						<configuration>
							<schemaFiles>DCL.xsd</schemaFiles>
							<packageName>net.aonsolutions.tgss.creta.jaxb.dcl</packageName>
							<clearOutputDir>false</clearOutputDir>
						</configuration>
					</execution-->
					<execution>
						<id>xjc-response-rlc</id>
						<goals>
							<goal>xjc</goal>
						</goals>
						<configuration>
							<schemaFiles>RLC.xsd</schemaFiles>
							<packageName>net.aonsolutions.tgss.creta.jaxb.rlc</packageName>
							<clearOutputDir>false</clearOutputDir>
						</configuration>
					</execution>
					<!--  execution>
						<id>xjc-response-rnt</id>
						<goals>
							<goal>xjc</goal>
						</goals>
						<configuration>
							<schemaFiles>RNT.xsd</schemaFiles>
							<packageName>net.aonsolutions.tgss.creta.jaxb.rnt</packageName>
							<clearOutputDir>false</clearOutputDir>
						</configuration>
					</execution -->

				</executions>
			</plugin>
			
			<plugin>
			    <groupId>org.jvnet.jaxb2.maven2</groupId>
			    <artifactId>maven-jaxb2-plugin</artifactId>
				<executions>
				    <execution>
				        <goals>
				            <goal>generate</goal>
				        </goals>
				    </execution>
				</executions>
            	<configuration>
            		<verbose>true</verbose>
			        <extension>true</extension>
			        <args>
			            <!--  arg>-XtoString</arg -->
			            <!--  arg>-Xequals</arg-->
			            <arg>-Xinheritance</arg>
			            <arg>-Xsetters</arg>
			        </args>
			        <plugins>
			            <plugin>
			                <groupId>org.jvnet.jaxb2_commons</groupId>
			                <artifactId>jaxb2-basics</artifactId>
			                <version>0.9.4</version>
			            </plugin>
			        </plugins>
			        <!-- The schema directory or xsd files. -->
			        <schemaDirectory>${basedir}/src/main/xsd</schemaDirectory>
 					<schemaIncludes>
                		<include>DCL.xsd</include>
                		<include>RNT.xsd</include>
                		<include>Respuesta.xsd</include>
                		<include>TrabajadoresTramos.xsd</include>
                		<include>SolicitudCalculos.xsd</include>
                		<include>SolicitudConfirmacion.xsd</include>
                		<include>SolicitudTrabajadoresTramos.xsd</include>
            		</schemaIncludes>			        
					<!-- Default to the schemaDirectory -->
					<bindingDirectory>src/main/resources</bindingDirectory>
					<bindingIncludes>
					    <include>AONSolutions.xjb</include>
					</bindingIncludes>
                	<!-- The working directory to create the generated java source files. -->
                	<outputDirectory>${basedir}/target/generated-sources/</outputDirectory>
                </configuration>
			</plugin>

		</plugins>
	</build>

</project>
