<?xml version="1.0" encoding="utf-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <parent>
    <groupId>com.code.aon</groupId>
    <artifactId>aon.parent</artifactId>
    <version>8.114.1</version>
  </parent>
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.esferalia.aon</groupId>
  <artifactId>aon.ui.payroll</artifactId>
  <description>AON UI PAYROLL</description>
  <name>AON UI PAYROLL</name>
  <dependencies>
    <dependency>
      <groupId>net.aonsolutions.core</groupId>
      <artifactId>pool</artifactId>
      <version>8.114</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>com.esferalia.aon</groupId>
      <artifactId>aon.calendar</artifactId>
      <version>${project.version}</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.esferalia.aon</groupId>
      <artifactId>aon.file.payroll</artifactId>
      <version>${project.version}</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.esferalia.aon</groupId>
      <artifactId>aon.payroll</artifactId>
      <version>${project.version}</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.code.aon</groupId>
      <artifactId>aon.customer</artifactId>
      <version>${project.version}</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.code.aon</groupId>
      <artifactId>aon.ui.company</artifactId>
      <version>${project.version}</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.code.aon</groupId>
      <artifactId>aon.ui.form</artifactId>
      <version>${project.version}</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.code.aon</groupId>
      <artifactId>aon.ui.resources</artifactId>
      <version>${project.version}</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.code.aon</groupId>
      <artifactId>aon.ui.report</artifactId>
      <version>${project.version}</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.esferalia.aon</groupId>
      <artifactId>aon.ui.sepe</artifactId>
      <version>${project.version}</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.8</version>
      <type>jar</type>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>com.transtools</groupId>
      <artifactId>ctsql-jdbc</artifactId>
      <version>2.2.3.6</version>
      <scope>runtime</scope>
      <optional>false</optional>
    </dependency>
    <dependency>
      <groupId>javax.faces</groupId>
      <artifactId>jsf-api</artifactId>
      <version>1.2_14</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>javax.servlet</groupId>
      <artifactId>javax.servlet-api</artifactId>
      <version>3.1.0</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>javax.el</groupId>
      <artifactId>el-api</artifactId>
      <version>1.0</version>
      <scope>provided</scope>
    </dependency>
    <!-- EDICION DE PDF -->
    <dependency>
      <groupId>org.swinglabs</groupId>
      <artifactId>pdf-renderer</artifactId>
      <version>1.0.5</version>
    </dependency>
    <dependency>
      <groupId>com.lowagie</groupId>
      <artifactId>itext</artifactId>
      <version>2.1.7</version>
    </dependency>
    <dependency>
      <groupId>com.ibm.icu</groupId>
      <artifactId>icu4j</artifactId>
      <version>4.8.1.1</version>
      <scope>compile</scope>
    </dependency>
  </dependencies>
</project>
