<?xml version="1.0"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<parent>
		<groupId>com.code.aon</groupId>
		<artifactId>aon.parent</artifactId>
		<version>7.0.1</version>
	</parent>
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.esferalia.aon</groupId>
	<artifactId>aon.ui.payroll</artifactId>
	<description>AON UI PAYROLL</description>
	<name>AON UI PAYROLL</name>	
  	<build>
		<plugins>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>jasperreports-maven-plugin</artifactId>
				<version>${jasperreportsMavenPluginVersion}</version>
				<configuration>
					<outputDirectory>${project.build.directory}/classes/com/esferalia/aon/ui/payroll/report</outputDirectory>
					<xmlValidation>true</xmlValidation>
					<compiler>${jasperreportsMavenPluginCompiler}</compiler>
				</configuration>
				<executions>
					<execution>
						<phase>prepare-package</phase>
						<goals>
							<goal>compile-reports</goal>
						</goals>
					</execution>
				</executions>
				<dependencies>
					<dependency>
						<groupId>net.sf.jasperreports</groupId>
						<artifactId>${jasperReportsArtifact}</artifactId>
						<version>${jasperReportsVersion}</version>
					</dependency>
					<dependency>
						<groupId>com.esferalia.aon</groupId>
						<artifactId>aon.ui.payroll</artifactId>
						<version>${project.version}</version>
					</dependency>
 				</dependencies>
			</plugin>
		</plugins>
		<pluginManagement>
			<plugins>
				<!--This plugin's configuration is used to store Eclipse m2e settings 
					only. It has no influence on the Maven build itself. -->
				<plugin>
					<groupId>org.eclipse.m2e</groupId>
					<artifactId>lifecycle-mapping</artifactId>
					<version>1.0.0</version>
					<configuration>
						<lifecycleMappingMetadata>
							<pluginExecutions>
								<pluginExecution>
									<pluginExecutionFilter>
										<groupId>org.codehaus.mojo</groupId>
										<artifactId>jasperreports-maven-plugin</artifactId>
										<versionRange>
											[1.0-beta-2,)
										</versionRange>
										<goals>
											<goal>compile-reports</goal>
										</goals>
									</pluginExecutionFilter>
									<action>
										<ignore />
									</action>
								</pluginExecution>
							</pluginExecutions>
						</lifecycleMappingMetadata>
					</configuration>
				</plugin>
			</plugins>
		</pluginManagement>
	</build>
	<dependencies>
		<dependency>
			<groupId>com.esferalia.aon</groupId>
			<artifactId>aon.calendar</artifactId>
			<version>${project.version}</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>com.esferalia.aon</groupId>
			<artifactId>aon.file.payroll</artifactId>
			<version>${project.version}</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>com.esferalia.aon</groupId>
			<artifactId>aon.payroll</artifactId>
			<version>${project.version}</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.customer</artifactId>
			<version>${project.version}</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.company</artifactId>
			<version>${project.version}</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.form</artifactId>
			<version>${project.version}</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.resources</artifactId>
			<version>${project.version}</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.report</artifactId>
			<version>${project.version}</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>javax.faces</groupId>
			<artifactId>jsf-api</artifactId>
			<version>1.2_14</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>javax.servlet</groupId>
			<artifactId>servlet-api</artifactId>
			<version>2.4</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>javax.el</groupId>
			<artifactId>el-api</artifactId>
			<version>1.0</version>
			<scope>provided</scope>
		</dependency>		
		
		<!-- EDICION DE PDF -->
		<dependency>
		    <groupId>org.swinglabs</groupId>
		    <artifactId>pdf-renderer</artifactId>
		    <version>1.0.5</version>
		</dependency>
		<dependency>
		        <groupId>com.lowagie</groupId>
		        <artifactId>itext</artifactId>
		        <version>2.1.7</version>
		</dependency>
	</dependencies>
    <profiles>
      	<profile>
            <id>perform-stats</id>
        </profile>
    </profiles>
</project>
