<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<parent>
		<groupId>com.code.aon</groupId>
		<artifactId>aon.parent</artifactId>
		<version>5.0.0</version>
	</parent>
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.code.aon</groupId>
	<artifactId>aon.ui.marketing</artifactId>
	<version>${aon-version}</version>
	<description>AON UI MARKETING</description>
	<name>AON UI MARKETING</name>
	<dependencies>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.security.bridge</artifactId>
			<version>${aon-version}</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId> 
			<artifactId>aon.security</artifactId>
			<version>1.9.0</version>
			<scope>provided</scope>
		</dependency>		
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.form</artifactId>
			<version>${aon-version}</version>
			<scope>compile</scope>
		</dependency>				
		<dependency>
			<groupId>com.code.aon</groupId> 
			<artifactId>aon.marketing</artifactId>
			<version>${aon-version}</version>
			<scope>compile</scope>
		</dependency>	
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.commercial</artifactId>
			<version>${aon-version}</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.company</artifactId>
			<version>${aon-version}</version>			
			<scope>compile</scope>
		</dependency>				
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.config</artifactId>
			<version>${aon-version}</version>
			<scope>compile</scope>
		</dependency>		
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.mailing</artifactId>
			<version>${aon-version}</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.messaging</artifactId>
			<version>${aon-version}</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.webmail</artifactId>
			<version>${aon-version}</version>
		</dependency>		
		<dependency>
			<groupId>javax.faces</groupId>
			<artifactId>jsf-api</artifactId>
			<version>1.2_14</version>
			<scope>provided</scope>
		</dependency>
	</dependencies>
</project>