<?xml version="1.0"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<parent>
		<groupId>com.code.aon</groupId>
		<artifactId>aon.web.parent</artifactId>
		<version>5.0.2</version>
	</parent>
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.code.aon</groupId>
	<artifactId>aon-ecommerce</artifactId>
	<packaging>war</packaging>
	<version>5.0.2</version>
	<description>AON WEB ECOMMERCE</description>
	<name>AON WEB ECOMMERCE</name>
	<properties>
		<dbVersion>4.8.1</dbVersion>
	</properties>
	<build>
		<finalName>aon-ecommerce</finalName>
	</build>
	<dependencies>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.ecommerce</artifactId>
			<version>${pom.version}</version>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.resources</artifactId>
			<version>${pom.version}</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.geozone</artifactId>
			<version>${pom.version}</version>
			<scope>runtime</scope>
		</dependency>
		<!--  Necesario para imprimir barcodes con jasper -->
		<dependency>
			<groupId>iReport</groupId>
			<artifactId>iReport-utils</artifactId>
			<version>2.0.1</version>
			<scope>compile</scope>
		</dependency>
	</dependencies>
</project>
