<?xml version="1.0"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

	<parent>
		<groupId>com.code.aon</groupId>
		<artifactId>aon.parent</artifactId>
		<version>8.102.3</version>
	</parent>
	<modelVersion>4.0.0</modelVersion>
	<artifactId>aon.conexflow</artifactId>
	<description>AON CONEXFLOW</description>
	<name>AON CONEXFLOW</name>

	<dependencies>
		
		<!-- External Dependencies -->
		
		<dependency>
			<groupId>xml-security</groupId>
			<artifactId>xmlsec</artifactId>
			<version>1.0.5D2</version>
		</dependency>
		<dependency>
			<groupId>org.apache.httpcomponents</groupId>
			<artifactId>httpclient</artifactId>
			<version>4.5</version>
			
		</dependency>
		<dependency>
			<groupId>org.bouncycastle</groupId>
			<artifactId>bcprov-jdk14</artifactId>
			<version>1.38</version>
			<scope>compile</scope>			
		</dependency>

		<dependency>
			<groupId>commons-cli</groupId>
			<artifactId>commons-cli</artifactId>
			<version>1.2</version>
			<scope>compile</scope>
		</dependency>
		<!-- AON Dependencies -->

		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.common</artifactId>
			<version>${project.version}</version>
			<scope>provided</scope>
		</dependency>
		
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.pool</artifactId>
			<version>${project.version}</version>
		</dependency>
		
		<dependency>
			<groupId>com.esferalia.aon</groupId>
			<artifactId>aon.pms</artifactId>
			<version>${project.version}</version>
			<scope>compile</scope>
		</dependency>
		
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.common</artifactId>
			<version>${project.version}</version>
			<scope>compile</scope>
		</dependency>
		
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.google.apis</artifactId>
			<version>${project.version}</version>
			<scope>compile</scope>
		</dependency>
		

		
	
	</dependencies>
	<profiles>
		<profile>
			<id>rpm-release</id>
			<activation>
				<property>
					<name>rpm.release</name>
					<value>true</value>
				</property>
			</activation>
			
			<dependencies>
				<!-- añadir dependencias -->
				<dependency>
					<groupId>com.code.aon</groupId>
					<artifactId>aon.pool</artifactId>
					<version>${project.version}</version>
				</dependency>
				<dependency>
					<groupId>org.jooq</groupId>
					<artifactId>jooq</artifactId>
					<version>3.8.4</version>
				</dependency>
				<dependency>
					<groupId>com.mchange</groupId>
					<artifactId>c3p0</artifactId>
					<version>0.9.2</version>
				</dependency>
				<dependency>
					<groupId>com.mchange</groupId>
					<artifactId>mchange-commons-java</artifactId>
					<version>0.2.3.3</version>
				</dependency>
				<dependency>
					<groupId>com.esferalia.aon</groupId>
					<artifactId>aon.occam</artifactId>
					<version>${project.version}</version>
					<scope>compile</scope>
				</dependency>
				<dependency>
					<groupId>com.esferalia.aon</groupId>
					<artifactId>aon.watson</artifactId>
					<version>${project.version}</version>
				</dependency>
				<dependency>
					<groupId>com.esferalia.aon</groupId>
					<artifactId>aon.entity.common</artifactId>
					<version>${project.version}</version>
					<scope>compile</scope>
				</dependency>			
				<dependency>
      				<groupId>com.code.aon</groupId>
     			 	<artifactId>aon.common</artifactId>
      				<version>${project.version}</version>
      				<scope>compile</scope>
  			 	</dependency>	
  			 	<dependency>
					<groupId>org.apache.httpcomponents</groupId>
					<artifactId>httpclient</artifactId>
					<version>4.5</version>
					<scope>compile</scope>
				</dependency>
				<dependency>
					<groupId>org.apache.httpcomponents</groupId>
					<artifactId>httpcore</artifactId>
					<version>4.4.1</version>
					<scope>compile</scope>
				</dependency>
				<dependency>
					<groupId>commons-cli</groupId>
					<artifactId>commons-cli</artifactId>
					<version>1.2</version>
					<scope>compile</scope>
				</dependency>
				<dependency>
					<groupId>commons-logging</groupId>
					<artifactId>commons-logging</artifactId>
					<version>1.2</version>
				</dependency>
				<dependency>
					<groupId>org.bouncycastle</groupId>
					<artifactId>bcprov-jdk14</artifactId>
					<version>1.38</version>
					<scope>compile</scope>			
				</dependency>
				<dependency>
					<groupId>xml-security</groupId>
					<artifactId>xmlsec</artifactId>
					<version>1.0.5D2</version>
				</dependency>
				<dependency>
					<groupId>com.code.aon</groupId>
					<artifactId>aon.ui.common</artifactId>
					<version>${project.version}</version>
					<scope>provided</scope>
				</dependency>
				<dependency>
					<groupId>com.esferalia.aon</groupId>
					<artifactId>aon.pms</artifactId>
					<version>${project.version}</version>
					<scope>compile</scope>
				</dependency>
				<dependency>
					<groupId>com.code.aon</groupId>
					<artifactId>aon.ql</artifactId>
					<version>${project.version}</version>
					<scope>compile</scope>
				</dependency>
				
				<dependency>
					<groupId>com.code.aon</groupId>
					<artifactId>aon.product</artifactId>
					<version>${project.version}</version>
				</dependency>
				<dependency>
					<groupId>com.code.aon</groupId>
					<artifactId>aon.registry</artifactId>
					<version>${project.version}</version>
				</dependency>
				<dependency>
					<groupId>commons-lang</groupId>
					<artifactId>commons-lang</artifactId>
					<version>2.5</version>
					<scope>compile</scope>
				</dependency>
				<dependency>
					<groupId>com.code.aon</groupId>
					<artifactId>aon.project</artifactId>
					<version>${project.version}</version>
					<scope>compile</scope>
				</dependency>
				
				<dependency>
					<groupId>com.esferalia.aon</groupId>
					<artifactId>aon.entity</artifactId>
					<version>${project.version}</version>
					<scope>compile</scope>
				</dependency>		
				<dependency>
					<groupId>com.code.aon</groupId>
					<artifactId>aon.customer</artifactId>
					<version>${project.version}</version>
				</dependency>
				<dependency>
					<groupId>com.code.aon</groupId>
					<artifactId>aon.config</artifactId>
					<version>${project.version}</version>
					<scope>compile</scope>
				</dependency>
				<dependency>
					<groupId>org.hibernate</groupId>
					<artifactId>hibernate</artifactId>
					<version>3.2.7.ga</version>
					<scope>compile</scope>
					<exclusions>
						<exclusion>
							<groupId>commons-logging</groupId>
							<artifactId>commons-logging</artifactId>
						</exclusion>
					</exclusions>
				</dependency>
				<dependency>
					<groupId>org.hibernate</groupId>
					<artifactId>hibernate-annotations</artifactId>
					<version>3.3.1.GA</version>
					<scope>compile</scope>
				</dependency>
				<dependency>
					<groupId>org.hibernate</groupId>
					<artifactId>hibernate-commons-annotations</artifactId>
					<version>3.3.0.ga</version>
					<scope>compile</scope>
				</dependency>
				<dependency>
					<groupId>dom4j</groupId>
					<artifactId>dom4j</artifactId>
					<version>1.6.1</version>
				</dependency>
				<dependency>
					<groupId>com.code.aon</groupId>
					<artifactId>aon.company</artifactId>
					<version>${project.version}</version>
					<scope>compile</scope>
				</dependency>
				
				<dependency>
					<groupId>javax.persistence</groupId>
					<artifactId>persistence-api</artifactId>
					<version>1.0.2</version>
				</dependency>
				<dependency>
					<groupId>commons-collections</groupId>
					<artifactId>commons-collections</artifactId>
					<version>3.1</version>
				</dependency>
				
				<dependency>
					<groupId>com.esferalia.aon</groupId>
					<artifactId>aon.calendar</artifactId>
					<version>${project.version}</version>
					<scope>compile</scope>
				</dependency>
				<dependency>
					<groupId>com.code.aon</groupId>
					<artifactId>aon.seller</artifactId>
					<version>${project.version}</version>
					<scope>compile</scope>
				</dependency>
				<dependency>
					<groupId>com.code.aon</groupId>
					<artifactId>aon.geozone</artifactId>
					<version>${project.version}</version>
					<scope>compile</scope>
				</dependency>
				<dependency>
    				<groupId>cglib</groupId>
    				<artifactId>cglib</artifactId>
    				<version>2.2.2</version>
				</dependency>
				<dependency>
    				<groupId>asm</groupId>
    				<artifactId>asm</artifactId>
    				<version>3.3.1</version>
				</dependency>
				
				<dependency>
					<groupId>com.code.aon</groupId>
					<artifactId>aon.asset</artifactId>
					<version>${project.version}</version>
					<scope>compile</scope>
				</dependency>
				
				<dependency>
					<groupId>com.code.aon</groupId>
					<artifactId>aon.finance</artifactId>
					<version>${project.version}</version>
					<scope>compile</scope>
				</dependency>
				<dependency>
					<groupId>com.code.aon</groupId>
					<artifactId>aon.warehouse</artifactId>
					<version>${project.version}</version>
					<scope>compile</scope>
				</dependency>
					
				<dependency>
					<groupId>com.esferalia.aon</groupId>
					<artifactId>aon.entity.alias</artifactId>
					<version>${project.version}</version>
				</dependency>
				<dependency>
					<groupId>antlr</groupId>
					<artifactId>antlr</artifactId>
					<version>2.7.6</version>
					<scope>compile</scope>
				</dependency>
		
				<dependency>
					<groupId>javax.transaction</groupId>
					<artifactId>jta</artifactId>
					<version>1.1</version>
				</dependency>
			</dependencies>
				
			<build>
				<plugins>
					<!-- Para construir el RPM -->
					<plugin>
						<groupId>org.codehaus.mojo</groupId>
						<artifactId>rpm-maven-plugin</artifactId>
						<version>2.0.1</version>
						<extensions>true</extensions>

						<executions>
							<execution>
								<id>rpm-build</id>
								<goals>
									<goal>attached-rpm</goal>
								</goals>
							</execution>
						</executions>
						<configuration>
							<group>Applications/Aon</group>
							<release>${buildNumber}</release>
							<copyright>2014, esferalia Networks S.A</copyright>
							<requires>
								<require>slf4j</require>
								<require>aon-dbutils</require>
								<require>mysql-connector-java</require>
							</requires>
							<mappings>
								<mapping>
									<filemode>755</filemode>
									<username>root</username>
									<groupname>root</groupname>

									<directory>/usr/share/java/aon-conexflow</directory>
									<dependency>
										<includes>
											<!-- ext -->
											<include>commons-cli:commons-cli:1.2</include>
											<include>org.jooq:jooq:3.5.2</include>
											<include>com.mchange:c3p0:0.9.2</include>
											<include>com.mchange:mchange-commons-java:0.2.3.3</include>
											<include>org.apache.httpcomponents:httpclient:4.5</include>
											<include>org.apache.httpcomponents:httpcore:4.4.1</include>
											<include>commons-cli:commons-cli:1.2</include>
											<include>commons-logging:commons-logging:1.2</include>
											<include>org.bouncycastle:bcprov-jdk14:1.38</include>
											<include>xml-security:xmlsec:1.0.5D2</include>
											<include>org.hibernate:hibernate:3.2.7.ga</include>
											<include>org.hibernate:hibernate-annotations:3.3.1.GA</include>
											<include>org.hibernate:hibernate-commons-annotations:3.3.0.ga</include>
											<include>dom4j:dom4j:1.6.1</include>
											<include>javax.persistence:persistence-api:1.0.2</include>
											<include>commons-collections:commons-collections:3.1</include>
											<include>cglib:cglib:2.2.2</include>
											<include>asm:asm:3.3.1</include>
											<include>antlr:antlr:2.7.6</include>
											<include>javax.transaction:jta:1.1</include>										
										
											<!-- aon -->
											<include>com.code.aon:aon.pool:${project.version}</include>
											<include>com.esferalia.aon:aon.master.jooq:${project.version}</include>
											<include>com.esferalia.aon:aon.occam:${project.version}</include>
											<include>com.esferalia.aon:aon.watson:${project.version}</include>
											<include>com.esferalia.aon:aon.entity.common:${project.version}</include>
											<include>com.code.aon:aon.common:${project.version}</include>
											<include>com.code.aon:aon.ui.common:${project.version}</include>
											<include>com.esferalia.aon:aon.pms:${project.version}</include>
											<include>com.code.aon:aon.ql:${project.version}</include>
											<include>com.code.aon:aon.product:${project.version}</include>
											<include>com.code.aon:aon.registry:${project.version}</include>
											<include>commons-lang:commons-lang:2.5</include>
											<include>com.code.aon:aon.project:${project.version}</include>
											
											<include>com.esferalia.aon:aon.entity:${project.version}</include>
											
											<include>com.code.aon:aon.customer:${project.version}</include>
											<include>com.code.aon:aon.config:${project.version}</include>
											<include>com.code.aon:aon.company:${project.version}</include>
											<include>com.esferalia.aon:aon.calendar:${project.version}</include>
											<include>com.code.aon:aon.seller:${project.version}</include>
											<include>com.code.aon:aon.geozone:${project.version}</include>
											<include>com.code.aon:aon.asset:${project.version}</include>
											<include>com.code.aon:aon.finance:${project.version}</include>
											<include>com.code.aon:aon.warehouse:${project.version}</include>
											<include>com.esferalia.aon:aon.entity.alias:${project.version}</include>
											
											<!-- Google APIS-->
											<include>com.code.aon:aon.google.apis:${project.version}</include>
											
											<include>com.google.api-client:google-api-client:1.21.0</include>
											<include>com.google.http-client:google-http-client:1.21.0</include>
											<include>com.google.http-client:google-http-client-jackson2:1.21.0</include>
											<include>com.google.oauth-client:google-oauth-client:1.21.0</include>
											<include>com.google.apis:google-api-services-oauth2:v2-rev98-1.21.0</include>
											<include>com.google.apis:google-api-services-drive:v2-rev194-1.21.0</include>
											
											<include>javax.mail:mail:1.4</include>
											<include>com.fasterxml.jackson.core:jackson-core:2.1.3</include>
											
										</includes>
									</dependency>
									<sources>
										<source>
											<location>target</location>
											<includes>
												<include>${project.artifactId}-${project.version}.jar</include>
											</includes>
										</source>
									</sources>
								</mapping>
								
								<mapping>
									<filemode>755</filemode>
									<username>root</username>
									<groupname>root</groupname>
									<directory>/usr/share/aon-conexflow/bin</directory>
									<sources>
										<source>
											<location>src/main/scripts</location>
											<includes>
												<include>aon-conexflow.sh</include>
											</includes>
										</source>
									</sources>
								</mapping>
								
							</mappings>
						</configuration>
					</plugin>
				</plugins>
			</build>
		</profile>
	</profiles>
	
</project>
 
