//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.05.06 at 11:09:31 a. m. CEST 
//


package ticketbai.anulacion;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.w3._2000._09.xmldsig.SignatureType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Cabecera" type="{urn:ticketbai:anulacion}Cabecera"/>
 *         &lt;element name="IDFactura" type="{urn:ticketbai:anulacion}IDFactura"/>
 *         &lt;element name="HuellaTBAI" type="{urn:ticketbai:anulacion}HuellaTBAI"/>
 *         &lt;element ref="{http://www.w3.org/2000/09/xmldsig#}Signature"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "cabecera",
    "idFactura",
    "huellaTBAI",
    "signature"
})
@XmlRootElement(name = "AnulaTicketBai")
public class AnulaTicketBai {

    @XmlElement(name = "Cabecera", required = true)
    protected Cabecera cabecera;
    @XmlElement(name = "IDFactura", required = true)
    protected IDFactura idFactura;
    @XmlElement(name = "HuellaTBAI", required = true)
    protected HuellaTBAI huellaTBAI;
    @XmlElement(name = "Signature", namespace = "http://www.w3.org/2000/09/xmldsig#", required = true)
    protected SignatureType signature;

    /**
     * Gets the value of the cabecera property.
     * 
     * @return
     *     possible object is
     *     {@link Cabecera }
     *     
     */
    public Cabecera getCabecera() {
        return cabecera;
    }

    /**
     * Sets the value of the cabecera property.
     * 
     * @param value
     *     allowed object is
     *     {@link Cabecera }
     *     
     */
    public void setCabecera(Cabecera value) {
        this.cabecera = value;
    }

    /**
     * Gets the value of the idFactura property.
     * 
     * @return
     *     possible object is
     *     {@link IDFactura }
     *     
     */
    public IDFactura getIDFactura() {
        return idFactura;
    }

    /**
     * Sets the value of the idFactura property.
     * 
     * @param value
     *     allowed object is
     *     {@link IDFactura }
     *     
     */
    public void setIDFactura(IDFactura value) {
        this.idFactura = value;
    }

    /**
     * Gets the value of the huellaTBAI property.
     * 
     * @return
     *     possible object is
     *     {@link HuellaTBAI }
     *     
     */
    public HuellaTBAI getHuellaTBAI() {
        return huellaTBAI;
    }

    /**
     * Sets the value of the huellaTBAI property.
     * 
     * @param value
     *     allowed object is
     *     {@link HuellaTBAI }
     *     
     */
    public void setHuellaTBAI(HuellaTBAI value) {
        this.huellaTBAI = value;
    }

    /**
     * Gets the value of the signature property.
     * 
     * @return
     *     possible object is
     *     {@link SignatureType }
     *     
     */
    public SignatureType getSignature() {
        return signature;
    }

    /**
     * Sets the value of the signature property.
     * 
     * @param value
     *     allowed object is
     *     {@link SignatureType }
     *     
     */
    public void setSignature(SignatureType value) {
        this.signature = value;
    }

}
