package com.esferalia.aon.gwt.payroll.shared;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.HashMap;
import java.util.Map;
import java.util.Map.Entry;

public class BankEntities {
	
	private static final Map<String, String> bankEntities;
	static {
		Map<String, String> bankEntitiesMap = new HashMap<String, String>();
		
		bankEntitiesMap.put("", "");
		bankEntitiesMap.put("0241", "A&G Banca Privada, S.A.");
		bankEntitiesMap.put("2080", "Abanca Corporaci" + String.valueOf("\u00F3") + "n Bancaria, S.A.");
		bankEntitiesMap.put("8620", "Abanca Servicios Financieros E.F.C., S.A.");
		bankEntitiesMap.put("1535", "AKF Bank Gmbh & Co Kg, S.E.");
		bankEntitiesMap.put("0011", "Allfunds Bank, S.A");
		bankEntitiesMap.put("1544", "Andbank Espa" + String.valueOf("\u00F1") + "a, S.A.");
		bankEntitiesMap.put("0136", "Aresbank, S.A.");
		bankEntitiesMap.put("3183", "Arquia Bank, S.A.");
		bankEntitiesMap.put("1541", "Attijariwafa Bank Europe, S.E");
		bankEntitiesMap.put("1554", "Banca Farmafactoring, SPA Suc en España");
		bankEntitiesMap.put("0061", "Banca March, S.A.");
		bankEntitiesMap.put("1550", "Banca Popolare Etica Sociedad Cooperativa Per Aziones, S.E.");
		bankEntitiesMap.put("0078", "Banca Pueyo, S.A.");
		bankEntitiesMap.put("0188", "Banco Alcal" + String.valueOf("\u00E1") + ", S.A.");
		bankEntitiesMap.put("0182", "Banco Bilbao Vizcaya Argentaria, S.A.");
		bankEntitiesMap.put("0234", "Banco Caminos, S.A.");
		bankEntitiesMap.put("0225", "Banco Cetelem, S.A.");
		bankEntitiesMap.put("0198", "Banco Cooperativo Espa" + String.valueOf("\u00F1") + "ol, S.A.");
		bankEntitiesMap.put("0091", "Banco de Albacete, S.A.");
		bankEntitiesMap.put("0240", "Banco de Cr" + String.valueOf("\u00E9") + "dito Social Cooperativo, S.A.");
		bankEntitiesMap.put("0003", "Banco de Dep" + String.valueOf("\u00F3") + "sitos, S.A.");
		bankEntitiesMap.put("9000", "Banco de Espa" + String.valueOf("\u00F1") + "a");
		bankEntitiesMap.put("1569", "Banco de Investimento Global S.A., S.E.");
		bankEntitiesMap.put("0169", "Banco de la Naci" + String.valueOf("\u00F3") + "n Argentina, S.E.");
		bankEntitiesMap.put("0081", "Banco de Sabadell, S.A.");
		bankEntitiesMap.put("0155", "Banco do Brasil, AG., S.E");
		bankEntitiesMap.put("0184", "Banco Europeo de Finanzas, S.A.");
		bankEntitiesMap.put("0220", "Banco Finantia Spain, S.A.");
		bankEntitiesMap.put("0113", "Banco Industrial de Bilbao, S.A.");
		bankEntitiesMap.put("0232", "Banco Inversis, S.A.");
		bankEntitiesMap.put("0186", "Banco Mediolanum, S.A.");
		bankEntitiesMap.put("0121", "Banco Occidental, S.A.");
		bankEntitiesMap.put("0235", "Banco Pichincha España, S.A.");
		bankEntitiesMap.put("1509", "Banco Primus, S.A., S.E.");
		bankEntitiesMap.put("0049", "Banco Santander, S.A.");
		bankEntitiesMap.put("0125", "Bancofar, S.A.");
		bankEntitiesMap.put("0200", "Bank Degroof Petercam Spain, S.A.");
		bankEntitiesMap.put("1485", "Bank of America Merrill Lynch International DAC, Sucursal en Espa" + String.valueOf("\u00F1") + "a");
		bankEntitiesMap.put("2038", "Bankia, S.A.");
		bankEntitiesMap.put("8832", "Bankinter Consumer Finance, E.F.C., S.A.");
		bankEntitiesMap.put("0128", "Bankinter, S.A.");
		bankEntitiesMap.put("0138", "Bankoa, S.A.");
		bankEntitiesMap.put("1525", "Banque Chaabi Du Maroc, S.E.");
		bankEntitiesMap.put("8211", "Bansabadell Financiaci" + String.valueOf("\u00F3") + "n  E.F.C., S.A.");
		bankEntitiesMap.put("0152", "Barclays Bank Ireland Plc, S.E.");
		bankEntitiesMap.put("8235", "Bilbao Hipotecaria, S.A., E.F.C.");
		bankEntitiesMap.put("1521", "Binckbank NV, S.E.");
		bankEntitiesMap.put("0219", "BMCE Bank International, S.A.");
		bankEntitiesMap.put("1533", "BMW Bank GMBH, SE");
		bankEntitiesMap.put("6717", "Bnext Electronic Issuer, E.D.E. S.L.");
		bankEntitiesMap.put("1532", "BNP Paribas Factor, S.A., S.E.");
		bankEntitiesMap.put("0167", "BNP Paribas Fortis, S.A., N.V., Sucursal en Espa" + String.valueOf("\u00F1") + "a");
		bankEntitiesMap.put("1492", "BNP Paribas Lease Group, S.A., S.E.");
		bankEntitiesMap.put("0144", "BNP Paribas Securities Services, S.E.");
		bankEntitiesMap.put("0149", "BNP Paribas, S.E.");
		bankEntitiesMap.put("1500", "BPCE Lease, S.A., S.E.");
		bankEntitiesMap.put("3060", "C.R. Burgos, Fuentepelayo, Segovia Y Castelldans, S.C.C.");
		bankEntitiesMap.put("3190", "C.R. de Albacete, Ciudad Real Y Cuenca, S.C.C.");
		bankEntitiesMap.put("1545", "CA Indosuez Wealth (Europe), S.E.");
		bankEntitiesMap.put("8841", "CACF Bankia Consumer Finance EFC, S.A");
		bankEntitiesMap.put("1451", "Caisse R" + String.valueOf("\u00E9") + "gionale Cr" + String.valueOf("\u00E9") + "dit Agricole Mutuel Sud Med, S.E.");
		bankEntitiesMap.put("1493", "Caixa Banco de Investimento, S.A., S.E.");
		bankEntitiesMap.put("3025", "Caixa de C. dels Enginyers-C.C. Ingenieros S.C.C.");
		bankEntitiesMap.put("3159", "Caixa Popular-Caixa Rural, S.C.C.V.");
		bankEntitiesMap.put("3045", "Caixa R. Altea, C.C.V.");
		bankEntitiesMap.put("3162", "Caixa R. Benicarl" + String.valueOf("\u00F3") + ", S.C.C.V.");
		bankEntitiesMap.put("3117", "Caixa R. DAlgemes" + String.valueOf("\u00ED") + ", S.C.V.C.");
		bankEntitiesMap.put("3105", "Caixa R. de Callosa d en Sarria, C.C.V.");
		bankEntitiesMap.put("3096", "Caixa R. de L Alcudia, S.C.V.C.");
		bankEntitiesMap.put("3123", "Caixa R. de Turis, C.C.V.");
		bankEntitiesMap.put("3070", "Caixa R. Galega, S.C.C.L.G.");
		bankEntitiesMap.put("3111", "Caixa R. La Vall S. Isidro, S.C.C.V.");
		bankEntitiesMap.put("3166", "Caixa R. Les Coves de Vinroma, S.C.C.V.");
		bankEntitiesMap.put("3102", "Caixa R. S. Vicent Ferrer de la Vall d Uix" + String.valueOf("\u00F3") + ", C.C.V.");
		bankEntitiesMap.put("3160", "Caixa R. Sant Josep de Vilavella, S.C.C.V");
		bankEntitiesMap.put("3174", "Caixa R. Vinaros, S.C.C.V.");
		bankEntitiesMap.put("3118", "Caixa Rural Torrent, C.C.V.");
		bankEntitiesMap.put("6702", "Caixabank Electronic Money, EDE, S.L.");
		bankEntitiesMap.put("8776", "Caixabank Payments & Consumer, E.F.C., E.P., S.A.");
		bankEntitiesMap.put("2100", "CaixaBank, S.A.");
		bankEntitiesMap.put("2045", "Caja de Ahorros y M.P. de Ontinyent");
		bankEntitiesMap.put("3029", "Caja de Cr" + String.valueOf("\u00E9") + "dito de Petrel, Caja Rural, C.C.V.");
		bankEntitiesMap.put("3035", "Caja Laboral Popular, C.C.");
		bankEntitiesMap.put("3110", "Caja R. Cat" + String.valueOf("\u00F3") + "lico Agraria, S.C.C.V.");
		bankEntitiesMap.put("3005", "Caja R. Central, S.C.C.");
		bankEntitiesMap.put("3150", "Caja R. de Albal, C.C.V.");
		bankEntitiesMap.put("3179", "Caja R. de Alginet, S.C.C.V.");
		bankEntitiesMap.put("3001", "Caja R. de Almendralejo, S.C.C.");
		bankEntitiesMap.put("3059", "Caja R. de Asturias, S.C.C.");
		bankEntitiesMap.put("3089", "Caja R. de Baena Ntra. Sra. de Guadalupe, S.C.C.A.");
		bankEntitiesMap.put("3104", "Caja R. de Cañete de las Torres Ntra. Sra. del Campo S.C.A.C.");
		bankEntitiesMap.put("3127", "Caja R. de Casas Iba" + String.valueOf("\u00F1") + "ez, S.C.C.Castilla-La Mancha");
		bankEntitiesMap.put("3121", "Caja R. de Cheste, S.C.C.");
		bankEntitiesMap.put("3009", "Caja R. de Extremadura, S.C.C.");
		bankEntitiesMap.put("3023", "Caja R. de Granada, S.C.C.");
		bankEntitiesMap.put("3140", "Caja R. de Guissona, S.C.C.");
		bankEntitiesMap.put("3067", "Caja R. de Ja" + String.valueOf("\u00E9") + "n, Barcelona y Madrid, S.C.C.");
		bankEntitiesMap.put("3008", "Caja R. de Navarra, S.C.C.");
		bankEntitiesMap.put("3016", "Caja R. de Salamanca, S.C.C.");
		bankEntitiesMap.put("3017", "Caja R. de Soria, S.C.C.");
		bankEntitiesMap.put("3080", "Caja R. de Teruel, S.C.C.");
		bankEntitiesMap.put("3020", "Caja R. de Utrera, S.C.A.C.");
		bankEntitiesMap.put("3144", "Caja R. de Villamalea, S.C.C.A. de Castilla la Mancha");
		bankEntitiesMap.put("3152", "Caja R. de Villar, C.C.V.");
		bankEntitiesMap.put("3085", "Caja R. de Zamora, C.C.");
		bankEntitiesMap.put("3187", "Caja R. del Sur, S.C.C.");
		bankEntitiesMap.put("3157", "Caja R. la Junquera de Chilches, S.C.C.V.");
		bankEntitiesMap.put("3134", "Caja R. Ntra. Sra. la Esperanza de Onda, S.C.C.V.");
		bankEntitiesMap.put("3115", "Caja R. Nuestra Madre del Sol, S.C.A.C.");
		bankEntitiesMap.put("3165", "Caja R. S. Isidro de Vilafames, S.C.C.V.");
		bankEntitiesMap.put("3119", "Caja R. S. Jaime de Alquer" + String.valueOf("\u00ED") + "as Niño Perdido, S.C.C.V.");
		bankEntitiesMap.put("3113", "Caja R. S. Jos" + String.valueOf("\u00E9") + " de Alcora, S.C.C.V.");
		bankEntitiesMap.put("3130", "Caja R. S. Jos" + String.valueOf("\u00E9") + " de Almassora, S.C.C.V.");
		bankEntitiesMap.put("3112", "Caja R. S. Jos" + String.valueOf("\u00E9") + " de Burriana, S.C.C.V.");
		bankEntitiesMap.put("3135", "Caja R. S. Jos" + String.valueOf("\u00E9") + " de Nules, S.C.C.V.");
		bankEntitiesMap.put("3095", "Caja R. S. Roque de Almenara S.C.C.V.");
		bankEntitiesMap.put("3018", "Caja R.R.S. Agust" + String.valueOf("\u00ED") +"n Fuente Alamo Murcia, S.C.C.");
		bankEntitiesMap.put("3191", "Caja Rural de Aragon Soc. Coop. de Credito");
		bankEntitiesMap.put("3007", "Caja Rural de Gij" + String.valueOf("\u00F3") + "n, S.C. Asturiana de Cr" + String.valueOf("\u00E9") + "dito");
		bankEntitiesMap.put("3098", "Caja Rural de Nueva Carteya, Sociedad Cooperativa Andaluza de Cr" + String.valueOf("\u00E9") + "dito");
		bankEntitiesMap.put("3058", "Cajamar Caja Rural, S.C.C.");
		bankEntitiesMap.put("3076", "Cajasiete, Caja Rural, S.C.C.");
		bankEntitiesMap.put("0237", "Cajasur Banco, S.A");
		bankEntitiesMap.put("4706", "Caterpillar Financial Corporaci" + String.valueOf("\u00F3") + "n Financiera, S.A., E.F.C.");
		bankEntitiesMap.put("2000", "Cecabank, S.A.");
		bankEntitiesMap.put("1553", "China Construction Bank (Europe) S.A., S.E");
		bankEntitiesMap.put("1474", "Citibank Europe PLC, S.E.");
		bankEntitiesMap.put("1499", "Claas Financial Services, S.A.S., S.E.");
		bankEntitiesMap.put("1514", "CNH  Industrial Financial Services, S.E.");
		bankEntitiesMap.put("1546", "CNH Capital Europe, S.A.S., S.E.");
		bankEntitiesMap.put("1543", "Cofidis, S.A., S.E.");
		bankEntitiesMap.put("2056", "Colonya - Caixa D Estalvis de Pollensa");
		bankEntitiesMap.put("0159", "Commerzbank Aktiengesellschaft, S.E.");
		bankEntitiesMap.put("1459", "Cooperatieve Rabobank U.A. S.E.");
		bankEntitiesMap.put("8221", "Corporaci" + String.valueOf("\u00F3") + "n Hipotecaria Mutual, S.A., E.F.C.");
		bankEntitiesMap.put("0154", "Credit Agricole Corporate and Investment Bank , S.E.");
		bankEntitiesMap.put("1472", "Credit Agricole Leasing & Factoring, S.E.");
		bankEntitiesMap.put("1555", "Credit Mutuel Leasing, S.E");
		bankEntitiesMap.put("1460", "Cr" + String.valueOf("\u00E9") + "dit Suisse AG, S.E.");
		bankEntitiesMap.put("1531", "Credit Suisse International,S.E.");
		bankEntitiesMap.put("6711", "Currencies Direct Limited, S.E");
		bankEntitiesMap.put("6716", "Currencies Direct Spain, EDE, SL");
		bankEntitiesMap.put("1457", "De Lage Landen International B.V., S.E.");
		bankEntitiesMap.put("1548", "Dell Bank International Designated Activity Company, S.E.");
		bankEntitiesMap.put("0145", "Deutsche Bank A.G., S.E.");
		bankEntitiesMap.put("0019", "Deutsche Bank, S.A.E.");
		bankEntitiesMap.put("8826", "Deutsche Leasing Iberica, E.F.C.,  S.A.");
		bankEntitiesMap.put("1501", "Deutsche Pfandbriefbank Ag, S.E");
		bankEntitiesMap.put("6704", "E. Kuantia EDE, S.L.");
		bankEntitiesMap.put("0211", "EBN Banco de Negocios, S.A.");
		bankEntitiesMap.put("6710", "Ebury Partners U.K., S.E");
		bankEntitiesMap.put("1473", "Edmond de Rothschild (Europe), S.E.");
		bankEntitiesMap.put("1512", "Elavon Financial Services Limited Designated Activity Company, S.E.");
		bankEntitiesMap.put("8321", "Entre2 Servicios Financieros, E.F.C., S.A.");
		bankEntitiesMap.put("6881", "EURO EXCHANGE SECURITIES UK LIMITED, S.E.");
		bankEntitiesMap.put("3081", "Eurocaja Rural, Sociedad Cooperativa de Cr" + String.valueOf("\u00E9") + "dito");
		bankEntitiesMap.put("6703", "Euronet 360 Finance Limited, S.E.");
		bankEntitiesMap.put("0239", "Evo Banco S.A.");
		bankEntitiesMap.put("8640", "FCA Capital Espa" + String.valueOf("\u00F1") + "a, EFC SA");
		bankEntitiesMap.put("0218", "Fce Bank plc S.E.");
		bankEntitiesMap.put("8308", "Financiera Carri" + String.valueOf("\u00F3") + "n, S.A., E.F.C.");
		bankEntitiesMap.put("8805", "Financiera El Corte Ingl" + String.valueOf("\u00E9") + "s E.F.C., S.A.");
		bankEntitiesMap.put("8823", "Financiera española de cr" + String.valueOf("\u00E9") + "dito a distancia, E.F.C., S.A.");
		bankEntitiesMap.put("6718", "FINPAY Entidad de Dineero Electr" + String.valueOf("\u00F3") + "nico, S.A");
		bankEntitiesMap.put("6714", "Foreign Currency Direct PLC, S.E");
		bankEntitiesMap.put("8839", "GCC Consumo, EFC");
		bankEntitiesMap.put("1496", "Genefim, S.E.");
		bankEntitiesMap.put("1564", "Goldman Sachs Bank Europe, SE");
		bankEntitiesMap.put("1497", "Haitong Bank, S.A., S.E.");
		bankEntitiesMap.put("1504", "Honda Bank GMBH, S.E.");
		bankEntitiesMap.put("0162", "HSBC France, S.E.");
		bankEntitiesMap.put("2085", "Ibercaja Banco, S.A.");
		bankEntitiesMap.put("4832", "Ibercaja Leasing y Financiaci" + String.valueOf("\u00F3") + "n, S.A., E.F.C.");
		bankEntitiesMap.put("1538", "Industrial and Commercial Bank of China (Europe),S.A.,S.E.");
		bankEntitiesMap.put("1465", "ING Bank, N.V. S.E");
		bankEntitiesMap.put("1000", "Instituto de Cr" + String.valueOf("\u00E9") + "dito Oficial");
		bankEntitiesMap.put("1494", "Intesa Sanpaolo S.P.A., S.E.");
		bankEntitiesMap.put("1516", "J.P. Morgan Bank Luxembourg S.A., S.E.");
		bankEntitiesMap.put("1542", "J.P. Morgan Securities Plc, S.E.");
		bankEntitiesMap.put("1482", "John Deere Bank, S.A., S.E");
		bankEntitiesMap.put("1567", "JP Morgan AG, S.E.");
		bankEntitiesMap.put("0151", "Jpmorgan Chase Bank National Association, S.E.");
		bankEntitiesMap.put("2095", "Kutxabank, S.A.");
		bankEntitiesMap.put("2048", "Liberbank, S.A.");
		bankEntitiesMap.put("1547", "Lombard Odier (Europe), S.A., S.E.");
		bankEntitiesMap.put("8342", "Luzaro E.F.C. S.A");
		bankEntitiesMap.put("1520", "Mediobanca, S.E.");
		bankEntitiesMap.put("1523", "Mercedes-Benz Bank AG, S.E.");
		bankEntitiesMap.put("4799", "Mercedes-Benz Financial Services Espa" + String.valueOf("\u00F1") + "a E.F.C., S.A.");
		bankEntitiesMap.put("1552", "Mirabaud & CIE (Europe), S.A., S.E.");
		bankEntitiesMap.put("1559", "Mizuho Bank Europe N.V., S.E.");
		bankEntitiesMap.put("0160", "MUFG Bank (Europe) N.V., S.E.");
		bankEntitiesMap.put("1563", "N26 Bank GmbH");
		bankEntitiesMap.put("1479", "Natixis, S.A., S.E.");
		bankEntitiesMap.put("1566", "Natwest Markets N.V., S.E");
		bankEntitiesMap.put("0131", "Novo Banco, S.A., S.E.");
		bankEntitiesMap.put("0133", "Nuevo Micro Bank, S.A");
		bankEntitiesMap.put("8814", "Oney Servicios Financieros, E.F.C., S.A.");
		bankEntitiesMap.put("1565", "Opel Bank, S.A., SE");
		bankEntitiesMap.put("0073", "Open Bank, S.A.");
		bankEntitiesMap.put("1568", "Orange Bank S.A., S.E.");
		bankEntitiesMap.put("6707", "Pecunia Cards E.D.E. S.L");
		bankEntitiesMap.put("1488", "Pictet & Cie (Europe), S.A., S.E.");
		bankEntitiesMap.put("6713", "Prepaid Financial Services Limited, S.E");
		bankEntitiesMap.put("8838", "PSA Financial Services Spain E.F.C. S.A");
		bankEntitiesMap.put("1534", "Quintet Private Bank (Europe) S.A.,S.E.");
		bankEntitiesMap.put("1558", "RBC EUROPE LIMITED, SUCURSAL EN ESPA" + String.valueOf("\u00F1") + "A");
		bankEntitiesMap.put("1508", "RCI Banque, S.A., S.E.");
		bankEntitiesMap.put("0083", "RENTA 4 Banco, S.A.");
		bankEntitiesMap.put("3138", "Ruralnostra, Sociedad Cooperativa de cr" + String.valueOf("\u00E9") + "dito Valenciana");
		bankEntitiesMap.put("0242", "Sabadell Consumer Finance, S.A.");
		bankEntitiesMap.put("8835", "Santander Brasil, E.F.C., S.A.");
		bankEntitiesMap.put("0224", "Santander Consumer Finance, S.A.");
		bankEntitiesMap.put("8236", "Santander Consumer, E.F.C., S.A.");
		bankEntitiesMap.put("8906", "Santander Factoring y Confirming, S.A., E.F.C.");
		bankEntitiesMap.put("0036", "Santander Investment, S.A.");
		bankEntitiesMap.put("4797", "Santander Lease, S.A. EFC");
		bankEntitiesMap.put("0038", "Santander Securities Services,S.A.");
		bankEntitiesMap.put("8813", "Scania Finance Hispania, E.F.C., S.A.");
		bankEntitiesMap.put("6705", "SEFIDE, E.D.E. S.L.");
		bankEntitiesMap.put("8795", "Servicios Financieros Carrefour, E.F.C., S.A.");
		bankEntitiesMap.put("8434", "Servicios Prescriptor y Medios de Pagos, E.F.C., S.A.");
		bankEntitiesMap.put("8433", "SG Equipment Finance Iberia, E.F.C., S.A.");
		bankEntitiesMap.put("1490", "Singular Bank, S.A.");
		bankEntitiesMap.put("1551", "SMBC Bank EU AG, S.E.");
		bankEntitiesMap.put("8816", "Sociedad Conjunta para la Emisi" + String.valueOf("\u00F3") + "n y Gesti" + String.valueOf("\u00F3") + "n de Medios de Pago, E.F.C., S.A");
		bankEntitiesMap.put("0108", "Soci" + String.valueOf("\u00E9") + "t" + String.valueOf("\u00E9") + " Gen" + String.valueOf("\u00E9") + "rale, S.E.");
		bankEntitiesMap.put("0216", "Targobank, S.A.");
		bankEntitiesMap.put("8836", "Telefonica Consumer Finance, EFC, S.A.");
		bankEntitiesMap.put("1570", "The Governor and Company of the Bank of Ireland, S.E.");
		bankEntitiesMap.put("1487", "Toyota Kreditbank GMBH, S.E.");
		bankEntitiesMap.put("4784", "Transolver Finance, E.F.C., S.A.");
		bankEntitiesMap.put("1491", "Triodos Bank, N.V., S.E.");
		bankEntitiesMap.put("0226", "UBS Europe SE, S.E.");
		bankEntitiesMap.put("2103", "Unicaja Banco, S.A.");
		bankEntitiesMap.put("1657", "Unicredit. S.P.A. S.E");
		bankEntitiesMap.put("8596", "Uni" + String.valueOf("\u00F3") + "n Cto. Fin. Mob. e Inm., Credifimo, E.F.C., S.A.");
		bankEntitiesMap.put("8512", "Uni" + String.valueOf("\u00F3") + "n de Cr" + String.valueOf("\u00E9") + "ditos Inmobiliarios, S.A., E.F.C.");
		bankEntitiesMap.put("8769", "Uni" + String.valueOf("\u00F3") + "n Financiera Asturiana, S.A., E.F.C.");
		bankEntitiesMap.put("6709", "Up Aganea EDE, SA");
		bankEntitiesMap.put("8806", "VFS Financial Services Spain E.F.C., S.A.");
		bankEntitiesMap.put("6715", "Viva Payment Services, S.A. S.E.");
		bankEntitiesMap.put("1480", "Volkswagen Bank GmbH, S.E.");
		bankEntitiesMap.put("0229", "Wizink Bank, S.A.");
		bankEntitiesMap.put("8840", "Xfera Consumer Finance, E.F.C. S.A.");
		bankEntitiesMap.put("1560", "Younited, S.E.");
		
		bankEntities = Collections.unmodifiableMap(bankEntitiesMap);
		
	}

	public static Collection<String> getAllEntriesCollection() {
		Collection<String> entries = new ArrayList<String>();
		
		for(Entry<String, String> entry : bankEntities.entrySet())
			entries.add(entry.getKey() + " - " + entry.getValue());
		
		return entries;
	}
	
	public static String getEntryByCode(String code) {
		if(null == code) return "";
		
		return code + " - " + bankEntities.get(code);
	}
	
	public static String getBankEntity(String code) {
		String bankEntity = bankEntities.getOrDefault(code, "CUENTA");
		if(bankEntity.length() > 25) {
			bankEntity = bankEntity.substring(0, 24);
		}
		return bankEntity;
	}
	
	
}
