package com.esferalia.aon.gwt.payroll.shared;

import java.util.HashMap;
import java.util.Map;

public class FormativeLevel {
	private static final Map<String, String> FORMATIVELEVEL = new HashMap<String,String>(){
		{
			put("11", "ESTUDIOS PRIMARIOS INCOMPLETOS");
			put("12", "ESTUDIOS PRIMARIOS COMPLETO");
			put("21", "PROGRAMAS PARA FORMACION E INSERCION LABORAL QUE NO PRECISAN DE UNA TITULACION");
			put("22", "PRIMERA ETAPA DE EDUCACION SECUNDARIA SIN TITULO DE GRADUADO ESCOLAR O EQUIVALENTE");
			put("23", "PRIMERA ETAPA DE EDUCACION SECUNDARIA CON TITULO DE GRADUADO ESCOLAR O EQUIVALENTE");
			put("31", "PROGRAMAS PARA FORMACION E INSERCION LABORAL QUE PRECISAN DE UNA TITULACION DE ESTUDIOS SECUNDARIOS DE PRIMERA ETAPA");
			put("32", "ENSE" + String.valueOf("\u00D1") + "ANZAS DE BACHILLERATO");
			put("33", "ENSE" + String.valueOf("\u00D1") + "ANZAS DE GRADO MEDIO DE FORMACION ESPECIFICA, ARTES PLASTICAS...");
			put("34", "ENSE" + String.valueOf("\u00D1") + "ANZAS DE GRADO MEDIO DE MUSICA Y DANZA");
			put("41", "ENSE" + String.valueOf("\u00D1") + "ANZAS PARA LA FORMACION E INSERCION LABORAL QUE PRECISAN DE UNA TITULACION DE ESTUDIOS SECUNDARIOS DE SEGUNDA ETAPA");
			put("51", "ENSE" + String.valueOf("\u00D1") + "ANZAS DE GRADO SUPERIOR DE FORMACION PROFESIONAL ESPECIFICA Y EQUIVALENTE");
			put("52", "TITULOS PROPIOS DE LAS UNIVERSIDADES Y OTRAS ENSE" + String.valueOf("\u00D1") + "ANZAS QUE PRECISAN DEL TITULO");
			put("53", "ENSE" + String.valueOf("\u00D1") + "ANZAS PARA LA FORMACION E INSERCION LABORAL QUE PRECISAN DE UNA FORMACION PROFESIONAL");
			put("54", "ENSE" + String.valueOf("\u00D1") + "ANZAR UNIVERSITARIAS DE PRIMER CICLO Y EQUIVALENTES");
			put("55", "ENSE" + String.valueOf("\u00D1") + "ANZAR UNIVERSITARIAS DE SEGUNDO CICLO Y EQUIVALENTES");
			put("56", "ESTUDIOS OFICIALES DE ESPECIALIZACION PREFESIONAL");
			put("57", "PROGRAMAS DE POSTGRADO IMPARTIDOS POR LAS UNIVERSIDADES U OTRAS INSTITUCIONES");
			put("58", "PROGRAMAS DE FORMACION E INSERCION LABORAL QUE PRECISAN DE UNA TITULACION UNIVERSITARIA");
			put("59", "ENSE" + String.valueOf("\u00D1") + "ANZAS UNIVERSITARIAS DE GRADO");
			put("60", "ENSE" + String.valueOf("\u00D1") + "ANZAS UNIVERSITARIAS DE MASTER");
			put("61", "DOCTORADO UNIVERSITARIO");
			put("80", "SIN ESTUDIOS");
		}
	};
	
	public Map<String, String> getFormativeLevelMap(){
		return FORMATIVELEVEL;
	}
	
	public String getFormativeLevelDescription(String code) {
		return FORMATIVELEVEL.getOrDefault(code, "");
	}
}
