package com.esferalia.aon.gwt.payroll.shared;

import java.util.HashMap;
import java.util.Map;

public class FormativeLevel {
	private static Map<String, String> formativeLevel = new HashMap<>();
	
	public FormativeLevel() {
		formativeLevel.put("11", "ESTUDIOS PRIMARIOS INCOMPLETOS");
		formativeLevel.put("12", "ESTUDIOS PRIMARIOS COMPLETO");
		formativeLevel.put("21", "PROGRAMAS PARA FORMACION E INSERCION LABORAL QUE NO PRECISAN DE UNA TITULACION");
		formativeLevel.put("22", "PRIMERA ETAPA DE EDUCACION SECUNDARIA SIN TITULO DE GRADUADO ESCOLAR O EQUIVALENTE");
		formativeLevel.put("23", "PRIMERA ETAPA DE EDUCACION SECUNDARIA CON TITULO DE GRADUADO ESCOLAR O EQUIVALENTE");
		formativeLevel.put("31", "PROGRAMAS PARA FORMACION E INSERCION LABORAL QUE PRECISAN DE UNA TITULACION DE ESTUDIOS SECUNDARIOS DE PRIMERA ETAPA");
		formativeLevel.put("32", "ENSE\u00D1ANZAS DE BACHILLERATO");
		formativeLevel.put("33", "ENSE\u00D1ANZAS DE GRADO MEDIO DE FORMACION ESPECIFICA, ARTES PLASTICAS...");
		formativeLevel.put("34", "ENSE\u00D1ANZAS DE GRADO MEDIO DE MUSICA Y DANZA");
		formativeLevel.put("41", "ENSE\u00D1ANZAS PARA LA FORMACION E INSERCION LABORAL QUE PRECISAN DE UNA TITULACION DE ESTUDIOS SECUNDARIOS DE SEGUNDA ETAPA");
		formativeLevel.put("51", "ENSE\u00D1ANZAS DE GRADO SUPERIOR DE FORMACION PROFESIONAL ESPECIFICA Y EQUIVALENTE");
		formativeLevel.put("52", "TITULOS PROPIOS DE LAS UNIVERSIDADES Y OTRAS ENSE" + String.valueOf("\u00D1") + "ANZAS QUE PRECISAN DEL TITULO");
		formativeLevel.put("53", "ENSE\u00D1ANZAS PARA LA FORMACION E INSERCION LABORAL QUE PRECISAN DE UNA FORMACION PROFESIONAL");
		formativeLevel.put("54", "ENSE\u00D1ANZAS UNIVERSITARIAS DE PRIMER CICLO Y EQUIVALENTES");
		formativeLevel.put("55", "ENSE\u00D1ANZAS UNIVERSITARIAS DE SEGUNDO CICLO Y EQUIVALENTES");
		formativeLevel.put("56", "ESTUDIOS OFICIALES DE ESPECIALIZACION PREFESIONAL");
		formativeLevel.put("57", "PROGRAMAS DE POSTGRADO IMPARTIDOS POR LAS UNIVERSIDADES U OTRAS INSTITUCIONES");
		formativeLevel.put("58", "PROGRAMAS DE FORMACION E INSERCION LABORAL QUE PRECISAN DE UNA TITULACION UNIVERSITARIA");
		formativeLevel.put("59", "ENSE\u00D1ANZAS UNIVERSITARIAS DE GRADO");
		formativeLevel.put("60", "ENSE\u00D1ANZAS UNIVERSITARIAS DE MASTER");
		formativeLevel.put("61", "DOCTORADO UNIVERSITARIO");
		formativeLevel.put("80", "SIN ESTUDIOS");
	}
	
	public Map<String, String> getFormativeLevelMap(){
		return formativeLevel;
	}
	
	public String getFormativeLevelDescription(String code) {
		return formativeLevel.getOrDefault(code, "");
	}
}
