bgcolor_color_de_fondo_blanco = #ffffff
bgcolor_color_de_fondo_azul = #6699ff
bgcolor_color_de_fondo_azul_oscuro = #3366ff
color_color_texto = #666666
color_cabecera_color_texto = #6699ff
color_cabecera_color_de_texto_link = #ffffff
color_contenidos_color_de_texto_link_hover = #3366ff
color_pie_color_de_texto = #ffffff
font_fuente = 3
