bgcolor_color_de_fondo_cabecera = #ffffff
bgcolor_color_de_fondo_cabecera_link = #0478CE
bgcolor_color_de_fondo_cabecera_link_hover = #000066
bgcolor_color_de_fondo_contenido = #ffffff
bgcolor_color_de_fondo_menu = #cccccc
bgcolor_color_de_fondo_pie = #d5dbe1
color_color_de_texto_contenido = #000000
color_color_de_texto_menu = #000000
color_color_de_texto_menu_link = #ffffff
color_color_de_texto_pie = #000000
color_color_de_texto_cabecera = #ffffff
font_fuente = 3
size_tamaño_de_fuente = 12
size_tamaño_de_fuente_pie = 10	
color_color_borde = #e55302