<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="audaBridge" targetNamespace="auda" xmlns:ns1="http://soap.audabridge.audatex.com/" xmlns:ns2="http://cxf.apache.org/bindings/xformat" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="auda" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <wsdl:import location="http://audabridge.audatex.es/AudaBridge/services/AudaBridge?wsdl=IAudaBridgeService.wsdl" namespace="http://soap.audabridge.audatex.com/">
    </wsdl:import>
  <wsdl:binding name="audaBridgeSoapBinding" type="ns1:IAudaBridgeService">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="getDataInfo">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="getDataInfo">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="getDataInfoResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="audaBridge">
    <wsdl:port binding="tns:audaBridgeSoapBinding" name="audaBridgeServicePort">
      <soap:address location="http://audabridge.audatex.es/AudaBridge/services/AudaBridge"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>