<?xml version="1.0"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<parent>
		<groupId>com.code.aon</groupId>
		<artifactId>aon.parent</artifactId>
		<version>1.0.1</version>
	</parent>
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.code.aon</groupId>
	<artifactId>aon.ui.ecm</artifactId>
	<version>2.0.0</version>
	<name>AON ECM</name>
	<description>Enterprise Content Management</description>
	<dependencies>

		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.resources</artifactId>
			<version>3.2.0</version>
			<scope>compile</scope>
			<exclusions>
				<exclusion>
					<groupId>log4j</groupId>
					<artifactId>log4j</artifactId>
				</exclusion>
				<exclusion>
					<groupId>com.code.aon</groupId>
					<artifactId>aon.ql</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.hibernate</groupId>
					<artifactId>hibernate</artifactId>
				</exclusion>
				<exclusion>
					<groupId>commons-dbcp</groupId>
					<artifactId>commons-dbcp</artifactId>
				</exclusion>
				<exclusion>
					<groupId>velocity</groupId>
					<artifactId>velocity</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.hibernate</groupId>
					<artifactId>hibernate-annotations</artifactId>
				</exclusion>
				<exclusion>
					<groupId>velocity-tools</groupId>
					<artifactId>velocity-tools</artifactId>
				</exclusion>
			</exclusions>
		</dependency>

		<dependency>
		    <groupId>org.apache.jackrabbit</groupId>
		    <artifactId>jackrabbit-core</artifactId>
		    <version>1.3.3</version>
			<scope>compile</scope>
			<exclusions>
				<exclusion>
					<groupId>org.apache.geronimo.specs</groupId>
					<artifactId>geronimo-jta_1.0.1B_spec</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.apache.derby</groupId>
					<artifactId>derby</artifactId>
				</exclusion>
				<exclusion>
					<groupId>xerces</groupId>
					<artifactId>xercesImpl</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.slf4j</groupId>
					<artifactId>slf4j-api</artifactId>
				</exclusion>
				<exclusion>
					<groupId>poi</groupId>
					<artifactId>poi</artifactId>
				</exclusion>
			</exclusions>
		</dependency> 
		<dependency>
		    <groupId>org.apache.jackrabbit</groupId>
		    <artifactId>jackrabbit-index-filters</artifactId>
		    <version>1.2.3</version>
			<scope>compile</scope>
			<exclusions>
				<exclusion>
					<groupId>poi</groupId>
					<artifactId>poi</artifactId>
				</exclusion>
			</exclusions>
		</dependency>

		<dependency>
			<groupId>net.sf.ehcache</groupId>
			<artifactId>ehcache</artifactId>
			<version>1.5.0</version>
			<scope>compile</scope>
		</dependency> 

		<dependency>
			<groupId>poi</groupId>
			<artifactId>poi</artifactId>
			<version>3.0-FINAL</version>
			<scope>compile</scope>
		</dependency>

		<dependency>
		    <groupId>pdfbox</groupId>
		    <artifactId>pdfbox</artifactId>
		    <version>0.7.3</version>
		</dependency> 

		<dependency>
		    <groupId>org.fontbox</groupId>
		    <artifactId>fontbox</artifactId>
		    <version>0.1.0</version>
		</dependency> 

		<dependency>
		    <groupId>org.slf4j</groupId>
		    <artifactId>slf4j-log4j12</artifactId> 
		    <version>1.4.3</version>
			<scope>compile</scope>
		</dependency> 

		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.security</artifactId>
			<version>1.7.0</version>
			<scope>provided</scope>
		</dependency>

		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.security.bridge</artifactId>
			<version>1.7.0</version>
			<scope>compile</scope>
		</dependency>

		<dependency>
			<groupId>org.apache.tomcat</groupId>
			<artifactId>coyote</artifactId>
			<version>6.0.13</version>
			<scope>provided</scope>
		</dependency>

		<dependency>
			<groupId>javax.servlet</groupId>
			<artifactId>servlet-api</artifactId>
			<version>2.4</version>
			<scope>provided</scope>
		</dependency>

		<dependency>
			<groupId>javax.faces</groupId>
			<artifactId>jsf-api</artifactId>
			<version>1.2_02</version>
			<scope>provided</scope>
		</dependency>

		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.1</version>
			<scope>test</scope>
		</dependency>

	</dependencies>
</project>
