<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>com.code.aon</groupId>
		<artifactId>aon.parent</artifactId>
		<version>9.23-SNAPSHOT</version>
	</parent>
	
	<groupId>com.esferalia.aon</groupId>
	<artifactId>aon.dsi.nominas</artifactId>
	<packaging>jar</packaging>

	<name>AON-DSI-NOMINAS</name>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
	</properties>

	<build>
		<plugins>
          	<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
	      		<configuration>
					<skipTests>true</skipTests>
				</configuration>
			</plugin>
		</plugins>
	</build>
	
	<dependencies>
		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter</artifactId>
			<version>5.13.3</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>com.googlecode.paradoxdriver</groupId>
			<artifactId>paradoxdriver</artifactId>
			<version>1.6.0</version>
		</dependency>
		<dependency>
			<groupId>com.mysql</groupId>
			<artifactId>mysql-connector-j</artifactId>
			<version>9.6.0</version>
			<scope>compile</scope>
			<optional>false</optional>
		</dependency>
	 	<dependency>
			<groupId>com.esferalia.aon</groupId>
			<artifactId>aon.payroll</artifactId>
			<version>${project.version}</version>
			<scope>compile</scope>
		</dependency>
	</dependencies>
</project>
