<?xml version="1.0" encoding="ISO-8859-1"?>
<xs:schema targetNamespace="http://www.seg-social.es/creta/esquemas/V100/Bases" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.seg-social.es/creta/esquemas/V100/Bases" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="Bases">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Autorizado"/>
				<xs:element ref="ReferenciaExterna"/>
				<xs:element ref="IndicadorRectificacion" minOccurs="0"/>
				<xs:element ref="Liquidacion" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Autorizado">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:pattern value="\d\d\d\d\d\d\d\d"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="ReferenciaExterna">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
				<xs:maxLength value="8"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="IndicadorRectificacion">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="S"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<!--xs:element name="Liquidacion">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Ccc"/>
				<xs:choice>
					<xs:sequence>
						<xs:element ref="CccConcertado"/>
						<xs:element ref="PeriodoDesde"/>
						<xs:element ref="PeriodoHasta"/>
						<xs:element ref="Tipo"/>
						<xs:element ref="FechaControl" minOccurs="0"/>
					</xs:sequence>
					<xs:sequence>
						<xs:element ref="PeriodoDesde"/>
						<xs:element ref="PeriodoHasta"/>
						<xs:element ref="Tipo"/>
						<xs:choice>
							<xs:element ref="FechaControl" minOccurs="0"/>
							<xs:element ref="AceptarBasesAnteriores" minOccurs="0"/>
						</xs:choice>
					</xs:sequence>
				</xs:choice>
				<xs:choice>
					<xs:sequence>
						<xs:element ref="DatosLiquidacion"/>
						<xs:element ref="LiquidacionMes" minOccurs="0" maxOccurs="unbounded"/>
					</xs:sequence>
					<xs:element ref="LiquidacionMes" maxOccurs="unbounded"/>
				</xs:choice>
			</xs:sequence>
		</xs:complexType>
	</xs:element-->
	<xs:element name="Liquidacion">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Ccc"/>
				<xs:element ref="CccConcertado"/>
				<xs:element ref="PeriodoDesde"/>
				<xs:element ref="PeriodoHasta"/>
				<xs:element ref="Tipo"/>
				<xs:element ref="FechaControl" minOccurs="0"/>
				<xs:element ref="AceptarBasesAnteriores" minOccurs="0"/>
				<xs:element ref="DatosLiquidacion"/>
				<xs:element ref="LiquidacionMes" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="CtaCot">
		<xs:sequence>
			<xs:element ref="Regimen"/>
			<xs:element ref="Provincia"/>
			<xs:element ref="Numero"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="Ccc" type="CtaCot"/>
	<xs:element name="CccConcertado" type="CtaCot"/>
	<xs:element name="Regimen">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:pattern value="\d\d\d\d"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Provincia">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:pattern value="\d\d"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Numero">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:pattern value="\d{9}"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="PeriodoDesde" type="Periodo"/>
	<xs:element name="PeriodoHasta" type="Periodo"/>
	<xs:element name="Tipo">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="3"/>
				<xs:maxLength value="3"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="FechaControl" type="Periodo"/>
	<xs:complexType name="Periodo">
		<xs:sequence>
			<xs:element ref="Mes"/>
			<xs:element ref="Anho"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="Mes">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="12"/>
				<xs:enumeration value="11"/>
				<xs:enumeration value="10"/>
				<xs:enumeration value="09"/>
				<xs:enumeration value="08"/>
				<xs:enumeration value="07"/>
				<xs:enumeration value="06"/>
				<xs:enumeration value="05"/>
				<xs:enumeration value="04"/>
				<xs:enumeration value="03"/>
				<xs:enumeration value="02"/>
				<xs:enumeration value="01"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Anho">
		<xs:simpleType>
			<xs:restriction base="xs:string">
					<!-- Sólo se admiten años mayores o iguales a 2006 hasta 2099 -->
					<xs:pattern value="200[6-9]|20[1-9][0-9]"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="AceptarBasesAnteriores">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="S"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="DatosLiquidacion">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Dato" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="DatosMes">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Dato" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Dato">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="TipoDato"/>
				<xs:element ref="Codigo"/>
				<xs:element ref="Valor"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="TipoDato">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:length value="1"/>
				<xs:enumeration value="C"/>
				<xs:enumeration value="H"/>
				<xs:enumeration value="I"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Codigo">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="2"/>
				<xs:maxLength value="3"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Valor">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
				<xs:maxLength value="11"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<!--xs:element name="LiquidacionMes">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="MesLiquidativo"/>
				<xs:choice>
					<xs:sequence>
						<xs:element ref="DatosMes"/>
						<xs:element ref="Trabajadores" minOccurs="0"/>
					</xs:sequence>
					<xs:element ref="Trabajadores"/>
				</xs:choice>
			</xs:sequence>
		</xs:complexType>
	</xs:element-->
	<xs:element name="LiquidacionMes">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="MesLiquidativo"/>
				<xs:element ref="DatosMes"/>
				<xs:element ref="Trabajadores"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="MesLiquidativo" type="Periodo"/>
	<xs:element name="Trabajadores">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Trabajador" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Trabajador">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Naf"/>
				<xs:element ref="Tramos"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Naf">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:pattern value="\d{12}"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Tramos">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Tramo" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Tramo">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="FechaDesdeAlta" minOccurs="0"/>
				<xs:element ref="FechaHastaAlta" minOccurs="0"/>				
				<xs:element ref="FechaDesde"/>
				<xs:element ref="FechaHasta"/>
				<xs:choice>
					<xs:element ref="MarcaBorrado"/>
					<xs:element ref="DatosTramo"/>
				</xs:choice>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="Fecha">
		<xs:sequence>
			<xs:element ref="Dia"/>
			<xs:element ref="Mes"/>
			<xs:element ref="Anho"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="Dia">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="2"/>
				<xs:maxLength value="2"/>
				<xs:pattern value="\d\d"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="FechaDesde" type="Fecha"/>
	<xs:element name="FechaHasta" type="Fecha"/>
	<xs:element name="FechaDesdeAlta" type="Fecha"/>
	<xs:element name="FechaHastaAlta" type="Fecha"/>
	<xs:element name="MarcaBorrado">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="N"/>
				<xs:enumeration value="S"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="DatosTramo">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Dato" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>
