package com.code.aon.payroll.principales.empresa;




import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EmprctraId generated by Expand 2.0.1
 */
@Embeddable
public class EmprctraId  implements java.io.Serializable {

     private Integer codact;
     private Integer cdg;
     private Integer domicilio;

    


    @Column(name="codact", nullable=false, length=4)
    public Integer getCodact() {
        return this.codact;
    }
    
    public void setCodact(Integer codact) {
        this.codact = codact;
    }


    @Column(name="cdg", nullable=false, length=4)
    public Integer getCdg() {
        return this.cdg;
    }
    
    public void setCdg(Integer cdg) {
        this.cdg = cdg;
    }

    @Column(name="domicilio", nullable=false, length=4)
    public Integer getDomicilio() {
        return this.domicilio;
    }
    
    public void setDomicilio(Integer domicilio) {
        this.domicilio = domicilio;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EmprctraId) ) return false;
		 EmprctraId castOther = ( EmprctraId ) other; 
         
		 return (this.getCodact()==castOther.getCodact())
 && (this.getCdg()==castOther.getCdg())
 && (this.getDomicilio()==castOther.getDomicilio());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCodact();
         result = 37 * result + this.getCdg();
         result = 37 * result + this.getDomicilio();
         return result;
   }   
}


