GENERIC=true
BANNER=true
BANNER_GROUP=true
ARTICLE=true
ARTICLE_NEWS=true
ARTICLE_SERVICES=true
ARTICLE_EVENTS=true
ARTICLE_OTHER=true
DIRECT_ACCESS_GROUP=true
DOWNLOADS=true
DIRECT_ACCESS=true
LINK_CATEGORY=true
ACTIVITY=true
ALBUM_CATEGORY=true
BULLETIN_SUSCRIBE=true
NEXT_ARTICLES=true
