<?xml version="1.0" encoding="utf-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <parent>
    <groupId>com.code.aon</groupId>
    <artifactId>aon.parent</artifactId>
    <version>9.23-SNAPSHOT</version>
  </parent>
  <modelVersion>4.0.0</modelVersion>
  <artifactId>aon.ui.warehouse</artifactId>
  <description>AON UI WAREHOUSE</description>
  <name>AON UI WAREHOUSE</name>
  <dependencies>
    <dependency>
      <groupId>net.aonsolutions.core</groupId>
      <artifactId>pool</artifactId>
      <version>${project.version}</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>com.code.aon</groupId>
      <artifactId>aon.ui.form</artifactId>
      <version>${project.version}</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.code.aon</groupId>
      <artifactId>aon.ui.report</artifactId>
      <version>${project.version}</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.code.aon</groupId>
      <artifactId>aon.company</artifactId>
      <version>${project.version}</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.code.aon</groupId>
      <artifactId>aon.config</artifactId>
      <version>${project.version}</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.code.aon</groupId>
      <artifactId>aon.customer</artifactId>
      <version>${project.version}</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.esferalia.aon</groupId>
      <artifactId>aon.file.seres</artifactId>
      <version>${project.version}</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.esferalia.aon</groupId>
      <artifactId>aon.seres</artifactId>
      <version>${project.version}</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.esferalia.aon</groupId>
      <artifactId>aon.ingenet</artifactId>
      <version>${project.version}</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.code.aon</groupId>
      <artifactId>aon.finance</artifactId>
      <version>${project.version}</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.code.aon</groupId>
      <artifactId>aon.finance.bridge</artifactId>
      <version>${project.version}</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.code.aon</groupId>
      <artifactId>aon.product</artifactId>
      <version>${project.version}</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.code.aon</groupId>
      <artifactId>aon.purchase</artifactId>
      <version>${project.version}</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.code.aon</groupId>
      <artifactId>aon.purchase.bridge</artifactId>
      <version>${project.version}</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.code.aon</groupId>
      <artifactId>aon.registry</artifactId>
      <version>${project.version}</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.code.aon</groupId>
      <artifactId>aon.sales</artifactId>
      <version>${project.version}</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.esferalia.aon</groupId>
      <artifactId>aon.ui.carrier</artifactId>
      <version>${project.version}</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.code.aon</groupId>
      <artifactId>aon.ui.company</artifactId>
      <version>${project.version}</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.code.aon</groupId>
      <artifactId>aon.ui.customer</artifactId>
      <version>${project.version}</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.code.aon</groupId>
      <artifactId>aon.ui.finance</artifactId>
      <version>${project.version}</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.code.aon</groupId>
      <artifactId>aon.ui.product</artifactId>
      <version>${project.version}</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.code.aon</groupId>
      <artifactId>aon.ui.supplier</artifactId>
      <version>${project.version}</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.code.aon</groupId>
      <artifactId>aon.ui.tas</artifactId>
      <version>${project.version}</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.code.aon</groupId>
      <artifactId>aon.warehouse</artifactId>
      <version>${project.version}</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>org.apache.tomcat</groupId>
      <artifactId>tomcat-servlet-api</artifactId>
      <version>10.1.7</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>jakarta.faces</groupId>
      <artifactId>jsf-api</artifactId>
      <version>1.2_14</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>jakarta.el</groupId>
      <artifactId>el-api</artifactId>
      <version>1.0</version>
      <scope>provided</scope>
    </dependency>
  </dependencies>
</project>
