package com.esferalia.aon.payroll.ctsql2mysql;

import java.util.LinkedList;




public class Contract {
	
	static final String BASE="https://www.redtrabaja.es/es/portaltrabaja/resources/contenidos/empleo_formacion/Empleo/pdf/";
	final static Object [][] MODELS = {
		{"PE/170", "Mod_170_24sept.pdf", "CONTRATO DE TRABAJO INDEFINIDO"},
		{"PE/221", "Mod_221_24sept.pdf", "CONTRATO DE TRABAJO INDEFINIDO BONIFICADO"},
		{"PE/181", "Mod_181_24sept.pdf", "CONTRATO DE TRABAJO PARA LA REALIZACIÓN DE TRABAJOS FIJOS DISCONTÍNUOS"},
		{"PE/213", "Mod_213_29sept.pdf", "CONTRATO DE TRABAJO INDEFINIDO BONIFICADO PARA TRABAJADORES/AS DESEMPLEADOS/AS INCLUIDOS EN LOS PLANES SECTORIALES DE APOYO AL EMPLEO"},
		{"PE/183", "Mod_183_24sept.pdf", "COMUNICACIÓN DE CONVERSIÓN DE CONTRATO TEMPORAL EN CONTRATO INDEFINIDO"},
		{"PE/185", "Mod_185_24sept.pdf", "COMUNICACIÓN DE CONVERSIÓN DE CONTRATO TEMPORAL EN CONTRATO INDEFINIDO PARA LA REALIZACIÓN DE TRABAJOS FIJOS DISCONTÍNUOS"},
		{"PE/174", "Mod_174_24sept.pdf", "CONTRATO DE TRABAJO PARA TRABAJADORES/AS DESEMPLEADOS CONTEMPLADOS EN LA LEY 43/2006 DE 29 DE DICIEMBRE (BOE DE 30 DE DICIEMBRE) (ARTICULO 2, APARTADOS 4 Y 5)"},
		{"PE/202", "Mod_202_24sept.pdf", "CONTRATACIÓN DE TRABAJADORES/AS DESEMPLEADOS/AS MAYORES DE 52 AÑOS BENEFICIA-RIOS/AS DE LOS SUBSIDIOS POR DESEMPLEO. LEY 45/2002, DE 12 DE DICIEMBRE, DISPOSICIÓN TRANSITORIA QUINTA (B.O.E. DE 13 DE DICIEMBRE)"},
		{"PE/218", "Mod_218_24sept.pdf", "CONTRATO DE TRABAJO PARA TRABAJADORES/AS DESEMPLEADOS/AS CONTRATADOS POR EMPRESAS DE INSERCIÓN CONTEMPLADO EN LA LEY 44/2007 DE 13 DE DICIEMBRE (BOE DE 14 DE DICIEMBRE)"},
		{"PE/175", "Mod_175_24sept.pdf", "CONTRATO DE TRABAJO PARA LA FORMACIÓN"},
		{"PE/176", "Mod_176_29sept.pdf", "CONTRATO DE TRABAJO EN PRÁCTICAS"},
		{"PE/177", "Mod_177_25sept.pdf", "CONTRATO DE TRABAJO DE DURACIÓN DETERMINADA"},
		{"PE/179", "Mod_179_29sept.pdf", "CONTRATO DE TRABAJO DE INTERINIDAD CON BONIFICACIÓN PARA SUSTITUIR A TRABAJADORES/AS DURANTE LOS PERÍODOS DE DESCANSO POR MATERNIDAD, ADOPCIÓN, ACOGIMIENTO, RIESGO DURANTE EL EMBARAZO,RIESGO DURANTE LA LACTANCIA NATURAL O SUSPENSIÓN POR PATERNIDAD"},
		{"PE/206", "Mod_206_24sept.pdf", "CONTRATO DE TRABAJO DE DURACIÓN DETERMINADA DE INTERÉS SOCIAL/FOMENTO DE EMPLEO AGRARIO"},
		{"PE/193", "Mod_193.pdf", 		 "CONTRATO DE TRABAJO PARA TRABAJADORES/AS PENADOS/AS EN INSTITUCIONES PENITENICIARIAS"},
		{"PE/220", "Mod_220.pdf", 		 "CONTRATO DE TRABAJO PARA MENORES Y JÓVENES, EN CENTROS DE MENORES, SOMETIDOS A MEDIDAS DE INTERNAMIENTO, PREVISTAS EN LA L.O. 5/2000 DE 12 DE ENERO, REGULADORA DE LA RESPONSABILIDAD PENAL DE LOS/LAS MENORES"},
		{"PE/182", "Mod_182.pdf", 		 "CONTRATO DE TRABAJO DE RELEVO"},
	};

	final static Object [][] CODES = {
		
		{100, "INDEFINIDO, TIEMPO COMPLETO, ORDINARIO"},
		{109, "INDEFINIDO, TIEMPO COMPLETO, FOMENTO CONTRATACIÓN INDEFINIDA/EMPLEO, TRANSFORMACIÓN CONTRATO TEMPORAL"},
		{130, "INDEFINIDO, TIEMPO COMPLETO, MINUSVÁLIDOS"},
		{139, "INDEFINIDO, TIEMPO COMPLETO, MINUSVÁLIDOS, TRANSFORMACIÓN CONTRATO TEMPORAL"},
		{150, "INDEFINIDO, TIEMPO COMPLETO, FOMENTO CONTRATACIÓN INDEFINIDA/EMPLEO, INICIAL"},
		{189, "INDEFINIDO, TIEMPO COMPLETO, TRANSFORMACIÓN CONTRATO TEMPORAL"},
		
		{200, "INDEFINIDO, TIEMPO PARCIAL, ORDINARIO"},
		{209, "INDEFINIDO, TIEMPO PARCIAL, FOMENTO CONTRATACIÓN INDEFINIDA/EMPLEO, TRANSFORMACIÓN CONTRATO TEMPORAL"},
		{230, "INDEFINIDO, TIEMPO PARCIAL, MINUSVÁLIDOS,  "},
		{239, "INDEFINIDO, TIEMPO PARCIAL, MINUSVÁLIDOS, RANSFORMACIÓN CONTRATO TEMPORAL"},
		{250, "INDEFINIDO, TIEMPO PARCIAL, FOMENTO CONTRATACIÓN INDEFINIDA/EMPLEO, INICIAL"},
		{289, "INDEFINIDO, TIEMPO PARCIAL, TRANSFORMACIÓN CONTRATO TEMPORAL"},
		
		{300, "INDEFINIDO, FIJO/DISCONTINUO"},
		{309, "INDEFINIDO, FIJO/DISCONTINUO, FOMENTO CONTRATACIÓN INDEFINIDA/EMPLEO ESTABLE, TRANSFORMACIÓN CONTRATO TEMPORAL"},
		{330, "INDEFINIDO, FIJO/DISCONTINUO, MINUSVÁLIDOS"},
		{350, "INDEFINIDO, FIJO/DISCONTINUO, FOMENTO CONTRATACIÓN INDEFINIDA/EMPLEO ESTABLE, INICIAL"},
		{389, "INDEFINIDO, FIJO/DISCONTINUO, TRANSFORMACIÓN CONTRATO TEMPORAL"},
		
		{401, "DURACIÓN DETERMINADA, TIEMPO COMPLETO, OBRA O SERVICIO DETERMINADO"},
		{402, "DURACIÓN DETERMINADA, TIEMPO COMPLETO, EVENTUAL POR CIRCUNSTANCIAS DE LA PRODUCCIÓN"},
		{403, "DURACIÓN DETERMINADA, TIEMPO COMPLETO, INSERCIÓN"},
		{408, "TEMPORAL, TIEMPO COMPLETO, CARÁCTER ADMINISTRATIVO"},
		{410, "DURACIÓN DETERMINADA, TIEMPO COMPLETO, INTERINIDAD"},
		{418, "DURACIÓN DETERMINADA, TIEMPO COMPLETO, INTERINIDAD, CARÁCTER ADMINISTRATIVO"},
		{420, "TEMPORAL, TIEMPO COMPLETO, PRÁCTICAS"},
		{421, "TEMPORAL, TIEMPO COMPLETO, FORMACIÓN"},
		{430, "TEMPORAL, TIEMPO COMPLETO, MINUSVÁLIDOS"},
		{441, "TEMPORAL, TIEMPO COMPLETO, RELEVO"},
		{450, "TEMPORAL, TIEMPO COMPLETO, FOMENTO CONTRATACIÓN INDEFINIDA"},
		{452, "TEMPORAL, TIEMPO COMPLETO, FOMENTO DEL EMPLEO" }, //????
		
		{501, "DURACIÓN DETERMINADA, TIEMPO PARCIAL, OBRA O SERVICIO DETERMINADO"},
		{502, "DURACIÓN DETERMINADA, TIEMPO PARCIAL, EVENTUAL POR CIRCUNSTANCIAS"},
		{503, "DURACIÓN DETERMINADA, TIEMPO PARCIAL, INSERCIÓN"},
		{508, "TEMPORAL, TIEMPO PARCIAL, CARÁCTER ADMINISTRATIVO"},
		{510, "DURACIÓN DETERMINADA, TIEMPO PARCIAL, INTERINIDAD"},
		{518, "DURACIÓN DETERMINADA, TIEMPO PARCIAL, INTERINIDAD, CARÁCTER ADMINISTRATIVO"},
		{520, "TEMPORAL, TIEMPO PARCIAL, PRÁCTICAS"},
		{530, "TEMPORAL, TIEMPO PARCIAL, MINUSVÁLIDOS"},
		{540, "TEMPORAL, TIEMPO PARCIAL, JUBILADO PARCIAL"},
		{541, "TEMPORAL, TIEMPO PARCIAL, RELEVO"},
		{550, "TEMPORAL, TIEMPO PARCIAL, FOMENTO CONTRATACIÓN INDEFINIDA/EMPLEO ESTABLE "},
		{552, "TEMPORAL, TIEMPO PARCIAL, FOMENTO DEL EMPLEO"}, // ????

		{990, "OTROS CONTRATOS"},
	};

	final static Object [][] MODEL_CODES = {
		{"PE/170", 100},
		{"PE/170", 200},

		{"PE/221", 150},
		{"PE/221", 250},

		{"PE/181", 350},
		{"PE/181", 300},
		
		{"PE/213", 150},
		{"PE/213", 250},
		{"PE/213", 350},
		
		{"PE/183", 109},
		{"PE/183", 189},
		{"PE/183", 209},
		{"PE/183", 289},
		
		{"PE/185", 309},
		{"PE/185", 389},
		
		{"PE/174", 150},
		{"PE/174", 250},
		{"PE/174", 350},
		{"PE/174", 450},
		{"PE/174", 550},

		{"PE/202", 100},
		{"PE/202", 150},
		{"PE/202", 450},
		{"PE/202", 401},
		{"PE/202", 402},
		{"PE/202", 410},
		{"PE/202", 420},
		{"PE/202", 421},
		{"PE/202", 990},
		
		{"PE/218", 150},
		{"PE/218", 250},
		{"PE/218", 350},
		{"PE/218", 450},
		{"PE/218", 550},
		{"PE/218", 452},
		{"PE/218", 552},
		
		{"PE/175", 421},

		{"PE/176", 420},
		{"PE/176", 520},

		{"PE/177", 401},
		{"PE/177", 402},
		{"PE/177", 410},
		{"PE/177", 501},
		{"PE/177", 502},
		{"PE/177", 510},
		{"PE/177", 540},

		{"PE/179", 410},
		{"PE/179", 510},

		{"PE/206", 401},
		{"PE/206", 402},
		{"PE/206", 410},
		{"PE/206", 420},
		{"PE/206", 421},
		{"PE/206", 450},
		{"PE/206", 990},
		{"PE/206", 501},
		{"PE/206", 502},
		{"PE/206", 510},
		{"PE/206", 520},
		{"PE/206", 550},
		{"PE/206", 990},
		
		{"PE/193", 450},
		{"PE/193", 550},

		{"PE/220", 450},
		{"PE/220", 550},

		{"PE/182", 441},
		{"PE/182", 541},
	};


}
