bgcolor_color_de_fondo = #ffffff
bgcolor_color_de_fondo_menu = #d1dbbd
bgcolor_color_de_fondo_menu_hover = #FCFFF5
bgcolor_color_de_fondo_contenido = #FCFFF5
bgcolor_color_de_fondo_pie = #193340
color_color_de_texto = #000000
color_color_de_texto_pie = #ffffff
color_color_de_texto_cabecera = #ffffff
color_color_de_texto_menu = #2D5A71
color_color_de_texto_menu_hover = #193441
color_color_de_borde = #0A0A0B
font_fuente = 2
size_tamano_de_fuente = 12
size_tamano_de_fuente_pie = 10
size_tamano_de_fuente_menu = 14
border_borde = 2