<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>com.code.aon</groupId>
		<artifactId>aon.parent</artifactId>
		<version>8.94.2</version>
	</parent>
	<groupId>net.aonsolutions</groupId>
	<artifactId>creta</artifactId>
	<name>AON CRET@</name>
	<dependencies>
              	<dependency>
                        <groupId>com.esferalia.aon</groupId>
                        <artifactId>aon.occam</artifactId>
                        <version>${project.version}</version>
                        <scope>compile</scope>
                </dependency>
              	<dependency>
                        <groupId>net.aonsolutions</groupId>
                        <artifactId>aon.tgss</artifactId>
                        <version>${project.version}</version>
                        <scope>compile</scope>
                </dependency>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.1</version>
			<scope>test</scope>
		</dependency>
	</dependencies>
</project>
