#!/bin/sh
# The cret@ executable script.

# Copyright (C) 2015, AON SOLUTIONS, S.L.U


usage="usage: $0 [--version] [--help] <command> [<args>]"
help="$usage
The most commonly used $0 commands are:
   bases        Fichero de Bases
   tramos       Fichero de Solicitud de Trabajadores y Tramos

'$0 <command> --help' to read about a specific subcommand ."


classpath=/usr/share/java/mysql-connector-java.jar
classpath=$classpath:/usr/share/java/jooq.jar
classpath=$classpath:/usr/share/java/aon-tgss.jar
classpath=$classpath:/usr/share/java/aon-common.jar
classpath=$classpath:/usr/share/java/aon-occam.jar
classpath=$classpath:/usr/share/java/aon-salary.jar
classpath=$classpath:/usr/share/java/aon-payroll.jar
classpath=$classpath:/usr/share/java/commons-cli.jar
classpath=$classpath:/usr/share/java/aon-master-jooq.jar
classpath=$classpath:/usr/share/java/apache-commons-lang.jar
classpath=$classpath:/usr/share/java/apache-commons-logging.jar
classpath=$classpath:/usr/share/java/slf4j/api.jar
classpath=$classpath:/usr/share/java/slf4j/jcl.jar
classpath=$classpath:/usr/share/java/antlr.jar
classpath=$classpath:/usr/share/java/aon-ql.jar
classpath=$classpath:/usr/share/java/aon-watson.jar
classpath=$classpath:/usr/share/java/commons-math3.jar
classpath=$classpath:/usr/share/java/mvel2.jar
classpath=$classpath:/usr/share/java/aon-entity-common.jar
classpath=$classpath:/usr/share/java/aon-entity.jar
classpath=$classpath:/usr/share/java/aon-pool.jar
classpath=$classpath:/usr/share/java/jool.jar
classpath=$classpath:/usr/share/java/aon-aeat.jar
classpath=$classpath:usr/share/java/ModRet2015.jar
classpath=$classpath:usr/share/java/PRET-R150_shared.jar


case $1 in
"")    		exec echo -e "$help";;
--help)    	exec echo -e "$help";;
--version) 	exec echo -e "$version";;
bases)    	exec java -classpath $classpath com.esferalia.aon.payroll.tgss.creta.Bases ${@:2};;
tramos)    	exec java -classpath $classpath com.esferalia.aon.payroll.tgss.creta.TrabajadoresTramos ${@:2};;
-*)    		exec echo -e "Unknown option: $1.\r\n$usage";;
*)    		exec echo -e "$0: '$1' is not a $0 command. See '$0 --help'.";;
esac


