<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<parent>
		<groupId>com.code.aon</groupId>
		<artifactId>aon.parent</artifactId>
		<version>8.108</version>
	</parent>
	<modelVersion>4.0.0</modelVersion>
	<artifactId>aon-jasperreports</artifactId>
	<name>AON JASPERREPORTS TEMPLATES</name>
	<description>AON JASPERREPORTS TEMPLATES</description>

	<properties>
		<maven.compiler.source>1.8</maven.compiler.source>
		<maven.compiler.target>1.6</maven.compiler.target>
	</properties>
	
	<build>
		<plugins>
			<plugin>
				<groupId>${jasperreportsMavenPluginGroup}</groupId>
				<artifactId>${jasperreportsMavenPluginArtifact}</artifactId>
				<version>${project.version}</version>
				<executions>
					<execution>
						<phase>process-sources</phase>
						<goals>
							<goal>jasper</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<outputDirectory>${project.build.directory}/classes</outputDirectory>
					<verbose>true</verbose>
				</configuration>
				<dependencies>
					<dependency>
						<groupId>com.code.aon</groupId>
						<artifactId>aon-master</artifactId>
						<version>${project.version}</version>
						<scope>compile</scope>
						<exclusions>
							<exclusion>
								<artifactId>slf4j-api</artifactId>
								<groupId>org.slf4j</groupId>
							</exclusion>
						</exclusions>
					</dependency>
					<dependency>
						<groupId>com.code.aon</groupId>
						<artifactId>aon-dbutils</artifactId>
						<version>${project.version}</version>
						<scope>compile</scope>
						<exclusions>
							<exclusion>
								<artifactId>slf4j-api</artifactId>
								<groupId>org.slf4j</groupId>
							</exclusion>
						</exclusions>
					</dependency>
					<dependency>
						<groupId>com.code.aon</groupId>
						<artifactId>aon.ui.company</artifactId>
						<version>${project.version}</version>
						<scope>compile</scope>
					</dependency>
					<dependency>
						<groupId>com.code.aon</groupId>
						<artifactId>aon.ui.customer</artifactId>
						<version>${project.version}</version>
						<scope>compile</scope>
					</dependency>
					<dependency>
						<groupId>com.code.aon</groupId>
						<artifactId>aon.ui.finance</artifactId>
						<version>${project.version}</version>
						<scope>compile</scope>
					</dependency>
					<dependency>
						<groupId>com.esferalia.aon</groupId>
						<artifactId>aon.ui.pms</artifactId>
						<version>${project.version}</version>
						<scope>compile</scope>
					</dependency>
					<dependency>
						<groupId>com.code.aon</groupId>
						<artifactId>aon.ui.fiscal</artifactId>
						<version>${project.version}</version>
						<scope>compile</scope>
					</dependency>
					<dependency>
						<groupId>com.code.aon</groupId>
						<artifactId>aon.ui.accounting</artifactId>
						<version>${project.version}</version>
						<scope>compile</scope>
					</dependency>
					<dependency>
						<groupId>com.code.aon</groupId>
						<artifactId>aon.ui.academy</artifactId>
						<version>${project.version}</version>
						<scope>compile</scope>
					</dependency>
					<dependency>
						<groupId>com.esferalia.aon</groupId>
						<artifactId>aon.ui.payroll</artifactId>
						<version>${project.version}</version>
						<scope>compile</scope>
						<exclusions>
							<exclusion>
								<groupId>mysql</groupId>
								<artifactId>mysql-connector-java</artifactId>
							</exclusion>
							<exclusion>
								<groupId>org.slf4j</groupId>
								<artifactId>slf4j-jcl</artifactId>
							</exclusion>
						</exclusions>
					</dependency>
					<dependency>
						<groupId>com.code.aon</groupId>
						<artifactId>aon.ui.tas</artifactId>
						<version>${project.version}</version>
						<scope>compile</scope>
					</dependency>
					<dependency>
						<groupId>com.code.aon</groupId>
						<artifactId>aon.ui.purchase</artifactId>
						<version>${project.version}</version>
						<scope>compile</scope>
					</dependency>
				</dependencies>
			</plugin>
		</plugins>
	</build>
</project>
