export const ToolbarType = {
  APPLICATION: 'application',
  SECONDARY: 'secondary'
}

export const Role = {
  ADMIN: 'ADMIN',
	ACCOUNTING: 'ACCOUNTING', 		              // ACCESO A CONTABILIDAD -  MODO PORTAL/EMPRESA
	ACCOUNTING_MANAGER: 'ACCOUNTING_MANAGER',	  // ACCESO A CONTABILIDAD -  MODO ASESOR
	FISCAL: 'FISCAL',				                    // ACCESO A FISCAL -  MODO PORTAL/EMPRESA
	FISCAL_MANAGER: 'FISCAL_MANAGER',		        // ACCESO A FISCAL -  MODO ASESOR
	PAYROLL: 'PAYROLL',			                    // ACCESO A LABORAL -  MODO EMPLEADO
	PAYROLL_MANAGER: 'PAYROLL_MANAGER',	        // ACCESO A LABORAL - MODO ASESOR
	PAYROLL_PORTAL: 'PAYROLL_PORTAL',		        // ACCESO A LABORAL -  MODO PORTAL/EMPRESA
	DOCUMENTAL: 'DOCUMENTAL',			              // ACCESO A DOCUMENTAL -  MODO PORTAL/EMPRESA
	DOCUMENTAL_MANAGER: 'DOCUMENTAL_MANAGER',	  // ACCESO A DOCUMENTAL -  MODO ASESOR
	COMUNICA: 'COMUNICA',			                  // ACCESO A COMUNIC@ -  MODO EMPLEADO
	COMUNICA_MANAGER: 'COMUNICA_MANAGER',	      // ACCESO A COMUNIC@ -  MODO ASESOR
	COMUNICA_PORTAL: 'COMUNICA_PORTAL',	        // ACCESO A COMUNIC@ -  MODO PORTAL/EMPRESA
	TIMECONTROL: 'TIMECONTROL',		              // ACCESO A CONTROL DE HORARIO -  MODO EMPLEADO
	TIMECONTROL_MANAGER: 'TIMECONTROL_MANAGER', // ACCESO A CONTROL DE HORARIO -  MODO ASESOR
	TIMECONTROL_PORTAL: 'TIMECONTROL_PORTAL',   // ACCESO A CONTROL DE HORARIO -  MODO PORTAL/EMPRESA
	MESSENGER: 'MESSENGER',			                // ACCESO A MENSAJERIA -  MODO PORTAL/EMPRESA
	MESSENGER_MANAGER: 'MESSENGER_MANAGER',	    // ACCESO A MENSAJERIA -  MODO ASESOR
	INVOICE: 'INVOICE',			                    // ACCESO A FACTURAS - MODO EMPLEADO
	INVOICE_MANAGER: 'INVOICE_MANAGER',	        // ACCESO A FACTURAS - MODO ASESOR
	INVOICE_PORTAL: 'INVOICE_PORTAL',		        // ACCESO A FACTURAS - MODO PORTAL/EMPRESA
	MANAGEMENT: 'MANAGEMENT',			              // ACCESO A GESTION - MODO PORTAL/EMPRESA
	MANAGEMENT_MANAGER: 'MANAGEMENT_MANAGER',	  // ACCESO A GESTION - MODO ASESOR
	ALMA: 'ALMA',			           	              // ACCESO AL SERVICIO ALMA
	OCR: 'OCR',				                          // ACCESO AL SERVICIO OCR
	BANK: 'BANK',				                        // ACCESO AL SERVICIO BANK
	CONVENIOS: 'CONVENIOS',			                // ACCESO AL SERVICIO CONVENIOS
	AON: 'AON',
	BIDOQ: 'BIDOQ'
}
export const App = {
  INVOICE: 'INVOICE',
  DOCUMENTAL: 'DOCUMENTAL',
  MESSENGER: 'MESSENGER',
  ACCOUNTING: 'ACCOUNTING',
  FISCAL: 'FISCAL',
  PAYROLL: 'PAYROLL',
  OCR: 'OCR',
  AIO: 'AIO',
  ALMA: 'ALMA',
  COMUNICA: 'COMUNICA',
  BIDOQ: 'BIDOQ',
  CONVENIOS: 'CONVENIOS',
  BANK: 'BANK',
  TIMECONTROL: 'TIMECONTROL',
  MANAGEMENT: 'MANAGEMENT'
}
