bgcolor_color_de_fondo = #000000
bgcolor_color_de_fondo_cabecera = #000000
bgcolor_color_de_fondo_menu = #000000
bgcolor_color_de_fondo_contenido = #949494
bgcolor_color_de_fondo_pie = #000000
color_color_de_texto = #FFFFFF
color_color_de_texto_pie = #FFFFFF
color_color_de_texto_contenido = #FFFFFF
color_color_de_borde = #e55302
font_fuente = 3
size_tamano_de_fuente = 11
border_bordes = 0
color_color_de_texto_menu = #FFFFFF