<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<parent>
		<groupId>com.code.aon</groupId>
		<artifactId>aon.web.parent</artifactId>
		<version>1.0.1</version>
	</parent>
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.code.aon</groupId>
	<artifactId>aon.gta</artifactId>
	<packaging>war</packaging>
	<version>2.0.0</version>
	<description>AON GTA</description>
	<name>AON GTA</name>
	<build>
		<finalName>aon-gta</finalName>
	</build>
	<dependencies>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.customer</artifactId>
			<version>2.0.0</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.commercial</artifactId>
			<version>2.0.0</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.tas</artifactId>
			<version>2.0.0</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.warehouse</artifactId>
			<version>2.0.0</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.purchase</artifactId>
			<version>2.0.0</version>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.composite</artifactId>
			<version>2.0.0</version>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.account</artifactId>
			<version>2.0.0</version>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.finance</artifactId>
			<version>2.0.0</version>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.employee</artifactId>
			<version>2.0.0</version>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.sales.purchase</artifactId>
			<version>2.0.0</version>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.tas.commercial</artifactId>
			<version>2.0.0</version>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.tas.delivery</artifactId>
			<version>2.0.0</version>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.hyperview</artifactId>
			<version>2.0.0</version>
			<scope>runtime</scope>
		</dependency>
		<!--
			PARA CONSTRUIR CORRECTAMENTE EL WAR 		
		-->
		<dependency>
			<groupId>org.apache.myfaces.core</groupId>
			<artifactId>myfaces-api</artifactId>
			<version>1.1.5</version>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>javax.servlet.jsp</groupId>
			<artifactId>jsp-api</artifactId>
			<version>2.1</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>commons-fileupload</groupId>
			<artifactId>commons-fileupload</artifactId>
			<version>1.1</version>
			<scope>runtime</scope>
		</dependency>

	</dependencies>
</project>