<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<parent>
		<artifactId>aon.web.parent</artifactId>
		<groupId>com.code.aon</groupId>
		<version>1.0.5</version>
	</parent>
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.code.aon</groupId>
	<artifactId>aon-web-commercial</artifactId>
	<packaging>war</packaging>
	<name>AON WEB COMMERCIAL</name>
	<version>1.7.1</version>
	<description>AON WEB COMMERCIAL</description>
	<properties>
		<dbVersion>4.4.0</dbVersion>
	</properties>
	<build>
		<finalName>aon-commercial</finalName>
	</build>
	<dependencies>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.security.bridge</artifactId>
			<version>3.3.0</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId> 
			<artifactId>aon.security</artifactId>
			<version>1.8.0</version>
			<scope>provided</scope>
		</dependency>	
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.form</artifactId>
			<version>4.1.0</version>
			<scope>compile</scope>
		</dependency>		
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.rich.components</artifactId>
			<version>4.3.1</version>
			<scope>compile</scope>
		</dependency>		
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.resources</artifactId>
			<version>3.10.0</version>
			<scope>compile</scope>
			<exclusions>
				<exclusion>
					<artifactId>velocity</artifactId>
					<groupId>velocity</groupId>
				</exclusion>
				<exclusion>
					<artifactId>velocity-tools</artifactId>
					<groupId>velocity-tools</groupId>
				</exclusion>
				<exclusion>
					<artifactId>jmimemagic</artifactId>
					<groupId>jmimemagic</groupId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.commercial</artifactId>
			<version>4.6.0</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.registry</artifactId>
			<version>4.3.3</version>
			<scope>compile</scope>
		</dependency>		
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.product</artifactId>
			<version>4.5.0</version>			
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.company</artifactId>
			<version>4.2.0</version>			
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.geozone</artifactId>
			<version>4.0.1</version>
			<scope>compile</scope>
		</dependency>		
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.sales</artifactId>
			<version>4.3.0</version>
		</dependency>	
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.marketing</artifactId>
			<version>3.3.0</version>
		</dependency>
	</dependencies>
</project>