#!/bin/sh
. aondir-functions

APP=aon-enterprise

if ! aondir_has_app $APP; then

        aondir-addapp $APP &>/dev/null

        aondir-addrole User $APP &>/dev/null
        aondir-addrole Guest $APP &>/dev/null
        aondir-addrole Admin $APP &>/dev/null
        aondir-addrole Config $APP &>/dev/null
        aondir-addrole Auditor $APP &>/dev/null
        aondir-addrole Confidentiality $APP &>/dev/null
        aondir-addrole Product $APP &>/dev/null
        aondir-addrole Commercial $APP &>/dev/null
        aondir-addrole Sale $APP &>/dev/null
        aondir-addrole Purchase $APP &>/dev/null
        aondir-addrole Warehouse $APP &>/dev/null
        aondir-addrole Finance $APP &>/dev/null
        aondir-addrole Accounting $APP &>/dev/null
        aondir-addrole Statistics $APP &>/dev/null
        aondir-addrole eSignature $APP &>/dev/null
        aondir-addrole TaskMonitoring $APP &>/dev/null

        aondir-addprofile Administrador $APP Admin TaskMonitoring User &>/dev/null
        aondir-addprofile Gestion $APP Config Auditor Product Commercial Sale Purchase Warehouse Finance Statistics eSignature User &>/dev/null
        aondir-addprofile Invitado $APP Guest User &>/dev/null

else

        aondir-addprofile Gestion $APP Config Auditor Product Commercial Sale Purchase Warehouse Finance Statistics eSignature User &>/dev/null

fi
