// ----- A

export const ABOUT = 'Acerca de';
export const ACADEMIES = 'Acadèmies';
export const ACADEMY = 'Acadèmi';
export const ACCEPT = 'Acceptar';
export const ACCESS = "Accés";
export const ACCESS_TO_YOUR_AON_ACCOUNT = "Accedeix al teu compte d'AON";
export const ACCOUNT = 'Cuenta';
export const ACCOUNTED = 'Comptabilitzada';
export const ACCOUNTEDS = 'Comptabilitzades';
export const ACCOUNTING = 'Comptabilitat';
export const ACCOUNTING_SUMMARY = 'Resum Comptabilitat';
export const ACTIVATE = 'Activar';
export const ACTIVE = 'Activo';
export const ACTIVES = 'Actives';
export const ACTIVITY = 'Activitat';
export const ACTIVITY_SUMMARY = `Resum d'Activitats`;
export const ADD = 'Afegir';
export const ADD_CATEGORY = 'Afegir Categoria';
export const ADD_COMMENT = 'Afegir Comentari';
export const ADD_COMPOSITION = 'Afegir Composició';
export const ADD_CREDITOR = 'Afegir creditor';
export const ADD_CUSTOMER = 'Afegir client';
export const ADD_EXPENSE = 'Afegir despesa';
export const ADD_FILE = 'Adjuntar Fitxer';
export const ADD_INVEST_ASSET = 'Afegir bé afecte';
export const ADD_INVOICE = 'Afegir Factura';
export const ADD_NEW = "Afegir nou";
export const ADD_PRODUCT = 'Afegir producte';
export const ADD_PROJECT = 'Afegir projecte';
export const ADD_REMARKS = 'Afegir Observacions';
export const ADD_SCOPE = 'Afegir Àmbit';
export const ADD_ALL_SCOPES = 'Afegir tots els Àmbits';
export const ADD_SUPPLIER = 'Afegir Proveïdor';
export const ADD_TAG = 'Afegir Etiqueta';
export const ADD_TAX = 'Afegir Impost';
export const ADD_TO_STOCK = "Afegir a estoc";
export const ADD_TYPE = 'Afegir Tipus';
export const ADD_WORKGROUP = 'Afegir grup de treball';
export const ADDITIONAL_DATA = 'Dades addicionals';
export const ADDITIONAL_HIRING = "Contractació addicional";
export const ADDITIONAL_INFORMATION = 'Informació Addicional';
export const ADDRESS = 'Dirección';
export const ADVISER = 'Assessor';
export const ADVISERS = 'Assessors';
export const AGENT = 'Agent';
export const AGENTS = 'Agents';
export const ALIAS = 'Àlies';
export const ALL = 'Tot';
export const ALL1 = 'Tots';
export const ALL2 = 'Totes';
export const ALL_FILES = 'Tots els Fitxers';
export const AMOUNT = 'Import';
export const AMORTIZATION = 'Amortització';
export const ANNUAL_VIEW = 'Vista anual';
export const AON_BLUE = 'Blau Aon';
export const AON_SERVICES = 'Serveis Aon';
export const API_DOCUMENTATION = 'Documentació API';
export const APPLICATION = 'Aplicació';
export const APPLICATIONS = 'Aplicacions';
export const APPROVED = 'Aprovada';
export const ASESOR = 'Assessor';
export const ASSIGN = 'Assignar';
export const ATTACH_FILES_DRAGGING_DROPPING = 'Arrossega o selecciona el fitxer';
export const ATTACH_FILES_DRAGGING_DROPPING_BACKGROUND = 'Arrossega o selecciona el fons';
export const ATTACH_FILES_DRAGGING_DROPPING_LOGO = 'Arrossega o selecciona el logo';
export const AUDIT = 'Auditoria';
export const AUTOBOOKING = 'Auto-Contractació';
export const AVAILABLE = 'Disponible';
export const AVERAGE = 'Mitjana';

// ----- B

export const BACK = 'Endarrere';
export const BACKGROUND = 'Fons';
export const BACKGROUND_ADJUST = 'Ajustar Fons';
export const BANK = 'Banc';
export const BANK_ACCOUNT = 'Compte Bancari';
export const BANK_ACCOUNTS = 'Comptes Bancaris';
export const BANK_DATA = 'Dades Bancàries';
export const BANKS = 'Bancs';
export const BARCODE = 'Codi de Barres';
export const BASE = 'Base';
export const BASQUE = 'Euskera';
export const BI_MONTHLY = 'Bimestral';
export const BILLING = 'Facturació';
export const BILLABLE_USERS = "Usuaris facturables";
export const BLOCKED = 'Bloquejat';
export const BLOCKED_POPUP = "Ventana bloqueada!";
export const BOLD = 'Negreta';
export const BOOKING = 'Contractació';
export const BOOKING_PANEL = 'Panell de Contractació';
export const BOOKING_RESUME = 'Resum de Contractació';
export const BORDER = 'Vora';
export const BOX_CRITERION = 'Criteri de Caixa';
export const BUDGET = 'Pressupost';
export const BUDGETS = 'Pressupostos';
export const BUSINESS_NAME = 'Raó Social';

// ----- C

export const CAMPAIGN = 'Campanya';
export const CAMPAIGNS = 'Campanyes';
export const CANCEL = 'Cancel·lar';
export const CARRIER = 'Agència de Transport';
export const CARRIERS = 'Agències de Transport';
export const CAUSE = 'Motiu';
export const CATALAN = 'Català';
export const CATEGORY = 'Categoria';
export const CATEGORIES = 'Categories';
export const CERTIFICATE = 'Certificat';
export const CERTIFICATES = 'Certificats';
export const CERTIFICATIONS = 'Certificacions';
export const CHANGE_TYPE = 'Canviar Tipus';
export const CHARGES_AND_PAYMENTS = 'Cobraments i Pagaments';
export const CHANGE_PASSWORD = 'Canvia contrasenya';
export const CHOOSE_A_DOMAIN = 'Si us plau, seleccioneu un domini';
export const CITY = 'Ciudad';
export const CLASSIC = 'Clàssic';
export const CLASSIC_APPLICATIONS = 'Aplicacions Clàssiques';
export const CLASSIC_VIEW = 'Vista Clàssica';
export const CLIENT_FILE = 'Fitxa Client';
export const CLOSE = 'Tancar';
export const CLOSE_SESSION = 'Tancar Sessió';
export const CLOSED = 'Tancat';
export const CODE = 'Codi';
export const COMMENT = 'Comentari';
export const COMMENTS = 'Comentaris';
export const COMMERCE = 'Comerç'
export const COMMERCIAL = 'Comercial';
export const COMMERCIAL_NAME = 'Nom Comercial';
export const COMMERCIAL_PRODUCT = 'Producte Comercial';
export const COMMERCIAL_REGISTRY_CODE = 'Codi de registre mercantil';
export const COMMUNICATE = 'Comunicar';
export const COMMUNICATE_CONFIRM = 'Voleu comunicar a la seguretat social?';
export const COMMUNICATE_INVOICE = 'Comunicar Factura';
export const COMMUNICATION = 'Comunicació';
export const COMMUNICATIONS = 'Comunicacions';
export const COMPANIES = 'Empreses';
export const COMPANY = 'Empresa';
export const COMPANY_COSTS = `Costos d'Empresa`;
export const COMPANY_MANAGEMENT = `Gestió d'Empreses`;
export const COMPANY_SELECTION = `Selecció d'Empresa`;
export const COMPONENTS = 'Components';
export const COMPOSITION = 'Composició';
export const CONCEPT = 'Concepte';
export const CONCEPTS = 'Conceptes';
export const CONFIDENTIAL = 'Confidencial';
export const CONFIGURATION = 'Configuració';
export const CONFIRM = 'Confirmar';
export const CONSOLE = 'Consola';
export const CONTACT = 'Contacte';
export const CONTACT_DATA = 'Dades de Contacte';
export const CONTACT_DATA2 = "Dades de contacte"
export const CONTACTS = 'Contactes';
export const CONTAINER = 'Envàs';
export const CONTENT = 'Contingut';
export const CONTENT_INDEX = 'Índex de continguts';
export const CONTRACT = 'Contractar';
export const CONTRACTED_PRODUCTS = "Productes contractats";
export const CONTRACTED_USERS = "Usuaris contractats";
export const CONTRACT_PAYROLL = 'Contracte';
export const CONTRACTS = 'Contractes';
export const CONVERSATION = 'Conversa';
export const CONNECTING_TO = 'Connectant-se a';
export const COPIED_TO_CLIPBOARD = "Copiat al porta-retalls";
export const COPY = "Copiar";
export const COUNTRY = 'País';
export const CREATE = 'Crear'
export const CREATE_INVOICE = 'Crear Factura';
export const CREATE_QUERY = 'Crear consulta';
export const CREATED_BY = 'Creat per';
export const CREATION_DATE = 'Data de Creació';
export const CREDITOR = 'Creditor';
export const CREDITORS = 'Creditors';
export const CUSTOM_VIEW = 'Vista Personalitzada';
export const CUSTOMER =  'Client';
export const CUSTOMER_FEE = 'Quotes';
export const CUSTOMER_SEARCH =  'cerca de client';
export const CUSTOMER_SEARCH_DOMAIN_NOT_FOUND = "No s'han trobat clients relacionats amb aquest aquest domini";
export const CUSTOMER_SEARCH_NOT_FOUND = "No s'han trobat clients relacionats amb aquesta cerca";
export const CUSTOMERS = 'Clients';
export const CUSTOMIZE_INVOICE = 'Personalitzar Factura';

// ----- D

export const DATA = 'Dades';
export const DATE = 'Data';
export const DATE_CREATION = 'Data de creació';
export const DARK = 'Fosc';
export const DEACTIVATE = 'Desactivar';
export const DEFAULT_CATEGORIES = 'Categories per defecte';
export const DELETE = 'Esborrar';
export const DELETE_ALL_SCOPES = 'Eliminar tots els Àmbits';
export const DELETE_BACKGROUND_CONFIRM = "Estàs segur d'eliminar el fons";
export const DELETE_CATEGORY = 'Esborrar Categoria';
export const DELETE_CONFIRM = "Estàs segur d'eliminar";
export const DELETE_FILE = 'Esborrar Fitxer';
export const DELETE_FILE_CONFIRM = "Estàs segur d'eliminar el fitxer";
export const DELETE_FOREVER = 'Esborrar Definitivament';
export const DELETE_FOREVER_INVOICE_CONFIRMATION = `La factura s'ha esborrat definitivament.`;
export const DELETE_INVOICE = 'Esborrar Factura';
export const DELETE_LOGO_CONFIRM = "Estàs segur d'eliminar el logo";
export const DELETE_SCOPE = 'Esborrar Àmbit';
export const DELETE_TAG = 'Esborrar Etiqueta';
export const DELETE_TAX = 'Esborrar Impost';
export const DELETE_WAREHOUSE = 'Esborrar Magatzem';
export const DELETE_WORKGROUP = 'Esborrar Grup de treball';
export const DELETED_DATA = "Les dades s'han eliminat correctament";
export const DELIVERY = 'Albarà de Venda';
export const DELIVERY_TAG = 'Etiqueta d\'Enviament';
export const DESCRIPTION = 'Descripció';
export const DETAILED = 'Detallat';
export const DEUTSCH = 'Alemany';
export const DOCUMENT = 'Document';
export const DOCUMENT_DATA = 'Dades Document';
export const DOCUMENTS = 'Documents';
export const DISCARDED = 'Descartades';
export const DOCUMENTS_IN_PROCESS = 'Documents en tràmit';
export const DOCUMENTS_UNDER_REVIEW = 'Documents en revisió';
export const DOCUMENTARY = 'Documental';
export const DOCUMENTAL_FILE = 'Fitxa Documental';
export const DOMAIN = 'Domini';
export const DOMAIN_PARENT = 'Domini Pare';
export const DOMAIN_SEARCH = 'Cerca de domini';
export const DOWNLOAD = 'Descarregar';
export const DOWNLOAD_FILE = 'Descarregar Fitxer';
export const DOWNLOAD_FILES = 'Descarregar Fitxers';
export const DOWNLOAD_INVOICE = 'Descarregar Factura';
export const DOWNLOAD_INVOICES = 'Descarregar Factures';
export const DRAFT = 'Esborrany';
export const DRAFTS = 'Esborranys';
export const DROP_FILE = 'Deixa anar el fitxer';
export const DUPLICATE = 'Duplicar';
export const DUPLICATE_INVOICE = 'Duplicar Factura';
export const DURATION = 'Durada';

// ----- E

export const EDIT = 'Editar';
export const EDIT_CATEGORY = 'Editar Categoria';
export const EDIT_FILE = 'Editar Fitxer';
export const EDIT_FILES = 'Editar Fitxers';
export const EDIT_TAG = 'Editar Etiqueta';
export const EDIT_WAREHOUSE = 'Editar Magatzem';
export const EDIT_WORKGROUP = 'Editar grup de treball';
export const ELABORATION = 'Elaboració';
export const ELABORATIONS = 'Elaboracions';
export const EMAIL = 'Email';
export const EMAIL_ADD = 'Assignar adreça de correu electrònic';
export const EMAIL_VERIFICATION = 'Verificació adreça de correu electrònic';
export const EMAIL_ADD_DESCRIPTION = "És necessari assignar una adreça de correu electrònic a un compte per poder recuperar la contrasenya, rebre notificacions i confirmacions, i per a la seguretat del compte";
export const EMAIL_VERIFICATION_DESCRIPTION = '*Introduïu el codi de verificació que hem enviat a la vostra adreça de correu electrònic';
export const EMPLOYEE = 'Empleat';
export const EMPLOYEES = 'Empleats';
export const END_DATE = 'Data Fin';
export const ENGLISH = 'Anglès';
export const ENTERPRISE = 'Empresa';
export const ENTERPRISES = 'Empresas';
export const ENTRY = 'Entrada';
export const ENVIRONMENT = 'Entorno';
export const EQUIVALENCE_SURCHARGE = `Recàrrec d'Equivalència`;
export const ERR_EMPTY_VALUE = 'Camps sense valor';
export const ERR_LOW_CONFIDENCE = 'Camps amb poca confiança';
export const ERROR = 'Error';
export const ERRORS = 'Errors';
export const ESTIMATED_TIME = 'Temps estimat';
export const EXAMPLE = 'Exemple';
export const EXERCISE = 'Exercici';
export const EXEMPTION_CAUSE = 'Causa d\'Exempció';
export const EXIT = 'Sortida';
export const EXPAND_HIRIND = 'Ampliar Contractació';
export const EXPEDITION_DATE = 'Data d\'expedició';
export const EXPEDITION_DATE_MIN = 'D. Expedición';
export const EXPIRATION_DATE = 'Data d\'expiració';
export const EXPENSE = 'Despesa';
export const EXPENSES = 'Despeses';
export const EXPIRATIONS = 'Venciments';
export const EXPIRED = 'Caducat';
export const EXPIRED_SESSION = 'Sessió expirada';
export const EXPORTED = 'Exportades';



// ----- F

export const FAILED = 'Fallat';
export const FAX = 'Fax';
export const FILE = 'Fitxer';
export const FILE_DATA = `Dades de l'Fitxer`;
export const FILTER = 'Filtre';
export const FILTERS = 'Filtres';
export const FIND_LINKED_DOMAINS = "Buscar dominis vinculats";
export const FISCAL = 'Fiscal';
export const FISCAL_DATA = 'Dades Fiscals';
export const FOLIO = 'Foli';
export const FOOTER = 'Peu';
export const FORMALITIES = 'Tràmits';
export const FROM = 'Des';
export const FRENCH = 'Francès';
export const FUTURE = 'Molt aviat...';

// ----- G

export const GALICIAN = 'Gallec';
export const GARAGE = 'Garatge';
export const GENERAL_DATA = 'Dades Generals';
export const GENERAL_INFORMATION = 'Informació General';
export const GET_INVOICE = 'Obtenir Factura';
export const GET_INVOICES = 'Obtenir Factures';
export const GLOBAL_CONFIGURATION = 'Configuració Global';
export const GO_CONFIGURATION = 'Anar a configuració';
export const GROUP_DATA = 'Dades de el Grup';
export const GROUP_MANAGEMENT = `Gestió d'Grups`;
export const GROUP = 'Grup';
export const GROUPWARE = 'Expedients';
export const GROUPED = 'Agrupades';
export const GROUPS = 'Grups';

// ----- H

export const HEADER = 'Capçalera';
export const HELP = 'Ajuda';
export const HELP_RESULTS = 'Resultats en Ajuda';
export const HIDE_FIELDS = 'Ocultar camps';
export const HIRING = 'Contractació';
export const HIRING_DATA = 'Dades de contractació';
export const HISTORIC = "Historial";
export const HOLDER = 'Titular';
export const HOLDERS = 'Titulars';
export const HOME = 'Inici';
export const HOUR = 'Hora';
export const HOURS = "Hores";

// ----- I

export const IN_DEVELOPMENT = 'Aquesta opció està en desenvolupament...';
export const IN_PREPARATION = 'En Preparació';
export const IN_PROGRESS = 'En Progrés';
export const IN_TRASH = 'A la Paperera';
export const INACTIVE = 'Inactivo';
export const INACTIVES = 'Inactives';
export const INBOX = `Safata d'Entrada`;
export const INCLUDE_COMPANY_DATA = `Incloure Dades d'Empresa`;
export const INCLUDE_CONTACT_DATA = 'Incloure Dades de Contacte';
export const INCLUDE_LOGO = 'Incloure Logo';
export const INCLUDE_REGISTRATION_DATA = 'Incloure Dades Registrals';
export const INCOMES = 'Ingressos';
export const INFORMATION = 'Informació';
export const INFO_INCOMES = "Informació Apartat d'Ingressos";
export const INFO_EXPENSES = "Informació Apartat de Despeses";
export const INFO_PENDING = "Informació Apartat de Arracades";
export const INSCRIPTION = 'Inscripció';
export const INTERNAL = 'Intern';
export const INVENTORIES = 'Inventaris';
export const INVENTORY = 'Inventari';
export const INVEST_ASSET = 'Bé Afecte';
export const INVEST_ASSETS = 'Béns Afectes';
export const INVESTMENT = 'Inversió';
export const INVOICE = 'Factura';
export const INVOICE_CONCEPTS = 'Conceptes Factura';
export const INVOICE_CONFIGURATION = 'Configuració de Factures';
export const INVOICE_DATA = 'Dades Factura';
export const INVOICE_DOCUMENT_NUMBER = 'Número Document';
export const INVOICE_ISSUED = 'Factura Emesa';
export const INVOICE_NUMBER = 'Número Factura';
export const INVOICE_OBJECT = 'Objecte de Factura';
export const INVOICE_PRINTING = 'Impressió de Factures';
export const INVOICE_RECEIVED = 'Factura Rebuda';
export const INVOICE_ID_DESCRIPTION = 'Identificador de la Factura.';
export const INVOICE_DOMAIN_DESCRIPTION = 'Domini al qual pertany la factura.';
export const INVOICE_TYPE_DESCRIPTION = 'Tipus de la factura. emesa | rebuda | tiquet';
export const INVOICE_SERIE_DESCRIPTION = 'Sèrie de la factura. (Per a factures emeses)';
export const INVOICE_NUMBER_DESCRIPTION = 'Número de la factura. (Per a factures emeses)';
export const INVOICE_REFERENCE_DESCRIPTION = 'Referència de la factura. (Per a factures rebudes o tiquets)';
export const INVOICE_DATE_DESCRIPTION = 'Data de la factura.';
export const INVOICE_TRANSACTION_DESCRIPTION = 'Tipus de transacció de la factura. NAC | INTR | EXTR | CCM | ISP';
export const INVOICE_CATEGORY_DESCRIPTION = 'Categoria de la factura. (Compte Comptable de la factura)';
export const INVOICE_TOTAL_DESCRIPTION = 'Import total de la factura.';
export const INVOICE_SENDER_DESCRIPTION = 'Informació de l\'emissor de la factura.';
export const INVOICE_RECEIVER_DESCRIPTION = 'Informació del receptor de la factura.';
export const INVOICE_INVESTMENT_DESCRIPTION = 'Indica si és una factura d\'inversió.';
export const INVOICE_SERVICE_DESCRIPTION = 'Indica si és una factura de servei.';
export const INVOICE_WITHHOLDING_DESCRIPTION = 'Indica si la factura té retenció';
export const INVOICE_WITHHOLDING_FARMER_DESCRIPTION = 'Indica si la factura té règim especial d\'agricultura, ramaderia i pesca.';
export const INVOICE_VAT_ACCRUAL_PAYMENT_DESCRIPTION = 'Indica si la factura té règim especial de criteri de caixa.';
export const INVOICE_SURCHARGE_DESCRIPTION = 'Indica si la factura té recàrrec d\'equivalència.';
export const INVOICE_RECTIFIED_DESCRIPTION = 'Indica si és una factura rectificada.';
export const INVOICE_RECTIFIER_DESCRIPTION = 'Indica si és una factura rectificativa.';
export const INVOICE_RECTIFICATION_INVOICE_DESCRIPTION = 'Identificador de la factura rectificada o de la factura rectificativa.';
export const INVOICE_COMMENTS_DESCRIPTION = 'Comentaris de la factura';
export const INVOICE_REMARKS_DESCRIPTION = 'Observacions de la factura';
export const INVOICE_ACTIVITY_DESCRIPTION = 'Activitat de la factura.';
export const INVOICE_STATUS_DESCRIPTION = 'Estat de la factura inbox | rejected | trash | pending | scored';
export const INVOICE_TAXES_DESCRIPTION = 'Resum dels impostos de la factura';
export const INVOICE_DETAILS_DESCRIPTION = 'Detalls de la factura';
export const INVOICE_FINANCES_DESCRIPTION = 'Venciments de la factura.';
export const INVOICE_WORKPLACE_DESCRIPTION = 'Centre de Treball de la factura.';
export const INVOICED = 'Facturat';
export const INVOICES = 'Factures';
export const IRPF = 'IRPF';
export const IS_REQUIRED = 'és obligatori';
export const IS_NOT_VALID_EMAIL = 'no és un email vàlid';
export const ISSUE = 'Assumpte';
export const ISSUED = 'Emesa';
export const ISSUED_INVOICES = 'Factures Emeses';
export const ISSUEDS = 'Emeses';

// ----- J

// ----- K

// ----- L

export const LABORAL_COSTS = 'Resum Laboral';
export const LABELS = 'Etiquetes';
export const LANGUAGE = 'Idioma';
export const LAST = 'Última';
export const LAST_ACCESS = 'Últim Accés';
export const LAST_LOCATION = 'Última ubicació';
export const LAST_MODIFICATION = 'Última modificació';
export const LAST_STATUS = 'Último estat';
export const LEGAL_LITERALS = 'Literals Legals';
export const LINK = 'Vincular';
export const LINK_CLIENT = "Vincular cliente";
export const LINKED = 'Vinculat';
export const LINKED1 = 'Vinculats';
export const LINKING = "Vinculació";
export const LINK_CUSTOMER = 'Vincular Client';
export const LINK_DOMAINS = 'Vincular Dominis amb Clients';
export const LINK_DOMAIN_QUESTION = "Voleu desvincular aquest client del domini?";
export const LIST = 'Llistat';
export const LOADING = 'Carregant';
export const LOCATION = 'Ubicació';
export const LOCATIONS = 'Ubicacions';
export const LOGIN = 'Inici de sessió';
export const LOGIN_SUBTITLE = 'Introduïu les vostres credencials';

// ----- M

export const MAILBOX = 'Bústia';
export const MARKETING = 'Màrqueting';
export const MARK_ENTRY = 'Marcar Entrada';
export const MARK_EXIT = 'Marcar Sortida';
export const MANAGEMENT = 'Gestió';
export const MANUALS = 'Manuals';
export const MAXIMIZE = 'Maximitzar';
export const MENU = 'Menú';
export const MESSAGE = 'Missatge';
export const MESSENGER_SERVICE = 'Missatgeria';
export const MINIMIZE = 'Minimitzar';
export const MINS = 'Minuts';
export const MODEL = 'Model';
export const MODEL_111 = 'Model 111';
export const MODEL_111_DESCRIPTION = `Model 111. Retencions i ingressos a compte. Rendiments del treball i d'activitats econòmiques, premis i determinats guanys patrimonials i imputacions de renda. Autoliquidació.`;
export const MODEL_190 = 'Model 190';
export const MODEL_190_DESCRIPTION = `Model 190. Declaració Informativa. Retencions i ingressos a compte. Rendiments del treball i d'activitats econòmiques, premis i determinats guanys patrimonials i imputacions de rendes. Resum anual.`;
export const MODIFIED_BY = 'Modificat per';
export const MODERN = 'Modern';
export const MONTH = 'Mes';
export const MONTHLY = 'Mensual';
export const MONTHLY_VIEW = 'Vista mensual';
export const MOVE_STOCK = 'Moure Estoc';
export const MOVED_TO_TRASH = `S'ha moguda a la paperera`;
export const MSG_SENT = 'Missatge enviat';
export const MY_CLOUD = 'El meu núvol';
export const MY_DATA = 'Les Meves Dades';
export const MY_MANAGER = 'El meu Gestor';
export const MY_USER = 'Mi Usuari';
export const MAGIC_LINK = 'Enviament d´enllaç d´accés per email';

// ----- N

export const NAME = 'Nom';
export const NEW = 'Nou';
export const NEW_COMPANY = 'Nova Empresa';
export const NEW_DOCUMENT = 'Nou Document';
export const NEW_ELABORATION = 'Nova Elaboració';
export const NEW_EMPLOYEE = 'Nou Empleat';
export const NEW_EXPENSE = 'Nova Despesa';
export const NEW_INVEST_ASSET = 'Nou Bé Afecte';
export const NEW_INVOICE = 'Nova Factura';
export const NEW_ISSUED_INVOICE = 'Nova Factura Emesa';
export const NEW_PASSWORD = 'Nova Contrasenya';
export const NEW_PRODUCT = 'Nou Producte';
export const NEW_RECEIVED_INVOICE = 'Nova Factura Rebuda';
export const NEW_REQUEST = 'Nova Sol·licitud';
export const NEW_SALE = 'Nova Comanda de Venda';
export const NEW_TICKET = 'Nou Tiquet';
export const NEW_WAREHOUSE = 'Nou Magatzem';
export const NEWS = 'Notícies';
export const NEXT = 'Següent';
export const NIF = 'NIF';
export const NO_DATA = 'No hi ha dades';
export const NO_INFORMATION = 'No hi ha informació';
export const NO_LINK_CLIENT = 'Client sense vincular';
export const NO_PERIOD = 'Sense Període';
export const NO_STOCK_AVAILABLE = 'No hi ha stock disponible';
export const NO_VERIFACTU = 'No Verifactu';
export const NOT_LINKED = 'No vinculat';
export const NOT_LINKED1 = 'No vinculats';
export const NOTARY = 'Notari';
export const NOTICE = 'Notícia';
export const NOTIFICATION = 'Notificació';
export const NOTIFICATIONS = 'Notificacions';
export const NOTES = 'Notes';
export const NOTE = 'Nota';
export const NUMBER = 'Nombre';
export const NUMBER_OF_USERS = "Nombre d'usuaris";
export const NUMBER_OF_PALLETS = "Nombre de palets";


// ----- O

export const OBSERVATION = 'Observació';
export const OCR = 'OCR';
export const OFFERS = 'Pressupostos';
export const OFFICE = 'Despatx';
export const OFFICE_CATEGORIES = 'Categories del despatx';
export const ONE = 'Una';
export const ONLY_DOMAINS_WITHOUT_LINKED_CUSTOMER = "Només dominis sense client vinculat";
export const ONLY_PORTAL = 'Sol Portal';
export const OPEN = 'Obrir';
export const OPEN_MENU = 'Obrir Menú';
export const OPEN_REQUESTS = 'Sol·licituds Obertes';
export const OPENED = 'Obert';
export const OPERATION_DATE = 'Data d\'operació';
export const OPERATION_DATE_MIN = 'D. Operació';
export const OPTIONAL = "Opcional"; 
export const OPTIONS = 'Opcions';
export const OR_ACCESS = 'o ACCEDEIX';
export const OTHER_EXPENSES = 'Altres Despeses';
export const OTHER_INCOMES = 'Altres Ingressos';
export const OTHER_SERVICES = 'Altres Serveis';
export const OTHERS = 'Altres';

// ----- P

export const PACKAGE = 'Envàs';
export const PACKAGES = 'Envasos';
export const PACKAGING = 'Embalatge';
export const PARENT = 'Pare';
export const PARENT_APPS = "Aplicacions del pare";
export const PAUSE = 'Pausa';
export const PASSWORD = 'Contrasenya';
export const PAYMETHOD = 'Forma de Pagament';
export const PAYMETHODS = 'Formes de Pagament';
export const PAYROLL = "Laboral";
export const PAYSHEET = 'Nòmina';
export const PAYSHEETS = 'Nòminas';
export const PENDING = 'Pendent';
export const PENDING_CORRECTION = 'Pendent de Correcció';
export const PENDING_DECISSION = 'Pendent de Decisió';
export const PENDING_DOCUMENTS = 'Documents Pendents'
export const PENDING_DRAFTS = 'Esborranys Pendents';
export const PENDING_INVOICES = 'Factures Pendents';
export const PENDING_REVIEW = 'Pendent de Revisió';
export const PENDING_TASKS = 'Tasques Pendents';
export const PENDINGS = 'Pendentes';
export const PERCENTAGE = 'Percentatge';
export const PERIOD = 'Període';
export const PERMISSIONS = 'Permisos';
export const PERSONALIZATION = 'Personalització';
export const PERSONALIZED = 'Personalitzat';
export const PERSONALIZED_THEME = 'Tema Personalitzat';
export const PHONE = 'Teléfono';
export const PLAN = 'Plans';
export const PORTAL = 'Portal';
export const PORTAL_MENU = "Menu portal"
export const POSTAL_CODE = 'Código Postal';
export const POSTAL_CODE_MIN = 'C.P.';
export const PRESENCE = 'Presència';
export const PREVIOUS = 'Anterior';
export const PRICE = 'Preu';
export const PRINT = 'Imprimir';
export const PRINT_INVOICE = 'Imprimir Factura';
export const PRINTER = 'Impressora';
export const PRINTS = 'Impressions';
export const PROCCESSING = 'En Tràmit';
export const PROCESS = 'Tràmit';
export const PROCESS_TYPE = 'Tipus de tràmit';
export const PROCESSED = 'Processat';
export const PROCESSED_MOVEMENT = "El alta se ha procesado correctamente";
export const PROCESSED_MOVEMENT_BJ = 'La baixa s\'ha processat correctament';
export const PRODUCT = 'Producte';
export const PRODUCT_NOT_EMPTY = "El producte no pot estar buit";
export const PRODUCT_MUST_BE_SELECTED = "És obligatori seleccionar un producte";
export const PRODUCTS = 'Productes';
export const PRODUCTS_AND_SERVICES = 'Productes i Serveis';
export const PROFIT = 'Benefici';
export const PROFORMA = 'Proforma';
export const PROVINCE = 'Provincia';
export const PROFORMA_INVOICES = "Esborrany/Proforma";
export const PROGRAMMED = "Programat";
export const PROJECT = 'Projecte';
export const PROJECTS = 'Projectes';
export const PROFILES = "Perfils";
export const PROTOCOL = 'Protocol';
export const PURCHASE_PRICE = 'Preu de Cost';
// ----- Q

export const QUERY = 'Consulta';
export const QUANTITY = 'Quantitat';
export const QUARTERLY_VIEW = 'Vista trimestral';
export const QUESTION = 'Pregunta';
export const QUESTIONS = 'Preguntes';
export const QUICK_ACCESS = "Accés ràpid";
export const QUOTA = 'Quota';
export const QUOTE_GROUP = 'Grup de cotització';

// ----- R

export const RADIO = "Radio";
export const RECEIVED = 'Rebuda';
export const RECEIVED_INVOICES = "Factures Rebudes";
export const RECEIVEDS = 'Rebudes';
export const RECENTS = 'Recents';
export const RECENTLY_OPENED = "Obert recentment";
export const RECORD = 'Comptabilitzar';
export const RECORD_INVOICE = 'Comptabilitzar';
export const RECOVER_PASSWORD = 'Recuperar Contrasenya';
export const RECTIFIED = 'Rectificada';
export const RECTIFIER = 'Rectificativa';
export const RECTIFY = 'Rectificar';
export const RECTIFY_INVOICE = 'Rectificar Factura';
export const REFERENCE = 'Referència';
export const REFRESH = 'Refrescar';
export const REGIME = 'Règim';
export const REGISTER = 'Registre';
export const REGISTERED_TRADEMARK = 'Marca Registrada';
export const REGISTERED_TRADEMARK_AON = 'és una marca registrada de AON SOLUTIONS, S.L.';
export const REGISTRATION_DATA = 'Dades Registrals';
export const REGISTRATION_DATE = 'Data de Registre';
export const REJECT = 'Rebutjar';
export const REJECT_INVOICE = 'Rebutjar Factura';
export const REJECT_INVOICES = 'Rebutjar Factures';
export const REJECTED = 'Factures Rebutjada';
export const REJECTED_INVOICES = 'Factures Rebutjades';
export const REJECTEDS = 'Rebutjades';
export const REMARKS = 'Observacions';
export const REMINDER = 'Recordatori';
export const REOPEN = 'Reobrir';
export const REOPENED = 'Reobert';
export const REPEAT_PASSWORD = 'Repetir Contrasenya';
export const REPROCESS = 'Reprocessar';
export const REQUEST = 'Sol·licitud';
export const REQUEST_CLOSE_CONFIRM = 'Esteu segurs de tancar la sol·licitud?';
export const REQUEST_EMPTY_DATA = 'Sense dades noves per a la consulta';
export const REQUESTS = 'Sol·licituds';
export const REQUESTS_SENT = 'Sol·licituds Enviades';
export const REQUESTS_RECEIVED = 'Sol·licituds Rebudes';
export const RESTORE = 'Restaurar';
export const RESTORED_DATA = 'Los datos se han restaurado correctamente';
export const RESTORE_INVOICE = 'Restaurar Factura';
export const RESTORE_INVOICES = 'Restaurar Factures';
export const RESULTS = "Resultats";
export const RESUME_COSTS = 'Resum Costos';
export const RETENTION_PANEL = 'Panell d\'IRPF';
export const REVIEW = "Revisar";

// ----- S

export const SALES_PREPARATION = 'Preparació de Comandes';
export const SAVE = 'Guardar';
export const SAVED_DATA = "Los datos se han guardado correctamente";
export const SCOPE = 'Àmbit';
export const SCOPES = 'Àmbits';
export const SCHEDULE = "Horari";
export const SEARCH = 'Buscar';
export const SECTION = 'Secció';
export const SECURITY = 'Seguretat';
export const SEE_ALL = 'Veure Totes';
export const SELECT_LANGUAGE = "Selecció d'idioma";
export const SELECT_COMPANY_TYPE = "Seleccionar tipus d'empresa";
export const SEND = 'Enviar';
export const SEND_FILE = 'Enviar Fitxer';
export const SEND_FILES = 'Enviar Fitxers';
export const SEND_INVOICE = 'Enviar Factura';
export const SEND_INVOICES = 'Enviar Factures';
export const SENDER = 'Remitent';
export const SENT = 'Enviades';
export const SEPA_FILES = 'Fitxers SEPA';
export const SERIE = 'Sèrie';
export const SERVICE = 'Servei';
export const SERVICE_ACCOUNT = 'Compte de Servei';
export const SERVICE_ACCOUNTS = 'Comptes de Servei';
export const SERVICES = 'Serveis';
export const SETTING = 'Configuració';
export const SHARED = 'Compartides';
export const SHEET = 'Full';
export const SHOW_FILE = 'Mostrar Fitxer';
export const SIDE_MENU = 'Menú Lateral sempre visible';
export const SIGN_IN = 'Iniciar Sessió';
export const SIGN_IN_WITHOUT_PASSWORD = 'Sense Contrasenya';
export const SIGN_IN_WITH_CERTIFICATE = 'Iniciar Sessió amb Certificat';
export const SIGNING = 'Fitxatge';
export const SII = 'SII';
export const SII_TICKETBAI = 'SII / TicketBAI';
export const SIMPLIFIED_INVOICE = 'Factura Simplificada';
export const SIMPLIFIED_INVOICES = 'Simplificades';
export const SITUATION = 'Situació';
export const SIZE = 'Mida';
export const SIX_MONTHLY = 'Semestral';
export const SPANISH = 'Castellà';
export const STAFF_EXPENSES = 'Despeses de Personal';
export const STANDARD = 'Estàndard';
export const START_DATE = 'Data d\'inici';
export const STATISTICS = 'Estadístiques';
export const STATUS = "Estado";
export const STATUS_NOT_EMPTY = "L'estat no pot estar buit";
export const STOCK = 'Estoc';
export const STORE = 'Arxivar';
export const STREET_TYPE = 'Tipus de via';
export const SUITE_MENU = "Menu suite";
export const SUMMARIZED = 'Resumit';
export const SUPPLIED = 'Bestretes';
export const SUPPLIER = 'Proveïdor';
export const SUPPLIERS = 'Proveïdors';
export const SUPPORT = 'Suport';
export const SUPPORTING_DOCUMENTS = 'Justificants';
export const SURCHARGE = 'Recàrrec';
export const SURNAME = 'Cognoms';
export const SURVEY = 'Qüestionari';
export const SURVEYS = 'Qüestionaris';
export const SYSTEM_MESSAGES =  'Missatges de Sistema';

// ----- T

export const TAG = 'Etiqueta';
export const TAGS = 'Etiquetes';
export const TARGET = 'Client Potencial';
export const TARGETS = 'Clients Potencials';
export const TASK = 'Tasca';
export const TASKS = 'Tasques';
export const TASK_TRAY = 'Safata Tasques';
export const TAX = 'Impost';
export const TAX_BASE = 'Base Imposable';
export const TAXES = 'Impostos';
export const TAXES_DETAIL = 'Detall Impostos'
export const TEST_ENVIRONMENT = 'Entorn de Proves';
export const THEME = 'Tema';
export const THEME_SELECTION = 'Selecció del tema';
export const THREE_MONTHLY = 'Trimestral';
export const TICKET = 'Tiquet';
export const TICKETBAI = 'TicketBAI';
export const TICKETS = 'Tiquets';
export const TIMECONTROL = `Control d'Horari`;
export const TIMECTRL = 'Ctrl. Horari';
export const TITLE = 'Títol';
export const TITULAR_DATA = 'Titular Data';
export const TO = 'Fins';
export const TO_REVIEW = 'A revisar';
export const TO_SHOW = 'Mostrar';
export const TO_TRASH = 'Enviar a la Paperera';
export const TODAY = 'Avui';
export const TOMORROW = 'Matí';
export const TOOLS = 'Eines';
export const TOTAL = 'Total';
export const TOTAL_SUPPLIED = 'Total Bestretes';
export const TRAY = 'Safata';
export const TYPE_CONTRACT = 'Tipus de contracte';
export const TYPE_HERE = 'Escriviu aquí';
export const TYPE_INCIDENT = 'Tipus d\'incidència';
export const TYPE_JOB = 'Tipus de treball';
export const TYPE_REQUEST = 'Tipus sol·licitud';
export const TRANSACTION_TYPE = 'Tipus de Transacció';
export const TRASH = 'Paperera';
export const TREASURY = 'Tresoreria';
export const TYPE = 'Tipus';
export const TYPES = 'Tipues';

// ----- U


export const UNACCOUNT_INVOICES = 'Factures sense Comptabilitzar';
export const UNLINK = "Desvincular";
export const UNLINK_DOMAIN_QUESTION = "¿Desea desvincular aquest client del domini?";
export const UNLINK_CLIENT = "Desvincular client";
export const UNLINKED = "Sense vincular";
export const UPDATE = 'Actualitzar';
export const UPDATE_INVOICE = 'Actualitzar Factura';
export const UPDATED_CONTRACT = "El contrato se ha modificado correctamente";
export const UPLOAD = 'Pujar';
export const UPLOAD_FILE = 'Pujar Fitxer';
export const UPLOAD_INVOICE = 'Pujar Factura';
export const UPLOAD_DOCUMENT = 'Pujar Document';
export const UPPER_MENU = "Menú de capçalera";
export const USER = 'Usuari';
export const USER_CATEGORIES = 'Les meves categories';
export const USER_DATA = `Dades de l'Usuari`;
export const USER_MANAGEMENT = `Gestió d'Usuaris`;
export const USERS = 'Usuaris';
export const UTILITIES = 'Utilitats';

// ----- V

export const VAT = 'IVA';
export const VAT_ACCRUAL_PAYMENT = 'Criteri de Caixa';
export const VAT_PANEL = 'Panell d\'IVA';
export const VERIFIED = 'Verificat';
export const VERIFICATION = 'Verificació';
export const VERIFICATION_CODE = 'Codi Verificació';
export const VERSION = 'Versió';
export const VIEW = 'Veure';
export const VIEW_FIELDS = 'Veure camps';
export const VIEW_PAYROLL = 'Veure nòmina';
export const VIEW_PAYROLLS = 'Veure nòmines';
export const VOLUME = 'Tom';

// ----- W

export const WAREHOUSE = 'Magatzem';
export const WAREHOUSES = 'Magatzems';
export const WEB = 'Web';
export const WEEK_SCHEDULE = "Dilluns a dijous de 8:00 a 15:00";
export const WEEK_FRIDAY_SCHEDULE = "Divendres de 8:00 a 14:00";
export const WELCOME_TO_AON_SOLUTIONS = 'Us donem la benvinguda a aon Solutions'
export const WITHHOLDING = 'Retenció';
export const WITHHOLDING_FARMER = 'Règ. agri. ram. i pesca';
export const WORKGROUP = 'Grup de treball';
export const WORKPLACE = 'Centre de treball';
export const WORKSHOPS = 'Tallers';
export const WRITE_YOUR_TITLE = "Escriu el teu títol aquí";
export const WRITE_A_COMMENT =  "Escriu un comentari";
export const WRITE_A_DESCRIPTION = "Escriu una descripció";
export const WRITE_A_NOTE =  "Escriu una nota";
export const WRONG_CODE = 'Codi Erroni';
export const BLACK_AND_WHITE = 'Blanc i Negre';

// ----- X

// ----- Y

export const YEAR = 'Any';
export const YEARLY = 'Anual';
export const YESTERDAY = 'Ahir';

// ----- Z

//-------------DAYS
export const SUNDAY = "Diumenge";
export const MONDAY = "Dilluns"; 
export const TUESDAY = "Dimarts";
export const WEDNESDAY = "Dimecres";
export const THURSDAY = "Dijous"; 
export const FRIDAY = "Divendres"; 
export const SATURDAY = "Dissabte"; 

//-------------MONTHS
export const JANUARY = "Gener"; 
export const FEBRUARY = "Febrer"; 
export const MARCH = "Març"; 
export const APRIL = "Abril"; 
export const MAY = "Maig"; 
export const JUNE = "Juny"; 
export const JULY = "Juliol"; 
export const AUGUST = "Agost";
export const SEPTEMBER = "Setembre";
export const OCTOBER = "Octubre"; 
export const NOVEMBER = "Novembre"; 
export const DECEMBER = "Desembre"; 