package com.esferalia.aon.payroll.agreement;

import java.io.Serializable;

import com.esferalia.aon.watson.util.AonStringUtils;

public enum AgreementPayment implements Serializable {

	// ------------------------- SALARIO BASE
	
	SALARIO_CONVENIO_ANUAL("SALARIO_CONVENIO_ANUAL", "[01] SALARIO BASE ANUAL", "SALARIO_BASE", "/*read-only*/SALARIO_ANUAL/**/ / PAGAS * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	SALARIO_CONVENIO_ANUAL_ANUAL("SALARIO_CONVENIO_ANUAL_ANUAL", "[01] SALARIO BASE ANUAL", "SALARIO_BASE", "/*read-only*/SALARIO_ANUAL/**/ / PAGAS * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	SALARIO_BASE_ANUAL("SALARIO_BASE_ANUAL", "[01] SALARIO BASE ANUAL", "SALARIO_BASE", "/*read-only*/SALARIO_ANUAL/**/ / PAGAS * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	SALARIO_BASE_ANUAL_ANUAL("SALARIO_BASE_ANUAL_ANUAL", "[01] SALARIO BASE ANUAL", "SALARIO_BASE", "/*read-only*/SALARIO_ANUAL/**/ / PAGAS * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	
	SALARIO_CONVENIO_MENSUAL("SALARIO_CONVENIO_MENSUAL", "[02] SALARIO BASE MENSUAL", "SALARIO_BASE", "/*read-only*/SALARIO_MENSUAL/**/ * DIAS_TRABAJADOS / DIAS_MES ", (byte)1),
	SALARIO_BASE_MENSUAL("SALARIO_BASE_MENSUAL", "[02] SALARIO BASE MENSUAL", "SALARIO_BASE", "/*read-only*/SALARIO_MENSUAL/**/ * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	
	SALARIO_CONVENIO_HORAS("SALARIO_CONVENIO_HORAS", "[04] SALARIO BASE HORAS", "SALARIO_BASE", "(SALARIO_HORA=/*read-only*/SALARIO_HORA/**/) * HORAS_TRABAJADAS", (byte)1),
	SALARIO_HORA_HORAS("SALARIO_HORA_HORAS", "[04] SALARIO BASE HORAS", "SALARIO_BASE", "(SALARIO_HORA=/*read-only*/SALARIO_HORA/**/) * HORAS_TRABAJADAS", (byte)1),
	SALARIO_BASE_HORAS("SALARIO_BASE_HORAS", "[04] SALARIO BASE HORAS", "SALARIO_BASE", "(SALARIO_HORA=/*read-only*/SALARIO_HORA/**/) * HORAS_TRABAJADAS", (byte)1),
	
	SALARIO_CONVENIO_DIARIO("SALARIO_CONVENIO_DIARIO", "[03] SALARIO BASE DIARIO", "SALARIO_BASE", "/*read-only*/SALARIO_ANUAL/**/ * HORAS_TRABAJADAS", (byte)1),
	SALARIO_BASE_DIARIO("SALARIO_BASE_DIARIO", "[03] SALARIO BASE DIARIO", "SALARIO_BASE", "(SALARIO_DIARIO=/*read-only*/SALARIO_DIARIO/**/) * DIAS_TRABAJADOS", (byte)1),

	SALARIO_BASE_MINIMO_ANUAL("SALARIO_BASE_MINIMO_ANUAL", "[06] SALARIO BASE MINIMO SMI", "SALARIO_BASE", "MAX(SMI*DIAS_TRABAJADOS/DIAS_MES, (PORC_SALARIO=SI(AÑOS_ANTIGUEDAD<2, SI (AÑOS_ANTIGUEDAD<1, 70 ,80) ,100))* /*user*/SALARIO_PRACTICAS/**/ /100*DIAS_TRABAJADOS/DIAS_MES)", (byte)1),

	// ------------------------- PLUS CONVENIO
	
	PLUS_CONVENIO_ANUAL("PLUS_CONVENIO_ANUAL", "[10] PLUS CONVENIO ANUAL", "PLUS_CONVENIO", "PLUS_CONVENIO_ANUAL/PAGAS", (byte)1),
	
	PLUS_CONVENIO_MENSUAL("PLUS_CONVENIO_MENSUAL", "[10] PLUS CONVENIO MENSUAL", "PLUS_CONVENIO", "(/*user*/ PLUS_CONVENIO/**/) * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	COMPLEMENTO_CONVENIO_MENSUAL("COMPLEMENTO_CONVENIO_MENSUAL", "[02] PLUS CONVENIO MENSUAL", "PLUS_CONVENIO", "PLUS_CONVENIO_MENSUAL * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PLUS_MANUTENCION_NO_OBLIGATORIA_MENSUAL("PLUS_MANUTENCION_NO_OBLIGATORIA_MENSUAL", "[10] PLUS MANUTENCION NO OBLIGATORIA MENSUAL", "P_MANUTENCION_NO_OBL_M", "(/*user*/ P_MANUTENCION_NO_OBL_M/**/) * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PLUS_MANUTENCION_MENSUAL("PLUS_MANUTENCION_MENSUAL", "[10] PLUS MANUTENCION MENSUAL", "P_MANUTENCION_M", "(/*user*/ P_MANUTENCION_M/**/) * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	
	PLUS_CONVENIO_HORAS("PLUS_CONVENIO_HORAS", "[02] PLUS CONVENIO HORAS", "PLUS_CONVENIO", "(SALARIO_DIARIO=/*read-only*/PLUS_CONVENIO_HORAS/**/) * HORAS_TRABAJADAS", (byte)1),
	
	COMPLEMENTO_CONVENIO_DIARIO("COMPLEMENTO_CONVENIO_DIARIO", "[02] PLUS CONVENIO DIARIO", "PLUS_CONVENIO_DIARIO", "PLUS_CONVENIO_DIARIO * DIAS_TRABAJADOS", (byte)1),
	PLUS_CONVENIO_DIARIO("PLUS_CONVENIO_DIARIO", "[02] PLUS CONVENIO DIARIO", "PLUS_CONVENIO", "PLUS_CONVENIO_DIARIO * DIAS_TRABAJADOS", (byte)1),
	
	// ------------------------- OTROS PLUS CONVENIO
	
	PLUS_SALARIAL_DIARIO("PLUS_SALARIAL_DIARIO", "[11] PLUS SALARIAL DIARIO", "PLUS_DIARIO", "(/*user*/PLUS_DIARIO/**/) * DIAS_TRABAJADOS", (byte)1),
	PLUS_SALARIAL_LABORAL_DIARIO("PLUS_SALARIAL_LABORAL_DIARIO", "[12] PLUS SALARIAL DIARIO LABORABLES", "PLUS_LABORABLES", "(/*user*/PLUS_LABORABLES/**/) * DIAS_EFECTIVOS", (byte)1),
	PLUS_SALARIAL_FIJO_MENSUAL("PLUS_SALARIAL_FIJO_MENSUAL", "[13] PLUS SALARIAL FIJO", "PLUS_FIJO", "FRACCIONAR(/*user*/PLUS_FIJO/**/)", (byte)1),
	
	PLUS_EXTRA_CATEGORIA_ANUAL("PLUS_EXTRA_CATEGORIA_ANUAL", "[03] PLUS EXTRA CATEGORIA ANUAL", "PLUS_EXTRA_CATEGORIA_A", "PLUS_EXTRA_CATEGORIA_A / PAGAS * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	
	PLUS_HERRAMIENTAS_ANUAL("PLUS_HERRAMIENTAS_ANUAL", "[03] PLUS HERRAMIENTAS ANUAL", "PLUS_HERRAMIENTAS_A", "PLUS_HERRAMIENTAS_A / PAGAS * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PLUS_HERRAMIENTAS_DIARIO("PLUS_HERRAMIENTAS_DIARIO", "[03] PLUS HERRAMIENTAS DIARIO", "PLUS_HERRAMIENTAS_D", "PLUS_HERRAMIENTAS_D * DIAS_TRABAJADOS", (byte)1),
	
	PLUS_ACTIVIDAD_MENSUAL("PLUS_ACTIVIDAD_MENSUAL", "[03] PLUS ACTIVIDAD MENSUAL", "PLUS_ACTIVIDAD_MENSUAL", "PLUS_ACTIVIDAD_MENSUAL * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PLUS_ACTIVIDAD_DIARIO("PLUS_ACTIVIDAD_DIARIO", "[03] PLUS ACTIVIDAD DIARIO", "PLUS_ACTIVIDAD_DIARIO", "PLUS_ACTIVIDAD_DIARIO * DIAS_TRABAJADOS", (byte)1),
	
	PLUS_EXTRA_SALARIAL_MENSUAL("PLUS_EXTRA_SALARIAL_MENSUAL", "[20] PLUS EXTRA SALARIAL MENSUAL", "PLUS_XS_MENSUAL", "(/*user*/PLUS_XS_MENSUAL/**/) * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PLUS_EXTRA_SALARIAL_DIARIO("PLUS_EXTRA_SALARIAL_DIARIO", "[21] PLUS EXTRA SALARIAL DIARIO", "PLUS_XS_DIARIO", "(/*user*/PLUS_XS_DIARIO/**/) * DIAS_TRABAJADOS", (byte)1),
	PLUS_EXTRA_SALARIAL_LABORAL_DIARIO("PLUS_EXTRA_SALARIAL_LABORAL_DIARIO", "[22] PLUS EXTRASALARIAL DIARIO LABORABLES", "PLUS_XS_LABORABLES", "(/*user*/PLUS_XS_LABORABLES/**/) * DIAS_EFECTIVOS", (byte)1),
	PLUS_EXTRA_SALARIAL_FIJO_MENSUAL("PLUS_EXTRA_SALARIAL_FIJO_MENSUAL", "[23] PLUS EXTRASALARIAL FIJO", "PLUS_XS_FIJO", "FRACCIONAR(/*user*/PLUS_XS_FIJO/**/)", (byte)1),
	
	PLUS_VESTUARIO_MENSUAL("PLUS_VESTUARIO_MENSUAL", "[03] PLUS VESTUARIO MENSUAL", "PLUS_VESTUARIO", "PLUS_VESTUARIO * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	
	PLUS_ROTACION_MENSUAL("PLUS_ROTACION_MENSUAL", "[03] PLUS ROTACION MENSUAL", "PLUS_ROTACION", "PLUS_ROTACION * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	
	PLUS_DISTANCIA_MENSUAL("PLUS_DISTANCIA_MENSUAL", "[03] PLUS DISTANCIA MENSUAL", "PLUS_DISTANCIA_M", "PLUS_DISTANCIA_M * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PLUS_DISTANCIA_HORAS("PLUS_DISTANCIA_HORAS", "[03] PLUS DISTANCIA HORAS", "PLUS_DISTANCIA_H", "PLUS_DISTANCIA_H * HORAS_TRABAJADAS", (byte)1),
	PLUS_DISTANCIA_DIARIO("PLUS_DISTANCIA_DIARIO", "[03] PLUS DISTANCIA DIARIO", "PLUS_DISTANCIA_D", "PLUS_DISTANCIA_D * DIAS_TRABAJADOS", (byte)1),
	
	PLUS_URGENCIA_MENSUAL("PLUS_URGENCIA_MENSUAL", "[03] PLUS URGENCIA MENSUAL", "PLUS_URGENCIA", "PLUS_URGENCIA * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	
	PLUS_ASISTENCIA_ANUAL("PLUS_ASISTENCIA_ANUAL", "[03] PLUS ASISTENCIA ANUAL", "PLUS_ASISTENCIA", "PLUS_ASISTENCIA / PAGAS * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PLUS_ASISTENCIA_MENSUAL("PLUS_ASISTENCIA_MENSUAL", "[03] PLUS ASISTENCIA MENSUAL", "PLUS_ASISTENCIA", "PLUS_ASISTENCIA * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PLUS_ASISTENCIA_DIARIO("PLUS_ASISTENCIA_DIARIO", "[03] PLUS ASISTENCIA DIARIO", "PLUS_ASISTENCIA", "PLUS_ASISTENCIA * DIAS_TRABAJADOS", (byte)1),
	
	PLUS_TRANSPORTE_MENSUAL("PLUS_TRANSPORTE_MENSUAL", "[03] PLUS TRANSPORTE MENSUAL", "PLUS_TRANSPORTE_MEN", "PLUS_TRANSPORTE_MEN * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PLUS_TRANSPORTE_DIARIO("PLUS_TRANSPORTE_DIARIO", "[03] PLUS TRANSPORTE DIARIO", "PLUS_TRANSPORTE_DIA", "PLUS_TRANSPORTE_DIA * DIAS_TRABAJADOS", (byte)1),
	
	PLUS_CARENCIA_DE_INCENTIVOS_MENSUAL("PLUS_CARENCIA_DE_INCENTIVOS_MENSUAL", "[03] PLUS CARENCIA DE INCENTIVOS MENSUAL", "PLUS_CARENCIA_INCENT_M", "PLUS_CARENCIA_INCENT_M * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	
	PLUS_RIESGO_DIARIO("PLUS_RIESGO_DIARIO", "[03] PLUS RIESGO DIARIO", "PLUS_RIESGO", "PLUS_RIESGO * DIAS_TRABAJADOS", (byte)1),
	
	PLUS_FESTIVOS_DIARIO("PLUS_FESTIVOS_DIARIO", "[03] PLUS FESTIVO DIARIO", "PLUS_FESTIVO", "PLUS_FESTIVO * DIAS_TRABAJADOS", (byte)1),
	PLUS_FESTIVOS_ESPECIALES_DIARIO("PLUS_FESTIVOS_ESPECIALES_DIARIO", "[03] PLUS FESTIVO ESPECIALES DIARIO", "PLUS_FESTIVO_ESP", "PLUS_FESTIVO_ESP * DIAS_TRABAJADOS", (byte)1),
	
	PLUS_DOMINGOS_Y_FESTIVOS_DIARIO("PLUS_DOMINGOS_Y_FESTIVOS_DIARIO", "[03] PLUS DOMINGOS Y FESTIVOS", "PLUS_FINDES", "PLUS_FINDES * DIAS_TRABAJADOS", (byte)1),
	
	PLUS_DIA_NAVIDAD_Y_AÑO_NUEVO_DIARIO("PLUS_DIA_NAVIDAD_Y_AÑO_NUEVO_DIARIO", "[03] PLUS DIA NAVIDAD Y AÑO NUEVO", "PLUS_NAVIDAD_AÑO_NUEVO", "PLUS_NAVIDAD_AÑO_NUEVO * DIAS_TRABAJADOS", (byte)1),
	
	PLUS_PENOSIDAD_1_CIRCUNSTANCIA_DIARIO("PLUS_PENOSIDAD_1_CIRCUNSTANCIA_DIARIO", "[03] PLUS_PENOSIDAD 1 CIRCUNSTANCIA DIARIO", "PLUS_PENOSIDAD_1", "PLUS_PENOSIDAD_1 * DIAS_TRABAJADOS", (byte)1),
	PLUS_PENOSIDAD_2_CIRCUNSTANCIAS_DIARIO("PLUS_PENOSIDAD_2_CIRCUNSTANCIAS_DIARIO", "[03] PLUS_PENOSIDAD 2 CIRCUNSTANCIAS DIARIO", "PLUS_PENOSIDAD_2", "PLUS_PENOSIDAD_2 * DIAS_TRABAJADOS", (byte)1),
	
	PLUS_TOXICIDAD_MENSUAL("PLUS_TOXICIDAD_MENSUAL", "[03] PLUS TOXICIDAD", "PLUS_TOXICIDAD", "PLUS_TOXICIDAD * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PLUS_TOXICIDAD_DIARIO("PLUS_TOXICIDAD_DIARIO", "[03] PLUS TOXICIDAD", "PLUS_TOXICIDAD", "PLUS_TOXICIDAD * DIAS_TRABAJADOS", (byte)1),
	
	PLUS_ACERCAMIENTO_ANUAL("PLUS_ACERCAMIENTO_ANUAL", "[03] PLUS ACERCAMIENTO ANUAL", "PLUS_ACERCAMIENTO_ANUAL", "PLUS_ACERCAMIENTO_ANUAL / PAGAS * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	
	COMPLEMENTO_LINEAL_ANUAL("COMPLEMENTO_LINEAL_ANUAL", "[03] COMPLEMENTO LINEAL ANUAL", "COMPL_LINEAL_A", "COMPL_LINEAL_A / PAGAS * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	
	COMPLEMENTO_NACIMIENTO_O_ADOPCION_DE_HIJO_ANUAL("COMPLEMENTO_NACIMIENTO_O_ADOPCION_DE_HIJO_ANUAL", "[03] COMPLEMENTO NACIMIENTO O ADOPCION DE HIJO", "COMPL_NAC_ADOP_HIJO", "COMPL_NAC_ADOP_HIJO / PAGAS * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	
	COMPLEMENTO_ESPECIFICO_MENSUAL("COMPLEMENTO_ESPECIFICO_MENSUAL", "[03] COMPLEMENTO ESPECIFICO MENSUAL", "COMPL_ESPECIFICO_MEN", "COMPL_ESPECIFICO_MEN * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	
	SEGURO_COMPLEMENTARIO_ANUAL("SEGURO_COMPLEMENTARIO_ANUAL", "[03] SEGURO COMPLEMENTARIO ANUAL", "SEGURO_COMPLEMENT_A", "SEGURO_COMPLEMENT_A / PAGAS * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	FIDELIZACION_POR_EXTINCION_DE_CONTRATO_ANUAL("FIDELIZACION_POR_EXTINCION_DE_CONTRATO_ANUAL", "[03] FIDELIZACION EXTINCION CONTRATO ANUAL", "FID_EXTIN_CONTRATO_A", "FID_EXTIN_CONTRATO_A / PAGAS * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	
	COMPLEMENTO_NO_SALARIAL_ANUAL("COMPLEMENTO_NO_SALARIAL_ANUAL", "[03] COMPLEMENTO NO SALARIAL ANUAL", "COMPL_NO_SALARIAL_ANUAL", "COMPLEMENTO_NO_SALARIAL_ANUAL / PAGAS * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	COMPLEMENTO_NO_SALARIAL_MENSUAL("COMPLEMENTO_NO_SALARIAL_MENSUAL", "[03] COMPLEMENTO NO SALARIAL MENSUAL", "COMPL_NO_SALARIAL_MEN", "COMPL_NO_SALARIAL_MEN * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	COMPLEMENTO_NO_SALARIAL_DIARIO("COMPLEMENTO_NO_SALARIAL_DIARIO", "[03] COMPLEMENTO NO SALARIAL DIARIO", "COMPL_NO_SALARIAL_DIA", "COMPL_NO_SALARIAL_DIA * DIAS_TRABAJADOS", (byte)1),
	
	COMPLEMENTO_PERSONAL_REPARTO_HORAS("COMPLEMENTO_PERSONAL_REPARTO_HORAS", "[03] COMPLEMENTO PERSONAL REPARTO HORAS", "COMPL_PER_REPARTO_H", "COMPL_PER_REPARTO_H * HORAS_TRABAJADAS", (byte)1),
	
	PLUS_FESTIVO_NOCTURNO_DIARIO("PLUS_FESTIVO_NOCTURNO_DIARIO", "[03] PLUS FESTIVO NOCTURNO DIARIO", "P_FESTIVO_NOCT_D", "P_FESTIVO_NOCT_D * DIAS_TRABAJADOS", (byte)1),
	
	PLUS_PUNTUALIDAD_MENSUAL("PLUS_PUNTUALIDAD_MENSUAL", "[03] PLUS PUNTUALIDAD MENSUAL", "PLUS_PUNTUALIDAD_M", "PLUS_PUNTUALIDAD_M * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	
	PLUS_IDIOMAS_MENSUAL("PLUS_IDIOMAS_MENSUAL", "[03] PLUS IDIOMAS MENSUAL", "PLUS_IDIOMAS_M", "PLUS_IDIOMAS_M * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	
	PLUS_NOCTURNIDAD_MENSUAL("PLUS_NOCTURNIDAD_MENSUAL", "[03] PLUS NOCTURNIDAD MENSUAL", "PLUS_NOCTURNIDAD_M", "PLUS_NOCTURNIDAD_M * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PLUS_NOCTURNIDAD_HORAS("PLUS_NOCTURNIDAD_HORAS", "[03] PLUS NOCTURNIDAD HORAS", "PLUS_NOCTURNIDAD_H", "PLUS_NOCTURNIDAD_H * HORAS_TRABAJADAS", (byte)1),
	PLUS_DE_LAVADO_HORAS("PLUS_DE_LAVADO_HORAS", "[03] PLUS DE LAVADO HORAS", "PLUS_LAVADO_H", "PLUS_LAVADO_H * HORAS_TRABAJADAS", (byte)1),
	PLUS_DESPLAZAMIENTOS_HORAS("PLUS_DESPLAZAMIENTOS_HORAS", "[03] PLUS DESPLAZAMIENTOS HORAS", "PLUS_DESPLAZAMIENTOS_H", "PLUS_DESPLAZAMIENTOS_H * HORAS_TRABAJADAS", (byte)1),
	PLUS_HOSPITAL_HORAS("PLUS_HOSPITAL_HORAS", "[03] PLUS HOSPITAL HORAS", "PLUS_HOSPITAL_H", "PLUS_HOSPITAL_H * HORAS_TRABAJADAS", (byte)1),
	PLUS_CENTRO_DE_SALUD_HORAS("PLUS_CENTRO_DE_SALUD_HORAS", "[03] PLUS CENTRO DE SALUD HORAS", "PLUS_CENT_SALUD_H", "PLUS_CENT_SALUD_H * HORAS_TRABAJADAS", (byte)1),
	PLUS_GERIATRICO_HORAS("PLUS_GERIATRICO_HORAS", "[03] PLUS GERIATRICO HORAS", "PLUS_GERIATRICO_H", "PLUS_GERIATRICO_H * HORAS_TRABAJADAS", (byte)1),
	PLUS_DISPONIBILIDAD_HORAS("PLUS_DISPONIBILIDAD_HORAS", "[03] PLUS DISPONIBILIDAD HORAS", "PLUS_DISPONIBILIDAD_H", "PLUS_DISPONIBILIDAD_H * HORAS_TRABAJADAS", (byte)1),
	
	// ------------------------- PAGAS EXTRAS
	
	PAGAS_EXTRA_VERANO_Y_NAVIDAD_ANUAL("PAGAS_EXTRA_VERANO_Y_NAVIDAD_ANUAL", "[03] PAGAS EXTRA VERANO Y NAVIDAD ANUAL", "P_E_VERANO_Y_NAVIDAD_A", "P_E_VERANO_Y_NAVIDAD_A / PAGAS * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	
	PAGAS_EXTRA_VERANO_Y_NAVIDAD_MENSUAL("PAGAS_EXTRA_VERANO_Y_NAVIDAD_MENSUAL", "[03] PAGAS EXTRA VERANO Y NAVIDAD MENSUAL", "P_E_VERANO_Y_NAVIDAD_M", "P_E_VERANO_Y_NAVIDAD_M * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PAGA_EXTRA_VERANO_MENSUAL("PAGA_EXTRA_VERANO_MENSUAL", "[03] PAGAS EXTRA VERANO MENSUAL", "P_E_VERANO_M", "P_E_VERANO_M * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PAGA_EXTRA_NAVIDAD_MENSUAL("PAGA_EXTRA_NAVIDAD_MENSUAL", "[03] PAGAS EXTRA NAVIDAD MENSUAL", "P_E_NAVIDAD_M", "P_E_NAVIDAD_M * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PAGA_EXTRA_SIN_ANTIGUEDAD_MENSUAL("PAGA_EXTRA_SIN_ANTIGUEDAD_MENSUAL", "[03] PAGA EXTRA SIN ANTIGUEDAD MENSUAL", "P_EXTRA_SIN_ANTIGUEDAD_M", "P_EXTRA_SIN_ANTIGUEDAD_M * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PAGA_EXTRA_MARZO_MENSUAL("PAGA_EXTRA_MARZO_MENSUAL", "[03] PAGA EXTRA MARZO MENSUAL", "PAGA_EXTRA_MARZO", "PAGA_EXTRA_MARZO * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	
	// ------------------------- HORAS Y HORAS EXTRAS
	
	HORA_ORDINARIA_HORAS("HORA_ORDINARIA_HORAS", "[04] HORAS ORDINARIAS", "HORA_ORDINARIA", "HORA_ORDINARIA * HORAS_ORDINARIAS", (byte)2),
	HORA_EXTRA_HORAS("HORA_EXTRA_HORAS", "[04] HORAS EXTRAS", "HORA_EXTRA", "HORA_EXTRA * HORAS_EXTRAS", (byte)2),
	HORA_EXTRA_DOMINGOS_Y_FESTIVOS_HORAS("HORA_EXTRA_DOMINGOS_Y_FESTIVOS_HORAS", "[04] HORAS EXTRAS DOMINGOS Y FESTIVOS", "HORAS_EXTRAS_F", "HORAS_EXTRAS_F * H_E_FINDE_FESTIVOS", (byte)2),
	HORA_EXTRA_NOCTURNA_HORAS("HORA_EXTRA_NOCTURNA_HORAS", "[04] HORAS EXTRAS NOCTURNAS", "HORAS_EXTRAS_NOC", "HORAS_EXTRAS_NOC * HORAS_EXTRAS_NOCTURNAS", (byte)2),
	HORA_EXTRA_SIN_ANTIGUEDAD_HORAS("HORA_EXTRA_SIN_ANTIGUEDAD_HORAS", "[03] PAGA EXTRA SIN ANTIGUEDAD HORAS", "P_EXTRA_SIN_ANTIGUEDAD_H", "P_EXTRA_SIN_ANTIGUEDAD_H * HORAS_TRABAJADAS", (byte)1),
	HORA_EXTRA_SIN_ANTIGUEDAD_MENSUAL("HORA_EXTRA_SIN_ANTIGUEDAD_MENSUAL", "[03] PAGA EXTRA SIN ANTIGUEDAD HORAS", "P_EXTRA_SIN_ANTIGUEDAD_M", "P_EXTRA_SIN_ANTIGUEDAD_M * HORAS_TRABAJADAS", (byte)1),
	
	ANTIGUEDAD_1_TRIENIO_MENSUAL("ANTIGUEDAD_1_TRIENIO_MENSUAL", "[04] ANTIGUEDAD 1 TRIENIO", "ANTIGUEDAD_1_TRIENIO", "ANTIGUEDAD_1_TRIENIO * HORAS_TRABAJADAS", (byte)2),
	
	HORA_EXTRA_1_QUINQUENIO_HORAS("HORA_EXTRA_1_QUINQUENIO_HORAS", "[04] HORA EXTRA 1 QUINQUENIO", "H_E_1_QUINQUENIO", "H_E_1_QUINQUENIO * HORAS_1_QUINQUENIO", (byte)2),
	HORA_EXTRA_2_QUINQUENIO_HORAS("HORA_EXTRA_2_QUINQUENIO_HORAS", "[04] HORA EXTRA 2 QUINQUENIO", "H_E_2_QUINQUENIO", "H_E_2_QUINQUENIO * HORAS_2_QUINQUENIO", (byte)2),
	HORA_EXTRA_3_QUINQUENIO_HORAS("HORA_EXTRA_3_QUINQUENIO_HORAS", "[04] HORA EXTRA 3 QUINQUENIO", "H_E_3_QUINQUENIO", "H_E_3_QUINQUENIO * HORAS_3_QUINQUENIO", (byte)2),
	HORA_EXTRA_4_QUINQUENIO_HORAS("HORA_EXTRA_4_QUINQUENIO_HORAS", "[04] HORA EXTRA 4 QUINQUENIO", "H_E_4_QUINQUENIO", "H_E_4_QUINQUENIO * HORAS_4_QUINQUENIO", (byte)2),
	
	HORA_EXTRA_ANTIGUEDAD_2_AÑOS_MENSUAL("HORA_EXTRA_ANTIGUEDAD_2_AÑOS_MENSUAL", "[04] HORA EXTRA ANTIGUEDAD 2 AÑOS", "H_E_ANTIGUEDAD_2", "H_E_ANTIGUEDAD_2 * DIAS_TRABAJADOS / DIAS_MES", (byte)2),
	HORA_EXTRA_ANTIGUEDAD_4_AÑOS_MENSUAL("HORA_EXTRA_ANTIGUEDAD_4_AÑOS_MENSUAL", "[04] HORA EXTRA ANTIGUEDAD 4 AÑOS", "H_E_ANTIGUEDAD_4", "H_E_ANTIGUEDAD_4 * DIAS_TRABAJADOS / DIAS_MES", (byte)2),
	HORA_EXTRA_ANTIGUEDAD_9_AÑOS_MENSUAL("HORA_EXTRA_ANTIGUEDAD_9_AÑOS_MENSUAL", "[04] HORA EXTRA ANTIGUEDAD 9 AÑOS", "H_E_ANTIGUEDAD_9", "H_E_ANTIGUEDAD_9 * DIAS_TRABAJADOS / DIAS_MES", (byte)2),
	HORA_EXTRA_ANTIGUEDAD_14_AÑOS_MENSUAL("HORA_EXTRA_ANTIGUEDAD_14_AÑOS_MENSUAL", "[04] HORA EXTRA ANTIGUEDAD 14 AÑOS", "H_E_ANTIGUEDAD_14", "H_E_ANTIGUEDAD_14 * DIAS_TRABAJADOS / DIAS_MES", (byte)2),
	HORA_EXTRA_ANTIGUEDAD_19_AÑOS_MENSUAL("HORA_EXTRA_ANTIGUEDAD_19_AÑOS_MENSUAL", "[04] HORA EXTRA ANTIGUEDAD 19 AÑOS", "H_E_ANTIGUEDAD_19", "H_E_ANTIGUEDAD_19 * DIAS_TRABAJADOS / DIAS_MES", (byte)2),
	HORA_EXTRA_ANTIGUEDAD_24_AÑOS_MENSUAL("HORA_EXTRA_ANTIGUEDAD_24_AÑOS_MENSUAL", "[04] HORA EXTRA ANTIGUEDAD 24 AÑOS", "H_E_ANTIGUEDAD_24", "H_E_ANTIGUEDAD_24 * DIAS_TRABAJADOS / DIAS_MES", (byte)2),
	HORA_EXTRA_ANTIGUEDAD_29_AÑOS_MENSUAL("HORA_EXTRA_ANTIGUEDAD_29_AÑOS_MENSUAL", "[04] HORA EXTRA ANTIGUEDAD 29 AÑOS", "H_E_ANTIGUEDAD_29", "H_E_ANTIGUEDAD_29 * DIAS_TRABAJADOS / DIAS_MES", (byte)2),
	
	HORA_EXTRA_DIARIO("HORA_EXTRA_DIARIO", "[04] HORAS EXTRAS DIARIO", "HORA_EXTRA_D", "HORA_EXTRA_D * DIAS_HORAS_EXTRAS", (byte)2),
	
	HORA_NOCTURNA_DISPONIBLE_HORAS("HORA_NOCTURNA_DISPONIBLE_HORAS", "[04] HORA NOCTURNA DISPONIBLE HORAS", "HORA_NOCTURNA_DISP_H", "HORA_NOCTURNA_DISP_H * HORAS_HORA_REGULARIZACION", (byte)2),
	
	HORA_REGULARIZACION_HORAS("HORA_REGULARIZACION_HORAS", "[04] HORA REGULARIZACION", "HORA_REGULARIZACION", "HORA_REGULARIZACION * HORAS_HORA_REGULARIZACION", (byte)2),
	
	HORA_BOLSA_HORARIA_HORAS("HORA_BOLSA_HORARIA_HORAS", "[04] HORA BOLSA HORARIA", "HORA_BOLSA_HORARIA", "HORA_BOLSA_HORARIA * HORAS_HORA_BOLSA_HORARIA", (byte)2),
	
	// ------------------------- VACACIONES
	
	VACACIONES_ANUAL("VACACIONES_ANUAL", "[05] VACACIONES ANUAL", "VACACIONES_ANUAL", "VACACIONES_ANUAL / PAGAS * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	VACACIONES_MENSUAL("VACACIONES_MENSUAL", "[05] VACACIONES MENSUAL", "VACACIONES_MENSUAL", "VACACIONES_MENSUAL * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	
	// ------------------------- DIETAS
	
	DIETA_ALOJAMIENTO_MENSUAL("DIETA_ALOJAMIENTO_MENSUAL", "[06] DIETA ALOJAMIENTO MENSUAL", "DIETA_ALOJAMIENTO_M", "DIETA_ALOJAMIENTO_M *  * DIAS_TRABAJADOS / DIAS_MES", (byte)43),
	
	GASTOS_PECNORTA_DIARIO("GASTOS_PECNORTA_DIARIO", "[43] GASTOS PERNOCTA DIARIO", "IMPORTE_PERNOCTA", "/*read-only*/IMPORTE_PERNOCTA * DIAS_PERNOCTA/**/", (byte)43),
	GASTOS_MANUTENCION_DIARIO("GASTOS_MANUTENCION_DIARIO", "[45] GASTOS MANUTENCION DIARIO", "IMPORTE_MANUTENCION", "/*read-only*/IMPORTE_MANUTENCION * DIAS_MANUTENCION/**/", (byte)45),
	GASTOS_LOCOMOCION_SIN_JUSTIFICANTE_DIARIO("GASTOS_LOCOMOCION_SIN_JUSTIFICANTE_DIARIO", "[50] GASTOS LOCOMOCIÓN SIN JUSTIFICANTE", "IMPORTE_KM", "/*read-only*/IMPORTE_KM * KMS/**/", (byte)50),
	
	DIETA_COMPLETA_DIARIO("DIETA_COMPLETA_DIARIO", "[06] DIETA_COMPLETA", "DIETA_COMPLETA", "DIETA_COMPLETA * DIAS_DIETA_COMPLETA", (byte)43),
	DIETA_COMPLETA_DESPL_MAS_100KMS_DIARIO("DIETA_COMPLETA_DESPL_MAS_100KMS_DIARIO", "[06] DIETA_COMPLETA > 100 KMS", "DIETA_COMPLETA_G_100", "DIETA_COMPLETA_G_100 * DIAS_DIETA_COMPLETA_G_100", (byte)43),
	DIETA_COMPLETA_DESPL_MENOS_100KMS_DIARIO("DIETA_COMPLETA_DESPL_MENOS_100KMS_DIARIO", "[06] DIETA_COMPLETA < 100 KMS", "DIETA_COMPLETA_L_100", "DIETA_COMPLETA_L_100 * DIAS_DIETA_COMPLETA_L_100", (byte)43),
	DIETA_PERNOCTA_DIARIO("DIETA_PERNOCTA_DIARIO", "[06] DIETA PERNOCTA", "DIETA_PERNOCTA", "DIETA_PERNOCTA * DIAS_DIETA_COMPLETA_PEC", (byte)43),
	DIETAS_DIARIO("DIETAS_DIARIO", "[06] DIETA DIARIO", "DIETA", "DIETA * DIAS_DIETA", (byte)43),
	DIETA_COMIDA_DIARIO("DIETA_COMIDA_DIARIO", "[06] DIETA COMIDA", "DIETA_COMIDA", "DIETA_COMIDA * DIAS_DIETA_COMIDA", (byte)43),
	
	MEDIA_DIETA_DIARIO("MEDIA_DIETA_DIARIO", "[06] MEDIA_DIETA", "MEDIA_DIETA", "MEDIA_DIETA * DIAS_MEDIA_DIETA", (byte)43),
	MEDIA_DIETA_DESPL_MAS_100KMS_DIARIO("MEDIA_DIETA_DESPL_MAS_100KMS_DIARIO", "[06] MEDIA_DIETA > 100 KMS", "MEDIA_DIETA_G_100", "MEDIA_DIETA_G_100 * DIAS_MEDIA_DIETA_G_100", (byte)43),
	MEDIA_DIETA_DESPL_MENOS_100KMS_DIARIO("MEDIA_DIETA_DESPL_MENOS_100KMS_DIARIO", "[06] MEDIA_DIETA < 100 KMS", "MEDIA_DIETA_L_100", "MEDIA_DIETA_L_100 * DIAS_MEDIA_DIETA_L_100", (byte)43),
	DIETA_DESAYUNO_DIARIO("DIETA_DESAYUNO_DIARIO", "[06] DIETA DESAYUNO DIARIO", "DIETA_DESAYUNO_D", "DIETA_DESAYUNO_D * DIAS_DIETA_DESAYUNO_D", (byte)43),
	
	// ------------------------- INCENTIVOS
	
	INCENTIVOS_MENSUAL("INCENTIVOS_MENSUAL", "[07] INCENTIVOS MENSUALES", "INCENTIVOS_MENSUAL", "INCENTIVOS_MENSUAL * DIAS_TRABAJADOS / DIAS_MES", (byte)43),
	INCENTIVOS_DIARIO("INCENTIVOS_DIARIO", "[07] INCENTIVOS DIARIOS", "INCENTIVO_DIARIO", "INCENTIVO_DIARIO * DIAS_TRABAJADOS", (byte)43),
	INCENTIVOS_MARMOLERIAS_DIARIO("INCENTIVOS_MARMOLERIAS_DIARIO", "[07] INCENTIVOS MARMOLERIAS DIARIO", "INCENTIVOS_MARMOL_DIA", "INCENTIVOS_MARMOL_DIA * DIAS_TRABAJADOS", (byte)1),
	
	// ------------------------- INCENTIVOS
	
	TURNICIDAD_ANUAL("TURNICIDAD_ANUAL", "[09] TURNICIDAD ANUAL", "TURNICIDAD_ANUAL", "TURNICIDAD_ANUAL / PAGAS * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	SEGURO_DE_ACCIDENTES_ANUAL("SEGURO_DE_ACCIDENTES_ANUAL", "[08] SEGURO DE ACCIDENTES ANUAL", "SEGURO_DE_ACCIDENTES_A", "SEGURO_DE_ACCIDENTES_A / PAGAS * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	GRATIFICACION_ANUAL("GRATIFICACION_ANUAL", "[08] GRATIFICACION ANUAL", "GRATIFICACION_ANUAL", "GRATIFICACION_ANUAL / PAGAS * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	GRATIFICACION_NAVIDAD_ANUAL("GRATIFICACION_NAVIDAD_ANUAL", "[08] GRATIFICACION NAVIDAD ANUAL", "GRATIFICACION_NAVIDAD_A", "GRATIFICACION_NAVIDAD_A / PAGAS * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	INVALIDEZ_PERMANENTE_ABSOLUTA_ANUAL("INVALIDEZ_PERMANENTE_ABSOLUTA_ANUAL", "[40] INVALIDEZ PERMANENTE ABSOLUTA ANUAL", "INVALIDEZ_PERMANENTE_ABS", "INVALIDEZ_PERMANENTE_ABS / PAGAS * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	SEGURO_GRAN_INVALIDEZ_ANUAL("SEGURO_GRAN_INVALIDEZ_ANUAL", "[40] SEGURO GRAN INVALIDEZ ANUALL", "SEGURO_GRAN_INVALIDEZ", "SEGURO_GRAN_INVALIDEZ / PAGAS * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	SEGURO_DE_MUERTE_ANUAL("SEGURO_DE_MUERTE_ANUAL", "[01] SEGURO DE MUERTE ANUAL", "SEGURO_DE_MUERTE", "/*read-only*/SEGURO_DE_MUERTE/**/ / PAGAS * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	QUEBRANDO_DE_MONEDA_ANUAL("QUEBRANDO_DE_MONEDA_ANUAL", "[09] QUEBRANDO DE MONEDA ANUAL", "QUEBRANDO_MONEDA", "QUEBRANDO_MONEDA / PAGAS * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	
	ANTIGUEDAD_MENSUAL("ANTIGUEDAD_MENSUAL", "[09] ANTIGUEDAD MENSUALL", "ANTIGUEDAD_MENSUAL", "ANTIGUEDAD_MENSUAL * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	COMPENSACIONES_MARMOLERIAS_MENSUAL("COMPENSACIONES_MARMOLERIAS_MENSUAL", "[09] COMPENSACIONES MARMOLERIAS MENSUAL", "COMP_MARMOLERIAS", "COMP_MARMOLERIAS * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	AYUDA_FAMILIA_NUMEROSA_MENSUAL("AYUDA_FAMILIA_NUMEROSA_MENSUAL", "[09] AYUDA FAMILIA NUMEROSA MENSUAL", "AYUDA_FAMILIA_NUM", "AYUDA_FAMILIA_NUM * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	AYUDA_ESCOLAR_MENSUAL("AYUDA_ESCOLAR_MENSUAL", "[09] AYUDA ESCOLAR MENSUAL", "AYUDA_ESCOLAR_M", "AYUDA_ESCOLAR_M * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	QUEBRANDO_DE_MONEDA_MENSUAL("QUEBRANDO_DE_MONEDA_MENSUAL", "[09] QUEBRANDO DE MONEDA MENSUAL", "QUEBRANDO_MONEDA", "QUEBRANDO_MONEDA * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	COMPENSACIONES_MENSUAL("COMPENSACIONES_MENSUAL", "[09] COMPENSACIONES MENSUAL", "COMPENSACIONES", "COMPENSACIONES * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PAGAS_EXTRA_MENSUAL("PAGAS_EXTRA_MENSUAL", "[09] PAGAS EXTRA MENSUAL", "PAGAS_EXTRA_MENSUAL", "PAGAS_EXTRA_MENSUAL * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	TURNICIDAD_MENSUAL("TURNICIDAD_MENSUAL", "[09] TURNICIDAD MENSUAL", "TURNICIDAD_MENSUAL", "TURNICIDAD_MENSUAL * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	QUINQUENIOS_MENSUAL("QUINQUENIOS_MENSUAL", "[09] QUINQUENIOS MENSUAL", "QUINQUENIOS_MENSUAL", "QUINQUENIOS_MENSUAL * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	CUATRIENIOS_MENSUAL("CUATRIENIOS_MENSUAL", "[09] CUATRIENIOS MENSUAL", "CUATRIENIOS_MENSUAL", "CUATRIENIOS_MENSUAL * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	TRIENIOS_MENSUAL("TRIENIOS_MENSUAL", "[09] TRIENIOS MENSUAL", "TRIENIOS_MENSUAL", "TRIENIOS_MENSUAL * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	BIENIOS_MENSUAL("BIENIOS_MENSUAL", "[09] BIENIOS MENSUAL", "BIENIOS_MENSUAL", "BIENIOS_MENSUAL * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	P_C_I__MENSUAL("P_C_I__MENSUAL", "[09] P.C.I", "PCI_MENUSAL", "PCI_MENUSAL * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	ESTUDIOS_MENSUAL("ESTUDIOS_MENSUAL", "[09] ESTUDIOS MENSUAL", "ESTUDIOS_MENSUAL", "ESTUDIOS_MENSUAL * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PANTALLA_MENSUAL("PANTALLA_MENSUAL", "[09] PANTALLA MENSUAL", "PANTALLA_MENSUAL", "PANTALLA_MENSUAL * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	
	DIETA_KILOMETRAJE_HORAS("DIETA_KILOMETRAJE_HORAS", "[09] DIETA KILOMETRAJE", "DIETA_KILOMETRAJE_H", "DIETA_KILOMETRAJE_H * HORAS_TRABAJADAS", (byte)1),
	
	GARANTIZADO_MENSUAL("GARANTIZADO_MENSUAL", "[30] GARANTIZADO MENSUAL", "GARANTIZADO_MENSUAL", "GARANTIZADO_MENSUAL", (byte)13),
	
	RETRIBUCION_EN_ESPECIE_MENSUAL("RETRIBUCION_EN_ESPECIE_MENSUAL", "[30] RETRIBUCION EN ESPECIE", "RETRIBUCION_ESPECIE", "RETRIBUCION_ESPECIE", (byte)13),
	COMPLEMENTO_PERSONAL_DE_ANTIGUEDAD_MENSUAL("COMPLEMENTO_PERSONAL_DE_ANTIGUEDAD_MENSUAL", "[40] COMPLEMENTO PERSONAL DE ANTIGÜEDAD", "IMPORTE_ANTIGUEDAD", "INPUT(\"/*user*/IMPORTE_ANTIGUEDAD/**/\",ANTIGUEDAD_HELP)", (byte)1),
	
	SERVICIO_EXTRA_CAMARERO_DIARIO("SERVICIO_EXTRA_CAMARERO_DIARIO", "[40] SERVICIO EXTRA CAMARERO DIARIO", "S_E_CAMARERO_D", "S_E_CAMARERO_D * DIAS_TRABAJADOS", (byte)1),
	SERVICIO_EXTRA_LAVAPLATOS_DIARIO("SERVICIO_EXTRA_LAVAPLATOS_DIARIO", "[40] SERVICIO EXTRA LAVAPLATOS DIARIO", "S_E_LAVAPLATOS_D", "S_E_LAVAPLATOS_D * DIAS_TRABAJADOS", (byte)1),
	SERVICIO_EXTRA_AYUDANTE_DIARIO("SERVICIO_EXTRA_AYUDANTE_DIARIO", "[40] SERVICIO EXTRA AYUDANTE DIARIO", "S_E_AYUDANTE_D", "S_E_AYUDANTE_D * DIAS_TRABAJADOS", (byte)1),
	SERVICIO_EXTRA_COCINERO_DIARIO("SERVICIO_EXTRA_COCINERO_DIARIO", "[40] SERVICIO EXTRA COCINERO DIARIO", "S_E_COCINERO_D", "S_E_COCINERO_D * DIAS_TRABAJADOS", (byte)1),
	SERVICIO_EXTRA_COBRADOR_DIARIO("SERVICIO_EXTRA_COBRADOR_DIARIO", "[40] SERVICIO EXTRA COBRADOR DIARIO", "S_E_COBRADOR_D", "S_E_COBRADOR_D * DIAS_TRABAJADOS", (byte)1),
	SERVICIO_EXTRA_AYDTE_COCINA_DIARIO("SERVICIO_EXTRA_AYDTE_COCINA_DIARIO", "[40] SERVICIO EXTRA AYUDANTE COCINA DIARIO", "S_E_AYDTE_COCINA_D", "S_E_AYDTE_COCINA_D * DIAS_TRABAJADOS", (byte)1),
	SERVICIO_EXTRA_LAVAPLATOS_FESTIVOS_DIARIO("SERVICIO_EXTRA_LAVAPLATOS_FESTIVOS_DIARIO", "[40] SERVICIO EXTRA LAVAPLATOS FESTIVOS DIARIO", "S_E_LAVAPLATOS_FEST_D", "S_E_LAVAPLATOS_FEST_D * DIAS_TRABAJADOS", (byte)1),
	SERVICIO_EXTRA_CAMARERO_FESTIVOS_DIARIO("SERVICIO_EXTRA_CAMARERO_FESTIVOS_DIARIO", "[40] SERVICIO EXTRA CAMARERO FESTIVOS DIARIO", "S_E_CAMARERO_FEST_D", "S_E_CAMARERO_FEST_D * DIAS_TRABAJADOS", (byte)1),
	
	TURNICIDAD_DIARIO("TURNICIDAD_DIARIO", "[09] TURNICIDAD DIARIO", "TURNICIDAD_DIARIO", "TURNICIDAD_DIARIO * DIAS_TRABAJADOS", (byte)1),
	
	SISTEMA_INCENTIVACION_Y_PROMOCION_C10_MENSUAL("SISTEMA_INCENTIVACION_Y_PROMOCION_C10_MENSUAL", "[40] SISTEMA INCENTIVACION Y PROMOCION C10 MENSUAL", "SIST_INCENT_PROMO_C10_M", "SIST_INCENT_PROMO_C10_M * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PLUS_VINCULACION_17_AÑOS_ANUAL("PLUS_VINCULACION_17_AÑOS_ANUAL", "[40] PLUS VINCULACION 17 AÑOS ANUAL", "P_VINCULACION_17_AÑOS_A", "P_VINCULACION_17_AÑOS_A / PAGAS * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	SISTEMA_INCENTIVACION_Y_PROMOCION_C10_RVOG_ANUAL("SISTEMA_INCENTIVACION_Y_PROMOCION_C10_RVOG_ANUAL", "[40] SISTEMA INCENTIVACION Y PROMOCION C10 RVOG MENSUAL", "SIST_INC_PROM_C10_RVOG_M", "SIST_INC_PROM_C10_RVOG_M / PAGAS * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	SISTEMA_INCENTIVACION_Y_PROMOCION_A5_ANUAL("SISTEMA_INCENTIVACION_Y_PROMOCION_A5_ANUAL", "[40] SISTEMA INCENTIVACION Y PROMOCION A5 ANUAL", "SIST_INCENT_PROMO_A5_A", "SIST_INCENT_PROMO_A5_A / PAGAS * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PLUS_VINCULACION_16_AÑOS_MENSUAL("PLUS_VINCULACION_16_AÑOS_MENSUAL", "[40] PLUS VINCULACION 16 AÑOS MENSUAL", "P_VINCULACION_16_AÑOS_M", "P_VINCULACION_16_AÑOS_M * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PLUS_VINCULACION_5_AÑOS_MENSUAL("PLUS_VINCULACION_5_AÑOS_MENSUAL", "[40] PLUS VINCULACION 5 AÑOS MENSUAL", "P_VINCULACION_5_AÑOS_M", "P_VINCULACION_5_AÑOS_M * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PLUS_VINCULACION_RVOG_8_AÑOS_ANUAL("PLUS_VINCULACION_RVOG_8_AÑOS_ANUAL", "[40] PLUS VINCULACION RVOG 8 AÑOS ANUAL", "P_VINC_RVOG_8_AÑOS_A", "P_VINCULACION_RVOG_8_AÑOS_A / PAGAS * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	SISTEMA_INCENTIVACION_Y_PROMOCION_B8_ANUAL("SISTEMA_INCENTIVACION_Y_PROMOCION_B8_ANUAL", "[40] SISTEMA INCENTIVACION Y PROMOCION B8 ANUAL", "SIST_INCENT_PROMO_B8_A", "SIST_INCENT_PROMO_B8_A / PAGAS * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	COMPLEMENTO_ATENCION_PRIMARIA_RVOG_ANUAL("COMPLEMENTO_ATENCION_PRIMARIA_RVOG_ANUAL", "[40] COMPLEMENTO ATENCION PRIMARIA RVOG ANUAL", "COMPL_ATEN_PRIM_RVOG_A", "COMPL_ATEN_PRIM_RVOG_A / PAGAS * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	COMPLEMENTO_ATENCION_PROGRAMADA_RVOG_MENSUAL("COMPLEMENTO_ATENCION_PROGRAMADA_RVOG_MENSUAL", "[40] COMPLEMENTO ATENCION PRIMARIA RVOG MENSUAL", "COMPL_ATEN_PRIM_RVOG_M", "COMPL_ATEN_PRIM_RVOG_M * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PLUS_RESPONSABILIDAD_MENSUAL("PLUS_RESPONSABILIDAD_MENSUAL", "[40] PLUS RESPONSABILIDAD MENSUAL", "PLUS_RESPONSABILIDAD_M", "PLUS_RESPONSABILIDAD_M * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	RETRIBUCION_FIJA_MENSUAL("RETRIBUCION_FIJA_MENSUAL", "[40] RETRIBUCION FIJA MENSUAL", "RETRIBUCION_FIJA_M", "RETRIBUCION_FIJA_M", (byte)1),
	PLUS_VINCULACION_RVOG_15_AÑOS_ANUAL("PLUS_VINCULACION_RVOG_15_AÑOS_ANUAL", "[40] PLUS VINCULACION RVOG 15 AÑOS ANUAL", "P_VINC_RVOG_15_AÑOS_A", "P_VINC_RVOG_15_AÑOS_A / PAGAS * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PLUS_VINCULACION_21_AÑOS_ANUAL("PLUS_VINCULACION_21_AÑOS_ANUAL", "[40] PLUS VINCULACION 21 AÑOS ANUAL", "P_VINCULACION_21_AÑOS_A", "P_VINCULACION_21_AÑOS_A / PAGAS * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PLUS_VINCULACION_RVOG_11_AÑOS_MENSUAL("PLUS_VINCULACION_RVOG_11_AÑOS_MENSUAL", "[40] PLUS VINCULACION RVOG 11 AÑOS MENSUAL", "P_VINC_RVOG_11_AÑOS_M", "P_VINC_RVOG_11_AÑOS_M * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PLUS_VINCULACION_9_AÑOS_ANUAL("PLUS_VINCULACION_9_AÑOS_ANUAL", "[40] PLUS VINCULACION 9 AÑOS ANUAL", "P_VINCULACION_9_AÑOS_A", "P_VINCULACION_9_AÑOS_A / PAGAS * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PLUS_VINCULACION_9_AÑOS_MENSUAL("PLUS_VINCULACION_9_AÑOS_MENSUAL", "[40] PLUS VINCULACION 9 AÑOS MENSUAL", "P_VINCULACION_9_AÑOS_M", "P_VINCULACION_9_AÑOS_M * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PLUS_VINCULACION_11_AÑOS_ANUAL("PLUS_VINCULACION_11_AÑOS_ANUAL", "[40] PLUS VINCULACION 11 AÑOS ANUAL", "P_VINCULACION_11_AÑOS_A", "P_VINCULACION_11_AÑOS_A / PAGAS * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PLUS_VINCULACION_14_AÑOS_ANUAL("PLUS_VINCULACION_14_AÑOS_ANUAL", "[40] PLUS VINCULACION 14 AÑOS ANUAL", "P_VINCULACION_14_AÑOS_A", "P_VINCULACION_14_AÑOS_A / PAGAS * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PLUS_VINCULACION_RVOG_9_AÑOS_MENSUAL("PLUS_VINCULACION_RVOG_9_AÑOS_MENSUAL", "[40] PLUS VINCULACION RVOG 9 AÑOS MENSUAL", "P_VINC_RVOG_9_AÑOS_M", "P_VINC_RVOG_9_AÑOS_M * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PLUS_VINCULACION_RVOG_18_AÑOS_ANUAL("PLUS_VINCULACION_RVOG_18_AÑOS_ANUAL", "[40] PLUS VINCULACION RVOG 18 AÑOS ANUAL", "P_VINC_RVOG_18_AÑOS_A", "P_VINC_RVOG_18_AÑOS_A / PAGAS * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PLUS_VINCULACION_6_AÑOS_ANUAL("PLUS_VINCULACION_6_AÑOS_ANUAL", "[40] PLUS VINCULACION 6 AÑOS ANUAL", "P_VINCULACION_6_AÑOS_A", "P_VINCULACION_6_AÑOS_A / PAGAS * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PLUS_CONVENIO_RVOG_MENSUAL("PLUS_CONVENIO_RVOG_MENSUAL", "[40] PLUS CONVENIO RVOG MENSUAL", "PLUS_CONV_RVOG_M", "PLUS_CONV_RVOG_M * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	COMPLEMENTO_ESPECIFICO_RVOG_MENSUAL("COMPLEMENTO_ESPECIFICO_RVOG_MENSUAL", "[40] COMPLEMENTO ESPECIFICO RVOG MENSUAL", "COMPL_ESPECI_RVOG_M", "COMPL_ESPECI_RVOG_M * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	SALARIO_BASE_RVOG_MENSUAL("SALARIO_BASE_RVOG_MENSUAL", "[40] SALARIO BASE RVOG MENSUAL", "S_BASE_RVOG_M", "S_BASE_RVOG_M * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	SISTEMA_INCENTIVACION_Y_PROMOCION_B8_RVOG_ANUAL("SISTEMA_INCENTIVACION_Y_PROMOCION_B8_RVOG_ANUAL", "[40] SISTEMA INCENTIVACION Y PROMOCION B8 RVOG ANUAL", "SIS_INC_PROMO_B8_RVOG_M", "SIS_INC_PROMO_B8_RVOG_M / PAGAS * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PLUS_VINCULACION_RVOG_12_AÑOS_ANUAL("PLUS_VINCULACION_RVOG_12_AÑOS_ANUAL", "[40] PLUS VINCULACION RVOG 12 AÑOS ANUAL", "P_VINC_RVOG_12_AÑOS_A", "P_VINC_RVOG_12_AÑOS_A / PAGAS * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PLUS_VINCULACION_1_AÑOS_ANUAL("PLUS_VINCULACION_1_AÑOS_ANUAL", "[40] PLUS VINCULACION 1 AÑOS ANUAL", "P_VINCULACION_1_AÑOS_A", "P_VINCULACION_1_AÑOS_A / PAGAS * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	RETRIBUCION_FIJA_RVOG_MENSUAL("RETRIBUCION_FIJA_RVOG_MENSUAL", "[40] RETRIBUCION FIJA RVOG MENSUAL", "RETRIB_FIJA_RVOG_M", "RETRIB_FIJA_RVOG_M", (byte)1),
	PLUS_VINCULACION_RVOG_5_AÑOS_ANUAL("PLUS_VINCULACION_RVOG_5_AÑOS_ANUAL", "[40] PLUS VINCULACION RVOG 5 AÑOS ANUAL", "P_VINC_RVOG_5_AÑOS_A", "P_VINC_RVOG_5_AÑOS_A / PAGAS * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PLUS_NOCTURNIDAD_ANUAL("PLUS_NOCTURNIDAD_ANUAL", "[40] PLUS NOCTURNIDAD ANUAL", "P_NOCTURNIDAD_A", "P_NOCTURNIDAD_A / PAGAS * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PLUS_RESPONSABILIDAD_ANUAL("PLUS_RESPONSABILIDAD_ANUAL", "[40] PLUS RESPONSABILIDAD ANUAL", "P_RESPONSABILIDAD_A", "P_RESPONSABILIDAD_A / PAGAS * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PLUS_VINCULACION_RVOG_1_AÑOS_MENSUAL("PLUS_VINCULACION_RVOG_1_AÑOS_MENSUAL", "[40] PLUS VINCULACION RVOG 1 AÑOS MENSUAL", "P_VINC_RVOG_1_AÑOS_M", "P_VINC_RVOG_1_AÑOS_M * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PLUS_VINCULACION_18_AÑOS_ANUAL("PLUS_VINCULACION_18_AÑOS_ANUAL", "[40] PLUS VINCULACION 18 AÑOS ANUAL", "P_VINCULACION_18_AÑOS_A", "P_VINCULACION_18_AÑOS_A / PAGAS * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PLUS_VINCULACION_RVOG_10_AÑOS_ANUAL("PLUS_VINCULACION_RVOG_10_AÑOS_ANUAL", "[40] PLUS VINCULACION RVOG 10 AÑOS ANUAL", "P_VINC_RVOG_10_AÑOS_A", "P_VINC_RVOG_10_AÑOS_A / PAGAS * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	COMPLEMENTO_ATENCION_CONTINUADA_MENSUAL("COMPLEMENTO_ATENCION_CONTINUADA_MENSUAL", "[40] COMPLEMENTO ATENCION CONTINUADA MENSUAL", "COMPL_ATEN_CONT_M", "COMPL_ATEN_CONT_M * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	SISTEMA_INCENTIVACION_Y_PROMOCION_A5_RVOG_MENSUAL("SISTEMA_INCENTIVACION_Y_PROMOCION_A5_RVOG_MENSUAL", "[40] SISTEMA INCENTIVACION Y PROMOCION A5 RVOG MENSUAL", "S_INCENT_PROMO_A5_RVOG_M", "S_INCENT_PROMO_A5_RVOG_M * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PLUS_VINCULACION_5_AÑOS_ANUAL("PLUS_VINCULACION_5_AÑOS_ANUAL", "[40] PLUS VINCULACION 5 AÑOS ANUAL", "P_VINCULACION_5_AÑOS_A", "P_VINCULACION_5_AÑOS_A / PAGAS * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PLUS_VINCULACION_RVOG_20_AÑOS_ANUAL("PLUS_VINCULACION_RVOG_20_AÑOS_ANUAL", "[40] PLUS VINCULACION RVOG 20 AÑOS ANUAL", "P_VINC_RVOG_20_AÑOS_A", "P_VINC_RVOG_20_AÑOS_A / PAGAS * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PLUS_VINCULACION_20_AÑOS_MENSUAL("PLUS_VINCULACION_20_AÑOS_MENSUAL", "[40] PLUS VINCULACION 20 AÑOS MENSUAL", "P_VINCULACION_20_AÑOS_M", "P_VINCULACION_20_AÑOS_M * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PLUS_VINCULACION_RVOG_7_AÑOS_ANUAL("PLUS_VINCULACION_RVOG_7_AÑOS_ANUAL", "[40] PLUS VINCULACION RVOG 7 AÑOS ANUAL", "P_VINC_RVOG_7_AÑOS_A", "P_VINC_RVOG_7_AÑOS_A / PAGAS * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PLUS_NOCTURNIDAD_RVOG_MENSUAL("PLUS_NOCTURNIDAD_RVOG_MENSUAL", "[40] PLUS NOCTURNIDAD RVOG MENSUAL", "P_NOCT_RVOG_M", "P_NOCT_RVOG_M * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PLUS_VINCULACION_3_AÑOS_ANUAL("PLUS_VINCULACION_3_AÑOS_ANUAL", "[40] PLUS VINCULACION 3 AÑOS ANUAL", "P_VINCULACION_3_AÑOS_A", "P_VINCULACION_3_AÑOS_A / PAGAS * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	COMPLEMENTO_ATENCION_PROGRAMADA_MENSUAL("COMPLEMENTO_ATENCION_PROGRAMADA_MENSUAL", "[40] COMPLEMENTO ATENCION PROGRAMADA MENSUAL", "COMPL_ATEN_PROG_M", "COMPL_ATEN_PROG_M * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PLUS_RESPONSABILIDAD_RVOG_MENSUAL("PLUS_RESPONSABILIDAD_RVOG_MENSUAL", "[40] PLUS RESPONSABILIDAD RVOG ANUAL", "P_RESP_RVOG_A", "P_RESP_RVOG_A * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PLUS_VINCULACION_18_AÑOS_MENSUAL("PLUS_VINCULACION_18_AÑOS_MENSUAL", "[40] PLUS VINCULACION 18 AÑOS MENSUAL", "P_VINCULACION_18_AÑOS_M", "P_VINCULACION_18_AÑOS_M * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PLUS_VINCULACION_7_AÑOS_MENSUAL("PLUS_VINCULACION_7_AÑOS_MENSUAL", "[40] PLUS VINCULACION 7 AÑOS MENSUAL", "P_VINCULACION_7_AÑOS_M", "P_VINCULACION_7_AÑOS_M * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PLUS_VINCULACION_RVOG_13_AÑOS_MENSUAL("PLUS_VINCULACION_RVOG_13_AÑOS_MENSUAL", "[40] PLUS VINCULACION RVOG 13 AÑOS MENSUAL", "P_VINC_RVOG_13_AÑOS_M", "P_VINC_RVOG_13_AÑOS_M * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	DIETA_CENA_DIARIO("DIETA_CENA_DIARIO", "[09] DIETA CENA DIARIO", "DIETA_CENA_D", "DIETA_CENA_D * DIAS_TRABAJADOS", (byte)1),
	PLUS_VINCULACION_4_AÑOS_ANUAL("PLUS_VINCULACION_4_AÑOS_ANUAL", "[40] PLUS VINCULACION 4 AÑOS ANUAL", "P_VINCULACION_4_AÑOS_A", "P_VINCULACION_4_AÑOS_A / PAGAS * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	COMPLEMENTO_ATENCION_CONTINUADA_RVOG_MENSUAL("COMPLEMENTO_ATENCION_CONTINUADA_RVOG_MENSUAL", "[40] COMPLEMENTO ATENCION CONTINUADA RVOG MENSUAL", "COMPL_ATEN_CONT_RVOG_M", "COMPL_ATEN_CONT_RVOG_M * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PLUS_VINCULACION_RVOG_7_AÑOS_MENSUAL("PLUS_VINCULACION_RVOG_7_AÑOS_MENSUAL", "[40] PLUS VINCULACION RVOG 7 AÑOS MENSUAL", "P_VINC_RVOG_7_AÑOS_M", "P_VINC_RVOG_13_AÑOS_M * P_VINC_RVOG_13_AÑOS_M / DIAS_MES", (byte)1),
	COMPLEMENTO_ATENCION_PRIMARIA_RVOG_MENSUAL("COMPLEMENTO_ATENCION_PRIMARIA_RVOG_MENSUAL", "[40] COMPLEMENTO ATENCION PRIMARIA RVOG MENSUAL", "COMPL_ATEN_PRIM_RVOG_M", "COMPL_ATEN_PRIM_RVOG_M * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	RETRIBUCION_FIJA_ANUAL("RETRIBUCION_FIJA_ANUAL", "[40] RETRIBUCION FIJA ANUAL", "RETRIB_FIJA_A", "RETRIB_FIJA_A", (byte)1),
	PLUS_VINCULACION_21_AÑOS_MENSUAL("PLUS_VINCULACION_21_AÑOS_MENSUAL", "[40] PLUS VINCULACION 21 AÑOS MENSUAL", "P_VINCULACION_21_AÑOS_M", "P_VINCULACION_21_AÑOS_M * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	SISTEMA_INCENTIVACION_Y_PROMOCION_A5_MENSUAL("SISTEMA_INCENTIVACION_Y_PROMOCION_A5_MENSUAL", "[40] SISTEMA INCENTIVACION Y PROMOCION A5 MENSUAL", "S_INCENT_PROMO_A5_M", "S_INCENT_PROMO_A5_M * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PLUS_VINCULACION_RVOG_14_AÑOS_ANUAL("PLUS_VINCULACION_RVOG_14_AÑOS_ANUAL", "[40] PLUS VINCULACION RVOG 14 AÑOS ANUAL", "P_VINC_RVOG_14_AÑOS_A", "P_VINC_RVOG_14_AÑOS_A / PAGAS * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PLUS_VINCULACION_12_AÑOS_ANUAL("PLUS_VINCULACION_12_AÑOS_ANUAL", "[40] PLUS VINCULACION 12 AÑOS ANUAL", "P_VINCULACION_12_AÑOS_A", "P_VINCULACION_12_AÑOS_A / PAGAS * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PLUS_VINCULACION_RVOG_11_AÑOS_ANUAL("PLUS_VINCULACION_RVOG_11_AÑOS_ANUAL", "[40] PLUS VINCULACION RVOG 11 AÑOS ANUAL", "P_VINC_RVOG_11_AÑOS_A", "P_VINC_RVOG_11_AÑOS_A / PAGAS * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PLUS_VINCULACION_RVOG_21_AÑOS_ANUAL("PLUS_VINCULACION_RVOG_21_AÑOS_ANUAL", "[40] PLUS VINCULACION RVOG 21 AÑOS ANUAL", "P_VINC_RVOG_21_AÑOS_A", "P_VINC_RVOG_21_AÑOS_A / PAGAS * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PLUS_VINCULACION_19_AÑOS_ANUAL("PLUS_VINCULACION_19_AÑOS_ANUAL", "[40] PLUS VINCULACION 19 AÑOS ANUAL", "P_VINCULACION_19_AÑOS_A", "P_VINCULACION_19_AÑOS_A / PAGAS * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PLUS_VINCULACION_RVOG_6_AÑOS_ANUAL("PLUS_VINCULACION_RVOG_6_AÑOS_ANUAL", "[40] PLUS VINCULACION RVOG 6 AÑOS ANUAL", "P_VINC_RVOG_6_AÑOS_A", "P_VINC_RVOG_6_AÑOS_A / PAGAS * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PLUS_VINCULACION_RVOG_20_AÑOS_MENSUAL("PLUS_VINCULACION_RVOG_20_AÑOS_MENSUAL", "[40] PLUS VINCULACION RVOG 20 AÑOS MENSUAL", "P_VINC_RVOG_20_AÑOS_M", "P_VINC_RVOG_20_AÑOS_M * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PLUS_VINCULACION_RVOG_1_AÑOS_ANUAL("PLUS_VINCULACION_RVOG_1_AÑOS_ANUAL", "[40] PLUS VINCULACION RVOG 1 AÑOS ANUAL", "P_VINC_RVOG_1_AÑOS_A", "P_VINC_RVOG_1_AÑOS_A / PAGAS * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PLUS_VINCULACION_RVOG_21_AÑOS_MENSUAL("PLUS_VINCULACION_RVOG_21_AÑOS_MENSUAL", "[40] PLUS VINCULACION RVOG 21 AÑOS MENSUAL", "P_VINC_RVOG_21_AÑOS_M", "P_VINC_RVOG_21_AÑOS_M * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PLUS_VINCULACION_RVOG_13_AÑOS_ANUAL("PLUS_VINCULACION_RVOG_13_AÑOS_ANUAL", "[40] PLUS VINCULACION RVOG 13 AÑOS ANUAL", "P_VINC_RVOG_13_AÑOS_A", "P_VINC_RVOG_13_AÑOS_A / PAGAS * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PLUS_VINCULACION_7_AÑOS_ANUAL("PLUS_VINCULACION_7_AÑOS_ANUAL", "[40] PLUS VINCULACION 7 AÑOS ANUAL", "P_VINCULACION_7_AÑOS_A", "P_VINCULACION_7_AÑOS_A / PAGAS * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PLUS_VINCULACION_13_AÑOS_ANUAL("PLUS_VINCULACION_13_AÑOS_ANUAL", "[40] PLUS VINCULACION 13 AÑOS ANUAL", "P_VINCULACION_13_AÑOS_A", "P_VINCULACION_13_AÑOS_A / PAGAS * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PLUS_VINCULACION_8_AÑOS_ANUAL("PLUS_VINCULACION_8_AÑOS_ANUAL", "[40] PLUS VINCULACION 8 AÑOS ANUAL", "P_VINCULACION_8_AÑOS_A", "P_VINCULACION_8_AÑOS_A / PAGAS * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PLUS_VINCULACION_10_AÑOS_ANUAL("PLUS_VINCULACION_10_AÑOS_ANUAL", "[40] PLUS VINCULACION 10 AÑOS ANUAL", "P_VINCULACION_10_AÑOS_A", "P_VINCULACION_10_AÑOS_A / PAGAS * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PLUS_VINCULACION_20_AÑOS_ANUAL("PLUS_VINCULACION_20_AÑOS_ANUAL", "[40] PLUS VINCULACION 20 AÑOS ANUAL", "P_VINCULACION_20_AÑOS_A", "P_VINCULACION_20_AÑOS_A / PAGAS * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PLUS_VINCULACION_RVOG_3_AÑOS_ANUAL("PLUS_VINCULACION_RVOG_3_AÑOS_ANUAL", "[40] PLUS VINCULACION RVOG 3 AÑOS ANUAL", "P_VINC_RVOG_3_AÑOS_A", "P_VINC_RVOG_3_AÑOS_A / PAGAS * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PLUS_VINCULACION_RVOG_1_AÑO_ANUAL("PLUS_VINCULACION_RVOG_1_AÑO_ANUAL", "[40] PLUS VINCULACION RVOG 1 AÑO ANUAL", "P_VINC_RVOG_1_AÑO_A", "P_VINC_RVOG_1_AÑO_A / PAGAS * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PLUS_VINCULACION_1_AÑO_ANUAL("PLUS_VINCULACION_1_AÑO_ANUAL", "[40] PLUS VINCULACION 1 AÑO ANUAL", "P_VINCULACION_1_AÑO_A", "P_VINCULACION_1_AÑO_A / PAGAS * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PLUS_VINCULACION_19_AÑOS_MENSUAL("PLUS_VINCULACION_19_AÑOS_MENSUAL", "[40] PLUS VINCULACION 19 AÑOS MENSUAL", "P_VINCULACION_19_AÑOS_M", "P_VINCULACION_19_AÑOS_M * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PLUS_VINCULACION_6_AÑOS_MENSUAL("PLUS_VINCULACION_6_AÑOS_MENSUAL", "[40] PLUS VINCULACION 6 AÑOS MENSUAL", "P_VINCULACION_6_AÑOS_M", "P_VINCULACION_6_AÑOS_M * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PLUS_VINCULACION_1_AÑO_MENSUAL("PLUS_VINCULACION_1_AÑO_MENSUAL", "[40] PLUS VINCULACION 1 AÑO MENSUAL", "P_VINCULACION_1_AÑO_M", "P_VINCULACION_1_AÑO_M * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PLUS_VINCULACION_17_AÑOS_MENSUAL("PLUS_VINCULACION_17_AÑOS_MENSUAL", "[40] PLUS VINCULACION 17 AÑOS MENSUAL", "P_VINCULACION_17_AÑOS_M", "P_VINCULACION_17_AÑOS_M * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PLUS_VINCULACION_RVOG_4_AÑOS_ANUAL("PLUS_VINCULACION_RVOG_4_AÑOS_ANUAL", "[40] PLUS VINCULACION RVOG 4 AÑOS ANUAL", "P_VINC_RVOG_4_AÑOS_A", "P_VINC_RVOG_4_AÑOS_A / PAGAS * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PLUS_VINCULACION_RVOG_19_AÑOS_ANUAL("PLUS_VINCULACION_RVOG_19_AÑOS_ANUAL", "[40] PLUS VINCULACION RVOG 19 AÑOS ANUAL", "P_VINC_RVOG_19_AÑOS_A", "P_VINC_RVOG_19_AÑOS_A / PAGAS * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PLUS_VINCULACION_RVOG_1_AÑO_MENSUAL("PLUS_VINCULACION_RVOG_1_AÑO_MENSUAL", "[40] PLUS VINCULACION RVOG 1 AÑO MENSUAL", "P_VINC_RVOG_1_AÑO_M", "P_VINC_RVOG_1_AÑO_M * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PLUS_VINCULACION_8_AÑOS_MENSUAL("PLUS_VINCULACION_8_AÑOS_MENSUAL", "[40] PLUS VINCULACION 8 AÑOS MENSUAL", "P_VINCULACION_8_AÑOS_M", "P_VINCULACION_8_AÑOS_M * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PLUS_VINCULACION_RVOG_10_AÑOS_MENSUAL("PLUS_VINCULACION_RVOG_10_AÑOS_MENSUAL", "[40] PLUS VINCULACION RVOG 10 AÑOS MENSUAL", "P_VINC_RVOG_10_AÑOS_M", "P_VINC_RVOG_10_AÑOS_M * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PLUS_VINCULACION_RVOG_12_AÑOS_MENSUAL("PLUS_VINCULACION_RVOG_12_AÑOS_MENSUAL", "[40] PLUS VINCULACION RVOG 12 AÑOS MENSUAL", "P_VINC_RVOG_12_AÑOS_M", "P_VINC_RVOG_12_AÑOS_M * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	SISTEMA_INCENTIVACION_Y_PROMOCION_C10_ANUAL("SISTEMA_INCENTIVACION_Y_PROMOCION_C10_ANUAL", "[40] SISTEMA INCENTIVACION Y PROMOCION C10 MENSUAL", "SIST_INC_PROM_C10_M", "SIST_INC_PROM_C10_M / PAGAS * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PLUS_RESPONSABILIDAD_RVOG_ANUAL("PLUS_RESPONSABILIDAD_RVOG_ANUAL", "[40] PLUS RESPONSABILIDAD RVOG ANUAL", "P_RESP_RVOG_A", "P_RESP_RVOG_A / PAGAS * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PLUS_VINCULACION_RVOG_6_AÑOS_MENSUAL("PLUS_VINCULACION_RVOG_6_AÑOS_MENSUAL", "[40] PLUS VINCULACION RVOG 6 AÑOS MENSUAL", "P_VINC_RVOG_6_AÑOS_M", "P_VINC_RVOG_6_AÑOS_M * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	SALARIO_BASE_RVOG_ANUAL("SALARIO_BASE_RVOG_ANUAL", "[40] SALARIO BASE RVOG ANUAL", "SALARIO_BASE_RVOG_A", "SALARIO_BASE_RVOG_A / PAGAS * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PLUS_VINCULACION_RVOG_8_AÑOS_MENSUAL("PLUS_VINCULACION_RVOG_8_AÑOS_MENSUAL", "[40] PLUS VINCULACION RVOG 8 AÑOS MENSUAL", "P_VINC_RVOG_8_AÑOS_M", "P_VINC_RVOG_8_AÑOS_M * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	COMPLEMENTO_SIPDP_RVOG_MENSUAL("COMPLEMENTO_SIPDP_RVOG_MENSUAL", "[40] COMPLEMENTO SIPDP RVOG MENSUAL", "COMP_SIPDP_RVOG_M", "COMP_SIPDP_RVOG_M * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	COMPLEMENTO_ATENCION_PRIMARIA_ANUAL("COMPLEMENTO_ATENCION_PRIMARIA_ANUAL", "[40] COMPLEMENTO ATENCION PRIMARIA ANUAL", "COMP_ATEN_PRIM_A", "COMP_ATEN_PRIM_A / PAGAS * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PLUS_VINCULACION_RVOG_2_AÑOS_MENSUAL("PLUS_VINCULACION_RVOG_2_AÑOS_MENSUAL", "[40] PLUS VINCULACION RVOG 2 AÑOS MENSUAL", "P_VINC_RVOG_2_AÑOS_M", "P_VINC_RVOG_2_AÑOS_M * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PLUS_VINCULACION_15_AÑOS_ANUAL("PLUS_VINCULACION_15_AÑOS_ANUAL", "[40] PLUS VINCULACION 15 AÑOS ANUAL", "P_VINCULACION_15_AÑOS_A", "P_VINCULACION_15_AÑOS_A / PAGAS * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	RETRIBUCION_EN_FUNCION_DE_OBJETIVOS_RVOG_MENSUAL("RETRIBUCION_EN_FUNCION_DE_OBJETIVOS_RVOG_MENSUAL", "[40] RETRIBUCION EN FUNCION DE OBJETIVOS RVOG MENSUALL", "RETRIB_FUNC_OBJ_RVOG_M", "RETRIB_FUNC_OBJ_RVOG_M * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PLUS_VINCULACION_RVOG_2_AÑOS_ANUAL("PLUS_VINCULACION_RVOG_2_AÑOS_ANUAL", "[40] PLUS VINCULACION RVOG 2 AÑOS ANUAL", "P_VINC_RVOG_2_AÑOS_A", "P_VINC_RVOG_2_AÑOS_A / PAGAS * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PLUS_VINCULACION_RVOG_17_AÑOS_ANUAL("PLUS_VINCULACION_RVOG_17_AÑOS_ANUAL", "[40] PLUS VINCULACION RVOG 17 AÑOS ANUAL", "P_VINC_RVOG_17_AÑOS_A", "P_VINC_RVOG_17_AÑOS_A / PAGAS * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PLUS_VINCULACION_RVOG_5_AÑOS_MENSUAL("PLUS_VINCULACION_RVOG_5_AÑOS_MENSUAL", "[40] PLUS VINCULACION RVOG 5 AÑOS MENSUAL", "P_VINC_RVOG_5_AÑOS_M", "P_VINC_RVOG_5_AÑOS_M * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PLUS_VINCULACION_RVOG_4_AÑOS_MENSUAL("PLUS_VINCULACION_RVOG_4_AÑOS_MENSUAL", "[40] PLUS VINCULACION RVOG 4 AÑOS MENSUAL", "P_VINC_RVOG_4_AÑOS_M", "P_VINC_RVOG_4_AÑOS_M * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PLUS_VINCULACION_RVOG_3_AÑOS_MENSUAL("PLUS_VINCULACION_RVOG_3_AÑOS_MENSUAL", "[40] PLUS VINCULACION RVOG 3 AÑOS MENSUAL", "P_VINC_RVOG_3_AÑOS_M", "P_VINC_RVOG_3_AÑOS_M * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	RETRIBUCION_FIJA_RVOG_ANUAL("RETRIBUCION_FIJA_RVOG_ANUAL", "[40] RETRIBUCION FIJA RVOG ANUAL", "RETRIB_FIJA_RVOG_A", "RETRIB_FIJA_RVOG_A", (byte)1),
	COMPLEMENTO_ATENCION_PRIMARIA_MENSUAL("COMPLEMENTO_ATENCION_PRIMARIA_MENSUAL", "[40] COMPLEMENTO ATENCION PRIMARIA MENSUAL", "COMPL_ATEN_PRIM_M", "COMPL_ATEN_PRIM_M * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	SISTEMA_INCENTIVACION_Y_PROMOCION_A5_RVOG_ANUAL("SISTEMA_INCENTIVACION_Y_PROMOCION_A5_RVOG_ANUAL", "[40] SISTEMA INCENTIVACION Y PROMOCION A5 RVOG ANUAL", "S_INCENT_PROMO_A5_RVOG_A", "S_INCENT_PROMO_A5_RVOG_A / PAGAS * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PLUS_VINCULACION_2_AÑOS_ANUAL("PLUS_VINCULACION_2_AÑOS_ANUAL", "[40] PLUS VINCULACION 2 AÑOS ANUAL", "P_VINCULACION_2_AÑOS_A", "P_VINCULACION_2_AÑOS_A / PAGAS * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PLUS_VINCULACION_10_AÑOS_MENSUAL("PLUS_VINCULACION_10_AÑOS_MENSUAL", "[40] PLUS VINCULACION 10 AÑOS MENSUAL", "P_VINCULACION_10_AÑOS_M", "P_VINCULACION_10_AÑOS_M * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PLUS_VINCULACION_RVOG_14_AÑOS_MENSUAL("PLUS_VINCULACION_RVOG_14_AÑOS_MENSUAL", "[40] PLUS VINCULACION RVOG 14 AÑOS MENSUAL", "P_VINC_RVOG_14_AÑOS_M", "P_VINC_RVOG_14_AÑOS_M * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PLUS_VINCULACION_RVOG_15_AÑOS_MENSUAL("PLUS_VINCULACION_RVOG_15_AÑOS_MENSUAL", "[40] PLUS VINCULACION RVOG 15 AÑOS MENSUAL", "P_VINC_RVOG_15_AÑOS_M", "P_VINC_RVOG_15_AÑOS_M * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PLUS_VINCULACION_16_AÑOS_ANUAL("PLUS_VINCULACION_16_AÑOS_ANUAL", "[40] PLUS VINCULACION 16 AÑOS ANUAL", "P_VINCULACION_16_AÑOS_A", "P_VINCULACION_16_AÑOS_A / PAGAS * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PLUS_CONVENIO_RVOG_ANUAL("PLUS_CONVENIO_RVOG_ANUAL", "[40] PLUS CONVENIO RVOG ANUAL", "P_CONV_RVOG_A", "P_CONV_RVOG_A / PAGAS * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PLUS_VINCULACION_11_AÑOS_MENSUAL("PLUS_VINCULACION_11_AÑOS_MENSUAL", "[40] PLUS VINCULACION 11 AÑOS MENSUAL", "P_VINCULACION_11_AÑOS_M", "P_VINCULACION_11_AÑOS_M * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PLUS_VINCULACION_RVOG_17_AÑOS_MENSUAL("PLUS_VINCULACION_RVOG_17_AÑOS_MENSUAL", "[40] PLUS VINCULACION RVOG 17 AÑOS MENSUAL", "P_VINC_RVOG_17_AÑOS_M", "P_VINC_RVOG_17_AÑOS_M * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	SISTEMA_INCENTIVACION_Y_PROMOCION_C10_RVOG_MENSUAL("SISTEMA_INCENTIVACION_Y_PROMOCION_C10_RVOG_MENSUAL", "[40] SISTEMA INCENTIVACION Y PROMOCION C10 RVOG MENSUAL", "SIS_INCEN_PROM_C10_RVOG_M", "SIS_INCEN_PROM_C10_RVOG_M * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PLUS_VINCULACION_14_AÑOS_MENSUAL("PLUS_VINCULACION_14_AÑOS_MENSUAL", "[40] PLUS VINCULACION 14 AÑOS MENSUAL", "P_VINCULACION_14_AÑOS_M", "P_VINCULACION_14_AÑOS_M * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	SISTEMA_INCENTIVACION_Y_PROMOCION_B8_MENSUAL("SISTEMA_INCENTIVACION_Y_PROMOCION_B8_MENSUAL", "[40] SISTEMA INCENTIVACION Y PROMOCION B8 MENSUAL", "SIST_INCENT_PROMO_B8_M", "SIST_INCENT_PROMO_B8_M * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PLUS_VINCULACION_15_AÑOS_MENSUAL("PLUS_VINCULACION_15_AÑOS_MENSUAL", "[40] PLUS VINCULACION 15 AÑOS MENSUAL", "P_VINCULACION_15_AÑOS_M", "P_VINCULACION_15_AÑOS_M * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PLUS_VINCULACION_RVOG_16_AÑOS_MENSUAL("PLUS_VINCULACION_RVOG_16_AÑOS_MENSUAL", "[40] PLUS VINCULACION RVOG 16 AÑOS MENSUAL", "P_VINC_RVOG_16_AÑOS_M", "P_VINC_RVOG_16_AÑOS_M * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PLUS_VINCULACION_4_AÑOS_MENSUAL("PLUS_VINCULACION_4_AÑOS_MENSUAL", "[40] PLUS VINCULACION 4 AÑOS MENSUAL", "P_VINCULACION_4_AÑOS_M", "P_VINCULACION_4_AÑOS_M * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PLUS_VINCULACION_RVOG_9_AÑOS_ANUAL("PLUS_VINCULACION_RVOG_9_AÑOS_ANUAL", "[40] PLUS VINCULACION RVOG 9 AÑOS ANUAL", "P_VINC_RVOG_9_AÑOS_A", "P_VINC_RVOG_9_AÑOS_A / PAGAS * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	SISTEMA_INCENTIVACION_Y_PROMOCION_B8_RVOG_MENSUAL("SISTEMA_INCENTIVACION_Y_PROMOCION_B8_RVOG_MENSUAL", "[40] SISTEMA INCENTIVACION Y PROMOCION B8 RVOG MENSUAL", "S_INC_PROMO_B8_RVOG_M", "S_INC_PROMO_B8_RVOG_M * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PLUS_VINCULACION_RVOG_19_AÑOS_MENSUAL("PLUS_VINCULACION_RVOG_19_AÑOS_MENSUAL", "[40] PLUS VINCULACION RVOG 19 AÑOS MENSUAL", "P_VINC_RVOG_19_AÑOS_M", "P_VINC_RVOG_19_AÑOS_M * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PLUS_VINCULACION_3_AÑOS_MENSUAL("PLUS_VINCULACION_3_AÑOS_MENSUAL", "[40] PLUS VINCULACION 3 AÑOS MENSUAL", "P_VINCULACION_3_AÑOS_M", "P_VINCULACION_3_AÑOS_M * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	RETRIBUCION_EN_FUNCION_DE_OBJETIVOS_MENSUAL("RETRIBUCION_EN_FUNCION_DE_OBJETIVOS_MENSUAL", "[40] RETRIBUCION EN FUNCION DE OBJETIVOS MENSUAL", "RETRIB_FUNC_OBJ_M", "RETRIB_FUNC_OBJ_M * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	COMPLEMENTO_SIPDP_MENSUAL("COMPLEMENTO_SIPDP_MENSUAL", "[40] COMPLEMENTO SIPDP MENSUAL", "COMPL_SIPDP_M", "COMPL_SIPDP_M * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PLUS_VINCULACION_13_AÑOS_MENSUAL("PLUS_VINCULACION_13_AÑOS_MENSUAL", "[40] PLUS VINCULACION 13 AÑOS MENSUAL", "P_VINCULACION_13_AÑOS_M", "P_VINCULACION_13_AÑOS_M * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PLUS_VINCULACION_RVOG_18_AÑOS_MENSUAL("PLUS_VINCULACION_RVOG_18_AÑOS_MENSUAL", "[40] PLUS VINCULACION RVOG 18 AÑOS MENSUAL", "P_VINC_RVOG_18_AÑOS_M", "P_VINC_RVOG_18_AÑOS_M * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PLUS_VINCULACION_RVOG_16_AÑOS_ANUAL("PLUS_VINCULACION_RVOG_16_AÑOS_ANUAL", "[40] PLUS VINCULACION RVOG 16 AÑOS ANUAL", "P_VINC_RVOG_16_AÑOS_A", "P_VINC_RVOG_16_AÑOS_A / PAGAS * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PLUS_NOCTURNIDAD_RVOG_ANUAL("PLUS_NOCTURNIDAD_RVOG_ANUAL", "[40] PLUS NOCTURNIDAD RVOG ANUAL", "P_NOCT_RVOG_A", "P_NOCT_RVOG_A / PAGAS * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PLUS_VINCULACION_2_AÑOS_MENSUAL("PLUS_VINCULACION_2_AÑOS_MENSUAL", "[40] PLUS VINCULACION 2 AÑOS MENSUAL", "P_VINCULACION_2_AÑOS_M", "P_VINCULACION_2_AÑOS_M * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PLUS_VINCULACION_12_AÑOS_MENSUAL("PLUS_VINCULACION_12_AÑOS_MENSUAL", "[40] PLUS VINCULACION 12 AÑOS MENSUAL", "P_VINCULACION_12_AÑOS_M", "P_VINCULACION_12_AÑOS_M * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	
	SALARIO_MINIMO_GARANTIZADO_ANUAL("SALARIO_MINIMO_GARANTIZADO_ANUAL", "[40] SALARIO MINIMO GARANTIZADO ANUAL", "S_MIN_GARANT_A", "S_MIN_GARANT_A / PAGAS * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	;
	
	private String name;
	private String normalizeName;
	private String conceptCode;
	private String expression;
	private byte type;
	
	private AgreementPayment(String name, String normalizeName, String conceptCode, String expression, byte type) {
		this.name = name;
		this.normalizeName = normalizeName;
		this.conceptCode = conceptCode;
		this.expression = expression;
		this.type = type;
	}
	
	public static AgreementPayment safeValueOf(String name) {
		if (AonStringUtils.isBlank(name)) {
			return null;
		}
		try {
			return AgreementPayment.valueOf(name);
		} catch (IllegalArgumentException e) {
			return null;
		}
	}

	public String getName() {
		return name;
	}
	
	public String getNormalizeName() {
		return normalizeName;
	}

	public String getConceptCode() {
		return conceptCode;
	}

	public String getExpression() {
		return expression;
	}
	
	public byte getType() {
		return type;
	}
	
	public static void main(String[] args) {
		for(int i=0; i < AgreementPayment.values().length; i++) {
			System.out.println("put(\"" + AgreementPayment.values()[i].name + "\", \"" + AgreementPayment.values()[i].getConceptCode() + "\");");
		}
	}
	
}
