package com.esferalia.aon.payroll.agreement;

import java.io.Serializable;

import com.esferalia.aon.watson.util.AonStringUtils;

public enum AgreementPayment implements Serializable {

	// ------------------------- SALARIO BASE
	
	SALARIO_CONVENIO_ANUAL("SALARIO_CONVENIO_ANUAL", "[01] SALARIO BASE ANUAL", "SALARIO_ANUAL", "/*read-only*/SALARIO_ANUAL/**/ / PAGAS * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	SALARIO_CONVENIO_ANUAL_ANUAL("SALARIO_CONVENIO_ANUAL_ANUAL", "[01] SALARIO BASE ANUAL", "SALARIO_ANUAL", "/*read-only*/SALARIO_ANUAL/**/ / PAGAS * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	SALARIO_BASE_ANUAL("SALARIO_BASE_ANUAL", "[01] SALARIO BASE ANUAL", "SALARIO_ANUAL", "/*read-only*/SALARIO_ANUAL/**/ / PAGAS * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	SALARIO_BASE_ANUAL_ANUAL("SALARIO_BASE_ANUAL_ANUAL", "[01] SALARIO BASE ANUAL", "SALARIO_ANUAL", "/*read-only*/SALARIO_ANUAL/**/ / PAGAS * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	
	SALARIO_CONVENIO_MENSUAL("SALARIO_CONVENIO_MENSUAL", "[02] SALARIO BASE MENSUAL", "SALARIO_MENSUAL", "/*read-only*/SALARIO_MENSUAL/**/ * DIAS_TRABAJADOS / DIAS_MES ", (byte)1),
	SALARIO_BASE_MENSUAL("SALARIO_BASE_MENSUAL", "[02] SALARIO BASE MENSUAL", "SALARIO_MENSUAL", "/*read-only*/SALARIO_MENSUAL/**/ * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	
	SALARIO_CONVENIO_HORAS("SALARIO_CONVENIO_HORAS", "[04] SALARIO BASE HORAS", "SALARIO_HORA", "(SALARIO_HORA=/*read-only*/SALARIO_HORA/**/) * HORAS_TRABAJADAS", (byte)1),
	SALARIO_HORA_HORAS("SALARIO_HORA_HORAS", "[04] SALARIO BASE HORAS", "SALARIO_HORA", "(SALARIO_HORA=/*read-only*/SALARIO_HORA/**/) * HORAS_TRABAJADAS", (byte)1),
	SALARIO_BASE_HORAS("SALARIO_BASE_HORAS", "[04] SALARIO BASE HORAS", "SALARIO_HORA", "(SALARIO_HORA=/*read-only*/SALARIO_HORA/**/) * HORAS_TRABAJADAS", (byte)1),
	
	SALARIO_CONVENIO_DIARIO("SALARIO_CONVENIO_DIARIO", "[03] SALARIO BASE DIARIO", "SALARIO_DIARIO", "/*read-only*/SALARIO_ANUAL/**/ * HORAS_TRABAJADAS", (byte)1),
	SALARIO_BASE_DIARIO("SALARIO_BASE_DIARIO", "[03] SALARIO BASE DIARIO", "SALARIO_DIARIO", "(SALARIO_DIARIO=/*read-only*/SALARIO_DIARIO/**/) * DIAS_TRABAJADOS", (byte)1),

	SALARIO_BASE_MINIMO_ANUAL("SALARIO_BASE_MINIMO_ANUAL", "[06] SALARIO BASE MINIMO SMI", "PORC_SALARIO", "MAX(SMI*DIAS_TRABAJADOS/DIAS_MES, (PORC_SALARIO=SI(AÑOS_ANTIGUEDAD<2, SI (AÑOS_ANTIGUEDAD<1, 70 ,80) ,100))* /*user*/SALARIO_PRACTICAS/**/ /100*DIAS_TRABAJADOS/DIAS_MES)", (byte)1),

	// ------------------------- PLUS CONVENIO
	
	PLUS_CONVENIO_ANUAL("PLUS_CONVENIO_ANUAL", "[10] PLUS CONVENIO ANUAL", "PLUS_CONVENIO_ANUAL", "PLUS_CONVENIO_ANUAL/PAGAS", (byte)1),
	
	PLUS_CONVENIO_MENSUAL("PLUS_CONVENIO_MENSUAL", "[10] PLUS CONVENIO MENSUAL", "PLUS_CONVENIO", "(/*user*/ PLUS_CONVENIO/**/) * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	COMPLEMENTO_CONVENIO_MENSUAL("COMPLEMENTO_CONVENIO_MENSUAL", "[02] PLUS CONVENIO MENSUAL", "PLUS_CONVENIO_MENSUAL", "PLUS_CONVENIO_MENSUAL * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	
	PLUS_CONVENIO_HORAS("PLUS_CONVENIO_HORAS", "[02] PLUS CONVENIO HORAS", "PLUS_CONVENIO_HORAS", "(SALARIO_DIARIO=/*read-only*/PLUS_CONVENIO_HORAS/**/) * HORAS_TRABAJADAS", (byte)1),
	
	COMPLEMENTO_CONVENIO_DIARIO("COMPLEMENTO_CONVENIO_DIARIO", "[02] PLUS CONVENIO DIARIO", "PLUS_CONVENIO_DIARIO", "PLUS_CONVENIO_DIARIO * DIAS_TRABAJADOS", (byte)1),
	
	// ------------------------- OTROS PLUS CONVENIO
	
	PLUS_SALARIAL_DIARIO("PLUS_SALARIAL_DIARIO", "[11] PLUS SALARIAL DIARIO", "PLUS_DIARIO", "(/*user*/PLUS_DIARIO/**/) * DIAS_TRABAJADOS", (byte)1),
	PLUS_SALARIAL_LABORAL_DIARIO("PLUS_SALARIAL_LABORAL_DIARIO", "[12] PLUS SALARIAL DIARIO LABORABLES", "PLUS_LABORABLES", "(/*user*/PLUS_LABORABLES/**/) * DIAS_EFECTIVOS", (byte)1),
	PLUS_SALARIAL_FIJO_MENSUAL("PLUS_SALARIAL_FIJO_MENSUAL", "[13] PLUS SALARIAL FIJO", "PLUS_FIJO", "FRACCIONAR(/*user*/PLUS_FIJO/**/)", (byte)1),
	
	PLUS_EXTRA_CATEGORIA_ANUAL("PLUS_EXTRA_CATEGORIA_ANUAL", "[03] PLUS EXTRA CATEGORIA ANUAL", "PLUS_EXTRA_CATEGORIA_A", "PLUS_EXTRA_CATEGORIA_A / PAGAS * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	
	PLUS_ACTIVIDAD_MENSUAL("PLUS_ACTIVIDAD_MENSUAL", "[03] PLUS ACTIVIDAD MENSUAL", "PLUS_ACTIVIDAD_MENSUAL", "PLUS_ACTIVIDAD_MENSUAL * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PLUS_ACTIVIDAD_DIARIO("PLUS_ACTIVIDAD_DIARIO", "[03] PLUS ACTIVIDAD DIARIO", "PLUS_ACTIVIDAD_DIARIO", "PLUS_ACTIVIDAD_DIARIO * DIAS_TRABAJADOS", (byte)1),
	
	PLUS_EXTRA_SALARIAL_MENSUAL("PLUS_EXTRA_SALARIAL_MENSUAL", "[20] PLUS EXTRA SALARIAL MENSUAL", "PLUS_XS_MENSUAL", "(/*user*/PLUS_XS_MENSUAL/**/) * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PLUS_EXTRA_SALARIAL_DIARIO("PLUS_EXTRA_SALARIAL_DIARIO", "[21] PLUS EXTRA SALARIAL DIARIO", "PLUS_XS_DIARIO", "(/*user*/PLUS_XS_DIARIO/**/) * DIAS_TRABAJADOS", (byte)1),
	PLUS_EXTRA_SALARIAL_LABORAL_DIARIO("PLUS_EXTRA_SALARIAL_LABORAL_DIARIO", "[22] PLUS EXTRASALARIAL DIARIO LABORABLES", "PLUS_XS_LABORABLES", "(/*user*/PLUS_XS_LABORABLES/**/) * DIAS_EFECTIVOS", (byte)1),
	PLUS_EXTRA_SALARIAL_FIJO_MENSUAL("PLUS_EXTRA_SALARIAL_FIJO_MENSUAL", "[23] PLUS EXTRASALARIAL FIJO", "PLUS_XS_FIJO", "FRACCIONAR(/*user*/PLUS_XS_FIJO/**/)", (byte)1),
	
	PLUS_VESTUARIO_MENSUAL("PLUS_VESTUARIO_MENSUAL", "[03] PLUS VESTUARIO MENSUAL", "PLUS_VESTUARIO", "PLUS_VESTUARIO * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	
	PLUS_ROTACION_MENSUAL("PLUS_ROTACION_MENSUAL", "[03] PLUS ROTACION MENSUAL", "PLUS_ROTACION", "PLUS_ROTACION * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	
	PLUS_DISTANCIA_MENSUAL("PLUS_DISTANCIA_MENSUAL", "[03] PLUS DISTANCIA MENSUAL", "PLUS_DISTANCIA_M", "PLUS_DISTANCIA_M * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PLUS_DISTANCIA_HORAS("PLUS_DISTANCIA_HORAS", "[03] PLUS DISTANCIA HORAS", "PLUS_DISTANCIA_H", "PLUS_DISTANCIA_H * HORAS_TRABAJADAS", (byte)1),
	
	PLUS_URGENCIA_MENSUAL("PLUS_URGENCIA_MENSUAL", "[03] PLUS URGENCIA MENSUAL", "PLUS_URGENCIA", "PLUS_URGENCIA * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	
	PLUS_ASISTENCIA_MENSUAL("PLUS_ASISTENCIA_MENSUAL", "[03] PLUS ASISTENCIA MENSUAL", "PLUS_ASISTENCIA", "PLUS_ASISTENCIA * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	
	PLUS_TRANSPORTE_MENSUAL("PLUS_TRANSPORTE_MENSUAL", "[03] PLUS TRANSPORTE MENSUAL", "PLUS_TRANSPORTE_MEN", "PLUS_TRANSPORTE_MEN * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PLUS_TRANSPORTE_DIARIO("PLUS_TRANSPORTE_DIARIO", "[03] PLUS TRANSPORTE DIARIO", "PLUS_TRANSPORTE_DIA", "PLUS_TRANSPORTE_DIA * DIAS_TRABAJADOS", (byte)1),
	
	PLUS_CARENCIA_DE_INCENTIVOS_MENSUAL("PLUS_CARENCIA_DE_INCENTIVOS_MENSUAL", "[03] PLUS CARENCIA DE INCENTIVOS MENSUAL", "PLUS_CARENCIA_INCENT_M", "PLUS_CARENCIA_INCENT_M * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	
	PLUS_RIESGO_DIARIO("PLUS_RIESGO_DIARIO", "[03] PLUS RIESGO DIARIO", "PLUS_RIESGO", "PLUS_RIESGO * DIAS_TRABAJADOS", (byte)1),
	
	PLUS_DOMINGOS_Y_FESTIVOS_DIARIO("PLUS_DOMINGOS_Y_FESTIVOS_DIARIO", "[03] PLUS DOMINGOS Y FESTIVOS", "PLUS_FINDES", "PLUS_FINDES * DIAS_TRABAJADOS", (byte)1),
	
	PLUS_PENOSIDAD_1_CIRCUNSTANCIA_DIARIO("PLUS_PENOSIDAD_1_CIRCUNSTANCIA_DIARIO", "[03] PLUS_PENOSIDAD 1 CIRCUNSTANCIA DIARIO", "PLUS_PENOSIDAD_1", "PLUS_PENOSIDAD_1 * DIAS_TRABAJADOS", (byte)1),
	PLUS_PENOSIDAD_2_CIRCUNSTANCIAS_DIARIO("PLUS_PENOSIDAD_2_CIRCUNSTANCIAS_DIARIO", "[03] PLUS_PENOSIDAD 2 CIRCUNSTANCIAS DIARIO", "PLUS_PENOSIDAD_2", "PLUS_PENOSIDAD_2 * DIAS_TRABAJADOS", (byte)1),
	
	PLUS_TOXICIDAD_MENSUAL("PLUS_TOXICIDAD_MENSUAL", "[03] PLUS TOXICIDAD", "PLUS_TOXICIDAD", "PLUS_TOXICIDAD * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	
	PLUS_ACERCAMIENTO_ANUAL("PLUS_ACERCAMIENTO_ANUAL", "[03] PLUS ACERCAMIENTO ANUAL", "PLUS_ACERCAMIENTO_ANUAL", "PLUS_ACERCAMIENTO_ANUAL / PAGAS * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	
	COMPLEMENTO_ESPECIFICO_MENSUAL("COMPLEMENTO_ESPECIFICO_MENSUAL", "[03] COMPLEMENTO ESPECIFICO MENSUAL", "COMPL_ESPECIFICO_MEN", "COMPL_ESPECIFICO_MEN * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	
	COMPLEMENTO_NO_SALARIAL_ANUAL("COMPLEMENTO_NO_SALARIAL_ANUAL", "[03] COMPLEMENTO NO SALARIAL ANUAL", "COMPL_NO_SALARIAL_ANUAL", "COMPLEMENTO_NO_SALARIAL_ANUAL / PAGAS * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	COMPLEMENTO_NO_SALARIAL_MENSUAL("COMPLEMENTO_NO_SALARIAL_MENSUAL", "[03] COMPLEMENTO NO SALARIAL MENSUAL", "COMPL_NO_SALARIAL_MEN", "COMPL_NO_SALARIAL_MEN * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	COMPLEMENTO_NO_SALARIAL_DIARIO("COMPLEMENTO_NO_SALARIAL_DIARIO", "[03] COMPLEMENTO NO SALARIAL DIARIO", "COMPL_NO_SALARIAL_DIA", "COMPL_NO_SALARIAL_DIA * DIAS_TRABAJADOS", (byte)1),
	
	// ------------------------- PAGAS EXTRAS
	
	PAGAS_EXTRA_VERANO_Y_NAVIDAD_ANUAL("PAGAS_EXTRA_VERANO_Y_NAVIDAD_ANUAL", "[03] PAGAS EXTRA VERANO Y NAVIDAD ANUAL", "P_E_VERANO_Y_NAVIDAD_A", "P_E_VERANO_Y_NAVIDAD_A / PAGAS * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	
	PAGAS_EXTRA_VERANO_Y_NAVIDAD_MENSUAL("PAGAS_EXTRA_VERANO_Y_NAVIDAD_MENSUAL", "[03] PAGAS EXTRA VERANO Y NAVIDAD MENSUAL", "P_E_VERANO_Y_NAVIDAD_M", "P_E_VERANO_Y_NAVIDAD_M * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PAGA_EXTRA_VERANO_MENSUAL("PAGA_EXTRA_VERANO_MENSUAL", "[03] PAGAS EXTRA VERANO MENSUAL", "P_E_VERANO_M", "P_E_VERANO_M * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PAGA_EXTRA_NAVIDAD_MENSUAL("PAGA_EXTRA_NAVIDAD_MENSUAL", "[03] PAGAS EXTRA NAVIDAD MENSUAL", "P_E_NAVIDAD_M", "P_E_NAVIDAD_M * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PAGA_EXTRA_SIN_ANTIGUEDAD_MENSUAL("PAGA_EXTRA_SIN_ANTIGUEDAD_MENSUAL", "[03] PAGA EXTRA SIN ANTIGUEDAD MENSUAL", "P_EXTRA_SIN_ANTIGUEDAD_M", "P_EXTRA_SIN_ANTIGUEDAD_M * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PAGA_EXTRA_MARZO_MENSUAL("PAGA_EXTRA_MARZO_MENSUAL", "[03] PAGA EXTRA MARZO MENSUAL", "PAGA_EXTRA_MARZO", "PAGA_EXTRA_MARZO * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	
	// ------------------------- HORAS Y HORAS EXTRAS
	
	HORA_ORDINARIA_HORAS("HORA_ORDINARIA_HORAS", "[04] HORAS ORDINARIAS", "HORA_ORDINARIA", "HORA_ORDINARIA * HORAS_ORDINARIAS", (byte)2),
	HORA_EXTRA_HORAS("HORA_EXTRA_HORAS", "[04] HORAS EXTRAS", "HORA_EXTRA", "HORA_EXTRA * HORAS_EXTRAS", (byte)2),
	HORA_EXTRA_DOMINGOS_Y_FESTIVOS_HORAS("HORA_EXTRA_DOMINGOS_Y_FESTIVOS_HORAS", "[04] HORAS EXTRAS DOMINGOS Y FESTIVOS", "HORAS_EXTRAS_F", "HORAS_EXTRAS_F * H_E_FINDE_FESTIVOS", (byte)2),
	HORA_EXTRA_NOCTURNA_HORAS("HORA_EXTRA_NOCTURNA_HORAS", "[04] HORAS EXTRAS NOCTURNAS", "HORAS_EXTRAS_NOC", "HORAS_EXTRAS_NOC * HORAS_EXTRAS_NOCTURNAS", (byte)2),
	HORA_EXTRA_SIN_ANTIGUEDAD_HORAS("HORA_EXTRA_SIN_ANTIGUEDAD_HORAS", "[03] PAGA EXTRA SIN ANTIGUEDAD HORAS", "P_EXTRA_SIN_ANTIGUEDAD_H", "P_EXTRA_SIN_ANTIGUEDAD_H * HORAS_TRABAJADAS", (byte)1),
	
	HORA_EXTRA_1_QUINQUENIO_HORAS("HORA_EXTRA_1_QUINQUENIO_HORAS", "[04] HORA EXTRA 1 QUINQUENIO", "H_E_1_QUINQUENIO", "H_E_1_QUINQUENIO * HORAS_1_QUINQUENIO", (byte)2),
	HORA_EXTRA_2_QUINQUENIO_HORAS("HORA_EXTRA_2_QUINQUENIO_HORAS", "[04] HORA EXTRA 2 QUINQUENIO", "H_E_2_QUINQUENIO", "H_E_2_QUINQUENIO * HORAS_2_QUINQUENIO", (byte)2),
	HORA_EXTRA_3_QUINQUENIO_HORAS("HORA_EXTRA_3_QUINQUENIO_HORAS", "[04] HORA EXTRA 3 QUINQUENIO", "H_E_3_QUINQUENIO", "H_E_3_QUINQUENIO * HORAS_3_QUINQUENIO", (byte)2),
	HORA_EXTRA_4_QUINQUENIO_HORAS("HORA_EXTRA_4_QUINQUENIO_HORAS", "[04] HORA EXTRA 4 QUINQUENIO", "H_E_4_QUINQUENIO", "H_E_4_QUINQUENIO * HORAS_4_QUINQUENIO", (byte)2),
	
	// ------------------------- VACACIONES
	
	VACACIONES_MENSUAL("VACACIONES_MENSUAL", "[05] VACACIONES MENSUAL", "VACACIONES_MENSUAL", "VACACIONES_MENSUAL * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	
	// ------------------------- DIETAS
	GASTOS_PECNORTA_DIARIO("GASTOS_PECNORTA_DIARIO", "[43] GASTOS PERNOCTA DIARIO", "IMPORTE_PERNOCTA", "/*read-only*/IMPORTE_PERNOCTA * DIAS_PERNOCTA/**/", (byte)43),
	GASTOS_MANUTENCION_DIARIO("GASTOS_MANUTENCION_DIARIO", "[45] GASTOS MANUTENCION DIARIO", "IMPORTE_MANUTENCION", "/*read-only*/IMPORTE_MANUTENCION * DIAS_MANUTENCION/**/", (byte)45),
	GASTOS_LOCOMOCION_SIN_JUSTIFICANTE_DIARIO("GASTOS_LOCOMOCION_SIN_JUSTIFICANTE_DIARIO", "[50] GASTOS LOCOMOCIÓN SIN JUSTIFICANTE", "IMPORTE_KM", "/*read-only*/IMPORTE_KM * KMS/**/", (byte)50),
	
	DIETA_COMPLETA_DIARIO("DIETA_COMPLETA_DIARIO", "[06] DIETA_COMPLETA", "DIETA_COMPLETA", "DIETA_COMPLETA * DIAS_DIETA_COMPLETA", (byte)43),
	DIETA_COMPLETA_DESPL_MAS_100KMS_DIARIO("DIETA_COMPLETA_DESPL_MAS_100KMS_DIARIO", "[06] DIETA_COMPLETA > 100 KMS", "DIETA_COMPLETA_G_100", "DIETA_COMPLETA_G_100 * DIAS_DIETA_COMPLETA_G_100", (byte)43),
	DIETA_COMPLETA_DESPL_MENOS_100KMS_DIARIO("DIETA_COMPLETA_DESPL_MENOS_100KMS_DIARIO", "[06] DIETA_COMPLETA < 100 KMS", "DIETA_COMPLETA_L_100", "DIETA_COMPLETA_L_100 * DIAS_DIETA_COMPLETA_L_100", (byte)43),
	DIETA_PERNOCTA_DIARIO("DIETA_PERNOCTA_DIARIO", "[06] DIETA PERNOCTA", "DIETA_PERNOCTA", "DIETA_PERNOCTA * DIAS_DIETA_COMPLETA_PEC", (byte)43),
	DIETAS_DIARIO("DIETAS_DIARIO", "[06] DIETA DIARIO", "DIETA", "DIETA * DIAS_DIETA", (byte)43),
	DIETA_COMIDA_DIARIO("DIETA_COMIDA_DIARIO", "[06] DIETA COMIDA", "DIETA_COMIDA", "DIETA_COMIDA * DIAS_DIETA_COMIDA", (byte)43),
	
	MEDIA_DIETA_DIARIO("MEDIA_DIETA_DIARIO", "[06] MEDIA_DIETA", "MEDIA_DIETA", "MEDIA_DIETA * DIAS_MEDIA_DIETA", (byte)43),
	MEDIA_DIETA_DESPL_MAS_100KMS_DIARIO("MEDIA_DIETA_DESPL_MAS_100KMS_DIARIO", "[06] MEDIA_DIETA > 100 KMS", "MEDIA_DIETA_G_100", "MEDIA_DIETA_G_100 * DIAS_MEDIA_DIETA_G_100", (byte)43),
	MEDIA_DIETA_DESPL_MENOS_100KMS_DIARIO("MEDIA_DIETA_DESPL_MENOS_100KMS_DIARIO", "[06] MEDIA_DIETA < 100 KMS", "MEDIA_DIETA_L_100", "MEDIA_DIETA_L_100 * DIAS_MEDIA_DIETA_L_100", (byte)43),
	
	// ------------------------- INCENTIVOS
	
	INCENTIVOS_MENSUAL("INCENTIVOS_MENSUAL", "[07] INCENTIVOS MENSUALES", "INCENTIVOS_MENSUAL", "INCENTIVOS_MENSUAL * DIAS_TRABAJADOS / DIAS_MES", (byte)43),
	INCENTIVOS_DIARIO("INCENTIVOS_DIARIO", "[07] INCENTIVOS DIARIOS", "INCENTIVO_DIARIO", "INCENTIVO_DIARIO * DIAS_TRABAJADOS", (byte)43),
	INCENTIVOS_MARMOLERIAS_DIARIO("INCENTIVOS_MARMOLERIAS_DIARIO", "[07] INCENTIVOS MARMOLERIAS DIARIO", "INCENTIVOS_MARMOL_DIA", "INCENTIVOS_MARMOL_DIA * DIAS_TRABAJADOS", (byte)1),
	
	// ------------------------- INCENTIVOS
	
	GRATIFICACION_ANUAL("GRATIFICACION_ANUAL", "[08] GRATIFICACION ANUAL", "GRATIFICACION_ANUAL", "GRATIFICACION_ANUAL / PAGAS * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	
	COMPENSACIONES_MARMOLERIAS_MENSUAL("COMPENSACIONES_MARMOLERIAS_MENSUAL", "[09] COMPENSACIONES MARMOLERIAS MENSUAL", "COMP_MARMOLERIAS", "COMP_MARMOLERIAS * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	AYUDA_FAMILIA_NUMEROSA_MENSUAL("AYUDA_FAMILIA_NUMEROSA_MENSUAL", "[09] AYUDA FAMILIA NUMEROSA MENSUAL", "AYUDA_FAMILIA_NUM", "AYUDA_FAMILIA_NUM * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	QUEBRANDO_DE_MONEDA_MENSUAL("QUEBRANDO_DE_MONEDA_MENSUAL", "[09] QUEBRANDO DE MONEDA MENSUAL", "QUEBRANDO_MONEDA", "QUEBRANDO_MONEDA * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	COMPENSACIONES_MENSUAL("COMPENSACIONES_MENSUAL", "[09] COMPENSACIONES MENSUAL", "COMPENSACIONES", "COMPENSACIONES * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	PAGAS_EXTRA_MENSUAL("PAGAS_EXTRA_MENSUAL", "[09] PAGAS EXTRA MENSUAL", "PAGAS_EXTRA_MENSUAL", "PAGAS_EXTRA_MENSUAL * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	TURNICIDAD_MENSUAL("TURNICIDAD_MENSUAL", "[09] TURNICIDAD MENSUAL", "TURNICIDAD_MENSUAL", "TURNICIDAD_MENSUAL * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	TRIENIOS_MENSUAL("TRIENIOS_MENSUAL", "[09] TRIENIOS MENSUAL", "TRIENIOS_MENSUAL", "TRIENIOS_MENSUAL * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	BIENIOS_MENSUAL("BIENIOS_MENSUAL", "[09] BIENIOS MENSUAL", "BIENIOS_MENSUAL", "BIENIOS_MENSUAL * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	P_C_I__MENSUAL("P_C_I__MENSUAL", "[09] P.C.I", "PCI_MENUSAL", "PCI_MENUSAL * DIAS_TRABAJADOS / DIAS_MES", (byte)1),
	
	DIETA_KILOMETRAJE_HORAS("DIETA_KILOMETRAJE_HORAS", "[09] DIETA KILOMETRAJE", "DIETA_KILOMETRAJE_H", "DIETA_KILOMETRAJE_H * HORAS_TRABAJADAS", (byte)1),
	
	RETRIBUCION_EN_ESPECIE_MENSUAL("RETRIBUCION_EN_ESPECIE_MENSUAL", "[30] RETRIBUCION EN ESPECIE", "RETRIBUCION_ESPECIE", "RETRIBUCION_ESPECIE", (byte)13),
	COMPLEMENTO_PERSONAL_DE_ANTIGUEDAD_MENSUAL("COMPLEMENTO_PERSONAL_DE_ANTIGUEDAD_MENSUAL", "[40] COMPLEMENTO PERSONAL DE ANTIGÜEDAD", "IMPORTE_ANTIGUEDAD", "INPUT(\"/*user*/IMPORTE_ANTIGUEDAD/**/\",ANTIGUEDAD_HELP)", (byte)1),
	
	;
	
	private String name;
	private String normalizeName;
	private String conceptCode;
	private String expression;
	private byte type;
	
	private AgreementPayment(String name, String normalizeName, String conceptCode, String expression, byte type) {
		this.name = name;
		this.normalizeName = normalizeName;
		this.conceptCode = conceptCode;
		this.expression = expression;
		this.type = type;
	}
	
	public static AgreementPayment safeValueOf(String name) {
		if (AonStringUtils.isBlank(name)) {
			return null;
		}
		try {
			return AgreementPayment.valueOf(name);
		} catch (IllegalArgumentException e) {
			return null;
		}
	}

	public String getName() {
		return name;
	}
	
	public String getNormalizeName() {
		return normalizeName;
	}

	public String getConceptCode() {
		return conceptCode;
	}

	public String getExpression() {
		return expression;
	}
	
	public byte getType() {
		return type;
	}
	
	public static void main(String[] args) {
		for(int i=0; i < AgreementPayment.values().length; i++) {
			System.out.println("put(\"" + AgreementPayment.values()[i].name + "\", \"" + AgreementPayment.values()[i].getConceptCode() + "\");");
		}
	}
	
}
