bgcolor_color_de_fondo = #ffffff
bgcolor_color_de_fondo_pie = #ffffff
color_color_de_texto = #000000
color_color_borde = #cccccc
font_fuente = 3
size_tamano_de_fuente = 12
border_tamano_bordes =1
color_color_de_texto_menu = #000000
size_tamano_de_fuente_menu = 13
color_color_de_texto_pie = #000000
color_color_de_texto_contenido = #ffffff