<?xml version="1.0"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<parent>
		<groupId>com.code.aon</groupId>
		<artifactId>aon.web.parent</artifactId>
		<version>6.14.1</version>
	</parent>
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.code.aon</groupId>
	<artifactId>aon-project</artifactId>
	<packaging>war</packaging>
	<version>6.14.1</version>
	<description>AON WEB PROJECT</description>
	<name>AON WEB PROJECT</name>
	<build>
		<finalName>aon-project</finalName>
		<plugins>
			<!-- Para construir el RPM -->
                       <plugin>
                                <groupId>org.codehaus.mojo</groupId>
                                <artifactId>rpm-maven-plugin</artifactId>
                       </plugin>
		</plugins>
	</build>
	<dependencies>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.rich.components</artifactId>
			<version>${pom.version}</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.security.bridge</artifactId>
			<version>${pom.version}</version>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.form</artifactId>
			<version>${pom.version}</version>
			<scope>compile</scope>
		</dependency>			
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.audit</artifactId>
			<version>${pom.version}</version>
			<scope>compile</scope>
		</dependency>				
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.company</artifactId>
			<version>${pom.version}</version>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.config</artifactId>
			<version>${pom.version}</version>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.geozone</artifactId>
			<version>${pom.version}</version>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.groupware</artifactId>
			<version>${pom.version}</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.registry</artifactId>
			<version>${pom.version}</version>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.report</artifactId>
			<version>${pom.version}</version>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.resources</artifactId>
			<version>${pom.version}</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.stat</artifactId>
			<version>${pom.version}</version>
			<scope>compile</scope>
		</dependency>
	</dependencies>
</project>

