# COMÚN
tipoDocumento_0=NIF 
tipoDocumento_1=CIF
tipoDocumento_2=NIE
tipoDocumento_3=PASAPORTE
tipoDocumento_4=PERMISO TRABAJO
tipoDocumento_5=OTROS

transaccion_0=NACIONAL
transaccion_1=INTRACOMUNITARIO
transaccion_2=EXTRACOMUNITARIO
transaccion_3=CANARIAS, CEUTA y MELILLA

tipo_0=Venta
tipo_1=Compra
tipo_2=Gasto
tipo_3=Gasto no deducible

tipoDeduccionIva_0=Con derecho a deducción
tipoDeduccionIva_1=Sin derecho a deducción
tipoDeduccionIva_2=No sujeto

tipoIrpf_0=Profesionales
tipoIrpf_1=Arrendamiento
tipoIrpf_2=Capital Mobiliario
tipoIrpf_3=Agricultura
tipoIrpf_4=Transporte

pago_0=Cobro
pago_1=Pago

inversion_0=Si
inversion_1=No

retencion_0=Si
retencion_1=No

re_0=Si
re_1=No

facturarAlbaranesAgrupados_0=Si
facturarAlbaranesAgrupados_1=No

# CLIENTES
CustomerLoaderFactory=Clientes
CustomerLoaderFactory_id=Identificador único del cliente. Válido para realizar referencias dentro del fichero de carga. 
CustomerLoaderFactory_razonSocial=Razón social del cliente.
CustomerLoaderFactory_alias=Alias del cliente .
CustomerLoaderFactory_tipoDocumento=Tipo de documento identificativo del cliente.
CustomerLoaderFactory_paisDocumento=Pais de expedición del documento. Será un valor válido según el código estándar ISO 3166-1.
CustomerLoaderFactory_documento=Documento identificativo del cliente.
CustomerLoaderFactory_nacionalidad=Nacionalidad del cliente. Será un valor válido según el código estándar ISO 3166-1.
CustomerLoaderFactory_cuenta=Código de cuenta contable.
CustomerLoaderFactory_re=Inscrito en el regimen de recargo de equivalencia.
CustomerLoaderFactory_transaccion=Tipo de transacción. 
CustomerLoaderFactory_retencion=Indica si se ha de aplicar retención al cliente.
CustomerLoaderFactory_facturarAlbaranesAgrupados=Cuando se facturen albaranes, si se deben agrupar en una única factura.
CustomerLoaderFactory_tipoVia=Abreviatura del tipo de vía. 
CustomerLoaderFactory_direccion=Nombre de la calle, via, plaza, etc ...
CustomerLoaderFactory_numero=Número de la calle, via, plaza, etc ...
CustomerLoaderFactory_direccion2=Complementos de la dirección.
CustomerLoaderFactory_direccion3=Complementos de la dirección.
CustomerLoaderFactory_cp=Código postal.
CustomerLoaderFactory_ciudad=Ciudad.
CustomerLoaderFactory_provincia=Código de provincia.
CustomerLoaderFactory_nombreProvincia=Nombre de la provincia.
CustomerLoaderFactory_pais=Pais. Será un valor válido según el código estándar ISO 3166-1.
CustomerLoaderFactory_telefono1=Primer teléfono.
CustomerLoaderFactory_telefono2=Segundo teléfono.
CustomerLoaderFactory_fax=Fax.
CustomerLoaderFactory_email=Dirección de correo electrónico.
CustomerLoaderFactory_web=Dirección de la página web.
CustomerLoaderFactory_banco=Nombre del banco del cliente.
CustomerLoaderFactory_cuentaBanco=Cuenta del banco, en formato "XXXX.XXXX.XX.XXXXXXXXXX".
CustomerLoaderFactory_formaPago=Forma de Pago.
CustomerLoaderFactory_numeroVtos=Número de vencimientos, para la generación automática de vencimientos.
CustomerLoaderFactory_diasAlPrimerVto=Dias al primer vencimiento, para la generación automática de vencimientos.
CustomerLoaderFactory_diasEntreVtos=Dias entre vencimientos, para la generación automática de vencimientos.
CustomerLoaderFactory_diasPago=Dias de pago, para la generación automática de vencimientos. Formato "XX XX XX".

# ACREEDORES
CreditorLoaderFactory=Acreedores
CreditorLoaderFactory_id=Identificador único del acreedor. Válido para realizar referencias dentro del fichero de carga.
CreditorLoaderFactory_razonSocial=Razón social del acreedor.
CreditorLoaderFactory_alias=Alias del acreedor.
CreditorLoaderFactory_tipoDocumento=Tipo de documento identificativo del acreedor.
CreditorLoaderFactory_paisDocumento=Pais de expedición del documento. Será un valor válido según el código estándar ISO 3166-1.
CreditorLoaderFactory_documento=Documento identificativo del acreedor.
CreditorLoaderFactory_nacionalidad=Nacionalidad del acreedor. Será un valor válido según el código estándar ISO 3166-1.
CreditorLoaderFactory_cuenta=Código de cuenta contable.
CreditorLoaderFactory_transaccion=Tipo de transacción.
CreditorLoaderFactory_retencion=Indica si se ha de aplicar retención al acreedor.
CreditorLoaderFactory_tipoVia=Abreviatura del tipo de vía.
CreditorLoaderFactory_direccion=Nombre de la calle, via, plaza, etc ...
CreditorLoaderFactory_numero=Número de la calle, via, plaza, etc ...
CreditorLoaderFactory_direccion2=Complementos de la dirección
CreditorLoaderFactory_direccion3=Complementos de la dirección
CreditorLoaderFactory_cp=Código postal.
CreditorLoaderFactory_ciudad=Ciudad.
CreditorLoaderFactory_provincia=Código de provincia.
CreditorLoaderFactory_nombreProvincia=Nombre de la provincia.
CreditorLoaderFactory_pais=Pais. Será un valor válido según el código estándar ISO 3166-1.
CreditorLoaderFactory_telefono1=Primer teléfono.
CreditorLoaderFactory_telefono2=Segundo teléfono.
CreditorLoaderFactory_fax=Fax.
CreditorLoaderFactory_email=Dirección de correo electrónico.
CreditorLoaderFactory_web=Dirección de la página web.
CreditorLoaderFactory_banco=Nombre del banco del acreedor.
CreditorLoaderFactory_cuentaBanco=Cuenta del banco, en formato "XXXX.XXXX.XX.XXXXXXXXXX".
CreditorLoaderFactory_formaPago=Forma de Pago.
CreditorLoaderFactory_numeroVtos=Número de vencimientos, para la generación automática de vencimientos.
CreditorLoaderFactory_diasAlPrimerVto=Dias al primer vencimiento, para la generación automática de vencimientos.
CreditorLoaderFactory_diasEntreVtos=Dias entre vencimientos, para la generación automática de vencimientos.
CreditorLoaderFactory_diasPago=Dias de pago, para la generación automática de vencimientos. Formato "XX XX XX".

SupplierLoaderFactory=Proveedores
SupplierLoaderFactory_id=Identificador único del proveedor. Válido para realizar referencias dentro del fichero de carga.
SupplierLoaderFactory_razonSocial=Razón social del proveedor.
SupplierLoaderFactory_alias=Alias del proveedor.
SupplierLoaderFactory_tipoDocumento=Tipo de documento identificativo del proveedor.
SupplierLoaderFactory_paisDocumento=Pais de expedición del documento. Será un valor válido según el código estándar ISO 3166-1.
SupplierLoaderFactory_documento=Documento identificativo del proveedor.
SupplierLoaderFactory_nacionalidad=Nacionalidad del proveedor. Será un valor válido según el código estándar ISO 3166-1.
SupplierLoaderFactory_cuenta=Código de cuenta contable.
SupplierLoaderFactory_transaccion=Tipo de transacción.
SupplierLoaderFactory_retencion=Indica si se ha de aplicar retención al proveedor.
SupplierLoaderFactory_tipoVia=Abreviatura del tipo de vía.
SupplierLoaderFactory_direccion=Nombre de la calle, via, plaza, etc ...
SupplierLoaderFactory_numero=Número de la calle, via, plaza, etc ...
SupplierLoaderFactory_direccion2=Complementos de la dirección.
SupplierLoaderFactory_direccion3=Complementos de la dirección.
SupplierLoaderFactory_cp=Código postal.
SupplierLoaderFactory_ciudad=Ciudad.
SupplierLoaderFactory_provincia=Código de provincia.
SupplierLoaderFactory_nombreProvincia=Nombre de la provincia.
SupplierLoaderFactory_pais=Pais. Será un valor válido según el código estándar ISO 3166-1.
SupplierLoaderFactory_telefono1=Primer teléfono.
SupplierLoaderFactory_telefono2=Segundo teléfono.
SupplierLoaderFactory_fax=Fax.
SupplierLoaderFactory_email=Dirección de correo electrónico.
SupplierLoaderFactory_web=Dirección de la página web.
SupplierLoaderFactory_banco=Nombre del banco del proveedor.
SupplierLoaderFactory_cuentaBanco=Cuenta del banco, en formato "XXXX.XXXX.XX.XXXXXXXXXX".
SupplierLoaderFactory_formaPago=Forma de Pago.
SupplierLoaderFactory_numeroVtos=Número de vencimientos, para la generación automática de vencimientos.
SupplierLoaderFactory_diasAlPrimerVto=Dias al primer vencimiento, para la generación automática de vencimientos.
SupplierLoaderFactory_diasEntreVtos=Dias entre vencimientos, para la generación automática de vencimientos.
SupplierLoaderFactory_diasPago=Dias de pago, para la generación automática de vencimientos. Formato "XX XX XX".

# CLIENTES POTENCIALES
TargetLoaderFactory=Clientes Potenciales
TargetLoaderFactory_id=Identificador único del cliente potencial. Válido para realizar referencias dentro del fichero de carga. 
TargetLoaderFactory_razonSocial=Razón social del cliente potencial.
TargetLoaderFactory_alias=Alias del cliente potencial .
TargetLoaderFactory_tipoDocumento=Tipo de documento identificativo del cliente potencial.
TargetLoaderFactory_paisDocumento=Pais de expedición del documento. Será un valor válido según el código estándar ISO 3166-1.
TargetLoaderFactory_documento=Documento identificativo del cliente potencial.
TargetLoaderFactory_nacionalidad=Nacionalidad del cliente potencial. Será un valor válido según el código estándar ISO 3166-1.
TargetLoaderFactory_re=Inscrito en el regimen de recargo de equivalencia.
TargetLoaderFactory_transaccion=Tipo de transacción. 
TargetLoaderFactory_retencion=Indica si se ha de aplicar retención al cliente potencial.
TargetLoaderFactory_tipoVia=Abreviatura del tipo de vía. 
TargetLoaderFactory_direccion=Nombre de la calle, via, plaza, etc ...
TargetLoaderFactory_numero=Número de la calle, via, plaza, etc ...
TargetLoaderFactory_direccion2=Complementos de la dirección.
TargetLoaderFactory_direccion3=Complementos de la dirección.
TargetLoaderFactory_cp=Código postal.
TargetLoaderFactory_ciudad=Ciudad.
TargetLoaderFactory_provincia=Código de provincia.
TargetLoaderFactory_nombreProvincia=Nombre de la provincia.
TargetLoaderFactory_pais=Pais. Será un valor válido según el código estándar ISO 3166-1.
TargetLoaderFactory_telefono1=Primer teléfono.
TargetLoaderFactory_telefono2=Segundo teléfono.
TargetLoaderFactory_fax=Fax.
TargetLoaderFactory_email=Dirección de correo electrónico.
TargetLoaderFactory_web=Dirección de la página web.
TargetLoaderFactory_banco=Nombre del banco del cliente potencial.
TargetLoaderFactory_cuentaBanco=Cuenta del banco, en formato "XXXX.XXXX.XX.XXXXXXXXXX".
TargetLoaderFactory_formaPago=Forma de Pago.
TargetLoaderFactory_numeroVtos=Número de vencimientos, para la generación automática de vencimientos.
TargetLoaderFactory_diasAlPrimerVto=Dias al primer vencimiento, para la generación automática de vencimientos.
TargetLoaderFactory_diasEntreVtos=Dias entre vencimientos, para la generación automática de vencimientos.
TargetLoaderFactory_diasPago=Dias de pago, para la generación automática de vencimientos. Formato "XX XX XX".

FinanceLoaderFactory=Vencimientos
FinanceLoaderFactory_id=Identificador único del vencimiento. 
FinanceLoaderFactory_factura=Identificador, en el fichero de carga, de la factura a la cual pertenece el vencimiento.
FinanceLoaderFactory_pago=Indica si se trata de un cobro o de un pago.
FinanceLoaderFactory_idTitular=Identificador, en el fichero de carga, del titular al cual pertenece el vencimiento.
FinanceLoaderFactory_tipoDocumento=Tipo de documento identificativo del titular del vencimiento.
FinanceLoaderFactory_paisDocumento=Pais de expedición del documento. Será un valor válido según el código estándar ISO 3166-1.
FinanceLoaderFactory_documento=Documento identificativo del titular del vencimiento.
FinanceLoaderFactory_razonSocial=Razón social del titular del vencimiento.
FinanceLoaderFactory_importe=Importe del vencimiento.
FinanceLoaderFactory_concepto=Concepto del vencimiento.
FinanceLoaderFactory_fechaVto=Fecha del vencmiento.
FinanceLoaderFactory_formaPago=Forma de Pago.
FinanceLoaderFactory_cuentaBanco=Cuenta del banco, en formato "XXXX.XXXX.XX.XXXXXXXXXX".
FinanceLoaderFactory_cuenta=Código de cuenta contable del titular del vencimiento.

InvoiceLoaderFactory=Facturas
InvoiceLoaderFactory_id=Identificador único de la factura. Válido para realizar referencias dentro del fichero de carga.
InvoiceLoaderFactory_serie=Serie de la factura.
InvoiceLoaderFactory_numero=Número de la factura.
InvoiceLoaderFactory_referencia=Número de referencia de la factura.
InvoiceLoaderFactory_idTitular=Identificador, en el fichero de carga, del titular al cual pertenece el vencimiento.
InvoiceLoaderFactory_cuenta=Código de cuenta contable del titular de la factura.
InvoiceLoaderFactory_documento=Documento identificativo del titular de la factura.
InvoiceLoaderFactory_tipoDocumento=Tipo de documento identificativo del titular de la factura.
InvoiceLoaderFactory_paisDocumento=Pais de expedición del documento. Será un valor válido según el código estándar ISO 3166-1.
InvoiceLoaderFactory_razonSocial=Razón social del titular de la factura.
InvoiceLoaderFactory_fechaFactura=Fecha de la factura.
InvoiceLoaderFactory_fechaIva=Fecha de la factura para tratamiento del IVA.
InvoiceLoaderFactory_tipo=Tipo de factura.
InvoiceLoaderFactory_inversion=Indica si se trata de una inversión.
InvoiceLoaderFactory_transaccion=Tipo de transacción.
InvoiceLoaderFactory_comentario=Comentario.
InvoiceLoaderFactory_baseImponible=Base Imponible de la factura.
InvoiceLoaderFactory_totalCuotaIVA=Total cuota de IVA de la factura.
InvoiceLoaderFactory_totalCuotaIRPF=Total cuota de retención IRPF de la factura.
InvoiceLoaderFactory_totalFactura=Total factura.

InvoiceDetailLoaderFactory=Líneas de Facturas
InvoiceDetailLoaderFactory_factura=Identificador, en el fichero de carga, de la factura a la cual pertenece la línea de factura.
InvoiceDetailLoaderFactory_linea=Número de línea.
InvoiceDetailLoaderFactory_articulo=Identificador del artículo.
InvoiceDetailLoaderFactory_concepto=Concepto de la línea de factura.
InvoiceDetailLoaderFactory_cantidad=Cantidad.
InvoiceDetailLoaderFactory_precio=Precio.
InvoiceDetailLoaderFactory_baseImponible=Base Imponible de la línea.
InvoiceDetailLoaderFactory_porcentajeIva=Porcentaje de IVA que se aplica en la línea.
InvoiceDetailLoaderFactory_cuotaIva=Cuota de IVA de la línea de factura.
InvoiceDetailLoaderFactory_re=Porcentaje de RE que se aplica en la línea.
InvoiceDetailLoaderFactory_cuotaRe=Cuota de RE de la línea de factura.
InvoiceDetailLoaderFactory_porcentajeIrpf=Porcentaje de retención IRPF que se aplica en la línea.
InvoiceDetailLoaderFactory_cuotaIrpf=Cuota de retención IRPF de la línea de factura.
InvoiceDetailLoaderFactory_tipoDeduccionIva=Calificador del IVA aplicado en la línea.
InvoiceDetailLoaderFactory_tipoIrpf=Calificador de la retención IRPF aplicada en la línea.
InvoiceDetailLoaderFactory_cuenta=Código de cuenta contable de ventas, ingresos, compras o gastos.
InvoiceDetailLoaderFactory_cuentaIva=Código de cuenta contable para la cuota de IVA.
InvoiceDetailLoaderFactory_cuentaIrpf=Código de cuenta contable para la cuota de retención IRPF.

AccountEntryLoaderFactory=Asientos
AccountEntryLoaderFactory_id=Identificador único del asiento. Válido para realizar referencias dentro del fichero de carga.
AccountEntryLoaderFactory_diaro=Número de diario.
AccountEntryLoaderFactory_fecha=Fecha del asiento.
AccountEntryLoaderFactory_comentario

AccountEntryDetailLoaderFactory=Apuntes (Líneas de asientos)
AccountEntryDetailLoaderFactory_id=Identificador único del apunte. Válido para realizar referencias dentro del fichero de carga.
AccountEntryDetailLoaderFactory_asiento=Identificador, en el fichero de carga, del asiento al cual pertenece el apunte.
AccountEntryDetailLoaderFactory_fechaAsiento=Fecha del asiento.
AccountEntryDetailLoaderFactory_cuenta=Código de cuenta contable.
AccountEntryDetailLoaderFactory_descripcionCuenta=Descripción de la cuenta contable.
AccountEntryDetailLoaderFactory_concepto=Concepto.
AccountEntryDetailLoaderFactory_documento=Numero de documento (factura).
AccountEntryDetailLoaderFactory_debe=Importe del debe.
AccountEntryDetailLoaderFactory_haber=Importe del haber.
AccountEntryDetailLoaderFactory_contrapartida=Código de cuenta contable para la contrapartida.
AccountEntryDetailLoaderFactory_descripcionContrapartida=Descripción de la cuenta contable de la contrapartida.

