<!--
	Esquema de datos del modelo 420. En las anotaciones de los atributos se informa 
	de aquellos que debeADIn quedar cumplimentados de forma obligatoria en el esquema, 
	a pesar de ser opcionales. Estos atributos serán completados por el programa.
-->
<?xml version="1.0" encoding="ISO-8859-1"?>
<xs:schema id="Modelo420DataSet" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<!--
		La siguiente forma de referenciar el XSD, con las definiciones de los elementos comunes  a  todos
		los modelos, permite acceder a dicho fichero desde el JAR generado. Pero para poder  ejecutar  el
		modelo internamente (Eclipse) necesitaremso tener dicho esquema situado en este mismo  directorio
		o definir un enlace simbólico que permita acceder al mismo en la ubicación de "pa-tributos". Este
		último es el mecanismo que hemos utilizado hasta ahora. 
	
				<xs:include schemaLocation="Comunes_Presentacion.xsd"/> 
	-->
	
	<xs:include schemaLocation="Comunes_Presentacion.xsd"/>
	
	<xs:element name="DEC">
		<xs:complexType>
			<xs:annotation>
				<xs:documentation>
					Nodo principal de la declaración.
    			</xs:documentation>
			</xs:annotation>
			<xs:sequence>
				
				<!-- El elemento AUX es cumplimentado por el programa -->
				<xs:element name="AUX" type="T_AUXILIAR" maxOccurs="1" minOccurs="0"/>
				
				<xs:element name="IDE" type="T_IDENT_IGIC" maxOccurs="1" minOccurs="1">
					<xs:annotation>
						<xs:documentation>
							Datos identificativos y opciones tributarias.
							Los atributos de opciones tributarias relevantes en el  
							modelo 420 son ACO, RECC, DRECC, EOP, ACR, FAC y TAC.
						</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="IGI_DEV" maxOccurs="1" minOccurs="0" type="T_DEVENGADO">
					<xs:annotation>
						<xs:documentation>IGIC devengado</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="IGI_DED"  maxOccurs="1" minOccurs="0" type="T_DEDUCIBLE">
					<xs:annotation>
						<xs:documentation>
							IGIC deducible
						</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="LIQ" type="T_LIQUIDACION" maxOccurs="1" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Liquidación</xs:documentation>
					</xs:annotation>
        			</xs:element>
				<xs:element name="RES" minOccurs="1" maxOccurs="1" type="RESULTADO_LIQUIDACION">
					<xs:annotation>
						<xs:documentation>Resultado de la declaración</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="ADI" type="T_INFO_ADICIONAL" maxOccurs="1" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Información adicional</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="RCC" type="T_OPERACIONES_RECC" maxOccurs="1" minOccurs="0">
					<xs:annotation>
						<xs:documentation>
							Datos exclusivos para sujetos acogidos al régimen especial
							de criterio de caja y/o destinatarios de operaciones afectadas
							por el mismo.
						</xs:documentation>
					</xs:annotation>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="NDE" type="xs:string">
				<xs:annotation>
					<xs:documentation>
						Atributo cumplimentado por el programa.
						Tiene carácter interno obligatorio.
						Número de identificación electrónica de la declaración equivalente
						al número de justificante. 
    				</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="MOD" type="xs:string" use="required">
				<xs:annotation>
					<xs:documentation>
						Identificador del modelo.
    				</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="ANY" use="required">
				<xs:annotation>
					<xs:documentation>
						Ejercicio al que se refiere la autoliquidación.
						Formato	String(4).
    				</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:length value="4"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="PER" use="required">
				<xs:annotation>
					<xs:documentation>
						Período al que se refiere la autoliquidación.
						Formato String(2): 
							Primer trimestre:  1T
							Segundo trimestre: 2T
							Tercer trimestre:  3T
							Cuarto trimestre:  4T
    				</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:length value="2"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="FIM">
				<xs:annotation>
					<xs:documentation>
						Atributo cumplimentado por el programa.
						Tiene carácter interno obligatorio.
						Fecha de impresión/generación de la declaración
						según el cliente del programa de ayuda.
    				</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:length value="8"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="COM" use="optional">
				<xs:annotation>
					<xs:documentation>
						Se establece con "X" cuando esta autoliquidación sea complementaria
						de otra u otras autoliquidaciones presentadas anteriormente por el
						mismo concepto y correspondientes al mismo ejercicio y período.
    				</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="X"/>
						<xs:enumeration value=""/>
						<xs:minLength value="0"/>
						<xs:maxLength value="1"/>						
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="NJA" type="xs:string" use="optional">
				<xs:annotation>
					<xs:documentation>
						Para una declaración complementaria se declara el
						número anterior de justificante.
    				</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="VER" type="xs:string">
				<xs:annotation>
					<xs:documentation>
						Atributo cumplimentado por el programa.
						Versión del programa de ayuda con la que se generó el XML.
					</xs:documentation>
				</xs:annotation>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
</xs:schema>