bgcolor_color_de_fondo = #1e2a06
bgcolor_color_de_fondo_cabecera = #1e2a06
bgcolor_color_de_fondo_menu = #1e2a06
bgcolor_color_de_fondo_pie = #1e2a06
color_color_de_texto = #FFFF00
font_fuente = 3
size_tamano_de_fuente = 11
color_color_de_texto_menu = #999900
color_color_de_texto_pie = #999900
size_tamano_de_fuente_menu = 14
color_color_de_texto_contenido = #5c7c1f