<?xml version="1.0"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<parent>
		<groupId>com.code.aon</groupId>
		<artifactId>aon.parent</artifactId>
		<version>8.57</version>
	</parent>
	<modelVersion>4.0.0</modelVersion>
	<artifactId>aon.jaas</artifactId>
	<description>AON JAAS</description>
	<name>AON JAAS</name>
	<dependencies>
		<dependency>
		    <groupId>com.code.aon</groupId>
		    <artifactId>aon.pool</artifactId>
			<version>${project.version}</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
		    <groupId>commons-dbutils</groupId>
		    <artifactId>commons-dbutils</artifactId>
		    <version>1.5</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>commons-lang</groupId>
			<artifactId>commons-lang</artifactId>
			<version>2.5</version>
			<scope>compile</scope>
		</dependency>
	    <dependency>
	      <groupId>org.apache.tomcat</groupId>
	      <artifactId>tomcat-catalina</artifactId>
	      <version>8.0.30</version>
	      <scope>provided</scope>
	    </dependency>
		<dependency>
			<groupId>org.jboss.slf4j</groupId>
			<artifactId>slf4j-jboss-logging</artifactId>
			<version>1.0.2.GA</version>
			<scope>provided</scope>
			<exclusions>
				<exclusion>
					<groupId>org.jboss.logging</groupId>
					<artifactId>jboss-logging-spi</artifactId>
				</exclusion>
			</exclusions>
		</dependency>		
	</dependencies>
</project>
 
