//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.03.31 at 11:57:12 AM CEST 
//


package com.esferalia.aon.ui.payroll.utils.contractMojo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Datos de los contratos de interinidad.
 * 
 * <p>Java class for DATOS_CONTRATOINTERINIDADTYPE complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DATOS_CONTRATOINTERINIDADTYPE">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CAUSA_INTERINIDAD">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;length value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DATOS_CONTRATOINTERINIDADTYPE", propOrder = {
    "causainterinidad"
})
public class DATOSCONTRATOINTERINIDADTYPE {

    @XmlElement(name = "CAUSA_INTERINIDAD", required = true)
    protected String causainterinidad;

    /**
     * Gets the value of the causainterinidad property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCAUSAINTERINIDAD() {
        return causainterinidad;
    }

    /**
     * Sets the value of the causainterinidad property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCAUSAINTERINIDAD(String value) {
        this.causainterinidad = value;
    }

}
