<?xml version="1.0"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<parent>
		<groupId>com.code.aon</groupId>
		<artifactId>aon.web.parent</artifactId>
		<version>6.73</version>
		<relativePath>../aon-web-parent</relativePath>
	</parent>
	<modelVersion>4.0.0</modelVersion>
	<artifactId>aon-gt</artifactId>
	<packaging>war</packaging>
	<description>AON WEB GTA (gt revision)</description>
	<name>AON WEB GTA (gt revision)</name>
	<properties>
		<dbVersion>5.0.0</dbVersion>
	</properties>
	<build>
		<finalName>aon-gt</finalName>
		<plugins>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>jasperreports-maven-plugin</artifactId>
				<version>${jasperreportsMavenPluginVersion}</version>
				<configuration>
					<outputDirectory>${project.build.directory}/classes/com/code/aon/web/gta/report</outputDirectory>
					<xmlValidation>true</xmlValidation>
					<compiler>${jasperreportsMavenPluginCompiler}</compiler>
				</configuration>
				<executions>
					<execution>
						<phase>compile</phase>
						<goals>
							<goal>compile-reports</goal>
						</goals>
					</execution>
				</executions>
				<dependencies>
					<dependency>
						<groupId>net.sf.jasperreports</groupId>
						<artifactId>${jasperReportsArtifact}</artifactId>
						<version>${jasperReportsVersion}</version>
					</dependency>
					<dependency>
						<groupId>org.slf4j</groupId>
						<artifactId>slf4j-jcl</artifactId>
						<version>1.5.11</version>
					</dependency>
                                        <dependency>
                                                <groupId>com.code.aon</groupId>
                                                <artifactId>aon.ui.finance</artifactId>
                                                <version>${project.version}</version>
                                        </dependency>
 				</dependencies>
			</plugin>
			
			<!-- Para construir el RPM -->
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>rpm-maven-plugin</artifactId>
				<version>2.0.1</version>
			</plugin>
		</plugins>
		<pluginManagement>
			<plugins>
				<!--This plugin's configuration is used to store Eclipse m2e settings 
					only. It has no influence on the Maven build itself. -->
				<plugin>
					<groupId>org.eclipse.m2e</groupId>
					<artifactId>lifecycle-mapping</artifactId>
					<version>1.0.0</version>
					<configuration>
						<lifecycleMappingMetadata>
							<pluginExecutions>
								<pluginExecution>
									<pluginExecutionFilter>
										<groupId>org.codehaus.mojo</groupId>
										<artifactId>jasperreports-maven-plugin</artifactId>
										<versionRange>
											[1.0-beta-2,)
										</versionRange>
										<goals>
											<goal>compile-reports</goal>
										</goals>
									</pluginExecutionFilter>
									<action>
										<ignore />
									</action>
								</pluginExecution>
							</pluginExecutions>
						</lifecycleMappingMetadata>
					</configuration>
				</plugin>
			</plugins>
		</pluginManagement>
	</build>
	<dependencies>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.rich.components</artifactId>
			<version>${project.version}</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.security.bridge</artifactId>
			<version>${project.version}</version>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.form</artifactId>
			<version>${project.version}</version>
			<scope>compile</scope>
		</dependency>			
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.report</artifactId>
			<version>${project.version}</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.resources</artifactId>
			<version>${project.version}</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.account</artifactId>
			<version>${project.version}</version>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.audit</artifactId>
			<version>${project.version}</version>
			<scope>compile</scope>
		</dependency>		
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.account.bridge</artifactId>
			<version>${project.version}</version>
			<scope>runtime</scope>
		</dependency>
 
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.audabridge</artifactId>
			<version>${project.version}</version>
			<scope>runtime</scope>
		</dependency>

		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.commercial</artifactId>
			<version>${project.version}</version>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.company</artifactId>
			<version>${project.version}</version>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.config</artifactId>
			<version>${project.version}</version>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.db.manager</artifactId>
			<version>${project.version}</version>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.finance</artifactId>
			<version>${project.version}</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.geozone</artifactId>
			<version>${project.version}</version>
			<scope>runtime</scope>
		</dependency>
 		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.product</artifactId>
			<version>${project.version}</version>
			<scope>runtime</scope>
		</dependency>
 		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.project</artifactId>
			<version>${project.version}</version>
			<scope>runtime</scope>
		</dependency>
 		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.purchase</artifactId>
			<version>${project.version}</version>
			<scope>runtime</scope>
		</dependency>
 		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.registry</artifactId>
			<version>${project.version}</version>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.sales</artifactId>
			<version>${project.version}</version>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.stat</artifactId>
			<version>${project.version}</version>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.supplier</artifactId>
			<version>${project.version}</version>
			<scope>runtime</scope>
		</dependency>	
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.tas</artifactId>
			<version>${project.version}</version>
			<scope>compile</scope>
		</dependency>	
	    <dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.warehouse</artifactId>
			<version>${project.version}</version>
			<scope>runtime</scope>
		</dependency>
	</dependencies>
</project>
 
