<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="urn:lroe-pj-subvenciones-entidades-publicas:anulacion-peticion"
	xmlns:lrpjsepap="urn:lroe-pj-subvenciones-entidades-publicas:anulacion-peticion"
	xmlns:tiposcomplejos="https://www.batuz.eus/fitxategiak/batuz/LROE/esquemas/batuz_TiposComplejos.xsd"
	xmlns:tiposanulacion="https://www.batuz.eus/fitxategiak/batuz/LROE/esquemas/batuz_TiposAnulacion.xsd">

	<import namespace="https://www.batuz.eus/fitxategiak/batuz/LROE/esquemas/batuz_TiposComplejos.xsd" schemaLocation="batuz_TiposComplejos.xsd"/>
	<import namespace="https://www.batuz.eus/fitxategiak/batuz/LROE/esquemas/batuz_TiposAnulacion.xsd" schemaLocation="batuz_TiposAnulacion.xsd"/>

	<element name="LROEPJ240SubvencionesEntidadesPublicasAnulacionPeticion">
		<complexType>
			<sequence>
				<element name="Cabecera" type="tiposcomplejos:Cabecera240Type"/>
				<element name="SubvencionesEntidadesPublicas" type="tiposanulacion:AnulacionesSubvencionesEntidadesPublicasType"/>
			</sequence>
		</complexType>
	</element>
</schema>