<?xml version="1.0"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<parent>
		<groupId>com.code.aon</groupId>
		<artifactId>aon.parent</artifactId>
		<version>8.83-SNAPSHOT</version>
	</parent>
	<modelVersion>4.0.0</modelVersion>
	<artifactId>aon-dbutils</artifactId>
	<description>AON DBUTILS</description>
	<name>AON DB DBUTILS</name>

    <scm>
            <connection>scm:svn:http://dev.esferalia.net/repos/aon-application/trunk/aon-dbutils</connection>
            <developerConnection>scm:svn:http://dev.esferalia.net/repos/aon-application/trunk/aon-dbutils</developerConnection>
      <tag></tag>
  </scm>

	<dependencies>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.pool</artifactId>
			<version>${project.version}</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
		    <groupId>commons-dbutils</groupId>
		    <artifactId>commons-dbutils</artifactId>
		    <version>1.5</version>
		</dependency>
		<dependency>
			<groupId>commons-codec</groupId>
			<artifactId>commons-codec</artifactId>
			<version>1.3</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>commons-cli</groupId>
			<artifactId>commons-cli</artifactId>
			<version>1.2</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>commons-lang</groupId>
			<artifactId>commons-lang</artifactId>
			<version>2.5</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-api</artifactId>
			<version>1.5.11</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.8</version>
			<type>jar</type>
			<scope>test</scope>
		</dependency>
	</dependencies>

        <build>
                <plugins>
                </plugins>
        </build>

       <profiles>
                <profile>
                        <id>rpm-release</id>
                        <activation>        
                                <property>  
                                        <name>rpm.release</name>
                                        <value>true</value>     
                                </property>                     
                        </activation>                           

                        <build>                                 
                                <plugins>                       
                                        <!-- Para construir el RPM -->
                                        <plugin>                      

                                                <groupId>org.codehaus.mojo</groupId>
                                                <artifactId>rpm-maven-plugin</artifactId>
                                                <version>2.0.1</version>                 
                                                <extensions>true</extensions>            

                                                <executions>
                                                        <execution>
                                                                <id>rpm-build</id>
                                                                <goals>           
                                                                        <goal>attached-rpm</goal>
                                                                </goals>                         
                                                        </execution>                             

                                                </executions>

                                                <configuration>
                                                        <group>Applications/Aon</group>
                                                        <release>${buildNumber}</release>
                                                        <copyright>2010, esferalia Networks S.A</copyright>
                                                        <mappings>                                                   
                                                                <mapping>                                            
                                                                        <filemode>755</filemode>                     
                                                                        <username>root</username>                    
                                                                        <groupname>root</groupname>
                                                                        <directory>/usr/share/java</directory>

									<sources>
										<source>
											<location>target</location>
											<includes>												
												<include>${project.artifactId}-${project.version}.jar</include>
											</includes>
										</source>
										<softlinkSource>
											
											<location>/usr/share/java/${project.artifactId}-${project.version}.jar</location>
											<destination>${project.artifactId}.jar</destination>
										</softlinkSource>
										<softlinkSource>											
											<location>/usr/share/java/commons-dbutils-1.5.jar</location>
											<destination>commons-dbutils.jar</destination>
										</softlinkSource>
									</sources>
									<dependency>
										<includes>
											<include>commons-dbutils:commons-dbutils:1.5</include>
										</includes>
									</dependency>

                                                                </mapping>
                                                        </mappings>
                                                        <!--mappings>                                                   
                                                        </mappings-->
                                                </configuration>
                                        </plugin>

                                </plugins>
                        </build>
                </profile>
        </profiles>
</project>
 
