<?xml version="1.0"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<parent>
		<groupId>com.code.aon</groupId>
		<artifactId>aon.parent</artifactId>
		<version>9.09-SNAPSHOT</version>
	</parent>
	<modelVersion>4.0.0</modelVersion>
	<artifactId>aon-dbutils</artifactId>
	<description>AON DBUTILS</description>
	<name>AON DB DBUTILS</name>

    <scm>
            <connection>scm:svn:http://dev.esferalia.net/repos/aon-application/trunk/aon-dbutils</connection>
            <developerConnection>scm:svn:http://dev.esferalia.net/repos/aon-application/trunk/aon-dbutils</developerConnection>
      <tag></tag>
  </scm>

	<dependencies>
		<dependency>
			<groupId>net.aonsolutions.core</groupId>
			<artifactId>dbutils</artifactId>
			<version>9.09</version>
		</dependency>
		<dependency>
		    <groupId>commons-dbutils</groupId>
		    <artifactId>commons-dbutils</artifactId>
		    <version>1.5</version>
		</dependency>
	</dependencies>

        <build>
                <plugins>
                </plugins>
        </build>

       <profiles>
                <profile>
                        <id>rpm-release</id>
                        <activation>        
                                <property>  
                                        <name>rpm.release</name>
                                        <value>true</value>     
                                </property>                     
                        </activation>                           

                        <build>                                 
                                <plugins>                       
                                        <!-- Para construir el RPM -->
                                        <plugin>                      

                                                <groupId>org.codehaus.mojo</groupId>
                                                <artifactId>rpm-maven-plugin</artifactId>
                                                <version>2.0.1</version>                 
                                                <extensions>true</extensions>            

                                                <executions>
                                                        <execution>
                                                                <id>rpm-build</id>
                                                                <goals>           
                                                                        <goal>attached-rpm</goal>
                                                                </goals>                         
                                                        </execution>                             

                                                </executions>

                                                <configuration>
                                                        <group>Applications/Aon</group>
                                                        <release>${buildNumber}</release>
                                                        <copyright>2010, esferalia Networks S.A</copyright>
                                                        <mappings>                                                   
                                                                <mapping>                                            
                                                                        <filemode>755</filemode>                     
                                                                        <username>root</username>                    
                                                                        <groupname>root</groupname>
                                                                        <directory>/usr/share/java</directory>

									<sources>
										<softlinkSource>											
											<location>/usr/share/java/dbutils-${project.dependencies[0].version}.jar</location>
											<destination>${project.artifactId}.jar</destination>
										</softlinkSource>
										<softlinkSource>											
											<location>/usr/share/java/commons-dbutils-${project.dependencies[1].version}.jar</location>
											<destination>commons-dbutils.jar</destination>
										</softlinkSource>
									</sources>
									<dependency>
										<includes>
											<include>net.aonsolutions.core:dbutils</include>
											<include>commons-dbutils:commons-dbutils</include>
										</includes>
									</dependency>

                                                                </mapping>
                                                        </mappings>
                                                        <!--mappings>                                                   
                                                        </mappings-->
                                                </configuration>
                                        </plugin>

                                </plugins>
                        </build>
                </profile>
        </profiles>
</project>
 
