#!/bin/sh
. aondir-functions

APP=aon-consultant

if ! aondir_has_app $APP; then

        aondir-addapp $APP &>/dev/null

        aondir-addrole User $APP &>/dev/null
        aondir-addrole Guest $APP &>/dev/null
        aondir-addrole Admin $APP &>/dev/null
        aondir-addrole Config $APP &>/dev/null
        aondir-addrole Auditor $APP &>/dev/null
        aondir-addrole Confidentiality $APP &>/dev/null
        aondir-addrole Product $APP &>/dev/null
        aondir-addrole Finance $APP &>/dev/null
        aondir-addrole Accounting $APP &>/dev/null
        aondir-addrole Statistics $APP &>/dev/null
        aondir-addrole eSignature $APP &>/dev/null
        aondir-addrole TaskMonitoring $APP &>/dev/null


        aondir-addprofile Administrador $APP Admin User &>/dev/null
        aondir-addprofile Invitado $APP Guest User &>/dev/null

fi
