package com.code.aon.common.enumeration;


public enum AppParam {

	ACC_DEFAULT_ALLOWANCE_ACC,
	
	ACC_DEFAULT_ASSET_LOST_ACC,
	
	ACC_DEFAULT_ASSET_PROFIT_ACC,
	
	ACC_DEFAULT_CASH_ACC,
	
	ACC_DEFAULT_CHARGED_RET_ACC,
	
	ACC_DEFAULT_CHARGED_VAT_ACC,
	
	ACC_DEFAULT_COMPANY_SOC_INS_ACC,
	
	ACC_DEFAULT_COMPENSATION_ACC,
	
	ACC_DEFAULT_FINAN_EXPENSES_ACC,
	
	ACC_DEFAULT_INVOICE_SERIES,
	
	ACC_DEFAULT_PAID_RET_ACC,
	
	ACC_DEFAULT_PAID_VAT_ACC,

	ACC_DEFAULT_PENDING_SALARY_ACC,
	
	ACC_DEFAULT_PERIOD,
	
	ACC_DEFAULT_PREPAYMENT_ACC,
	
	ACC_DEFAULT_PURCHASE_ACC,
	
	ACC_DEFAULT_RETENTION_PERCENT,
	
	ACC_DEFAULT_SALARY_ACC,
	
	ACC_DEFAULT_SALES_ACC,
	
	ACC_DEFAULT_SOCIAL_INSURANCE_ACC,
	
	ACC_DEFAULT_VAT_PERCENT,
	
	ACC_OPERATIONS_DEADLINE,
	
	ACC_DEADLINE_INCL_RECTIFICATIONS,
	
	ACC_SALARY_CHARGED_RET_ACC,
	
	AGREEMENT,
	
	AON_AEB_ENABLED,
	
	AON_ALLOW_CONCURRENT_DOMAIN,
	
	AON_ALLOW_DUPLICATE_DOMAIN,
	
	AON_BETA_ENABLED,
	
	AON_CUSTOMIZE_FONT_COLOR,
	
	AON_CUSTOMIZE_HERITABLE_ID,
	
	AON_CUSTOMIZE_ID,
	
	AON_CUSTOMIZE_OEM,
	
	AON_CUSTOMIZE_LOGIN_SEPARATOR,
	
	AON_CUSTOMIZE_SEPARATOR,
	
	AON_CUSTOMIZE_SUPPORT_EMAIL,
	
	AON_CUSTOMIZE_SUPPORT_PHONE,
	
	AON_CUSTOMIZE_TITLE,
	
	AON_DOMAIN_PAYER,
	
	AON_DEH_ONLINE_USER,
	
	AON_DEH_ONLINE_PASSWORD,
	
	AON_DSI_LOADER_ENABLED,
	
	AON_HIDE_TRADEMARK,
	
	AON_HIDE_VERSION,
	
	AON_EXPORT_ACCOUNT_SIZE,
	
	AON_EXPORT_TYPE,
	
	AON_EXPORT_ENTERPRISE_ID,

	AON_EXPORT_INVOICE_MAX_LENGTH,
	
	AON_EXPORT_JOURNAL,
	
	AON_EXPORT_JOURNAL_EXPENSES,
	
	AON_EXPORT_JOURNAL_PURCHASE,
	
	AON_EXPORT_JOURNAL_SALES,
	
	AON_EXPORT_VATS,
	
	AON_EXTERNAL_APPLICATIONS,
	
	AON_FACTURAE_DECIMALS,
	
	AON_HELPDESK_ENABLED,
	
	AON_LOG_ENABLED,
	
	AON_PORTAL,
	
	AON_PRODUCT_DETAIL_LEVEL,
	
	AON_PRODUCT_VALUATION_METHOD,
	
	AON_PRODUCT_AVERAGE_MONTHS,
	
	AON_SUPPORT_ENABLED,
	
	APP_PRINT_INVOICE_WORD,
	
	APP_PRINT_HEADER_PARAM,
	
	APP_PRINT_RECORD_DATA_PARAM,
	
	APP_FPAYMENT_TEMPLATE_PARAM,
	
	APP_SALE_INVOICE_TEMPLATE_PARAM,
	
	APP_OFFER_TEMPLATE_PARAM,
	
	APP_DELIVERY_TEMPLATE_PARAM,
	
	APP_ITEM_TAG_TEMPLATE_PARAM,
	
	APP_ITEM_TAG_TEXT_PARAM,

	APP_ITEM_TAG_BARCODE_PARAM,
	
	APP_MANUFACT_TEMPLATE_TAG_PARAM,
	
	APP_PRINT_DISCOUNT_PRICE_APPLIED,
	
	APP_PRINT_LOGO_PARAM,
	
	APP_PRINT_NAME_PARAM,
	
	APP_PRINT_NIF_PARAM,
	
	APP_PRINT_ADDRESS_PARAM,
	
	APP_PRINT_INTERNET_DATA_PARAM,

	APP_PRINT_PRODUCT_CODE_PARAM,
	
	APP_PRINT_PRODUCT_VAT_PARAM,
	
	APP_PRINT_PROJECT_PARAM,
	
	APP_PRINT_REFERENCE_CODE_PARAM,

	APP_PRINT_S_INVOICE_FOOTER_PARAM,

	APP_SMART_CARD_PARAM,
	
	EDI_SUPPORT,
	
	EDI_COMPANY_CODE,
	
	REPORT_invoicePrint,
	
	REPORT_saleInvoice,
	
	REPORT_invoiceDetailDefault,
	
	REPORT_invoiceFinancesDefault,
	
	REPORT_invoicePrepaymentsDefault,
	
	REPORT_invoiceTaxBreakDown,
	
	WEBINFO_FTP_PASSWORD,

	WEBINFO_FTP_SERVER,
	
	WEBINFO_FTP_USER,
		
	WEBINFO_HOMEPAGE_ID,

	WEBINFO_PREVIEW_PATH,

	WEBINFO_PREVIEW_URL,

	WEBINFO_PUBLISH_PATH,

	WEBINFO_PUBLISH_URL,
	
	WEBINFO_TEMPLATE_NAME,
	
	PAY_available_contract_codes_PAY,

	PAY_afi_test_env_PAY,

	PAY_authorization_key_PAY,
	
	PAY_certifica2_passwd_PAY,
	
	PAY_certifica2_ssl_env_PAY,
	
	PAY_certifica2_test_env_PAY,
	
	PAY_certifica2_user_PAY,
	
	PAY_contrata_passwd_PAY,
	
	PAY_contrata_ssl_env_active_PAY,
	
	PAY_contrata_test_env_active_PAY,
	
	PAY_contrata_user_PAY,
	
	PAY_default_contractCode_PAY,
	
	PAY_default_trainingCenter_PAY,
	
	PAY_dev_mode_PAY,
	
	PAY_fan_test_env_PAY,
	
	PAY_REPORT_additional_salary_PAY,
	
	PAY_REPORT_salary_PAY,
	
	PAY_REPORT_salaryDraft_PAY,
	
	PAY_ss_mutual_PAY,
	
	PAY_ss_payment_bankAccount_PAY,

	PMS_SIMPLE_AVAILABILITY_URL,

	PMS_BOOKING_URL,

	PMS_INVENTORY_URL,

	PMS_ROOM_CATEGORY,

	PMS_SERVICE_CATEGORY,

	PMS_EXTRAPAX_CATEGORY,

	PMS_BOARD_CATEGORY,
	
	PMS_ADVANCE_ITEM,
	
	PMS_TOURIST_TAX_ITEM,
	
	PMS_EARLY_CHECKOUT_ITEM,
	
	PMS_NOSHOW_ITEM,
	
	PMS_CANCELLATION_ITEM,

	PMS_AUTO_DISCOUNT_ITEM,

	PMS_BEST_PRICE_DISCOUNT_ITEM,

	PMS_UNDEFINED_ROOM_ITEM,

	PMS_UNDEFINED_SERVICE_ITEM,

	PMS_UNDEFINED_TARIFF,

	PMS_REQUEST_AUTO_SELLER_ID,

	PMS_ALLOTMENT_RATE_CODE,
	
	PMS_DAILY_CASH_LIMIT,

	PMS_ROOM_CLEAN_MAX_DAYS,

	PMS_CONEXFLOW_SERVER_PARAM,
	
	PMS_CONEXFLOW_SERVER_ACK_PARAM,
	
	PMS_CONEXFLOW_USER,
	
	PMS_CONEXFLOW_KEY_A,
	
	PMS_CONEXFLOW_KEY_B,
	
	PMS_CONEXFLOW_PAY_METHOD,
	
	PMS_HHG_SERVER,

	PMS_PRODUCTION_REPORT_CATEGORY,

	PMS_PRODUCTION_REPORT_OPEN_HOUR,

	PMS_PRODUCTION_REPORT_CLOSE_HOUR,

	PMS_POLICE_COUNT,

	POS_INVOICE_PRINT_OUTPUT,
	
	POS_INVOICE_PRINT_LOGO,
	
	POS_INVOICE_PRINT_TRADENAME,
	
	POS_INVOICE_PRINT_DIR_STAFF,
	
	POS_INVOICE_PRINT_DISCOUNT,
	
	POS_INVOICE_PRINT_SELLER_NAME,
	
	POS_INVOICE_PRINT_DOMAIN,
	
	POS_INVOICE_FOOTER_TEXT,
	
	POS_INVOICE_WIDTH,
	
	SALES_ACTIVE_MARKETPLACE,
	
	SALES_AMAZON_PRODUCT_NAME,
	
	ACC_DEFAULT_SALARY_IK_ACC,
	
	ACC_SALARY_CHARGED_RET_IK_ACC
	
	,ACC_SALARY_DED_ADV_PAYMENT_ACC

	,ACC_SALARY_DED_SEIZE_ACC
	
	,ACC_SALARY_DED_IN_KIND_ACC
	
	,ACC_SALARY_DED_OTHER_ACC
	
	,ACC_VAT_NEGATIVE_ADJUST_ACC
	
	// CALL CENTER
	,NOTICE_NOTIFICATION_MAIL
	,NOTICE_NOTIFICATION_SIGNATURE
	,NOTICE_NOTIFICATION_AUTO
	,NOTICE_NOTIFICATION_HISTORY
	,NOTICE_NOTIFICATION_BCC
	,NOTICE_NOTIFICATION_MODE
	,NOTICE_NOTIFICATION_LOGO
	,CALL_CENTER_FAST_FILTER_MINE
	,CALL_CENTER_FAST_FILTER_GROUP
	,CALL_CENTER_FAST_FILTER_OPERATOR
	,CALL_CENTER_FAST_FILTER_TYPE
	,CALL_CENTER_FAST_FILTER_PRIORITY
	,CALL_CENTER_GITHUB_USERNAME
	,CALL_CENTER_GITHUB_REPOSITORY
	,CALL_CENTER_GITHUB_TOKEN
	
	,UDAPA
	;

	public String getValue() {
		return toString();
	}
	
}
