#!/bin/bash

#POM_VERSION=$(cat <<EOF | xsltproc - pom.xml
#<?xml version="1.0" encoding="UTF-8"?>
#<xsl:stylesheet version="1.0"
#xmlns:pom="http://maven.apache.org/POM/4.0.0"
#xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
#>
#<xsl:output method="text" />
#
#<xsl:template match="pom:project/pom:version/text()">
#<xsl:value-of select="."/>
#</xsl:template>
#
#<xsl:template match="text()"/>
#
#</xsl:stylesheet>
#EOF
#)

POM_VERSION=$(grep -Po "(?<=<version>)[[:digit:]]+\.[[:digit:]]+-SNAPSHOT(?=</version>)" pom.xml)

echo  'Tags for '$POM_VERSION' :'
wget -O - https://registry.hub.docker.com/v2/repositories/aonsolutions/aon-application/tags \
| grep -oE $POM_VERSION
echo  ' '

BUILD=$(wget -O - https://registry.hub.docker.com/v2/repositories/aonsolutions/aon-application/tags 2>/dev/null \
| grep -oE $POM_VERSION | wc -l)
export BUILD

TAG=aonsolutions/aon-application:$POM_VERSION-$BUILD-tomcat9-jre8
export TAG

echo  'New tag being built is '$TAG

docker tag $TAG $DOCKER_REPO:$SOURCE_COMMIT
docker push $DOCKER_REPO:$SOURCE_COMMIT
