bgcolor_color_de_fondo = #464646
bgcolor_color_de_fondo_contenido = #E2E2E2
bgcolor_color_de_fondo_pie = #484848
bgcolor_color_de_fondo_menu = #999999
bgcolor_color_de_fondo_sidebar = #444444
color_color_de_texto_link = #747474
color_color_de_texto_pie = #ffffff
color_color_de_texto_menu = #ffffff
color_color_de_texto_link_hover = #000000
color_color_de_texto_contenido = #333333
font_fuente = 3
size_tamano_de_fuente = 11
size_tamano_de_fuente_cabecera = 10	
size_tamano_de_fuente_menu = 11
border_bordes = 1
border_bordes_menu = 5
color_color_borde = #888888
color_color_borde_sidebar = #bbbbbb
color_color_borde_menu = #555555
color_color_borde_menu_hover = #222222