<?xml version="1.0" encoding="utf-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.code.aon</groupId>
    <artifactId>aon.parent</artifactId>
    <version>9.23-SNAPSHOT</version>
  </parent>
  <groupId>net.aonsolutions</groupId>
  <artifactId>aon-solutions</artifactId>
  <packaging>war</packaging>
  <name>AON SOLUTIONS</name>
  <description>AON SOLUTIONS</description>
  <properties>
    <maven.build.timestamp.format>dd/MM/yyyy HH:mm:ss</maven.build.timestamp.format>
  </properties>
  <build>
    <finalName>aon-solutions</finalName>
    <plugins>
   <plugin>
     <groupId>com.github.eirslett</groupId>
     <artifactId>frontend-maven-plugin</artifactId>
     <version>1.8.0</version>
     <configuration>
       <workingDirectory>src/main/webapp</workingDirectory>
       <installDirectory>temp</installDirectory>
     </configuration>
     <executions>
       <!-- It will install nodejs and npm -->
       <execution>
         <id>install node and npm</id>
         <goals>
           <goal>install-node-and-npm</goal>
         </goals>
         <configuration>
           <nodeVersion>v13.12.0</nodeVersion>
           </configuration>
       </execution>

       <!-- It will execute command "npm install" inside "/angular" directory -->
       <execution>
         <id>npm install</id>
         <goals>
           <goal>npm</goal>
         </goals>
         <configuration>
           <arguments>install</arguments>
         </configuration>
       </execution>

       <!-- It will execute command "npm build" inside "/angular" directory to clean and create "/dist" directory-->
       <execution>
         <id>npm build</id>
         <goals>
           <goal>npm</goal>
         </goals>
         <configuration>
           <arguments>run build</arguments>
         </configuration>
       </execution>
     </executions>
   </plugin>
    
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>build-helper-maven-plugin</artifactId>
        <executions>
          <execution>
            <id>parse-version</id>
            <goals>
              <goal>parse-version</goal>
            </goals>
            <configuration />
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-war-plugin</artifactId>
        <version>3.2.2</version>
        <configuration>
          <archive>
            <manifest>
              <addDefaultSpecificationEntries>true</addDefaultSpecificationEntries>
              <addDefaultImplementationEntries>true</addDefaultImplementationEntries>
            </manifest>
            <manifestEntries>
              <dbVersion>${dbVersion}</dbVersion>
              <buildNumber>${env.BUILD_NUMBER}</buildNumber>
              <buildDate>${maven.build.timestamp}</buildDate>
              <buildRevision>${buildNumber}</buildRevision>
            </manifestEntries>
          </archive>
          <webResources>
            <resource>
              <!-- this is relative to the pom.xml directory -->
              <directory>../aon-web-aio/src/main/webapp</directory>
              <!-- the list has a default value of ** -->
              <includes>
                <include>js/**</include>
                <include>css/**</include>
                <include>images/**</include>
              </includes>
            </resource>
            <resource>
              <!-- this is relative to the pom.xml directory -->
              <directory>../aon-ui-finance/src/main/resources</directory>
              <includes>
                <include>com/code/aon/ui/finance/pdfjs/**</include>
              </includes>
            </resource>
 
            <resource>
              <directory>../aon-suite/public</directory>
              <targetPath>aon-suite/public</targetPath>
              <!-- the list has a default value of ** 
              <includes>
                <include>**</include>
              </includes>
              -->
            </resource>
 
          </webResources>
        </configuration>
        <executions>
          <execution>
            <id>execution1</id>
            <phase>package</phase>
            <configuration />
            <!--goals>
              <goal>manifest</goal>
            </goals-->
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
  <dependencies>
  	<dependency>
      <groupId>net.aonsolutions</groupId>
      <artifactId>aon.gwt.aio</artifactId>
      <version>${project.version}</version>
      <scope>runtime</scope>
    </dependency>
	
	<dependency>
      <groupId>net.aonsolutions</groupId>
      <artifactId>aon.api</artifactId>
      <version>${project.version}</version>
      <scope>compile</scope>
    </dependency>
	
    <dependency>
      <groupId>net.aonsolutions</groupId>
      <artifactId>aon.webservice</artifactId>
      <version>${project.version}</version>
      <scope>compile</scope>
    </dependency>
	
	<dependency>
		<groupId>commons-lang</groupId>
		<artifactId>commons-lang</artifactId>
		<version>2.6</version>
		<scope>compile</scope>
	</dependency>
		    
	<!-- *** POR AON-FACTURAE... *** -->
	<dependency>
		<groupId>com.code.aon</groupId>
		<artifactId>aon.facturae</artifactId>
		<version>${project.version}</version>
		<scope>compile</scope>
	</dependency>
	
	<dependency>
    	<groupId>commons-logging</groupId>
    	<artifactId>commons-logging</artifactId>
    	<version>1.2</version>
	</dependency>

    <dependency>
        <groupId>log4j</groupId>
        <artifactId>log4j</artifactId>
        <version>1.2.17</version>
    </dependency>
    <!-- *********************** -->
    <dependency>
	   	<groupId>com.auth0</groupId>
	    <artifactId>java-jwt</artifactId>
	    <version>3.9.0</version>
	</dependency>
  	
  </dependencies>
</project>
