#!/bin/sh
### ====================================================================== ###
##                                                                          ##
##  Ctsql2MysqlD Bootstrap Script                                           ##
##                                                                          ##
### ====================================================================== ###


CLASSPATH=$CLASSPATH:/usr/share/java/ctsql-jdbc.jar
CLASSPATH=$CLASSPATH:/usr/share/java/mysql-connector-java.jar

CLASSPATH=$CLASSPATH:/usr/share/java/slf4j/api.jar
#CLASSPATH=$CLASSPATH:/usr/share/java/slf4j/jcl.jar
CLASSPATH=$CLASSPATH:/usr/share/java/slf4j/simple.jar


CLASSPATH=$CLASSPATH:/usr/share/java/aon-config.jar
CLASSPATH=$CLASSPATH:/usr/share/java/aon-common.jar
CLASSPATH=$CLASSPATH:/usr/share/java/aon-registry.jar
CLASSPATH=$CLASSPATH:/usr/share/java/aon-company.jar
CLASSPATH=$CLASSPATH:/usr/share/java/aon-customer.jar
CLASSPATH=$CLASSPATH:/usr/share/java/aon-calendar.jar
CLASSPATH=$CLASSPATH:/usr/share/java/aon-salary.jar
CLASSPATH=$CLASSPATH:/usr/share/java/aon-payroll.jar

CLASSPATH=$CLASSPATH:/usr/share/java/commons-cli.jar
CLASSPATH=$CLASSPATH:/usr/share/java/commons-lang.jar
#CLASSPATH=$CLASSPATH:/usr/share/java/commons-logging.jar

CLASSPATH=$CLASSPATH:/usr/share/java/aon-payroll-ctsql2mysql.jar

CLASSPATH=$CLASSPATH:/usr/share/inotify-java/lib/inotify-java-2.0.2.jar

java -classpath $CLASSPATH com.esferalia.aon.payroll.ctsql2mysql.Ctsql2MysqlD "$@"

