#####################################################################
#

# No inserta nada en la base de datos. No hace commit. 
# dryrun

# Traspasar los clientes inactivos.
#inactivo

# Chequear fechas de visionado.
#visionado

# trapasar los datos a partir de esta fecha M/d/Y
from=01/01/11

# mysqluser=dbuser 
# mysqlpasswd=serubd2000 
mysqlurl=jdbc:mysql://127.0.0.1:3306/payroll-esferalia-org 

# ctsqluser=ctl
# ctsqlpasswd=ctl
ctsqlurl=jdbc:ctsql://127.0.0.1:1101/empre055;DBPATH=/usr/share/ctsql/data;RTRIMCHAR=true 


domainUser=toledo 
domainPasswd=t0l3d0
domain=tadc055.toledoas.com 

# Espera antes de lanzar la sincronización ( sólo para el demonio ). 
delay=10

# Tablas de ctsql que lanzan la sincronización ( sólo para el demonio ). 
table=emprper


#commands
command=mysqldump --compact --databases payroll-esferalia-org | gzip > /tmp/payroll-esferalia-org.sql.gz
command=scp -i /root/.ssh/tolcaste.pem /tmp/payroll-esferalia-org.sql.gz ec2-user@54.246.227.104:/var/tmp
