#####################################################################
#

# No inserta nada en la base de datos. No hace commit. 
# dryrun

from=01/01/10

# mysqluser=dbuser
# mysqlpasswd=serubd2000 
mysqlurl=jdbc:mysql://127.0.0.1:3306/payroll-esferalia-org 

# ctsqluser=ctl
# ctsqlpasswd=ctl
ctsqlurl=jdbc:ctsql://127.0.0.1:1101/empre055;DBPATH=/usr/share/ctsql/data;RTRIMCHAR=true 


