#!/bin/sh

#####################################################################
# Copyright (c) 2011, esferalia NETWORKS S.A
#
# The copyright of the computer PROGram herein is the property 
# of esferalia NETWORKS.
#####################################################################
# The PROGram may be used and/or copied only with the written 
# permission of esferalia NETWORKS, or in accordance with the 
# terms and conditions stipulated in the agreement contract 
# under which the PROGram has been supplied.
####################################################################
#
# aon-payroll-ctsql2mysqld	Syncing daemon
#
# Author:       Raúl Trepiana <rtrepiana@esferalia.com>
#
# chkconfig:	345 97 03
#
# description:  Daemon which uses inotify to synchronize ctsql database\
#               with aon 'mysql' database.
# processname:  aon-payroll-ctsql2mysqld
# config: 	/etc/aon-payroll-ctsql2mysqld.conf
# logfile: 	/var/log/aon-payroll-ctsql2mysqld.log
# pidfile: 	/var/run/aon-payroll-ctsql2mysqld.pid
#

### BEGIN INIT INFO
# Provides: aon-payroll-ctsql2mysqld
# Required-Start: 
# Required-Stop: 
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: aon Payroll ctsql2mysql Daemon
# Description: Daemon that synchronizes 'nominasta' ctsql database 
# 	      with 'aon Payroll' mysql database.
### END INIT INFO

NAME=ctsql2mysqld
SYNC=/usr/bin/aon-payroll-ctsql2mysql
PROG=/usr/bin/aon-payroll-ctsql2mysqld
CONFFILE=${CONFILE-/etc/aon-payroll-ctsql2mysqld.conf}
LOGFILE=${LOGDIR-/var/log/aon-payroll-ctsql2mysqld.log}
PIDFILE=${PIDFILE-/var/run/aon-payroll-ctsql2mysqld.pid}
LOCKFILE=${LOCKFILE-/var/lock/subsys/aon-payroll-ctsql2mysqld}


# source function library
. /etc/rc.d/init.d/functions

declare -a ARGS
RETVAL=0

# check for configuration
check () {
	CONFFILE=$1
	if [ ! -f $CONFFILE ]; then
		echo
		echo 1>&2 " Configuration file $CONFFILE missing"
		failure "${NAME} config test"
		echo
		exit 1
	fi
}

function parseargs() {
	CONFFILE=$1
	check $CONFFILE || exit 1
    I=0
    while read LINE
    do 
    	LINE=${LINE%%#*}
    	[ -z "$LINE" ] && continue;
    	
    	if [[ $LINE == *=* ]]; then 
    		ARGS[$((I++))]='-'${LINE%%=*};
    		ARGS[$((I++))]=${LINE#*=};
    	else 
    		ARGS[$((I++))]=$LINE;
    	fi 
	
	done < $CONFFILE;
}


function procrunning() {
	
	procid=0
	
	parseargs $CONFFILE || exit 1

	SCRIPTARGS=$(echo "${ARGS[@]}" | sed 's/\([-"]\)/\\\1/g')   
   
	for procid in `pidof -x "java"`; do
		ps -fp $procid | grep "$SCRIPTARGS"  > /dev/null && pid=$procid
	done
}

sync() {
    parseargs $CONFFILE || exit 1
    echo $SYNC "${ARGS[@]}" 
    $SYNC "${ARGS[@]}"
    return $?
}

start() {
    echo -n $"Starting $PROG: "
	# if lock file exists
    if [ -f $LOCKFILE ]; then
        procrunning
        if [ ! $pid = '0' ]; then
           failure $"${NAME} startup"
           echo -n -e "\nProcess already running"
           echo -n -e "\n"
           return 2
        fi
    fi

    parseargs $CONFFILE || exit 1
	
    echo $PROG "${ARGS[@]}" >$LOGFILE
    $PROG "${ARGS[@]}" >>$LOGFILE 2>&1  &
	RETVAL=$?

    if [ $RETVAL -eq 0 ]; then
        success $"${NAME} startup"
    else
        failure $"${NAME} startup"
	fi
	
    echo
	[ $RETVAL = 0 ] && touch ${LOCKFILE}
	
	pid=0
    procrunning
    if [ ! $pid = '0' ]; then
		echo $pid > $PIDFILE
    fi
    return $RETVAL
}

stop() {

    echo -n $"Stopping ${NAME}: "
    parseargs $CONFFILE || exit 1
    pid=0
    procrunning
    if [ $pid = '0' ]; then
        failure $"${NAME} shutdown"
        echo -n -e "\nNo ${NAME} is currently running\n"
        if [ -f $LOCKFILE ]; then
            rm -f $LOCKFILE
        fi
        if [ -f $PIDFILE ]; then
            rm -f $PIDFILE
        fi
		return 1
	else
		kill -9 $pid &>/dev/null
    fi
	
	RETVAL=$?

    pid=0
    procrunning
	
	if [ $pid != '0' ] ; then
        echo -e "\nTimeout: Shutdown command was sent, but process is still running with PID $pid"
        failure $"${NAME} shutdown"
	else
		success $"${NAME} shutdown"
	fi

    echo
    [ $RETVAL -eq 0 ] && rm -f $LOCKFILE $PIDFILE 
    return $RETVAL
}

status() {
    pid=0
    procrunning
    if [ $pid == 0 ]; then
        if [ -f $LOCKFILE ]; then
            echo "${NAME} is dead but subsys locked";
            return 2
        fi
        if [ -f $PIDFILE ]; then
            echo "${NAME} is dead but pid file exists";
            return 3
        fi
        echo "${NAME} is stopped";
        return 0
    else
        echo "${NAME} (pid $pid) is running";
        return 0
    fi
}

# Restart only if process is already running
condrestart() {
	pid=0
    procrunning
    if [ $pid != 0 ]; then
    	stop
        sleep 3
		start
	fi
}


case "$1" in
  sync)
  	sync
	;;
  start)
	start
	;;
  stop)
	stop
	;;
  status)
    status
	;;
  restart)
    stop
    sleep 3
    start
	;;
  condrestart)
	condrestart
	;;
  *)
	echo $"Usage: $0 {start|stop|status|restart|condrestart}"
	exit 1
esac

