package com.code.aon.fiscal;

public interface IFiscalConstants {

	String FS_DEFAULT_YEAR = "FS_DEFAULT_YEAR";
	String FS_DEFAULT_ADMINISTRATION = "FS_DEFAULT_ADMINISTRATION";
	String FS_ADMINISTRATION_CODE = "FS_ADMINISTRATION_CODE";
	String FS_TAX_REFUND_REGISTRY = "FS_TAX_REFUND_REGISTRY";
	String FS_TAX_REGIME = "FS_TAX_REGIME";
	String FS_ADMON_CREDITOR = "FS_ADMON_CREDITOR";
	String FS_PERM_ADDRESS_CHANGES = "FS_PERM_ADDRESS_CHANGES";
	String FS_CONCTACT_PERSON = "FS_CONCTACT_PERSON";
	String FS_CONCTACT_PHONE = "FS_CONCTACT_PHONE";
	String FS_CONCTACT_CELLULAR = "FS_CONCTACT_CELLULAR";
	String FS_CONCTACT_MAIL = "FS_CONCTACT_MAIL";

}
