invoice=Rechnung
simplifiedInvoice=Vereinfachte Rechnung
rectifiedInvoice=Berichtigungsrechnung
rectifies=Diese Rechnung korrigiert:
number=Nummer
date=Datum
description=Bezeichnung
quantity=Anzahl
price=Preis
discount=%Dto.
amount=betragen
base=Base
type=Typ
quota=Quote
totalInvoice=Gesamte Rechnung
payMethod=Zahlungsmethode
bankAccount=Bankkonto
web=Netz
phone=Telefon
mail=Email
notes=Vermerken