invoice=Factura
number=Número
date=Data
description=Descrición
quantity=Cantidade
price=Prezo
discount=%Dto.
amount=Importe
base=Base
type=Tipo
quota=Cota
totalInvoice=Total Factura
payMethod=Forma de Pagament
bankAccount=Cuenta Bancaria
web=Web
phone=Teléfono
mail=Email