invoice=Factura
simplifiedInvoice=Factura Simplificada
number=Número
date=Fecha
description=Descripción
quantity=Cantidad
price=Precio
discount=%Dto.
amount=Importe
base=Base
type=Tipo
quota=Cuota
totalInvoice=Total Factura
payMethod=Forma de Pago
bankAccount=Cuenta Bancaria
web=Web
phone=Teléfono
mail=Email