invoice=Factura
simplifiedInvoice=Factura Simplificada
rectifiedInvoice=Factura Rectificativa
rectifies=Aquesta factura rectifica a:
number=Nombre
invoiceNumber=Nombre Factura
date=Data
operationDate=Data Operació
expeditionDate=Data Expedició
description=Descripció
quantity=Quantitat
price=Preu
discount=%Dto.
amount=Import
base=Base
type=Tipus
quota=Quota
totalInvoice=Total Factura
payMethod=Forma de Pagament
bankAccount=Compte Bancari
web=Web
phone=Teléfono
mail=Email
notes=Notes
nif=N.I.F.
customerNif=N.I.F. Client