<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<parent>
		<groupId>com.code.aon</groupId>
		<artifactId>aon.web.parent</artifactId>
		<version>1.0.4</version>
	</parent>
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.code.aon</groupId>
	<artifactId>aon.web.account</artifactId>
	<packaging>war</packaging>
	<version>2.1.0</version>
	<description>AON WEB ACCOUNT</description>
	<name>AON WEB ACCOUNT</name>
	<build>
		<finalName>aon-account</finalName>
	</build>
	<properties>
		<dbVersion>1.5.0</dbVersion>
	</properties>
	<dependencies>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.security.bridge</artifactId>
			<version>1.2.13</version>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.form.myfaces</artifactId>
			<version>2.0.3</version>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.report</artifactId>
			<version>2.0.0-SNAPSHOT</version>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.account</artifactId>
			<version>2.2.1</version>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.company</artifactId>
			<version>2.1.2</version>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.config</artifactId>
			<version>2.0.7</version>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.customer</artifactId>
			<version>2.0.12</version>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.finance</artifactId>
			<version>2.3.1</version>
			<scope>runtime</scope>
			<exclusions>
				<exclusion>
					<groupId>com.code.aon</groupId>
					<artifactId>aon.ui.warehouse</artifactId>
				</exclusion>
				<exclusion>
					<groupId>com.code.aon</groupId>
					<artifactId>aon.tas.delivery</artifactId>
				</exclusion>
				<exclusion>
					<groupId>com.code.aon</groupId>
					<artifactId>aon.csb</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.geozone</artifactId>
			<version>1.0.1</version>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.product</artifactId>
			<version>2.0.7</version>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.supplier</artifactId>
			<version>2.0.3</version>
			<scope>runtime</scope>
		</dependency>

		<!--
			PARA CONSTRUIR CORRECTAMENTE EL WAR 		
		-->
		<dependency>
			<groupId>javax.servlet.jsp</groupId>
			<artifactId>jsp-api</artifactId>
			<version>2.1</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.apache.myfaces.core</groupId>
			<artifactId>myfaces-api</artifactId>
			<version>1.1.5</version>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>org.apache.myfaces.core</groupId>
			<artifactId>myfaces-impl</artifactId>
			<version>1.1.5</version>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>org.apache.myfaces.tomahawk</groupId>
			<artifactId>tomahawk-sandbox</artifactId>
			<version>1.1.7-SNAPSHOT</version>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>com.sun.facelets</groupId>
			<artifactId>jsf-facelets</artifactId>
			<version>1.1.11</version>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>commons-fileupload</groupId>
			<artifactId>commons-fileupload</artifactId>
			<version>1.1</version>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>fop</groupId>
			<artifactId>fop</artifactId>
			<version>0.20.5</version>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi</artifactId>
			<version>3.0.1-FINAL</version>
			<scope>runtime</scope>
			<exclusions>
				<exclusion>
		            <groupId>log4j</groupId>
		            <artifactId>log4j</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
	</dependencies>
</project>

