EXTERNAL=true
GENERIC=true
MENU=true
FAQ=true
LINK=true
MODULAR=true
DIRECT_ACCESS=true
ALBUM_IMAGES=true
ARTICLE_NEWS=true
ARTICLE_SERVICES=true
ARTICLE_EVENTS=true
ARTICLE_OTHER=true
DOWNLOAD=true
DIARY=true
PRODUCT_CATEGORIES=true
BRANDS=true
HIRU=false
SPORT=false
ACTIVITY=true