100=The server is not connected!
101=The connection is not open!
200=The statement is not prepared!
201=The cursor is not open!
202=Bad row size!
203=Invalid column type!
205=the result set type is TYPE_FORWARD_ONLY!
206=the result set concurrency is CONCUR_READ_ONLY!
207= absolute method: the row is 0!
208=Can not find table name in the result set statement.
-1576=Incorrect year in DATE.
-1575=Incorrect month in DATE.
-1574=Incorrect day in DATE.
-1573=The converted value does not fit in the space reserved.
-1572=CHARACTER to non-CHARACTER conversion is not allowed.
-1571=Impossible to convert the DATE to month/day/year format.
-1570=CHARACTER to number conversion error
-1569=Value too big for a SMALLINT.
-1568=Value too big for an INTEGER.
-1567=FORMAT string too long.
-1566=CHARACTER to DATE conversion error.
-1565=Attempt to assign a null value to a variable defined as NOT NULL.
-1564=Too many digits to the left of the decimal point.
-1563=Invalid hour in TIME.
-1562=Invalid minute in TIME.
-1561=Invalid second in TIME.
-1560=CHAR to TIME conversion error.
-1542=NO KEY PRESENT.
-1529=Cannot connect with the SQL server. %s.
-1522=Invalid access to the SQL server.
-1521=The communication with the SQL server was interrupted.
-1454=Gateway incorrect version
-1453=Impossible to UPDATE the SERIAL column. Look MBSERIAL table
-1452=MultiBase Catalog corrupted. Server Error "(%s)"
-1451=MultiBase catalog does not match the SQL server catalog
-1450=Error "(%s)" returned by the SQL server
-1413=Impossible to remove file for table (%s)
-1412=Impossible to open file for table (%s)
-1411=Impossible to open or create a temporary file
-1410=Impossible to write to a temporary file
-1397=Database not found or no system permission
-1396=Impossible to drop the directory containing the database
-1395=Impossible to create database directory
-1394=Impossible to DROP. Database contains tables owned by other users
-1393=Database not opened
-1392=Before CREATE, START or ROLLFORWARD the current database must be CLOSED
-1391=Cannot drop current database
-1390=DBPATH too long
-1383=Imposible to create soo long registry
-1382=Table name (%s) not declared in the FROM clause
-1381=Impossible to create the system table (%s)
-1380=Cursor DECLARED for more than one table.  Impossible to UPDATE
-1379=Impossible to ALTER TABLE (%s). Cannot build the temporary file
-1378=Impossible to ALTER TABLE (%s). Cannot write to temporary file
-1377=Table name (%s) duplicated in the FROM clause
-1376=Impossible to rename file for table
-1375=Impossible to open the database table (%s)
-1374=Impossible to create file for table (%s)
-1373=Impossible to read information for table
-1372=Table (%s) already exists in database
-1371=The table (%s) does not exist in the database
-1370=Impossible to perform operation. Table (%s) currently in use
-1365=Each SELECT statement of a UNION must have the same number of columns
-1364=The types of the columns must be equal for each UNION statement
-1363=Column not found
-1362=Maximum column size for CHARACTER exceeded. Maximum is 32767
-1361=Column (%s) not found in the tables in the query
-1360=Ambiguous column (%s)
-1359=Column (%s) already exists in table
-1358=Column size too long
-1357=Column (%s) not declared in the UPDATE OF clause
-1356=Only one column of SERIAL type may be defined for a table
-1355=Impossible to drop last column
-1354=Column (%s) does not have the same type as in the table referenced
-1353=Components of the key are missing in the column list
-1352=The DEFAULT value and the column have incompatible types
-1351=Cannot insert into column (%s)
-1350=Cannot update column (%s)
-1335=Cursor NOT declared FOR UPDATE
-1334=A cursor opened FOR UPDATE must use a simple SELECT statement
-1333=Number of columns in INSERT different than number of VALUES
-1332=Synonym already used
-1331=Synonym (%s) not found
-1330=A SERIAL column cannot have a DEFAULT value
-1329=Incorrect database name, or column name, or CURSOR name
-1328=Incorrect number of host variables
-1327=Comment with no end found in SQL statement
-1326=Path name too long
-1325=Identifier too long
-1324=Illegal character found in the statement
-1323=Illegal integer found in the statement
-1322=Illegal decimal number found in the statement
-1321=FROM clause missing in the statement
-1320=Wildcards not allowed for non-character types
-1319=Quoted string too long
-1318=Syntax error: quote missing
-1317=A subscripted column must be of type CHAR, (%s) is not CHAR
-1316=Subscript out of range
-1315=Illegal subscript
-1314=Incorrect decimal format
-1313=Column value does not match PICTURE
-1312=PICTURE is only valid on CHAR type columns
-1311=FORMAT is not valid on CHAR type columns
-1310=Syntax error
-1299=Impossible to INSERT row. Duplicated value in column with UNIQUE INDEX
-1298=Impossible to create an index for system table (%s)
-1297=Impossible to add index
-1296=Impossible to delete index
-1295=Impossible to read through table. Index file may be corrupted
-1294=Index (%s) already exists
-1293=Impossible to DROP index. It does not exist
-1292=Impossible to DROP index. Not owner
-1291=Impossible to create unique index. Duplicated data found for the column
-1290=An index already exists for that column
-1285=The column (%s) does not accept NULLs
-1284=IS [NOT] NULL may only be used with existing columns
-1283=Impossible to add column (%s). It does not accept null values
-1282=The column contains NULL values
-1281=Attempt to INSERT a NULL value into column (%s)
-1280=SET NULL cannot be specified because column (%s) does not admit NULL values
-1277=The column (%s) must be included in the GROUP BY list
-1276=Too many columns in a GROUP BY clause. Maximum is 8
-1275=The sum of sizes for the columns in the GROUP BY exceeds 120 characters
-1274=Invalid GROUP BY column number (%s)
-1273=An ORDER BY in a UNION must refer to column numbers, not names
-1272=The SELECT list must include the column (%s) from the ORDER BY
-1271=Column number (%s) too big in an ORDER BY clause
-1270=ORDER BY not allowed with SELECT INTO TEMP clause
-1264=Cannot modify table or view used in a subquery
-1263=Cannot repeat the name of a table of the query in the subquery
-1262=A subquery may not be included in the SELECT list
-1261=More than one value returned by a subquery
-1260=Impossible to process the subquery
-1257=The use of SELECT DISTINCT with UNION ALL is not allowed
-1256=An expression may not include ANY or ALL
-1255=The clause COUNT(DISTINCT ... ) may only be used with an existing column
-1254=No more than one DISTINCT is allowed in a SELECT statement
-1253=Impossible to evaluate sums and averages for character columns
-1252=Impossible to GROUP BY an aggregate column (%s)
-1251=The expression is mixing columns with aggregates
-1250=Impossible to evaluate aggregate values with DISTINCT in the expression
-1244=The maximum number of CURSORs (%s) was exceeded
-1243=Cursor not open
-1242=A CURSOR may only be opened for SELECT statements
-1241=The table (%s) in the UPDATE is not the same as the table in the cursor
-1240=There is no current cursor
-1232=CONNECT permission required
-1231=RESOURCE permission required
-1230=DBA permission required
-1229=Impossible to GRANT or REVOKE database privileges for table or view
-1228=Impossible to GRANT privileges on temporary tables
-1227=Impossible to REVOKE privileges for columns
-1226=That user has been GRANTed the same privilege before
-1225=No SELECT permission
-1224=No UPDATE permission
-1223=No DELETE permission
-1222=No INSERT permission
-1221=No CREATE INDEX permission
-1220=Impossible to perform operation. No GRANT privilege
-1216=Too many locked tables
-1215=Impossible to LOCK row for UPDATE
-1214=Impossible to read record. Locked by another user
-1213=Impossible to UNLOCK table. Table not locked or not found
-1212=Record locked by another user
-1211=Table (%s) is already locked
-1210=Impossible to LOCK table (%s). Table locked by another user
-1205=Too many columns in foreign key definition. Maximum is eight
-1204=Duplicate column in foreign key description
-1203=A foreign key must be wholly null or wholly not null
-1202=Impossible to INSERT/UPDATE. There is no reference in table "%s"
-1201=Foreign key already exists
-1200=Cannot add foreign key
-1199=Too many columns in primary key definition. Maximum is eight
-1198=Table (%s) referred to in foreign key definition has no primary key
-1197=The table (%s) has no primary key
-1196=Impossible to DELETE/UPDATE.  There are rows in table "%s" pointing to this row
-1195=Cannot create foreign keys in temporary tables
-1194=Foreign key not found
-1193=A column which is part of the primary key cannot be dropped
-1192=A column which is part of a foreign key cannot be dropped
-1191=A column which is part of a primary key cannot accept NULL values
-1190=Duplicated column in primary key description
-1184=Condition not permitted in the WHERE clause for an OUTER join
-1183=Missing join between tables in an OUTER join
-1182=Illegal join between two tables in an OUTER join
-1181=Too many joined columns between two tables in WHERE clause of UPDATE statement
-1180=Tables incorrectly joined in WHERE clause of VIEW or UPDATE statement
-1176=The transaction must finish before the database is closed
-1175=Impossible to UNLOCK table (%s) within a transaction
-1174=Transaction management is active. WHERE CURRENT clause must be executed after a BEGIN WORK statement
-1173=Not in a transaction
-1172=Transaction management was not started
-1171=Impossible to execute ROLLBACK WORK
-1170=ROLLFORWARD database failed
-1169=The database does not have a LOG file
-1168=Impossible to execute COMMIT WORK
-1167=Impossible to execute BEGIN WORK
-1166=Cannot create log file
-1165=A LOG file name must include the full path name
-1164=Impossible to open the LOG file
-1163=LOG file already exists
-1162=Impossible to remove the LOG file
-1161=Access to LOG files is not allowed
-1160=Invalid collating file
-1153=Impossible to use ROWID in views
-1152=Impossible to INSERT into the VIEW column (%s)
-1151=A VIEW or LOG table cannot be locked
-1150=Impossible to alter VIEW (%s)
-1149=Impossible to create VIEW for temporary table (%s)
-1148=A table included in the VIEW (%s) has been altered
-1147=The number of columns in the VIEW and in the SELECT are different
-1146=Columns in the VIEW for aggregates or expressions must be named
-1145=This VIEW cannot be UPDATEd
-1144=VIEW (%s) not found
-1143=Incorrect values for table (%s) in INSERT through VIEW
-1142=No more than one OUTER join level is allowed for VIEW updating
-1141=Primary key columns are incorrectly listed in VIEW definition
-1140=VIEWs for update cannot be nested
-1133=Execution error
-1132=Error loading procedure (%s)
-1131=Error loading module (%s)
-1130=Module does not exist (%s)
-1129=Module already exists (%s)
-1128=Cosmos Error (%s)
-1127=Sessions number limit reached
-1126=Incorrect Version between monitor and ctsql
-1125=You have been killed by monitor
-1124=Monitor is not active
-1123=Conection Refused
-1122=Unknown user or no permission
-1121=Failure in ULIMIT. Check owner and permissions of your SQL Server
-1120=Value out of range
-1119=Impossible to FETCH next row
-1118=Impossible to retrieve the next row
-1117=Impossible to read a record for update
-1116=There is no current row for UPDATE/DELETE on cursor
-1115=Impossible to DELETE a row
-1114=Impossible to INSERT the row
-1113=Impossible to UPDATE a row in the table
-1112=Impossible to add the SERIAL column (%s) to table
-1111=Impossible to read a temporary file
-1110=Unexpected error while reading a temporary file
-1109=System catalog corrupted
-1108=Impossible to UPDATE the SERIAL column (%s)
-1107=Impossible to open system catalog (%s)
-1106=Impossible to update system catalog (%s)
-1105=Impossible to perform operation.  Not owner of table
-1104=Impossible to read system table (%s)
-1103=SQL error.  Invalid argument received
-1102=System error: Invalid statement received by the SQL
-1101=SQL: Unrecoverable error
-1100=Incorrect version of the SQL server