<?xml version="1.0"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>es.inteco.xbrl</groupId>
    <artifactId>pgc.parent</artifactId>
    <version>1.0.0-SNAPSHOT</version>
  </parent>
  <artifactId>xbrlpgc.ws.client</artifactId>
  <packaging>war</packaging>
  <name>PGC Cliente Web Services</name>
  <description>CLIENTE PAQUETE INTEGRACIÓN SERVICIOS WEB</description>
  <build>
    <finalName>PGCClientWSProject</finalName>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-war-plugin</artifactId>
        <version>2.2</version>
        <configuration>
          <archive>
            <manifest>
              <addDefaultSpecificationEntries>true</addDefaultSpecificationEntries>
              <addDefaultImplementationEntries>true</addDefaultImplementationEntries>
            </manifest>
            <manifestEntries>
              <dbVersion>${dbVersion}</dbVersion>
              <buildNumber>${env.BUILD_NUMBER}</buildNumber>
              <buildDate>${maven.build.timestamp}</buildDate>
              <buildRevision>${buildNumber}</buildRevision>
            </manifestEntries>
          </archive>
        </configuration>
        <executions>
          <execution>
            <id>execution1</id>
            <phase>package</phase>
            <configuration/>
            <goals>
              <goal>manifest</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
  <dependencies>
    <dependency>
      <groupId>es.inteco.xbrl</groupId>
      <artifactId>xbrlpgc.api.pc07</artifactId>
      <version>${project.version}</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>struts</groupId>
      <artifactId>struts</artifactId>
      <version>1.2.7</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.sun.woodstock</groupId>
      <artifactId>webui-jsf</artifactId>
      <version>4.2</version>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>com.sun.faces.extensions</groupId>
      <artifactId>jsf-extensions-dynamic-faces</artifactId>
      <version>0.1</version>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>javax.faces</groupId>
      <artifactId>jsf-api</artifactId>
      <version>1.2_14</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>javax.faces</groupId>
      <artifactId>jsf-impl</artifactId>
      <version>1.2_14</version>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>jstl</groupId>
      <artifactId>jstl</artifactId>
      <version>1.2</version>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>javax.servlet</groupId>
      <artifactId>javax.servlet-api</artifactId>
      <version>3.1.0</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>xbrl.Struts-Layout</groupId>
      <artifactId>Struts-Layout</artifactId>
      <version>1.0.0</version>
      <scope>runtime</scope>
    </dependency>
  </dependencies>
</project>
