<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<parent>
		<groupId>com.code.aon</groupId>
		<artifactId>aon.web.parent</artifactId>
		<version>1.0.5</version>
	</parent>
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.code.aon</groupId>
	<artifactId>aon-web-cms</artifactId>
	<packaging>war</packaging>
	<version>4.3.2</version>
	<description>WEB CMS</description>
	<name>WEB CMS</name>
	<build>
		<finalName>aon-web-cms</finalName>
	</build>
	<properties>
		<dbVersion>2.0.4</dbVersion>
	</properties>
	<dependencies>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.rich.components</artifactId>
			<version>3.7.1</version>
			<scope>compile</scope>
		</dependency>					
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.security</artifactId>
			<version>1.8.0</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.security.bridge</artifactId>
			<version>3.3.0</version>
			<scope>compile</scope>
		</dependency>
	    <dependency>
	      <groupId>com.code.aon</groupId>
	      <artifactId>aon.ui.resources</artifactId>
	      <version>3.7.0</version>
	      <scope>compile</scope>
	    </dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.cms</artifactId>
			<version>3.4.3</version>
			<scope>compile</scope>
			<exclusions>
				<exclusion>
					<groupId>commons-collections</groupId>
					<artifactId>commons-collections</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
		    <groupId>commons-fileupload</groupId>
		    <artifactId>commons-fileupload</artifactId>
		    <version>1.0</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>com.sun</groupId>
			<artifactId>jimi</artifactId>
			<version>1.0</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>commons-net</groupId>
			<artifactId>commons-net</artifactId>
			<version>2.0</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>commons-collections</groupId>
			<artifactId>commons-collections</artifactId>
			<version>3.1</version>
			<scope>compile</scope>
		</dependency>
	</dependencies>
</project>