package es.code.nominasta.entity;
// Generated by Expand 2.0.1 

import com.transtools.expand.annotation.DataDefinition;
import com.transtools.expand.annotation.Lines;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Categoria generated by Expand 2.0.1
 */
@Entity
@Lines(joinProperty="convenio")
@Table(name="categoria")
public class Categoria  implements java.io.Serializable {

     private CategoriaId id;
     private String nivel;
     private String descripcion;
     private String cno;
     private Basecoti basecoti;
     private Convenio convenio;
     private Epigrafe epigrafe;

    public Categoria() {
    }
	
    public Categoria(CategoriaId id, String nivel) {
        this.id = id;
        this.nivel = nivel;
    }

    public Categoria(CategoriaId id, String nivel, String descripcion, String cno, Basecoti basecoti, Convenio convenio, Epigrafe epigrafe) {
       this.id = id;
       this.nivel = nivel;
       this.descripcion = descripcion;
       this.cno = cno;
       this.basecoti = basecoti;
       this.convenio = convenio;
       this.epigrafe = epigrafe;
    }

    @EmbeddedId    
    @AttributeOverrides( {
        @AttributeOverride(name="codcon", column=@Column(name="codcon", nullable=false, length=2) ), 
        @AttributeOverride(name="cdg", column=@Column(name="cdg", nullable=false, length=2) ) } )
    public CategoriaId getId() {
        return this.id;
    }
    
    public void setId(CategoriaId id) {
        this.id = id;
    }
    
	@DataDefinition(label="Codigo de Nivel Retributivo",descriptionColumn=true)
    @Column(name="nivel", nullable=false, length=2)
    public String getNivel() {
        return this.nivel;
    }
    
    public void setNivel(String nivel) {
        this.nivel = nivel;
    }
    
	@DataDefinition(label="Descripcion de Categoria")
    @Column(name="descripcion", length=35)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    
	@DataDefinition(label="Codigo Nacional O.")
    @Column(name="cno", length=4)
    public String getCno() {
        return this.cno;
    }
    
    public void setCno(String cno) {
        this.cno = cno;
    }
    
	@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="codbas")
    public Basecoti getBasecoti() {
        return this.basecoti;
    }
    
    public void setBasecoti(Basecoti basecoti) {
        this.basecoti = basecoti;
    }
    
	@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="codcon", insertable=false, updatable=false)
    public Convenio getConvenio() {
        return this.convenio;
    }
    
    public void setConvenio(Convenio convenio) {
        this.convenio = convenio;
    }
    
	@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="codepi")
    public Epigrafe getEpigrafe() {
        return this.epigrafe;
    }
    
    public void setEpigrafe(Epigrafe epigrafe) {
        this.epigrafe = epigrafe;
    }


}


