package es.code.nominasta.entity;
// Generated by Expand 2.0.1 

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NszepigId generated by Expand 2.0.1
 */
@Embeddable
public class NszepigId  implements java.io.Serializable {

     private String sea0;
     private String sea1;
     private BigDecimal nea0;
     private BigDecimal nea1;

    public NszepigId() {
    }

    public NszepigId(String sea0, String sea1, BigDecimal nea0, BigDecimal nea1) {
       this.sea0 = sea0;
       this.sea1 = sea1;
       this.nea0 = nea0;
       this.nea1 = nea1;
    }


    @Column(name="sea0", nullable=false, length=3)
    public String getSea0() {
        return this.sea0;
    }
    
    public void setSea0(String sea0) {
        this.sea0 = sea0;
    }

    @Column(name="sea1", nullable=false, length=30)
    public String getSea1() {
        return this.sea1;
    }
    
    public void setSea1(String sea1) {
        this.sea1 = sea1;
    }

    @Column(name="nea0", nullable=false, precision=5)
    public BigDecimal getNea0() {
        return this.nea0;
    }
    
    public void setNea0(BigDecimal nea0) {
        this.nea0 = nea0;
    }

    @Column(name="nea1", nullable=false, precision=5)
    public BigDecimal getNea1() {
        return this.nea1;
    }
    
    public void setNea1(BigDecimal nea1) {
        this.nea1 = nea1;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof NszepigId) ) return false;
		 NszepigId castOther = ( NszepigId ) other; 
         
		 return ( (this.getSea0()==castOther.getSea0()) || ( this.getSea0()!=null && castOther.getSea0()!=null && this.getSea0().equals(castOther.getSea0()) ) )
 && ( (this.getSea1()==castOther.getSea1()) || ( this.getSea1()!=null && castOther.getSea1()!=null && this.getSea1().equals(castOther.getSea1()) ) )
 && ( (this.getNea0()==castOther.getNea0()) || ( this.getNea0()!=null && castOther.getNea0()!=null && this.getNea0().equals(castOther.getNea0()) ) )
 && ( (this.getNea1()==castOther.getNea1()) || ( this.getNea1()!=null && castOther.getNea1()!=null && this.getNea1().equals(castOther.getNea1()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getSea0() == null ? 0 : this.getSea0().hashCode() );
         result = 37 * result + ( getSea1() == null ? 0 : this.getSea1().hashCode() );
         result = 37 * result + ( getNea0() == null ? 0 : this.getNea0().hashCode() );
         result = 37 * result + ( getNea1() == null ? 0 : this.getNea1().hashCode() );
         return result;
   }   
}


