package es.code.nominasta.entity;
// Generated by Expand 2.0.1 

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Nszotpe generated by Expand 2.0.1
 */
@Entity
@Table(name="nszotpe")
public class Nszotpe  implements java.io.Serializable {

     private NszotpeId id;

    public Nszotpe() {
    }

    public Nszotpe(NszotpeId id) {
       this.id = id;
    }

    @EmbeddedId    
    @AttributeOverrides( {
        @AttributeOverride(name="sop0", column=@Column(name="sop0", nullable=false, length=15) ), 
        @AttributeOverride(name="sop1", column=@Column(name="sop1", nullable=false, length=105) ), 
        @AttributeOverride(name="nop0", column=@Column(name="nop0", nullable=false, length=4) ), 
        @AttributeOverride(name="nop1", column=@Column(name="nop1", nullable=false, length=4) ), 
        @AttributeOverride(name="nop2", column=@Column(name="nop2", nullable=false, length=4) ) } )
    public NszotpeId getId() {
        return this.id;
    }
    
    public void setId(NszotpeId id) {
        this.id = id;
    }


}


