bgcolor_color_de_fondo = #ffffff
bgcolor_color_de_fondo_cabecera = #ff0000
color_color_de_texto = #666666
color_color_de_texto_pie = #ff0000
color_color_de_texto_contenido = #666666
color_color_de_texto_menu = #999999
color_color_de_texto_menu_hover = #ff6666
color_color_de_texto_cabecera = #ffffff
color_color_de_texto_link = #ff0000
color_color_de_texto_link_hover = #ff9900
color_color_de_borde = #cccccc
font_fuente = 3
size_tamano_de_fuente = 11
size_tamano_de_fuente_contenido = 12
border_bordes = 1

****************

bgcolor_color_fondo_pagina = #ffffff
font_fuente_texto_pagina = 3
size_tamano_texto_pagina = 11
color_color_texto_pagina = #666666
border_tamano_borde_pagina = 1
color_color_borde_pagina = #cccccc
img_imagen_fondo_pagina =

bgcolor_color_fondo_cabecera = #ff0000
font_fuente_texto_cabecera = 
size_tamano_texto_cabecera = 
color_color_texto_cabecera = #ffffff
border_tamano_borde_cabecera = 
color_color_borde_cabecera = 
img_imagen_fondo_cabecera =
img_mostrar_logo_cabecera = 

border_tamano_borde_imagen = 
color_color_borde_imagen =

bgcolor_color_fondo_titulo = 
font_fuente_texto_titulo = 3
size_tamano_texto_titulo = 12
color_color_texto_titulo = 
border_tamano_borde_titulo =
color_color_borde_titulo = 

bgcolor_color_fondo_menu =
font_fuente_texto_menu =
size_tamano_texto_menu =
color_color_texto_menu = #999999
color_color_texto_menu_hover = #ff6666
size_tamano_texto_menu_hover =
color_color_fondo_menu_hover =
color_color_borde_menu_hover =
color_color_borde_menu = 
border_tamano_borde_menu = 
color_color_borde_menu =

bgcolor_color_fondo_contenido =
font_fuente_texto_contenido =
size_tamano_texto_contenido = 12
color_color_texto_contenido = #666666
color_color_borde_contenido = 
border_tamano_borde_contenido = 
color_color_borde_contenido =
img_imagen_fondo_contenido =

bgcolor_color_fondo_pie =
font_fuente_texto_pie =
size_tamano_texto_pie =
color_color_texto_pie = #ff0000
border_tamano_borde_pie =
color_color_borde_pie =

bgcolor_color_fondo_link =
color_color_texto_link = #ff0000
size_tamano_texto_link =
font_fuente_texto_link =
color_color_texto_hover = #ff9900
size_tamano_texto_hover =
font_fuente_texto_hover =

bgcolor_color_fondo_sidebar = 
color_color_borde_sidebar =

color_color_texto_slogan = 
size_tamano_texto_slogan =
font_fuente_texto_slogan =