<?xml version="1.0" encoding="UTF-8"?>
<project basedir="." default="jboss-4.x.sar">

	<property name="mgr" value="aon-security-mgr" />
	<property name="client" value="aon.security" />
	<property name="version" value="1.9.2" />
	<property name="vendor" value="Consulting &amp; Development" />
	<property name="jar.valve.name" value="valve-${version}" />

    <property name="src.dir" value="src/main/java" />
	<property name="resources.dir" value="src/main/resources" />
	<property name="build.dir" value="${java.io.tmpdir}/classes/security" />
	<property name="ldap.dir" value="${java.io.tmpdir}/ldap" />
	<property name="mgr.dist.dir" value="dist" />
	<property name="client.dist.dir" value="/JAVA/aon-security-${version}" />
	<property name="templates.dir" value="templates" />

    <property name="tomcat.home" value="/SERVER/apache-tomcat-5.5.17"/>
    <property name="tomcat.6.home" value="/SERVER/apache-tomcat-6.0.13"/>
	<property name="jboss.home" value="/SERVER/jboss-4.2.3.GA" />

	<property name="jboss.server.home" value="${jboss.home}/server/default" />
    <property name="jboss.tomcat.home" value="${jboss.server.home}/deploy/jboss-web.deployer"/>

    <!-- classpath and local.classpath must have a value using with a path -->
    <property name="classpath" value=""/>
    <property name="local.classpath" value=""/>

	<!-- Jakarta Commons -->
	<property name="commons.digester.home" value="${user.home}/.m2/repository/commons-digester/commons-digester/1.8.1" />
	<property name="commons.digester.jar" value="commons-digester-1.8.1.jar" />
	<property name="commons.beanutils.home" value="${user.home}/.m2/repository/commons-beanutils/commons-beanutils/1.8.0" />
	<property name="commons.beanutils.jar" value="commons-beanutils-1.8.0.jar" />
	<property name="commons.logging.home" value="${user.home}/.m2/repository/commons-logging/commons-logging/1.1" />
	<property name="commons.logging.jar" value="commons-logging-1.1.jar" />
	<property name="commons.lang.home" value="${user.home}/.m2/repository/commons-lang/commons-lang/2.4" />
	<property name="commons.lang.jar" value="commons-lang-2.4.jar" />
	<property name="commons.io.home" value="${user.home}/.m2/repository/commons-io/commons-io/1.4" />
	<property name="commons.io.jar" value="commons-io-1.4.jar" />

	<!-- AON -->
	<property name="aon.ldap.home" value="${user.home}/.m2/repository/com/code/aon/aon.ldap/1.0.0" />

	<!-- The classpath required to build classes. -->
    <path id="javac.classpath">
		<pathelement path="${classpath}"/>
		<pathelement path="${local.classpath}"/>
        <pathelement path="${commons.logging.home}/${commons.logging.jar}"/>
        <pathelement path="${commons.digester.home}/${commons.digester.jar}"/>
    </path>

    <!-- JBoss Default jars in Lib directory -->
    <property name="jboss.lib" value="${jboss.home}/lib"/>
    <path id="jboss.lib.classpath">
      <pathelement path="${jboss.lib}/jboss-system.jar"/>
      <pathelement path="${jboss.lib}/jboss-common.jar"/>
      <pathelement path="${jboss.lib}/jboss-jmx.jar"/>
    </path>

    <!-- JBoss Server -->
    <path id="jboss.server.classpath">
		<pathelement path="${jboss.server.home}/lib/ojdbc14.jar"/>
        <pathelement path="${jboss.server.home}/lib/servlet-api.jar"/>
		<pathelement path="${jboss.server.home}/lib/jsp-api.jar"/>
		<pathelement path="${jboss.server.home}/lib/jmx-adaptor-plugin.jar"/>
    </path>

    <!-- JBoss Tomcat Container -->
    <path id="jboss.tomcat.container.classpath"> 
		<pathelement path="${jboss.tomcat.home}/jbossweb.jar"/>
    	<pathelement path="${jboss.tomcat.home}/jbossweb-service.jar"/>
    </path> 

    <!-- The classpath required to build classes. -->
    <path id="jboss.javac.classpath">
		<path refid="javac.classpath"/>
		<path refid="jboss.lib.classpath"/>
		<path refid="jboss.server.classpath"/>
		<path refid="jboss.tomcat.container.classpath"/>
    </path>

    <!-- The classpath required to build classes. -->
    <path id="jboss.ldap.javac.classpath">
		<path refid="jboss.javac.classpath"/>
        <pathelement path="${aon.ldap.home}/aon.ldap-1.0.0.jar"/>		
    	<pathelement path="${commons.lang.home}/${commons.lang.jar}"/>
    	<pathelement path="${commons.io.home}/${commons.io.jar}"/>
    </path>

    <!-- Tomcat 5.5.x Container -->
    <path id="tomcat.5.container.classpath">
		<pathelement path="${tomcat.home}/common/lib/jsp-api.jar"/>
		<pathelement path="${tomcat.home}/common/lib/servlet-api.jar"/>
		<pathelement path="${tomcat.home}/common/lib/ojdbc14.jar"/>
		<pathelement path="${tomcat.home}/server/lib/catalina.jar"/>
		<pathelement path="${tomcat.home}/server/lib/catalina-optional.jar"/>
		<pathelement path="${tomcat.home}/server/lib/commons-modeler.jar"/>
    </path>

	<!-- The classpath required to build classes. -->
    <path id="tomcat.5.javac.classpath">
		<path refid="javac.classpath"/>
    	<path refid="tomcat.5.container.classpath"/>
    </path>

    <!-- Tomcat 6.x Container -->
    <path id="tomcat.6.container.classpath">
		<pathelement path="${tomcat.6.home}/lib/jsp-api.jar"/>
		<pathelement path="${tomcat.6.home}/lib/servlet-api.jar"/>
		<pathelement path="${tomcat.6.home}/lib/ojdbc14.jar"/>
		<pathelement path="${tomcat.6.home}/lib/catalina.jar"/>
		<pathelement path="${tomcat.6.home}/lib/tomcat-coyote.jar"/>
    </path>

	<!-- The classpath required to build classes. -->
    <path id="tomcat.6.javac.classpath">
		<path refid="javac.classpath"/>
    	<path refid="tomcat.6.container.classpath"/>
    </path>

    <!-- XDoclet -->
    <path id="xdoclet.task.classpath">
      <path refid="javac.classpath"/>
      <fileset dir="/java.old/xdoclet-1.2.3">
        <include name="**/*.jar"/>
      </fileset>
    </path>
    <property name="xdoclet.task.classpath" refid="xdoclet.task.classpath"/>

    <!-- ===================================================================== -->
    <!-- CLEAN BUILD & DIST                                                    -->
    <!-- ===================================================================== -->

	<target name="clean">
	    <delete dir="${build.dir}" quiet="true" />
	    <delete dir="${mgr.dist.dir}" quiet="true" />
	    <delete dir="${client.dist.dir}" quiet="true" />
		<delete dir="${ldap.dir}" quiet="true" />
	</target>

	<!-- ===================================================================== -->
    <!-- PREPARE                                                               -->
    <!-- ===================================================================== -->
	<target name="prepare" depends="clean">
		<mkdir dir="${build.dir}" />
	    <mkdir dir="${mgr.dist.dir}" />
	    <mkdir dir="${client.dist.dir}" />
	</target>

	<!-- Copy everything. -->
	<target name="copy" description="Copy all aditional files." depends="prepare">
	    <copy todir="${build.dir}">
	      <fileset dir="${resources.dir}">
	        <patternset>
	          <include name="**/*.xml" />
	        </patternset>
	      </fileset>
	    </copy>
	</target>

	<!-- Copy everything. -->
	<target name="copy.ldap" description="Copy all aditional files." depends="prepare">
		<copy file="${resources.dir}/com/code/aon/jaas/client/ast/core/applications_digester.xml"
			tofile="${build.dir}/com/code/aon/jaas/client/ast/core/applications_digester.xml"/>
		<copy file="${resources.dir}/com/code/aon/jaas/vendor/jboss/deployment/vendor_digester.xml"
			tofile="${build.dir}/com/code/aon/jaas/vendor/jboss/deployment/vendor_digester.xml"/>
	</target>
	
    <!-- COMPILE-VALVE -->
	<target name="compile-valve" depends="prepare" >

		<javac destdir="${build.dir}" optimize="on" debug="on">
			<classpath>
		        <pathelement path="${tomcat.5.home}/common/lib/servlet-api.jar"/>
		        <pathelement path="${tomcat.5.home}/server/lib/catalina.jar}"/>
			</classpath>
			<src path="${src.dir}"/>	
			<include name="**/com/code/aon/jaas/valves/**" />
		</javac>

	</target>

	<!-- COMPILE FOR Tomcat 5.5.x -->
	<target name="compile-tomcat-5.5.x" description="Compile for Tomcat 5.5.x" depends="copy" >
		<javac destdir="${build.dir}"
				optimize="${javac.optimize}"
				debug="${javac.debug}"
				depend="${javac.depend}"
				verbose="${javac.verbose}"
				deprecation="${javac.deprecation}"
				includeAntRuntime="${javac.include.ant.runtime}"
				includeJavaRuntime="${javac.include.java.runtime}"
				failonerror="${javac.fail.onerror}"
				target="1.5">
			<src path="${src.dir}"/>
			<classpath refid="tomcat.5.javac.classpath"/>
			<exclude name="com/code/aon/jaas/vendor/jboss/**"/>
			<exclude name="com/code/aon/jaas/valves/SecurityValve.*"/>
  	      	<exclude name="com/code/aon/jaas/auth/Utilities.*" />
		</javac>
	</target>

	<!-- COMPILE FOR Tomcat 6.0.x -->
	<target name="compile-tomcat-6.0.x" description="Compile for Tomcat 6.0.x" depends="copy" >
	    <javac destdir="${build.dir}"
	           optimize="${javac.optimize}"
	           debug="${javac.debug}"
			   depend="${javac.depend}"
			   verbose="${javac.verbose}"
			   deprecation="${javac.deprecation}"
			   includeAntRuntime="${javac.include.ant.runtime}"
			   includeJavaRuntime="${javac.include.java.runtime}"
			   failonerror="${javac.fail.onerror}">
			<src path="${src.dir}"/>
			<classpath refid="tomcat.6.javac.classpath"/>
	        <exclude name="com/code/aon/jaas/vendor/jboss/**"/>
  	      	<exclude name="com/code/aon/jaas/valves/SecurityValve.*"/>
  	      	<exclude name="com/code/aon/jaas/auth/Utilities.*" />
	    </javac>
	</target>

	<!-- COMPILE FOR JBoss -->
	<target name="compile-jboss" description="Compile for JBoss" depends="copy">
	    <javac destdir="${build.dir}"
	           optimize="${javac.optimize}"
	           debug="${javac.debug}"
			   depend="${javac.depend}"
			   verbose="${javac.verbose}"
			   deprecation="${javac.deprecation}"
			   includeAntRuntime="${javac.include.ant.runtime}"
			   includeJavaRuntime="${javac.include.java.runtime}"
			   failonerror="${javac.fail.onerror}">
			<src path="${src.dir}"/>
			<classpath refid="jboss.javac.classpath"/>
	        <exclude name="com/code/aon/jaas/vendor/tomcat/**"/>
  	      	<exclude name="com/code/aon/jaas/auth/Utilities.*" />
	    </javac>
	</target>

	<!-- COMPILE FOR JBoss (LDAP) -->
	<target name="compile-jboss-ldap" description="Compile for JBoss (LDAP)" depends="copy.ldap">
	    <javac destdir="${build.dir}"
	           optimize="${javac.optimize}"
	           debug="true"
			   depend="${javac.depend}"
			   verbose="${javac.verbose}"
			   deprecation="${javac.deprecation}"
			   includeAntRuntime="${javac.include.ant.runtime}"
			   includeJavaRuntime="${javac.include.java.runtime}"
			   failonerror="${javac.fail.onerror}">
			<src path="${src.dir}"/>
			<classpath refid="jboss.ldap.javac.classpath"/>
	    	<include name="com/code/aon/jaas/client/ast/core/**"/>
	        <include name="com/code/aon/jaas/vendor/jboss/LdapLoginModule.java"/>
	    	<include name="com/code/aon/jaas/vendor/jboss/JBossSessionManager.java"/>
	    	<include name="com/code/aon/jaas/vendor/jboss/JBossMainDeployer.java"/>
	    	<include name="com/code/aon/jaas/vendor/jboss/JBossLdap.java"/>
	    	<include name="com/code/aon/jaas/vendor/jboss/deployment/**"/>
	    	<include name="com/code/aon/jaas/valves/**"/>
	    </javac>
	</target>

	<!-- COMPILE FOR Utilities-->
	<target name="compile-utilities" description="Compile for Utilities" depends="copy" >
		<javac destdir="${build.dir}"
				optimize="${javac.optimize}"
				debug="${javac.debug}"
				depend="${javac.depend}"
				verbose="${javac.verbose}"
				deprecation="${javac.deprecation}"
				includeAntRuntime="${javac.include.ant.runtime}"
				includeJavaRuntime="${javac.include.java.runtime}"
				failonerror="${javac.fail.onerror}"
				target="1.5">
			<src path="${src.dir}"/>
			<classpath refid="javac.classpath"/>
			<classpath>
				<pathelement location="${jboss.home}/client/jbossall-client.jar"/>
			</classpath>
			<exclude name="com/code/aon/jaas/auth/session/**"/>
			<exclude name="com/code/aon/jaas/auth/spi/**"/>
			<exclude name="com/code/aon/jaas/valves/**"/>
	        <exclude name="com/code/aon/jaas/vendor/**"/>
		</javac>
	</target>

	<!-- Compile mbeans with XDoclet -->
	<target name="compile-mbean-sources">
    	<taskdef name="jmxdoclet" 
    		classname="xdoclet.modules.jmx.JMXDocletTask" 
	   		classpathref="xdoclet.task.classpath"/>
	    <jmxdoclet destdir="${src.dir}" excludedtags="@version,@author">
	      <fileset dir="${src.dir}">
	        <include name="com/code/aon/jaas/vendor/jboss/*.java"/>
	        <include name="com/code/aon/jaas/vendor/tomcat/*.java"/>
	      </fileset>
	      <mbeaninterface mergedir="${templates.dir}"/>
	    </jmxdoclet>
	</target>

	<target name="utilities.jar" depends="compile-utilities">
		<jar jarfile="${mgr.dist.dir}/utilities.jar">
			<manifest>
				<attribute name="Main-Class" value="com.code.aon.jaas.auth.Utilities"/>
			</manifest>
			<fileset dir="${build.dir}">
				<include name="com/code/aon/jaas/auth/Utilities.class"/>
				<include name="com/code/aon/jaas/client/ast/**"/>
				<include name="com/code/aon/jaas/auth/util/**"/>
				<include name="com/code/aon/jaas/deployment/ast/AstException.class"/>
				<include name="com/code/aon/jaas/storage/**"/>
			</fileset>
		</jar>
	</target>

	<!-- ===================================================================== -->
	<!-- BUILD aon-security-client									   		   -->
	<!-- ===================================================================== -->
	<target name="security-client.jar">
		<jar jarfile="${client.dist.dir}/${client}-${version}.jar">
			<fileset dir="${build.dir}">
				<include name="com/code/aon/jaas/auth/AuthGroup.class"/>
				<include name="com/code/aon/jaas/auth/AuthPrincipal.class"/>
				<include name="com/code/aon/jaas/auth/AonGenericPrincipal.class"/>
				<include name="com/code/aon/jaas/auth/IConstants.class"/>
				<include name="com/code/aon/jaas/auth/session/**"/>
				<include name="com/code/aon/jaas/auth/util/**"/>
				<include name="com/code/aon/jaas/client/ast/**"/>
				<include name="com/code/aon/jaas/client/xml/**"/>
				<include name="com/code/aon/jaas/deployment/DeploymentException.class"/>
				<include name="com/code/aon/jaas/deployment/ast/*.class"/>
				<include name="com/code/aon/jaas/deployment/core/SubDeployerVisitor.class"/>
				<include name="com/code/aon/jaas/deployment/event/**"/>
				<include name="com/code/aon/jaas/storage/**"/>
				<include name="com/code/aon/jaas/vendor/deployment/ast/IVendorDescriptor.class"/>
				<include name="com/code/aon/jaas/valves/**"/>
				<exclude name="com/code/aon/jaas/valves/SecurityValve.class"/>
				<exclude name="com/code/aon/jaas/vendor/tomcat/**"/>
			</fileset>
		</jar>
	</target>

	<!-- ================================================================== -->
	<!-- DEPLOY ON TOMCAT 5.5.x												-->
	<!-- ================================================================== -->
	<target name="tomcat-5.5.x.sar" description="Builds Tomcat 5.5.x version." 
			depends="compile-tomcat-5.5.x, security-client.jar">
	    <!-- Build aon-security-mgr.jar -->
		<jar jarfile="${tomcat.home}/server/lib/${mgr}-${version}.jar">
  	      <fileset dir="${build.dir}">
  	        <include name="com/code/aon/**"/>
  	      	<exclude name="com/code/aon/jaas/auth/Utilities.*" />
			<exclude name="com/code/aon/jaas/auth/spi/InteriorLoginModule.*"/>
  	      	<exclude name="com/code/aon/jaas/auth/test/**"/>
  	      	<exclude name="com/code/aon/jaas/valves/SecurityValve.*"/>
  	      	<exclude name="com/code/aon/jaas/vendor/jboss/**"/>
    	  </fileset>
  	    </jar>
	</target>

	<!-- ================================================================== -->
	<!-- DEPLOY ON TOMCAT 6.0.x												-->
	<!-- ================================================================== -->
	<target name="tomcat-6.0.x.sar" description="Builds Tomcat 5.5.x version." 
			depends="compile-tomcat-6.0.x, security-client.jar">
	    <!-- Build aon-security-mgr.jar -->
		<jar jarfile="${tomcat.6.home}/lib/${mgr}-${version}.jar">
			<manifest>
				<attribute name="Built-By" value="${user.name}"/>
				<attribute name="Implementation-Title" value="${mgr}"/>
				<attribute name="Implementation-Version" value="${version}"/> 
				<attribute name="Implementation-Vendor" value="${vendor}"/>
			</manifest>
  	      <fileset dir="${build.dir}">
  	        <include name="com/code/aon/**"/>
  	      	<exclude name="com/code/aon/jaas/auth/Utilities.*" />
  	        <exclude name="com/code/aon/jaas/auth/spi/InteriorLoginModule.*"/>
  	      	<exclude name="com/code/aon/jaas/auth/test/**"/>
  	      	<exclude name="com/code/aon/jaas/valves/SecurityValve.*"/>
  	      	<exclude name="com/code/aon/jaas/vendor/jboss/**"/>
    	  </fileset>
  	    </jar>
	</target>

	<!-- ================================================================== -->
	<!-- DEPLOY INTERIOR ON TOMCAT 5.5.17									-->
	<!-- ================================================================== -->
	<target name="interior.sar" description="Builds all jar files." 
			depends="compile-tomcat-5.5.x, security-client.jar">
	    <!-- Build aon-security-mgr.jar -->
		<jar jarfile="${mgr.dist.dir}/${mgr}-${version}.jar">
  	      <fileset dir="${build.dir}">
  	        <include name="com/code/aon/jaas/auth/**"/>
  	        <exclude name="com/code/aon/jaas/auth/spi/XMLLoginModule.*"/>
    	  </fileset>
  	    </jar>
	</target>

	<!-- ===================================================================== -->
	<!-- DEPLOY ON JBOSS 4.x										   		   -->
	<!-- ===================================================================== -->
	<target name="jboss-4.x.sar" description="Builds all jar files." 
			depends="compile-jboss, security-client.jar">
	    <!-- Build aon-security-mgr.jar -->
	    <jar jarfile="${mgr.dist.dir}/${mgr}-${version}.jar">
	      <fileset dir="${build.dir}">
	        <include name="com/code/aon/**"/>
  	      	<exclude name="com/code/aon/jaas/auth/test/**" />
  	      	<exclude name="com/code/aon/jaas/auth/Utilities.*" />
  	      	<exclude name="com/code/aon/jaas/valves/SecurityValve.*" />
  	      	<exclude name="com/code/aon/jaas/vendor/tomcat/**" />
	      </fileset>
	    </jar>
    	<jar jarfile="${jboss.server.home}/deploy/${mgr}.sar">
			<manifest>
				<attribute name="Built-By" value="${user.name}"/>
				<attribute name="Implementation-Title" value="${mgr}"/>
				<attribute name="Implementation-Version" value="${version}"/> 
				<attribute name="Implementation-Vendor" value="${vendor}"/>
			</manifest>
			<fileset dir="${commons.beanutils.home}">
				<include name="${commons.beanutils.jar}"/>
			</fileset>
    		<fileset dir="${commons.digester.home}">
				<include name="${commons.digester.jar}"/>
			</fileset>

			<fileset dir="${mgr.dist.dir}">
				<include name="${mgr}-${version}.jar"/>
			</fileset>
			<fileset dir="${resources.dir}">
				<include name="**/*service.xml"/>
			</fileset>
	    </jar>
	</target>

	<!-- ===================================================================== -->
	<!-- DEPLOY ON JBOSS 4.x (LDAP)											   -->
	<!-- ===================================================================== -->
	<target name="jboss-4.x.ldap.sar" description="Builds all jar files." 
			depends="compile-jboss-ldap">
	    <!-- Build aon-security-mgr.jar -->
	    <jar jarfile="${mgr.dist.dir}/${mgr}-${version}.jar">
	      <fileset dir="${build.dir}">
	        <include name="com/code/aon/**"/>
  	      	<exclude name="com/code/aon/jaas/auth/test/**" />
  	      	<exclude name="com/code/aon/jaas/auth/Utilities.*" />
  	      	<exclude name="com/code/aon/jaas/valves/SecurityValve.*" />
  	      	<exclude name="com/code/aon/jaas/vendor/tomcat/**" />
	      </fileset>
	    </jar>
		<mkdir dir="${ldap.dir}" />
		<copy file="${resources.dir}/META-INF/jboss-service.xml.ldap"
			tofile="${ldap.dir}/META-INF/jboss-service.xml"/>
		<jar jarfile="${jboss.server.home}/deploy/${mgr}-ldap.sar">
			<manifest>
				<attribute name="Built-By" value="${user.name}"/>
				<attribute name="Implementation-Title" value="${mgr}"/>
				<attribute name="Implementation-Version" value="${version}"/> 
				<attribute name="Implementation-Vendor" value="${vendor}"/>
			</manifest>
    		<fileset dir="${commons.beanutils.home}">
				<include name="${commons.beanutils.jar}"/>
			</fileset>
       		<fileset dir="${commons.digester.home}">
   				<include name="${commons.digester.jar}"/>
   			</fileset>
    		<fileset dir="${commons.lang.home}">
				<include name="${commons.lang.jar}"/>
			</fileset>
    		<fileset dir="${commons.io.home}">
				<include name="${commons.io.jar}"/>
			</fileset>
    		<fileset dir="${aon.ldap.home}">
				<include name="aon.ldap-1.0.0.jar"/>
			</fileset>
			<fileset dir="${mgr.dist.dir}">
				<include name="${mgr}-${version}.jar"/>
			</fileset>
			<fileset dir="${ldap.dir}">
				<include name="**/*.xml"/>
			</fileset>
	    </jar>
	</target>

	<!-- ===================================================================== -->
	<!-- INSTALL 													   		   -->
	<!-- ===================================================================== -->
	<target name="install" description="Builds all jar files." depends="security-client.jar">
		<exec dir="/java/maven-2.0.7/bin" executable="cmd" >
		  <arg line="/c install-aon.security.client.bat ${client.dist.dir} ${client} ${version}"/>
		</exec>
	</target>

	<!-- ===================================================================== -->
	<!-- DEPLOY INHOUSE												   		   -->
	<!-- ===================================================================== -->
	<target name="deploy-inhouse" description="Builds all jar files." depends="security-client.jar">
		<exec dir="/java/maven-2.0.7/bin" executable="cmd" >
		  <arg line="/c deploy-aon.security.client.bat ${client.dist.dir} ${client} ${version} inhouse"/>
		</exec>
	</target>

	<!-- ===================================================================== -->
	<!-- DEPLOY SNAPSHOT												   		   -->
	<!-- ===================================================================== -->
	<target name="deploy-snapshot" description="Builds all jar files." depends="security-client.jar">
		<exec dir="/java/maven-2.0.7/bin" executable="cmd" >
		  <arg line="/c deploy-aon.security.client.bat ${client.dist.dir} ${client} ${version} snapshot"/>
		</exec>
	</target>

</project>