<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>com.code.aon</groupId>
		<artifactId>aon.parent</artifactId>
		<version>9.23-SNAPSHOT</version>
	</parent>
	<groupId>net.aonsolutions</groupId>
	<artifactId>aon.external.sources</artifactId>
	<name>AON EXTERNAL SOURCES</name>
	<description>AON EXTERNAL SOURCES [SII]</description>

	<dependencies>
		<dependency>
			<groupId>javax.xml.ws</groupId>
			<artifactId>jaxws-api</artifactId>
			<version>2.3.1</version>
		</dependency>
		<!-- https://mvnrepository.com/artifact/javax.wsdl/com.springsource.javax.wsdl -->

		<!-- Migrating From Java 8 To Java 11. Instead of using the deprecated 
			JAXB (java.xml.bind) module, use the following artifacts. -->
		<dependency>
			<groupId>javax.xml.bind</groupId>
			<artifactId>jaxb-api</artifactId>
			<version>2.3.1</version>
		</dependency>
		<dependency>
			<groupId>com.sun.xml.bind</groupId>
			<artifactId>jaxb-core</artifactId>
			<version>2.3.0.1</version>
		</dependency>
		<dependency>
			<groupId>com.sun.xml.bind</groupId>
			<artifactId>jaxb-impl</artifactId>
			<version>2.3.2</version>
		</dependency>

		<!-- Migrating From Java 8 To Java 11. Instead of using the deprecated 
			JAX-WS (java.xml.ws) module, use the following artifacts. -->
		<dependency>
			<groupId>com.sun.xml.ws</groupId>
			<artifactId>jaxws-ri</artifactId>
			<version>2.3.2</version>
			<type>pom</type>
                       <exclusions>
                        <exclusion>
                            <groupId>jakarta.mail</groupId>
                            <artifactId>jakarta.mail-api</artifactId>
                        </exclusion>
                        </exclusions>
		</dependency>
	</dependencies>

<!--  	<build>
		<plugins>

			<plugin>
				<groupId>com.helger.maven</groupId>
				<artifactId>jaxws-maven-plugin</artifactId>
				<version>2.6.2</version>
				<executions>
					<execution>
						<id>V1_1</id>
						<goals>
							<goal>wsimport</goal>
						</goals>
						<configuration>
							<wsdlUrls>

								AEAT WSDL URLS VERSION 1.1

								<wsdlUrl>https://www.agenciatributaria.es/static_files/AEAT/Contenidos_Comunes/La_Agencia_Tributaria/Modelos_y_formularios/Suministro_inmediato_informacion/FicherosSuministros/V_1_1/SuministroFactEmitidas.wsdl</wsdlUrl>
								<wsdlUrl>https://www.agenciatributaria.es/static_files/AEAT/Contenidos_Comunes/La_Agencia_Tributaria/Modelos_y_formularios/Suministro_inmediato_informacion/FicherosSuministros/V_1_1/SuministroFactRecibidas.wsdl</wsdlUrl>
								<wsdlUrl>https://www.agenciatributaria.es/static_files/AEAT/Contenidos_Comunes/La_Agencia_Tributaria/Modelos_y_formularios/Suministro_inmediato_informacion/FicherosSuministros/V_1_1/SuministroBienesInversion.wsdl</wsdlUrl>
								<wsdlUrl>https://www.agenciatributaria.es/static_files/AEAT/Contenidos_Comunes/La_Agencia_Tributaria/Modelos_y_formularios/Suministro_inmediato_informacion/FicherosSuministros/V_1_1/SuministroOpIntracomunitarias.wsdl</wsdlUrl>
								<wsdlUrl>https://www.agenciatributaria.es/static_files/AEAT/Contenidos_Comunes/La_Agencia_Tributaria/Modelos_y_formularios/Suministro_inmediato_informacion/FicherosSuministros/V_1_1/SuministroCobrosEmitidas.wsdl</wsdlUrl>
								<wsdlUrl>https://www.agenciatributaria.es/static_files/AEAT/Contenidos_Comunes/La_Agencia_Tributaria/Modelos_y_formularios/Suministro_inmediato_informacion/FicherosSuministros/V_1_1/SuministroOpTrascendTribu.wsdl</wsdlUrl>
								<wsdlUrl>https://www.agenciatributaria.es/static_files/AEAT/Contenidos_Comunes/La_Agencia_Tributaria/Modelos_y_formularios/Suministro_inmediato_informacion/FicherosSuministros/V_1_1/SuministroPagosRecibidas.wsdl</wsdlUrl>
								<wsdlUrl>https://www.agenciatributaria.es/static_files/AEAT/Contenidos_Comunes/La_Agencia_Tributaria/Modelos_y_formularios/Suministro_inmediato_informacion/FicherosSuministros/V_1_1/SuministroInmueblesAdicionales.wsdl</wsdlUrl>

							</wsdlUrls>
							<sourceDestDir>src/main/java</sourceDestDir>
						</configuration>
					</execution>
				</executions>
			</plugin>
			
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>jaxb2-maven-plugin</artifactId>
				<version>1.5</version>
				<executions>
					<execution>
						<id>xjc</id>
						<goals>
							<goal>xjc</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<schemaDirectory> src/main/xsd/tbai </schemaDirectory>
					<schemaDirectory> src/main/xsd/verifactu </schemaDirectory>
					<outputDirectory> src/main/java </outputDirectory>
				</configuration>
			</plugin>
		</plugins>
	</build>  -->
</project>
