<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<parent>
		<artifactId>aon.web.parent</artifactId>
		<groupId>com.code.aon</groupId>
		<version>1.0.4</version>
	</parent>
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.code.aon</groupId>
	<artifactId>aon-web-payroll</artifactId>
	<packaging>war</packaging>
	<name>AON WEB PAYROLL</name>
	<version>0.16.0</version>
	<description>AON WEB PAYROLL</description>
	<build>
		<finalName>aon-payroll</finalName>
	</build>
	<dependencies>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.payroll</artifactId>
			<version>0.17.0</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.rich.components</artifactId>
			<version>3.7.1</version>
			<scope>compile</scope>
		</dependency>		
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.resources</artifactId>
			<version>3.5.1</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.audit</artifactId>
			<version>0.10.0</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
		    <groupId>commons-el</groupId>
		    <artifactId>commons-el</artifactId>
		    <version>1.0</version>
			<scope>runtime</scope>
		</dependency>					
	</dependencies>
</project>