<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>com.code.aon</groupId>
		<artifactId>aon.parent</artifactId>
		<version>9.23-SNAPSHOT</version>
	</parent>
	<groupId>net.aonsolutions.core</groupId>
	<artifactId>aeat</artifactId>
        <name>aeat Java Classes of I.R.P.F XSD schemas</name>
        <description>aon Solutions JAXB Java classes of I.R.P.F XSD validation schemas</description>
	<dependencies>
		<!--
		 Migrating From Java 8 To Java 11.
		 Instead of using the deprecated JAXB (java.xml.bind) module, use the following artifacts.
		 -->
		 <dependency>
			 <groupId>javax.xml.bind</groupId>
			 <artifactId>jaxb-api</artifactId>
			 <version>2.3.1</version>
		 </dependency>
		 <dependency>
		     <groupId>com.sun.xml.bind</groupId>
		     <artifactId>jaxb-core</artifactId>
		     <version>2.3.0.1</version>
		 </dependency>
		 <dependency>
			 <groupId>com.sun.xml.bind</groupId>
			 <artifactId>jaxb-impl</artifactId>
			 <version>2.3.2</version>
		 </dependency>

	</dependencies>
	<build>
		<plugins>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>jaxb2-maven-plugin</artifactId>
				<version>2.5.0</version>
				<dependencies>
					<!--
					 Migrating From Java 8 To Java 11.
					 Instead of using the deprecated JAF (java.activation) module, use the following artifacts.
					 -->
					<dependency>
					    <groupId>com.sun.activation</groupId>
					    <artifactId>javax.activation</artifactId>
					    <version>1.2.0</version>
					</dependency>
				</dependencies>
				<executions>
					<execution>
						<id>xjc-2020</id>
						<goals>
							<goal>xjc</goal>
						</goals>
						<configuration>
							<sources>
                    						<source>src/main/xsd/AEATRetenciones2020.xsd</source>
					                </sources>
							<packageName>net.aonsolutions.core.aeat.v2020.jaxb</packageName>
					                <!--
					                    Don't clear the output directory before generating the sources.
					                    Clearing the output directory removes the 2020 schema from above.
					                -->
					                <clearOutputDir>false</clearOutputDir>
						</configuration>
                                        </execution>
					<execution>
						<id>xjc-2021</id>
						<goals>
							<goal>xjc</goal>
						</goals>
						<configuration>
							<sources>
                    						<source>src/main/xsd/AEATRetenciones2021.xsd</source>
					                </sources>
							<packageName>net.aonsolutions.core.aeat.v2021.jaxb</packageName>
					                <!--
					                    Don't clear the output directory before generating the sources.
					                    Clearing the output directory removes the 2020 schema from above.
					                -->
					                <clearOutputDir>false</clearOutputDir>
						</configuration>
                                        </execution>
					<execution>
						<id>xjc-2022</id>
						<goals>
							<goal>xjc</goal>
						</goals>
						<configuration>
							<sources>
                    						<source>src/main/xsd/AEATRetenciones2022.xsd</source>
					                </sources>
							<packageName>net.aonsolutions.core.aeat.v2022.jaxb</packageName>
					                <!--
					                    Don't clear the output directory before generating the sources.
					                    Clearing the output directory removes the 2020 schema from above.
					                -->
					                <clearOutputDir>false</clearOutputDir>
						</configuration>
                                        </execution>
					<execution>
						<id>xjc-2023</id>
						<goals>
							<goal>xjc</goal>
						</goals>
						<configuration>
							<sources>
                    						<source>src/main/xsd/AEATRetenciones2023.xsd</source>
					                </sources>
							<packageName>net.aonsolutions.core.aeat.v2023.jaxb</packageName>
					                <!--
					                    Don't clear the output directory before generating the sources.
					                    Clearing the output directory removes the 2023 schema from above.
					                -->
					                <clearOutputDir>false</clearOutputDir>
						</configuration>
                                        </execution>
				</executions>
			</plugin>
		</plugins>
	</build>

</project>
