<?xml version="1.0" encoding="utf-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <parent>
    <groupId>com.code.aon</groupId>
    <artifactId>aon.parent</artifactId>
    <version>9.23-SNAPSHOT</version>
  </parent>
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.esferalia.aon</groupId>
  <artifactId>aon.payroll</artifactId>
  <description>AON PAYROLL</description>
  <name>AON PAYROLL</name>
  <build>
    <plugins>
      <plugin>
        <artifactId>maven-surefire-plugin</artifactId>
        <configuration>
          <workingDirectory>target</workingDirectory>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <configuration>
          <systemProperties>
            <property>
              <name>dbName</name>
              <value>aon_jooq_</value>
            </property>
            <property>
              <name>javax.xml.validation.SchemaFactory:http://www.w3.org/2001/XMLSchema</name>
              <value>com.sun.org.apache.xerces.internal.jaxp.validation.XMLSchemaFactory</value>
            </property>
          </systemProperties>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-jar-plugin</artifactId>
        <executions>
          <execution>
            <goals>
              <goal>test-jar</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
  <dependencies>
  	<dependency>
		<groupId>solutions.aon</groupId>
		<artifactId>aon.sepe</artifactId>
		<version>${project.version}</version>
		<scope>compile</scope>
	</dependency>
    <dependency>
		<groupId>org.htmlunit</groupId>
		<artifactId>htmlunit</artifactId>
		<version>3.1.0</version>
		<scope>compile</scope>
     </dependency>
    <dependency>
      <groupId>com.esferalia.aon</groupId>
      <artifactId>aon.watson</artifactId>
      <version>${project.version}</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.esferalia.aon</groupId>
      <artifactId>aon.occam</artifactId>
      <version>${project.version}</version>
      <scope>compile</scope>
    </dependency>
    <!-- We must remove this as soon as possible. -->
    <dependency>
      <groupId>com.esferalia.aon</groupId>
      <artifactId>aon.entity</artifactId>
      <version>${project.version}</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.esferalia.aon</groupId>
      <artifactId>aon.entity.common</artifactId>
      <version>${project.version}</version>
      <scope>compile</scope>
      <exclusions>
        <exclusion>
          <artifactId>asm</artifactId>
          <groupId>asm</groupId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>com.esferalia.aon</groupId>
      <artifactId>aon.master.jooq</artifactId>
      <version>${project.version}</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.esferalia.aon</groupId>
      <artifactId>aon.calendar</artifactId>
      <version>${project.version}</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.code.aon</groupId>
      <artifactId>aon.company</artifactId>
      <version>${project.version}</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.code.aon</groupId>
      <artifactId>aon.registry</artifactId>
      <version>${project.version}</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.esferalia.aon</groupId>
      <artifactId>aon.salary</artifactId>
      <version>${project.version}</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>net.aonsolutions.core</groupId>
      <artifactId>tgss</artifactId>
      <version>${project.version}</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.13-beta-1</version>
      <type>jar</type>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>com.code.aon</groupId>
      <artifactId>aon.customer</artifactId>
      <version>${project.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-jcl</artifactId>
      <version>1.7.25</version>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>mysql</groupId>
      <artifactId>mysql-connector-java</artifactId>
      <version>8.0.13</version>
      <scope>compile</scope>
      <optional>false</optional>
    </dependency>
    <dependency>
      <groupId>es.aeat</groupId>
      <artifactId>PRET-RW13_shared</artifactId>
      <scope>compile</scope>
      <version>1.00</version>
    </dependency>
    <!--dependency>
      <groupId>es.aeat</groupId>
      <artifactId>ModRet2021</artifactId>
      <scope>compile</scope>
      <version>1.2</version>
    </dependency>
    <dependency>
      <groupId>es.aeat</groupId>
      <artifactId>ModRet2022</artifactId>
      <scope>compile</scope>
      <version>1.1</version>
    </dependency>
    <dependency>
      <groupId>es.aeat</groupId>
      <artifactId>ModRet2023</artifactId>
      <scope>compile</scope>
      <version>1.2</version>
    </dependency-->
    <dependency>
      <groupId>es.aeat</groupId>
      <artifactId>ModRet2024</artifactId>
      <scope>compile</scope>
      <version>1.2</version>
    </dependency>
    <dependency>
      <groupId>com.esferalia.aon</groupId>
      <artifactId>aon.sepe.api</artifactId>
      <version>${project.version}</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>net.aonsolutions.core</groupId>
      <artifactId>aeat</artifactId>
      <version>${project.version}</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>org.apache.commons</groupId>
      <artifactId>commons-math3</artifactId>
      <scope>compile</scope>
      <version>3.6.1</version>
    </dependency>
    <dependency>
      <groupId>net.aonsolutions.core</groupId>
      <artifactId>pool</artifactId>
      <version>${project.version}</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
	  <groupId>org.apache.pdfbox</groupId>
	  <artifactId>pdfbox</artifactId>
	  <version>3.0.0-alpha2</version>
	</dependency>
 
  </dependencies>
</project>
