<?xml version="1.0"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<parent>
		<groupId>com.code.aon</groupId>
		<artifactId>aon.parent</artifactId>
		<version>9.00-SNAPSHOT</version>
	</parent>
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.esferalia.aon</groupId>
	<artifactId>aon.payroll</artifactId>
	<description>AON PAYROLL</description>
	<name>AON PAYROLL</name>
	<build>
		<plugins>
			<plugin>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>2.10</version>
				<configuration>
					<workingDirectory>target</workingDirectory>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<configuration>
					<systemProperties>
						<property>
							<name>dbName</name>
							<value>aon_jooq_</value>
						</property>
					</systemProperties>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-jar-plugin</artifactId>
				<executions>
					<execution>
						<goals>
							<goal>test-jar</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
	<dependencies>

		<dependency>
			<groupId>com.esferalia.aon</groupId>
			<artifactId>aon.watson</artifactId>
			<version>${project.version}</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>com.esferalia.aon</groupId>
			<artifactId>aon.occam</artifactId>
			<version>${project.version}</version>
			<scope>compile</scope>
		</dependency>
		<!-- We must remove this as soon as possible. -->
		<dependency>
			<groupId>com.esferalia.aon</groupId>
			<artifactId>aon.entity</artifactId>
			<version>${project.version}</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>com.esferalia.aon</groupId>
			<artifactId>aon.entity.common</artifactId>
			<version>${project.version}</version>
			<scope>compile</scope>
			<exclusions>
				<exclusion>
					<artifactId>asm</artifactId>
					<groupId>asm</groupId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>com.esferalia.aon</groupId>
			<artifactId>aon.master.jooq</artifactId>
			<version>${project.version}</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>com.esferalia.aon</groupId>
			<artifactId>aon.calendar</artifactId>
			<version>${project.version}</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.company</artifactId>
			<version>${project.version}</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.registry</artifactId>
			<version>${project.version}</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>com.esferalia.aon</groupId>
			<artifactId>aon.salary</artifactId>
			<version>${project.version}</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>net.aonsolutions.core</groupId>
			<artifactId>tgss</artifactId>
			<version>9.00-SNAPSHOT</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.8</version>
			<type>jar</type>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.customer</artifactId>
			<version>${project.version}</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-jcl</artifactId>
			<version>1.5.11</version>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>mysql</groupId>
			<artifactId>mysql-connector-java</artifactId>
			<version>5.1.10</version>
			<scope>compile</scope>
			<optional>false</optional>
		</dependency>

		<dependency>
			<groupId>es.aeat</groupId>
			<artifactId>ModRet2013</artifactId>
			<scope>compile</scope>
			<version>1.00</version>
		</dependency>
		<dependency>
			<groupId>es.aeat</groupId>
			<artifactId>PRET-RW13_shared</artifactId>
			<scope>compile</scope>
			<version>1.00</version>
		</dependency>

		<dependency>
			<groupId>es.aeat</groupId>
			<artifactId>ModRet2016</artifactId>
			<scope>compile</scope>
			<version>1.0</version>
		</dependency>
		<dependency>
			<groupId>es.aeat</groupId>
			<artifactId>ModRet2017</artifactId>
			<scope>compile</scope>
			<version>1.0</version>
		</dependency>
		<dependency>
			<groupId>net.aonsolutions.core</groupId>
			<artifactId>aeat</artifactId>
			<version>9.00-SNAPSHOT</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-math3</artifactId>
			<scope>compile</scope>
			<version>3.2</version>
		</dependency>

		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.pool</artifactId>
			<version>${project.version}</version>
			<scope>compile</scope>
		</dependency>
	</dependencies>
	<profiles>
		<profile>
			<id>rpm-release</id>
			<activation>
				<property>
					<name>rpm.release</name>
					<value>true</value>
				</property>
			</activation>
			<build>
				<plugins>
					<!-- Build el RPM -->
					<plugin>
						<groupId>org.codehaus.mojo</groupId>
						<artifactId>rpm-maven-plugin</artifactId>
						<version>2.0.1</version>
						<extensions>true</extensions>
						<executions>
							<execution>
								<id>rpm-build</id>
								<goals>
									<goal>attached-rpm</goal>
								</goals>
							</execution>
						</executions>

						<configuration>
							<group>Applications/Aon</group>
							<release>${buildNumber}</release>
							<copyright>2015, AON SOLUTIONS S.L.U</copyright>
							<requires>
								<require>slf4j</require>
								<require>antlr</require>
								<require>apache-commons-lang</require>
								<require>mysql-connector-java</require>
								<require>apache-commons-logging</require>
							</requires>
							<mappings>
								<mapping>
									<filemode>644</filemode>
									<username>root</username>
									<groupname>root</groupname>
									<directory>/usr/share/java</directory>
									<dependency>
										<includes>
											<include>org.jooq:jooq</include>
											<include>org.jooq:jool</include>
											<include>org.mvel:mvel2</include>
											<include>commons-cli:commons-cli</include>
											<include>com.code.aon:aon.ql</include>
											<include>com.code.aon:aon.pool</include>
											<include>com.code.aon:aon.common</include>
											<include>net.aonsolutions:aon.tgss</include>
											<include>com.esferalia.aon:aon.aeat</include>
											<include>com.esferalia.aon:aon.entity</include>
											<include>com.esferalia.aon:aon.entity.common</include>
											<include>com.esferalia.aon:aon.occam</include>
											<include>com.esferalia.aon:aon.watson</include>
											<include>com.esferalia.aon:aon.salary</include>
											<include>com.esferalia.aon:aon.master.jooq</include>
											<include>org.apache.commons:commons-math3</include>
											<include>es.aeat:ModRet2015</include>
											<include>es.aeat:PRET-R151_shared</include>
											<include>es.aeat:ModRet2013</include>
											<include>es.aeat:PRET-RW13_shared</include>
										</includes>
									</dependency>
									<sources>
										<source>
											<location>target</location>
											<includes>
												<include>${project.artifactId}-${project.version}.jar</include>
											</includes>
										</source>
										<softlinkSource>
											<location>/usr/share/java/mvel2-2.2.4.Final.jar</location>
											<destination>mvel2.jar</destination>
										</softlinkSource>
										<softlinkSource>
											<location>/usr/share/java/jooq-3.5.2.jar</location>
											<destination>jooq.jar</destination>
										</softlinkSource>
										<softlinkSource>
											<location>/usr/share/java/jool-0.9.6.jar</location>
											<destination>jool.jar</destination>
										</softlinkSource>
										<softlinkSource>
											<location>/usr/share/java/commons-cli-1.2.jar</location>
											<destination>commons-cli.jar</destination>
										</softlinkSource>
										<softlinkSource>
											<location>/usr/share/java/commons-math3-3.2.jar</location>
											<destination>commons-math3.jar</destination>
										</softlinkSource>
										<softlinkSource>
											<location>/usr/share/java/aon.tgss-${project.version}.jar</location>
											<destination>aon-tgss.jar</destination>
										</softlinkSource>
										<softlinkSource>
											<location>/usr/share/java/${project.artifactId}-${project.version}.jar</location>
											<destination>aon-payroll.jar</destination>
										</softlinkSource>
										<softlinkSource>
											<location>/usr/share/java/aon.ql-${project.version}.jar</location>
											<destination>aon-ql.jar</destination>
										</softlinkSource>
										<softlinkSource>
											<location>/usr/share/java/aon.pool-${project.version}.jar</location>
											<destination>aon-pool.jar</destination>
										</softlinkSource>
										<softlinkSource>
											<location>/usr/share/java/aon.common-${project.version}.jar</location>
											<destination>aon-common.jar</destination>
										</softlinkSource>
										<softlinkSource>
											<location>/usr/share/java/aon.watson-${project.version}.jar</location>
											<destination>aon-watson.jar</destination>
										</softlinkSource>
										<softlinkSource>
											<location>/usr/share/java/aon.occam-${project.version}.jar</location>
											<destination>aon-occam.jar</destination>
										</softlinkSource>
										<softlinkSource>
											<location>/usr/share/java/aon.salary-${project.version}.jar</location>
											<destination>aon-salary.jar</destination>
										</softlinkSource>
										<softlinkSource>
											<location>/usr/share/java/aon.master.jooq-${project.version}.jar</location>
											<destination>aon-master-jooq.jar</destination>
										</softlinkSource>
										<softlinkSource>
											<location>/usr/share/java/aon.entity-${project.version}.jar</location>
											<destination>aon-entity.jar</destination>
										</softlinkSource>
										<softlinkSource>
											<location>/usr/share/java/aon.entity.common-${project.version}.jar</location>
											<destination>aon-entity-common.jar</destination>
										</softlinkSource>
										<softlinkSource>
											<location>/usr/share/java/aon.aeat-${project.version}.jar</location>
											<destination>aon-aeat.jar</destination>
										</softlinkSource>
										<softlinkSource>
											<location>/usr/share/java/ModRet2015-2.0.jar</location>
											<destination>ModRet2015.jar</destination>
										</softlinkSource>
										<softlinkSource>
											<location>/usr/share/java/PRET-R151_shared-2.0.jar</location>
											<destination>PRET-R151_shared.jar</destination>
										</softlinkSource>
										<softlinkSource>
											<location>/usr/share/java/ModRet2013-1.00.jar</location>
											<destination>ModRet2013.jar</destination>
										</softlinkSource>
										<softlinkSource>
											<location>/usr/share/java/PRET-RW13_shared-1.00.jar</location>
											<destination>PRET-RW13_shared</destination>
										</softlinkSource>
									</sources>
								</mapping>
								<mapping>
									<sources>
										<source>
											<location>src/main/scripts</location>
										</source>
									</sources>
									<filemode>555</filemode>
									<username>root</username>
									<groupname>root</groupname>
									<directory>/usr/bin</directory>
								</mapping>
							</mappings>
						</configuration>
					</plugin>
				</plugins>
			</build>
		</profile>
	</profiles>
</project>
