<?xml version="1.0"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<parent>
		<groupId>com.code.aon</groupId>
		<artifactId>aon.parent</artifactId>
		<version>9.13.3</version>
	</parent>
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.esferalia.aon</groupId>
	<artifactId>aon.gwt.aio</artifactId>
	<packaging>jar</packaging>
	<description>AON GWT AIO</description>
	<name>AON GWT AIO</name>
	<build>
		<plugins>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>gwt-maven-plugin</artifactId>
				<version>2.8.0</version>
				<configuration>
					<module>com.esferalia.aon.gwt.aio.Aio</module>
					<webappDirectory>${project.build.outputDirectory}</webappDirectory>
					<compileSourcesArtifacts>
					  <compileSourcesArtifact>com.esferalia.aon:aon.gwt.common</compileSourcesArtifact>  
					  <compileSourcesArtifact>com.esferalia.aon:aon.gwt.api</compileSourcesArtifact>  
					  <compileSourcesArtifact>com.esferalia.aon:aon.occam</compileSourcesArtifact>
					  <compileSourcesArtifact>com.esferalia.aon:aon.gwt.issues</compileSourcesArtifact>  
					  <compileSourcesArtifact>com.esferalia.aon:aon.gwt.document</compileSourcesArtifact>
					  <compileSourcesArtifact>com.esferalia.aon:aon.gwt.stat</compileSourcesArtifact>
					  <compileSourcesArtifact>com.esferalia.aon:aon.gwt.dump</compileSourcesArtifact>
					  <compileSourcesArtifact>net.aonsolutions:aon.gwt.warehouse</compileSourcesArtifact>
					  <compileSourcesArtifact>net.aonsolutions:aon.gwt.udapa</compileSourcesArtifact>
					  <compileSourcesArtifact>net.aonsolutions.polymer:aon.gwt.polymer</compileSourcesArtifact>  
					  <compileSourcesArtifact>com.esferalia.aon:aon.gwt.templates</compileSourcesArtifact>
					  <compileSourcesArtifact>net.aonsolutions:aon.gwt.sii</compileSourcesArtifact>
					  <compileSourcesArtifact>net.aonsolutions:aon.gwt.invoice</compileSourcesArtifact>
					  <compileSourcesArtifact>net.aonsolutions:aon.gwt.seres</compileSourcesArtifact>
					</compileSourcesArtifacts>
					<extraJvmArgs>-Xmx2048M</extraJvmArgs>
				</configuration>
				<executions>
					<execution>
						<phase>prepare-package</phase>
						<goals>
							<goal>compile</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>com.google.code.maven-replacer-plugin</groupId>
				<artifactId>replacer</artifactId>
				<version>1.5.3</version>
				<executions>
					<execution>
						<phase>prepare-package</phase>
						<goals>
							<goal>replace</goal>
						</goals>                   
					</execution>
				</executions>
				<configuration>
					<basedir>${project.basedir}/target/classes</basedir>
					<includes>
						<include>**/gwt/clean/clean.css</include>
					</includes>
					<regexFlags>
					    <regexFlag>MULTILINE</regexFlag>
					    <regexFlag>CASE_INSENSITIVE</regexFlag>
					</regexFlags>
					<replacements>
						<replacement>
							<token>^([a-z: \t,]*)\{$</token>
							<value>/** $1 */
.disabled-by-aon {</value>
						</replacement>         
					</replacements>
				</configuration>
			</plugin>
		</plugins>
	</build>


	<dependencies>

		<dependency>
			<groupId>com.google.gwt</groupId>
			<artifactId>gwt-servlet</artifactId>
			<version>2.8.0</version>
			<scope>compile</scope>
		</dependency>

		<dependency>
			<groupId>com.google.gwt</groupId>
			<artifactId>gwt-user</artifactId>
			<version>2.8.0</version>
			<scope>provided</scope>
		</dependency>
	
		<dependency>
			<groupId>com.google.gwt</groupId>
			<artifactId>gwt-dev</artifactId>
			<version>2.8.0</version>
			<scope>provided</scope>
		</dependency>

		<dependency>
			<groupId>com.esferalia.aon</groupId>
			<artifactId>aon.occam</artifactId>
			<version>${project.version}</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>com.esferalia.aon</groupId>
			<artifactId>aon.occam</artifactId>
			<version>${project.version}</version>
			<scope>provided</scope>
			<classifier>sources</classifier>
		</dependency>
		<dependency>
			<groupId>com.esferalia.aon</groupId>
			<artifactId>aon.gwt.common</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>com.esferalia.aon</groupId>
			<artifactId>aon.gwt.common</artifactId>
			<version>${project.version}</version>
			<scope>compile</scope>
			<classifier>sources</classifier>
		</dependency>
		<dependency>
			<groupId>com.esferalia.aon</groupId>
			<artifactId>aon.gwt.api</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>com.esferalia.aon</groupId>
			<artifactId>aon.gwt.api</artifactId>
			<version>${project.version}</version>
			<scope>compile</scope>
			<classifier>sources</classifier>
		</dependency>
		
		<!-- MODULES -->
		
		<dependency>
			<groupId>com.esferalia.aon</groupId>
			<artifactId>aon.gwt.issues</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>com.esferalia.aon</groupId>
			<artifactId>aon.gwt.issues</artifactId>
			<version>${project.version}</version>
			<scope>compile</scope>
			<classifier>sources</classifier>
		</dependency>
		
		<dependency>
			<groupId>com.esferalia.aon</groupId>
			<artifactId>aon.gwt.document</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>com.esferalia.aon</groupId>
			<artifactId>aon.gwt.document</artifactId>
			<version>${project.version}</version>
			<scope>compile</scope>
			<classifier>sources</classifier>
		</dependency>
		
		<dependency>
			<groupId>com.esferalia.aon</groupId>
			<artifactId>aon.gwt.template</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>com.esferalia.aon</groupId>
			<artifactId>aon.gwt.template</artifactId>
			<version>${project.version}</version>
			<scope>compile</scope>
			<classifier>sources</classifier>
		</dependency>
		
		<dependency>
			<groupId>net.aonsolutions</groupId>
			<artifactId>aon.gwt.sii</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>net.aonsolutions</groupId>
			<artifactId>aon.gwt.sii</artifactId>
			<version>${project.version}</version>
			<scope>compile</scope>
			<classifier>sources</classifier>
		</dependency>
		
		<dependency>
			<groupId>net.aonsolutions</groupId>
			<artifactId>aon.gwt.invoice</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>net.aonsolutions</groupId>
			<artifactId>aon.gwt.invoice</artifactId>
			<version>${project.version}</version>
			<scope>compile</scope>
			<classifier>sources</classifier>
		</dependency>
		
		<dependency>
			<groupId>net.aonsolutions</groupId>
			<artifactId>aon.gwt.seres</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>net.aonsolutions</groupId>
			<artifactId>aon.gwt.seres</artifactId>
			<version>${project.version}</version>
			<scope>compile</scope>
			<classifier>sources</classifier>
		</dependency>
		
		<dependency>
			<groupId>com.esferalia.aon</groupId>
			<artifactId>aon.gwt.stat</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>com.esferalia.aon</groupId>
			<artifactId>aon.gwt.stat</artifactId>
			<version>${project.version}</version>
			<scope>compile</scope>
			<classifier>sources</classifier>
		</dependency>
		
		<dependency>
			<groupId>net.aonsolutions</groupId>
			<artifactId>aon.gwt.warehouse</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>net.aonsolutions</groupId>
			<artifactId>aon.gwt.warehouse</artifactId>
			<version>${project.version}</version>
			<scope>compile</scope>
			<classifier>sources</classifier>
		</dependency>
		
		<dependency>
			<groupId>net.aonsolutions</groupId>
			<artifactId>aon.gwt.udapa</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>net.aonsolutions</groupId>
			<artifactId>aon.gwt.udapa</artifactId>
			<version>${project.version}</version>
			<scope>compile</scope>
			<classifier>sources</classifier>
		</dependency>
		
		<dependency>
			<groupId>com.esferalia.aon</groupId>
			<artifactId>aon.gwt.dump</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>com.esferalia.aon</groupId>
			<artifactId>aon.gwt.dump</artifactId>
			<version>${project.version}</version>
			<scope>compile</scope>
			<classifier>sources</classifier>
		</dependency>
		
		<!-- ******* -->
		
		<dependency>
 			<groupId>com.vaadin.polymer</groupId>
 			<artifactId>vaadin-gwt-polymer-elements</artifactId>
 			<version>1.7.0.0</version> 
  			<scope>provided</scope>
		</dependency>
		
		<dependency>
 			<groupId>net.aonsolutions.polymer</groupId>
 			<artifactId>aon.gwt.polymer</artifactId>
 			<version>${project.version}</version> 
  			<scope>provided</scope>
		</dependency>
		 
	</dependencies>
  <profiles>
    <profile>
    <id>dev</id>
    <activation>
      <property>
        <name>gwt.working</name>
        <value>true</value>
      </property>
    </activation>
    <build>
      <plugins>
        <plugin>
          <groupId>org.codehaus.mojo</groupId>
          <artifactId>gwt-maven-plugin</artifactId>
          <configuration>
            <draftCompile>true</draftCompile>
	   		<module>com.esferalia.aon.gwt.aio.WorkingAio</module>
          </configuration>
        </plugin>
      </plugins>
    </build>
    </profile>
  </profiles>

</project>
