bgcolor_color_de_fondo = #44607e
bgcolor_color_de_fondo_cabecera = #44607e
bgcolor_color_de_fondo_menu = #44607e
bgcolor_color_de_fondo_contenido = #FFFFFF
color_texto = #000000
color_cabecera_color_de_texto_cabecera = #FFFFFF
color_contenidos_color_de_texto_link = #415d8b
color_pie_color_de_texto = #ffffff
font_fuente = 3
size_tamano_de_fuente = 11
size_tamano_de_fuente_contenidos = 14
size_cabecera_tamano_de_fuente = 18
size_pie_tamano_de_fuente = 12
border_bordes = 0

img_imagen_de_fondo = fondo.jpg
color_color_bordes= #f70e76
color_color_titulo= #f70e76
color_texto_menu= #FFFFFF