showDomainSearch=true
showDomainBack=true
showDomainCapabilities=true
showDomainManagement=true
showDomainStatus=true

showDomainUserPasswordExpirationTimestamp=true
showDomainUserChangePassword=true

showDomainApplicationReset=true
showDomainApplicationStatus=true

showDBConnections=true
showApplications=true
showConfig=true

showDBConnectionDetails=true
showDBConnectionScope=true
showDBConnectionWorkGroup=true
