showDomainManagement=true
showDomainActive=true

showDomainUserPasswordExpirationTimestamp=true
showDomainUserChangePassword=true

showDomainApplicationReset=true
editDomainApplicationActive=true

showDBConnections=true
showApplications=true
showConfig=true

showDBConnectionDetails=true
showDBConnectionScope=true
showDBConnectionWorkGroup=true
