package com.esferalia.aon.occam.api.model.type;

import com.esferalia.aon.watson.util.AonStringUtils;

// Á --> \u00C1 á --> \u00E1
// É --> \u00C9 é --> \u00E9
// Í --> \u00CD í --> \u00ED
// Ó --> \u00D3 ó --> \u00F3
// Ú --> \u00DA ú --> \u00FA
// Ñ --> \u00D1 ñ --> \u00F1
// º --> \u00AA ª --> \u00BA
// ¿ --> \u00BF 
// Ç --> \u00C7	ç --> \u00E7

/**
 * 
 * http://www.agenciatributaria.es/AEAT.internet/Inicio_es_ES/_Configuracion_/_top_/Ayuda/Tablas_auxiliares_de_domicilios__provincias__municipios____/Tabla_de_Tipos_de_Vias/Tabla_de_Tipos_de_Vias.shtml
 *
 */
public enum StreetType {
	
	ACCE 	("ACCE ","AC","ACCES"),
	ACCES	("ACCES","AC","ACCESO"),
	ACEQ 	("ACEQ ","AE","ACEQUIA"),
	ACERA	("ACERA","AA","ACERA"),
	ALAM 	("ALAM ","AL","ALAMEDA"),
	ALDAP	("ALDAP","CT","ALDAPA"),
	ALDEA	("ALDEA","AD","ALDEA"),
	ALQUE	("ALQUE","AQ","ALQUERIA"),
	ALTO 	("ALTO ","AT","ALTO"),
	ANDAD	("ANDAD","AN","ANDADOR"),
	ANGTA	("ANGTA","AG","ANGOSTA"),
	APDRO	("APDRO","AO","APEADERO"),
	APTES	("APTES","AP","APARTAMENTS"),
	APTOS	("APTOS","AP","APARTAMENTOS"),
	ARB  	("ARB  ","AB","ARBOLEDA"),
	ARRAL	("ARRAL","AR","ARRABAL"),
	ARREK	("ARREK","AY","ERREKA"),
	ARRY 	("ARRY ","AY","ARROYO"),
	ASSEG	("ASSEG","AS","ASSEGADOR"),
	ATAJO	("ATAJO","AJ","ATAJO"),
	ATAL 	("ATAL ","AJ","ATALL"),
	ATALL	("ATALL","AJ","ATALLO"),
	ATZUC	("ATZUC","AZ","ATZUCAT"),
	AUTO 	("AUTO ","AU","AUTOPISTA"),
	AUTOV	("AUTOV","AI","AUTOVIA"),
	AUZO 	("AUZO ","BO","AUZO"),
	AUZOT	("AUZOT","BA","AUZOTEGI"),
	AUZUN	("AUZUN","BO","AUZUNEA"),
	AV   	("AV   ","AV","AV"),
	AVDA 	("AVDA ","AV","AVENIDA"),
	AVGDA	("AVGDA","AV","AVINGUDA"),
	AVIA 	("AVIA ","AI","AUTOVIA"),
	BALNR	("BALNR","BN","BALNEARIO"),
	BARDA	("BARDA","BA","BARRIADA"),
	BARRI	("BARRI","BO","BARRI"),
	BARRO	("BARRO","BO","BARRIO"),
	BDA  	("BDA  ","BJ","BAIXADA"),
	BELNA	("BELNA","BE","BELENA"),
	BIDE 	("BIDE ","VI","BIDE"),
	BIDEB	("BIDEB","GL","BIDEBIETA"),
	BJADA	("BJADA","BJ","BAJADA"),
	BLOC 	("BLOC ","BL","BLOC"),
	BLQUE	("BLQUE","BL","BLOQUE"),
	BQLLO	("BQLLO","BQ","BARRANQUIL"),
	BRANC	("BRANC","BR","BARRANCO"),
	BRDLA	("BRDLA","BD","BARREDUELA"),
	BRZAL	("BRZAL","BZ","BRAZAL"),
	BSRIA	("BSRIA","BS","BASERRIA"),
	BULEV	("BULEV","BV","BULEVAR"),
	BV   	("BV   ","BV","BULEVAR"),
	C_H 	("C.H. ","KH","CMNO HONDO"),
	C_N 	("C.N. ","KN","CMNO NUEVO"),
	C_V 	("C.V. ","KV","CMNO VIEJO"),
	C   	("C/   ","C/","C/"),
	CNADA	("C\u00D1ADA","C\u00D1","CA\u00D1ADA"),
	CALLE	("CALLE","CL","CALLE"),
	CAMI 	("CAMI ","CM","CAMI"),
	CAMIN	("CAMIN","CM","CAMIN"),
	CAMPA	("CAMPA","CP","CAMPA"),
	CAMPG	("CAMPG","CG","CAMPING"),
	CAMPO	("CAMPO","CP","CAMPO"),
	CANNO	("CAN\u00D1O","K\u00D1","CANTI\u00D1O"),
	CANAL	("CANAL","CA","CANAL"),
	CANT 	("CANT ","CQ","CANTON"),
	CANTI	("CANTI","QT","CANTINA"),
	CANTO	("CANTO","CQ","CANTO"),
	CANTR	("CANTR","QA","CANTERA"),
	CARRA	("CARRA","QD","CARRERADA"),
	CARRE	("CARRE","CL","CARRER"),
	CARRY	("CARRY","VR","CARRERANY"),
	CASA 	("CASA ","CS","CASA"),
	CBTIZ	("CBTIZ","CB","COBERTIZO"),
	CCVCN	("CCVCN","CV","CIRCUNVALACION"),
	CELLA	("CELLA","QN","CANELLA"),
	CERRO	("CERRO","CE","CERRO"),
	CHLET	("CHLET","CH","CHALET"),
	CINT 	("CINT ","CI","CINTURON"),
	CINY 	("CINY ","CI","CINYELL"),
	CIRCU	("CIRCU","CV","CIRCUNVALACION"),
	CJLA 	("CJLA ","CU","CALLEJUELA"),
	CJTO 	("CJTO ","CN","CONJUNTO"),
	CLEYA	("CLEYA","CY","CALEYA"),
	CLLJA	("CLLJA","CJ","CALLEJA"),
	CLLON	("CLLON","CK","CALLEJON"),
	CLLZO	("CLLZO","KZ","CALLIZO"),
	CLYON	("CLYON","KY","CALEYON"),
	CMNIO 	("CM\u00D1O ","CM","CAMI\u00D1O"),
	CMNET	("CMNET","CM","CAMINET"),
	CMNO 	("CMNO ","CM","CAMINO"),
	CNLLA	("CNLLA","QN","CANELLA"),
	CNVT 	("CNVT ","CW","CONVENT"),
	CNVTO	("CNVTO","CW","CONVENTO"),
	COL  	("COL  ","CO","COLONIA"),
	COMPJ	("COMPJ","QJ","COMPLEJO"),
	COOP 	("COOP ","KP","COOPERATIVA"),
	COSTA	("COSTA","KO","COSTA"),
	COSTE	("COSTE","KR","COSTERA"),
	CRA  	("CRA  ","KA","CARRERA"),
	CRCRO	("CRCRO","CC","CRUCEIRO"),
	CRLLO	("CRLLO","RL","CORRILLO"),
	CRO  	("CRO  ","QR","CARRERO"),
	CRRAL	("CRRAL","QL","CORRAL"),
	CRRCI	("CRRCI","KD","CORREDORCILLO"),
	CRRDA	("CRRDA","KD","CORREDOIRA"),
	CRRDE	("CRRDE","KD","CORREDERA"),
	CRRDO	("CRRDO","KD","CORREDOR"),
	CRRIL	("CRRIL","KL","CARRIL"),
	CRRLO	("CRRLO","QO","CORRALILLO"),
	CRROL	("CRROL","RR","CORRIOL"),
	CRTIL	("CRTIL","QI","CARRETIL"),
	CRTJO	("CRTJO","KT","CORTIJO"),
	CSRIO	("CSRIO","CS","CASERIO"),
	CSTAN	("CSTAN","KS","COSTANILLA"),
	CTRA 	("CTRA ","CR","CARRETERA"),
	CTRIN	("CTRIN","QE","CARRETERIN"),
	CUADR	("CUADR","CD","CUADRA"),
	CUEVA	("CUEVA","QV","CUEVA/S"),
	CUSTA	("CUSTA","CT","CUESTA"),
	CXON 	("CXON ","CX","CALEXON"),
	CZADA	("CZADA","CZ","CALZADA"),
	CZADS	("CZADS","C\u00C7","CALZADAS"),
	DEMAR	("DEMAR","DM","DEMARCACION"),
	DHSA 	("DHSA ","DH","DEHESA"),
	DISEM	("DISEM","DS","DISEMINADO"),
	DISSE	("DISSE","DS","DISSEMINAT"),
	DRERA	("DRERA","DR","DRE\u00C7ERA"),
	EDIFC	("EDIFC","ED","EDIFICIO/S"),
	EIRAD	("EIRAD","EI","EIRADO"),
	EMPR 	("EMPR ","ER","EMPRESA"),
	ENTD 	("ENTD ","EP","ENTRADA"),
	EPTZA	("EPTZA","PZ","ENPARANTZA"),
	ERREB	("ERREB","AR","ERREBAL"),
	ERREP	("ERREP","CR","ERREPIDE"),
	ERRIB	("ERRIB","VG","ERRIBERA"),
	ESC  	("ESC  ","EC","ESCALA/S"),
	ESCA 	("ESCA ","EC","ESCALERA/S"),
	ESCAL	("ESCAL","EW","ESCALINATA"),
	ESLDA	("ESLDA","ES","ESPALDA"),
	ESPIG	("ESPIG","EG","ESPIGO"),
	ESTAC	("ESTAC","EN","ESTACIO"),
	ESTCN	("ESTCN","EN","ESTACION"),
	ESTDA	("ESTDA","EX","ESTRADA"),
	ETDEA	("ETDEA","AV","ETORBIDEA"),
	ETXAD	("ETXAD","GR","ETXADI"),
	ETXAR	("ETXAR","CK","ETXARTE"),
	EXPLA	("EXPLA","EZ","EXPLANADA"),
	EXTRM	("EXTRM","EM","EXTRAMUROS"),
	EXTRR	("EXTRR","ET","EXTRARRADIO"),
	FALDA	("FALDA","FD","FALDA"),
	FBRCA	("FBRCA","FC","FABRICA"),
	FINCA	("FINCA","FN","FINCA"),
	G_V 	("G.V. ","GV","GRAN VIA"),
	GAIN 	("GAIN ","AT","GAIN"),
	GALE 	("GALE ","GA","GALERIA"),
	GLLZO	("GLLZO","GZ","GALLIZO"),
	GORAB	("GORAB","SB","GORABIDE"),
	GRANJ	("GRANJ","GJ","GRANJA"),
	GRUP 	("GRUP ","GR","GRUP"),
	GRUPO	("GRUPO","GR","GRUPO/S"),
	GTA  	("GTA  ","GL","GLORIETA"),
	HEGI 	("HEGI ","HG","HEGI"),
	HIPOD	("HIPOD","HP","HIPODROMO"),
	HIRIB	("HIRIB","AV","HIRIBIDEA"),
	HONDA	("HONDA","PY","HONDARTZA"),
	HOYA 	("HOYA ","HY","HOYA"),
	ILLA 	("ILLA ","IL","ILLA"),
	INDA 	("INDA ","IN","INDA"),
	JARD 	("JARD ","JR","JARDI"),
	JDIN 	("JDIN ","JR","JARDIN"),
	JDINS	("JDINS","JR","JARDINES"),
	KAI  	("KAI  ","ML","KAI"),
	KALE 	("KALE ","CL","KALEA"),
	KARIK	("KARIK","CJ","KARRIK"),
	KARRE	("KARRE","KA","KARRERA"),
	KARRI	("KARRI","CL","KARRIKA"),
	KOSTA	("KOSTA","KO","KOSTA"),
	KRRIL	("KRRIL","KL","KARRIL"),
	LAGO 	("LAGO ","LA","LAGO"),
	LASTE	("LASTE","AJ","LASTERBIDE"),
	LDERA	("LDERA","LD","LADERA"),
	LEKU 	("LEKU ","LG","LEKU"),
	LLNRA	("LLNRA","LL","LLANURA"),
	LLOC 	("LLOC ","LG","LLOC"),
	LOMA 	("LOMA ","LM","LOMA"),
	LOMO 	("LOMO ","LO","LOMO"),
	LORAK	("LORAK","JR","LORATEGIAK"),
	LORAT	("LORAT","JR","LORATEGI"),
	LUGAR	("LUGAR","LG","LUGAR"),
	MALEC	("MALEC","MA","MALECON"),
	MASIA	("MASIA","MS","MASIA/S"),
	MAZO 	("MAZO ","MZ","MAZO"),
	MENDI	("MENDI","MT","MENDI"),
	MERC 	("MERC ","MC","MERCADO"),
	MERCT	("MERCT","MC","MERCAT"),
	MIRAD	("MIRAD","MD","MIRADOR"),
	MOLL 	("MOLL ","ML","MOLL"),
	MONTE	("MONTE","MT","MONTE"),
	MRDOR	("MRDOR","MD","MIRADOR"),
	MTRIO	("MTRIO","MO","MONASTERIO"),
	MUELL	("MUELL","ML","MUELLE"),
	NAVE 	("NAVE ","NV","NAVE/S"),
	NCLEO	("NCLEO","UN","NUCLEO"),
	NUDO 	("NUDO ","ND","NUDO"),
	ONDA 	("ONDA ","PY","ONDARTZA"),
	PAGO 	("PAGO ","PP","PAGO"),
	PALAC	("PALAC","PC","PALACIO"),
	PANT 	("PANT ","P ","PANTANO"),
	PARC 	("PARC ","PQ","PARC"),
	PARKE	("PARKE","PQ","PARKE"),
	PARTI	("PARTI","PF","PARTICULAR"),
	PAS  	("PAS  ","PA","PAS"),
	PASAI	("PASAI","PJ","PASAIA"),
	PASEA	("PASEA","PS","PASEABIDE"),
	PASEO	("PASEO","PS","PASEO"),
	PASSE	("PASSE","PS","PASSEIG"),
	PATIO	("PATIO","PK","PATIO"),
	PBDO 	("PBDO ","PB","POBLADO"),
	PBLO 	("PBLO ","PB","PUEBLO"),
	PDA  	("PDA  ","PV","PUJADA"),
	PDIS 	("PDIS ","P\u00C7","PASSADIS"),
	PG   	("PG   ","PG","PG"),
	PGIND	("PGIND","PG","POLIGONO INDUST"),
	PINAR	("PINAR","PN","PINAR"),
	PISTA	("PISTA","PI","PISTA"),
	PJDA 	("PJDA ","SU","PUJADA, SUBIDA"),
	PL   	("PL   ","PL","PL"),
	PLA  	("PLA  ","PW","PLA"),
	PLACA	("PLA\u00C7A","PZ","PLA\u00C7A"),
	PLAYA	("PLAYA","PY","PLAYA"),
	PLAZA	("PLAZA","PZ","PLAZA"),
	PLCET	("PLCET","PL","PLACETA"),
	PLLOP	("PLLOP","PX","PASILLO"),
	PLZLA	("PLZLA","PL","PLAZUELA"),
	PNTE 	("PNTE ","PT","PUENTE"),
	POLIG	("POLIG","PG","POLIGONO"),
	PONT 	("PONT ","PT","PONT"),
	PONTE	("PONTE","PT","PONTE"),
	PORT 	("PORT ","PO","PORT"),
	PQUE 	("PQUE ","PQ","PARQUE"),
	PRANA	("PRA\u00D1A","P\u00D1","PRACI\u00D1A"),
	PRAGE	("PRAGE","PE","PARATGE"),
	PRAIA	("PRAIA","PY","PRAIA"),
	PRAJE	("PRAJE","PE","PARAJE"),
	PRAXE	("PRAXE","PE","PARAXE"),
	PRAZA	("PRAZA","PZ","PRAZA"),
	PROL 	("PROL ","PR","PROLONGACION"),
	PRTAL	("PRTAL","PH","PORTAL"),
	PRTCO	("PRTCO","PH","PORTICO"),
	PRZLA	("PRZLA","PL","PRAZUELA"),
	PSAJE	("PSAJE","PJ","PASAJE"),
	PSAXE	("PSAXE","PJ","PASAXE"),
	PSLLO	("PSLLO","PX","PASILLO"),
	PSMAR	("PSMAR","PM","PASEO MARITIMO"),
	PTA  	("PTA  ","PU","PUERTA"),
	PTDA 	("PTDA ","PD","PARTIDA"),
	PTGE 	("PTGE ","PJ","PASSATGE"),
	PTILO	("PTILO","PO","PORTILLO"),
	PTLLO	("PTLLO","PO","PUERTILO"),
	PTO  	("PTO  ","PO","PUERTO"),
	PZO  	("PZO  ","P\u00C7","PASADIZO"),
	PZTA 	("PZTA ","PL","PLAZOLETA"),
	RABAL	("RABAL","AR","RABAL"),
	RACDA	("RACDA","RA","RACONADA"),
	RACO 	("RACO ","RC","RACO"),
	RAMAL	("RAMAL","RM","RAMAL"),
	RAMPA	("RAMPA","RP","RAMPA"),
	RAVAL	("RAVAL","AR","RAVAL"),
	RBLA 	("RBLA ","RB","RAMBLA"),
	RBRA 	("RBRA ","RI","RIBERA"),
	RCDA 	("RCDA ","RN","RINCONADA"),
	RCON 	("RCON ","RC","RINCON"),
	RENTO	("RENTO","RT","RENTO"),
	RESID	("RESID","RS","RESIDENCIAL"),
	RIERA	("RIERA","AY","RIERA"),
	RONDA	("RONDA","RD","RONDA"),
	RTDA 	("RTDA ","RO","ROTONDA"),
	RUA  	("RUA  ","RU","RUA"),
	RUELA	("RUELA","CU","RUELA"),
	RUERO	("RUERO","RE","RUEIRO"),
	SANAT	("SANAT","SA","SANATORIO"),
	SANTU	("SANTU","ST","SANTUARIO"),
	SARBI	("SARBI","AC","SARBIDE"),
	SBIDA	("SBIDA","SB","SUBIDA"),
	SECT 	("SECT ","SC","SECTOR"),
	SEDER	("SEDER","SD","SENDER"),
	SEDRA	("SEDRA","SR","SENDERA"),
	SEKT 	("SEKT ","SC","SEKTORE"),
	SEND 	("SEND ","SN","SENDERO"),
	SENDA	("SENDA","SD","SENDA"),
	SVTIA	("SVTIA","CM","SERVENTIA"),
	TALDE	("TALDE","GR","TALDE"),
	TOKI 	("TOKI ","PE","TOKI"),
	TRANS	("TRANS","TS","TRANSITO"),
	TRAS 	("TRAS ","TA","TRASERA"),
	TRAV 	("TRAV ","TR","TRAVESSERA"),
	TRRNT	("TRRNT","TO","TORRENTE"),
	TRSSI	("TRSSI","TR","TRAVESSIA"),
	TRVA 	("TRVA ","TR","TRAVESIA"),
	TRVAL	("TRVAL","TV","TRANSVERSAL"),
	URB  	("URB  ","UR","URBANIZACION"),
	URBAT	("URBAT","UR","URBANITZACIO"),
	URBAZ	("URBAZ","UR","URBANIZAZIO"),
	VALLE	("VALLE","VA","VALLE"),
	VCTE 	("VCTE ","VD","VIADUCTE"),
	VCTO 	("VCTO ","VD","VIADUCTO"),
	VECIN	("VECIN","VC","VECINDARIO"),
	VEGA 	("VEGA ","VG","VEGA"),
	VENAT	("VENAT","VE","VEINAT"),
	VENLA	("VENLA","VN","VENELA"),
	VIA  	("VIA  ","VI","VIA"),
	VIAL 	("VIAL ","VL","VIAL"),
	VIANY	("VIANY","SN","VIARANY"),
	VILLA	("VILLA","V ","VILLA"),
	VREDA	("VREDA","VR","VEREDA"),
	VVDAS	("VVDAS","VV","VIVIENDAS"),
	XDIN 	("XDIN ","JR","XARDIN"),
	ZEHAR	("ZEHAR","ZE","ZEARKALETA"),
	ZONA 	("ZONA ","ZO","ZONA"),
	ZUBI 	("ZUBI ","PT","ZUBI"),
	ZUHAI	("ZUHAI","AB","ZUHAIZTI"),
	ZUMAR	("ZUMAR","AL","ZUMARDI"),
	
	XX	("XX","XX","XX"),	// TODO ???????????????
	ZZ	("ZZ","ZZ","ZZ"),	// TODO ???????????????
	;
	private String ineCode;
	private String aeatCode;
	private String description;
	
	private StreetType(String ineCode, String aeatCode, String description) {
		this.ineCode = ineCode; 
		this.aeatCode = aeatCode;
		this.description = description; 
	}

	public String getIneCode() {
		return ineCode;
	}

	public String getAeatCode() {
		return aeatCode;
	}

	public String getDescription() {
		return description;
	}

	public static StreetType getForIneCode( String ineCode ) {
		if (ineCode != null) {
			for (StreetType st : StreetType.values()) {
				if (st.getIneCode().equals(ineCode)){
					return st;
				}
			}
		}
		return null;
	}
	
	public static StreetType safeValueOf( String value ) {
		if (AonStringUtils.isBlank(value)) {
			return null;
		}
		for (StreetType st : StreetType.values()) {
			if (AonStringUtils.equalsIgnoreCase(value, st.getAeatCode())
			 || AonStringUtils.equalsIgnoreCase(value, st.getIneCode())
			 || AonStringUtils.equalsIgnoreCase(value, st.getDescription())) {
				return st;
			}
		}
		return null;
	}
	
}
