<?xml version="1.0"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<parent>
		<groupId>com.code.aon</groupId>
		<artifactId>aon.parent</artifactId>
		<version>8.78.3</version>
	</parent>
	<modelVersion>4.0.0</modelVersion>
	<artifactId>aon-msm</artifactId>
	<packaging>jar</packaging>
	<description>aon Solutions high-availability clusters with memcached.</description>
	<name>AON MEMCACHED SESSION MANAGER</name>
	<properties>
		<maven.build.timestamp.format>dd/MM/yyyy</maven.build.timestamp.format>
	</properties>
	<scm>
		<developerConnection>scm:svn:http://dev.esferalia.com/repos/aon-application/trunk/aon-solutions-release</developerConnection>
		<connection>scm:svn:http://dev.esferalia.com/repos/aon-application/trunk/aon-solutions-release</connection>
	  <tag>8.78.3.x</tag>
  </scm>
	<build>
		<plugins>
			<!-- Para construir el RPM -->
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>rpm-maven-plugin</artifactId>
				<version>2.0.1</version>
			</plugin>
		</plugins>
	</build>
	<dependencies>
		<dependency>
			<groupId>net.spy</groupId>
			<artifactId>spymemcached</artifactId>
			<version>2.11.1</version>
			<scope>runtime</scope>
			<optional>false</optional>
		</dependency>
		<dependency>
			<groupId>de.javakaffee.msm</groupId>
			<artifactId>memcached-session-manager</artifactId>
			<version>1.9.3</version>
			<scope>runtime</scope>
			<optional>false</optional>
		</dependency>
		<!--
		kryo-serializer: msm-kryo-serializer, kryo-serializers-0.34, kryo-3.x, minlog, reflectasm, asm-5.x
		<dependency>
			<groupId>de.javakaffee.msm</groupId>
			<artifactId>msm-kryo-serializer</artifactId>
			<version>1.8.2</version>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>de.javakaffee</groupId>
			<artifactId>kryo-serializers</artifactId>
			<version>0.11</version>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>com.googlecode</groupId>
			<artifactId>kryo</artifactId>
			<version>1.04</version>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>com.googlecode</groupId>
			<artifactId>minlog</artifactId>
			<version>1.2</version>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>com.googlecode</groupId>
			<artifactId>reflectasm</artifactId>
			<version>1.01</version>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>asm</groupId>
			<artifactId>asm</artifactId>
			<version>3.2</version>
			<scope>runtime</scope>
		</dependency>
		-->
	</dependencies>
	<profiles>
		<profile>
			<id>rpm-release</id>
			<activation>
				<property>
					<name>rpm.release</name>
					<value>true</value>
				</property>
			</activation>
			<dependencies>
				<dependency>
					<groupId>de.javakaffee.msm</groupId>
					<artifactId>memcached-session-manager-tc8</artifactId>
					<version>1.9.3</version>
					<scope>runtime</scope>
					<optional>false</optional>
				</dependency>
			</dependencies>
			<build>
				<pluginManagement>
					<plugins>
						<plugin>
							<groupId>org.codehaus.mojo</groupId>
							<artifactId>rpm-maven-plugin</artifactId>
							<version>2.0.1</version>
							<extensions>true</extensions>
							<executions>
								<execution>
									<goals>
										<goal>attached-rpm</goal>
									</goals>
									<configuration>
										<name>aon-msm8</name>
										<group>Applications/Aon</group>
										<classifier>TOMCAT8</classifier>
										<release>${buildNumber}</release>
										<copyright>2014, esferalia Networks S.A</copyright>
										<requires>
											<require>tomcat8</require>
											<require>aon-aio8</require>
											<require>libxslt</require>
										</requires>
										<mappings>
											<mapping>
												<filemode>755</filemode>
												<username>tomcat</username>
												<groupname>tomcat</groupname>
												<directoryIncluded>false</directoryIncluded>
												<directory>/usr/share/tomcat8/lib</directory>
												<dependency>
													<includes>
														<include>net.spy:spymemcached:2.11.1</include>
														<include>de.javakaffee.msm:memcached-session-manager:1.9.2</include>
														<include>de.javakaffee.msm:memcached-session-manager-tc8:1.9.2</include>
													</includes>
												</dependency>
											</mapping>
											<!--
											<mapping>
												<filemode>755</filemode>
												<username>tomcat</username>
												<groupname>tomcat</groupname>
												<directoryIncluded>false</directoryIncluded>
												<directory>/usr/share/tomcat8/webapps/aon-aio/WEB-INF/lib</directory>
												<dependency>
													<includes>
														<include>asm:asm:3.2</include>
														<include>com.googlecode:reflectasm:1.01</include>
														<include>com.googlecode:kryo:1.04</include>
														<include>com.googlecode:minlog:1.2</include>
														<include>de.javakaffee:kryo-serializers:0.11</include>
														<include>de.javakaffee.msm:msm-kryo-serializer:1.8.2</include>
													</includes>
												</dependency>
											</mapping>
											-->
										</mappings>
										<postinstallScriptlet>
											<scriptFile>src/main/scripts/postinstall</scriptFile>
											<fileEncoding>utf-8</fileEncoding>
										</postinstallScriptlet>
									</configuration>
								</execution>
							</executions>
						</plugin>
					</plugins>
				</pluginManagement>
			</build>
		</profile>
	</profiles>
</project>
