<?xml version="1.0"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<parent>
		<groupId>com.code.aon</groupId>
		<artifactId>aon.parent</artifactId>
		<version>6.1.0-SNAPSHOT</version>
	</parent>
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.esferalia.aon</groupId>
	<artifactId>aon.master.sql</artifactId>
	<version>6.1.0-SNAPSHOT</version>
	<description>AON MASTER SQL</description>
	<name>AON MASTER SQL</name>

        <pluginRepositories>
                <pluginRepository>
                        <id>aon</id>
                        <url>http://dev.esferalia.com/maven2_repositories/inhouse</url>
                </pluginRepository>
                <pluginRepository>
                        <id>aon.snapshots</id>
                        <url>http://dev.esferalia.com/maven2_repositories/inhouse_snapshot</url>
                </pluginRepository>
        </pluginRepositories>

	<build>
		<plugins>
			<plugin>
				<groupId>com.code.aon</groupId>
				<artifactId>aon-master</artifactId>
				<!--version>${pom.version}</version-->
				<executions>
					<execution>
						<goals>
							<goal>DB</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<vmDir>src/main/resources/com/esferalia/aon/master/vm</vmDir>
					<javaOut>src/main/java/com/esferalia/aon/master/sql</javaOut>
				</configuration>
			</plugin>
		</plugins>
	</build>

	<dependencies>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-api</artifactId>
			<version>1.5.11</version>
			<scope>compile</scope>
		</dependency>
	</dependencies>
</project>
 
