bgcolor_color_de_fondo = #ffffff
color_color_de_texto = #000000
color_color_de_texto_menu = #FFFFFF
color_color_de_texto_cabecera = #002D00
color_color_de_texto_link = #40552D
color_color_borde = #ccd7e1
font_fuente = 3
size_tamano_de_fuente = 12
size_tamano_de_fuente_pie = 9
size_tamano_de_fuente_menu = 11
border_bordes = 1