titulo=Recibo individual justificativo del pago de salario
Empresa=Empresa
Domicilio=Domicilio
Cif=CIF
Ccc=CCC
Trabajador=Trabajador
Nif=NIF
Nss=NSS
Gcotiz=G.Cotiz
Gprofesional=G.Profesional
Periodo_liquidación=Periodo Liquidacion
Total_dias=Total dias
Devengos=Devengos
Totales=Totales
Total_devengado=Total devengado
Deducciones=Deducciones
Titulo_pie=Determinación de las bases de cotización a la Seguridad Social y conceptos de recaudación conjunta
Titulo_pie_2=y de la base sujeta a retención del IRPF y aportación de la empresa
Base=Base
Tipo=Tipo
AP_Empresa=AP.Empresa
Contingencias_comunes=Contingencias comunes
Importe_remuneración_mensual=Importe de remuneración mensual
Importe_prorrata_paga_extraordinaria=Importe prorrata de paga extraordinaria
Contingencias_profesionales_y_conceptos_recaudación_conjunta.
At_ep=AT y EP
Desempleo=Desempleo
Formacion_profesional=Formación profesional
Fondo_de_garantía_salarial=Fondo de garantia salarial
Cotizacion_adicional_por_horas_extras=Cotización adicional por horas extraordinarias
Fuerza_mayor_o=Fuerza mayor o
No_estructurales=No estructurales;
Base_sujeta_retencion_IRPF=Base sujeta a retención del IRPF 
