//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.23 at 04:07:42 PM CEST 
//


package com.esferalia.aon.occam.impl.jooq.dao.mod200_2016.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tipo_CambiosPP_Aseguradora complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tipo_CambiosPP_Aseguradora">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Pagina41" type="{}tipo_Pagina41" minOccurs="0"/>
 *         &lt;element name="Pagina42" type="{}tipo_Pagina42" minOccurs="0"/>
 *         &lt;element name="Pagina43" type="{}tipo_Pagina43" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tipo_CambiosPP_Aseguradora", propOrder = {
    "pagina41",
    "pagina42",
    "pagina43"
})
public class TipoCambiosPPAseguradora {

    @XmlElement(name = "Pagina41")
    protected TipoPagina41 pagina41;
    @XmlElement(name = "Pagina42")
    protected TipoPagina42 pagina42;
    @XmlElement(name = "Pagina43")
    protected TipoPagina43 pagina43;

    /**
     * Gets the value of the pagina41 property.
     * 
     * @return
     *     possible object is
     *     {@link TipoPagina41 }
     *     
     */
    public TipoPagina41 getPagina41() {
        return pagina41;
    }

    /**
     * Sets the value of the pagina41 property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoPagina41 }
     *     
     */
    public void setPagina41(TipoPagina41 value) {
        this.pagina41 = value;
    }

    /**
     * Gets the value of the pagina42 property.
     * 
     * @return
     *     possible object is
     *     {@link TipoPagina42 }
     *     
     */
    public TipoPagina42 getPagina42() {
        return pagina42;
    }

    /**
     * Sets the value of the pagina42 property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoPagina42 }
     *     
     */
    public void setPagina42(TipoPagina42 value) {
        this.pagina42 = value;
    }

    /**
     * Gets the value of the pagina43 property.
     * 
     * @return
     *     possible object is
     *     {@link TipoPagina43 }
     *     
     */
    public TipoPagina43 getPagina43() {
        return pagina43;
    }

    /**
     * Sets the value of the pagina43 property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoPagina43 }
     *     
     */
    public void setPagina43(TipoPagina43 value) {
        this.pagina43 = value;
    }

}
