package com.esferalia.aon.payroll.contrata.enumeration;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;

/** 
 * Enumeration for represent Contrata (S.E.P.E.) TABCCNAE table codes.
 * Generation main class: com.esferalia.aon.payroll.contrata.ContrataCodeTablesWriter.
 *  ------------------------------------------------------------------------
 *  TABLA      	DESCRIPCION						FECHA ÚLTIMA ACTUALIZACIÓN.
 *  TABCCNAE	ACTIVIDAD ECONÓMICA						15-03-2009	
 *  ------------------------------------------------------------------------
 */ 
public enum TABCCNAE {

	TABCCNAE_00( "00", "SIN ACTIVIDAD ECONÓMICA", null, null ),
	TABCCNAE_01( "01", "AGRICULTURA, GANADERÍA, CAZA Y SERVICIOS RELACIONADOS CON LAS MISMAS", null, null ),
	TABCCNAE_02( "02", "SILVICULTURA Y EXPLOTACIÓN FORESTAL", null, null ),
	TABCCNAE_03( "03", "PESCA Y ACUICULTURA", null, null ),
	TABCCNAE_05( "05", "EXTRACCIÓN DE ANTRACITA, HULLA Y LIGNITO", null, null ),
	TABCCNAE_06( "06", "EXTRACCIÓN DE CRUDO DE PETRÓLEO Y GAS NATURAL", null, null ),
	TABCCNAE_07( "07", "EXTRACCIÓN DE MINERALES METÁLICOS", null, null ),
	TABCCNAE_08( "08", "OTRAS INDUSTRIAS EXTRACTIVAS", null, null ),
	TABCCNAE_09( "09", "ACTIVIDADES DE APOYO A LAS INDUSTRIAS EXTRACTIVAS", null, null ),
	TABCCNAE_10( "10", "INDUSTRIA DE LA ALIMENTACIÓN", null, null ),
	TABCCNAE_11( "11", "FABRICACIÓN DE BEBIDAS", null, null ),
	TABCCNAE_12( "12", "INDUSTRIA DEL TABACO", null, null ),
	TABCCNAE_13( "13", "INDUSTRIA TEXTIL", null, null ),
	TABCCNAE_14( "14", "CONFECCIÓN DE PRENDAS DE VESTIR", null, null ),
	TABCCNAE_15( "15", "INDUSTRIA DEL CUERO Y DEL CALZADO", null, null ),
	TABCCNAE_16( "16", "INDUSTRIA DE LA MADERA Y DEL CORCHO, EXCEPTO MUEBLES. CESTERÍA Y ESPARTERÍA", null, null ),
	TABCCNAE_17( "17", "INDUSTRIA DEL PAPEL", null, null ),
	TABCCNAE_18( "18", "ARTES GRÁFICAS Y REPRODUCCIÓN DE SOPORTES GRABADOS", null, null ),
	TABCCNAE_19( "19", "COQUERÍAS Y REFINO DE PETRÓLEO", null, null ),
	TABCCNAE_20( "20", "INDUSTRIA QUÍMICA", null, null ),
	TABCCNAE_21( "21", "FABRICACIÓN DE PRODUCTOS FARMACÉUTICOS", null, null ),
	TABCCNAE_22( "22", "FABRICACIÓN DE PRODUCTOS DE CAUCHO Y PLÁSTICOS", null, null ),
	TABCCNAE_23( "23", "FABRICACIÓN DE OTROS PRODUCTOS MINERALES NO METÁLICOS", null, null ),
	TABCCNAE_24( "24", "METALURGIA. FABRICACIÓN DE PRODUCTOS DE HIERRO, ACERO Y FERROALEACIONES", null, null ),
	TABCCNAE_25( "25", "FABRICACIÓN DE PRODUCTOS METÁLICOS, EXCEPTO MAQUINARIA Y EQUIPO", null, null ),
	TABCCNAE_26( "26", "FABRICACIÓN DE PRODUCTOS INFORMÁTICOS, ELECTRÓNICOS Y ÓPTICOS", null, null ),
	TABCCNAE_27( "27", "FABRICACIÓN DE MATERIAL Y EQUIPO ELÉCTRICO", null, null ),
	TABCCNAE_28( "28", "FABRICACIÓN DE MAQUINARIA Y EQUIPO N.C.O.P.", null, null ),
	TABCCNAE_29( "29", "FABRICACIÓN DE VEHÍCULOS DE MOTOR, REMOLQUES Y SEMIRREMOLQUES", null, null ),
	TABCCNAE_30( "30", "FABRICACIÓN DE OTRO MATERIAL TRANSPORTE", null, null ),
	TABCCNAE_31( "31", "FABRICACIÓN DE MUEBLES", null, null ),
	TABCCNAE_32( "32", "OTRAS INDUSTRIAS MANUFACTURERAS", null, null ),
	TABCCNAE_33( "33", "REPARACIÓN E INSTALACIÓN DE MAQUINARIA Y EQUIPO", null, null ),
	TABCCNAE_35( "35", "SUMINISTRO DE ENERGÍA ELÉCTRICA, GAS, VAPOR Y AIRE ACONDICIONADO", null, null ),
	TABCCNAE_36( "36", "CAPTACIÓN, DEPURACIÓN Y DISTRIBUCIÓN DE AGUA", null, null ),
	TABCCNAE_37( "37", "RECOGIDA Y TRATAMIENTO DE AGUAS RESIDUALES", null, null ),
	TABCCNAE_38( "38", "RECOGIDA, TRATAMIENTO Y ELIMINACIÓN DE RESIDUOS. VALORIZACIÓN", null, null ),
	TABCCNAE_39( "39", "ACTIVIDADES DE DESCONTAMINACIÓN Y OTROS SERVICIOS DE GESTIÓN DE RESIDUOS", null, null ),
	TABCCNAE_41( "41", "CONSTRUCCIÓN DE EDIFICIOS", null, null ),
	TABCCNAE_42( "42", "INGENIERÍA CIVIL", null, null ),
	TABCCNAE_43( "43", "ACTIVIDADES DE CONSTRUCCIÓN ESPECIALIZADA", null, null ),
	TABCCNAE_45( "45", "VENTA Y REPARACIÓN DE VEHÍCULOS DE MOTOR Y MOTOCICLETAS", null, null ),
	TABCCNAE_46( "46", "COMERCIO AL POR MAYOR E INTERMEDIARIOS DEL COMERCIO, EXCEPTO DE VEHÍCULOS DE MOTOR Y MOTOCICLETAS", null, null ),
	TABCCNAE_47( "47", "COMERCIO AL POR MENOR, EXCEPTO DE VEHÍCULOS DE MOTOR Y MOTOCICLETAS", null, null ),
	TABCCNAE_49( "49", "TRANSPORTE TERRESTRE Y POR TUBERÍA", null, null ),
	TABCCNAE_50( "50", "TRANSPORTE MARÍTIMO Y POR VÍAS NAVEGABLES INTERIORES", null, null ),
	TABCCNAE_51( "51", "TRANSPORTE AÉREO", null, null ),
	TABCCNAE_52( "52", "ALMACENAMIENTO Y ACTIVIDADES ANEXAS AL TRANSPORTE", null, null ),
	TABCCNAE_53( "53", "ACTIVIDADES POSTALES Y DE CORREOS", null, null ),
	TABCCNAE_55( "55", "SERVICIOS DE ALOJAMIENTO", null, null ),
	TABCCNAE_56( "56", "SERVICIOS DE COMIDAS Y BEBIDAS", null, null ),
	TABCCNAE_58( "58", "EDICIÓN", null, null ),
	TABCCNAE_59( "59", "ACTIVIDADES CINEMATOGRÁFICAS, DE VÍDEO Y DE PROGRAMAS DE TELEVISIÓN, GRABACIÓN DE SONIDO Y EDICIÓN MUSICAL", null, null ),
	TABCCNAE_60( "60", "ACTIVIDADES DE PROGRAMACIÓN Y EMISIÓN DE RADIO Y TELEVISIÓN", null, null ),
	TABCCNAE_61( "61", "TELECOMUNICACIONES", null, null ),
	TABCCNAE_62( "62", "PROGRAMACIÓN, CONSULTORÍA Y OTRAS ACTIVIDADES RELACIONADAS CON LA INFORMÁTICA", null, null ),
	TABCCNAE_63( "63", "SERVICIOS DE INFORMACIÓN", null, null ),
	TABCCNAE_64( "64", "SERVICIOS FINANCIEROS, EXCEPTO SEGUROS Y FONDOS DE PENSIONES", null, null ),
	TABCCNAE_65( "65", "SEGUROS, REASEGUROS Y FONDOS DE PENSIONES, EXCEPTO SEGURIDAD SOCIAL OBLIGATORIA", null, null ),
	TABCCNAE_66( "66", "ACTIVIDADES AUXILIARES A LOS SERVICIOS FINANCIEROS Y A LOS SEGUROS", null, null ),
	TABCCNAE_68( "68", "ACTIVIDADES INMOBILIARIAS", null, null ),
	TABCCNAE_69( "69", "ACTIVIDADES JURÍDICAS Y DE CONTABILIDAD", null, null ),
	TABCCNAE_70( "70", "ACTIVIDADES DE LAS SEDES CENTRALES. ACTIVIDADES DE CONSULTORÍA DE GESTIÓN EMPRESARIAL", null, null ),
	TABCCNAE_71( "71", "SERVICIOS TÉCNICOS DE ARQUITECTURA E INGENIERÍA. ENSAYOS Y ANÁLISIS TÉCNICOS", null, null ),
	TABCCNAE_72( "72", "INVESTIGACIÓN Y DESARROLLO", null, null ),
	TABCCNAE_73( "73", "PUBLICIDAD Y ESTUDIOS DE MERCADO", null, null ),
	TABCCNAE_74( "74", "OTRAS ACTIVIDADES PROFESIONALES, CIENTÍFICAS Y TÉCNICAS", null, null ),
	TABCCNAE_75( "75", "ACTIVIDADES VETERINARIAS", null, null ),
	TABCCNAE_77( "77", "ACTIVIDADES DE ALQUILER", null, null ),
	TABCCNAE_78( "78", "ACTIVIDADES RELACIONADAS CON EL EMPLEO", null, null ),
	TABCCNAE_79( "79", "ACTIVIDADES DE AGENCIAS DE VIAJES, OPERADORES TURÍSTICOS, SERVICIOS DE RESERVA Y ACTIVIDADES RELACIONADAS CON LOS MISMOS", null, null ),
	TABCCNAE_80( "80", "ACTIVIDADES DE SEGURIDAD E INVESTIGACIÓN", null, null ),
	TABCCNAE_81( "81", "SERVICIOS A EDIFICIOS Y ACTIVIDADES DE JARDINERÍA", null, null ),
	TABCCNAE_82( "82", "ACTIVIDADES ADMINISTRATIVAS DE OFICINA Y OTRAS ACTIVIDADES AUXILIARES A LAS EMPRESAS", null, null ),
	TABCCNAE_84( "84", "ADMINISTRACIÓN PÚBLICA Y DEFENSA. SEGURIDAD SOCIAL OBLIGATORIA", null, null ),
	TABCCNAE_85( "85", "EDUCACIÓN", null, null ),
	TABCCNAE_86( "86", "ACTIVIDADES SANITARIAS", null, null ),
	TABCCNAE_87( "87", "ASISTENCIA EN ESTABLECIMIENTOS RESIDENCIALES", null, null ),
	TABCCNAE_88( "88", "ACTIVIDADES DE SERVICIOS SOCIALES SIN ALOJAMIENTO", null, null ),
	TABCCNAE_90( "90", "ACTIVIDADES DE CREACIÓN, ARTÍSTICAS Y ESPECTÁCULOS", null, null ),
	TABCCNAE_91( "91", "ACTIVIDADES DE BIBLIOTECAS, ARCHIVOS, MUSEOS Y OTRAS ACTIVIDADES CULTURALES", null, null ),
	TABCCNAE_92( "92", "ACTIVIDADES DE JUEGOS DE AZAR Y APUESTAS", null, null ),
	TABCCNAE_93( "93", "ACTIVIDADES DEPORTIVAS, RECREATIVAS Y DE ENTRETENIMIENTO", null, null ),
	TABCCNAE_94( "94", "ACTIVIDADES ASOCIATIVAS", null, null ),
	TABCCNAE_95( "95", "REPARACIÓN DE ORDENADORES, EFECTOS PERSONALES Y ARTÍCULOS DE USO DOMÉSTICO", null, null ),
	TABCCNAE_96( "96", "OTROS SERVICIOS PERSONALES", null, null ),
	TABCCNAE_97( "97", "ACTIVIDADES DE LOS HOGARES COMO EMPLEADORES DE PERSONAL DOMÉSTICO", null, null ),
	TABCCNAE_98( "98", "ACTIVIDADES DE LOS HOGARES COMO PRODUCTORES DE BIENES Y SERVICIOS PARA USO PROPIO", null, null ),
	TABCCNAE_99( "99", "ACTIVIDADES DE ORGANIZACIONES Y ORGANISMOS EXTRATERRITORIALES", null, null ),
	;
	public static final String TABLE_NAME = "TABCCNAE";
	public static final String TABLE_DESCRIPTION = " TABCCNAE	ACTIVIDAD ECONÓMICA						15-03-2009	";
	private final SimpleDateFormat sdf = new SimpleDateFormat("yyyyMMdd");
	private String code;
	private String description;
	private String startDate;
	private String endDate;

	TABCCNAE( String code, String description, String startDate, String endDate ) {
		this.code = code;
		this.description = description;
		this.startDate = startDate;
		this.endDate = endDate;
	}

	public String getCode() {
		return code;
	}

	public String getDescription() {
		return description;
	}

	public Date getStartDate(){
		try {
			if(startDate!=null){
				return sdf.parse(startDate);
			}
		} catch (ParseException e) {
			// nothing to do
		}
		return null;
	}

	public Date getEndDate(){
		try {
			if(endDate!=null){
				return sdf.parse(endDate);
			}
		} catch (ParseException e) {
			// nothing to do
		}
	return null;
	}

	public static TABCCNAE getEnumByValue(String expression) {
		for( TABCCNAE o : TABCCNAE.values() ) {
			if ( o.getCode().equals(expression) ) {
				return o;
			}
		}
		return null;
	}

}