DBConnnection_commonName=aon_master
DBConnnection_driverClassName=org.gjt.mm.mysql.Driver
DBConnnection_uid=dbuser
DBConnnection_userPassword=serubd2000
DBConnnection_labeledURI=jdbc:mysql:replication://192.168.3.110,192.168.3.111,192.168.3.112:3306/{0}?autoReconnect=true

notification_email=test@esferalia.com
newDomainApplicationURL=http\://www.esferalia.com/termsOfService/newDomainApplication.html
newDomainApplicationUserURL=http\://www.esferalia.com/termsOfService/newDomainApplicationUser.html

Signature_signature=<br/><br/><br/><br/><b><font size="4">{0}</font></b><p><b><font size="2"></font></b></p><p><br/><i>Aviso legal<br/>Esta comunicación (incluyendo texto y cualquier archivo adjunto) contiene información confidencial y/o privilegiada, está exclusivamente dirigida a los destinatarios y puede ser legalmente privilegiada y estar protegida ante cualquier tipo de publicación y/o transmisión. Si usted no es el destinatario de esta comunicación, notifíquelo inmediatamente a Consulting and Development, S.A. A continuación borre esta comunicación sin realizar ninguna copia. Queda prohibido cualquier uso, distribución o reproducción, utilizando cualquier medio o método, de este mensaje y su material adjunto.<br/>No se puede garantizar la transmisión segura o libre de errores de los correos electrónicos y sus archivos adjuntos, ya que dicha información puede ser interceptada, corrompida, extraviada, retenida, incompleta y/o contener virus. Por lo tanto, el emisor no admitirá ninguna reclamación ni se hará responsable por los errores u omisiones resultantes de esta transmisión electrónica y sus contenidos. Si el destinatario/s de esta transmisión requiere una verificación adicional, por favor solicite una copia impresa de la misma.</i>

MailAccount_email={0}@{1}
MailAccount_host=mail.{0}
MailAccount_incomingHost=mail.{0}
MailAccount_incomingPort=143
MailAccount_incomingSsl=false
MailAccount_mailUsername={0}@{1}
MailAccount_outgoingHost=mail.{0}
MailAccount_outgoingPort=25
MailAccount_outgoingSsl=false
MailAccount_outgoingVerification=true
MailAccount_protocol=imap

MailAccount_create_script.1=/usr/share/aon-manager/aon-create-mail.sh
MailAccount_create_script.2=/usr/share/aon-manager/aon-create-sieve.sh
MailAccount_create_script.3=/usr/share/aon-manager/aon-mailquota.sh

MailAccount_delete_script.1=/usr/share/aon-manager/aon-delete-sieve.sh
MailAccount_delete_script.2=/usr/share/aon-manager/aon-delete-mail.sh