DBConnnection_commonName=aon_master
DBConnnection_driverClassName=org.gjt.mm.mysql.Driver
DBConnnection_uid=dbuser
DBConnnection_userPassword=serubd2000
DBConnnection_labeledURI=jdbc:mysql:replication://192.168.3.110,192.168.3.111,192.168.3.112:3306/{0}?autoReconnect=true