showDomainSearch=true
showDomainCapabilities=true
showDomainManagement=true
showDomainAccessPolicy=true

showDomainUserPasswordExpirationTimestamp=true
showDomainUserChangePassword=true

showDomainApplicationReset=true
showDomainApplicationStatus=true
showDomainApplicationDBConnection=true

showDBConnections=true
showApplications=true
showConfig=true

showDBConnectionDetails=true
showDBConnectionScope=true
showDBConnectionWorkGroup=true
