showDomainSearch=true
showDomainSubDomainSuffix=true
showDomainManagementTab=true
showDomainManagement=true

showDomainUserPasswordExpirationTimestamp=true
showDomainUserChangePassword=true

showDomainApplicationReset=true
showDomainApplicationStatus=true
showDomainApplicationDBConnection=true

showDBConnections=true
showApplications=true
showConfig=true

showDBConnectionDetails=true
