showDomainMail=true
showDomainMobile=true
showDomainHost=true
showDomainReset=true
showDomainSearch=true
showDomainRemove=true
showDomainSubDomainSuffix=true
showDomainManagement=true

showDomainUserPasswordExpirationTimestamp=true
showDomainUserChangePassword=true

showDomainApplicationReset=true

showDBConnections=true
showApplications=true

showDBConnectionDetails=true