showDomainMail=true
showDomainMobile=true
showDomainHost=true
showDomainSearch=true
showDomainSubDomainSuffix=true
showDomainManagement=true

showDomainApplicationReset=true

showAdvancedMode=true