<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.code.aon</groupId>
    <artifactId>aon.parent</artifactId>
    <version>9.16</version>
  </parent>
  <artifactId>aon.oauth2</artifactId>
  <name>AON OAUTH2</name>
  <description>AON OAUTH2</description>
  
  <dependencies>
		<dependency>
			<groupId>org.json</groupId>
			<artifactId>json</artifactId>
			<version>20140107</version>
		</dependency>

		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.jaas</artifactId>
			<version>${project.version}</version>
			<scope>provided</scope>
		</dependency>

		<!-- Google -->
		
		<!-- Google Drive -->
		<dependency>
			<groupId>com.google.apis</groupId>
			<artifactId>google-api-services-drive</artifactId>
			<version>v2-rev194-1.21.0</version>
		</dependency>
		
		<!-- Gmail API -->
		<dependency>
			<groupId>com.google.apis</groupId>
			<artifactId>google-api-services-gmail</artifactId>
			<version>v1-rev34-1.21.0</version>
		</dependency>
		
		<!-- Google Task API -->
		<dependency>
			<groupId>com.google.apis</groupId>
			<artifactId>google-api-services-tasks</artifactId>
			<version>v1-rev41-1.21.0</version>
		</dependency>

		<!-- Google Oauth2 API -->
		<dependency>
			<groupId>com.google.apis</groupId>
			<artifactId>google-api-services-oauth2</artifactId>
			<version>v2-rev98-1.21.0</version>
		</dependency>
		
		<dependency>
			<groupId>com.google.api-client</groupId>
			<artifactId>google-api-client-servlet</artifactId>
			<version>1.21.0</version>
		</dependency>

	</dependencies>
</project>