<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<parent>
		<groupId>com.code.aon</groupId>
		<artifactId>aon.web.parent</artifactId>
		<version>1.0.7</version>
	</parent>
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.code.aon</groupId>
	<artifactId>aon.web.consultant</artifactId>
	<packaging>war</packaging>
	<version>4.3.2</version>
	<description>AON WEB CONSULTANT</description>
	<name>AON WEB CONSULTANT</name>
	<properties>
		<dbVersion>4.7.0</dbVersion>
	</properties>
	<build>
		<finalName>aon-consultant</finalName>
	</build>
	<dependencies>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.rich.components</artifactId>
			<version>4.5.0</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.security.bridge</artifactId>
			<version>3.4.0</version>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.account.bridge</artifactId>
			<version>4.2.7</version>
			<scope>runtime</scope>
		</dependency>
 		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.accounting</artifactId>
			<version>4.11.0</version>
			<scope>runtime</scope>
		</dependency>
 		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.campaign</artifactId>
			<version>4.3.0</version>
			<scope>runtime</scope>
		</dependency>
 		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.company</artifactId>
			<version>4.4.0</version>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.config</artifactId>
			<version>4.3.0</version>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.customer</artifactId>
			<version>4.6.1</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.finance</artifactId>
			<version>4.14.0</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.product</artifactId>
			<version>4.7.0</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.project</artifactId>
			<version>4.3.0</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.report</artifactId>
			<version>4.2.0</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.resources</artifactId>
			<version>4.0.0</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.stat</artifactId>
			<version>4.1.0</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.supplier</artifactId>
			<version>4.3.1</version>
			<scope>compile</scope>
		</dependency>
	</dependencies>
</project>