<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

	<modelVersion>4.0.0</modelVersion>
	<parent>
		<artifactId>aon.parent</artifactId>
		<groupId>com.code.aon</groupId>
		<version>6.74.1</version>
		<relativePath>..</relativePath>
	</parent>
	<groupId>com.esferalia.aon</groupId>
	<artifactId>aon.entity</artifactId>
	<name>AON ENTITY</name>
	<description>AON ENTITY</description>
	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-jar-plugin</artifactId>
				<version>2.3.2</version>
				<configuration>
					<includes>
						<include>META-INF/**</include>
						<include>com/esferalia/aon/entity/**</include>
						<include>com/code/aon/registry/I**</include>
						<include>com/code/aon/project/I**</include>
						<include>com/code/aon/asset/I**</include>
					</includes>
										
					<archive>
						<manifest>
							<addDefaultSpecificationEntries>true</addDefaultSpecificationEntries>
							<addDefaultImplementationEntries>true</addDefaultImplementationEntries>
						</manifest>
					</archive>
				</configuration>
			</plugin>
			<!-- Para añadir la carpeta de los fuentes generados como source folder. -->
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>build-helper-maven-plugin</artifactId>
				<version>1.5</version>
				<executions>
					<execution>
						<id>add-source</id>
						<phase>process-sources</phase>
						<goals>
							<goal>add-source</goal>
						</goals>
						<configuration>
							<sources>
								<source>
									${project.build.directory}/generated-sources/entity
								</source>
							</sources>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>hibernate3-maven-plugin</artifactId>
				<version>2.2</version>
				<executions>
					<execution>
						<phase>generate-sources</phase>
						<goals>
							<goal>hbmtemplate</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<components>
						<component>
							<name>hbmtemplate</name>
							<outputDirectory>/target/generated-sources/entity</outputDirectory>
							<implementation>jdbcconfiguration</implementation>
						</component>
					</components>
					<componentProperties>
						<packagename>com.esferalia.aon.entity.master</packagename>
						<reversestrategy>com.esferalia.aon.entity.hibernate.tools.AonReverseEngineeringStrategy</reversestrategy>
						<revengfile>/src/main/resources/META-INF/hibernate.reveng.xml</revengfile>
						<jdk5>true</jdk5>
						<ejb3>true</ejb3>
						<drop>true</drop>
						<format>true</format>
						<detectmanytomany>false</detectmanytomany>
						<configurationfile>/src/main/resources/META-INF/hibernate.cfg.xml</configurationfile>
						<exporterclass>com.esferalia.aon.entity.hibernate.tools.AonExporter</exporterclass>
						<template>pojo/Pojo.ftl</template>
						<templatepath>/src/main/resources/com/esferalia/aon/entity/hibernate/tools</templatepath>
						<filepattern>{package-name}/{class-name}.java</filepattern>
					</componentProperties>
				</configuration>

				<dependencies>
					<dependency>
						<groupId>com.esferalia.aon</groupId>
						<artifactId>aon.entity.common</artifactId>
						<version>${project.version}</version>
						<scope>compile</scope>
					</dependency>
					<dependency>
						<groupId>mysql</groupId>
						<artifactId>mysql-connector-java</artifactId>
						<version>5.0.8</version>
						<scope>runtime</scope>
					</dependency>
					<dependency>
						<groupId>cglib</groupId>
						<artifactId>cglib</artifactId>
						<version>2.1_3</version>
						<scope>runtime</scope>
					</dependency>
				</dependencies>
			</plugin>
			<plugin>
				<groupId>com.esferalia.aon</groupId>
				<artifactId>aon.mock.entity.maven.plugin</artifactId>
				<version>${project.version}</version>
				<executions>
					<execution>
						<phase>generate-sources</phase>
						<goals>
							<goal>generate-mock-entities</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<outputDir>${project.build.directory}/generated-sources/entity</outputDir>
					<generateHibernateCfg>false</generateHibernateCfg>
				</configuration>
				<dependencies>
					<dependency>
						<groupId>com.esferalia.aon</groupId>
						<artifactId>aon.entity.common</artifactId>
						<version>${project.version}</version>
						<scope>runtime</scope>
					</dependency>
					<dependency>
						<groupId>org.javassist</groupId>
						<artifactId>javassist</artifactId>
						<version>3.15.0-GA</version>
						<scope>runtime</scope>
					</dependency>
				</dependencies>
			</plugin>
		</plugins>
		<pluginManagement>
			<plugins>
				<!--This plugin's configuration is used to store Eclipse m2e settings 
					only. It has no influence on the Maven build itself. -->
				<plugin>
					<groupId>org.eclipse.m2e</groupId>
					<artifactId>lifecycle-mapping</artifactId>
					<version>1.0.0</version>
					<configuration>
						<lifecycleMappingMetadata>
							<pluginExecutions>
								<pluginExecution>
									<pluginExecutionFilter>
										<groupId>
											org.codehaus.mojo
										</groupId>
										<artifactId>
											hibernate3-maven-plugin
										</artifactId>
										<versionRange>
											[2.2,)
										</versionRange>
										<goals>
											<goal>hbmtemplate</goal>
										</goals>
									</pluginExecutionFilter>
									<action>
										<ignore />
									</action>
								</pluginExecution>
								<pluginExecution>
									<pluginExecutionFilter>
										<groupId>
											com.esferalia.aon
										</groupId>
										<artifactId>
											aon.mock.entity.maven.plugin
										</artifactId>
										<versionRange>
											[7.0-SNAPSHOT,)
										</versionRange>
										<goals>
											<goal>
												generate-mock-entities
											</goal>
										</goals>
									</pluginExecutionFilter>
									<action>
										<ignore />
									</action>
								</pluginExecution>
							</pluginExecutions>
						</lifecycleMappingMetadata>
					</configuration>
				</plugin>
			</plugins>
		</pluginManagement>
	</build>
	<dependencies>
		<dependency>
			<groupId>com.esferalia.aon</groupId>
			<artifactId>aon.entity.common</artifactId>
			<version>${project.version}</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon-master</artifactId>
			<version>${project.version}</version>
			<scope>compile</scope>
		</dependency>
	</dependencies>
</project>