# DAO para el Empleado
aon.payroll.empleado.dao.class=com.esferalia.aon.payroll.empleado.EmpleadoDAO

# DAO para el Nomina
aon.payroll.nomina.dao.class=com.esferalia.aon.payroll.nomina.NominaDAO

# DAO para los Partes IT
aon.payroll.parteIT.dao.class=com.esferalia.aon.payroll.parteIT.ParteITDAO
aon.payroll.parteIT.calculators.classes=com.esferalia.aon.payroll.impl.it.ParteITAccidentesCalculator,com.esferalia.aon.payroll.impl.it.ParteITTiempoCompletoCalculator
