<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<parent>
		<artifactId>aon.web.parent</artifactId>
		<groupId>com.code.aon</groupId>
		<version>1.0.5</version>
	</parent>
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.code.aon</groupId>
	<artifactId>aon-web-webmail</artifactId>
	<packaging>war</packaging>
	<name>AON WEB WEBMAIL</name>
	<version>4.12.1</version>
	<description>AON WEB WEBMAIL</description>
	<build>
		<finalName>aon-webmail</finalName>
	</build>
	<dependencies>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.webmail</artifactId>
			<version>4.12.1</version>
			<scope>runtime</scope>
		</dependency>
	</dependencies>
</project>