<?xml version="1.0"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<parent>
		<groupId>com.code.aon</groupId>
		<artifactId>aon.parent</artifactId>
		<version>8.60.1</version>
	</parent>
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.esferalia.aon</groupId>
	<artifactId>aon.gwt.api</artifactId>
	<packaging>jar</packaging>
	<description>AON GWT API</description>
	<name>AON GWT API</name>
	<build>
		<plugins>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>gwt-maven-plugin</artifactId>
				<version>2.8.0-beta1</version>
				<configuration>
					<webappDirectory>${project.build.outputDirectory}</webappDirectory>
				</configuration>
				<executions>
					<execution>
						<phase>prepare-package</phase>
						<goals>
							<goal>compile</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>com.google.code.maven-replacer-plugin</groupId>
				<artifactId>replacer</artifactId>
				<version>1.5.3</version>
				<executions>
					<execution>
						<phase>prepare-package</phase>
						<goals>
							<goal>replace</goal>
						</goals>                   
					</execution>
				</executions>
				<configuration>
					<basedir>${project.basedir}/target/classes</basedir>
					<includes>
						<include>**/gwt/clean/clean.css</include>
					</includes>
					<regexFlags>
					    <regexFlag>MULTILINE</regexFlag>
					    <regexFlag>CASE_INSENSITIVE</regexFlag>
					</regexFlags>
					<replacements>
						<replacement>
							<token>^([a-z: \t,]*)\{$</token>
							<value>/** $1 */
.disabled-by-aon {</value>
						</replacement>         
					</replacements>
				</configuration>
			</plugin>
		</plugins>
	</build>

	<dependencies>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.8</version>
			<type>jar</type>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>com.google.gwt</groupId>
			<artifactId>gwt-servlet</artifactId>
			<version>2.8.0-beta1</version>
			<scope>compile</scope>
		</dependency>

		<dependency>
			<groupId>com.google.gwt</groupId>
			<artifactId>gwt-user</artifactId>
			<version>2.8.0-beta1</version>
			<scope>provided</scope>
		</dependency>
		
		<!-- ONLY DEV 
		<dependency>
    		<groupId>com.google.gwt</groupId>
    		<artifactId>gwt-dev</artifactId>
    		<version>2.8.0-beta1</version>
		</dependency>
		 -->
		
	</dependencies>
  <profiles>
    <profile>
    <id>dev</id>
    <activation>
      <property>
        <name>gwt.working</name>
        <value>true</value>
      </property>
    </activation>
    <build>
      <plugins>
        <plugin>
          <groupId>org.codehaus.mojo</groupId>
          <artifactId>gwt-maven-plugin</artifactId>
          <configuration>
            <draftCompile>true</draftCompile>
          </configuration>
        </plugin>
      </plugins>
    </build>
    </profile>
  </profiles>

</project>
