<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<artifactId>aon.parent</artifactId>
		<groupId>com.code.aon</groupId>
		<version>8.103.1</version>
		<relativePath>..</relativePath>
	</parent>
	<groupId>com.esferalia.aon</groupId>
	<artifactId>aon.entity.alias</artifactId>
	<name>AON ENTITY ALIAS</name>
	<description>AON ENTITY ALIAS</description>
	<build>
		<plugins>
			<plugin>
				<groupId>com.esferalia.aon</groupId>
				<artifactId>aon-alias-maven-plugin</artifactId>
				<version>${project.version}</version>
				<executions>
					<execution>
						<phase>generate-sources</phase>
						<goals>
							<goal>generate-alias</goal>
						</goals>
						<configuration>
							<targetPackage>com.esferalia.aon.entity</targetPackage>
							<targetName>IEntityAlias</targetName>
							<includeGeneratedEntities>true</includeGeneratedEntities>
							<excludes />
						</configuration>
					</execution>
				</executions>
				<dependencies>
					<dependency>
						<groupId>com.esferalia.aon</groupId>
						<artifactId>aon.entity</artifactId>
						<version>${project.version}</version>
						<scope>compile</scope>
					</dependency>
					<dependency>
						<groupId>com.esferalia.aon</groupId>
						<artifactId>aon.entity.common</artifactId>
						<version>${project.version}</version>
						<scope>runtime</scope>
					</dependency>
				</dependencies>
			</plugin>
		</plugins>
	</build>
	<dependencies>
		<dependency>
			<groupId>com.esferalia.aon</groupId>
			<artifactId>aon.entity</artifactId>
			<version>${project.version}</version>
			<scope>compile</scope>
		</dependency>
		<!-- Esta dependencia se introduce para que los alias puedan compilar, 
			 para ello se utilizan los falsos pojos generados en el plugin -->
		<dependency>
			<groupId>com.esferalia.aon</groupId>
			<artifactId>aon-alias-maven-plugin</artifactId>
			<version>${project.version}</version>
			<scope>provided</scope>
		</dependency>
	</dependencies>
</project>
