<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<parent>
		<groupId>com.code.aon</groupId>
		<artifactId>aon.web.parent</artifactId>
		<version>1.0.4</version>
	</parent>
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.code.aon</groupId>
	<artifactId>aon.desktop</artifactId>
	<packaging>war</packaging>
	<version>1.6.1</version>
	<description>AON DESKTOP</description>
	<name>AON DESKTOP</name>
	<properties>
		<dbVersion>1.7.2</dbVersion>
	</properties>
	<build>
		<finalName>aon-desktop</finalName> 
	</build>
	<dependencies>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.common</artifactId>
			<version>1.9.19</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.common</artifactId>
			<version>2.1.1</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.form</artifactId>
			<version>2.3.0</version>
			<scope>compile</scope>
		</dependency>		
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.resources</artifactId>
			<version>1.4.0-SNAPSHOT</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.rich.components</artifactId>
			<version>1.4.0-SNAPSHOT</version>
			<scope>compile</scope>
		</dependency>				
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.security.bridge</artifactId>
			<version>1.6.1</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId> 
			<artifactId>aon.security</artifactId>
			<version>1.5.0</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.webmail</artifactId>
			<version>3.7.1</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.company</artifactId>
			<version>2.2.0</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.config</artifactId>
			<version>2.1.0</version>
			<scope>compile</scope>
			<exclusions>
				<exclusion>
					<groupId>com.code.aon</groupId>
					<artifactId>aon.ui.menu</artifactId>
				</exclusion>
				<exclusion>
					<groupId>com.code.aon</groupId>
					<artifactId>aon.company</artifactId>
				</exclusion>
			</exclusions>			
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.company</artifactId>
			<version>2.3.3</version>
			<scope>runtime</scope>
			<exclusions>
				<exclusion>
					<groupId>org.apache.myfaces.tomahawk</groupId>
					<artifactId>tomahawk</artifactId>
				</exclusion>
				<exclusion>
					<groupId>com.code.aon</groupId>
					<artifactId>aon.ui.menu</artifactId>
				</exclusion>
			</exclusions> 
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.groupware</artifactId>
			<version>2.1.15</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.groupware</artifactId>
			<version>2.1.1</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.messaging</artifactId>
			<version>0.1.0</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.project</artifactId>
			<version>2.3.0</version>
			<scope>compile</scope>
		</dependency>
	</dependencies>
</project>