//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.11.07 at 06:49:52 p. m. CET 
//


package https.www_batuz_eus.fitxategiak.batuz.lroe.esquemas.batuz_tiposcomplejos;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CriterioCajaPagoPJType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CriterioCajaPagoPJType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="EmisorFacturaRecibida" type="{https://www.batuz.eus/fitxategiak/batuz/LROE/esquemas/batuz_TiposComplejos.xsd}DocumentoPersonaType"/>
 *         &lt;element name="OperacionOriginal" type="{https://www.batuz.eus/fitxategiak/batuz/LROE/esquemas/batuz_TiposComplejos.xsd}IDFacturaType"/>
 *         &lt;element name="FechaPago" type="{https://www.batuz.eus/fitxategiak/batuz/LROE/esquemas/batuz_TiposBasicos.xsd}FechaType"/>
 *         &lt;element name="ImportePagado" type="{https://www.batuz.eus/fitxategiak/batuz/LROE/esquemas/batuz_TiposBasicos.xsd}ImporteSgn12.2Type"/>
 *         &lt;element name="CuotaIVASoportada" type="{https://www.batuz.eus/fitxategiak/batuz/LROE/esquemas/batuz_TiposBasicos.xsd}ImporteSgn12.2Type"/>
 *         &lt;element name="CuotaIVADeducible" type="{https://www.batuz.eus/fitxategiak/batuz/LROE/esquemas/batuz_TiposBasicos.xsd}ImporteSgn12.2Type"/>
 *         &lt;element name="MedioDePago" type="{https://www.batuz.eus/fitxategiak/batuz/LROE/esquemas/batuz_Enumerados.xsd}MedioDeCobroPagoEnum"/>
 *         &lt;element name="DescripcionMedio" type="{https://www.batuz.eus/fitxategiak/batuz/LROE/esquemas/batuz_TiposBasicos.xsd}TextMax34Type" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CriterioCajaPagoPJType", propOrder = {
    "emisorFacturaRecibida",
    "operacionOriginal",
    "fechaPago",
    "importePagado",
    "cuotaIVASoportada",
    "cuotaIVADeducible",
    "medioDePago",
    "descripcionMedio"
})
public class CriterioCajaPagoPJType {

    @XmlElement(name = "EmisorFacturaRecibida", required = true)
    protected DocumentoPersonaType emisorFacturaRecibida;
    @XmlElement(name = "OperacionOriginal", required = true)
    protected IDFacturaType operacionOriginal;
    @XmlElement(name = "FechaPago", required = true)
    protected String fechaPago;
    @XmlElement(name = "ImportePagado", required = true)
    protected String importePagado;
    @XmlElement(name = "CuotaIVASoportada", required = true)
    protected String cuotaIVASoportada;
    @XmlElement(name = "CuotaIVADeducible", required = true)
    protected String cuotaIVADeducible;
    @XmlElement(name = "MedioDePago", required = true)
    protected String medioDePago;
    @XmlElement(name = "DescripcionMedio")
    protected String descripcionMedio;

    /**
     * Gets the value of the emisorFacturaRecibida property.
     * 
     * @return
     *     possible object is
     *     {@link DocumentoPersonaType }
     *     
     */
    public DocumentoPersonaType getEmisorFacturaRecibida() {
        return emisorFacturaRecibida;
    }

    /**
     * Sets the value of the emisorFacturaRecibida property.
     * 
     * @param value
     *     allowed object is
     *     {@link DocumentoPersonaType }
     *     
     */
    public void setEmisorFacturaRecibida(DocumentoPersonaType value) {
        this.emisorFacturaRecibida = value;
    }

    /**
     * Gets the value of the operacionOriginal property.
     * 
     * @return
     *     possible object is
     *     {@link IDFacturaType }
     *     
     */
    public IDFacturaType getOperacionOriginal() {
        return operacionOriginal;
    }

    /**
     * Sets the value of the operacionOriginal property.
     * 
     * @param value
     *     allowed object is
     *     {@link IDFacturaType }
     *     
     */
    public void setOperacionOriginal(IDFacturaType value) {
        this.operacionOriginal = value;
    }

    /**
     * Gets the value of the fechaPago property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFechaPago() {
        return fechaPago;
    }

    /**
     * Sets the value of the fechaPago property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFechaPago(String value) {
        this.fechaPago = value;
    }

    /**
     * Gets the value of the importePagado property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImportePagado() {
        return importePagado;
    }

    /**
     * Sets the value of the importePagado property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImportePagado(String value) {
        this.importePagado = value;
    }

    /**
     * Gets the value of the cuotaIVASoportada property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCuotaIVASoportada() {
        return cuotaIVASoportada;
    }

    /**
     * Sets the value of the cuotaIVASoportada property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCuotaIVASoportada(String value) {
        this.cuotaIVASoportada = value;
    }

    /**
     * Gets the value of the cuotaIVADeducible property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCuotaIVADeducible() {
        return cuotaIVADeducible;
    }

    /**
     * Sets the value of the cuotaIVADeducible property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCuotaIVADeducible(String value) {
        this.cuotaIVADeducible = value;
    }

    /**
     * Gets the value of the medioDePago property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMedioDePago() {
        return medioDePago;
    }

    /**
     * Sets the value of the medioDePago property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMedioDePago(String value) {
        this.medioDePago = value;
    }

    /**
     * Gets the value of the descripcionMedio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescripcionMedio() {
        return descripcionMedio;
    }

    /**
     * Sets the value of the descripcionMedio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescripcionMedio(String value) {
        this.descripcionMedio = value;
    }

}
