//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.05.06 at 11:09:31 a. m. CEST 
//


package https.www_batuz_eus.fitxategiak.batuz.lroe.esquemas.batuz_tiposcomplejos;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import https.www_batuz_eus.fitxategiak.batuz.lroe.esquemas.batuz_enumerados.TipoOperacionSujetaNoExentaEnum;


/**
 * <p>Java class for DetalleNoExentaType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DetalleNoExentaType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TipoNoExenta" type="{https://www.batuz.eus/fitxategiak/batuz/LROE/esquemas/batuz_Enumerados.xsd}TipoOperacionSujetaNoExentaEnum"/>
 *         &lt;element name="DesgloseIVA" type="{https://www.batuz.eus/fitxategiak/batuz/LROE/esquemas/batuz_TiposComplejos.xsd}DesgloseIVAType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DetalleNoExentaType", propOrder = {
    "tipoNoExenta",
    "desgloseIVA"
})
public class DetalleNoExentaType {

    @XmlElement(name = "TipoNoExenta", required = true)
    protected TipoOperacionSujetaNoExentaEnum tipoNoExenta;
    @XmlElement(name = "DesgloseIVA", required = true)
    protected DesgloseIVAType desgloseIVA;

    /**
     * Gets the value of the tipoNoExenta property.
     * 
     * @return
     *     possible object is
     *     {@link TipoOperacionSujetaNoExentaEnum }
     *     
     */
    public TipoOperacionSujetaNoExentaEnum getTipoNoExenta() {
        return tipoNoExenta;
    }

    /**
     * Sets the value of the tipoNoExenta property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoOperacionSujetaNoExentaEnum }
     *     
     */
    public void setTipoNoExenta(TipoOperacionSujetaNoExentaEnum value) {
        this.tipoNoExenta = value;
    }

    /**
     * Gets the value of the desgloseIVA property.
     * 
     * @return
     *     possible object is
     *     {@link DesgloseIVAType }
     *     
     */
    public DesgloseIVAType getDesgloseIVA() {
        return desgloseIVA;
    }

    /**
     * Sets the value of the desgloseIVA property.
     * 
     * @param value
     *     allowed object is
     *     {@link DesgloseIVAType }
     *     
     */
    public void setDesgloseIVA(DesgloseIVAType value) {
        this.desgloseIVA = value;
    }

}
