//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.11.07 at 06:49:52 p. m. CET 
//


package https.www_batuz_eus.fitxategiak.batuz.lroe.esquemas.batuz_tiposcomplejos;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import https.www_batuz_eus.fitxategiak.batuz.lroe.esquemas.batuz_enumerados.ClaveCodigoFacturaRectificativaEnum;
import https.www_batuz_eus.fitxategiak.batuz.lroe.esquemas.batuz_enumerados.ClaveTipoRectificativaEnum;


/**
 * <p>Java class for FacturaRectificativaImporteType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FacturaRectificativaImporteType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Codigo" type="{https://www.batuz.eus/fitxategiak/batuz/LROE/esquemas/batuz_Enumerados.xsd}ClaveCodigoFacturaRectificativaEnum"/>
 *         &lt;element name="Tipo" type="{https://www.batuz.eus/fitxategiak/batuz/LROE/esquemas/batuz_Enumerados.xsd}ClaveTipoRectificativaEnum"/>
 *         &lt;element name="ImporteRectificacionSustitutiva" type="{https://www.batuz.eus/fitxategiak/batuz/LROE/esquemas/batuz_TiposComplejos.xsd}ImporteRectificacionSustitutivaType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FacturaRectificativaImporteType", propOrder = {
    "codigo",
    "tipo",
    "importeRectificacionSustitutiva"
})
public class FacturaRectificativaImporteType {

    @XmlElement(name = "Codigo", required = true)
    protected ClaveCodigoFacturaRectificativaEnum codigo;
    @XmlElement(name = "Tipo", required = true)
    protected ClaveTipoRectificativaEnum tipo;
    @XmlElement(name = "ImporteRectificacionSustitutiva")
    protected ImporteRectificacionSustitutivaType importeRectificacionSustitutiva;

    /**
     * Gets the value of the codigo property.
     * 
     * @return
     *     possible object is
     *     {@link ClaveCodigoFacturaRectificativaEnum }
     *     
     */
    public ClaveCodigoFacturaRectificativaEnum getCodigo() {
        return codigo;
    }

    /**
     * Sets the value of the codigo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClaveCodigoFacturaRectificativaEnum }
     *     
     */
    public void setCodigo(ClaveCodigoFacturaRectificativaEnum value) {
        this.codigo = value;
    }

    /**
     * Gets the value of the tipo property.
     * 
     * @return
     *     possible object is
     *     {@link ClaveTipoRectificativaEnum }
     *     
     */
    public ClaveTipoRectificativaEnum getTipo() {
        return tipo;
    }

    /**
     * Sets the value of the tipo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClaveTipoRectificativaEnum }
     *     
     */
    public void setTipo(ClaveTipoRectificativaEnum value) {
        this.tipo = value;
    }

    /**
     * Gets the value of the importeRectificacionSustitutiva property.
     * 
     * @return
     *     possible object is
     *     {@link ImporteRectificacionSustitutivaType }
     *     
     */
    public ImporteRectificacionSustitutivaType getImporteRectificacionSustitutiva() {
        return importeRectificacionSustitutiva;
    }

    /**
     * Sets the value of the importeRectificacionSustitutiva property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImporteRectificacionSustitutivaType }
     *     
     */
    public void setImporteRectificacionSustitutiva(ImporteRectificacionSustitutivaType value) {
        this.importeRectificacionSustitutiva = value;
    }

}
