//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.11.07 at 06:49:52 p. m. CET 
//


package https.www_batuz_eus.fitxategiak.batuz.lroe.esquemas.batuz_tiposcomplejos;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import https.www_batuz_eus.fitxategiak.batuz.lroe.esquemas.batuz_enumerados.SiNoEnum;


/**
 * <p>Java class for OtraInformacionTrascendenciaTributariaType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OtraInformacionTrascendenciaTributariaType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NIFRepresentanteDeclarado" type="{https://www.batuz.eus/fitxategiak/batuz/LROE/esquemas/batuz_TiposBasicos.xsd}NIFType" minOccurs="0"/>
 *         &lt;element name="Inmuebles" type="{https://www.batuz.eus/fitxategiak/batuz/LROE/esquemas/batuz_TiposComplejos.xsd}InmueblesType" minOccurs="0"/>
 *         &lt;element name="ImporteTransmisionInmueblesSujetoAIVA" type="{https://www.batuz.eus/fitxategiak/batuz/LROE/esquemas/batuz_TiposBasicos.xsd}ImporteSgn12.2Type" minOccurs="0"/>
 *         &lt;element name="NumRegistroAcuerdoFacturacion" type="{https://www.batuz.eus/fitxategiak/batuz/LROE/esquemas/batuz_TiposBasicos.xsd}TextMax15Type" minOccurs="0"/>
 *         &lt;element name="ReferenciaExterna" type="{https://www.batuz.eus/fitxategiak/batuz/LROE/esquemas/batuz_TiposBasicos.xsd}TextMax60Type" minOccurs="0"/>
 *         &lt;element name="Cupon" type="{https://www.batuz.eus/fitxategiak/batuz/LROE/esquemas/batuz_Enumerados.xsd}SiNoEnum" minOccurs="0"/>
 *         &lt;element name="EntidadSucedida" type="{https://www.batuz.eus/fitxategiak/batuz/LROE/esquemas/batuz_TiposComplejos.xsd}EntidadSucedidaType" minOccurs="0"/>
 *         &lt;element name="FacturacionDispAdicionalSegundaYQuinta" type="{https://www.batuz.eus/fitxategiak/batuz/LROE/esquemas/batuz_Enumerados.xsd}SiNoEnum" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OtraInformacionTrascendenciaTributariaType", propOrder = {
    "nifRepresentanteDeclarado",
    "inmuebles",
    "importeTransmisionInmueblesSujetoAIVA",
    "numRegistroAcuerdoFacturacion",
    "referenciaExterna",
    "cupon",
    "entidadSucedida",
    "facturacionDispAdicionalSegundaYQuinta"
})
public class OtraInformacionTrascendenciaTributariaType {

    @XmlElement(name = "NIFRepresentanteDeclarado")
    protected String nifRepresentanteDeclarado;
    @XmlElement(name = "Inmuebles")
    protected InmueblesType inmuebles;
    @XmlElement(name = "ImporteTransmisionInmueblesSujetoAIVA")
    protected String importeTransmisionInmueblesSujetoAIVA;
    @XmlElement(name = "NumRegistroAcuerdoFacturacion")
    protected String numRegistroAcuerdoFacturacion;
    @XmlElement(name = "ReferenciaExterna")
    protected String referenciaExterna;
    @XmlElement(name = "Cupon")
    protected SiNoEnum cupon;
    @XmlElement(name = "EntidadSucedida")
    protected EntidadSucedidaType entidadSucedida;
    @XmlElement(name = "FacturacionDispAdicionalSegundaYQuinta")
    protected SiNoEnum facturacionDispAdicionalSegundaYQuinta;

    /**
     * Gets the value of the nifRepresentanteDeclarado property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNIFRepresentanteDeclarado() {
        return nifRepresentanteDeclarado;
    }

    /**
     * Sets the value of the nifRepresentanteDeclarado property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNIFRepresentanteDeclarado(String value) {
        this.nifRepresentanteDeclarado = value;
    }

    /**
     * Gets the value of the inmuebles property.
     * 
     * @return
     *     possible object is
     *     {@link InmueblesType }
     *     
     */
    public InmueblesType getInmuebles() {
        return inmuebles;
    }

    /**
     * Sets the value of the inmuebles property.
     * 
     * @param value
     *     allowed object is
     *     {@link InmueblesType }
     *     
     */
    public void setInmuebles(InmueblesType value) {
        this.inmuebles = value;
    }

    /**
     * Gets the value of the importeTransmisionInmueblesSujetoAIVA property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImporteTransmisionInmueblesSujetoAIVA() {
        return importeTransmisionInmueblesSujetoAIVA;
    }

    /**
     * Sets the value of the importeTransmisionInmueblesSujetoAIVA property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImporteTransmisionInmueblesSujetoAIVA(String value) {
        this.importeTransmisionInmueblesSujetoAIVA = value;
    }

    /**
     * Gets the value of the numRegistroAcuerdoFacturacion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumRegistroAcuerdoFacturacion() {
        return numRegistroAcuerdoFacturacion;
    }

    /**
     * Sets the value of the numRegistroAcuerdoFacturacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumRegistroAcuerdoFacturacion(String value) {
        this.numRegistroAcuerdoFacturacion = value;
    }

    /**
     * Gets the value of the referenciaExterna property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReferenciaExterna() {
        return referenciaExterna;
    }

    /**
     * Sets the value of the referenciaExterna property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReferenciaExterna(String value) {
        this.referenciaExterna = value;
    }

    /**
     * Gets the value of the cupon property.
     * 
     * @return
     *     possible object is
     *     {@link SiNoEnum }
     *     
     */
    public SiNoEnum getCupon() {
        return cupon;
    }

    /**
     * Sets the value of the cupon property.
     * 
     * @param value
     *     allowed object is
     *     {@link SiNoEnum }
     *     
     */
    public void setCupon(SiNoEnum value) {
        this.cupon = value;
    }

    /**
     * Gets the value of the entidadSucedida property.
     * 
     * @return
     *     possible object is
     *     {@link EntidadSucedidaType }
     *     
     */
    public EntidadSucedidaType getEntidadSucedida() {
        return entidadSucedida;
    }

    /**
     * Sets the value of the entidadSucedida property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntidadSucedidaType }
     *     
     */
    public void setEntidadSucedida(EntidadSucedidaType value) {
        this.entidadSucedida = value;
    }

    /**
     * Gets the value of the facturacionDispAdicionalSegundaYQuinta property.
     * 
     * @return
     *     possible object is
     *     {@link SiNoEnum }
     *     
     */
    public SiNoEnum getFacturacionDispAdicionalSegundaYQuinta() {
        return facturacionDispAdicionalSegundaYQuinta;
    }

    /**
     * Sets the value of the facturacionDispAdicionalSegundaYQuinta property.
     * 
     * @param value
     *     allowed object is
     *     {@link SiNoEnum }
     *     
     */
    public void setFacturacionDispAdicionalSegundaYQuinta(SiNoEnum value) {
        this.facturacionDispAdicionalSegundaYQuinta = value;
    }

}
