//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.11.07 at 06:49:52 p. m. CET 
//


package https.www_batuz_eus.fitxategiak.batuz.lroe.esquemas.batuz_tiposcomplejos;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RegistroBienesInversionModelo140Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RegistroBienesInversionModelo140Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="IDBien" type="{https://www.batuz.eus/fitxategiak/batuz/LROE/esquemas/batuz_TiposComplejos.xsd}IDBienInversionModelo140Type"/>
 *         &lt;element name="SituacionRegistro" type="{https://www.batuz.eus/fitxategiak/batuz/LROE/esquemas/batuz_TiposComplejos.xsd}SituacionRegistroType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RegistroBienesInversionModelo140Type", propOrder = {
    "idBien",
    "situacionRegistro"
})
public class RegistroBienesInversionModelo140Type {

    @XmlElement(name = "IDBien", required = true)
    protected IDBienInversionModelo140Type idBien;
    @XmlElement(name = "SituacionRegistro", required = true)
    protected SituacionRegistroType situacionRegistro;

    /**
     * Gets the value of the idBien property.
     * 
     * @return
     *     possible object is
     *     {@link IDBienInversionModelo140Type }
     *     
     */
    public IDBienInversionModelo140Type getIDBien() {
        return idBien;
    }

    /**
     * Sets the value of the idBien property.
     * 
     * @param value
     *     allowed object is
     *     {@link IDBienInversionModelo140Type }
     *     
     */
    public void setIDBien(IDBienInversionModelo140Type value) {
        this.idBien = value;
    }

    /**
     * Gets the value of the situacionRegistro property.
     * 
     * @return
     *     possible object is
     *     {@link SituacionRegistroType }
     *     
     */
    public SituacionRegistroType getSituacionRegistro() {
        return situacionRegistro;
    }

    /**
     * Sets the value of the situacionRegistro property.
     * 
     * @param value
     *     allowed object is
     *     {@link SituacionRegistroType }
     *     
     */
    public void setSituacionRegistro(SituacionRegistroType value) {
        this.situacionRegistro = value;
    }

}
