<?xml version="1.0"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

	<parent>
		<groupId>com.code.aon</groupId>
		<artifactId>aon.parent</artifactId>
		<version>8.54.2</version>
	</parent>

	<modelVersion>4.0.0</modelVersion>
	<artifactId>aon-infoweb-templates</artifactId>
	<packaging>pom</packaging>
	<description>Plantillas (Velocity) del InfoWeb.</description>
	<name>AON INFOWEB TEMPLATES</name>

	<properties>
		<maven.build.timestamp.format>dd/MM/yyyy</maven.build.timestamp.format>
	</properties>

	<scm>
		<developerConnection>scm:svn:http://dev.esferalia.net/repos/aon-application/trunk/aon-infoweb-templates</developerConnection>
		<connection>scm:svn:http://dev.esferalia.net/repos/aon-application/trunk/aon-infoweb-templates</connection>
	  <tag>8.54.2.x</tag>
  </scm>

	<build>
		<plugins>
		</plugins>
	</build>

	<dependencies>
	</dependencies>

	<profiles>
		<profile>
			<id>rpm-release</id>
			<activation>
				<property>
					<name>rpm.release</name>
					<value>true</value>
				</property>
			</activation>

			<build>
				<plugins>

					<!-- Para construir el RPM -->
					<plugin>

						<groupId>org.codehaus.mojo</groupId>
						<artifactId>rpm-maven-plugin</artifactId>
						<version>2.0.1</version>
						<extensions>true</extensions>

						<executions>
							<execution>
								<goals>
									<goal>attached-rpm</goal>
								</goals>
							</execution>

						</executions>

						<configuration>
							<group>Applications/Aon</group>
							<release>${buildNumber}</release>
							<copyright>2009, esferalia Networks S.A</copyright>
							<requires>
							</requires>
							<mappings>
								<mapping>
									<filemode>755</filemode>
									<username>tomcat</username>
									<groupname>tomcat</groupname>
									<directory>/home/COMMON-RESOURCES/aon-web-info/templates</directory>
									<sources>
										<source>
											<location>templates</location>
										</source>
									</sources>
								</mapping>
							</mappings>
						</configuration>
					</plugin>
				</plugins>
			</build>
		</profile>
	</profiles>
</project>
 
