<?xml version="1.0"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

	<parent>
		<groupId>com.code.aon</groupId>
		<artifactId>aon.parent</artifactId>
		<version>7.14.7</version>
	</parent>

	<modelVersion>4.0.0</modelVersion>
	<artifactId>aon-common-resources</artifactId>
	<packaging>jar</packaging>
	<description>Plantillas de impresion (jasper).</description>
	<name>AON COMMON TEMPLATES</name>

	<properties>
		<maven.build.timestamp.format>dd/MM/yyyy</maven.build.timestamp.format>
	</properties>

	<scm>
		<developerConnection>scm:svn:http://dev.esferalia.com/repos/aon-application/releases/7.14.x/aon.web.parent</developerConnection>
		<connection>scm:svn:http://dev.esferalia.com/repos/aon-application/releases/7.14.x/aon.web.parent</connection>
		<url>scm:svn:http://dev.esferalia.com/repos/aon-application/releases/7.14.x/aon.web.parent</url>
	</scm>

  	<build>
		<plugins>
			<plugin>
				<groupId>${jasperreportsMavenPluginGroup}</groupId>
				<artifactId>${jasperreportsMavenPluginArtifact}</artifactId>
				<version>${project.version}</version>
				<executions>
					<execution>
						<id>SALE INVOICE</id>
						<phase>compile</phase>
						<goals>
							<goal>compile-reports</goal>
						</goals>
						<configuration>
							<sourceDirectory>jasperreports/saleInvoiceTemplate2</sourceDirectory>
							<outputDirectory>${project.build.directory}/templates/saleInvoiceTemplate2</outputDirectory>
							<xmlValidation>true</xmlValidation>
							<compiler>${jasperreportsMavenPluginCompiler}</compiler>
						</configuration>
					</execution>
					<execution>
						<id>OFFER EXTENDED</id>
						<phase>compile</phase>
						<goals>
							<goal>compile-reports</goal>
						</goals>
						<configuration>
							<sourceDirectory>jasperreports/offerExtended</sourceDirectory>
							<outputDirectory>${project.build.directory}/templates/offerExtended</outputDirectory>
							<xmlValidation>true</xmlValidation>
							<compiler>${jasperreportsMavenPluginCompiler}</compiler>
						</configuration>
					</execution>
					<execution>
						<id>ELECTROMEDICAL</id>
						<phase>compile</phase>
						<goals>
							<goal>compile-reports</goal>
						</goals>
						<configuration>
							<sourceDirectory>jasperreports/electromedical</sourceDirectory>
							<outputDirectory>${project.build.directory}/templates/electromedical</outputDirectory>
							<xmlValidation>true</xmlValidation>
							<compiler>${jasperreportsMavenPluginCompiler}</compiler>
						</configuration>
					</execution>
					<execution>
						<id>MEDISER</id>
						<phase>compile</phase>
						<goals>
							<goal>compile-reports</goal>
						</goals>
						<configuration>
							<sourceDirectory>jasperreports/mediser</sourceDirectory>
							<outputDirectory>${project.build.directory}/templates/mediser</outputDirectory>
							<xmlValidation>true</xmlValidation>
							<compiler>${jasperreportsMavenPluginCompiler}</compiler>
						</configuration>
					</execution>
					<execution>
						<id>SALE INVOICE GT EUS</id>
						<phase>compile</phase>
						<goals>
							<goal>compile-reports</goal>
						</goals>
						<configuration>
							<sourceDirectory>jasperreports/saleInvoiceGtEus</sourceDirectory>
							<outputDirectory>${project.build.directory}/templates/saleInvoiceGtEus</outputDirectory>
							<xmlValidation>true</xmlValidation>
							<compiler>${jasperreportsMavenPluginCompiler}</compiler>
						</configuration>
					</execution>
					<execution>
						<id>AMILIBIA</id>
						<phase>compile</phase>
						<goals>
							<goal>compile-reports</goal>
						</goals>
						<configuration>
							<sourceDirectory>jasperreports/amilibia</sourceDirectory>
							<outputDirectory>${project.build.directory}/templates/amilibia</outputDirectory>
							<xmlValidation>true</xmlValidation>
							<compiler>${jasperreportsMavenPluginCompiler}</compiler>
						</configuration>
					</execution>
					<execution>
						<id>PRESENCIA DIGITAL</id>
						<phase>compile</phase>
						<goals>
							<goal>compile-reports</goal>
						</goals>
						<configuration>
							<sourceDirectory>jasperreports/presenciaDigital</sourceDirectory>
							<outputDirectory>${project.build.directory}/templates/presenciaDigital</outputDirectory>
							<xmlValidation>true</xmlValidation>
							<compiler>${jasperreportsMavenPluginCompiler}</compiler>
						</configuration>
					</execution>
				</executions>
			</plugin>
		
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>buildnumber-maven-plugin</artifactId>
				<version>1.2</version>
				<executions>
					<execution>
						<phase>validate</phase>
						<goals>
							<goal>create</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<doCheck>false</doCheck>
					<doUpdate>false</doUpdate>
				</configuration>
			</plugin>
		</plugins>
		<pluginManagement>
			<plugins>
				<!--This plugin's configuration is used to store Eclipse m2e settings 
					only. It has no influence on the Maven build itself. -->
				<plugin>
					<groupId>org.eclipse.m2e</groupId>
					<artifactId>lifecycle-mapping</artifactId>
					<version>1.0.0</version>
					<configuration>
						<lifecycleMappingMetadata>
							<pluginExecutions>
								<pluginExecution>
									<pluginExecutionFilter>
										<groupId>org.codehaus.mojo</groupId>
										<artifactId>jasperreports-maven-plugin</artifactId>
										<versionRange>
											[1.0-beta-2,)
										</versionRange>
										<goals>
											<goal>compile-reports</goal>
										</goals>
									</pluginExecutionFilter>
									<action>
										<ignore />
									</action>
								</pluginExecution>
							</pluginExecutions>
						</lifecycleMappingMetadata>
					</configuration>
				</plugin>
			</plugins>
		</pluginManagement>
	</build>

	<dependencies>
		<dependency>
			<groupId>izenpe</groupId>
			<artifactId>izenpesigner-applet</artifactId>
			<version>1.0</version>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.report</artifactId>
			<version>${project.version}</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.warehouse</artifactId>
			<version>${project.version}</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.finance</artifactId>
			<version>${project.version}</version>
			<scope>compile</scope>
		</dependency>
	</dependencies>

	<profiles>
		<profile>
			<id>rpm-release</id>
			<activation>
				<property>
					<name>rpm.release</name>
					<value>true</value>
				</property>
			</activation>
			<build>
				<plugins>

					<!-- Para construir el RPM -->
					<plugin>
						<groupId>org.codehaus.mojo</groupId>
						<artifactId>rpm-maven-plugin</artifactId>
						<version>2.0.1</version>
						<extensions>true</extensions>

						<executions>
							<execution>
								<goals>
									<goal>attached-rpm</goal>
								</goals>
							</execution>

						</executions>

						<configuration>
							<group>Applications/Aon</group>
							<release>${buildNumber}</release>
							<copyright>2009, esferalia Networks S.A</copyright>
							<requires>
							</requires>
							<mappings>
								<mapping>
									<filemode>755</filemode>
									<username>tomcat</username>
									<groupname>tomcat</groupname>
									<directory>/home/COMMON-RESOURCES/aon-report</directory>
									<sources>
										<source>
											<location>${project.build.directory}/templates</location>
										</source>
									</sources>
								</mapping>
								<mapping>
									<filemode>755</filemode>
									<username>tomcat</username>
									<groupname>tomcat</groupname>
									<directory>/home/COMMON-RESOURCES/aon-ui-sign</directory>
									<sources>
										<softlinkSource>
											<location>/home/COMMON-RESOURCES/aon-ui-sign/izenpesigner-applet-1.0.jar</location>
											<destination>izenpesigner-applet.jar</destination>
										</softlinkSource>
									</sources>
									<dependency>
										<includes>
											<include>izenpe:izenpesigner-applet:1.0</include>
										</includes>
									</dependency>
								</mapping>
							</mappings>
							<postinstallScriptlet>
								<scriptFile>src/main/scripts/postinstall</scriptFile>
								<fileEncoding>utf-8</fileEncoding>
							</postinstallScriptlet>
						</configuration>
					</plugin>
				</plugins>
			</build>
		</profile>
      	<profile>
            <id>perform-stats</id>
        </profile>
	</profiles>
</project>
