<?xml version="1.0"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

	<parent>
		<groupId>com.code.aon</groupId>
		<artifactId>aon.parent</artifactId>
		<version>9.23-SNAPSHOT</version>
	</parent>

	<modelVersion>4.0.0</modelVersion>
	<artifactId>aon-common-resources</artifactId>
	<packaging>jar</packaging>
	<description>Plantillas de impresion (jasper).</description>
	<name>AON COMMON TEMPLATES</name>

	<properties>
		<maven.build.timestamp.format>dd/MM/yyyy</maven.build.timestamp.format>
	</properties>


  	<build>
		<plugins>
			<plugin>
				<groupId>${jasperreportsMavenPluginGroup}</groupId>
				<artifactId>${jasperreportsMavenPluginArtifact}</artifactId>
				<version>${project.version}</version>
				<executions>
					<execution>
						<phase>process-sources</phase>
						<goals>
							<goal>jasper</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<sourceDirectory>jasperreports</sourceDirectory>
					<outputDirectory>${project.build.directory}/templates</outputDirectory>
					<verbose>true</verbose>
				</configuration>
				<dependencies>
					<dependency>
						<groupId>com.code.aon</groupId>
						<artifactId>aon.ui.report</artifactId>
						<version>${project.version}</version>
						<scope>compile</scope>
					</dependency>
					<dependency>
						<groupId>com.code.aon</groupId>
						<artifactId>aon.ui.warehouse</artifactId>
						<version>${project.version}</version>
						<scope>compile</scope>
					</dependency>
					<dependency>
						<groupId>com.code.aon</groupId>
						<artifactId>aon.ui.commercial</artifactId>
						<version>${project.version}</version>
						<scope>compile</scope>
					</dependency>
					<dependency>
						<groupId>com.code.aon</groupId>
						<artifactId>aon.ui.finance</artifactId>
						<version>${project.version}</version>
						<scope>compile</scope>
					</dependency>
				</dependencies>
			</plugin>
                        <!-- Adds Jaspers built  -->
                        <plugin>
                                <groupId>org.apache.maven.plugins</groupId>
                                <artifactId>maven-jar-plugin</artifactId>
                                <!--version>2.4</version-->
				<executions>
					<execution>
						<phase>package</phase>
						<goals>
							<goal>jar</goal>
						</goals>
						<configuration>
							<classifier>templates</classifier>
							<classesDirectory>${project.build.directory}/templates</classesDirectory>
							<archive>
								<addMavenDescriptor>false</addMavenDescriptor>
							</archive>
							<includes>
								<include>**/*.jasper</include>
							</includes>
							<!--excludes>
								<exclude>**/pom.xml</exclude>
							</excludes-->
						</configuration>
					</execution>
				</executions>
                        </plugin>
		</plugins>
	</build>

	<dependencies>
		<dependency>
			<groupId>izenpe</groupId>
			<artifactId>izenpesigner-applet</artifactId>
			<version>1.0</version>
		</dependency>
	</dependencies>
</project>
