<?xml version="1.0"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

	<parent>
		<groupId>com.code.aon</groupId>
		<artifactId>aon.parent</artifactId>
		<version>9.23-SNAPSHOT</version>
	</parent>

	<modelVersion>4.0.0</modelVersion>
	<artifactId>aon-common-resources</artifactId>
	<packaging>jar</packaging>
	<description>Plantillas de impresion (jasper).</description>
	<name>AON COMMON TEMPLATES</name>

	<properties>
		<maven.build.timestamp.format>dd/MM/yyyy</maven.build.timestamp.format>
	</properties>


  	<build>
		<plugins>
			<plugin>
				<groupId>${jasperreportsMavenPluginGroup}</groupId>
				<artifactId>${jasperreportsMavenPluginArtifact}</artifactId>
				<version>${project.version}</version>
				<executions>
					<execution>
						<phase>process-sources</phase>
						<goals>
							<goal>jasper</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<sourceDirectory>jasperreports</sourceDirectory>
					<outputDirectory>${project.build.directory}/templates</outputDirectory>
					<verbose>true</verbose>
				</configuration>
				<dependencies>
					<dependency>
						<groupId>com.code.aon</groupId>
						<artifactId>aon.ui.report</artifactId>
						<version>${project.version}</version>
						<scope>compile</scope>
					</dependency>
					<dependency>
						<groupId>com.code.aon</groupId>
						<artifactId>aon.ui.warehouse</artifactId>
						<version>${project.version}</version>
						<scope>compile</scope>
					</dependency>
					<dependency>
						<groupId>com.code.aon</groupId>
						<artifactId>aon.ui.finance</artifactId>
						<version>${project.version}</version>
						<scope>compile</scope>
					</dependency>
				</dependencies>
			</plugin>
                        <!-- Adds Jaspers built  -->
                        <plugin>
                                <groupId>org.apache.maven.plugins</groupId>
                                <artifactId>maven-jar-plugin</artifactId>
                                <!--version>2.4</version-->
				<executions>
					<execution>
						<phase>package</phase>
						<goals>
							<goal>jar</goal>
						</goals>
						<configuration>
							<classifier>templates</classifier>
							<classesDirectory>${project.build.directory}/templates</classesDirectory>
							<archive>
								<addMavenDescriptor>false</addMavenDescriptor>
							</archive>
							<includes>
								<include>**/*.jasper</include>
							</includes>
							<!--excludes>
								<exclude>**/pom.xml</exclude>
							</excludes-->
						</configuration>
					</execution>
				</executions>
                        </plugin>
		</plugins>
	</build>

	<dependencies>
		<dependency>
			<groupId>izenpe</groupId>
			<artifactId>izenpesigner-applet</artifactId>
			<version>1.0</version>
		</dependency>
	</dependencies>

	<profiles>
		<profile>
			<id>rpm-release</id>
			<activation>
				<property>
					<name>rpm.release</name>
					<value>true</value>
				</property>
			</activation>
			<build>
				<plugins>

					<!-- Para construir el RPM -->
					<plugin>
						<groupId>org.codehaus.mojo</groupId>
						<artifactId>rpm-maven-plugin</artifactId>
						<version>2.0.1</version>
						<extensions>true</extensions>

						<executions>
							<execution>
								<goals>
									<goal>attached-rpm</goal>
								</goals>
							</execution>

						</executions>

						<configuration>
							<group>Applications/Aon</group>
							<release>${buildNumber}</release>
							<copyright>2009, esferalia Networks S.A</copyright>
							<requires>
							</requires>
							<mappings>
								<mapping>
									<filemode>755</filemode>
									<username>tomcat</username>
									<groupname>tomcat</groupname>
									<directory>/home/COMMON-RESOURCES/aon-report</directory>
									<sources>
										<source>
											<location>${project.build.directory}/templates</location>
										</source>
									</sources>
								</mapping>
								<mapping>
									<filemode>755</filemode>
									<username>tomcat</username>
									<groupname>tomcat</groupname>
									<directory>/home/COMMON-RESOURCES/aon-ui-sign</directory>
									<sources>
										<softlinkSource>
											<location>/home/COMMON-RESOURCES/aon-ui-sign/izenpesigner-applet-1.0.jar</location>
											<destination>izenpesigner-applet.jar</destination>
										</softlinkSource>
									</sources>
									<dependency>
										<includes>
											<include>izenpe:izenpesigner-applet:1.0</include>
										</includes>
									</dependency>
								</mapping>
							</mappings>
							<postinstallScriptlet>
								<scriptFile>src/main/scripts/postinstall</scriptFile>
								<fileEncoding>utf-8</fileEncoding>
							</postinstallScriptlet>
						</configuration>
					</plugin>
				</plugins>
			</build>
		</profile>
	</profiles>
</project>
