//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.05.06 at 11:09:31 a. m. CEST 
//


package https.www_batuz_eus.fitxategiak.batuz.lroe.esquemas.batuz_tiposconsulta;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import https.www_batuz_eus.fitxategiak.batuz.lroe.esquemas.batuz_enumerados.EstadoRegistroConsultaEnum;


/**
 * <p>Java class for SituacionRegistroConsultaType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SituacionRegistroConsultaType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="EstadoRegistro" type="{https://www.batuz.eus/fitxategiak/batuz/LROE/esquemas/batuz_Enumerados.xsd}EstadoRegistroConsultaEnum"/>
 *         &lt;element name="CodigoErrorRegistro" type="{https://www.batuz.eus/fitxategiak/batuz/LROE/esquemas/batuz_TiposBasicos.xsd}TextMax10Type" minOccurs="0"/>
 *         &lt;element name="DescripcionErrorRegistroES" type="{https://www.batuz.eus/fitxategiak/batuz/LROE/esquemas/batuz_TiposBasicos.xsd}TextMax250Type" minOccurs="0"/>
 *         &lt;element name="DescripcionErrorRegistroEU" type="{https://www.batuz.eus/fitxategiak/batuz/LROE/esquemas/batuz_TiposBasicos.xsd}TextMax250Type" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SituacionRegistroConsultaType", propOrder = {
    "estadoRegistro",
    "codigoErrorRegistro",
    "descripcionErrorRegistroES",
    "descripcionErrorRegistroEU"
})
public class SituacionRegistroConsultaType {

    @XmlElement(name = "EstadoRegistro", required = true)
    protected EstadoRegistroConsultaEnum estadoRegistro;
    @XmlElement(name = "CodigoErrorRegistro")
    protected String codigoErrorRegistro;
    @XmlElement(name = "DescripcionErrorRegistroES")
    protected String descripcionErrorRegistroES;
    @XmlElement(name = "DescripcionErrorRegistroEU")
    protected String descripcionErrorRegistroEU;

    /**
     * Gets the value of the estadoRegistro property.
     * 
     * @return
     *     possible object is
     *     {@link EstadoRegistroConsultaEnum }
     *     
     */
    public EstadoRegistroConsultaEnum getEstadoRegistro() {
        return estadoRegistro;
    }

    /**
     * Sets the value of the estadoRegistro property.
     * 
     * @param value
     *     allowed object is
     *     {@link EstadoRegistroConsultaEnum }
     *     
     */
    public void setEstadoRegistro(EstadoRegistroConsultaEnum value) {
        this.estadoRegistro = value;
    }

    /**
     * Gets the value of the codigoErrorRegistro property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodigoErrorRegistro() {
        return codigoErrorRegistro;
    }

    /**
     * Sets the value of the codigoErrorRegistro property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodigoErrorRegistro(String value) {
        this.codigoErrorRegistro = value;
    }

    /**
     * Gets the value of the descripcionErrorRegistroES property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescripcionErrorRegistroES() {
        return descripcionErrorRegistroES;
    }

    /**
     * Sets the value of the descripcionErrorRegistroES property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescripcionErrorRegistroES(String value) {
        this.descripcionErrorRegistroES = value;
    }

    /**
     * Gets the value of the descripcionErrorRegistroEU property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescripcionErrorRegistroEU() {
        return descripcionErrorRegistroEU;
    }

    /**
     * Sets the value of the descripcionErrorRegistroEU property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescripcionErrorRegistroEU(String value) {
        this.descripcionErrorRegistroEU = value;
    }

}
