//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.05.06 at 11:09:31 a. m. CEST 
//


package https.www_batuz_eus.fitxategiak.batuz.lroe.esquemas.batuz_tiposconsulta;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import https.www_batuz_eus.fitxategiak.batuz.lroe.esquemas.batuz_tiposcomplejos.TransmisionInmuebleType;


/**
 * <p>Java class for TransmisionInmuebleConsultaRespuestaType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TransmisionInmuebleConsultaRespuestaType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DatosTransmisionInmueble" type="{https://www.batuz.eus/fitxategiak/batuz/LROE/esquemas/batuz_TiposComplejos.xsd}TransmisionInmuebleType"/>
 *         &lt;element name="DatosPresentacion" type="{https://www.batuz.eus/fitxategiak/batuz/LROE/esquemas/batuz_TiposConsulta.xsd}DatosPresentacionConsultaType"/>
 *         &lt;element name="SituacionRegistro" type="{https://www.batuz.eus/fitxategiak/batuz/LROE/esquemas/batuz_TiposConsulta.xsd}SituacionRegistroConsultaType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TransmisionInmuebleConsultaRespuestaType", propOrder = {
    "datosTransmisionInmueble",
    "datosPresentacion",
    "situacionRegistro"
})
public class TransmisionInmuebleConsultaRespuestaType {

    @XmlElement(name = "DatosTransmisionInmueble", required = true)
    protected TransmisionInmuebleType datosTransmisionInmueble;
    @XmlElement(name = "DatosPresentacion", required = true)
    protected DatosPresentacionConsultaType datosPresentacion;
    @XmlElement(name = "SituacionRegistro", required = true)
    protected SituacionRegistroConsultaType situacionRegistro;

    /**
     * Gets the value of the datosTransmisionInmueble property.
     * 
     * @return
     *     possible object is
     *     {@link TransmisionInmuebleType }
     *     
     */
    public TransmisionInmuebleType getDatosTransmisionInmueble() {
        return datosTransmisionInmueble;
    }

    /**
     * Sets the value of the datosTransmisionInmueble property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransmisionInmuebleType }
     *     
     */
    public void setDatosTransmisionInmueble(TransmisionInmuebleType value) {
        this.datosTransmisionInmueble = value;
    }

    /**
     * Gets the value of the datosPresentacion property.
     * 
     * @return
     *     possible object is
     *     {@link DatosPresentacionConsultaType }
     *     
     */
    public DatosPresentacionConsultaType getDatosPresentacion() {
        return datosPresentacion;
    }

    /**
     * Sets the value of the datosPresentacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatosPresentacionConsultaType }
     *     
     */
    public void setDatosPresentacion(DatosPresentacionConsultaType value) {
        this.datosPresentacion = value;
    }

    /**
     * Gets the value of the situacionRegistro property.
     * 
     * @return
     *     possible object is
     *     {@link SituacionRegistroConsultaType }
     *     
     */
    public SituacionRegistroConsultaType getSituacionRegistro() {
        return situacionRegistro;
    }

    /**
     * Sets the value of the situacionRegistro property.
     * 
     * @param value
     *     allowed object is
     *     {@link SituacionRegistroConsultaType }
     *     
     */
    public void setSituacionRegistro(SituacionRegistroConsultaType value) {
        this.situacionRegistro = value;
    }

}
