<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<artifactId>aon.parent</artifactId>
		<groupId>com.code.aon</groupId>
		<version>8.81.2</version>
	</parent>
	<artifactId>aon.python</artifactId>
	<packaging>pom</packaging>
	<name>AON PYTHON</name>
	<description>AON PYTHON SCRIPTS</description>
	
	<profiles>
		<profile>
			<id>rpm-release</id>
			<activation>
				<property>
					<name>rpm.release</name>
					<value>true</value>
				</property>
			</activation>
			<build>
				<plugins>
					<plugin>
					    <artifactId>maven-clean-plugin</artifactId>
					    <version>2.5</version>
					    <configuration>
					      <filesets>
					        <fileset>
					          <directory>${basedir}</directory>
					          <includes>
					            <include>**/*.rpm</include>
					            <include>**/*.tar.gz</include>
					          </includes>
					        </fileset>
					      </filesets>
					    </configuration>
					  </plugin>
					<plugin>
						<groupId>org.codehaus.mojo</groupId>
						<artifactId>exec-maven-plugin</artifactId>
						<version>1.2.1</version>
						<executions>
							<execution>
								<configuration>
									<executable>python</executable>
									<arguments>
										<argument>setup.py</argument>
										<argument>bdist_rpm</argument>
									</arguments>    
									<environmentVariables>
										<PYTHONPATH>src/main/python:$PYTHONPATH</PYTHONPATH>
										<AON_VERSION>${project.version}-${buildNumber}</AON_VERSION>
									</environmentVariables>
								</configuration>
								<id>python-build</id>
								<phase>package</phase>
								<goals>
									<goal>exec</goal>
								</goals>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>
		</profile>
	</profiles>
 </project>
