package com.esferalia.aon.tests;

import com.thoughtworks.selenium.*;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import java.util.regex.Pattern;

public class ClickAccountTestCase extends SeleneseTestCase {
	@Before
	public void setUp() throws Exception {
		selenium = new AonSelenium("localhost", 4444, "*chrome", "http://test.esferalia.org/");
		selenium.start();
	}

	@Test
	public void testClickAccountTestCase() throws Exception {
		selenium.open("/aon-account/");
		selenium.type("j_username_view", "account");
		selenium.type("j_password", "demo");
		selenium.click("login_btn");
		selenium.waitForPageToLoad("30000");
		selenium.click("aonContent:j_id26:masters");
		selenium.click("aonContent:mastersMenu:accountEntry");
		selenium.click("aonContent:j_id127:masters");
		selenium.click("aonContent:mastersMenu:autConcept");
		selenium.click("aonContent:j_id224:masters");
		selenium.click("aonContent:mastersMenu:customer");
		selenium.click("aonContent:j_id310:masters");
		selenium.click("aonContent:mastersMenu:supplier");
		selenium.click("aonContent:j_id442:masters");
		selenium.click("aonContent:mastersMenu:creditor");
		selenium.click("aonContent:j_id563:masters");
		selenium.click("aonContent:mastersMenu:geotreeParent");
		selenium.click("aonContent:j_id684:masters");
		selenium.click("aonContent:mastersMenu:payMethod");
		selenium.click("aonContent:j_id761:masters");
		selenium.click("aonContent:mastersMenu:bank");
		selenium.click("aonContent:j_id851:masters");
		selenium.click("aonContent:mastersMenu:loan");
		selenium.click("aonContent:j_id921:masters");
		selenium.click("aonContent:mastersMenu:account");
		selenium.click("aonContent:j_id1007:masters");
		selenium.click("aonContent:mastersMenu:accountManager");
		selenium.click("aonContent:j_id1109:masters");
		selenium.click("aonContent:mastersMenu:customerAccountChecker");
		selenium.click("aonContent:j_id1211:masters");
		selenium.click("aonContent:mastersMenu:supplierAccountChecker");
		selenium.click("aonContent:j_id1283:masters");
		selenium.click("aonContent:mastersMenu:creditorAccountChecker");
		selenium.click("aonContent:j_id1355:masters");
		selenium.click("aonContent:j_id1390:entries");
		selenium.click("aonContent:mastersMenu:accountEntry-entries");
		selenium.click("aonContent:j_id1474:entries");
		selenium.click("aonContent:mastersMenu:invoiceEntry");
		selenium.click("aonContent:j_id1581:entries");
		selenium.click("aonContent:mastersMenu:financeEntry");
		selenium.click("aonContent:j_id1911:entries");
		selenium.click("aonContent:mastersMenu:financeTrackingEntry");
		selenium.click("aonContent:j_id2016:entries");
		selenium.click("aonContent:mastersMenu:expenseEntry");
		selenium.click("aonContent:j_id2107:entries");
		selenium.click("aonContent:mastersMenu:salaryEntry");
		selenium.click("aonContent:j_id2198:entries");
		selenium.click("aonContent:mastersMenu:socialInsuranceEntry");
		selenium.click("aonContent:j_id2301:entries");
		selenium.click("aonContent:mastersMenu:accountOperatingEntry");
		selenium.click("aonContent:j_id2411:entries");
		selenium.click("aonContent:mastersMenu:accountClosingEntry");
		selenium.click("aonContent:j_id2495:entries");
		selenium.click("aonContent:mastersMenu:accountOpeningEntry");
		selenium.click("aonContent:j_id2579:entries");
		selenium.click("aonContent:mastersMenu:loanEntry");
		selenium.click("aonContent:j_id2666:entries");
		selenium.click("aonContent:mastersMenu:loanFeeEntry");
		selenium.click("aonContent:j_id2758:entries");
		selenium.click("aonContent:mastersMenu:saleInvoiceRecorder");
		selenium.click("aonContent:j_id2851:entries");
		selenium.click("aonContent:mastersMenu:purchaseInvoiceRecorder");
		selenium.click("aonContent:j_id3042:entries");
		selenium.click("aonContent:mastersMenu:expenseInvoiceRecorder");
		selenium.click("aonContent:j_id3229:entries");
		selenium.click("aonContent:mastersMenu:undeductibleInvoiceRecorder");
		selenium.click("aonContent:j_id3416:entries");
		selenium.click("aonContent:j_id3556:reports");
		selenium.click("aonContent:reportsMenu:account_statement");
		selenium.click("aonContent:j_id3632:reports");
		selenium.click("aonContent:reportsMenu:journal");
		selenium.click("aonContent:j_id3723:reports");
		selenium.click("aonContent:reportsMenu:ledger");
		selenium.click("aonContent:j_id3809:reports");
		selenium.click("aonContent:reportsMenu:trialBalance");
		selenium.click("aonContent:j_id3891:reports");
		selenium.click("aonContent:reportsMenu:profitAndLossReport");
		selenium.click("aonContent:j_id4013:reports");
		selenium.click("aonContent:reportsMenu:vat_report");
		selenium.click("aonContent:j_id4113:reports");
		selenium.click("aonContent:reportsMenu:invoice_report");
		selenium.click("aonContent:j_id4202:reports");
		selenium.click("aonContent:reportsMenu:accountingBook_report");
		selenium.click("aonContent:j_id4277:reports");
		selenium.click("aonContent:j_id4363:balance");
		selenium.click("aonContent:reportsMenu:closing_balance_sheet");
		selenium.click("aonContent:j_id4418:balance");
		selenium.click("aonContent:reportsMenu:operating_balance_sheet");
		selenium.click("aonContent:j_id4508:balance");
		selenium.click("aonContent:reportsMenu:patrimony_balance_sheet");
		selenium.click("aonContent:j_id4598:balance");
		selenium.click("aonContent:reportsMenu:custom_balance_sheet");
		selenium.click("aonContent:j_id4688:balance");
		selenium.click("aonContent:reportsMenu:accounting_balance");
		selenium.click("aonContent:j_id4778:balance");
		selenium.click("aonContent:j_id4823:fixed_assets");
		selenium.click("aonContent:reportsMenu:amortization");
		selenium.click("aonContent:j_id4873:fixed_assets");
		selenium.click("aonContent:reportsMenu:periodAmortization");
		selenium.click("aonContent:j_id4954:fixed_assets");
		selenium.click("aonContent:reportsMenu:amortizationType");
		selenium.click("aonContent:j_id5012:fixed_assets");
		selenium.click("aonContent:j_id5068:finance");
		selenium.click("aonContent:reportsMenu:finance_charge");
		selenium.click("aonContent:j_id5116:finance");
		selenium.click("aonContent:reportsMenu:finance_payment");
		selenium.click("aonContent:j_id5214:finance");
		selenium.click("aonContent:reportsMenu:aon_fbatch");
		selenium.click("aonContent:j_id5308:finance");
		selenium.click("aonContent:j_id5357:configuration");
		selenium.click("aonContent:reportsMenu:accountChange");
		selenium.click("aonContent:j_id5425:configuration");
		selenium.click("aonContent:reportsMenu:regenerateAccount");
		selenium.click("aonContent:j_id5566:configuration");
		selenium.click("aonContent:reportsMenu:regenerateVat");
		selenium.click("aonContent:j_id5657:configuration");
		selenium.click("aonContent:reportsMenu:accountCheck");
		selenium.click("aonContent:j_id5760:configuration");
		selenium.click("aonContent:reportsMenu:account_exporter");
		selenium.click("aonContent:j_id5842:configuration");
		selenium.click("aonContent:reportsMenu:account_importer");
		selenium.click("aonContent:j_id5919:configuration");
		selenium.click("aonContent:reportsMenu:balance_exporter");
		selenium.click("aonContent:j_id5994:configuration");
		selenium.click("aonContent:reportsMenu:balance_importer");
		selenium.click("aonContent:j_id6062:configuration");
		selenium.click("aonContent:reportsMenu:amortization_exporter");
		selenium.click("aonContent:j_id6137:configuration");
		selenium.click("aonContent:reportsMenu:amortization_importer");
		selenium.click("aonContent:j_id6205:configuration");
		selenium.click("aonContent:reportsMenu:mbase_form");
		selenium.click("aonContent:j_id6280:configuration");
		selenium.click("aonContent:reportsMenu:dbDumper");
		selenium.click("aonContent:j_id6362:configuration");
		selenium.click("aonContent:reportsMenu:actionDenied");
		selenium.click("aonContent:j_id6439:configuration");
		selenium.click("aonContent:reportsMenu:company");
		selenium.click("aonContent:j_id6517:configuration");
		selenium.click("aonContent:reportsMenu:accPeriod");
		selenium.click("aonContent:j_id6782:configuration");
		selenium.click("aonContent:reportsMenu:defaultParams");
		selenium.click("aonContent:j_id6881:configuration");
		selenium.click("aonContent:reportsMenu:series");
		selenium.click("aonContent:j_id6991:configuration");
		selenium.click("aonContent:reportsMenu:tax");
		selenium.click("aonContent:j_id7092:configuration");
		selenium.click("//table[@id='aonContent:j_id7151:mainMenu']/tbody/tr/td[17]/a");
		selenium.waitForPageToLoad("30000");
		selenium.click("//a[@id='j_id21:j_id22']/span");
		selenium.waitForPageToLoad("30000");
	}

	@After
	public void tearDown() throws Exception {
		selenium.stop();
	}
}
