<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<parent>
		<groupId>com.code.aon</groupId>
		<artifactId>aon.parent</artifactId>
		<version>8.93.2</version>
	</parent>
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.esferalia.aon</groupId>
	<artifactId>aon.gwt.issues</artifactId>
	<packaging>jar</packaging>
	<name>AON GWT ISSUES</name>
	<description>AON GWT ISSUES</description>

	<build>
		<resources>
			<resource>
				<directory>src/main/java</directory>
				<includes>
					<include>**/client/**</include>
					<include>**/shared/**</include>
				</includes>
			</resource>
			<resource>
				<directory>src/main/resources</directory>
				<includes>
					<include>**/client/**</include>
					<include>**/facelet/**</include>
					<include>**/*.gwt.xml</include>
				</includes>
			</resource>
		</resources>
	</build>

	<dependencies>
		<dependency>
 			<groupId>com.esferalia.aon</groupId>
 			<artifactId>aon.gwt.api</artifactId>
 			<version>${project.version}</version>
 			<scope>compile</scope>
 		</dependency>
		<dependency>
			<groupId>com.esferalia.aon</groupId>
			<artifactId>aon.gwt.api</artifactId>
			<version>${project.version}</version>
			<scope>provided</scope>
			<classifier>sources</classifier>
		</dependency>
		
		<dependency>
 			<groupId>com.esferalia.aon</groupId>
 			<artifactId>aon.gwt.stat</artifactId>
 			<version>${project.version}</version>
 			<scope>compile</scope>
 		</dependency>
		<dependency>
			<groupId>com.esferalia.aon</groupId>
			<artifactId>aon.gwt.stat</artifactId>
			<version>${project.version}</version>
			<scope>provided</scope>
			<classifier>sources</classifier>
		</dependency>

		<dependency>
 			<groupId>com.esferalia.aon</groupId>
 			<artifactId>aon.occam</artifactId>
 			<version>${project.version}</version>
 			<scope>compile</scope>
 		</dependency>
		<dependency>
			<groupId>com.esferalia.aon</groupId>
			<artifactId>aon.occam</artifactId>
			<version>${project.version}</version>
			<scope>provided</scope>
			<classifier>sources</classifier>
		</dependency>
		
		<dependency>
 			<groupId>com.esferalia.aon</groupId>
 			<artifactId>aon.gwt.common</artifactId>
 			<version>${project.version}</version>
 			<scope>compile</scope>
 		</dependency>
		<dependency>
			<groupId>com.esferalia.aon</groupId>
			<artifactId>aon.gwt.common</artifactId>
			<version>${project.version}</version>
			<scope>compile</scope>
			<classifier>sources</classifier>
		</dependency>

		<dependency>
			<groupId>com.google.gwt</groupId>
			<artifactId>gwt-servlet</artifactId>
			<version>2.8.0</version>
			<scope>compile</scope>
		</dependency>

		<dependency>
			<groupId>com.google.gwt</groupId>
			<artifactId>gwt-user</artifactId>
			<version>2.8.0</version>
			<scope>provided</scope>
		</dependency>
		
		<dependency>
			<groupId>com.google.gwt</groupId>
			<artifactId>gwt-dev</artifactId>
			<version>2.8.0</version>
			<scope>provided</scope>
		</dependency>
		
		<dependency>
			<groupId>com.google.gwt.google-apis</groupId>
			<artifactId>gwt-visualization</artifactId>
			<version>1.1.2</version>
			<scope>compile</scope>
		</dependency>

		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.8</version>
			<type>jar</type>
			<scope>test</scope>
		</dependency>
		
		<dependency>
  		  	<groupId>com.vaadin.polymer</groupId>
    		<artifactId>vaadin-gwt-polymer-elements</artifactId>
    		<version>1.7.0.0</version>
    	 	<scope>provided</scope>
		</dependency>

		<dependency>
 			<groupId>net.aonsolutions.polymer</groupId>
 			<artifactId>aon.gwt.polymer</artifactId>
 			<version>${project.version}</version> 
  			<scope>provided</scope>
		</dependency>

	</dependencies>
</project>
