<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<parent>
		<artifactId>aon.web.parent</artifactId>
		<groupId>com.code.aon</groupId>
		<version>5.0.0</version>
	</parent>
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.code.aon</groupId>
	<artifactId>aon.web.task</artifactId>
	<packaging>war</packaging>
	<version>${aon-version}</version>
	<description>AON TASK</description>
	<name>AON TASK</name>
	<properties>
		<dbVersion>4.8.1</dbVersion>
	</properties>
	<build>
		<finalName>aon-task</finalName>
	</build>
	<dependencies>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.form</artifactId>
			<version>${aon-version}</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.resources</artifactId>
			<version>${aon-version}</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.project</artifactId>
			<version>${aon-version}</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.customer</artifactId>
			<version>${aon-version}</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.company</artifactId>
			<version>${aon-version}</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.campaign</artifactId>
			<version>${aon-version}</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.geozone</artifactId>
			<version>${aon-version}</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.security.bridge</artifactId>
			<version>${aon-version}</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.rich.components</artifactId>
			<version>${aon-version}</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.report</artifactId>
			<version>${aon-version}</version>
			<scope>compile</scope>
		</dependency>
	</dependencies>
</project>
