package com.esferalia.aon.occam.api.model.aonsolutions;

import java.io.Serializable;

public enum AonRole  implements Serializable {
	ADMIN, 
	ACCOUNTING, 		// ACCESO A CONTABILIDAD -  MODO PORTAL/EMPRESA 
	ACCOUNTING_MANAGER,	// ACCESO A CONTABILIDAD -  MODO ASESOR
	FISCAL,				// ACCESO A FISCAL -  MODO PORTAL/EMPRESA 
	FISCAL_MANAGER,		// ACCESO A FISCAL -  MODO ASESOR
	PAYROLL,			// ACCESO A LABORAL -  MODO EMPLEADO
	PAYROLL_MANAGER,	// ACCESO A LABORAL - MODO ASESOR
	PAYROLL_PORTAL,		// ACCESO A LABORAL -  MODO PORTAL/EMPRESA
	DOCUMENTAL,			// ACCESO A DOCUMENTAL -  MODO PORTAL/EMPRESA
	DOCUMENTAL_MANAGER,	// ACCESO A DOCUMENTAL -  MODO ASESOR
	COMUNICA,			// ACCESO A COMUNIC@ -  MODO EMPLEADO
	COMUNICA_MANAGER,	// ACCESO A COMUNIC@ -  MODO ASESOR
	COMUNICA_PORTAL,	// ACCESO A COMUNIC@ -  MODO PORTAL/EMPRESA
	TIMECONTROL,		// ACCESO A CONTROL DE HORARIO -  MODO EMPLEADO
	TIMECONTROL_MANAGER,// ACCESO A CONTROL DE HORARIO -  MODO ASESOR
	TIMECONTROL_PORTAL, // ACCESO A CONTROL DE HORARIO -  MODO PORTAL/EMPRESA
	MESSENGER,			// ACCESO A MENSAJERIA -  MODO PORTAL/EMPRESA
	MESSENGER_MANAGER,	// ACCESO A MENSAJERIA -  MODO ASESOR
	INVOICE,			// ACCESO A FACTURAS - MODO EMPLEADO
	INVOICE_MANAGER,	// ACCESO A FACTURAS - MODO ASESOR
	INVOICE_PORTAL,		// ACCESO A FACTURAS - MODO PORTAL/EMPRESA
	MANAGEMENT,			// ACCESO A GESTION - MODO PORTAL/EMPRESA
	MANAGEMENT_MANAGER,	// ACCESO A GESTION - MODO ASESOR
	ALMA,				// ACCESO AL SERVICIO ALMA
	OCR,				// ACCESO AL SERVICIO OCR
	BANK,				// ACCESO AL SERVICIO BANK
	CONVENIOS,			// ACCESO AL SERVICIO CONVENIOS
	AON,
	BIDOQ;
	
	public Byte value(){
		return (byte) ordinal();
	}
	
	public static AonRole safeValueOf( Byte i ) {
		if (i == null) return null;
		return safeValueOf( i.intValue() ); 
	}

	public static AonRole safeValueOf( Integer i ) {
		if (i == null) return null;
		if (i < 0 || i >= AonRole.values().length) return null;
		return AonRole.values()[i];
	}
	
	public static AonRole safeValueOf( String i ) {
		for (AonRole rs : values()) {
			if(i.equalsIgnoreCase(rs.name()))
				return rs;
		}
		return null;
	}
}

