hibernate.connection.provider_class=com.code.aon.common.dao.hibernate.C3P0ConnectionProvider
hibernate.connection.service=jboss.admin:service=AonLdap
hibernate.connection.datasource=java:comp/env/jdbc/AonSMB
hibernate.dialect=org.hibernate.dialect.MySQLDialect
hibernate.show_sql=true
hibernate.c3p0.acquire_increment=1
hibernate.c3p0.idle_test_period=1900
hibernate.c3p0.timeout=3600
hibernate.c3p0.max_size=30
hibernate.c3p0.min_size=1
hibernate.c3p0.max_statements=0
hibernate.c3p0.preferredTestQuery=select 1;
