#!/bin/bash

CTX=$(find /usr/share/tomcat*/webapps/aon-aio/META-INF -name context.xml)

if grep MemcachedBackupSessionManager $CTX &>/dev/null; then
  exit;
fi

mv $CTX $CTX.rpm.saved

xsltproc - $CTX.rpm.saved > $CTX  <<EOF
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0">
  <xsl:output method="xml" indent="yes" />

  <xsl:template match="/Context">
    <xsl:copy><xsl:copy-of select="@*"/><xsl:apply-templates/>


    <xsl:text disable-output-escaping="yes">&lt;!--</xsl:text>

	Example for sticky sessions + kryo

	<xsl:text disable-output-escaping="yes">&lt;</xsl:text>Manager 
	className="de.javakaffee.web.msm.MemcachedBackupSessionManager"
	memcachedNodes="n1:host1.yourdomain.com:11211"
	requestUriIgnorePattern=".*\.(ico|png|gif|jpg|css|js)$"
	transcoderFactoryClass="de.javakaffee.web.msm.serializer.kryo.KryoTranscoderFactory"
        <xsl:text disable-output-escaping="yes">/&gt;</xsl:text>
    	<xsl:text>&#xa;</xsl:text>
    <xsl:text disable-output-escaping="yes">--&gt;</xsl:text>
    <xsl:text>&#xa;</xsl:text>
    <xsl:text disable-output-escaping="yes">&lt;!--</xsl:text>

	Example for non sticky sessions + kryo

	<xsl:text disable-output-escaping="yes">&lt;</xsl:text>Manager 
	className="de.javakaffee.web.msm.MemcachedBackupSessionManager"
        memcachedNodes="n1:host1.yourdomain.com:11211,n2:host2.yourdomain.com:11211"
        sticky="false"
        sessionBackupAsync="false"
        lockingMode="uriPattern:/path1|/path2"
        requestUriIgnorePattern=".*\.(ico|png|gif|jpg|css|js)$"
        transcoderFactoryClass="de.javakaffee.web.msm.serializer.kryo.KryoTranscoderFactory"
        <xsl:text disable-output-escaping="yes">/&gt;</xsl:text>
    <xsl:text>&#xa;</xsl:text>
    <xsl:text disable-output-escaping="yes">--&gt;</xsl:text>
    <xsl:text>&#xa;</xsl:text>
    <xsl:text disable-output-escaping="yes">&lt;!--</xsl:text>
	
	Overview over memcached-session-manager configuration attributes

	className (required)

		This should be set to de.javakaffee.web.msm.MemcachedBackupSessionManager to 
		get sessions stored in memcached. However, since version 1.3.6 there's also 
		a de.javakaffee.web.msm.DummyMemcachedBackupSessionManager that can be used 
		for development purposes.

        memcachedNodes (required)

                This attribute must contain all memcached nodes you have running, or the 
                membase bucket uri(s). It should be the same for all tomcats.

        failoverNodes (optional, must not be used for non-sticky sessions)

                This attribute must contain the ids of the memcached nodes that must only 
                be used for session backup when none of the other memcached nodes are available.

        username (since 1.6.0, optional)

                Specifies the username used for a membase bucket or SASL. 

        password (since 1.6.0, optional)

                Specifies the password used for membase bucket or SASL authentication (can be 
                left empty / omitted if the "default" membase bucket without a password shall 
                be used). 

        memcachedProtocol (since 1.3, optional, default text)

                This attribute specifies the memcached protocol to use, one of text or binary. 

        sticky (since 1.4.0, optional, default true)

                Specifies if sticky or non-sticky sessions are used. 

        lockingMode (since 1.4.0, optional, for non-sticky sessions only, default none)

                Specifies the locking strategy for non-sticky sessions. 
                Possible values for lockingMode are:

                        none: sessions are never locked
                        all: the session is locked when requested by the app until the end 
                        of the request
                        auto: readonly requests are detected, for them the session is not 
                        locked. For requests that are not classified as "readonly" the session 
                        is locked
                        uriPattern:regexp: the provided regular expression pattern is compared 
                        with the requestURI + "?" + queryString and the session is locked if 
                        they match. 

        requestUriIgnorePattern (optional)

                This attribute contains a regular expression for request URIs, that shall not 
                trigger a session backup. 

        sessionBackupAsync (optional, default true)

                Specifies if the session shall be stored asynchronously in memcached.

        backupThreadCount (since 1.3, optional, default number-of-cpu-cores)

                The number of threads that are used for asynchronous session backup 
                (if sessionBackupAsync="true").

	sessionBackupTimeout (optional, default 100)

    		The timeout in milliseconds after that a session backup is considered as beeing failed. 

	operationTimeout (since 1.6.0, optional, default 1000)

    		The memcached operation timeout used at various places, e.g. used for the spymemcached 
		ConnectionFactory. 

	storageKeyPrefix (since 1.8.0, optional, default webappVersion)

    		Allows to configure a prefix that's added to the session id when a session is stored 
		in memcached. 

	sessionAttributeFilter (since 1.5.0, optional)

    		A regular expression to control which session attributes are serialized to memcached.

	transcoderFactoryClass (since 1.1, optional, default de.javakaffee.web.msm.JavaSerializationTranscoderFactory)

    		The class name of the factory that creates the transcoder to use for 
		serializing/deserializing sessions to/from memcached.

		Java serialization: de.javakaffee.web.msm.JavaSerializationTranscoderFactory
    		Kryo based serialization: de.javakaffee.web.msm.serializer.kryo.KryoTranscoderFactory
    		Javolution based serialization: de.javakaffee.web.msm.serializer.javolution.JavolutionTranscoderFactory
    		XStream based serialization: de.javakaffee.web.msm.serializer.xstream.XStreamTranscoderFactory 

	copyCollectionsForSerialization (since 1.1, optional, default false)

    		A boolean value that specifies, if iterating over collection elements shall be done on a copy 
		of the collection or on the collection itself. 

	customConverter (since 1.2, optional)

    		Custom converter allow you to provide custom serialization of application specific types. 

	enableStatistics (since 1.2, optional, default true)

    		A boolean value that specifies, if statistics shall be gathered. For more info see the JMXStatistics page. 

	enabled (since 1.4.0, optional, default true)

    		Specifies if session storage in memcached is enabled or not, can also be changed at runtime via JMX. 
		Only allowed in sticky mode.

    <xsl:text disable-output-escaping="yes">--&gt;</xsl:text>
    <xsl:text>&#xa;</xsl:text>
    <xsl:text disable-output-escaping="yes">&lt;!--</xsl:text>

	Overview over available system properties (all optional)

	msm.maxReconnectDelay (since 1.7, default 30)

	    	The max reconnect delay for the spymemcached MemcachedClient, in seconds. 

	msm.nodeAvailabilityCacheTTL (since 1.7, default 1000)

    		The TTL for msm NodeAvailabilityCache entries, in millis. 

	msm.kryo.bufferSize.initial (since 1.1, default 102400)

    		The initial size in bytes of the kryo object buffer when (de)serializing a session. 
		Is passed as initialCapacity when creating a kryo ObjectBuffer. 

	msm.kryo.bufferSize.max (since 1.1, default 2048000)

    		The maximum size in bytes of the kryo object buffer when (de)serializing a session - 
		the maximum size in bytes that a serialized session can take. 
		Is passed as maxCapacity when creating a kryo ObjectBuffer. 

	msm.kryo.defaultSerializerFactory (since 1.8, default de.javakaffee.web.msm.serializer.kryo.ReferenceFieldSerializerFactory)

    		The factory to create the Serializer used by Kryo when Kryo#newDefaultSerializer is called.

    <xsl:text disable-output-escaping="yes">--&gt;</xsl:text>
    <xsl:text>&#xa;</xsl:text>
    </xsl:copy>
  </xsl:template>

  <!-- copy all elements and their attributes-->
  <xsl:template match="* | @*">
    <xsl:copy><xsl:copy-of select="@*"/><xsl:apply-templates/></xsl:copy>
  </xsl:template>

</xsl:stylesheet>
EOF
