bgcolor_color_de_fondo_pie = #f3f3f3
bgcolor_color_de_fondo_contenido = #fcfcfc
color_color_de_texto_links = #6699ff
color_color_de_texto_menu = #333333
color_color_de_texto_links_hover = #3366cc	
font_fuente = 3
size_tamaño_de_fuente = 11
img_imagen_de_fondo = background.gif