package com.esferalia.aon.occam.api.model.attachment;

public enum ContractAttachmentType {

	CONTRACT_DOC_DRAFT,
	CONTRACT_DOC,
	
	BASIC_COPY_DRAFT,
	BASIC_COPY,
	
	SEPE_CONTRACT_FILE,
	@Deprecated
	SEPE_CONTRACT_COMMUNICATION_ID,
	@Deprecated
	SEPE_CONTRACT_RESPONSE,
	
	TRAINING_CENTER_DIRECT_DEBIT,
	
	TRAINING_ANNEX_I,
	TRAINING_ANNEX_II,

	EXTENSION_DOC_DRAFT,
	EXTENSION_DOC,
	
	CONTRACT_CLAUSES,
	
	SEPE_EXTENSION_FILE,
	@Deprecated
	SEPE_EXTENSION_COMMUNICATION_ID,
	@Deprecated
	SEPE_EXTENSION_RESPONSE,

	SEPE_CERTIFICADOS_FILE,
	@Deprecated
	SEPE_CERTIFICADOS_COMMUNICATION_ID,
	@Deprecated
	SEPE_CERTIFICADOS_RESPONSE,
	
	SEPE_TRANSFORM_FILE,
	@Deprecated
	SEPE_TRANSFORM_COMMUNICATION_ID,
	@Deprecated
	SEPE_TRANSFORM_RESPONSE,
	
	ENTERPRISE_CERTIFICATE_DOC_DRAFT,
	
	;
	
	public byte value() {
		return (byte) this.ordinal();
	}
	
	public String getName(){
		return this.toString();
	}
	
	public static Byte[] drive(){
		return new Byte[]{
			CONTRACT_DOC_DRAFT.value(), CONTRACT_DOC.value(),
			BASIC_COPY_DRAFT.value(), BASIC_COPY.value(),
			SEPE_CONTRACT_FILE.value(), SEPE_CONTRACT_COMMUNICATION_ID.value(),
			SEPE_CONTRACT_RESPONSE.value(), TRAINING_CENTER_DIRECT_DEBIT.value(),
			TRAINING_ANNEX_I.value(), TRAINING_ANNEX_II.value(),
			EXTENSION_DOC_DRAFT.value(), EXTENSION_DOC.value(),
			CONTRACT_CLAUSES.value(), SEPE_EXTENSION_FILE.value(),
			SEPE_EXTENSION_COMMUNICATION_ID.value(), SEPE_EXTENSION_RESPONSE.value(),
			SEPE_CERTIFICADOS_FILE.value(), SEPE_CERTIFICADOS_COMMUNICATION_ID.value(),
			SEPE_CERTIFICADOS_RESPONSE.value(), SEPE_TRANSFORM_FILE.value(),
			SEPE_TRANSFORM_COMMUNICATION_ID.value(), SEPE_TRANSFORM_RESPONSE.value(),
			ENTERPRISE_CERTIFICATE_DOC_DRAFT.value()
		};
	}
}