package com.esferalia.aon.occam.api.model.attachment;

public enum RegistryAttachmentType {

	LOGO,
	ADDITIONAL_IMAGE,
	BANNER,
	CORPORATE_IDENTITY,
	DIGITAL_CERTIFICATE,
	DOCUMENT,
	FISCAL_TEMPLATES,
	FISCAL_REPORTS,
	SIGNATURE,
	INVOICE_FOOTER_TEXT,
	MARKETING_TEMPLATE,
	ENTERPRISE_CONTRACT_CLAUSES,
	DOMAIN_BOOK_HISTORY,
	DOMAIN_INSERT_HISTORY,
	DOMAIN_REMOVE_HISTORY,
	AON_TEMPLATES,
	POS_INVOICE_FOOTER_TEXT,
	D2_DEPOSIT,
	ECOMMERCE_PRODUCT_TEMPLATES,
	REPORT_BACKGROUND,
	CRETA_RESPUESTA,
	CRETA_TRABAJADORES_Y_TRAMOS,
	SYSTEM_MESSAGE,
	CRETA_BASES,
	DOCUMENTAL_ENTERPRISE,
	DOCUMENTAL_EMPLOYEE
	;
	
	public byte value() {
		return (byte) this.ordinal();
	}
	
	public String getName(){
		return this.toString();
	}
	
	public static Byte[] drive(){
		return new Byte[]{
			ADDITIONAL_IMAGE.value(), BANNER.value(),
			CORPORATE_IDENTITY.value(), DIGITAL_CERTIFICATE.value(),
			DOCUMENT.value(), FISCAL_TEMPLATES.value(),
			FISCAL_REPORTS.value(), SIGNATURE.value(),
			INVOICE_FOOTER_TEXT.value(), MARKETING_TEMPLATE.value(),
			ENTERPRISE_CONTRACT_CLAUSES.value(), POS_INVOICE_FOOTER_TEXT.value(),
			REPORT_BACKGROUND.value(), SYSTEM_MESSAGE.value()
		};
	}
	
}