package com.esferalia.aon.occam.api.model.attachment;


import java.util.Locale;
import java.util.ResourceBundle;



public enum RegistryAttachmentType {

	LOGO,
	ADDITIONAL_IMAGE,
	BANNER,
	CORPORATE_IDENTITY,
	DIGITAL_CERTIFICATE,
	DOCUMENT,
	FISCAL_TEMPLATES,
	FISCAL_REPORTS,
	SIGNATURE,
	INVOICE_FOOTER_TEXT,
	MARKETING_TEMPLATE,
	ENTERPRISE_CONTRACT_CLAUSES,
	DOMAIN_BOOK_HISTORY,
	DOMAIN_INSERT_HISTORY,
	DOMAIN_REMOVE_HISTORY,
	AON_TEMPLATES,
	POS_INVOICE_FOOTER_TEXT,
	D2_DEPOSIT,
	ECOMMERCE_PRODUCT_TEMPLATES,
	REPORT_BACKGROUND,
	CRETA_RESPUESTA,
	CRETA_TRABAJADORES_Y_TRAMOS;
	
	public byte value() {
		return (byte) this.ordinal();
	}
}