bgcolor_color_de_fondo = #0066BB
bgcolor_color_de_fondo_cabecera = #FFFFFF
bgcolor_color_de_fondo_contenido = #FFFFFF
bgcolor_color_de_fondo_pie = #0066BB
color_color_de_texto = #444444
color_color_de_texto_menu = #EEEEEE
color_color_de_texto_pie = #EEEEEE
font_fuente = 3	
size_tamaño_de_fuente = 12
size_tamaño_de_fuente_pie = 11
img_imagen_de_fondo = bg.jpg
img_imagen_de_fondo_cabecera = header.jpg
img_imagen_de_fondo_pie = footer.jpg
