<?xml version="1.0"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

	<parent>
		<groupId>com.code.aon</groupId>
		<artifactId>aon.parent</artifactId>
		<version>8.111.2</version>
	</parent>
	<modelVersion>4.0.0</modelVersion>
	<artifactId>aon.google.apis</artifactId>
	<description>AON GOOGLE APIS</description>
	<name>AON GOOGLE APIS</name>

	<dependencies>
		<!-- -->
		<dependency>
			<groupId>javax.faces</groupId>
			<artifactId>jsf-api</artifactId>
			<version>1.2_14</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.richfaces.framework</groupId>
			<artifactId>richfaces-api</artifactId>
			<version>3.3.3.Final</version>
			<scope>compile</scope>
		</dependency>

		<!-- -->
		<dependency>
			<groupId>commons-cli</groupId>
			<artifactId>commons-cli</artifactId>
			<version>1.2</version>
			<scope>compile</scope>
		</dependency>
		
		<dependency>
			<groupId>com.esferalia.aon</groupId>
			<artifactId>aon.entity</artifactId>
			<version>${project.version}</version>
			<scope>compile</scope>
		</dependency>

		<dependency>
			<groupId>com.esferalia.aon</groupId>
			<artifactId>aon.master.jooq</artifactId>
			<version>${project.version}</version>
			<scope>compile</scope>
		</dependency>

		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.jaas</artifactId>
			<version>${project.version}</version>
			<scope>provided</scope>
		</dependency>

		<dependency>
			<groupId>com.esferalia.aon</groupId>
			<artifactId>aon.entity.common</artifactId>
			<version>${project.version}</version>
			<scope>compile</scope>
		</dependency>

		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.common</artifactId>
			<version>${project.version}</version>
			<scope>provided</scope>
		</dependency>
		
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.oauth2</artifactId>
			<version>${project.version}</version>
			<scope>provided</scope>
		</dependency>
		
		<dependency>
			<groupId>net.aonsolutions</groupId>
			<artifactId>aon.google.apis.v2</artifactId>
			<version>${project.version}</version>
			<scope>provided</scope>
		</dependency>

		<!-- Google -->
		<dependency>
			<groupId>com.google.api-client</groupId>
			<artifactId>google-api-client</artifactId>
			<version>1.21.0</version>
		</dependency>
		<dependency>
			<groupId>com.google.api-client</groupId>
			<artifactId>google-api-client-servlet</artifactId>
			<version>1.21.0</version>
		</dependency>
		<dependency>
			<groupId>com.google.http-client</groupId>
			<artifactId>google-http-client-jackson2</artifactId>
			<version>1.21.0</version>
		</dependency>
		
		<!-- Google Calendar API -->
		<dependency>
			<groupId>com.google.apis</groupId>
			<artifactId>google-api-services-calendar</artifactId>
			<version>v3-rev157-1.21.0</version>
		</dependency>

		<!-- Google UrlShortener API -->
		<dependency>
			<groupId>com.google.apis</groupId>
			<artifactId>google-api-services-urlshortener</artifactId>
			<version>v1-rev41-1.21.0</version>
		</dependency>
    	
    	<!-- Google Drive API-->
		<dependency>
			<groupId>com.google.apis</groupId>
			<artifactId>google-api-services-drive</artifactId>
			<version>v2-rev194-1.21.0</version>
		</dependency>
		
		<!-- Gmail API -->
		<dependency>
			<groupId>com.google.apis</groupId>
			<artifactId>google-api-services-gmail</artifactId>
			<version>v1-rev34-1.21.0</version>
		</dependency>
		
		<!-- Google Task API -->
		<dependency>
			<groupId>com.google.apis</groupId>
			<artifactId>google-api-services-tasks</artifactId>
			<version>v1-rev41-1.21.0</version>
		</dependency>

		<!-- Google Oauth2 API -->
		<dependency>
			<groupId>com.google.apis</groupId>
			<artifactId>google-api-services-oauth2</artifactId>
			<version>v2-rev98-1.21.0</version>
		</dependency>
		
		<!-- Google Contacts API -->
		<dependency>
			<groupId>com.google.api.client</groupId>
			<artifactId>google-api-data-contacts-v3</artifactId>
			<version>1.0.10-alpha</version>
		</dependency>
		
		<dependency>
			<groupId>javax.mail</groupId>
			<artifactId>mail</artifactId>
			<version>1.4</version>
		</dependency>
		<dependency>
			<groupId>org.json</groupId>
			<artifactId>json</artifactId>
			<version>20090211</version>
		</dependency>

		<dependency>
			<groupId>com.google.code.gson</groupId>
			<artifactId>gson</artifactId>
			<version>2.2.4</version>
		</dependency>
		
		<dependency>
			<groupId>commons-net</groupId>
			<artifactId>commons-net</artifactId>
			<version>3.3</version>
		</dependency>

	</dependencies>
	<profiles>
		<profile>
			<id>rpm-release</id>
			<activation>
				<property>
					<name>rpm.release</name>
					<value>true</value>
				</property>
			</activation>

			<dependencies>
				<dependency>
					<groupId>com.code.aon</groupId>
					<artifactId>aon.pool</artifactId>
					<version>${project.version}</version>
				</dependency>
				<dependency>
					<groupId>com.mchange</groupId>
					<artifactId>c3p0</artifactId>
					<version>0.9.2</version>
				</dependency>
				<dependency>
					<groupId>com.mchange</groupId>
					<artifactId>mchange-commons-java</artifactId>
					<version>0.2.3.3</version>
				</dependency>

				<dependency>
					<groupId>com.fasterxml.jackson.core</groupId>
					<artifactId>jackson-core</artifactId>
					<version>2.1.3</version>
				</dependency>

				<dependency>
					<groupId>com.google.oauth-client</groupId>
					<artifactId>google-oauth-client</artifactId>
					<version>1.21.0</version>
				</dependency>

				<dependency>
					<groupId>commons-lang</groupId>
					<artifactId>commons-lang</artifactId>
					<version>2.5</version>
				</dependency>

				<dependency>
					<groupId>commons-io</groupId>
					<artifactId>commons-io</artifactId>
					<version>1.4</version>
				</dependency>

				<dependency>
					<groupId>org.jooq</groupId>
					<artifactId>jooq</artifactId>
					<version>3.8.4</version>
				</dependency>

				<dependency>
					<groupId>commons-net</groupId>
					<artifactId>commons-net</artifactId>
					<version>3.3</version>
				</dependency>
				<dependency>
                	<groupId>com.esferalia.aon</groupId>
                    <artifactId>aon.occam</artifactId>
                    <version>${project.version}</version>
               	</dependency>
			</dependencies>


			<build>
				<plugins>
					<!-- Para construir el RPM -->
					<plugin>

						<groupId>org.codehaus.mojo</groupId>
						<artifactId>rpm-maven-plugin</artifactId>
						<version>2.0.1</version>
						<extensions>true</extensions>

						<executions>
							<execution>
								<id>rpm-build</id>
								<goals>
									<goal>attached-rpm</goal>
								</goals>
							</execution>
						</executions>

						<configuration>
							<group>Applications/Aon</group>
							<release>${buildNumber}</release>
							<copyright>2014, esferalia Networks S.A</copyright>
							<requires>
								<require>slf4j</require>
								<require>aon-dbutils</require>
								<require>mysql-connector-java</require>
							</requires>

							<mappings>

								<mapping>
									<filemode>755</filemode>
									<username>root</username>
									<groupname>root</groupname>

									<directory>/usr/share/java/aon-google-apis</directory>
									<dependency>
										<includes>
											<!-- ext -->
											<include>com.mchange:c3p0:0.9.2</include>
											<include>javax.mail:mail:1.4</include>
											<include>org.jooq:jooq:3.5.2</include>
											<include>com.mchange:c3p0:0.9.2</include>
											<include>com.mchange:mchange-commons-java:0.2.3.3</include>
											<include>commons-io:commons-io:1.4</include>
											<include>commons-cli:commons-cli:1.2</include>
											<include>commons-lang:commons-lang:2.5</include>
											<include>com.fasterxml.jackson.core:jackson-core:2.1.3</include>
											<include>commons-net:commons-net:3.3</include>
											
											<!-- aon -->
											<include>com.code.aon:aon.pool:${project.version}</include>
											<include>com.code.aon:aon.common:${project.version}</include>
											<include>com.esferalia.aon:aon.entity:${project.version}</include>
											<include>com.esferalia.aon:aon.master.jooq:${project.version}</include>
											<include>com.esferalia.aon:aon.entity.common:${project.version}</include>
											<include>com.code.aon:aon.oauth2:${project.version}</include>
											<include>com.esferalia.aon:aon.occam:${project.version}</include>
											<include>com.esferalia.aon:aon.watson:${project.version}</include>
											<include>net.aonsolutions:aon.google.apis.v2:${project.version}</include>
											
											<!-- Google -->
											<include>com.google.api-client:google-api-client:1.21.0</include>
											<include>com.google.http-client:google-http-client:1.21.0</include>
											<include>com.google.http-client:google-http-client-jackson2:1.21.0</include>
											<include>com.google.apis:google-api-services-drive:v2-rev194-1.21.0</include>
											<include>com.google.apis:google-api-services-calendar:v3-rev157-1.21.0</include>									
											<include>com.google.oauth-client:google-oauth-client:1.21.0</include>
											<include>com.google.apis:google-api-services-oauth2:v2-rev98-1.21.0</include>
											<include>com.google.apis:google-api-services-gmail:v1-rev34-1.21.0</include>
		
										</includes>
									</dependency>
									<sources>

										<source>
											<location>target</location>
											<includes>
												<include>${project.artifactId}-${project.version}.jar</include>
											</includes>
										</source>

									</sources>
								</mapping>

								<mapping>
									<filemode>755</filemode>
									<username>root</username>
									<groupname>root</groupname>
									<directory>/usr/share/aon-google-apis/bin</directory>
									<sources>
										<source>
											<location>src/main/scripts</location>
											<includes>
												<include>aon-google-drive.sh</include>
											</includes>
										</source>
										<source>
											<location>src/main/scripts</location>
											<includes>
												<include>aon-google-drive-v2.sh</include>
											</includes>
										</source>
										<source>
											<location>src/main/scripts</location>
											<includes>
												<include>aon-rattach.sh</include>
											</includes>
										</source>
										<source>
											<location>src/main/scripts</location>
											<includes>
												<include>aon-google-calendar.sh</include>
											</includes>
										</source>
									</sources>
								</mapping>
							</mappings>
						</configuration>

					</plugin>
				</plugins>
			</build>
		</profile>
	</profiles>
</project>
 
