<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<parent>
		<groupId>com.code.aon</groupId>
		<artifactId>aon.parent</artifactId>
		<version>1.0.1</version>
	</parent>
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.code.aon</groupId>
	<artifactId>aon.ui.company</artifactId>
	<version>4.0.0</version>
	<description>AON UI COMPANY</description>
	<name>AON UI COMPANY</name>
	<dependencies>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.common</artifactId>
			<version>4.0.0</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.form</artifactId>
			<version>3.5.1</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.company</artifactId>
			<version>3.3.3</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.registry</artifactId>
			<version>3.5.1</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.registry</artifactId>
			<version>3.12.0</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>javax.servlet</groupId>
			<artifactId>servlet-api</artifactId>
			<version>2.4</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>javax.faces</groupId>
			<artifactId>jsf-api</artifactId>
			<version>1.2_09</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
		    <groupId>javax.faces</groupId>
		    <artifactId>jsf-impl</artifactId>
		    <version>1.2_09</version>
		    <scope>provided</scope>
		</dependency> 						
		<dependency>
    		<groupId>jmimemagic</groupId>
    		<artifactId>jmimemagic</artifactId>
    		<version>0.1.2</version>
			<exclusions>
				<exclusion>
				      <groupId>xerces</groupId>
				      <artifactId>xerces</artifactId>
				</exclusion>
				<exclusion>
				      <groupId>xerces</groupId>
				      <artifactId>xercesImpl</artifactId>
				</exclusion>
				<exclusion>
					<groupId>xml-apis</groupId>
					<artifactId>xml-apis</artifactId>
				</exclusion>
				<exclusion>
					<groupId>xml-apis</groupId>
					<artifactId>xmlParserAPIs</artifactId>
				</exclusion>
				<exclusion>
					<groupId>log4j</groupId>
					<artifactId>log4j</artifactId>
				</exclusion>
			</exclusions>
		</dependency>		
 	</dependencies>
</project>