<?xml version="1.0"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<parent>
		<groupId>com.code.aon</groupId>
		<artifactId>aon.parent</artifactId>
		<version>8.86.1</version>
	</parent>
	<modelVersion>4.0.0</modelVersion>
	<artifactId>aon.project</artifactId>
	<description>AON PROJECT</description>
	<name>AON PROJECT</name>
	<dependencies>
		<dependency>
			<groupId>com.esferalia.aon</groupId>
			<artifactId>aon.entity</artifactId>
			<version>${project.version}</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.config</artifactId>
			<version>${project.version}</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.company</artifactId>
			<version>${project.version}</version>
			<scope>compile</scope>
		</dependency>
	</dependencies>
</project>
 
