//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.30 at 11:02:08 AM CET 
//


package net.aonsolutions.core.araba.sii;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RegistroRespuestaConsultaDetOperIntracomunitariasType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RegistroRespuestaConsultaDetOperIntracomunitariasType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="IDFactura" type="{https://sii.araba.eus/documentos/SuministroInformacion.xsd}IDFacturaComunitariaType"/>
 *         &lt;element name="DatosDetOperIntracomunitarias" type="{https://sii.araba.eus/documentos/RespuestaConsultaLR.xsd}RespuestaDetOperIntracomunitariaType"/>
 *         &lt;element name="DatosPresentacion" type="{https://sii.araba.eus/documentos/SuministroInformacion.xsd}DatosPresentacion2Type"/>
 *         &lt;element name="EstadoFactura" type="{https://sii.araba.eus/documentos/RespuestaConsultaLR.xsd}EstadoFactura2Type"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RegistroRespuestaConsultaDetOperIntracomunitariasType", namespace = "https://sii.araba.eus/documentos/RespuestaConsultaLR.xsd", propOrder = {
    "idFactura",
    "datosDetOperIntracomunitarias",
    "datosPresentacion",
    "estadoFactura"
})
public class RegistroRespuestaConsultaDetOperIntracomunitariasType {

    @XmlElement(name = "IDFactura", required = true)
    protected IDFacturaComunitariaType idFactura;
    @XmlElement(name = "DatosDetOperIntracomunitarias", required = true)
    protected RespuestaDetOperIntracomunitariaType datosDetOperIntracomunitarias;
    @XmlElement(name = "DatosPresentacion", required = true)
    protected DatosPresentacion2Type datosPresentacion;
    @XmlElement(name = "EstadoFactura", required = true)
    protected EstadoFactura2Type estadoFactura;

    /**
     * Gets the value of the idFactura property.
     * 
     * @return
     *     possible object is
     *     {@link IDFacturaComunitariaType }
     *     
     */
    public IDFacturaComunitariaType getIDFactura() {
        return idFactura;
    }

    /**
     * Sets the value of the idFactura property.
     * 
     * @param value
     *     allowed object is
     *     {@link IDFacturaComunitariaType }
     *     
     */
    public void setIDFactura(IDFacturaComunitariaType value) {
        this.idFactura = value;
    }

    /**
     * Gets the value of the datosDetOperIntracomunitarias property.
     * 
     * @return
     *     possible object is
     *     {@link RespuestaDetOperIntracomunitariaType }
     *     
     */
    public RespuestaDetOperIntracomunitariaType getDatosDetOperIntracomunitarias() {
        return datosDetOperIntracomunitarias;
    }

    /**
     * Sets the value of the datosDetOperIntracomunitarias property.
     * 
     * @param value
     *     allowed object is
     *     {@link RespuestaDetOperIntracomunitariaType }
     *     
     */
    public void setDatosDetOperIntracomunitarias(RespuestaDetOperIntracomunitariaType value) {
        this.datosDetOperIntracomunitarias = value;
    }

    /**
     * Gets the value of the datosPresentacion property.
     * 
     * @return
     *     possible object is
     *     {@link DatosPresentacion2Type }
     *     
     */
    public DatosPresentacion2Type getDatosPresentacion() {
        return datosPresentacion;
    }

    /**
     * Sets the value of the datosPresentacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatosPresentacion2Type }
     *     
     */
    public void setDatosPresentacion(DatosPresentacion2Type value) {
        this.datosPresentacion = value;
    }

    /**
     * Gets the value of the estadoFactura property.
     * 
     * @return
     *     possible object is
     *     {@link EstadoFactura2Type }
     *     
     */
    public EstadoFactura2Type getEstadoFactura() {
        return estadoFactura;
    }

    /**
     * Sets the value of the estadoFactura property.
     * 
     * @param value
     *     allowed object is
     *     {@link EstadoFactura2Type }
     *     
     */
    public void setEstadoFactura(EstadoFactura2Type value) {
        this.estadoFactura = value;
    }

}
