
taxonomyRoot=D:/_INTECO_mayo2011/taxonomia-pgc2007-v1.4.1_publicada-web-icac/taxonomia
basePath=/../..
tempDirectory=log/transformation/
schemaLocationIOInterface=http://www.inteco.es/xbrl/pgc07/interfazES http://www.inteco.es/xbrl/pgc07/interfazES/pgc07-io-interface.xsd

