
package eus.bizkaia.ogasuna.sii.documentos.suministrobienesinversion;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import eus.bizkaia.ogasuna.sii.documentos.consultalr.LRFiltroBienInversionType;
import eus.bizkaia.ogasuna.sii.documentos.respuestaconsultalr.IndicadorPaginacionType;
import eus.bizkaia.ogasuna.sii.documentos.respuestaconsultalr.RegistroRespuestaConsultaBienesType;
import eus.bizkaia.ogasuna.sii.documentos.respuestaconsultalr.ResultadoConsultaType;
import eus.bizkaia.ogasuna.sii.documentos.respuestasuministro.EstadoEnvioType;
import eus.bizkaia.ogasuna.sii.documentos.respuestasuministro.RespuestaBienType;
import eus.bizkaia.ogasuna.sii.documentos.respuestasuministro.RespuestaLRBajaBienesInversionType;
import eus.bizkaia.ogasuna.sii.documentos.suministroinformacion.CabeceraConsultaSii;
import eus.bizkaia.ogasuna.sii.documentos.suministroinformacion.CabeceraSii;
import eus.bizkaia.ogasuna.sii.documentos.suministroinformacion.DatosPresentacionType;
import eus.bizkaia.ogasuna.sii.documentos.suministrolr.BajaLRBienesInversion;
import eus.bizkaia.ogasuna.sii.documentos.suministrolr.LRBienesInversionType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "siiSOAP", targetNamespace = "http://www.bizkaia.eus/ogasuna/sii/documentos/SuministroBienesInversion.wsdl")
@XmlSeeAlso({
    eus.bizkaia.ogasuna.sii.documentos.respuestasuministro.ObjectFactory.class,
    eus.bizkaia.ogasuna.sii.documentos.respuestaconsultalr.ObjectFactory.class,
    eus.bizkaia.ogasuna.sii.documentos.suministroinformacion.ObjectFactory.class,
    eus.bizkaia.ogasuna.sii.documentos.consultalr.ObjectFactory.class,
    eus.bizkaia.ogasuna.sii.documentos.suministrolr.ObjectFactory.class
})
public interface SiiSOAP {


    /**
     * 
     * @param datosPresentacion
     * @param csv
     * @param estadoEnvio
     * @param cabecera
     * @param respuestaLinea
     * @param registroLRBienesInversion
     */
    @WebMethod(operationName = "SuministroLRBienesInversion")
    @RequestWrapper(localName = "SuministroLRBienesInversion", targetNamespace = "http://www.bizkaia.eus/ogasuna/sii/documentos/SuministroLR.xsd", className = "eus.bizkaia.ogasuna.sii.documentos.suministrolr.SuministroLRBienesInversion")
    @ResponseWrapper(localName = "RespuestaLRBienesInversion", targetNamespace = "http://www.bizkaia.eus/ogasuna/sii/documentos/RespuestaSuministro.xsd", className = "eus.bizkaia.ogasuna.sii.documentos.respuestasuministro.RespuestaLRBienesInversionType")
    public void suministroLRBienesInversion(
        @WebParam(name = "Cabecera", targetNamespace = "http://www.bizkaia.eus/ogasuna/sii/documentos/SuministroInformacion.xsd", mode = WebParam.Mode.INOUT)
        Holder<CabeceraSii> cabecera,
        @WebParam(name = "RegistroLRBienesInversion", targetNamespace = "http://www.bizkaia.eus/ogasuna/sii/documentos/SuministroLR.xsd")
        List<LRBienesInversionType> registroLRBienesInversion,
        @WebParam(name = "CSV", targetNamespace = "http://www.bizkaia.eus/ogasuna/sii/documentos/RespuestaSuministro.xsd", mode = WebParam.Mode.OUT)
        Holder<String> csv,
        @WebParam(name = "DatosPresentacion", targetNamespace = "http://www.bizkaia.eus/ogasuna/sii/documentos/RespuestaSuministro.xsd", mode = WebParam.Mode.OUT)
        Holder<DatosPresentacionType> datosPresentacion,
        @WebParam(name = "EstadoEnvio", targetNamespace = "http://www.bizkaia.eus/ogasuna/sii/documentos/RespuestaSuministro.xsd", mode = WebParam.Mode.OUT)
        Holder<EstadoEnvioType> estadoEnvio,
        @WebParam(name = "RespuestaLinea", targetNamespace = "http://www.bizkaia.eus/ogasuna/sii/documentos/RespuestaSuministro.xsd", mode = WebParam.Mode.OUT)
        Holder<List<RespuestaBienType>> respuestaLinea);

    /**
     * 
     * @param anulacionLRBienesInversion
     * @return
     *     returns eus.bizkaia.ogasuna.sii.documentos.respuestasuministro.RespuestaLRBajaBienesInversionType
     */
    @WebMethod(operationName = "AnulacionLRBienesInversion")
    @WebResult(name = "RespuestaLRBajaBienesInversion", targetNamespace = "http://www.bizkaia.eus/ogasuna/sii/documentos/RespuestaSuministro.xsd", partName = "RespuestaAnulacionLRBienesInversion")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public RespuestaLRBajaBienesInversionType anulacionLRBienesInversion(
        @WebParam(name = "BajaLRBienesInversion", targetNamespace = "http://www.bizkaia.eus/ogasuna/sii/documentos/SuministroLR.xsd", partName = "AnulacionLRBienesInversion")
        BajaLRBienesInversion anulacionLRBienesInversion);

    /**
     * 
     * @param registroRespuestaConsultaLRBienesInversion
     * @param periodoLiquidacion
     * @param indicadorPaginacion
     * @param cabecera
     * @param filtroConsulta
     * @param resultadoConsulta
     */
    @WebMethod(operationName = "ConsultaLRBienesInversion")
    @RequestWrapper(localName = "ConsultaLRBienesInversion", targetNamespace = "http://www.bizkaia.eus/ogasuna/sii/documentos/ConsultaLR.xsd", className = "eus.bizkaia.ogasuna.sii.documentos.consultalr.LRConsultaBienesInversionType")
    @ResponseWrapper(localName = "RespuestaConsultaLRBienesInversion", targetNamespace = "http://www.bizkaia.eus/ogasuna/sii/documentos/RespuestaConsultaLR.xsd", className = "eus.bizkaia.ogasuna.sii.documentos.respuestaconsultalr.RespuestaConsultaLRBienesInversionType")
    public void consultaLRBienesInversion(
        @WebParam(name = "Cabecera", targetNamespace = "http://www.bizkaia.eus/ogasuna/sii/documentos/SuministroInformacion.xsd", mode = WebParam.Mode.INOUT)
        Holder<CabeceraConsultaSii> cabecera,
        @WebParam(name = "FiltroConsulta", targetNamespace = "http://www.bizkaia.eus/ogasuna/sii/documentos/ConsultaLR.xsd")
        LRFiltroBienInversionType filtroConsulta,
        @WebParam(name = "PeriodoLiquidacion", targetNamespace = "http://www.bizkaia.eus/ogasuna/sii/documentos/RespuestaConsultaLR.xsd", mode = WebParam.Mode.OUT)
        Holder<eus.bizkaia.ogasuna.sii.documentos.respuestaconsultalr.RespuestaConsultaLRFacturasType.PeriodoLiquidacion> periodoLiquidacion,
        @WebParam(name = "IndicadorPaginacion", targetNamespace = "http://www.bizkaia.eus/ogasuna/sii/documentos/RespuestaConsultaLR.xsd", mode = WebParam.Mode.OUT)
        Holder<IndicadorPaginacionType> indicadorPaginacion,
        @WebParam(name = "ResultadoConsulta", targetNamespace = "http://www.bizkaia.eus/ogasuna/sii/documentos/RespuestaConsultaLR.xsd", mode = WebParam.Mode.OUT)
        Holder<ResultadoConsultaType> resultadoConsulta,
        @WebParam(name = "RegistroRespuestaConsultaLRBienesInversion", targetNamespace = "http://www.bizkaia.eus/ogasuna/sii/documentos/RespuestaConsultaLR.xsd", mode = WebParam.Mode.OUT)
        Holder<List<RegistroRespuestaConsultaBienesType>> registroRespuestaConsultaLRBienesInversion);

}
