//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.22 at 10:00:11 AM CEST 
//


package com.esferalia.aon.dex.shared;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="operation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="num_regs_ok" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="num_regs_dup" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="error" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "operation",
    "numRegsOk",
    "numRegsDup",
    "error"
})
@XmlRootElement(name = "PosShiftDexResponse")
public class PosShiftDexResponse {

    @XmlElement(required = true)
    protected String operation;
    @XmlElement(name = "num_regs_ok")
    protected int numRegsOk;
    @XmlElement(name = "num_regs_dup")
    protected int numRegsDup;
    @XmlElement(required = true)
    protected String error;

    /**
     * Gets the value of the operation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOperation() {
        return operation;
    }

    /**
     * Sets the value of the operation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperation(String value) {
        this.operation = value;
    }

    /**
     * Gets the value of the numRegsOk property.
     * 
     */
    public int getNumRegsOk() {
        return numRegsOk;
    }

    /**
     * Sets the value of the numRegsOk property.
     * 
     */
    public void setNumRegsOk(int value) {
        this.numRegsOk = value;
    }

    /**
     * Gets the value of the numRegsDup property.
     * 
     */
    public int getNumRegsDup() {
        return numRegsDup;
    }

    /**
     * Sets the value of the numRegsDup property.
     * 
     */
    public void setNumRegsDup(int value) {
        this.numRegsDup = value;
    }

    /**
     * Gets the value of the error property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getError() {
        return error;
    }

    /**
     * Sets the value of the error property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setError(String value) {
        this.error = value;
    }

}
