#!/bin/sh
. aondir-functions

APP=aon-payroll

if ! aondir_has_app $APP; then

        aondir-addapp $APP &>/dev/null

        aondir-addrole User $APP &>/dev/null
        aondir-addrole Guest $APP &>/dev/null
        aondir-addrole Admin $APP &>/dev/null
        aondir-addrole Auditor $APP &>/dev/null
        aondir-addrole Statistics $APP &>/dev/null


        aondir-addprofile Asesor $APP Admin User &>/dev/null
        aondir-addprofile Invitado $APP Guest User &>/dev/null
else

        aondir-delrole $APP &>/dev/null
        aondir-delprofile $APP &>/dev/null

        aondir-addrole User $APP &>/dev/null
        aondir-addrole Guest $APP &>/dev/null
        aondir-addrole Admin $APP &>/dev/null
        aondir-addrole Auditor $APP &>/dev/null
        aondir-addrole Statistics $APP &>/dev/null

        aondir-addprofile Asesor $APP Admin User &>/dev/null
        aondir-addprofile Invitado $APP Guest User &>/dev/null

        aondir-chprofile $APP AonAdmin Asesor
        aondir-chprofile $APP AonInvitado Invitado

fi




