#!/bin/sh
. aondir-functions

APP=aon-document

if ! aondir_has_app $APP; then

        aondir-addapp $APP &>/dev/null

        aondir-addrole User $APP &>/dev/null
        aondir-addrole Guest $APP &>/dev/null
        aondir-addrole Admin $APP &>/dev/null

        aondir-addprofile Administrador $APP Admin User &>/dev/null
        aondir-addprofile Invitado $APP Guest User &>/dev/null

fi
