<?xml version="1.0"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<parent>
		<groupId>com.code.aon</groupId>
		<artifactId>aon.web.parent</artifactId>
		<version>5.0.2</version>
	</parent>
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.code.aon</groupId>
	<artifactId>aon-ebackoffice</artifactId>
	<packaging>war</packaging>
	<version>5.0.2</version>
	<description>AON WEB EBACKOFFICE</description>
	<name>AON WEB EBACKOFFICE</name>
	<build>
		<finalName>aon-ebackoffice</finalName>
	</build>
	<properties>
		<dbVersion>5.0.0</dbVersion>
	</properties>
	<dependencies>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.security.bridge</artifactId>
			<version>${pom.version}</version>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.rich.components</artifactId>
			<version>${pom.version}</version>
			<scope>compile</scope>
		</dependency>	
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.audit</artifactId>
			<version>${pom.version}</version>
			<scope>compile</scope>
		</dependency>				
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.company</artifactId>
			<version>${pom.version}</version>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.ebackoffice</artifactId>
			<version>${pom.version}</version>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.resources</artifactId>
			<version>${pom.version}</version>
			<scope>compile</scope>
		</dependency>
			<dependency>
			<groupId>com.code.aon</groupId>
			<artifactId>aon.ui.sales</artifactId>
			<version>${pom.version}</version>
			<scope>compile</scope>
		</dependency>
				
		<dependency>
			<groupId>javax.servlet.jsp</groupId>
			<artifactId>jsp-api</artifactId>
			<version>2.1</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>com.sun.facelets</groupId>
			<artifactId>jsf-facelets</artifactId>
			<version>1.1.15</version>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>commons-fileupload</groupId>
			<artifactId>commons-fileupload</artifactId>
			<version>1.1</version>
			<scope>runtime</scope>
		</dependency>
		<!--  
		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi</artifactId>
			<version>3.0.1-FINAL</version>
			<scope>runtime</scope>
		 <exclusions>
				<exclusion>
					<artifactId>commons-logging</artifactId>
					<groupId>commons-logging</groupId>
				</exclusion>
				<exclusion>
					<artifactId>log4j</artifactId>
					<groupId>log4j</groupId>
				</exclusion>
			</exclusions>
		</dependency>
		-->
		
	</dependencies>
</project>
