
name: Java CI with Maven

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      imageTag:
        description: 'Docker image tag'
        type: string
        required: true
        default: 'snapshot'
      resumeFrom:
        description: 'Resume from specified project'
        type: string
        required: true
        default: 'changed'
      commitBefore:
        description: 'Before Commit SHA to list cahges'
        type: string
        required: false
        default: 'HEAD^'
      skipUnitTests:
        description: 'Skip unit tests'
        type: boolean
        required: true
        default: false
      skipSeleniumTests:
        description: 'Skip Selenium integration tests'
        type: boolean
        required: true
        default: false
      skipIntegrationTests:
        description: 'Skip HtmlUnit integration  tests'
        type: boolean
        required: true
        default: false
      buildProductionVersion:
        description: 'Build production version'
        type: boolean
        required: true
        default: false
      publishVersion:
        description: 'Publish version to Amazon ECR'
        type: boolean
        required: true
        default: false
      javaVersion:
        description: 'Java version'
        type: choice
        options:
          - 25
          - 24
          - 23
          - 22
          - 21
        required: true
        default: 25
      javaDistribution:
        description: 'Java distribution'
        type: choice
        options:
          - temurin
          - oracle
          - corretto
        required: true
        default: temurin
      browser:
        type: choice
        description: Which browser to test
        required: true
        options:
          - chrome
          - firefox
          - edge
env:
  TZ: Europe/Madrid
  AWS_REGION: eu-west-1
  BROWSER: ${{ github.event.inputs.browser || 'chrome' }}
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
  IMAGE_TAG: ${{ github.event.inputs.imageTag || 'snapshot' }}
  RESUME_FROM: ${{ github.event.inputs.resumeFrom || '.' }}
  COMMIT_BEFORE: ${{ github.event.inputs.commitBefore || 'HEAD' }}
  JAVA_VERSION: ${{ github.event.inputs.javaVersion || 21 }}
  JAVA_DISTRIBUTION: ${{ github.event.inputs.javaDistribution || 'temurin' }}
  SKIP_UNIT_TESTS: ${{ github.event.inputs.skipUnitTests || false }}
  SKIP_SELENIUM_TESTS: ${{ github.event.inputs.skipSeleniumTests || false }}
  SKIP_INTEGRATION_TESTS: ${{ github.event.inputs.skipIntegrationTests || github.ref != 'refs/heads/master' }}
  PUBLISH_VERSION: ${{ github.event.inputs.publishVersion || github.ref == 'refs/heads/master' }}
  BUILD_PRODUCTION_VERSION: ${{ github.event.inputs.buildProductionVersion || github.ref == 'refs/heads/master' }}

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-${{ github.event.inputs.browser || 'chrome' }}
        ports:
          - 4444:4444
          - 7900:7900
        options: >-
          --add-host=test.aonsolutions.org:host-gateway 
          --add-host=payroll-test.aonsolutions.org:host-gateway 
          --add-host=general-payroll-test.aonsolutions.org:host-gateway 
          --add-host=inactiva-payroll-test.aonsolutions.org:host-gateway 
          --add-host=inactive-test.aonsolutions.org:host-gateway 
          --add-host=payer-inactive-test.aonsolutions.org:host-gateway 
          --add-host=default-inactive-test.aonsolutions.org:host-gateway 
          --add-host=multi-test.aonsolutions.org:host-gateway 
          --add-host=expired-multi-test.aonsolutions.org:host-gateway 
          --shm-size=2gb

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
      actions: write

    steps:
    - name: Checkout HEAD
      if:  ${{ env.RESUME_FROM != 'changed' }}
      uses: actions/checkout@v4

    - name: Checkout HEAD^
      if:  ${{ env.RESUME_FROM == 'changed' && env.COMMIT_BEFORE == 'HEAD^' }}
      uses: actions/checkout@v4
      with:
        fetch-depth: 2

    - name: Checkout all history for all tags and branches
      if:  ${{ env.RESUME_FROM == 'changed' && env.COMMIT_BEFORE != 'HEAD^' }}
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: ${{ env.JAVA_VERSION }}
        distribution: ${{ env.JAVA_DISTRIBUTION }}
        # cache: maven

    - name: Restore local Maven repository
      id: cache
      uses: actions/cache/restore@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ env.BRANCH_NAME }}

    # - name: Check restored local Maven repository
    #  if: steps.cache.outputs.cache-hit
    #  run: |
    #    find ~/.m2/repository -name "*SNAPSHOT.jar" | xargs md5sum

    - name: Set up MySQL
      run: |
        sudo sed -i "s/\(bind-address.*\)=.*/\1= 0.0.0.0/" /etc/mysql/mysql.conf.d/mysqld.cnf
        sudo systemctl start mysql.service
        sudo mysql -u root --password=root -v  <<-EOSQL
        --
        SET GLOBAL sql_mode = '';
        SET GLOBAL time_zone = '+01:00';
        --
        CREATE USER 'dbuser'@'%' IDENTIFIED WITH mysql_native_password BY 'serubd2000' ;
        GRANT ALL ON *.* TO 'dbuser'@'%' ;
        --
        -- default privileges include a row with Host='localhost' and User=''.
        CREATE USER 'dbuser'@'localhost' IDENTIFIED WITH mysql_native_password BY 'serubd2000' ;
        GRANT ALL ON *.* TO 'dbuser'@'localhost';
        EOSQL

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Install AWS CLI v2
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o /tmp/awscliv2.zip
        unzip -q /tmp/awscliv2.zip -d /tmp
        sudo /tmp/aws/install --bin-dir /usr/local/bin --install-dir /usr/local/aws-cli --update
        aws --version

    - name: Create connection file
      run: |
        sudo mkdir /etc/aon-aio
        sudo tee -a /etc/aon-aio/connection >/dev/null <<-EOF
        driverClass=com.mysql.cj.jdbc.Driver
        jdbcUrl=jdbc:mysql://127.0.0.1:3306
        user=dbuser
        password=serubd2000
        useSSL=false
        sessionVariables=SQL_SAFE_UPDATES=1
        EOF

    - name: Get changed projects
      if: ${{ env.RESUME_FROM == 'changed' }}
      run: |
        REACTOR_PROJECTS=$(mvn -q --also-make exec:exec -Dexec.executable="pwd"  | while read path; do [[ $path != `pwd` ]] && echo ${path#`pwd`/}; done | sed ':a;N;$!ba;s/\n/|/g')
        CHANGED_PROJECTS=$(git diff --name-only  ${COMMIT_BEFORE} | cut -d/ -f1 | grep  -E $REACTOR_PROJECTS  | sort -u | sed ':a;N;$!ba;s/\n/,/g' )
        echo "RESUME_FROM=${CHANGED_PROJECTS:=aon-web-aio}" >> $GITHUB_ENV

    - name: Build with Maven
      run: mvn -B -Dgwt.jjs.maxThreads=1 -Dgwt.working=true -DskipTests=${SKIP_UNIT_TESTS} --projects ${RESUME_FROM} --also-make-dependents -T 1C clean install

    - name: Setup context for Docker
      run: |
       [[ -f pool/target/pool-9.23-SNAPSHOT.jar ]] || mvn -pl pool package  &>/dev/null
       [[ -f aon-jaas/target/aon.jaas-9.23-SNAPSHOT.jar ]] || mvn -pl aon-jaas package  &>/dev/null
       [[ -f aon-db-up2date/target/aon.db.up2date-9.23-SNAPSHOT.jar ]]  || mvn -pl aon-db-up2date package  &>/dev/null
       [[ -f aon-common-resources/target/aon-common-resources-9.23-SNAPSHOT-templates.jar ]]  || mvn -pl aon-common-resources package  &>/dev/null

    - name: Build Docker aon-application image
      if: ${{ env.SKIP_INTEGRATION_TESTS == 'false' || env.SKIP_SELENIUM_TESTS == 'false' }}
      uses: docker/build-push-action@v6
      with:
        context: .
        load: true
        tags: ghcr.io/${{ github.repository_owner }}/aon-application:${{ env.BRANCH_NAME }}

    - name: Build Docker aon-db-up2date image
      if: ${{ env.SKIP_INTEGRATION_TESTS == 'false' || env.SKIP_SELENIUM_TESTS == 'false' }}
      uses: docker/build-push-action@v6
      with:
        context: ./aon-db-up2date
        load: true
        tags: ghcr.io/${{ github.repository_owner }}/aon-db-up2date:${{ env.BRANCH_NAME }}


    - name: Setup environment for integration testing
      if: ${{ env.SKIP_INTEGRATION_TESTS == 'false' || env.SKIP_SELENIUM_TESTS == 'false' }}
      env:
        ECR_REGISTRY: ${{ steps.login-ecr-spain.outputs.registry }}
      run: |
        DB_HOST=$(ip addr show docker0 | grep -oP 'inet \K[0-9\.]+')
        DB_FILE=$(find aon-htmlunit/src -name "test-aonsolutions-org.sql")
        mysql -h ${DB_HOST} -u dbuser --password=serubd2000 < ${DB_FILE}
        docker run -e DB_USER=dbuser -e DB_PASSWD=serubd2000 -e DB_HOST=${DB_HOST} ghcr.io/${{ github.repository_owner }}/aon-db-up2date:${BRANCH_NAME}
        docker run -d -p 8080:8080 -e DB_USER=dbuser -e DB_PASSWD=serubd2000 -e DB_HOST=${DB_HOST} ghcr.io/${{ github.repository_owner }}/aon-application:${BRANCH_NAME}
        sudo tee -a /etc/hosts >/dev/null <<-EOF
        127.0.0.1    payroll-test.aonsolutions.org
        127.0.0.1    tgss-payroll-test.aonsolutions.org
        127.0.0.1    artist-payroll-test.aonsolutions.org
        127.0.0.1    home-payroll-test.aonsolutions.org
        127.0.0.1    agrarian-payroll-test.aonsolutions.org
        127.0.0.1    general-payroll-test.aonsolutions.org
        127.0.0.1    inactiva-payroll-test.aonsolutions.org
        127.0.0.1    trainning-payroll-test.aonsolutions.org
        EOF

    - name: Running Selenium integration tests
      if: ${{ env.SKIP_SELENIUM_TESTS == 'false' }}
      run: |
        mvn -B \
        -DskipTests=${SKIP_SELENIUM_TESTS} \
        -Dtest='app/*TestCase.java' -f aon-selenium/pom.xml integration-test

    - name: Running HtmlUnit integration tests
      if: ${{ env.SKIP_INTEGRATION_TESTS == 'false' }}
      run: |
        mvn -B \
        -DskipTests=${SKIP_INTEGRATION_TESTS} \
        -Dintegration.test.user=admin \
        -Dintegration.test.password=org \
        -Dintegration.test.payroll.url=http://payroll-test.aonsolutions.org:8080/original \
        -Dintegration.test.general.payroll.url=http://general-payroll-test.aonsolutions.org:8080/original \
        -Dintegration.test.agrarian.payroll.url=http://agrarian-payroll-test.aonsolutions.org:8080/original \
        -Dintegration.test.trainning.payroll.url=http://trainning-payroll-test.aonsolutions.org:8080/original \
        -Dintegration.test.home.payroll.url=http://home-payroll-test.aonsolutions.org:8080/original \
        -Dintegration.test.artist.payroll.url=http://artist-payroll-test.aonsolutions.org:8080/original \
        -Dtest='!GeneralEnterpriseTest' -f aon-htmlunit/pom.xml integration-test

    - name: Build production version with Maven
      if: ${{ env.BUILD_PRODUCTION_VERSION == 'true' &&  env.RESUME_FROM != 'aon-web-aio'  }}
      run: mvn -B --resume-from aon-js-payroll -Drpm.release=false -DskipTests=true clean install

    - name: Build and push Docker aon-application image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/aon-application:${{ env.BRANCH_NAME }}

    - name: Build and push Docker aon-db-up2date image
      uses: docker/build-push-action@v6
      with:
        context: ./aon-db-up2date
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/aon-db-up2date:${{ env.BRANCH_NAME }}

    # - name: Build and push Docker aon-solutions image
    #   uses: docker/build-push-action@v6
    #   with:
    #     context: .
    #     file: ./aon-solutions/Dockerfile
    #     push: true
    #     tags: ghcr.io/${{ github.repository_owner }}/aon-solutions:${{ env.BRANCH_NAME }}

    - name: Build AWS lambda Functions
      if: github.ref == 'refs/heads/master'
      run : |
        mvn -B -Daws.lambda=true -DskipTests=true -pl aon-in-invoice clean install
        mvn -B -Daws.lambda=true -DskipTests=true -pl aon-in-payroll clean install

    - name: Publish WAR to GitHub Packages
      if: github.ref == 'refs/heads/master'
      run: mvn -B -pl aon-web-aio -Dgithub.actions=true deploy
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # - name: Pull images from GitHub Container Registry
    #   if: github.ref == 'refs/heads/master'
    #   run: |
    #     docker pull ghcr.io/${{ github.repository_owner }}/aon-solutions:${{ env.BRANCH_NAME }}
    #     docker pull ghcr.io/${{ github.repository_owner }}/aon-application:${{ env.BRANCH_NAME }}
    #     docker pull ghcr.io/${{ github.repository_owner }}/aon-db-up2date:${{ env.BRANCH_NAME }}

    - name: Login to Amazon ECR (Ireland)
      id: login-ecr-ireland
      uses: aws-actions/amazon-ecr-login@v1

    - name: Tag, and push images to Amazon ECR (Ireland)
      if: ${{ env.BUILD_PRODUCTION_VERSION == 'true' || env.PUBLISH_VERSION == 'true' }}
      env:
        ECR_REGISTRY: ${{ steps.login-ecr-ireland.outputs.registry }}
      run: |
        # docker tag ghcr.io/${{ github.repository_owner }}/aon-solutions:${{ env.BRANCH_NAME }} $ECR_REGISTRY/aonsolutions/aon-solutions:$IMAGE_TAG 
        docker tag ghcr.io/${{ github.repository_owner }}/aon-application:${{ env.BRANCH_NAME }} $ECR_REGISTRY/aonsolutions/aon-application:$IMAGE_TAG
        docker tag ghcr.io/${{ github.repository_owner }}/aon-db-up2date:${{ env.BRANCH_NAME }} $ECR_REGISTRY/aonsolutions/aon-db-up2date:$IMAGE_TAG
        # docker push $ECR_REGISTRY/aonsolutions/aon-solutions:$IMAGE_TAG
        docker push $ECR_REGISTRY/aonsolutions/aon-application:$IMAGE_TAG
        docker push $ECR_REGISTRY/aonsolutions/aon-db-up2date:$IMAGE_TAG

    # - name: Set AWS region to (Spain)
    #  if: github.ref == 'refs/heads/master'
    #  run: aws configure set default.region eu-south-2

    - name: Login to Amazon ECR (Spain)
      id: login-ecr-spain
      uses: aws-actions/amazon-ecr-login@v1
      env:
        AWS_REGION: eu-south-2

    - name: Tag, and push images to Amazon ECR (Spain)
      if: ${{ env.PUBLISH_VERSION == 'true' }}
      env:
        ECR_REGISTRY: ${{ steps.login-ecr-spain.outputs.registry }}
      run: |
        # docker tag ghcr.io/${{ github.repository_owner }}/aon-solutions:${{ env.BRANCH_NAME }} $ECR_REGISTRY/aon-solutions:$IMAGE_TAG 
        docker tag ghcr.io/${{ github.repository_owner }}/aon-application:${{ env.BRANCH_NAME }} $ECR_REGISTRY/aon-application:$IMAGE_TAG
        docker tag ghcr.io/${{ github.repository_owner }}/aon-db-up2date:${{ env.BRANCH_NAME }} $ECR_REGISTRY/aon-db-up2date:$IMAGE_TAG
        # docker push $ECR_REGISTRY/aon-solutions:$IMAGE_TAG 
        docker push $ECR_REGISTRY/aon-application:$IMAGE_TAG
        docker push $ECR_REGISTRY/aon-db-up2date:$IMAGE_TAG

    # Delete the old cache on hit to emulate a cache update. See
    # https://github.com/actions/cache/issues/342.
    - name: Delete old cache
      if: steps.cache.outputs.cache-hit
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Using `--repo` makes it so that this step doesn't require checking out the
      # repo first.
      run: gh cache delete --repo ${{ github.repository }} ${{ steps.cache.outputs.cache-primary-key }}

    - name: Save cache
      uses: actions/cache/save@v4
      if: always()
      # Save the cache even if build steps fail.
      # with:
      with:
        path: ~/.m2/repository
        key: ${{ steps.cache.outputs.cache-primary-key }}
        # key: ${{ runner.os }}-maven-${{ env.BRANCH_NAME }}

    # - name: Re-check restored local Maven repository
    #   if: always()
    #   run: |
    #     find ~/.m2/repository -name "*SNAPSHOT.jar" | xargs md5sum

    # - name: Deploy to Amazon ECS AON 
    #  if: github.ref == 'refs/heads/master'
    #  run : |
    #    aws ecs update-service --region=eu-south-2 --cluster AON --service AON-SOLUTIONS --force-new-deployment
    #    aws ecs update-service --region=eu-south-2 --cluster AON --service AON-APPLICATION --force-new-deployment



