# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  # push:
  #   branches: [ "master" ]
  pull_request:
    # By default, a workflow only runs when a pull_request event's activity type is opened, synchronize, or reopened. types: [opened, synchronize, repoened]
    branches: [ "master" ]
  workflow_dispatch:

env:
  AWS_REGION: eu-west-1
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Set up MySQL
      run: |
        sudo systemctl start mysql.service
        sudo mysql -u root --password=root -v  <<-EOSQL
        --
        SET GLOBAL sql_mode = '';
        SET GLOBAL time_zone = '+01:00';
        --
        CREATE USER 'dbuser'@'%' IDENTIFIED WITH mysql_native_password BY 'serubd2000' ;
        GRANT ALL ON *.* TO 'dbuser'@'%' ;
        --
        -- default privileges include a row with Host='localhost' and User=''. 
        CREATE USER 'dbuser'@'localhost' IDENTIFIED WITH mysql_native_password BY 'serubd2000' ;
        GRANT ALL ON *.* TO 'dbuser'@'localhost';
        EOSQL
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    - name: Create configuration file
      run: |
        mkdir /etc/aon-aio
        cat >> /etc/aon-aio/configuration <<-EOF
        driverClass=com.mysql.cj.jdbc.Driver
        jdbcUrl=jdbc:mysql://127.0.0.1:3306
        user=dbuser
        password=serubd2000
        timezone=Europe/Madrid
        useSSL=false
        sessionVariables=SQL_SAFE_UPDATES=1
        EOF
        cat /etc/aon-aio/configuration
    - name: Build with Maven
      run: mvn -B -Dgwt.working=true clean install
    
    # - name: Build the Docker images
    #  run: |
    #    docker build --no-cache -t aonsolutions/aon-application:test .
    #    docker build --no-cache -t aonsolutions/aon-db-up2date:test ./aon-db-up2date

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    # - name: Update dependency graph
    #   uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
