package com.esferalia.aon.file.payroll.contract.pdf;

import org.apache.commons.lang.ArrayUtils;

public enum LearningAnnex2Field implements IContractFieldName {
	
	// HEADER FIELDS
	CP_NO("c1"),
	CP_YES("c2"),
	FP_NO("c4"),
	FP_YES("c5"),
	CENTER_AVAILABLE_NO("c7"),
	CENTER_AVAILABLE_YES("c8"),

	CP_NAME("c3"),
	FP_TITLE("c6"),
	
	// ENTERPRISE FIELDS
	ENTERPRISE_NAME("c9"),
	ENTERPRISE_CIF("c10"),
	
	ENTERPRISE_DIR_STAFF_NAME("c11"),
	ENTERPRISE_DIR_STAFF_NIF("c12"),
	ENTERPRISE_DIR_STAFF_CHARGE("c13"),
	
	ENTERPRISE_PHONE_1("c14"),
	ENTERPRISE_PHONE_2("c15"),
	ENTERPRISE_PHONE_3("c16"),
	ENTERPRISE_PHONE_4("c17"),
	ENTERPRISE_PHONE_5("c18"),
	ENTERPRISE_PHONE_6("c19"),
	ENTERPRISE_PHONE_7("c20"),
	ENTERPRISE_PHONE_8("c21"),
	ENTERPRISE_PHONE_9("c22"),
	ENTERPRISE_EMAIL("c23"),
	
	// EMPLOYEE FIELDS
	EMPLOYEE_NAME("c24"),
	EMPLOYEE_NIF("c25"),

	// CONTRACT FIELDS
	CONTRACT_ID_NUMBER_1("c26"),
	CONTRACT_ID_NUMBER_2("c27"),
	CONTRACT_ID_NUMBER_3("c28"),
	CONTRACT_ID_NUMBER_4("c29"),
	CONTRACT_ID_NUMBER_5("c30"),
	CONTRACT_ID_NUMBER_6("c31"),
	CONTRACT_ID_NUMBER_7("c32"),
	CONTRACT_ID_NUMBER_8("c33"),
	CONTRACT_ID_NUMBER_9("c34"),
	CONTRACT_ID_NUMBER_10("c35"),
	CONTRACT_ID_NUMBER_11("c36"),
	CONTRACT_ID_NUMBER_12("c37"),
	CONTRACT_ID_NUMBER_13("c38"),
	CONTRACT_ID_NUMBER_14("c39"),
	CONTRACT_ID_NUMBER_15("c40"),
	CONTRACT_ID_NUMBER_16("c41"),
	
	CONTRACT_START_DATE("c42"),
	CONTRACT_END_DATE("c43"),
	CONTRACT_OCCUPATION("c44"),
	CONTRACT_CNO_1("c45"),
	CONTRACT_CNO_2("c46"),
	CONTRACT_CNO_3("c47"),
	CONTRACT_CNO_4("c48"),
	CONTRACT_CNO_5("c49"),
	CONTRACT_CNO_6("c50"),
	CONTRACT_CNO_7("c51"),
	CONTRACT_CNO_8("c52"),
	
	// TRAINING CENTER FIELDS
	TRAINING_CENTER_CODE("c53"),
	TRAINING_CENTER_DIR_STAFF_NAME("c54"),
	TRAINING_CENTER_DIR_STAFF_NIF("c55"),
	TRAINING_CENTER_DIR_STAFF_CHARGE("c56"),
	TRAINING_CENTER_NAME("c57"),
	TRAINING_CENTER_NIF("c58"),
	TRAINING_CENTER_ADDRESS("c59"),
	TRAINING_CENTER_ZIP_1("c60"),
	TRAINING_CENTER_ZIP_2("c61"),
	TRAINING_CENTER_ZIP_3("c62"),
	TRAINING_CENTER_ZIP_4("c63"),
	TRAINING_CENTER_ZIP_5("c64"),
	TRAINING_CENTER_TOWN("c65"),
	TRAINING_CENTER_PROVINCE("c66"),
	TRAINING_CENTER_PHONE_1("c67"),
	TRAINING_CENTER_PHONE_2("c68"),
	TRAINING_CENTER_PHONE_3("c69"),
	TRAINING_CENTER_PHONE_4("c70"),
	TRAINING_CENTER_PHONE_5("c71"),
	TRAINING_CENTER_PHONE_6("c72"),
	TRAINING_CENTER_PHONE_7("c73"),
	TRAINING_CENTER_PHONE_8("c74"),
	TRAINING_CENTER_PHONE_9("c75"),
	TRAINING_CENTER_EMAIL("c76"),
	
	// TRAINING COURSE FIELDS
	TRAINING_COURSE_NAME("c77"),
	TRAINING_COURSE_CODE("c78"),
	TRAINING_COURSE_CLASSROOM("c79"),
	TRAINING_COURSE_DISTANCE("c80"),
	TRAINING_COURSE_PHONE_LEARNING("c81"),
	TRAINING_COURSE_MIXED("c80"),
	TRAINING_COURSE_START_DATE("c83"),
	TRAINING_COURSE_END_DATE("c84"),
	TRAINING_COURSE_SCHEDULE("c85"),
	TRAINING_COURSE_FIRST_YEAR_MAIN_HOURS("c86"),
	TRAINING_COURSE_FIRST_YEAR_COMPLEMENTARY_HOURS("c87"),
	TRAINING_COURSE_NEXT_YEAR_MAIN_HOURS("c88"),
	TRAINING_COURSE_NEXT_YEAR_COMPLEMENTARY_HOURS("c89"),

	// FOORTER FIELDS
	SIGNATURE_PLACE("c90"),
	SIGNATURE_DAY("c91"),
	SIGNATURE_MONTH("c92"),
	SIGNATURE_YEAR("c93"),
	SIGNATURE_EMPLOYEE("c94"),
	SIGNATURE_EMPLOYEE_DIR_STAFF("c95"),
	SIGNATURE_ENTERPRISE_DIR_STAFF("c96"),
	SIGNATURE_TRAINING_CENTER_DIR_STAFF("c97"),
	;
	
	private String value;
	private boolean overridable;
	private boolean check;
	
	private LearningAnnex2Field(String value, boolean... values) {
		this.value = value;
		if(ArrayUtils.getLength(values)>0){
			this.overridable = values[0];
		}
		if(ArrayUtils.getLength(values)>1){
			this.check = values[1];
		}
	}
	
	@Override
	public boolean isOverridable(){
		return overridable;
	}
	@Override
	public boolean isCheck(){
		return check;
	}
	@Override
	public String getValue() {
		return value;
	}

	@Override
	public IContractFieldName[] getCompositeValues() {
		// TODO Auto-generated method stub
		return null;
	}
	
}
	
	