package com.esferalia.aon.file.payroll.contract.pdf;

import java.util.ResourceBundle;

import org.apache.commons.lang.ArrayUtils;


public enum PdfFieldTemporary implements IContractFieldName{
	
	/* 
	 * Contract enterprise fields
	 */
	ENTERPRISE_CIF,
	ENTERPRISE_DIR_STAFF_NAME(Boolean.TRUE),
	ENTERPRISE_DIR_STAFF_NIF(Boolean.TRUE),
	ENTERPRISE_DIR_STAFF_CHARGE(Boolean.TRUE),
	ENTERPRISE_NAME,
	ENTERPRISE_ADDRESS,
	ENTERPRISE_COUNTRY,
	ENTERPRISE_COUNTRY_CODE1,
	ENTERPRISE_COUNTRY_CODE2,
	ENTERPRISE_COUNTRY_CODE3,
	ENTERPRISE_MUNICIPALITY,
	ENTERPRISE_MUNICIPALITY_CODE1,
	ENTERPRISE_MUNICIPALITY_CODE2,
	ENTERPRISE_MUNICIPALITY_CODE3,
	ENTERPRISE_MUNICIPALITY_CODE4,
	ENTERPRISE_MUNICIPALITY_CODE5,
	ENTERPRISE_ZIP1,
	ENTERPRISE_ZIP2,
	ENTERPRISE_ZIP3,
	ENTERPRISE_ZIP4,
	ENTERPRISE_ZIP5,
	
	/* 
	 * Contract ccc fields
	 */
	CCC_REG1,
	CCC_REG2,
	CCC_REG3,
	CCC_REG4,
	CCC_PROV1,
	CCC_PROV2,
	CCC_NISS,
	CCC_CONTROL_DIGIT1,
	CCC_CONTROL_DIGIT2,
	CCC_ACTIVITY,
	CCC_ACTIVITY_CODE1,
	CCC_ACTIVITY_CODE2,
	
	/* 
	 * Contract workplace fields
	 */
	WORKPLACE_COUNTRY,
	WORKPLACE_COUNTRY_CODE1,
	WORKPLACE_COUNTRY_CODE2,
	WORKPLACE_COUNTRY_CODE3,
	WORKPLACE_MUNICIPALITY,
	WORKPLACE_MUNICIPALITY_CODE1,
	WORKPLACE_MUNICIPALITY_CODE2,
	WORKPLACE_MUNICIPALITY_CODE3,
	WORKPLACE_MUNICIPALITY_CODE4,
	WORKPLACE_MUNICIPALITY_CODE5,
	
	/*
	 * Contract employee fields
	 */
	EMPLOYEE_NAME,
	EMPLOYEE_NIF,
	EMPLOYEE_BIRTH_DATE,
	EMPLOYEE_NSS,
	EMPLOYEE_FORMATION_LEVEL,
	EMPLOYEE_FORMATION_CODE1,
	EMPLOYEE_FORMATION_CODE2,
	EMPLOYEE_COUNTRY,
	EMPLOYEE_COUNTRY_CODE1,
	EMPLOYEE_COUNTRY_CODE2,
	EMPLOYEE_COUNTRY_CODE3,
	EMPLOYEE_ADDRESS_MUNICIPALITY,
	EMPLOYEE_ADDRESS_MUNICIPALITY_CODE1,
	EMPLOYEE_ADDRESS_MUNICIPALITY_CODE2,
	EMPLOYEE_ADDRESS_MUNICIPALITY_CODE3,
	EMPLOYEE_ADDRESS_MUNICIPALITY_CODE4,
	EMPLOYEE_ADDRESS_MUNICIPALITY_CODE5,
	EMPLOYEE_ADDRESS_COUNTRY,
	EMPLOYEE_ADDRESS_COUNTRY_CODE1,
	EMPLOYEE_ADDRESS_COUNTRY_CODE2,
	EMPLOYEE_ADDRESS_COUNTRY_CODE3,
	
	/*
	 * LEGAL REPRESENTATION
	 */
	LEGAL_REPRESENTATIVE_NAME,
	LEGAL_REPRESENTATIVE_NIF,
	LEGAL_REPRESENTATIVE_CHARGE,
	
	
	/*
	 * Contract page 1
	 */
	PROFESSION,
	CATEGORY,
	FUNCTIONS(Boolean.TRUE),
	WORKPLACE_FULL_ADDRESS,
	WORKPLACE_FULL_ADDRESS_MORE,
	EMPLOYEE_CONTRACT_DISTANCE(Boolean.TRUE,Boolean.TRUE),
	EMPLOYEE_CONTRACT_DIST_ADDR(Boolean.TRUE),
	FULL_TIME,
	FULL_TIME_WEEK_HOURS(Boolean.TRUE),
	FULL_TIME_START_TIME(Boolean.TRUE),
	FULL_TIME_END_TIME(Boolean.TRUE),
	PARTIALLY_TIME,
	PARTIALLY_TIME_HOURS,
	PARTIALLY_TIME_DAYLY,
	PARTIALLY_TIME_WEEKLY,
	PARTIALLY_TIME_MONTHLY,
	PARTIALLY_TIME_YEARLY,
	PARTIALLY_TIME_JOB_LOWER_THAN(Boolean.TRUE),
	PARTIALLY_TIME_JOB_DISTRIB(Boolean.TRUE),
	START_DATE,
	END_DATE,
	END_DATE_TEXT(Boolean.TRUE),
	TRIAL_DURATION(Boolean.TRUE),
	GREATER_DURATION_AGREEMENT_COL(Boolean.TRUE,Boolean.TRUE),
	SALARY_AMOUNT(Boolean.TRUE),
	SALARY_PERIOD(Boolean.TRUE),
	SALARY_CONCEPT(Boolean.TRUE),
	
	/*
	 * Contract page 2
	 */
	HOLIDAYS(Boolean.TRUE),
	SEPE_MUNICIPALITY(Boolean.TRUE),
	
	
	/* Contract PAGE 3 */
	MAIN_OPT1_CHECK,
	MAIN_OPT2_CHECK,
	MAIN_OPT3_CHECK,
	MAIN_OPT4_CHECK,
	MAIN_OPT5_CHECK,
	MAIN_OPT6_CHECK,
	MAIN_OPT7_CHECK,
	MAIN_OPT8_CHECK,
	MAIN_OPT9_CHECK,
	MAIN_OPT10_CHECK,
	MAIN_OPT11_CHECK,
	MAIN_OPT12_CHECK,
	MAIN_OPT13_CHECK,
	MAIN_OPT14_CHECK,
	MAIN_OPT15_CHECK,
	MAIN_OPT16_CHECK,
	MAIN_OPT17_CHECK,
	MAIN_OPT18_CHECK,
	
//		OBRA O SERVICIO DETERMINADO. ( pág.4 )
	OPT1_OPTION_CHECK,
	OPT1_TC2_401,
	OPT1_TC2_501,
	OPT1_WORK_DESCRIPTION1(Boolean.TRUE),
	OPT1_WORK_DESCRIPTION2(Boolean.TRUE),
//		EVENTUAL POR CIRCUNSTANCIAS DE LA PRODUCCIÓN. (pág.5 )
	OPT2_OPTION_CHECK,
	OPT2_TC2_402,
	OPT2_TC2_502,
	OPT2_WORK_DESCRIPTION1(Boolean.TRUE),
	OPT2_WORK_DESCRIPTION2(Boolean.TRUE),
//		INTERINIDAD. ( pág.6 )
	OPT3_OPTION_CHECK,
	OPT3_TC2_410,
	OPT3_TC2_510,
	OPT3_REPLACED_WORKER_NAME(Boolean.TRUE),
	OPT3_CAUSE1,
	OPT3_CAUSE2,
	OPT3_CAUSE3,
	OPT3_CAUSE4,
	OPT3_CAUSE5,
	OPT3_CAUSE6,
	OPT3_CAUSE7,
	OPT3_CAUSE7_OPT1,
	OPT3_CAUSE7_OPT2,
	OPT3_CAUSE1_BONUS,
	OPT3_CAUSE2_BONUS,
	OPT3_CAUSE3_BONUS,
	OPT3_CAUSE4_BONUS,
	OPT3_CAUSE5_BONUS,
	OPT3_CAUSE6_BONUS,
//		PRIMER EMPLEO JOVEN. ( pág.7 )
	OPT4_OPTION_CHECK,
//		DE TRABAJADORES EN SITUACIÓN DE EXCLUSIÓN SOCIAL, VÍCTIMAS DE VIOLENCIA DE GÉNERO, DOMÉSTICA O VÍCTIMA DE TERRORISMO. ( pág.8 )
	OPT5_OPTION_CHECK,
//		DE TRABAJADORES EN SITUACIÓN DE EXCLUSIÓN SOCIAL POR EMPRESA DE INSERCIÓN. ( pág.9 )
	OPT6_OPTION_CHECK,
//		DE TRABAJADORES MAYORES DE 52 AÑOS BENEFICIARIOS DE LOS SUBSIDIOS POR DESEMPLEO. ( pág.10 )
	OPT7_OPTION_CHECK,
//		SITUACIÓN DE JUBILACIÓN PARCIAL. ( pág.11 )
	OPT8_OPTION_CHECK,
	OPT8_REDUCTION_PERCENT,
//		RELEVO. ( pág.12 )
	OPT9_OPTION_CHECK,
//		A TIEMPO PARCIAL CON VINCULACIÓN FORMATIVA. ( pág.13 )
	OPT10_OPTION_CHECK,
	OPT10_TC2_501,
	OPT10_TC2_502,
	OPT10_REQUIREMENTS_OPT1,
	OPT10_REQUIREMENTS_OPT2,
	OPT10_REQUIREMENTS_OPT3,
	OPT10_REQUIREMENTS_OPT4,
	OPT10_REQUIREMENTS_OPT(OPT10_REQUIREMENTS_OPT1, OPT10_REQUIREMENTS_OPT2, OPT10_REQUIREMENTS_OPT3, OPT10_REQUIREMENTS_OPT4),
	OPT10_FORMATION_OPT1,
	OPT10_FORMATION_OPT2,
	OPT10_FORMATION_OPT(OPT10_FORMATION_OPT1, OPT10_FORMATION_OPT2),
	OPT10_FORMATION_TYPE_OPT1,
	OPT10_FORMATION_TYPE_OPT2,
	OPT10_FORMATION_TYPE_OPT(OPT10_FORMATION_TYPE_OPT1, OPT10_FORMATION_TYPE_OPT2),
	OPT10_FORMATION_TYPE_OPT1_TEXT(Boolean.TRUE),
	OPT10_FORMATION_TYPE_OPT2_TEXT(Boolean.TRUE),
	OPT10_REDUCTION_OPT1,
	OPT10_REDUCTION_OPT2,
//		DE TRABAJOS DE INTERÉS SOCIAL/FOMENTO DE EMPLEO AGRARIO. ( pág.14 )
	OPT11_OPTION_CHECK,
	OPT11_FULL_TIME,
	OPT11_TC2_401,
	OPT11_TC2_402,
	OPT11_TC2_410,
	OPT11_TC2_450,
	OPT11_TC2_990_FULL_TIME,
	OPT11_PARTIALLY_TIME,
	OPT11_TC2_501,
	OPT11_TC2_502,
	OPT11_TC2_510,
	OPT11_TC2_550,
	OPT11_TC2_990_PARTIALLY_TIME,
	OPT11_SOCIAL_INTERES_CHECK,
	OPT11_AGRICULTURAL_PROMOTION_CHECK,
	OPT11_EMPLOYER_LOCAL_CORPORATION_CHECK,
	OPT11_EMPLOYER_STATE_ADMINISTRATION_CHECK,
	OPT11_EMPLOYER_COMMUNITY_CHECK,
	OPT11_EMPLOYER_NONPROFIT_ENTITY_CHECK,
	OPT11_EMPLOYER_UNIVERSITY_CHECK,
	OPT11_COLLECTIVE_AGREEMENT,
//		DE TRABAJADORES DEL SERVICIO DEL HOGAR FAMILIAR. (pág.15 )
	OPT12_OPTION_CHECK,
	OPT12_FULL_TIME,
	OPT12_TC2_401,
	OPT12_TC2_410,
	OPT12_PARTIALLY_TIME,
	OPT12_TC2_501,
	OPT12_TC2_510,
	OPT12_ONSITE_HOURS_YES,
	OPT12_ONSITE_HOURS_NO,
	OPT12_ONSITE_HOURS(OPT12_ONSITE_HOURS_YES, OPT12_ONSITE_HOURS_NO),
	OPT12_ONSITE_WEEK_HOURS(Boolean.TRUE),
	OPT12_ONSITE_HOURS_DISTRIB(Boolean.TRUE),
	OPT12_SALARY_OPT1,
	OPT12_SALARY_OPT2,
	OPT12_SALARY_OPT3,
	OPT12_SALARY_OPT(OPT12_SALARY_OPT1, OPT12_SALARY_OPT2, OPT12_SALARY_OPT3),
	OPT12_OVERNIGHT_YES,
	OPT12_OVERNIGHT_NO,
	OPT12_OVERNIGHT(OPT12_OVERNIGHT_YES, OPT12_OVERNIGHT_NO),
	OPT12_OVERNIGHT_WEEK_DAYS(Boolean.TRUE),
//		DE PERSONAS CON DISCAPACIDAD. (pág.16 )
	OPT13_OPTION_CHECK,
//		DE PERSONAS CON DISCAPACIDAD EN CENTROS ESPECIALES DE EMPLEO. (pág.17 )
	OPT14_OPTION_CHECK,
	OPT14_FULL_TIME,
	OPT14_TC2_401,
	OPT14_TC2_402,
	OPT14_TC2_410,
	OPT14_TC2_430,
	OPT14_TC2_441,
	OPT14_TC2_990_FULL_TIME,
	OPT14_PARTIALLY_TIME,
	OPT14_TC2_501,
	OPT14_TC2_502,
	OPT14_TC2_510,
	OPT14_TC2_530,
	OPT14_TC2_540,
	OPT14_TC2_541,
	OPT14_TC2_990_PARTIALLY_TIME,
	OPT14_TRIAL_PERIOD(Boolean.TRUE),
	OPT14_TRIAL_TERMS(Boolean.TRUE),
	OPT14_PROFESSION(Boolean.TRUE),
	OPT14_DISTANCE_ADJUSTMENT(Boolean.TRUE),
	OPT14_DISTANCE_ADJUSTMENT_MORE(Boolean.TRUE),
	OPT14_COLLECTIVE_AGREEMENT(Boolean.TRUE),
//		DE INVESTIGADORES. ( pág.18 )
	OPT15_OPTION_CHECK,
//		DE TRABAJADOES/AS PENADOS EN INSTITUCIONES PENITENCIARIAS. (pág.19 )
	OPT16_OPTION_CHECK,
//		DE MENORES Y JÓVENES EN CENTROS DE MENORES. ( SOMETIDOS A MEDIDADAS DE INTERNAMIENTO PREVISTAS EN LA LEY ORGÁNICA 5/2000 DE 21 DE ENERO ). ( pág.20 )
	OPT17_OPTION_CHECK,
//		OTRAS SITUACIONES. ( pág.21 )
	OPT18_OPTION_CHECK,
	
	;
	
	private String BASE_NAME = "com.esferalia.aon.file.payroll.i18n.PdfFieldsTemporary";

	private boolean overridable;
	private boolean check;
	private PdfFieldTemporary[] compositeValues;
	
	private PdfFieldTemporary() {
	}
	private PdfFieldTemporary(PdfFieldTemporary... compositeValues) {
		this.compositeValues = compositeValues;
	}
	private PdfFieldTemporary(boolean... values) {
		this.overridable = (ArrayUtils.getLength(values)>0)?values[0]:false;
		this.check= (ArrayUtils.getLength(values)>1)?values[1]:false;
	}
	
	@Override
	public boolean isOverridable(){
		return overridable || compositeValues!=null;
	}
	@Override
	public boolean isCheck(){
		return check || compositeValues!=null;
	}
	@Override
	public boolean isCommonValue(){
		return !this.toString().matches("OPT\\d+_\\w+");
	}
	@Override
	public String getValue() {
		return ResourceBundle.getBundle(BASE_NAME).getString(toString());
	}
	@Override
	public IContractFieldName[] getCompositeValues(){
		return compositeValues;
	}
	
}	
