package com.esferalia.aon.file.payroll.contract.pdf;

import java.util.ResourceBundle;

import org.apache.commons.lang.ArrayUtils;



public enum PdfFieldLearning implements IContractFieldName{
	
	/* 
	 * Contract enterprise fields
	 */
	ENTERPRISE_CIF,
	ENTERPRISE_DIR_STAFF_NAME(Boolean.TRUE),
	ENTERPRISE_DIR_STAFF_NIF(Boolean.TRUE),
	ENTERPRISE_DIR_STAFF_CHARGE(Boolean.TRUE),
	ENTERPRISE_NAME,
	ENTERPRISE_ADDRESS,
	ENTERPRISE_COUNTRY,
	ENTERPRISE_COUNTRY_CODE1,
	ENTERPRISE_COUNTRY_CODE2,
	ENTERPRISE_COUNTRY_CODE3,
	ENTERPRISE_MUNICIPALITY,
	ENTERPRISE_MUNICIPALITY_CODE1,
	ENTERPRISE_MUNICIPALITY_CODE2,
	ENTERPRISE_MUNICIPALITY_CODE3,
	ENTERPRISE_MUNICIPALITY_CODE4,
	ENTERPRISE_MUNICIPALITY_CODE5,
	ENTERPRISE_ZIP1,
	ENTERPRISE_ZIP2,
	ENTERPRISE_ZIP3,
	ENTERPRISE_ZIP4,
	ENTERPRISE_ZIP5,
	
	/* 
	 * Contract ccc fields
	 */
	CCC_REG1,
	CCC_REG2,
	CCC_REG3,
	CCC_REG4,
	CCC_PROV1,
	CCC_PROV2,
	CCC_NISS,
	CCC_CONTROL_DIGIT1,
	CCC_CONTROL_DIGIT2,
	CCC_ACTIVITY,
	CCC_ACTIVITY_CODE1,
	CCC_ACTIVITY_CODE2,
	
	/* 
	 * Contract workplace fields
	 */
	WORKPLACE_COUNTRY,
	WORKPLACE_COUNTRY_CODE1,
	WORKPLACE_COUNTRY_CODE2,
	WORKPLACE_COUNTRY_CODE3,
	WORKPLACE_MUNICIPALITY,
	WORKPLACE_MUNICIPALITY_CODE1,
	WORKPLACE_MUNICIPALITY_CODE2,
	WORKPLACE_MUNICIPALITY_CODE3,
	WORKPLACE_MUNICIPALITY_CODE4,
	WORKPLACE_MUNICIPALITY_CODE5,
	
	/*
	 * Contract employee fields
	 */
	EMPLOYEE_NAME,
	EMPLOYEE_NIF,
	EMPLOYEE_BIRTH_DATE,
	EMPLOYEE_NSS,
	EMPLOYEE_FORMATION_LEVEL,
	EMPLOYEE_FORMATION_CODE1,
	EMPLOYEE_FORMATION_CODE2,
	EMPLOYEE_COUNTRY,
	EMPLOYEE_COUNTRY_CODE1,
	EMPLOYEE_COUNTRY_CODE2,
	EMPLOYEE_COUNTRY_CODE3,
	EMPLOYEE_ADDRESS_MUNICIPALITY,
	EMPLOYEE_ADDRESS_MUNICIPALITY_CODE1,
	EMPLOYEE_ADDRESS_MUNICIPALITY_CODE2,
	EMPLOYEE_ADDRESS_MUNICIPALITY_CODE3,
	EMPLOYEE_ADDRESS_MUNICIPALITY_CODE4,
	EMPLOYEE_ADDRESS_MUNICIPALITY_CODE5,
	EMPLOYEE_ADDRESS_COUNTRY,
	EMPLOYEE_ADDRESS_COUNTRY_CODE1,
	EMPLOYEE_ADDRESS_COUNTRY_CODE2,
	EMPLOYEE_ADDRESS_COUNTRY_CODE3,
	
	/*
	 * LEGAL REPRESENTATION
	 */
	LEGAL_REPRESENTATIVE_NAME(Boolean.TRUE),
	LEGAL_REPRESENTATIVE_NIF(Boolean.TRUE),
	LEGAL_REPRESENTATIVE_CHARGE(Boolean.TRUE),
	
	/*
	 * Contract page 1
	 */
	QUOTE_BONUS_YES,
	QUOTE_BONUS_NO,
	QUOTE_BONUS(QUOTE_BONUS_YES, QUOTE_BONUS_NO),
	EMPLOYEE_OPT1,
	EMPLOYEE_OPT2,
	EMPLOYEE_OPT3,
	EMPLOYEE_OPT4,
	EMPLOYEE_OPT(EMPLOYEE_OPT1,EMPLOYEE_OPT2,EMPLOYEE_OPT3,EMPLOYEE_OPT4),
	
	
	ACTIVITY_EMPLOYEE_PROFFESION,
	CNO1,
	CNO2,
	CNO3,
	CNO4,
	ACTIVITY_EMPLOYEE_CATEGORY,
	ACTIVITY_WORKPLACE_ADDRESS1,
	ACTIVITY_WORKPLACE_ADDRESS2,
	
	/*
	 * Contract page 2
	 */
	CONTRACT_EMPLOYEE_PROFFESION,
	CONTRACT_EMPLOYEE_CATEGORY,
	CONTRACT_WORKPLACE_ADDRESS(Boolean.TRUE),
	FORMATION_TEACHER(Boolean.TRUE),
	FORMATION_TEACHER_QUALIFICATION(Boolean.TRUE),
	
	JOURNAL_HOURS,
	TOTAL_HOURS,
	JOURNAL_PERCENT,
	JOURNAL_COLLECTIVE_AGREEMENT,
//		EFFECTIVE_JOURNAL_SCHEDULE("Texto39",Boolean.TRUE),
	HORARIO_LABORAL(Boolean.TRUE),
//		FORMATION_JOURNAL_SCHEDULE("Texto40",Boolean.TRUE),
	HORARIO_LECTIVO(Boolean.TRUE),
//		FORMATION_JOURNAL_SCHEDULE2,
	HORARIO_LECTIVO2,
	
	CONTRACT_DURATION,
	START_DATE,
	END_DATE,
	TRIAL_DURATION(Boolean.TRUE),
	TRIAL_DURATION_INCREASE(Boolean.TRUE, Boolean.TRUE),
	
	SALARY_AMOUNT(Boolean.TRUE),
	SALARY_PERIOD(Boolean.TRUE),
	
	HOLIDAYS(Boolean.TRUE),
	
	ANNEX_I_CHECK(Boolean.TRUE,Boolean.TRUE),
	ANNEX_II_CHECK(Boolean.TRUE,Boolean.TRUE),
	
	COLLECTIVE_AGREEMENT,
	
	SEPE_TOWN_FOR_CONTRACT_START,
	SEPE_TOWN_FOR_CONTRACT_END,
	
	
	SIGN_TOWN,
	SIGN_DAY,
	SIGN_MONTH,
	SIGN_YEAR,
	
	
	/* Contract PAGE 3 */
	MAIN_OPT1_CHECK,
	MAIN_OPT2_CHECK,
	MAIN_OPT3_CHECK,
	MAIN_OPT4_CHECK,
	
//		FORMACIÓN Y APRENDIZAJE ( ORDINARIO ). ( pág.4 )
	OPT1_OPTION_CHECK,
	OPT1_QUOTE_BONUS,
	OPT1_QUOTE_NO_BONUS,
	
	// TODO: complete this option
//		DE TRABAJADORES EN SITUACIÓN DE EXCLUSIÓN SOCIAL, VÍCTIMAS DE VIOLENCIA DE GÉNERO, DOMÉSTICA O VÍCTIMA DE TERRORISMO . ( pág.5 )
	OPT2_OPTION_CHECK,
	
	// TODO: complete this option
//		DE PERSONAS CON DISCAPACIDAD EN CENTROS ESPECIALES DE EMPLEO. ( pág.6 )
	OPT3_OPTION_CHECK,
	
	// TODO: complete this option
//		DE TRABAJOS DE INTERÉS SOCIAL/FOMENTO DE EMPLEO AGRARIO. ( pág.7 )
	OPT4_OPTION_CHECK,
	
	// PAGE 9. ANEX I
	
	// PAGE 12. ANEX II
	// HEADER FIELDS
	ANNEXII_CP_NO,
	ANNEXII_CP_YES,
	ANNEXII_FP_NO,
	ANNEXII_FP_YES,
	ANNEXII_CENTER_AVAILABLE_NO,
	ANNEXII_CENTER_AVAILABLE_YES,

	ANNEXII_CP_NAME,
	ANNEXII_FP_TITLE,
	
	// ENTERPRISE FIELDS
	ANNEXII_ENTERPRISE_NAME,
	ANNEXII_ENTERPRISE_CIF,
	
	ANNEXII_ENTERPRISE_DIR_STAFF_NAME,
	ANNEXII_ENTERPRISE_DIR_STAFF_NIF,
	ANNEXII_ENTERPRISE_DIR_STAFF_CHARGE,
	
	ANNEXII_ENTERPRISE_PHONE_1,
	ANNEXII_ENTERPRISE_PHONE_2,
	ANNEXII_ENTERPRISE_PHONE_3,
	ANNEXII_ENTERPRISE_PHONE_4,
	ANNEXII_ENTERPRISE_PHONE_5,
	ANNEXII_ENTERPRISE_PHONE_6,
	ANNEXII_ENTERPRISE_PHONE_7,
	ANNEXII_ENTERPRISE_PHONE_8,
	ANNEXII_ENTERPRISE_PHONE_9,
	ANNEXII_ENTERPRISE_EMAIL,
	
	// EMPLOYEE FIELDS
	ANNEXII_EMPLOYEE_NAME,
	ANNEXII_EMPLOYEE_NIF,

	// CONTRACT FIELDS
	ANNEXII_CONTRACT_ID_NUMBER_1,
	ANNEXII_CONTRACT_ID_NUMBER_2,
	ANNEXII_CONTRACT_ID_NUMBER_3,
	ANNEXII_CONTRACT_ID_NUMBER_4,
	ANNEXII_CONTRACT_ID_NUMBER_5,
	ANNEXII_CONTRACT_ID_NUMBER_6,
	ANNEXII_CONTRACT_ID_NUMBER_7,
	ANNEXII_CONTRACT_ID_NUMBER_8,
	ANNEXII_CONTRACT_ID_NUMBER_9,
	ANNEXII_CONTRACT_ID_NUMBER_10,
	ANNEXII_CONTRACT_ID_NUMBER_11,
	ANNEXII_CONTRACT_ID_NUMBER_12,
	ANNEXII_CONTRACT_ID_NUMBER_13,
	ANNEXII_CONTRACT_ID_NUMBER_14,
	ANNEXII_CONTRACT_ID_NUMBER_15,
	ANNEXII_CONTRACT_ID_NUMBER_16,
	
	ANNEXII_CONTRACT_START_DATE,
	ANNEXII_CONTRACT_END_DATE,
	ANNEXII_CONTRACT_OCCUPATION,
	ANNEXII_CONTRACT_CNO_1,
	ANNEXII_CONTRACT_CNO_2,
	ANNEXII_CONTRACT_CNO_3,
	ANNEXII_CONTRACT_CNO_4,
	ANNEXII_CONTRACT_CNO_5,
	ANNEXII_CONTRACT_CNO_6,
	ANNEXII_CONTRACT_CNO_7,
	ANNEXII_CONTRACT_CNO_8,
	
	// TRAINING CENTER FIELDS
	ANNEXII_TRAINING_CENTER_CODE,
	ANNEXII_TRAINING_CENTER_DIR_STAFF_NAME,
	ANNEXII_TRAINING_CENTER_DIR_STAFF_NIF,
	ANNEXII_TRAINING_CENTER_DIR_STAFF_CHARGE,
	ANNEXII_TRAINING_CENTER_NAME,
	ANNEXII_TRAINING_CENTER_NIF,
	ANNEXII_TRAINING_CENTER_ADDRESS,
	ANNEXII_TRAINING_CENTER_ZIP_1,
	ANNEXII_TRAINING_CENTER_ZIP_2,
	ANNEXII_TRAINING_CENTER_ZIP_3,
	ANNEXII_TRAINING_CENTER_ZIP_4,
	ANNEXII_TRAINING_CENTER_ZIP_5,
	ANNEXII_TRAINING_CENTER_TOWN,
	ANNEXII_TRAINING_CENTER_PROVINCE,
	ANNEXII_TRAINING_CENTER_PHONE_1,
	ANNEXII_TRAINING_CENTER_PHONE_2,
	ANNEXII_TRAINING_CENTER_PHONE_3,
	ANNEXII_TRAINING_CENTER_PHONE_4,
	ANNEXII_TRAINING_CENTER_PHONE_5,
	ANNEXII_TRAINING_CENTER_PHONE_6,
	ANNEXII_TRAINING_CENTER_PHONE_7,
	ANNEXII_TRAINING_CENTER_PHONE_8,
	ANNEXII_TRAINING_CENTER_PHONE_9,
	ANNEXII_TRAINING_CENTER_EMAIL,
	
	// TRAINING COURSE FIELDS
	ANNEXII_TRAINING_COURSE_NAME,
	ANNEXII_TRAINING_COURSE_CODE,
	ANNEXII_TRAINING_COURSE_CLASSROOM,
	ANNEXII_TRAINING_COURSE_DISTANCE,
	ANNEXII_TRAINING_COURSE_PHONE_LEARNING,
	ANNEXII_TRAINING_COURSE_MIXED,
	ANNEXII_TRAINING_COURSE_START_DATE,
	ANNEXII_TRAINING_COURSE_END_DATE,
	ANNEXII_TRAINING_COURSE_SCHEDULE,
	ANNEXII_TRAINING_COURSE_FIRST_YEAR_MAIN_HOURS,
	ANNEXII_TRAINING_COURSE_FIRST_YEAR_COMPLEMENTARY_HOURS,
	ANNEXII_TRAINING_COURSE_NEXT_YEAR_MAIN_HOURS,
	ANNEXII_TRAINING_COURSE_NEXT_YEAR_COMPLEMENTARY_HOURS,

	// FOORTER FIELDS
	ANNEXII_SIGNATURE_PLACE,
	ANNEXII_SIGNATURE_DAY,
	ANNEXII_SIGNATURE_MONTH,
	ANNEXII_SIGNATURE_YEAR,
	ANNEXII_SIGNATURE_EMPLOYEE,
	ANNEXII_SIGNATURE_EMPLOYEE_DIR_STAFF,
	ANNEXII_SIGNATURE_ENTERPRISE_DIR_STAFF,
	ANNEXII_SIGNATURE_TRAINING_CENTER_DIR_STAFF,
	
	
	;
	
	private String BASE_NAME = "com.esferalia.aon.file.payroll.i18n.PdfFieldsLearning";
	
	private boolean overridable;
	private boolean check;
	private PdfFieldLearning[] compositeValues;
	
	private PdfFieldLearning() {
	}
	private PdfFieldLearning(PdfFieldLearning... compositeValues) {
		this.compositeValues = compositeValues;
	}
	private PdfFieldLearning(boolean... values) {
		this.overridable = (ArrayUtils.getLength(values)>0)?values[0]:false;		
		this.check= (ArrayUtils.getLength(values)>1)?values[1]:false;
	}
	
	@Override
	public boolean isOverridable(){
		return overridable || compositeValues!=null;
	}
	@Override
	public boolean isCheck(){
		return check || compositeValues!=null;
	}
	@Override
	public boolean isCommonValue(){
		return !this.toString().matches("OPT\\d+_\\w+");
	}
	@Override
	public String getValue(){
		return ResourceBundle.getBundle(BASE_NAME).getString(toString());
	}
	@Override
	public IContractFieldName[] getCompositeValues(){
		return compositeValues;
	}
	
}
	