bgcolor_color_de_fondo = #88b8cb	
bgcolor_color_fondo_menu = #f3f3f3
color_color_de_texto = #666666
color_color_de_texto_menu = #999999
color_color_texto_titulos = #336699
color_color_texto_pie = #cccccc
color_color_bordes = #006600
color_color_bordes_contenido = #eeeeee
font_fuente = 2
size_tamano_de_fuente = 12
size_tamano_de_fuente_menu = 18
size_tamano_de_fuente_pie = 9
border_bordes = 1
border_bordes_contenido = 2