//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.10 at 04:04:50 PM CEST 
//


package com.esferalia.aon.occam.impl.jooq.dao.mod200_2015.jaxb;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tipo_Pagina29 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tipo_Pagina29">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="T258" type="{}tipo_ImpNegativo" minOccurs="0"/>
 *         &lt;element name="T259" type="{}tipo_ImpNegativo" minOccurs="0"/>
 *         &lt;element name="T260" type="{}tipo_ImpNegativo" minOccurs="0"/>
 *         &lt;element name="T262" type="{}tipo_ImpNegativo" minOccurs="0"/>
 *         &lt;element name="T263" type="{}tipo_ImpNegativo" minOccurs="0"/>
 *         &lt;element name="T264" type="{}tipo_ImpNegativo" minOccurs="0"/>
 *         &lt;element name="T265" type="{}tipo_ImpNegativo" minOccurs="0"/>
 *         &lt;element name="T267" type="{}tipo_ImpNegativo" minOccurs="0"/>
 *         &lt;element name="T268" type="{}tipo_ImpNegativo" minOccurs="0"/>
 *         &lt;element name="T269" type="{}tipo_ImpNegativo" minOccurs="0"/>
 *         &lt;element name="T271" type="{}tipo_ImpNegativo" minOccurs="0"/>
 *         &lt;element name="T272" type="{}tipo_ImpNegativo" minOccurs="0"/>
 *         &lt;element name="T273" type="{}tipo_ImpNegativo" minOccurs="0"/>
 *         &lt;element name="T275" type="{}tipo_ImpNegativo" minOccurs="0"/>
 *         &lt;element name="T276" type="{}tipo_ImpNegativo" minOccurs="0"/>
 *         &lt;element name="T277" type="{}tipo_ImpNegativo" minOccurs="0"/>
 *         &lt;element name="T278" type="{}tipo_ImpNegativo" minOccurs="0"/>
 *         &lt;element name="T279" type="{}tipo_ImpNegativo" minOccurs="0"/>
 *         &lt;element name="T280" type="{}tipo_ImpNegativo" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tipo_Pagina29", propOrder = {
    "t258",
    "t259",
    "t260",
    "t262",
    "t263",
    "t264",
    "t265",
    "t267",
    "t268",
    "t269",
    "t271",
    "t272",
    "t273",
    "t275",
    "t276",
    "t277",
    "t278",
    "t279",
    "t280"
})
public class TipoPagina29 {

    @XmlElement(name = "T258")
    protected BigDecimal t258;
    @XmlElement(name = "T259")
    protected BigDecimal t259;
    @XmlElement(name = "T260")
    protected BigDecimal t260;
    @XmlElement(name = "T262")
    protected BigDecimal t262;
    @XmlElement(name = "T263")
    protected BigDecimal t263;
    @XmlElement(name = "T264")
    protected BigDecimal t264;
    @XmlElement(name = "T265")
    protected BigDecimal t265;
    @XmlElement(name = "T267")
    protected BigDecimal t267;
    @XmlElement(name = "T268")
    protected BigDecimal t268;
    @XmlElement(name = "T269")
    protected BigDecimal t269;
    @XmlElement(name = "T271")
    protected BigDecimal t271;
    @XmlElement(name = "T272")
    protected BigDecimal t272;
    @XmlElement(name = "T273")
    protected BigDecimal t273;
    @XmlElement(name = "T275")
    protected BigDecimal t275;
    @XmlElement(name = "T276")
    protected BigDecimal t276;
    @XmlElement(name = "T277")
    protected BigDecimal t277;
    @XmlElement(name = "T278")
    protected BigDecimal t278;
    @XmlElement(name = "T279")
    protected BigDecimal t279;
    @XmlElement(name = "T280")
    protected BigDecimal t280;

    /**
     * Gets the value of the t258 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getT258() {
        return t258;
    }

    /**
     * Sets the value of the t258 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setT258(BigDecimal value) {
        this.t258 = value;
    }

    /**
     * Gets the value of the t259 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getT259() {
        return t259;
    }

    /**
     * Sets the value of the t259 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setT259(BigDecimal value) {
        this.t259 = value;
    }

    /**
     * Gets the value of the t260 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getT260() {
        return t260;
    }

    /**
     * Sets the value of the t260 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setT260(BigDecimal value) {
        this.t260 = value;
    }

    /**
     * Gets the value of the t262 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getT262() {
        return t262;
    }

    /**
     * Sets the value of the t262 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setT262(BigDecimal value) {
        this.t262 = value;
    }

    /**
     * Gets the value of the t263 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getT263() {
        return t263;
    }

    /**
     * Sets the value of the t263 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setT263(BigDecimal value) {
        this.t263 = value;
    }

    /**
     * Gets the value of the t264 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getT264() {
        return t264;
    }

    /**
     * Sets the value of the t264 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setT264(BigDecimal value) {
        this.t264 = value;
    }

    /**
     * Gets the value of the t265 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getT265() {
        return t265;
    }

    /**
     * Sets the value of the t265 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setT265(BigDecimal value) {
        this.t265 = value;
    }

    /**
     * Gets the value of the t267 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getT267() {
        return t267;
    }

    /**
     * Sets the value of the t267 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setT267(BigDecimal value) {
        this.t267 = value;
    }

    /**
     * Gets the value of the t268 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getT268() {
        return t268;
    }

    /**
     * Sets the value of the t268 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setT268(BigDecimal value) {
        this.t268 = value;
    }

    /**
     * Gets the value of the t269 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getT269() {
        return t269;
    }

    /**
     * Sets the value of the t269 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setT269(BigDecimal value) {
        this.t269 = value;
    }

    /**
     * Gets the value of the t271 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getT271() {
        return t271;
    }

    /**
     * Sets the value of the t271 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setT271(BigDecimal value) {
        this.t271 = value;
    }

    /**
     * Gets the value of the t272 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getT272() {
        return t272;
    }

    /**
     * Sets the value of the t272 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setT272(BigDecimal value) {
        this.t272 = value;
    }

    /**
     * Gets the value of the t273 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getT273() {
        return t273;
    }

    /**
     * Sets the value of the t273 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setT273(BigDecimal value) {
        this.t273 = value;
    }

    /**
     * Gets the value of the t275 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getT275() {
        return t275;
    }

    /**
     * Sets the value of the t275 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setT275(BigDecimal value) {
        this.t275 = value;
    }

    /**
     * Gets the value of the t276 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getT276() {
        return t276;
    }

    /**
     * Sets the value of the t276 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setT276(BigDecimal value) {
        this.t276 = value;
    }

    /**
     * Gets the value of the t277 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getT277() {
        return t277;
    }

    /**
     * Sets the value of the t277 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setT277(BigDecimal value) {
        this.t277 = value;
    }

    /**
     * Gets the value of the t278 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getT278() {
        return t278;
    }

    /**
     * Sets the value of the t278 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setT278(BigDecimal value) {
        this.t278 = value;
    }

    /**
     * Gets the value of the t279 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getT279() {
        return t279;
    }

    /**
     * Sets the value of the t279 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setT279(BigDecimal value) {
        this.t279 = value;
    }

    /**
     * Gets the value of the t280 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getT280() {
        return t280;
    }

    /**
     * Sets the value of the t280 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setT280(BigDecimal value) {
        this.t280 = value;
    }

}
