//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.10 at 04:04:50 PM CEST 
//


package com.esferalia.aon.occam.impl.jooq.dao.mod200_2015.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tipo_BalanceAseguradora complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tipo_BalanceAseguradora">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Pagina32" type="{}tipo_Pagina32" minOccurs="0"/>
 *         &lt;element name="Pagina33" type="{}tipo_Pagina33" minOccurs="0"/>
 *         &lt;element name="Pagina34" type="{}tipo_Pagina34" minOccurs="0"/>
 *         &lt;element name="Pagina35" type="{}tipo_Pagina35" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tipo_BalanceAseguradora", propOrder = {
    "pagina32",
    "pagina33",
    "pagina34",
    "pagina35"
})
public class TipoBalanceAseguradora {

    @XmlElement(name = "Pagina32")
    protected TipoPagina32 pagina32;
    @XmlElement(name = "Pagina33")
    protected TipoPagina33 pagina33;
    @XmlElement(name = "Pagina34")
    protected TipoPagina34 pagina34;
    @XmlElement(name = "Pagina35")
    protected TipoPagina35 pagina35;

    /**
     * Gets the value of the pagina32 property.
     * 
     * @return
     *     possible object is
     *     {@link TipoPagina32 }
     *     
     */
    public TipoPagina32 getPagina32() {
        return pagina32;
    }

    /**
     * Sets the value of the pagina32 property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoPagina32 }
     *     
     */
    public void setPagina32(TipoPagina32 value) {
        this.pagina32 = value;
    }

    /**
     * Gets the value of the pagina33 property.
     * 
     * @return
     *     possible object is
     *     {@link TipoPagina33 }
     *     
     */
    public TipoPagina33 getPagina33() {
        return pagina33;
    }

    /**
     * Sets the value of the pagina33 property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoPagina33 }
     *     
     */
    public void setPagina33(TipoPagina33 value) {
        this.pagina33 = value;
    }

    /**
     * Gets the value of the pagina34 property.
     * 
     * @return
     *     possible object is
     *     {@link TipoPagina34 }
     *     
     */
    public TipoPagina34 getPagina34() {
        return pagina34;
    }

    /**
     * Sets the value of the pagina34 property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoPagina34 }
     *     
     */
    public void setPagina34(TipoPagina34 value) {
        this.pagina34 = value;
    }

    /**
     * Gets the value of the pagina35 property.
     * 
     * @return
     *     possible object is
     *     {@link TipoPagina35 }
     *     
     */
    public TipoPagina35 getPagina35() {
        return pagina35;
    }

    /**
     * Sets the value of the pagina35 property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoPagina35 }
     *     
     */
    public void setPagina35(TipoPagina35 value) {
        this.pagina35 = value;
    }

}
