//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.10 at 04:04:50 PM CEST 
//


package com.esferalia.aon.occam.impl.jooq.dao.mod200_2015.jaxb;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tipo_Pagina31 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tipo_Pagina31">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="T287" type="{}tipo_ImpNegativo" minOccurs="0"/>
 *         &lt;element name="T288" type="{}tipo_ImpNegativo" minOccurs="0"/>
 *         &lt;element name="T290" type="{}tipo_ImpNegativo" minOccurs="0"/>
 *         &lt;element name="T297" type="{}tipo_ImpNegativo" minOccurs="0"/>
 *         &lt;element name="T298" type="{}tipo_ImpNegativo" minOccurs="0"/>
 *         &lt;element name="T300" type="{}tipo_ImpNegativo" minOccurs="0"/>
 *         &lt;element name="T307" type="{}tipo_ImpNegativo" minOccurs="0"/>
 *         &lt;element name="T308" type="{}tipo_ImpNegativo" minOccurs="0"/>
 *         &lt;element name="T310" type="{}tipo_ImpNegativo" minOccurs="0"/>
 *         &lt;element name="T327" type="{}tipo_ImpNegativo" minOccurs="0"/>
 *         &lt;element name="T328" type="{}tipo_ImpNegativo" minOccurs="0"/>
 *         &lt;element name="T330" type="{}tipo_ImpNegativo" minOccurs="0"/>
 *         &lt;element name="T347" type="{}tipo_ImpNegativo" minOccurs="0"/>
 *         &lt;element name="T348" type="{}tipo_ImpNegativo" minOccurs="0"/>
 *         &lt;element name="T350" type="{}tipo_ImpNegativo" minOccurs="0"/>
 *         &lt;element name="T357" type="{}tipo_ImpNegativo" minOccurs="0"/>
 *         &lt;element name="T358" type="{}tipo_ImpNegativo" minOccurs="0"/>
 *         &lt;element name="T360" type="{}tipo_ImpNegativo" minOccurs="0"/>
 *         &lt;element name="T367" type="{}tipo_ImpNegativo" minOccurs="0"/>
 *         &lt;element name="T368" type="{}tipo_ImpNegativo" minOccurs="0"/>
 *         &lt;element name="T370" type="{}tipo_ImpNegativo" minOccurs="0"/>
 *         &lt;element name="T377" type="{}tipo_ImpNegativo" minOccurs="0"/>
 *         &lt;element name="T378" type="{}tipo_ImpNegativo" minOccurs="0"/>
 *         &lt;element name="T380" type="{}tipo_ImpNegativo" minOccurs="0"/>
 *         &lt;element name="T387" type="{}tipo_ImpNegativo" minOccurs="0"/>
 *         &lt;element name="T388" type="{}tipo_ImpNegativo" minOccurs="0"/>
 *         &lt;element name="T390" type="{}tipo_ImpNegativo" minOccurs="0"/>
 *         &lt;element name="T397" type="{}tipo_ImpNegativo" minOccurs="0"/>
 *         &lt;element name="T398" type="{}tipo_ImpNegativo" minOccurs="0"/>
 *         &lt;element name="T400" type="{}tipo_ImpNegativo" minOccurs="0"/>
 *         &lt;element name="T407" type="{}tipo_ImpNegativo" minOccurs="0"/>
 *         &lt;element name="T408" type="{}tipo_ImpNegativo" minOccurs="0"/>
 *         &lt;element name="T410" type="{}tipo_ImpNegativo" minOccurs="0"/>
 *         &lt;element name="T417" type="{}tipo_ImpNegativo" minOccurs="0"/>
 *         &lt;element name="T418" type="{}tipo_ImpNegativo" minOccurs="0"/>
 *         &lt;element name="T420" type="{}tipo_ImpNegativo" minOccurs="0"/>
 *         &lt;element name="T427" type="{}tipo_ImpNegativo" minOccurs="0"/>
 *         &lt;element name="T428" type="{}tipo_ImpNegativo" minOccurs="0"/>
 *         &lt;element name="T430" type="{}tipo_ImpNegativo" minOccurs="0"/>
 *         &lt;element name="T437" type="{}tipo_ImpNegativo" minOccurs="0"/>
 *         &lt;element name="T438" type="{}tipo_ImpNegativo" minOccurs="0"/>
 *         &lt;element name="T440" type="{}tipo_ImpNegativo" minOccurs="0"/>
 *         &lt;element name="T447" type="{}tipo_ImpNegativo" minOccurs="0"/>
 *         &lt;element name="T448" type="{}tipo_ImpNegativo" minOccurs="0"/>
 *         &lt;element name="T450" type="{}tipo_ImpNegativo" minOccurs="0"/>
 *         &lt;element name="T457" type="{}tipo_ImpNegativo" minOccurs="0"/>
 *         &lt;element name="T458" type="{}tipo_ImpNegativo" minOccurs="0"/>
 *         &lt;element name="T460" type="{}tipo_ImpNegativo" minOccurs="0"/>
 *         &lt;element name="T467" type="{}tipo_ImpNegativo" minOccurs="0"/>
 *         &lt;element name="T468" type="{}tipo_ImpNegativo" minOccurs="0"/>
 *         &lt;element name="T470" type="{}tipo_ImpNegativo" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tipo_Pagina31", propOrder = {
    "t287",
    "t288",
    "t290",
    "t297",
    "t298",
    "t300",
    "t307",
    "t308",
    "t310",
    "t327",
    "t328",
    "t330",
    "t347",
    "t348",
    "t350",
    "t357",
    "t358",
    "t360",
    "t367",
    "t368",
    "t370",
    "t377",
    "t378",
    "t380",
    "t387",
    "t388",
    "t390",
    "t397",
    "t398",
    "t400",
    "t407",
    "t408",
    "t410",
    "t417",
    "t418",
    "t420",
    "t427",
    "t428",
    "t430",
    "t437",
    "t438",
    "t440",
    "t447",
    "t448",
    "t450",
    "t457",
    "t458",
    "t460",
    "t467",
    "t468",
    "t470"
})
public class TipoPagina31 {

    @XmlElement(name = "T287")
    protected BigDecimal t287;
    @XmlElement(name = "T288")
    protected BigDecimal t288;
    @XmlElement(name = "T290")
    protected BigDecimal t290;
    @XmlElement(name = "T297")
    protected BigDecimal t297;
    @XmlElement(name = "T298")
    protected BigDecimal t298;
    @XmlElement(name = "T300")
    protected BigDecimal t300;
    @XmlElement(name = "T307")
    protected BigDecimal t307;
    @XmlElement(name = "T308")
    protected BigDecimal t308;
    @XmlElement(name = "T310")
    protected BigDecimal t310;
    @XmlElement(name = "T327")
    protected BigDecimal t327;
    @XmlElement(name = "T328")
    protected BigDecimal t328;
    @XmlElement(name = "T330")
    protected BigDecimal t330;
    @XmlElement(name = "T347")
    protected BigDecimal t347;
    @XmlElement(name = "T348")
    protected BigDecimal t348;
    @XmlElement(name = "T350")
    protected BigDecimal t350;
    @XmlElement(name = "T357")
    protected BigDecimal t357;
    @XmlElement(name = "T358")
    protected BigDecimal t358;
    @XmlElement(name = "T360")
    protected BigDecimal t360;
    @XmlElement(name = "T367")
    protected BigDecimal t367;
    @XmlElement(name = "T368")
    protected BigDecimal t368;
    @XmlElement(name = "T370")
    protected BigDecimal t370;
    @XmlElement(name = "T377")
    protected BigDecimal t377;
    @XmlElement(name = "T378")
    protected BigDecimal t378;
    @XmlElement(name = "T380")
    protected BigDecimal t380;
    @XmlElement(name = "T387")
    protected BigDecimal t387;
    @XmlElement(name = "T388")
    protected BigDecimal t388;
    @XmlElement(name = "T390")
    protected BigDecimal t390;
    @XmlElement(name = "T397")
    protected BigDecimal t397;
    @XmlElement(name = "T398")
    protected BigDecimal t398;
    @XmlElement(name = "T400")
    protected BigDecimal t400;
    @XmlElement(name = "T407")
    protected BigDecimal t407;
    @XmlElement(name = "T408")
    protected BigDecimal t408;
    @XmlElement(name = "T410")
    protected BigDecimal t410;
    @XmlElement(name = "T417")
    protected BigDecimal t417;
    @XmlElement(name = "T418")
    protected BigDecimal t418;
    @XmlElement(name = "T420")
    protected BigDecimal t420;
    @XmlElement(name = "T427")
    protected BigDecimal t427;
    @XmlElement(name = "T428")
    protected BigDecimal t428;
    @XmlElement(name = "T430")
    protected BigDecimal t430;
    @XmlElement(name = "T437")
    protected BigDecimal t437;
    @XmlElement(name = "T438")
    protected BigDecimal t438;
    @XmlElement(name = "T440")
    protected BigDecimal t440;
    @XmlElement(name = "T447")
    protected BigDecimal t447;
    @XmlElement(name = "T448")
    protected BigDecimal t448;
    @XmlElement(name = "T450")
    protected BigDecimal t450;
    @XmlElement(name = "T457")
    protected BigDecimal t457;
    @XmlElement(name = "T458")
    protected BigDecimal t458;
    @XmlElement(name = "T460")
    protected BigDecimal t460;
    @XmlElement(name = "T467")
    protected BigDecimal t467;
    @XmlElement(name = "T468")
    protected BigDecimal t468;
    @XmlElement(name = "T470")
    protected BigDecimal t470;

    /**
     * Gets the value of the t287 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getT287() {
        return t287;
    }

    /**
     * Sets the value of the t287 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setT287(BigDecimal value) {
        this.t287 = value;
    }

    /**
     * Gets the value of the t288 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getT288() {
        return t288;
    }

    /**
     * Sets the value of the t288 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setT288(BigDecimal value) {
        this.t288 = value;
    }

    /**
     * Gets the value of the t290 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getT290() {
        return t290;
    }

    /**
     * Sets the value of the t290 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setT290(BigDecimal value) {
        this.t290 = value;
    }

    /**
     * Gets the value of the t297 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getT297() {
        return t297;
    }

    /**
     * Sets the value of the t297 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setT297(BigDecimal value) {
        this.t297 = value;
    }

    /**
     * Gets the value of the t298 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getT298() {
        return t298;
    }

    /**
     * Sets the value of the t298 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setT298(BigDecimal value) {
        this.t298 = value;
    }

    /**
     * Gets the value of the t300 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getT300() {
        return t300;
    }

    /**
     * Sets the value of the t300 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setT300(BigDecimal value) {
        this.t300 = value;
    }

    /**
     * Gets the value of the t307 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getT307() {
        return t307;
    }

    /**
     * Sets the value of the t307 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setT307(BigDecimal value) {
        this.t307 = value;
    }

    /**
     * Gets the value of the t308 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getT308() {
        return t308;
    }

    /**
     * Sets the value of the t308 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setT308(BigDecimal value) {
        this.t308 = value;
    }

    /**
     * Gets the value of the t310 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getT310() {
        return t310;
    }

    /**
     * Sets the value of the t310 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setT310(BigDecimal value) {
        this.t310 = value;
    }

    /**
     * Gets the value of the t327 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getT327() {
        return t327;
    }

    /**
     * Sets the value of the t327 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setT327(BigDecimal value) {
        this.t327 = value;
    }

    /**
     * Gets the value of the t328 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getT328() {
        return t328;
    }

    /**
     * Sets the value of the t328 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setT328(BigDecimal value) {
        this.t328 = value;
    }

    /**
     * Gets the value of the t330 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getT330() {
        return t330;
    }

    /**
     * Sets the value of the t330 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setT330(BigDecimal value) {
        this.t330 = value;
    }

    /**
     * Gets the value of the t347 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getT347() {
        return t347;
    }

    /**
     * Sets the value of the t347 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setT347(BigDecimal value) {
        this.t347 = value;
    }

    /**
     * Gets the value of the t348 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getT348() {
        return t348;
    }

    /**
     * Sets the value of the t348 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setT348(BigDecimal value) {
        this.t348 = value;
    }

    /**
     * Gets the value of the t350 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getT350() {
        return t350;
    }

    /**
     * Sets the value of the t350 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setT350(BigDecimal value) {
        this.t350 = value;
    }

    /**
     * Gets the value of the t357 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getT357() {
        return t357;
    }

    /**
     * Sets the value of the t357 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setT357(BigDecimal value) {
        this.t357 = value;
    }

    /**
     * Gets the value of the t358 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getT358() {
        return t358;
    }

    /**
     * Sets the value of the t358 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setT358(BigDecimal value) {
        this.t358 = value;
    }

    /**
     * Gets the value of the t360 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getT360() {
        return t360;
    }

    /**
     * Sets the value of the t360 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setT360(BigDecimal value) {
        this.t360 = value;
    }

    /**
     * Gets the value of the t367 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getT367() {
        return t367;
    }

    /**
     * Sets the value of the t367 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setT367(BigDecimal value) {
        this.t367 = value;
    }

    /**
     * Gets the value of the t368 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getT368() {
        return t368;
    }

    /**
     * Sets the value of the t368 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setT368(BigDecimal value) {
        this.t368 = value;
    }

    /**
     * Gets the value of the t370 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getT370() {
        return t370;
    }

    /**
     * Sets the value of the t370 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setT370(BigDecimal value) {
        this.t370 = value;
    }

    /**
     * Gets the value of the t377 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getT377() {
        return t377;
    }

    /**
     * Sets the value of the t377 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setT377(BigDecimal value) {
        this.t377 = value;
    }

    /**
     * Gets the value of the t378 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getT378() {
        return t378;
    }

    /**
     * Sets the value of the t378 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setT378(BigDecimal value) {
        this.t378 = value;
    }

    /**
     * Gets the value of the t380 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getT380() {
        return t380;
    }

    /**
     * Sets the value of the t380 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setT380(BigDecimal value) {
        this.t380 = value;
    }

    /**
     * Gets the value of the t387 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getT387() {
        return t387;
    }

    /**
     * Sets the value of the t387 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setT387(BigDecimal value) {
        this.t387 = value;
    }

    /**
     * Gets the value of the t388 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getT388() {
        return t388;
    }

    /**
     * Sets the value of the t388 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setT388(BigDecimal value) {
        this.t388 = value;
    }

    /**
     * Gets the value of the t390 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getT390() {
        return t390;
    }

    /**
     * Sets the value of the t390 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setT390(BigDecimal value) {
        this.t390 = value;
    }

    /**
     * Gets the value of the t397 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getT397() {
        return t397;
    }

    /**
     * Sets the value of the t397 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setT397(BigDecimal value) {
        this.t397 = value;
    }

    /**
     * Gets the value of the t398 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getT398() {
        return t398;
    }

    /**
     * Sets the value of the t398 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setT398(BigDecimal value) {
        this.t398 = value;
    }

    /**
     * Gets the value of the t400 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getT400() {
        return t400;
    }

    /**
     * Sets the value of the t400 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setT400(BigDecimal value) {
        this.t400 = value;
    }

    /**
     * Gets the value of the t407 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getT407() {
        return t407;
    }

    /**
     * Sets the value of the t407 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setT407(BigDecimal value) {
        this.t407 = value;
    }

    /**
     * Gets the value of the t408 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getT408() {
        return t408;
    }

    /**
     * Sets the value of the t408 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setT408(BigDecimal value) {
        this.t408 = value;
    }

    /**
     * Gets the value of the t410 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getT410() {
        return t410;
    }

    /**
     * Sets the value of the t410 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setT410(BigDecimal value) {
        this.t410 = value;
    }

    /**
     * Gets the value of the t417 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getT417() {
        return t417;
    }

    /**
     * Sets the value of the t417 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setT417(BigDecimal value) {
        this.t417 = value;
    }

    /**
     * Gets the value of the t418 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getT418() {
        return t418;
    }

    /**
     * Sets the value of the t418 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setT418(BigDecimal value) {
        this.t418 = value;
    }

    /**
     * Gets the value of the t420 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getT420() {
        return t420;
    }

    /**
     * Sets the value of the t420 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setT420(BigDecimal value) {
        this.t420 = value;
    }

    /**
     * Gets the value of the t427 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getT427() {
        return t427;
    }

    /**
     * Sets the value of the t427 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setT427(BigDecimal value) {
        this.t427 = value;
    }

    /**
     * Gets the value of the t428 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getT428() {
        return t428;
    }

    /**
     * Sets the value of the t428 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setT428(BigDecimal value) {
        this.t428 = value;
    }

    /**
     * Gets the value of the t430 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getT430() {
        return t430;
    }

    /**
     * Sets the value of the t430 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setT430(BigDecimal value) {
        this.t430 = value;
    }

    /**
     * Gets the value of the t437 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getT437() {
        return t437;
    }

    /**
     * Sets the value of the t437 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setT437(BigDecimal value) {
        this.t437 = value;
    }

    /**
     * Gets the value of the t438 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getT438() {
        return t438;
    }

    /**
     * Sets the value of the t438 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setT438(BigDecimal value) {
        this.t438 = value;
    }

    /**
     * Gets the value of the t440 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getT440() {
        return t440;
    }

    /**
     * Sets the value of the t440 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setT440(BigDecimal value) {
        this.t440 = value;
    }

    /**
     * Gets the value of the t447 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getT447() {
        return t447;
    }

    /**
     * Sets the value of the t447 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setT447(BigDecimal value) {
        this.t447 = value;
    }

    /**
     * Gets the value of the t448 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getT448() {
        return t448;
    }

    /**
     * Sets the value of the t448 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setT448(BigDecimal value) {
        this.t448 = value;
    }

    /**
     * Gets the value of the t450 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getT450() {
        return t450;
    }

    /**
     * Sets the value of the t450 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setT450(BigDecimal value) {
        this.t450 = value;
    }

    /**
     * Gets the value of the t457 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getT457() {
        return t457;
    }

    /**
     * Sets the value of the t457 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setT457(BigDecimal value) {
        this.t457 = value;
    }

    /**
     * Gets the value of the t458 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getT458() {
        return t458;
    }

    /**
     * Sets the value of the t458 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setT458(BigDecimal value) {
        this.t458 = value;
    }

    /**
     * Gets the value of the t460 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getT460() {
        return t460;
    }

    /**
     * Sets the value of the t460 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setT460(BigDecimal value) {
        this.t460 = value;
    }

    /**
     * Gets the value of the t467 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getT467() {
        return t467;
    }

    /**
     * Sets the value of the t467 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setT467(BigDecimal value) {
        this.t467 = value;
    }

    /**
     * Gets the value of the t468 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getT468() {
        return t468;
    }

    /**
     * Sets the value of the t468 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setT468(BigDecimal value) {
        this.t468 = value;
    }

    /**
     * Gets the value of the t470 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getT470() {
        return t470;
    }

    /**
     * Sets the value of the t470 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setT470(BigDecimal value) {
        this.t470 = value;
    }

}
