#!/bin/sh  


function link(){
        LIBRARY=$1;
        JAR=$(find /usr/share/java -name "${LIBRARY}-*.jar");
        [ ! -z $JAR  ] && ln -sf $JAR /usr/share/java/${LIBRARY}.jar ;
}


link aon-dbutils
